### ISSUE TITLE
Please provide more liberal payment options

### ISSUE THREAD

**Issue by Hubbitus** [archimatetool/archi#1003]
First, very thank you for the great product.
You are doing the great job.

Meantime, you are using patreon.com for the donations, and it does not accept for example Russian bank cards (and PayPal too).

Please add some other donation methods said cryptocurrency or more liberal systems like https://payeer.com.

**Comment by Phillipus** [comment]
Thanks for your suggestion, I'll take a look at it!

**Comment by startsevsa** [comment]
> Thanks for your suggestion, I'll take a look at it!

Hello!
What was a solution - paypal button on a site, or a payeer.com account?

**Comment by Phillipus** [comment]
PayPal and Patreon are the options at the moment - https://www.archimatetool.com/donate/

**Comment by Hubbitus** [comment]
Sorry, you are closing issue as completed, but still accept only patreon and PayPal? Am I wrong, but all is in initial state?
