### ISSUE TITLE
Feature Request: Add capability to "join/combine" two or more identical element types

### ISSUE THREAD

**Issue by kirkpabk** [archimatetool/archi#1009]
The idea is to provide the ability to combine multiple elements of the same type (only unspecialized, unless both are specialized the same), wherein the duplicate properties of the first selected (listed) item is favored over duplicates of other selections.  An option may be to allow duplicate properties to be copied (but could get messy).  But this option, especially in the Validator tab, would be extremely helpful and support quicker resolution on large models without having to recreate links and other activities across multiple models. 

Could save immense amounts of time and be a great right-click option in many tabs.

**Comment by jbsarrodie** [comment]
This can already be done using a jArchi script. I shared a script for that some years ago: https://gist.github.com/jbsarrodie/80a7bae59fb0469ab334ff13f7d6b5f9

**Comment by kirkpabk** [comment]
Just found that--was gonna post the same link for others and close!  Thanks a bunch.  Happy holidays.
