### ISSUE TITLE
Add "Distribute" functionality to Archi

### ISSUE THREAD

**Issue by rvaneerd** [archimatetool/archi#1010]
Hi there,

I'm rather new to Archi and trying to document some architecture views to be used within our company.
While doing so I often have to reposition elements to make it look good and logical.
I already found the "position" functions to align and size the elements but what I cannot seem to find is some functionality to distribute some elements evenly in between the outer ones.

So given the current situation:
![image](https://github.com/archimatetool/archi/assets/4356502/347d725c-1eda-43b3-a85b-dae47ca9ea36)
I would like to be able to distribute the objects evenly into the following:
![image](https://github.com/archimatetool/archi/assets/4356502/84f689db-ce58-42d9-8b62-8c72f9e827ad)

Obviously for just three objects, this is quite easy but when having more elements to be handled, a "distribute" functionality (either horizontally or vertically) would be very useful.

Could you please consider adding this functionality?

Regards,
Rob

**Comment by Phillipus** [comment]
A valid request, but we already have it [here ](https://github.com/archimatetool/archi/issues/189)so I'll close this one.
