### ISSUE TITLE
Feature request HTML report

### ISSUE THREAD

**Issue by ebrongers** [archimatetool/archi#1013]
In HTML report:

It would be nice to see the properties of a relation when the relation is selected in the HTML report view.

**Comment by jbsarrodie** [comment]
Actually, this is how it already work today. Simply clic on the name of a relation in the relationships tab (not on the view image).

**Comment by ebrongers** [comment]
Dear Jean-Baptiste,

In archimate it is correct, but in the HTML report the properties are not shown.

Example below is in Edge. When I click on the name of the relation Flow, properties are not shown.

Kind regards

[Afbeelding met tekst, schermopname, software, Computerpictogram  Automatisch gegenereerde beschrijving]

Van: Jean-Baptiste Sarrodie ***@***.***>
Verzonden: donderdag 11 januari 2024 10:50
Aan: archimatetool/archi ***@***.***>
CC: Eric Brongers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [archimatetool/archi] Feature request HTML report (Issue #1013)


Actually, this is how it already work today. Simply clic on the name of a relation in the relationships tab (not on the view image).

**Comment by Phillipus** [comment]
As @jbsarrodie says, the way to do this is to select the relation in the Model Tree section of the report and the Properties are shown in the lower-left tab. Clicking and selecting a relation on the diagram view is [not possible](https://github.com/archimatetool/archi/issues/376).

**Comment by Phillipus** [comment]
@ebrongers If you reply to a GitHub issue using email, attachments are not included. Please use the GitHub web interface to reply with steps to reproduce your issue.

**Comment by ebrongers** [comment]
Hi Phil,

Yes, I found it.

But it would also be nice to show the properties if the name in the view is selected. Same as it does when a device is selected.

Van: Phil Beauvoir ***@***.***>
Verzonden: donderdag 11 januari 2024 10:55
Aan: archimatetool/archi ***@***.***>
CC: Eric Brongers ***@***.***>; Author ***@***.***>
Onderwerp: Re: [archimatetool/archi] Feature request HTML report (Issue #1013)


As @jbsarrodie<https://github.com/jbsarrodie> says, the way to do this is to select the relation in the Model Tree section of the report and the Properties are shown in the lower-left tab. Clicking and selecting a relation on the diagram view is not possible<https://github.com/archimatetool/archi/issues/376>.

**Comment by Phillipus** [comment]
> But it would also be nice to show the properties if the name in the view is selected. Same as it does when a device is selected.

Yes, we are aware of this. See https://github.com/archimatetool/archi/issues/376

**Comment by jbsarrodie** [comment]
> In archimate it is correct, but in the HTML report the properties are not shown. Example below is in Edge. When I click on the name of the relation Flow, properties are not shown.

As I said, you have to clic on the relationship name in the list of relationships, not the diagram:
<img width="1629" alt="Capture d’écran 2024-01-11 à 11 02 04" src="https://github.com/archimatetool/archi/assets/5757396/0741909d-44ba-4935-981d-c38979513d05">

**Comment by ebrongers** [comment]
@Phillipus Phillipus perfect thank you

**Comment by Phillipus** [comment]
As we already have https://github.com/archimatetool/archi/issues/376, I'll close this one.
