### ISSUE TITLE
.lock - ransomware (false-positive)?

### ISSUE THREAD

**Issue by N3wScr1pt** [archimatetool/archi#1016]
Hello,

We recently had a request to have your software utilized for XML modeling with Abacus, however, as part of our analysis and scanning process a file was flagged as ransomware. (see attached)

We contacted support via the Contact's page on your website and they replied stating that it was a false-positive and that the file was of "zero-byte / zero length". Nonetheless we have refrained from using this software until we can receive a solid confirmation that the scan was in fact a false-positive. 

We used the x64 install with SHA-1 > bb71df085ef3522bc379529a785a69064b9f7b27    Archi-Win64-Setup-5.2.0.exe.

We like to gain confidence in utilizing this software and would like for the scan conducted by Cuckoo to result with no ransomware flag. Might there anything that can be done to reassure no such ransomware exists in your software? 

V/R - Alex

![faslsePos_ransomware_detected](https://github.com/archimatetool/archi/assets/87826159/8c921240-eb95-43f9-804c-50c79ed881f8)

**Comment by Phillipus** [comment]
As I said, that file is a zero length byte that is part of the installation of the underlying Eclipse framework. It's a lock file. It's empty, it does nothing. It's not even used.

I suggest you contact Cuckoo.

**Comment by N3wScr1pt** [comment]
Appreciate the reply and clarification.


On Jan 18, 2024, at 1:39 AM, Phil Beauvoir ***@***.***> wrote:

﻿

As I said, that file is a zero length byte that is part of the installation of the underlying Eclipse framework. It's a lock file. It's empty, it does nothing. It's not even used.

I suggest you contact Cuckoo.
