### ISSUE TITLE
Validator and nested elements

### ISSUE THREAD

**Issue by romualdrichard** [archimatetool/archi#1017]
### Version of Archi
5.2

### Archi Plug-ins
N/A

### Operating System
Windows

### Expected Behaviour
Having two elments with relations. One is a nested relation (Composition) and other just a relation. If you nested the elements, validator is ok.

### Actual Behaviour
Having two elments with relations. One is a nested relation (Composition) and other just a relation. If you nested the elements, validator is saying that ther is no nesting relation

### Steps to Reproduce the Behaviour
1. see figure to get the same model
2. nest applicaiton B in application A
3.Check with validator
![Capture d’écran 2024-01-24 133257](https://github.com/archimatetool/archi/assets/48156053/109b58e2-bea9-4619-9bad-cb71c9518d1a)
![Capture d’écran 2024-01-24 133511](https://github.com/archimatetool/archi/assets/48156053/8c5d4559-801e-4ed8-9088-f599832b740f)

**Comment by romualdrichard** [comment]
Yes, its just confusing since there is a real nested relation.

**Comment by Phillipus** [comment]
That's the way it works. If there is a non-nestable relationship, it lists it in the Validator. You can simply ignore the warning.
