### ISSUE TITLE
[Mac] Crash to desktop when Cmd-Z pressed in text control

### ISSUE THREAD

**Issue by rxcolvin** [archimatetool/archi#1018]
Happens randomly: actual state is lost, due to crash

### Version of Archi

5.2.0

### Archi Plug-ins

jArchi, coArchi

### Operating System

Macos 13.6.1

### Expected Behaviour

When I select undo the program should not crash

### Actual Behaviour

Very occasionally after selecting undo archi crashes - log attached

### Steps to Reproduce the Behaviour
1. No specific steps - just when undo is selected - happens infrequently, at random (seemingly)
2.
3.
[archi-crash.txt](https://github.com/archimatetool/archi/files/14086279/archi-crash.txt)
[archi-error-log.txt](https://github.com/archimatetool/archi/files/14086438/archi-error-log.txt)

**Comment by Phillipus** [comment]
This happens to me randomly, too. It can happen on a Mac when editing text in a diagram object ("direct edit") and hitting the Undo shortcut key (Command Z)  a few times. There's no way to reproduce this exactly and also I can't fix it as it's either an Eclipse or Mac bug.

[hs_err_pid3917.log](https://github.com/user-attachments/files/15765958/hs_err_pid3917.log)

**Comment by rxcolvin** [comment]
👍 👍

**Comment by Phillipus** [comment]
This will be fixed in Archi 5.4.0 (beta is available now).
