### ISSUE TITLE
feature request: reverse nesting

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1020]
When diagrams are created top-to-bottom - by placing top-level elements first and then, if nesting relationship is necessary, placing low-level elements on top, nesting relationship prompt pops up automatically, but when the order is reversed - probably not the best practice but it sometimes happens, creation of nesting relationships becomes clumsy - placing a large element over or under others does noting and one has to create relationships manually or jiggle nested elements to be prompted. It would be nice if prompt for nesting relationships will pop up automatically if a larger element is slid under other elements the same way it does when smaller elements are placed on top of a larger element.

**Comment by Phillipus** [comment]
Sorry, but this is not going to change. The nesting pop-up is triggered when an element is placed inside of a parent container element. Triggering that action by placing elements under others is not feasible.
