### ISSUE TITLE
Feature request: label expression applied on a view or grouping element

### ISSUE THREAD

**Issue by timconinx** [archimatetool/archi#1021]
I have a label expression which I'd like to apply to all current and future elements of a certain type. Also, when making changes to the expression I'd like to limit my change to one place.

Instead of copy/pasting the expression into the label of all elements, and remembering to do the copy/paste on every new element, could there be a feature where the label expression is defined on a view, or a group, or a folder - and which makes sure that every element under that view/group/folder has that expression applied to it

**Comment by jbsarrodie** [comment]
Hi,

Sorry but such feature is not planned and will most certainly never be added (unless someone is willing to implement it and discuss the details before with us here).

At some point though, default label expression might become part of profiles and specializations, but if done, you won't be able to associate a label expression on a view, group or folder, only profiles and specialization.

So your only realistic solution is to manage it with a jArchi script.

Regards
