### ISSUE TITLE
Winget manifest is incorrect

### ISSUE THREAD

**Issue by JaredSeth** [archimatetool/archi#1022]
### Version of Archi
5.2.0

### Operating System
Windows

### Expected Behaviour
Trying to use winget to install the latest version of Archi

### Actual Behaviour
Installation fails with the error:

An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Steps to Reproduce the Behaviour
Using **winget install ArchiMateTool.Archi**

The issue appears to be that the manifest is pointing to https://www.archimatetool.com/downloads/archi-5.php?/5.2.0/Archi-Win64-Setup-5.2.0.exe but the actual URL for the download is https://www.archimatetool.com/downloads/archi/5.2.0/Archi-Win64-Setup-5.2.0.exe

**Comment by Phillipus** [comment]
Please report this to the winget maintainers. We are not responsible for that. Supported downloads are available at https://www.archimatetool.com/download/

**Comment by JaredSeth** [comment]
Thanks. I've opened up an Issue on the winget-pkgs github.
