### ISSUE TITLE
[Feature request] Having user name in pref

### ISSUE THREAD

**Issue by romualdrichard** [archimatetool/archi#1023]
I want to put a note on my views to tell who changed the view.

For the moment, I use a little script which is setting a property with my name. It's pretty simple.

But... I'd like to be able to have this in Archi since I will not be the only one who will change views.
For the moment my name is hard coded in the script.

If I share the script in a git, no way to have this hard coded.
I though to have the author name like in Word for instance and then use the script to get it as a pref...

**Comment by Phillipus** [comment]
This won't be implemented as this is actually something that could be retrieved from an external configuration or properties file that you could create yourself. In your script you could replace your name with a reference to an entry in the configuration or properties file

**Comment by btk467** [comment]
Too bad. It is closed. 
I too had a trouble finding who last changed my view. 
I had to look into git history which was not easy if the were multiple commits after that change. 

Or I misunderstood the reason for that request.

**Comment by Phillipus** [comment]
> Or I misunderstood the reason for that request.

Yes I think you misunderstood this. Changes in coArchi are only tracked in the History. This request is about retrieving a property which happens to be a name in a jArchi script. This and any other property could be retrieved from a property configuration file.

**Comment by romualdrichard** [comment]
Not exactly, it was to get a property in Archi which contains the name of the user. This propoerty will be avaible to jArchi.
Well, I use the .gitconfig file to get the name of the user in my script which update the view property.
