### ISSUE TITLE
[Feature request ] Prevent duplication when adding properties using New Multiple feature

### ISSUE THREAD

**Issue by aayaffe** [archimatetool/archi#1025]
When using the new multiple feature under the elements properties tab, it will be helpful if there could be a button that enables adding the new properties without the duplicated ones (already existing ones).
Example Usecase:
1. Managing common properties for architectural elements over time.
2. After a while adding new properties.
3. Wanting to add all the new properties to existing elements using New Multiple and Select All.
4. Currently this requires adding all and deleting the duplicates manually. 
5. The requested feature will add a button next to OK button which will essentially add only the non existing properties.

**Comment by Phillipus** [comment]
Hi, yes I can see that would be annoying with lots of properties. The next version of Archi will have this.

![properties_user_dialog1](https://github.com/archimatetool/archi/assets/600504/87bd1579-b3c6-4de6-96a5-5b5e0f1bd8cc)

**Comment by Phillipus** [comment]
Implemented in Archi 5.3
