### ISSUE TITLE
[Feature Request] Expand Canvas Size

### ISSUE THREAD

**Issue by yellek** [archimatetool/archi#1030]
As a user, when I want to place a diagram element outside of the current canvas I would like to see enough space to place the element.

Can we make the canvas x units bigger to the right and bottom of the size needed to contain the current diagram elements so that if an element needs to move to the edges there is already visual space to put it? The size for diagram export should not include this extra space.

My current workaround is to zoom out all the way and put a dummy element far to the bottom and the right so that the canvas is always bigger than I need.

**Comment by Phillipus** [comment]
Unless you can supply a pull request implementing this it won't change as it's part of the Eclipse Graphical Eclipse Framework.
