### ISSUE TITLE
[Feature request] Ability to bind keys for Select in Model Tree

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#1033]
Hello!

Is it possible to add key bindings in preferences for **Select in Model Tree** function?
It could speed up the work significantly in some scenarios.

Thanks a lot!

**Comment by Phillipus** [comment]
Hi, there's a few key bindings that users have asked for, including this one. I'll wait until the next time I implement key bindings and do a few at the same time.

**Comment by davidsara** [comment]
OK, thank you!

**Comment by Phillipus** [comment]
This will be in the next version.
