### ISSUE TITLE
[Feature request] - always show alignment guides

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1034]
When an element is being dragged and is aligned with another element, Archi shows alignment guides (blue lines), but only if these elements are on the same level of nesting. Could it show them regardless of nesting? e.g. for this scenario
![2024-03-14 12_05_12-Archi](https://github.com/archimatetool/archi/assets/11752339/848614c8-07d2-4057-b26e-93105efa7681)

And could it show them for the original position of the element being dragged - when you need to drag it some distance precisely on the horizontal or vertical line?

**Comment by Phillipus** [comment]
The alignment guides are part of the Eclipse Graphical Eclipse Framework (GEF). Thus their behaviour is not something I can change, unless someone is prepared to submit a PR to change it.
