### ISSUE TITLE
Installer for windows 64 does not function on windows 11

### ISSUE THREAD

**Issue by GenioWBR** [archimatetool/archi#1038]
### Version of Archi
 5.3

### Actual Behaviour

You can download the installer file versión, but when you try to install norhing happens. The Zip portable is ok.

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Hi, there have been no reports of problems with the installer, and I just tested it and it's OK. Please try again or from a different Browser.
