### ISSUE TITLE
View scaling without default font (segoe) is broken

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#1039]
### Version of Archi
5.3.0

### Archi Plug-ins
N/A

### Operating System
Windows 11

### Expected Behaviour
Zooming the view page, or exporting the view at greater than 100% with an alternative font should render with the correct font at the correct size.

### Actual Behaviour
Text Boxes are cut off, font is not rendered correctly.

In these examples, the "Business Process" has a font of Segoe, the others are "Roboto Regular"

100% - <img width="382" alt="image" src="https://github.com/archimatetool/archi/assets/2892935/cd748275-37bc-473c-ab73-955a85e2ad9f">
150% - 
<img width="570" alt="image" src="https://github.com/archimatetool/archi/assets/2892935/9cfcf016-17d8-4d0c-b0e4-552e444230e3">

### Steps to Reproduce the Behaviour
1. Change to alternative font (Roboto downloaded from [Google](https://fonts.google.com/specimen/Roboto))
2. Zoom View or Export at > 100%
3. Render is broken

**Comment by Phillipus** [comment]
Hi, I tried to reproduce this using Roboto Regular but it was OK for me. Your `Roboto` font looks different than mine. I'm using the one in `C:\Windows\Fonts\` Could you try a different version of `Roboto`? Having said that, the Eclipse Draw2d framework does have some difficulty rendering some fonts, so you'll have to avoid these.

**Comment by smileham** [comment]
Just tried it with a different version of Roboto from [dafont.com](https://dafont.com/roboto.font) and this time it's even wierder...
<img width="482" alt="image" src="https://github.com/archimatetool/archi/assets/2892935/8f5c6dcb-9659-42c8-aea8-e720d3ce6e8d">
Looks almost like the issue in [974](https://github.com/archimatetool/archi/issues/974)

I'll see if there is another version of Roboto out there...

**Comment by smileham** [comment]
Working now!

<img width="539" alt="image" src="https://github.com/archimatetool/archi/assets/2892935/23804cf6-a560-46e8-98ac-b01944db564f">

Looks like my fonts were installed as a Local user...

Removed them from  %LOCALAPPDATA%\Microsoft\Windows\Fonts\ , installed the fonts for all users to Windows/Fonts, rebooted, and it's happy now!

Cheers
