### ISSUE TITLE
[feature]Shift left/right with Shift+Scrollwheel

### ISSUE THREAD

**Issue by cwknox** [archimatetool/archi#104]
One of my challenges moving between applications such as Visio (and even PDF viewers), and Archi is that Visio and PDF viewers offer a feature to move the view window left and right by pressing the Shift key along with moving the scroll wheel.  Is it possible to do the same in Archi?

**Comment by cwknox** [comment]
I've seen several other features proposed that seemed less useful but generated more interest. Not to ketch, but am I the only person here that uses the Shift-Scroll to move left and right in Visio and Adobe Reader?

**Comment by Phillipus** [comment]
OK. Our focus now is ArchiMate 3.0 support. I'll take a look at this along the way.

**Comment by Phillipus** [comment]
Hi, good news. I just committed the code that allows this. It will be in the next version of Archi later this year. Sorry it took so long.

**Comment by Phillipus** [comment]
I'll close this as it's implemented for next version.

**Comment by cwknox** [comment]
Escellent!  It'll be a usability boost -- at least for me!  Thanks!  And thanks for a useful tool.
