### ISSUE TITLE
Emojis do not renders properly in label properties

### ISSUE THREAD

**Issue by larchenkov** [archimatetool/archi#1041]
### Version of Archi
5.2.0

### Archi Plug-ins
coArchi

### Operating System
MacOs Sonoma 14

### Expected Behaviour
Fully rendered emoji in label properties (works only in element titles)

### Actual Behaviour
<img width="153" alt="image" src="https://github.com/archimatetool/archi/assets/61501977/e56fc59b-ceb2-44b2-a3f7-2691c8f7b261">

### Steps to Reproduce the Behaviour
1. create element
2. add emoji to propery
3. add property to label , you will see partly rendered images

**Comment by Phillipus** [comment]
Yes, they are getting clipped by the `Draw2d` framework that is used to render text. I'm not sure if that's easily fixable.

A workaround is to use a label expression with a line break. For example:

```
${name}
(line break)
```

or:

```
${property:propertykey}
(line break)
```

**Comment by larchenkov** [comment]
Oh, well. Such an easy fix. Well ok. At least we can handle it with line break. Thanks

**Comment by romualdrichard** [comment]
Is there a list of emoji we can use?

**Comment by jbsarrodie** [comment]
> Is there a list of emoji we can use?

You can use any emoji you want (knowing that several, if not most of them, will require you to add a newline to let it uncropped).

**Comment by Phillipus** [comment]
> Such an easy fix

Not easy.

Archi uses a graphical framework [Draw2D](https://github.com/archimatetool/archi/tree/master/org.eclipse.draw2d/src/org/eclipse/draw2d) which is rather old. A text control's height is calculated on the basis of the font's metrics, not on an emoji (which didn't exist when Draw2d was first developed).

**Comment by Phillipus** [comment]
This is Mac only, emojis render OK on Windows.

I opened an issue on the Eclipse repo - https://github.com/eclipse/gef-classic/issues/414

**Comment by Phillipus** [comment]
I'm closing this issue as it's been reported https://github.com/eclipse/gef-classic/issues/414
