### ISSUE TITLE
[Feature Request] Label Expressions - Traversing parents

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#1042]
Hello!

Is it possible to traverse parents using Label Expressions?

I'd like to add information about view name (Context), parent folder name (1 Preliminary) and its parent folder name (PROJ A) to get the project name into label.

![image](https://github.com/archimatetool/archi/assets/20066733/e1c2f6cd-05dd-43eb-8a2d-3d18f7dd01e2)

$ ???
$vfolder{name}
$view{name}

Thank you!
David

**Comment by romualdrichard** [comment]
Hi, not sure that's its possible but :
you can add a property "project" in the "1 Preliminary" which has value "PROJ A" and use it like
$vfolder{property:project}

**Comment by romualdrichard** [comment]
For this, jArchi is your friend, a script which update a property on the selected elements : [https://gist.github.com/davidsara/0bad09ad4d148b9cbef940b54f4df2e3](url)

**Comment by davidsara** [comment]
Thank you, I will try!
