### ISSUE TITLE
Zoom towards cursor

### ISSUE THREAD

**Issue by YurMischenkov** [archimatetool/archi#1046]
Feature request — Zoom towards cursor.

I can see that this question was raised earlier, but closed with reference to the external library which is used and request to the actual change in the code. I may be wrong, but there is a code available for the lib to fix that.

https://github.com/archimatetool/archi/issues/1031 — original feature request
https://github.com/eclipse/gef/commit/a646ad81ce7a7dd4d6758ad1d5b31e9825768b09 — code for the lib to change the behavior to the desired one for the Graphical Eclipse Framework.

I wonder if it is possible to implement the change in Archi, since zooming is a pain in the neck now.

### Version of Archi
5.2.0

### Archi Plug-ins
coArchi, jArchi

### Operating System
Windows

### Expected Behaviour
Zoom towards cursor

### Actual Behaviour
zoom towards canvas center

### Steps to Reproduce the Behaviour
- Ctrl + mouse scroll

**Comment by Phillipus** [comment]
Hi, the example code that you link to is for a completely different version of GEF, so it can't be used. We use GEF 3 (Classic) and I think that any changes would have to be applied here - https://github.com/archimatetool/archi/blob/master/org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomManager.java

If anyone would like to contribute a PR for this please do.

**Comment by Phillipus** [comment]
I'll re-open the original issue and close this one, so we can track it in one place.
