### ISSUE TITLE
XML file is coded

### ISSUE THREAD

**Issue by aayaffe** [archimatetool/archi#1049]
After using archi for a while with the collaboration plugin the xml file was suddenly coded and is somehow not human readable. The oddest part is that archi can still load it. 
The problem is I have been using the xml file to run some BI analysis in power bi and now the file is not readable. 

What could have cause issue? 

### Version of Archi
5.2

### Archi Plug-ins
Coarchi

### Operating System
Windows 10

### Expected Behaviour
Archi XML files are human and machine readable 

### Actual Behaviour
Archi XML file is coded in some way

### Steps to Reproduce the Behaviour
1. Normal usage with archi and coarchi

**Comment by Phillipus** [comment]
Hi, what do you mean by "the file is coded"? Perhaps you mean that it is a binary file? If so, this happens if the model contains an image (.png, .jpg, etc) file. In that case the `.archimate` file is saved as an archive file (zip format) containing the XML file and the image file(s).

**Comment by jbsarrodie** [comment]
Hi. I guess you are not speaking about the small xml files (usually
hundreds or thousands) but the tmp.archimate file you can find locally.
This file is the native Archi format and is an xml file, but if you add
some images in your model, it becomes a zip file containing both the images
and the xml.

**Comment by Phillipus** [comment]
I'll close this one.

**Comment by aayaffe** [comment]
That explains it. 
Thank you!
