### ISSUE TITLE
Wrapped Relationship Labels Overlap

### ISSUE THREAD

**Issue by myriammatwiy** [archimatetool/archi#1056]
View Error Log button is disabled (assuming the error log is empty)

### Version of Archi

Archi Win64 5.1.0 and 5.3.0

### Archi Plug-ins

Collaboration plug-in 0.9.2 installed

### Operating System

Windows 11 Enterprise

### Expected Behaviour
Relationship labels from existing views should remain as-is without wrapping

### Actual Behaviour

Relationship labels from existing views are wrapping which is causing them to overlap onto each other. A configuration setting to shut off automatic wrapping doesn't appear to exist.

### Steps to Reproduce the Behaviour
1. Import existing model created in Archi version 4.9.3
2. Open a view that contains multiple relationships between two elements, and long relationship label expressions
3. Notice that the text on these relationships is now wrapped, causing the text to overlap.

Before (in version 4.9.3):
![BEFORE - relationship text in version 4 9 3](https://github.com/archimatetool/archi/assets/106278290/c0ccd3a8-86ca-4056-89cf-ff012f793e20)

After (in version 5.3.0):
![AFTER - relationship text in version 5 3 0](https://github.com/archimatetool/archi/assets/106278290/f2eef535-8f13-4062-adab-d3d71633b876)

**Comment by Phillipus** [comment]
A maximum label width of 300 pixels was set in this [commit](https://github.com/archimatetool/archi/commit/1fd5f2fc15b58b6cfeb4903551f9670eb88cf568#diff-01b7ac4d12cc5484536988d7c9b9ed5354ae1cef5e3f78dcdfaeb236262683c7). This was set to stop excessively long labels.

**Comment by myriammatwiy** [comment]
> @myriammatwiy In the first screenshot the text is wrapped on the "Upload and hand-enter..." label. Are you using a label expression to wrap it?

Yes for that one the label expression is set to ${wordwrap:60:${name}}, however the existence of that relationship isn't necessary to reproduce the issue.

**Comment by myriammatwiy** [comment]
> A maximum label width of 300 pixels was set in this [commit](https://github.com/archimatetool/archi/commit/1fd5f2fc15b58b6cfeb4903551f9670eb88cf568#diff-01b7ac4d12cc5484536988d7c9b9ed5354ae1cef5e3f78dcdfaeb236262683c7). This was set to stop excessively long labels and because support for text alignment (left, centre and right) was added to connections. If there is no limit to the size of connection labels then text alignment does not work.

We have used long relationships a lot in our views, as there was no max length. This leaves us unable to upgrade to Archi 5 because there doesn't appear to be a configuration setting that allows us to shut off the new auto-wrap. Also, I didn't see anything in the release notes regarding this new wrap feature.

**Comment by Phillipus** [comment]
> Yes for that one the label expression is set to ${wordwrap:60:${name}}, however the existence of that relationship isn't necessary to reproduce the issue.

I just wanted to check that you were achieving your desired word wrap using a label expression.

> We have used long relationships a lot in our views, as there was no max length. This leaves us unable to upgrade to Archi 5 because there doesn't appear to be a configuration setting that allows us to shut off the new auto-wrap. Also, I didn't see anything in the release notes regarding this new wrap feature.

It came as part of support for text alignment on connection labels.

I think that the new maximum length of 300 pixels introduced in Archi 5 is not ideal. Therefore I'll remove that for the next version Archi 5.4.

**Comment by jbsarrodie** [comment]
> I think that the new maximum width of 300 pixels introduced in Archi 5 is not ideal. Therefore I'll remove that for the next version Archi 5.4.

I agree this hard-coded width limit is not ideal. Instead of removing it, would it be possible to set it per relationship instance on views (kind of native support for ${wordwrap...}). Maybe a slider of some sort ("0" would mean no width limit, and would be the default) ?

**Comment by Phillipus** [comment]
> I agree this hard-coded width limit is not ideal. Instead of removing it, would it be possible to set it per relationship instance on views (kind of native support for ${wordwrap...}). Maybe a slider of some sort ("0" would mean no width limit, and would be the default) ?

I'll look at that for a future version. In the meantime, go back to the old behaviour.

**Comment by Phillipus** [comment]
Fixed in Archi 5.4
