### ISSUE TITLE
Line Colour Derived from Fill Colour in Archi 5

### ISSUE THREAD

**Issue by myriammatwiy** [archimatetool/archi#1057]
View Error Log button is disabled (assuming the error log is empty)

### Version of Archi

Archi Win64 5.1.0 and 5.3.0

### Archi Plug-ins

Collaboration plug-in 0.9.2 installed

### Operating System

Windows 11 Enterprise

### Expected Behaviour
When upgrading to Archi 5, existing elements that do not derive element line colour from fill colour should remain set to the line colour specified.

### Actual Behaviour

The specified line colour is no longer set and the line colour is derived from the element fill colour instead.

### Steps to Reproduce the Behaviour
1. Import existing model created in Archi version 4.9.3 which was configured to not derive element line colour from fill colour.
2. Open a view that contains an element set with a specific line colour.
3. Notice that the line colour is derived from the fill colour (and that the specified line colour is no longer set). Before and after images attached.

Before (in version 4.9.3):
![line colour derived setting in version 4 9 3](https://github.com/archimatetool/archi/assets/106278290/cd7ac67a-4097-460e-8fb7-9e93795639a8)
![BEFORE - line colour not derived from fill colour in version 4 9 3](https://github.com/archimatetool/archi/assets/106278290/be98bb1e-8c23-4622-8635-812f03af91a5)

After (in version 5.3.0):
![line colour derived setting in version 5 3 0](https://github.com/archimatetool/archi/assets/106278290/80409d43-8dc0-4bff-9252-69f3ff87ad45)
![AFTER - line colour derived from fill colour in version 5 3 0](https://github.com/archimatetool/archi/assets/106278290/58dcde46-cfae-45ae-876d-15b263ee0cd4)

**Comment by Phillipus** [comment]
The previous global option was changed to a per-figure option in Archi 5.2. We had to decide what the default setting would be for existing models and chose for it to be on because that was the global default. There is an option to set it on/off for newly created objects in Preferences.

**Comment by myriammatwiy** [comment]
> The previous global option was changed to a per-figure option in Archi 5.2. We had to decide what the default setting would be for existing models and chose for it to be on because that was the global default. There is an option to set it on/off for newly created objects in Preferences.

I did notice that the setting has been moved to the element level. The issue is that we cannot easily upgrade to Archi 5 because line colours on existing elements are not carried forward.

**Comment by Phillipus** [comment]
> I did notice that the setting has been moved to the element level. The issue is that we cannot easily upgrade to Archi 5 because line colours on existing elements are not carried forward.

In Archi 5.2 we had to decide what default to use for elements when opening a model. This setting was a global application setting and is not stored in the model so we had to make a choice between on or off. We chose to set the default to on for elements, as that was the default setting before. We felt that most users would have that global setting on and if we set it to off for elements there would be more users affected.

**Comment by Phillipus** [comment]
> I did notice that the setting has been moved to the element level. The issue is that we cannot easily upgrade to Archi 5 because line colours on existing elements are not carried forward.

A simple jArchi script would set all elements derived line color off:

```js
$("view").find().forEach(element => {
    element.deriveLineColor = false;
});
```

**Comment by sonear** [comment]
Phil

In a similar/related situation I am looking to set element line color (and
hopefully line weight)  via script based on element property/ies

The use case is to:

- highlight impact of an initiative on our capability map

- display capability maturity level based on property

- show multidimensional element fill based heat map (say three color based
on property value of 1, 2, or 3... AND change border of element to
highlight something like (in scope or out of scope)

There are multiple use cases that could be applied but they all involve
property based setting of color on

- element fill <- multiple community examples already available
- element line color
- element line width

Ideally the color is learned from a property as well but that seems doable
already

Can all or some of this be done in existing versions of jarchi and archi?

Thank you

Scott Griffith

**Comment by Phillipus** [comment]
@sonear Hi Scott, that's a lot to process and this issue is not really the best place to go into detail. I suggest the best place for a jArchi discussion is on the [Archi Forum](https://forum.archimatetool.com/index.php?board=5.0). 😄 

Cheers, Phil.

**Comment by sonear** [comment]
Fair enough. Will do!

**Comment by myriammatwiy** [comment]
> > I did notice that the setting has been moved to the element level. The issue is that we cannot easily upgrade to Archi 5 because line colours on existing elements are not carried forward.
> 
> A simple jArchi script would set all elements derived line color off:
> 
> ```js
> $("view").find().forEach(element => {
>     element.deriveLineColor = false;
> });
> ```

Yes, what we'll need to do is write a script that determines which elements have a line colour override in Archi 4.9.3 and then use that list to set it in Archi 5, along with the deriveLineColor property. Thanks for your responses.

**Comment by Phillipus** [comment]
I'll close this one as there's nothing we can change regarding the default.
