### ISSUE TITLE
Extended possibilities to change colours of symbols in diagrams

### ISSUE THREAD

**Issue by nicoplat** [archimatetool/archi#106]
I want to change the appearance (colours, really) of the symbols in my diagram. Fill, font and line colours can be changed by selecting a symbol in my diagram, then selecting "Appearance" in the properties pane, and adjusting them. This works fine.

But then I also want to change the line colours of the symbol used inside the overall symbol. E.g. consider the "Actor" symbol. I can change the colour of the line of the rectangular box that represents it. But I want to change the colours of the "actor figure" in the top right hand side of that rectangular too. Apparently this is not possible in the current version of the tool. It is a feature I would like to see added, if others have a need for it as well.

**Comment by Phillipus** [comment]
This is implemented now.

**Comment by nicoplat** [comment]
Thank you!
