### ISSUE TITLE
Incorrect record size  - {0} error.

### ISSUE THREAD

**Issue by marbico** [archimatetool/archi#1062]
### Archi Version

5.3

### Operating System

WINDOWS 10

### Archi Plug-ins

coArchi, coArchi Command Line, Excel, Lightbox

### Description

1. Export the model to CSV
2. Open properties.CSV
3. Delete a few lines
4. Save properties.CSV
5. Import the model from CSV
6. I get an "Error importing"  pop-up with the message:  "Incorrect record size  - {0}"
[Archi Test model.zip](https://github.com/user-attachments/files/16390809/Archi.Test.model.zip)

**Comment by Phillipus** [comment]
Hi, it depends what you are deleting when you say "delete a few lines".  If a line is not fully deleted you will see this error. Make sure you delete the full line.

**Comment by marbico** [comment]
Hi,
Thank you for getting back to me so quickly.

I conducted additional testing.


1. First, I exported the model to CSV and imported it back to check for errors, and it worked fine.
2. Next, I used LibreOffice Calc to delete two lines from properties.csv and then imported it again, but encountered the  "Incorrect record size - {0}" error.
3. To investigate whether Calc was causing issues with CSV formatting, I again exported the original model to CSV and imported it without any errors. Then, I deleted the same lines from properties.csv using Notepad++. When I imported the model again, there was NO error, BUT the object still had the properties that I deleted from the CSV file.
4. To verify this, I created a new empty Archi model and imported the properties.csv with the deleted lines. This time, there was no import error, and the object did not have the deleted properties. The import worked correctly.

Based on this experience, Calc seems to mess up the formatting, while Note++ doesn't.  OK, I'll avoid using Calc or Excel.
However, why does deleting properties through CSV editing not work by importing into a non-empty model, but works when importing into an empty model?
Regards,
Marek

**Comment by Phillipus** [comment]
> However, why does deleting properties through CSV editing not work by importing into a non-empty model, but works when importing into an empty model?

When importing CSV, if a property does not exist in the model it is added to the model, if it already exists it is ignored or updated if the value is different. Deleting properties in the CSV file will not delete the property in the model when importing.

**Comment by marbico** [comment]
Oh. That makes sense. 
Thanks for explaining.

**Comment by Phillipus** [comment]
I'll close this one, then. :-)
