### ISSUE TITLE
Junction related relationships missing from view 

### ISSUE THREAD

**Issue by ewalters99** [archimatetool/archi#1063]
### Archi Version

5.3.0

### Operating System

Windows 10

### Description

In View 1 I create 3 x Business Processes: BP1, BP2, BP3. BP1 triggers BP2 AND BP3 using a junction.

In View 2 I drag in the 3 processes from the Model but the triggers and the junction don't appear.

### Steps to reproduce

In View 1 I create 3 x Business Processes: BP1, BP2, BP3. BP1 triggers BP2 AND BP3 using a junction.

In View 2 I drag in the 3 processes from the Model but the triggers and the junction don't appear.

**Comment by Phillipus** [comment]
When dragging objects from the Models Tree onto a View only the dragged objects and any relations between those objects are added to the View. In your case you also need to drag the Junction onto the View. You can drag BP1, BP2, BP3 and the Junction onto the View in any order or all together.

**Comment by ewalters99** [comment]
Hi Phil,

 

OK, I see … I always see the Junction as a type of Relationship, but of course it isn’t in the metamodel.

 

Regards

 

Ed Walters

Consultant, Business Systems Development

 ***@***.***> ***@***.***

https://fmedic.co.uk/truecom

+ 44 (0) 7786 444 372

 

Please note: I am in the process of switching my main personal email address to  ***@***.***> ***@***.***

However I will still be processing emails received at  ***@***.***> ***@***.*** for some time yet.
