### ISSUE TITLE
elements are deselected while dragging if their nesting status changes

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1065]
### Archi Version

5.3.0

### Operating System

windows 10

### Description

When selected elements are dragged with a mouse, they stay selected after the mouse button is released unless their nesting status changes: if they were nested inside another element and are dragged outside of it or vice versa, the selection is cleared. This is inconsistent and inconvenient if final position is unsatisfactory: to move them some more one has to select all of them again.

### Steps to reproduce

1. create an element with nested elements
2. select nested elements with ctrl-click
3. drag them outside - selection is cleared

**Comment by Phillipus** [comment]
Fixed in Archi 5.4
