### ISSUE TITLE
Portable installation for Windows still requires admin privileges when registring file association

### ISSUE THREAD

**Issue by damienb-opt** [archimatetool/archi#1066]
### Archi Version

5.3.0

### Operating System

Windows 11

### Description

The portable zip includes two files in order to manage .archimate file association on Windows: RegisterFileAssociation.bat and UnregisterFileAssociation.bat . They try to register this file association at the machine level. Usually, when someone uses the portable zip, it's in order to not mess with the machine level, so it would seem more logical to work at the user level. For Windows, it means to write inside HKCU\Software\Classes instead of HKCR.

**Comment by Phillipus** [comment]
Thanks for the heads up. Can you provide working batch files as attachments that you've tested?
