### ISSUE TITLE
Clear "search box in model tree" (x) does not clear in 5.4 (works in 5.3)

### ISSUE THREAD

**Issue by sonear** [archimatetool/archi#1072]
### Archi Version

5.4.0

### Operating System

macOS sonoma 14.6

### Archi Plug-ins

jArchi 1.6.1, coArchi 0.9.2.2

### Description

GOAL: search for a view name using search widget in model tree. Then when done, click the (x) within the search widget to clear my search

### Steps to reproduce

ACTIONS:
1. in model tree, click magnify glass to expose search widget,
2. type is "strategy" which results in default, existing Strategy folder
3. Now click the (x) in the right side of the search widget to clear the search.

it does nothing

NOTE: This last worked as expected in 5.3.

ALSO NOTE: In 5.3 then (x) shows up with a grey backgound. This is when it is working.  5.4 the (x) shows up with black background and does not work.

5.4
![Screenshot 2024-09-09 at 10 07 45 AM](https://github.com/user-attachments/assets/8925d1ee-e3b5-45a2-9cf9-cc579192aa5f)

5.3
![Screenshot 2024-09-09 at 10 23 15 AM](https://github.com/user-attachments/assets/760c24e4-4d9f-492d-90f0-de5e9b0ed4e1)

Thanks for taking a look at this.

**Comment by Phillipus** [comment]
Hi, you have to double click the "x" to close it. Because of changes in Eclipse we now use the Mac native close widget which, unfortunately, requires a double-click to close it. The same occurs in Eclipse itself.

**Comment by sonear** [comment]
Ahh. Thanks Phil. I didn't realize this
