### ISSUE TITLE
Clearing search bar by clicking on the 'x' circle does not work

### ISSUE THREAD

**Issue by CzechM8** [archimatetool/archi#1077]
### Archi Version

5.4.2

### Operating System

MacOS Sequoia

### Archi Plug-ins

CoArchi, jArchi (latest)

### Description

After I search for an object in the model tree I try to clear the search bar by clicking on the 'x."  It does not work.

### Steps to reproduce

1. Search for an object.
2. Clear the search by clicking on the 'x"

**Comment by Phillipus** [comment]
You need to double-click on the "x". It's the same in the search box in Preferences. It's an [Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551405).

**Comment by Phillipus** [comment]
Having said that, I can add a workaround to support single-click for the next release of Archi for the search box. However, I can't apply that workaround to the search box in Archi's Preferences/Settings dialog as it's an internal Eclipse control and I have no control over that.

**Comment by CzechM8** [comment]
Thanks, Phil. I appreciate the work you do!

Les


*J. Les Hardin, MBA, CCSP, CISSP-ISSAP*
