### ISSUE TITLE
[Feature Request] Add a "Show all views" option in the Model Tree Filtering options

### ISSUE THREAD

**Issue by AlexisHFr** [archimatetool/archi#1079]
### Description

While filtering concepts of the model tree, an indirect impact is that all views are filtered out and inaccessible to user.

A more basic option would be to add a 'Show all views' in the same logic with the 'Show all Folders', which is the feature request here.

Another option could be to separate more clearly Views from Concepts/Relationships of the model.. for eg by creating a clone of the Models widget in the UI but dedicated for 'Views'  (in my mind I don't think of 'Views' as elements of the model but as projection of the model content for a specific need/viewpoints so merging views with concepts & relationships is not natural for me), but this is a more impactful change .. and something that's rooted in Archi since the early days..

**Comment by AlexisHFr** [comment]
Hi Phil,

I work on a big model (7K concepts, 1K folders, 450 Views), and I sometime want to focus on specifics area/layer of the model, eg : Application structural concepts + a bunch of views showing applications landscapes or detailed architecture of specific application etc..
So I filter the model tree on concept types (this is ok) but how do I browse/open my views then ?
(I can use the Analysis panel of a specific concept to open dependant views, but it's cumbersome when you want to open a specific view and just know it's name/path )


Hope this clarifies my request.

**Comment by Phillipus** [comment]
OK, thanks for the feedback.

I think then we should add Views to the search filter, just like concepts as proposed here- https://github.com/archimatetool/archi/issues/998

I've now written the code for this and it works well. Will be in the next version.

**Comment by Phillipus** [comment]
I'll close this one so we can continue in #998
