### ISSUE TITLE
[Feature Request] Implicit line between same object twice within view being displayed

### ISSUE THREAD

**Issue by peterprib** [archimatetool/archi#1082]
### Description

If a object is twice in a view, a implicit line should appear between the two objects and one should have the choice to override.  This would avoid the need for self pointing relationships to enable drawing and would assist it realising the same object appears more than once in a diagram.

**Comment by romualdrichard** [comment]
For me, if you have twice an object in a view it's to avoid to have too many tangle lines.

**Comment by peterprib** [comment]
In a data object the same element/attribute may appear in more that one place especially if foreign key.  So I want to see line.  And labelled based on an expression for view.

**Comment by jbsarrodie** [comment]
Hi,

What you describe is a very narrow use-case. As @romualdrichard pointed out, in the majority of cases, people don't want to clutter their views with additionnal, automatic lines.

In addition, these should not be just lines, but reallrelationships (maybe association, but some might want another type).

So such use-case should be implemented using a jArchi script (and it could be run with a keyboard shortcut to speed things up).

Regards

**Comment by peterprib** [comment]
Must admit having trouble understanding the contradiction between it being a very narrow use case and all these diagrams being flooded with automatic lines.  Statement even contradicts current behaviour where one has to deleted unwanted lines when you select off the tree for a duplicate object on view which is another feature I wished to recommend, that is, have the choice of what lines are added. You can't have it both ways.  Note, I am aware of copy and special paste before y make that suggestion.

I suspect if you reflect and focus on data objects you will see it is not narrow use case.  Definitionally all data objects representing entities must have at least one common attribute appear between all relate entities.  Keys are basis of data stores. Data objects as they traverse the objects such as interfaces are common and would be benefical showing the commonality.  Can be common as object in flight and at rest at end points or transient store like queue or cache.

To force the addition of self referencing object relationships adds a burden of complexity to the management of concepts placed on diagrams.  It adds to performance degradation as such must be maintained and touched on filter of the tree.  To say an object is associated with itself is self evident.  Why does it have to be materialised as its own object when it can just be a visual object?

I know I could create such with jArchi but it is a poor work around as it needs the superfluous relationship to be create.  My model is already sustaining performance issues due to the volume of superfluous relationships.   Some intelligent additions to the management of implicit relationships, this being just one example, which would help reduce the volume of superfluous relationship one has to define in generating required visual diagrams.

regards

**Comment by jbsarrodie** [comment]
>Must admit having trouble understanding the contradiction between it being a very narrow use case and all these diagrams being flooded with automatic lines. Statement even contradicts current behaviour where one has to deleted unwanted lines when you select off the tree for a duplicate object on view which is another feature I wished to recommend, that is, have the choice of what lines are added.

[RTFM](https://www.archimatetool.com/downloads/archi/Archi%20User%20Guide.pdf) p.37

>To force the addition of self referencing object relationships adds a burden of complexity to the management of concepts placed on diagrams. It adds to performance degradation as such must be maintained and touched on filter of the tree. To say an object is associated with itself is self evident. Why does it have to be materialised as its own object when it can just be a visual object?

That's just not how the ArchiMate standard itself works: a line between two elements must be a relationship. Allowing to show a line on a view without it been "backed" by a real relationship would make this view impossible to export through the ArchiMate Model Exchange File Format. And I guess that you care about data interoperability.

>My model is already sustaining performance issues due to the volume of superfluous relationships.

That's maybe the sign that you should seriously think about buying a commercial tool so that a vendor will be happy to charge you some additional money to develop the one feature you need.

Regards

**Comment by peterprib** [comment]
I appreciate this response as it makes sense.  Not sure if I agree with your intrepretation of the standard but understand the argurment about on archimate model exchange although I suggest this could be overcome by materialisng the implicit relationship on export and removing on import.

With the start of my performance issue have pondered moving to a commerical tool.  Would point out the guidance has a negative impact on donations.
