### ISSUE TITLE
[Feature Request] line style for elements (e.g. dotted, dashed lines etc)

### ISSUE THREAD

**Issue by The-WetFish** [archimatetool/archi#1084]
### Description

When creating models we have the ability to change the line colour, width, and opacity of elements - but not the line style. 

Adding basic options such as dotted, dashed etc would give greater visual control for the modeller.

**Comment by Phillipus** [comment]
This is a duplicate of https://github.com/archimatetool/archi/issues/702 and https://github.com/archimatetool/archi/issues/1044 Let's stick to [one issue](https://github.com/archimatetool/archi/issues/702).
