### ISSUE TITLE
[Feature Request] Being able to set the size of the image of a specialization

### ISSUE THREAD

**Issue by romualdrichard** [archimatetool/archi#1086]
### Description

I think og using specialization to have an image of my applications like the attached image but I can't set the size.
For the moment, I have to copy/past the image (in a note) in the right place.

![image](https://github.com/user-attachments/assets/2d20a2f6-43ef-4a38-ba3e-426b1a5297c7)

**Comment by Phillipus** [comment]
Hi, an image is rendered at its original size (unless you use the "Fill" setting). So you'll need to create the image at the required size first.

**Comment by romualdrichard** [comment]
I understood. I have to change size of the image and it's working.
