### ISSUE TITLE
[Feature Request] Populate missing related Objects on View

### ISSUE THREAD

**Issue by pdev666** [archimatetool/archi#1087]
### Description

I would like to request a feature that allows users to easily populate missing related objects on a view in Archi. This feature would enable users to select an object on a view, right-click on it, and then have the option to add all related objects that are not yet included in the view but have a relationship with the selected object.

**Proposed Functionality:**
-     Right-click on any object within a view.
-     A new menu option called "Populate Related Objects" will be available.
-     When selected, this will automatically insert all missing objects that have a direct relationship with the chosen object into the current view.

This feature would significantly enhance efficiency in building comprehensive views of models and avoid the manual process of adding related objects individually.

**Comment by Phillipus** [comment]
Hi, this is exactly the kind of thing you can achieve with a jArchi script (and with the advantage that you can customise it for your particular needs). See [here ](https://github.com/archimatetool/archi-scripting-plugin/wiki)for more details.

**Comment by pdev666** [comment]
Thanks Pfillipus, with a jarchi Script it will go. But a basic implementation directly in archi would be great for the most use cases.
I would help a lot of users of archi.

**Comment by Phillipus** [comment]
> Thanks Pfillipus, with a jarchi Script it will go. But a basic implementation directly in archi would be great for the most use cases.
I would help a lot of users of archi.

As I said above, apart from jArchi, it's possible to do this now using the drag and drop method from the "Model Relations" table.

However, as Archi is open source you or others are free to provide a native implementation.
