### ISSUE TITLE
Allow chocolatey package for installation on windows

### ISSUE THREAD

**Issue by FilipDeVos** [archimatetool/archi#109]
As the [Chocolatey](https://chocolatey.org) package manager for windows is gaining popularity I wonder if you would accept the creation of an Archi Chocolatey package.

I have created it locally and it works perfectly fine. The chocolatey package will simply call the download link and execute the setup with /VERYSILENT option. 

When the package is published on chocolatey.org you can install Archi on windows by calling:

    choco install Archi

This outputs:

    Chocolatey (v0.9.8.27) is installing 'Archi' and dependencies. By installing you accept the license for 'Archi' and each dependency you are installing.
    Archi v3.1.1
    Downloading archi 32 bit  from 'http://archimatetool.com/downloads/latest/Archi-win32-Setup-3.1.1.exe'
    Installing archi...
    archi has been installed.
    archi has finished successfully! The chocolatey gods have answered your request!

Finished installing 'Archi' and dependencies - if errors not shown in console, n
one detected. Check log for errors if unsure.

I put the code to create this in a gist https://gist.github.com/FilipDeVos/24c6179313639ea96932

I am happy to maintain this chocolatey package, but I don't want to publish anything without your permission.

**Comment by Phillipus** [comment]
Hi, to be honest I hadn't heard of Chocolatey until now. It seems there are quite a few big apps available already. So, OK, why not. :-)

If you can maintain it, even better!

Regards,

Phil

**Comment by FilipDeVos** [comment]
I submitted the package, it is under review for now.

https://chocolatey.org/packages/Archi/3.1.1

**Comment by FilipDeVos** [comment]
Package is approved and published. See https://chocolatey.org/packages/Archi

**Comment by Phillipus** [comment]
Well done! :-)

**Comment by FilipDeVos** [comment]
Is there a way that we can keep "old" versions of the setup available on the current url? Otherwise I need to "cloak" older versions of the package.

Currently I use: http://archimatetool.com/downloads/latest/Archi-win32-Setup-3.1.1.exe 
Placing new releases next to the old ones would keep things clean.

**Comment by Phillipus** [comment]
Not really. I always use the http://archimatetool.com/downloads/latest/ prefix for URLs.

**Comment by FilipDeVos** [comment]
No worries, I'll manage.

**Comment by FilipDeVos** [comment]
Updated package for the 3.2.1 release. Currently awaiting moderation. 

See: https://chocolatey.org/packages/Archi/3.2.1

**Comment by FilipDeVos** [comment]
Updated package for the 3.3.1 release. Currently awaiting moderation.

See: https://chocolatey.org/packages/Archi/3.2.1

**Comment by FilipDeVos** [comment]
Archi 3.3.1 is now approved: https://chocolatey.org/packages/Archi/

**Comment by FilipDeVos** [comment]
Archi 3.3.2 is now approved https://chocolatey.org/packages/Archi

**Comment by FilipDeVos** [comment]
Updated package for the 4.0.0-pr1 release. Currently awaiting moderation.

See: https://chocolatey.org/packages/Archi/4.0.0-pr1

**Comment by FilipDeVos** [comment]
Archi 4.0.2 is now approved https://chocolatey.org/packages/Archi/4.0.2
