### ISSUE TITLE
Archimate is no longer opening my xmls nor achimate files rendering them useless, please help!

### ISSUE THREAD

**Issue by bhargavvivekanandan** [archimatetool/archi#1090]
### Archi Version

5.4.2

### Operating System

MacOS Ventura 13.3.1

### Description

I am no longer able to develop architecture models on my existing projects as Archi is no longer opening up my Xmls nor achimate files.

### Steps to reproduce

1. Download Archi 5.4.2
2. Import the open xml file attached
3. Open the achimate file attached

**Comment by Phillipus** [comment]
Please attach an example archi file.

**Comment by bhargavvivekanandan** [comment]
Hello Phil, thank you for the prompt response, here you go




Thank you,

Bhargav Vivekanandan (Bhargav) MS ISM CISSP CCSP GCSA
3329, Welton Circle,
Roseville, CA 95747
Artist | Information Security Expert | AI/ML Safety | Robotics
________________________________

**Comment by Phillipus** [comment]
You have to add attachments through the web interface on GitHub not email.

**Comment by bhargavvivekanandan** [comment]
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/1ddde777-e9fc-4689-85d4-5b3f0956b047">

**Comment by bhargavvivekanandan** [comment]
As you can see, I was able to open the file , however, it does not show me the hierarchical visualization with the connections, I do get it when I go to visualization but I am unable to see it in the main view

**Comment by Phillipus** [comment]
I don't know what you mean by "it does not show me the hierarchical visualization with the connections". If you open the "Views" folder you'll see your Views that you can double-click on to open them.

**Comment by bhargavvivekanandan** [comment]
Ok thank you I am able to see the visuals now, really appreciate it, although for some reason, one of my achimate files was overridden and the data was lost, it seems to be an iCloud issue as I see data lost in some other apps as well, thank you
