### ISSUE TITLE
Nesting creates potential false warnings in validation tool

### ISSUE THREAD

**Issue by flippinnora** [archimatetool/archi#1095]
### Archi Version

5.4.2

### Operating System

Windows 11

### Description

Taking an actor hierarchy to represent an org structure when I drag a child inside a parent I get prompted for the Composition relation type correctly but actually Arch create both a composition and an association relationship.
The validation tool then reports this as a warning because I suspect of the presence of both relationship types
It only reports this warning if shape  nesting is used

### Steps to reproduce

1. Create parent actor
2. Create child actor
3. Drag child inside parent
4. Select "composition"
5. Run validation tool - warning produced
6. Drag child outside parent (the two comp and assoc rel types are visisible)
7. Run validation too - no warning
![image](https://github.com/user-attachments/assets/1e595205-d4dc-4660-9dcf-ac675bd6be38)

**Comment by flippinnora** [comment]
Ah silly me. Yes of course. I had converted the parent from being roles to actors and when I later changed the parent to Actor it auto changed the assignments relationships to associations. Thanks

**Comment by Phillipus** [comment]
I'll close this one, then.
