### ISSUE TITLE
chnages to documentation are not saved while documentation still has focus

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#1096]
### Archi Version

5.4.3

### Operating System

windows 10

### Description

Modification of Documentation on the Main tab of properties of any element triggers actual diagram change (asterisk by its name) only after Documentation loses focus, consequently pressing ^S immediately after Documentation is changed and still has focus does not actually save the change, which I find at least counterintuitive and may be even unsafe. It would be nice if ^S pressed in Documentation field will trigger data commit before saving. Or is it an unavoidable Eclipse quirk?

### Steps to reproduce

1. type something into Documentation filed on the Main tab of properties of any element
2. while Documentation still has focus, press ^S - modification is not saved
3. leave Documentation field - asterisk appears by the diagram name on the top tab bar

**Comment by Phillipus** [comment]
A change to text in a multi-line control is "committed" either when the control loses focus or when Ctrl-Enter is pressed.
