### ISSUE TITLE
Import another model into selected model

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#1097]
### Archi Version

5.4.3

### Operating System

Windows 10 Home

### Archi Plug-ins

I use latest of all but not involved in this issue

### Description

Hi Plil,
The import function could be failing to check thoroughly for uuid clashes between host and imported model elements.
I have encountered this a couple of occasions where an import appears to have been successful (i.e. no errors) but, in the post state, links to views which should have been independent, have become merged into one.
i.e. imported views replace, rather than append; the existing views of the parent model.

### Steps to reproduce

The easiest way to reproduce would be for me to send you the parent and import model - but as these contain client information, I prefer to DM you rather than post here

**Comment by Phillipus** [comment]
Hi, matching of objects is based on their UUIDs. This is intentional so you can update a model. The importer assumes that an object with the same UUID is to be updated. You'll need to uncheck the "Update existing objects and folders" option in the import wizard if you don't want this behaviour.

**Comment by lavenderb** [comment]
All Clear - thank you :-)

**Comment by lavenderb** [comment]
The problem is that the imported model has been made by a degree of copy-paste from similar models
 - so although the intent of the merge is a 'true' import', the module contains a mixture of new elements and 'unintentional' uuid duplicates.
 Now that we understand the tool better, we'll adjust our process :-)
