### ISSUE TITLE
[Feature Request] Selectable relations in html report

### ISSUE THREAD

**Issue by MarcelSchrauwen** [archimatetool/archi#1098]
### Description

It would be great to be able to select relationships within the html report views. Currently this is only possible on elements. To be able to show the documentation, properties, an analysis tabs of releationships would make Archi even better.

**Comment by Phillipus** [comment]
Hi, please see:

https://github.com/archimatetool/archi/issues/1013

and

https://github.com/archimatetool/archi/issues/376

**Comment by MarcelSchrauwen** [comment]
Thanks @Phillipus . I did a search but could not find similar features.  #1013 is similar to mine, so that makes my request redundant.
