### ISSUE TITLE
[feature proposal] Archi scripting engine (Groovy?)

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#11]
Having passed some days to create some shell scripts to merge/remove duplicate elements in a (big) model, I think it should be a good idea to have a kind of scripting engine inside Archi. After some research, it seams that groovy is a good candidate (can be used as a standalone script engine) and a cool way of doing it is through an embedded groovy console. This would allow us to work on EMF model with the help of EMF Builder and thus access all elements and properties without (to many) issues.

I see in fact 2 use cases:
- Scripts in read only mode. This would be mainly for extraction/reporting purposes, offering a similar feature as what BIZZdesign Architect include. No issues with undo/redo stack so can be seen as a potential Archi feature or plugin. If GroovyConsole doesn't integrate well with eclipse, a simple UI can be created.
- Scripts in update mode. This would be mainly for model maniulation purposes. Undo/redo stack could be an issue, so this could be (at least at the begining) a companion tool, but not integrated into Archi itself. In this case, GroovyConsole UI is  perfect so we just have to focus on EMF integration through [Beans](http://groovy.codehaus.org/Using+the+Eclipse+Modeling+Framework+(EMF\)) and/or [EMF Builder](http://dinkla.net/en/programming/groovy-emf.html).

**Comment by Phillipus** [comment]
We have a JS Script Engine now ;-)
