### ISSUE TITLE
[Feature Request] Model Search Enhancements: Selected Model

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#1100]
### Description

It would be very useful to be able to restrict the Model Search functionality to the selected model(s) only.
The current default applies the search to all models loaded into the Model Catalogue - which can produce many unwanted/unnecessary matches and make finding the intended target more laborious.

**Comment by jbsarrodie** [comment]
Hi, you already can. The search scope can be restricted by "going into" the model or folder (yellow arrow pointing right).
