### ISSUE TITLE
[Forum] - No Signup

### ISSUE THREAD

**Issue by nicolas-goyon** [archimatetool/archi#1106]
### Archi Version

5.4.3

### Operating System

Windows 11

### Archi Plug-ins

None

### Description

I'm a new guys who would like to discuss with other people about archi and how to use it correctly. 

However it seems that we can't create an account in the forum, i can't see the SignUp button... Or maybe i'm blind.

**Comment by Phillipus** [comment]
Sometimes it's disabled due to spambots. No need to open an issue here, if you send an email you can be registered.
