### ISSUE TITLE
Other relationships in new archi version?

### ISSUE THREAD

**Issue by frag-duino** [archimatetool/archi#113]
Hi,
 
yesterday I wanted to model an implementation and deployment viewpoint. 
I was wondering, why I couldn't assign a node to a communication path. 
In the "Archimate relationships"-menu I saw, that the accepted relationships have been changed:

![compare](https://cloud.githubusercontent.com/assets/9322787/7929709/719bea12-0901-11e5-9c6d-9b4c5976e7c4.png)

Is this a bug or a feature? In my opinion this should be an allowed relationship.

greetings
marcel

**Comment by jbsarrodie** [comment]
Hi,

This is not an issue. Archi strictly follows official ArchiMate specifications which moved from v2.0 to 2.1 last year, leading to the change you've pointed (and some other).

Regards

JB

**Comment by frag-duino** [comment]
Hi, 

thanks for your quick reply. I was a little confused, because both versions were referencing the 2.1 specification.

greetings
Marcel
