### ISSUE TITLE
[Feature request] Insert related elements 

### ISSUE THREAD

**Issue by bdendulk** [archimatetool/archi#114]
I have the following feature request:
- I would like to have the possibility to insert elements to a view that are related to an element selected (e.g. when right clicking). This is a function I experienced in Sparx EA and had proven very usefull in more than one occasion. The function in EA also had the opportunity to filter by layer and by depth of the relations.

Kind regards, Bart

**Comment by theunsfvo** [comment]
I agree, this would come in very handy and streamline the modeling process a lot.

**Comment by phavekes** [comment]
+1 
This is the one feature i'm missing when I switched from an other (commercial) archimate tool.

**Comment by jbsarrodie** [comment]
Hi,

Well, in fact you've been able to do it for a long time: 

If you have the Navigator panel opened and have selected an element in a View, then you can drag&drop related elements from the Navigator to the View, which will lead to add the Element and the relation to the view.

Same is also possible from the Analysis tab of the Properties panel.

Regards,

JB
