### ISSUE TITLE
Archi language translations

### ISSUE THREAD

**Issue by Atharex** [archimatetool/archi#115]
Just wondering... Are the translated features and plugin folders for a different language than english meant to be distributed along with a distribution of Archi on Github? 
Or do translators have to host them somewhere on their own and cannot include them in the official distribution?

**Comment by jbsarrodie** [comment]
Hi,

I think it highly depends on your capacity to update it frequently. Il also means that if a new version of Archi is to be published, you'll have only a few days to update it and commit it here.

So IMHO, the best option is to do it on your side on a personnal github account, and when your first release is ready, I can create you a repository under [Archi Contribs](https://github.com/archi-contribs).

Regards

**Comment by Atharex** [comment]
I'm not sure I will be able to update the translations very quickly after a new update comes out, so this other suggestion of yours might be the best solution. I was hoping that language translations already have a central place of storage...

My current translations are complete as per: www.archimatetool.com/dev/translate-archi

So I currently have the .zip file of the "features" and "plugins" folders. I was thinking of publishing this file on a repository, so if you would create that one, I'd put it up there. 

Best regards

**Comment by jbsarrodie** [comment]
Sorry for late answer. I can create a repo for you, but I first need to know which language it is for :-)

As soon as you provide this information I'll create the repository.

**Comment by Phillipus** [comment]
Closing as no longer valid. Re-open new issue if required,
