### ISSUE TITLE
Risk and Security plugin

### ISSUE THREAD

**Issue by thellef** [archimatetool/archi#116]
We consider developing a risk and security plugin for Archi. We want to use OpenFair taxonmy to work with properties(attributes in Archimate). The purpose is to feed the repository with structured information about risk and security to be able to create profiles, views, viewpoints, model etc for risk and security reports/dashboards.
If this is of general interest, we will chase funding, develop and share on GitHub.

**Comment by Phillipus** [comment]
Hi Thorbjørn, sounds interesting.

(BTW, the XSLT example you made for the ArchiMate exchange format was useful)

**Comment by thellef** [comment]
Thanks! I have forked and created a branch called risk and security

**Comment by thellef** [comment]
Can I put the requirements specification as an Archimate model in the repository to collaborate on it? If yes, where should I put it?

**Comment by Phillipus** [comment]
Would it be better to open a new git repo in this set of projects?

https://github.com/archimatetool

**Comment by jbsarrodie** [comment]
Best would be inside https://github.com/archi-contribs ;-)

**Comment by Phillipus** [comment]
> Best would be inside https://github.com/archi-contribs ;-)

Yes, I forgot about that!

**Comment by jbsarrodie** [comment]
So just choose a name for your repo and I will create it and give you admin access on it.

**Comment by thellef** [comment]
Thanks! Sounds like a good idea. Call it Risk-Security

**Comment by jbsarrodie** [comment]
Done: https://github.com/archi-contribs/risk-security
You've been invited to be part of R/W group associated with this repo.

**Comment by thellef** [comment]
Thanks!
