### ISSUE TITLE
[feature] sort user properties by name

### ISSUE THREAD

**Issue by prgee99** [archimatetool/archi#120]
Archi will sort by name by clicking on the "Name" table column header. I am making extensive use of the "user properties" feature and have defined a hierarchical naming convention to support it. I find myself always having to click this column header to re-sort the properties and it seems it might be relatively easy for Archi to do this automatically whenever the "Properties" tab is selected. It could even be controlled by a "Preferences" setting to maintain backward compatibility with Archi's current behavior.

Regards,
PEter

**Comment by Phillipus** [comment]
Just a note. Haven't forgotten this one. Focus now is on ArchiMate 3.0 support. If time permits...

**Comment by prgee** [comment]
Thanks for the update Phil! 

Cheers, 
Peter
