### ISSUE TITLE
[feature] add prefix string to the ID attribute

### ISSUE THREAD

**Issue by prgee99** [archimatetool/archi#122]
I have 2 concerns about the element ID's that Archi assigns for model elements:
1. First is that it does occasionally generate one with leading zeroes. This causes havoc with Excel export/import if you forget to select the "Use Excel leading zeros/spaces workaround".
2. Second is that the ID's are very cryptic when viewing them in an exported spreadsheet and more so when exporting as individual files using JB's GRAFICO plugin.

It seems to me that both of these issues could be resolved if a suitable text string was added to the front of the ID after it as generated. What would be very helpful would be to use a 3 or 4 character acronym for the element/relation type, followed by a "-" and then the generated ID. This would aid readability, eliminate the chance of leading zero/space characters, and still not compromise the uniqueness of the current ID generation strategy.

Regards,
Peter

**Comment by Phillipus** [comment]
point (1) is being addressed for Archi 4.7

> What would be very helpful would be to use a 3 or 4 character acronym for the element/relation type, followed by a "-" and then the generated ID.

No, because it is possible to change the concept type in a jArchi script. The prefix would then not be applicable, and the ID should not be changed at this point.
