### ISSUE TITLE
[feature] add "..." to cut off labels

### ISSUE THREAD

**Issue by Andy-Turner** [archimatetool/archi#124]
Example:
![image](https://cloud.githubusercontent.com/assets/16327109/11906094/3946aace-a598-11e5-90d6-723449cb9910.png)

Full label is:
![image](https://cloud.githubusercontent.com/assets/16327109/11906126/6c700db4-a598-11e5-975c-60047892d82b.png)

An indication would be nice:
![image](https://cloud.githubusercontent.com/assets/16327109/11906111/5b6ab03c-a598-11e5-99b7-cd386bd0aae5.png)

**Comment by Phillipus** [comment]
Andy, you can do this by setting in Preferences - Diagram - Appearance - Word wrap style

**Comment by Andy-Turner** [comment]
Hi Phil, thanks for the reply, but I tried all three settings (hitting apply, closing the view, restarting Archi) but they all look the same for me:
![image](https://cloud.githubusercontent.com/assets/16327109/11907384/74985632-a5a1-11e5-9af7-da1a61b068a9.png)

![image](https://cloud.githubusercontent.com/assets/16327109/11907322/016bb190-a5a1-11e5-857e-cb54019b2bca.png)
![image](https://cloud.githubusercontent.com/assets/16327109/11907357/4c7cc7c8-a5a1-11e5-8462-d3b5a37723c9.png)
![image](https://cloud.githubusercontent.com/assets/16327109/11907362/53f4b7ea-a5a1-11e5-9b02-5e45513c56c3.png)

**Comment by Phillipus** [comment]
Oh, yes. that's vertical not horizontal.

This is something buried deep inside of GEF/Draw2D. Perhaps a wizard can come up with a solution.
