### ISSUE TITLE
[Feature] Auto size new element to text lentgth (vertical or horizontal)

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#129]
This would save a lot of time when adding new elements while modeling.

Depending on the modeling style, there should be a default setting or toggle icon for either auto horizontal or vertical adjustment of element size.

Let me know if you need a image example attached for illustration.

**Comment by jbsarrodie** [comment]
Hi,

_Let me know if you need a image example attached for illustration._

Yes, I'd like one ;-)

JB

**Comment by theunsfvo** [comment]
![auto-sizing of new element creation feature suggestion example](https://cloud.githubusercontent.com/assets/5095077/11974186/6207bbf8-a96a-11e5-8fd2-d382ed5e78ec.png)

Here is an example of what I have in mind... shouldn't be too difficult to do.

**Comment by jbsarrodie** [comment]
Thank you, it's now clearer.

_shouldn't be too difficult to do._

It seems you've never coded with eclipse frameworks ;-)

JB

**Comment by theunsfvo** [comment]
lol... not eclipse no

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>
