### ISSUE TITLE
[Feature] Relation name text display adjustment

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#130]
When adding relationship name, you cannot change the text display, i.e. showing text on multiple lines below each other instead of the default one line.

When there are multiple words in the relation name, it becomes difficult to arrange the model elements with the long text names and you have the view layout to accommodate long relation names.

Also being able to change the anchor point of the relation name would be very helpful, since the middle/source/target setting does not work very well currently and I have to add another point on the relationship line and move that to adjust the text position.

Let me know if you need a image example attached for illustration.

**Comment by jbsarrodie** [comment]
Hi,

I must admit I agree with you.

@Phillipus I've just seen I can tag issues, so I've tag this one with feature. Let me know if you prefer another tag (or just want to do it yourself).

JB

**Comment by Phillipus** [comment]
@jbsarrodie the tag is fine. Not sure about the "bug" tag on a couple fo other issues

**Comment by theunsfvo** [comment]
Was about to open another issue for this.

Is this one still on the cards?

It would really help a lot instead of having to reposition all the elements just so that the text shows properly on the relationship between them.

**Comment by theunsfvo** [comment]
Created another one before finding this old one...

#486

**Comment by Phillipus** [comment]
Close this because label expressions supports line breaks.
