### ISSUE TITLE
[issue] correct git eol character

### ISSUE THREAD

**Issue by Andy-Turner** [archimatetool/archi#132]
Hi,

I'm creating an issue in case anyone else runs in to this, but I really can't figure out what the correct eol character is for this repo. I had git configured for the best practice of using LF, but after issues with the commits I tried instead moving to use CRLF, however I'm still having issues. When checking out the master branch I am getting a problem like below, different files have different eol. Can someone confirm what the correct eol to use for this project is - CRLF or LF? I think maybe perhaps I'll have to delete my entire master branch and start again, I don't see why my master branch would corrupt eol chars on its own.

![image](https://cloud.githubusercontent.com/assets/16327109/11981497/2ed7389c-a971-11e5-9a10-51ce33fe21d0.png)

**Comment by Phillipus** [comment]
Andy, it should be CRLF.

**Comment by Andy-Turner** [comment]
Issue addressed in: Pull request - Issue 132 correct git eol character

**Comment by Phillipus** [comment]
Andy, the ".gitattribute" file is causing strange behaviour in my git client (SmartGit) and a couple of files where you say you have changed to CR/LF already are CR/LF.

Historically, I've mainly developed using Windows Eclipse and this has defaulted to CR/LF. 99.99% of files are CR/LF with maybe the odd one slipped through the net.
