### ISSUE TITLE
[bug] new "Blank Canvas" showing up twice in tree view

### ISSUE THREAD

**Issue by Andy-Turner** [archimatetool/archi#136]
Using master branch and seeing this:

![image](https://cloud.githubusercontent.com/assets/16327109/12339895/a572c720-bae5-11e5-9716-67825f055b17.png)

Steps:
1. File > New > Empty Model
2. Right click "Views" > New
3. Blank Canvas listed twice

**Comment by Phillipus** [comment]
This seems to be (yet another) bug in Eclipse 4.5. We're using using Eclipse 4.4 (Luna) because of the many regressions and breakages in 4.5. Andy can you use Eclipse 4.4.x?

**Comment by Phillipus** [comment]
You'll notice that if you hover your mouse over the "Collapse" menu item and then hover over "New" again, the menu displays normally.

* This bug occurs in Eclipe 4.5.
* It only seems to happen on sub-menus (the "New" submenu)

**Comment by Phillipus** [comment]
Popup Menu IDs are registered in com.archimatetool.editor.views.tree.TreeModelView#fillContextMenu()

Canvas registers menus in com.archimatetool.canvas plugin.xml and com.archimatetool.canvas.NewCanvasExtensionContributionFactory

**Comment by Phillipus** [comment]
I filed a bug report - https://bugs.eclipse.org/bugs/show_bug.cgi?id=485931

As I siad, this affects Eclipse 4.5, not 4.4. Another reason to stay with 4.4 for now. :-(

**Comment by Phillipus** [comment]
Added a workaround for Eclipse 4.6
