### ISSUE TITLE
error when open preferences

### ISSUE THREAD

**Issue by el3ctron** [archimatetool/archi#139]
when opening preferences in linux mint, archi quits

in console appears this message:

java: /build/buildd/gtk2-engines-oxygen-1.4.5/src/animations/oxygencomboboxdata.cpp:87: void Oxygen::ComboBoxData::setButton(GtkWidget*): La declaración `!_button._widget' no se cumple.

**Comment by Phillipus** [comment]
Which version of Mint is this? Which theme? Is this the public version of Archi, or a development version running from Eclipse?

**Comment by Phillipus** [comment]
I found this, via Google:

https://bugs.kde.org/show_bug.cgi?id=339174

**Comment by el3ctron** [comment]
thanks!! now its working.

Thanks a lot!
