### ISSUE TITLE
[bug] Copy (from one model) / paste (into another model) with view references

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#140]
Hi,

I've just found a bug in Archi related to copy/paste of view references across models:
* Open view "VIEW_1" from model A. Lets assume "VIEW_1" contains some view references
* Select elements (and thus view references) from "VIEW_1" and copy them (CTRL-C or Edit>Copy)
* Open view "VIEW_2" from model B.
* Paste (CTRL-V or Edit>Paste) into "VIEW_2"
* You now see view references in "VIEW_2"
* Try to open (double clic) those view references from "VIEW_2", you'll in fact open views from model A !
* Now close model A and again try to open those view references from "VIEW_2", you'll open some empty views whose label seems to indicate they are part of model A (which is now closed).
* Try to save when having focus on such view, you get an error message ("Error in model").

Seems like we have to update copy/paste to manage view references (but how? create new empty views, replace view references by something else...).

JB

**Comment by Phillipus** [comment]
Thanks for the report. It seems that CopySnapshot.java was checking for pasting view references across models but not when the view reference is in a container object (e.g. Group).

Committed a fix to check child objects when pasting.
