### ISSUE TITLE
.csv-export generates keys with multiple interpretations.

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi#141]
This issue is about the .csv files that Archi exports. Archi generates ids (aka identifiers, internal keys) for elements, relations and properties. These ids look like, `"2b4b47a5"` for example. I presume these are the hexadecimal representations of ids that Archi generates.

Here is the problem. Archi occasionally generates ids that can be interpreted both as a string and as a number, such as `"74095673"`, `"73928e03"`, and `"4e872096"`. The most obvious of all applications, MS-Excel, makes its own choice. MS-Excel prefers the numeric interpretation. So, it treats `"2b4b47a5"` as a string and  `"74095673"`, `"73928e03"` as numbers. There is no way of predicting how other applications will cope with this ambiguity.

For me, this problem hurts, because MS-Excel does things with numbers. It turns `"73928e05"` into `7392800000`, to mention just one example. It would save me a lot of work if the .csv-export produces ids that are uniquely interpretable as strings, because MS-Excel leaves strings alone.

I presume that other applications than MS-Excel might make different choices when reading .csv-files. For they too must do something to resolve ambiguities. Therefore, the problem has a broader impact than just MS-Excel.

**Comment by jbsarrodie** [comment]
Hi,

_This issue is about the .csv files that Archi exports_

Well, this issue is more about the way Excel manages CSV ;-)

@Phillipus: IMHO, this could be solved by extending the "Use Excel leading zeros/spaces workaround" option to always use the ``="id"`` syntax.

Regards

JB

**Comment by Phillipus** [comment]
How about if, when exporting to CSV, all identifiers are prefixed with the string "id-"? "id-73928e03" instead of "73928e03". Would that solve all the issues and the need for the excel leading zeros workaround?

Phil

**Comment by jbsarrodie** [comment]
_How about if, when exporting to CSV, all identifiers are prefixed with the string "id-"_

Impossible, or else you will not be able to import back to the original model (new element versus already existing elements).

Re your Edit : you're right, I forgotten that this fix also other fields

JB

**Comment by Phillipus** [comment]
> Impossible, or else you will not be able to import back to the original model (new element versus already existing elements).

Ah yes, there's that. Unless we add "id-" as an option and then say that. Not all people will be re-importing.

**Comment by Phillipus** [comment]
So, maybe just add the leading zeros/spaces workaround also to all ids, not just ones with leading zeros?

**Comment by jbsarrodie** [comment]
_So, maybe just add the leading zeros/spaces workaround also to all ids, not just ones with leading zeros?_

Yes, that should do the trick.

**Comment by stefjoosten** [comment]
Thanks guys for jumping on this so quickly. I really appreciate that. 

The "id-" prefix gives sufficient assurance that ids are only interpretable as strings. Importing back any exported file requires to implement the loopback-constraint. Assume a function `import` that maps any internal data set to an exported data set  (`import :: IDS -> EDS`), and a function `export` that does the reverse (`export :: EDS -> IDS`). The loopback constraint can now be expressed as:

    import (export (x)) = x

In order to allow that, any mapping that `export` does to its ids must be reversible. Of course, prefixing identifiers with "id-" is reversible. As a consequence, import must reverse that mapping. This can be done by dropping the first three digits. When specified in Haskell, this looks like:

    map (drop 3) (map ("id-"++) x) = x

which is true for every `x :: EDS`.

So technically, it is possible if you are prepared to reverse the mapping in the import function. Therefore, I must be unaware of some extra constraint, being the one that made JB say that the "id-" prefix is impossible.

Also, I'm unaware of the details for the leading zeros/spaces workaround. Does this solution give sufficient assurance that ids are only interpretable as strings?

In this context I have a question as well. Are there any other ambiguities with the export function that I need to be aware of? (Maybe with character encoding schemes?)

Thanks again,
Stef

**Comment by stefjoosten** [comment]
In this context I have a question as well. Are there any other ambiguities with the export function that I need to be aware of? (Maybe with character encoding schemes?)

Thanks again,

Stef

**Comment by Phillipus** [comment]
This is a workaround for Excel, which is doing some guessing as to what the data format is and getting it wrong. Adding "id-" and then stripping it off again may lead to problems - a user might have created a CSV file manually with "id-" prefixes. I'm not prepared to do this for this case. So:

The leading zeros/spaces workaround can be also applied to the id field. This adds =" before a field and is specifically meant to solve the Excel problem.

But of course the real solution is to import the CSV data into Excel properly:

http://smallbusiness.chron.com/keep-leading-zeros-csv-43807.html
