### ISSUE TITLE
Archi doesn't like spaces/blanks in unique IDs imported from a CSV

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#144]
They import and save just fine but Archi won't reload them a second time when you try to open the .archimate file.

Here's a couple examples:

<element xsi:type="archimate:AssignmentRelationship" id="b059f90b" source="LocationID-CentralUS" target="ServiceID3-Virtual Machines-"/>

<element xsi:type="archimate:AssignmentRelationship" id="9bbe8ad7" source="LocationID-CentralUS" target="ServiceID24-Compute-Other-VirtualMachine Scale Sets"/>

Here's the error message:

![blanks error1](https://cloud.githubusercontent.com/assets/6101736/15015481/2b5c6daa-11da-11e6-9688-84b988537d56.png)

Michael Herman (Toronto)

**Comment by Phillipus** [comment]
See my answer to issue #142
