### ISSUE TITLE
Search model on property values

### ISSUE THREAD

**Issue by artekcs** [archimatetool/archi#145]
It would be super useful to be able to search through the model for elements that share some property value.
For example, let's says that my Application Components have a property "version". How can I quickly list all the components for "version == 1.2"?

Thank you

**Comment by prgee** [comment]
I believe this is already included in the Archi "Search" functionality (Archi User Guide p. 17).  You simply have to uncheck the "Name" parameter from the Search dialog, hover over the "Properties" parameter, and select the specific user property (or properties) you are concerned with (e.g. "version"). The model tree will immediately update to show only those elements/views that contain that property. If you type something in the search field (e.g. "1.2"), the model tree will show only those elements/views that have that property with that value. I have found it to be a very useful feature, particularly for managing large models:-)

Please update this issue once you have verified that this works for you so Phil can close it. Thanks!!

**Comment by Phillipus** [comment]
That's right. Thanks Peter!

**Comment by artekcs** [comment]
Yes, I do confirm it definitely works!
RTFM as they say...
Thank you
