### ISSUE TITLE
Add support for hi-res screens (UH, 4k)

### ISSUE THREAD

**Issue by michalrames** [archimatetool/archi#146]
The menu icons are too small on UHD screens because they are rendered in native resolution. 

Eclipse 4.6 Neon supports UHD screens out of the box. Are there any plans to upgrade Archi to Eclipse 4.6 in the near future?

Thanks

**Comment by Phillipus** [comment]
Yes. Current dev version is on Neon. Not sure yet if icons will have to be added in bigger resolutions as well. Perhaps somebody could take a look?

**Comment by Phillipus** [comment]
We need new icon sets at 2x resolution.

**Comment by Phillipus** [comment]
Created new branch "icons2x" to incrementally add new 2x icons.

**Comment by Phillipus** [comment]
There are new 2x icons in beta 4.1.2

**Comment by Phillipus** [comment]
Released in 4.2

**Comment by Phillipus** [comment]
> is there any way to increase the size of icons? still looks way too small for me :(

No, but if you are on Windows you can change the DPI settings for the app.

See:

https://github.com/archimatetool/archi/issues/832#issuecomment-1082211193
