### ISSUE TITLE
[feature proposal] Multiples Architectures on same model

### ISSUE THREAD

**Issue by Markenson** [archimatetool/archi#147]
While issue #110 don't be closed, is there some possibility of Archi allows multiples architecture folders by model? Something like this:

![image](https://cloud.githubusercontent.com/assets/2985140/16780157/d471d2f2-484b-11e6-8bde-254d075774d8.png)

**Comment by Phillipus** [comment]
After we implement ArchiMate 3.0 this is the kind of thing we'll be looking at.

**Comment by Markenson** [comment]
Thank you @Phillipus !

**Comment by Markenson** [comment]
Only to help if anybody needs, my workaround for a while was to put a subfolder in Views folder. 

![image](https://cloud.githubusercontent.com/assets/2985140/16785329/d60f9636-4863-11e6-8724-5143654c90dd.png)
