### ISSUE TITLE
[feature proposal] Single command to match width and height of model element

### ISSUE THREAD

**Issue by benvolioT** [archimatetool/archi#148]
Currently, there are menu items under Menu Bar > View > Position for:
- Match Width
- Match Height

It would be convenient to have a single command to match both width and height atomically. It would also be convenient to have a keyboard shortcut or similar UI element to make this faster to invoke.

**Comment by Phillipus** [comment]
Hi Ben.

Hmm...too lazy to click twice, eh? ;-)

OK, noted.

Phil

**Comment by benvolioT** [comment]
Haha. You found me out. Although after submitting this, I realized there is a preference for default diagram element width and height, which makes this less of an issue for me.

**Comment by Phillipus** [comment]
I just added a keyboard shortcut for "Default Size" for the next version, if this would help. The only question is, which key combo? Ctrl-D is already used for "Duplicate" in the tree. I went with Ctrl and / for now.

**Comment by jbsarrodie** [comment]
Er.. Ctrl and / are difficult for most non english keyboard as / is obtained with a shift, leading to a Ctrl + shift + /

Do we use Ctrl + R for something? This could be seen as a "reset" for size...

**Comment by Phillipus** [comment]
OK, but what about people who have no "R" in their language? For example, Jason and the R-go-naughts?

**Comment by Phillipus** [comment]
Match Size will be in Archi 4.9.
