### ISSUE TITLE
[feature proposal] Export SVG diagrams

### ISSUE THREAD

**Issue by benvolioT** [archimatetool/archi#149]
It'd be great if we could export SVG diagrams, ideally with [clickable links](https://www.w3.org/wiki/SVG_Links)

**Comment by benvolioT** [comment]
I'm not an expert in the eclipse graphical modeling framework. Not even a novice. But this may be helpful:

[org.eclipse.gmf.runtime.draw2d.ui.render.awt.internal.svg.export.GraphicsSVG](http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/3.7.2/org.eclipse.gmf.runtime.draw2d.ui.render/awt/1.4.1/org/eclipse/gmf/runtime/draw2d/ui/render/awt/internal/svg/export/GraphicsSVG.java)

> Objects of this class can be used with draw2d to create an SVG DOM.

**Comment by Phillipus** [comment]
Yes. In fact somebody has done some experiments in this area.

**Comment by Phillipus** [comment]
We can do this now
