### ISSUE TITLE
[feature proposal] Export diagrams from command line

### ISSUE THREAD

**Issue by benvolioT** [archimatetool/archi#150]
To support our continuous integration build process that fires off when we check in the model to our source control, it'd be great if we could, from the command line, export all of the diagrams in the model.

**Comment by Phillipus** [comment]
I think we have this already as a feature request...no it was on the forum. The issue is that diagrams are generated from the whole Eclipse GEF stack, and that is not *easily* done from the CL. Though it may be possible since I already do it in my headless unit tests.

**Comment by Phillipus** [comment]
Aha! You can do this in Archi 4.1. I added command line support. :-)
