### ISSUE TITLE
[Issue] Import Open Exchange File Format doesn't re-create "organization" subfolders

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#151]
If I create an Artifact in a subfolder under, for example, the Technology folder in the model browser, export and import the model using the Open Exchange File Format, the Artifact is imported but it is placed directly under the Technology folder.  The subfolder is not created and the Artifact is not placed in the subfolder.  Attached is a sample export file.  Import it and export it and re-import it.

[model0out2.txt](https://github.com/archimatetool/archi/files/473640/model0out2.txt)

Best regards,
Michael Herman (Toronto)

**Comment by mwherman2000** [comment]
The model that results from importing the above AMEFF file is the same as if the <organization> element was not being processed at all (or conversely, was missing from the file).

[model0out3.txt](https://github.com/archimatetool/archi/files/475979/model0out3.txt)

**Comment by Phillipus** [comment]
Sub-folders proved problematic for an easy solution, so were left out of version 1 support in Archi. What to do if the imported file had an arrangement of sub-folders that didn't map onto Archi's sub-folders? For example, Archi keeps all technology elements in the Technology folder and sub-folders. What should it do if an exporting tool mixed all the types into a folder? Should Archi then put each into different folders? The answer was never clear how to handle it.

**Comment by Phillipus** [comment]
Fixed in 4.6
