### ISSUE TITLE
warning: ignoring option MaxPermSize=256m; support was removed in 8.0

### ISSUE THREAD

**Issue by donpellegrino** [archimatetool/archi#153]
When running Archi64 on RHEL 7 with OpenJDK 1.8, a warning is output to the terminal.

$ ./Archi64 
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

$ java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

This is a minor issue and does not appear to affect run-time behavior. It looks like a JVM option was removed in v8 and perhaps the parameter could just be removed from the Archi start-up sequence.

**Comment by Phillipus** [comment]
Hi,

yes, this will be removed for the next version of Archi which will require Java 8 as a minimum.

You can remove the following line from the .ini file:

-XX:MaxPermSize=256m

**Comment by donpellegrino** [comment]
Great. Thanks, removing that line from the .ini eliminated the warning.

**Comment by Phillipus** [comment]
Close this

**Comment by Hossam45** [comment]
i have the same problem but i don't know where i can found that file to change or remove the -XX:MaxPermSize 
i need help

**Comment by Phillipus** [comment]
@Hossam45 This should not happen with latest version of Archi. Which version are you using?

**Comment by ntikoo** [comment]
I too have the same problem dont know which file to remove and where can i find that file.

thanks

**Comment by Phillipus** [comment]
Which version of Archi are you using? Please use the latest version.

**Comment by kawtherkaouther** [comment]
jdk13.0.1

**Comment by Phillipus** [comment]
> jdk13.0.1

Archi supports Java 8 and 11. Not 13
