### ISSUE TITLE
[bug] Product business element has no fill color

### ISSUE THREAD

**Issue by archofit** [archimatetool/archi#155]
In Archi-4b1 the Product business element has no fill color. If an attempt is made to change the fill color via Edit>Preference>Colours and Fonts>Business element fill colours>Product, the changed color applies to the line, not the fill. This appears to only impact Product and not other elements.
![2016-10-28 18_17_19- bug product business element has no fill color issue 155 archimatetool_ar](https://cloud.githubusercontent.com/assets/23109329/19825101/f380698a-9d3a-11e6-9f42-464954e7aa5a.png)

**Comment by Phillipus** [comment]
Thanks for finding the bug.

Fixed for beta 2.
