### ISSUE TITLE
More intelligent transformation Archimate 2.1 => 3.0

### ISSUE THREAD

**Issue by alcedocoenen** [archimatetool/archi#163]
The current transformation from version-2-files to version-3 is quite straight forward. Due to the backwards compatibility of Archimate 3.0, all main concepts from Archimate 2.0 can be transformed to the newer (but not different) Archimate 3.0 concepts.

However, in my diagrams so far, in Archimate 2.0, I have (mis)used the "Function" concept for Capabilities. I am looking for a way to transform these Function concepts to Capability concepts. It would be nice to have this option during or after the transformation. It asks for some more intelligent transformation, because:
(1) Maybe not all Function are meant as Capabilties. The user should be enabled to "mark" or select the Functions-meant-as-capabilities.
(2) Capabilities have a much more restricted set of valid relationships. The transformation needs to highlight relationships that are not valid anymore.
(3) The capabilities need to be re-arranged in the folder structure.
Quite a challenge, but not impossible I guess. What are your ideas?

Another intelligent transformation are the ones where I used to have a sequence of "write" and "read" relationship between application components and a data object. The pattern is App1 - Write relation - ObjectA - Read relation - App2, actually meaning that ObjectA is transferred from App1 to App2. In Archimate 3.0 this can be designed with the relationship between an object to a flow relationship between two application components; the example would then be: App1 - Flow relation - App2, and ObjectA with assign relation to the Flow relation. How happy I would be when all my previous diagram could be transformed to this new possibility in Archimate 3.0 !

**Comment by bdendulk** [comment]
Hi Alcedo,

The issue with business function versus capability is all too familiar with me. What I would try (but haven't gotten around to yet) is to make an export to CSV, do a replace all with business function and then import again in a new model. offcourse this will not solve (1), (2) and (3) but does save a lot of retyping.

Kind regards, Bart den Dulk

**Comment by jbsarrodie** [comment]
Hi,

In fact what you describe is more related to "changing element type" (for which we have a dedicated issue #265) than conversion from 2.1 to 3.0.

The list of issues you face are common, but can't be generalized enough. The real point here is really to be able to "refactor" a model without loosing too much time.

If you're ok I'd suggest to close this issue and continue the discussion on issue #265

Regards
