### ISSUE TITLE
mac file corrupted

### ISSUE THREAD

**Issue by castigf** [archimatetool/archi#165]
When starting the Archi beta on mac OS X 10.10.5 I get a message "Archi 17-39-54-927 is damaged and can’t be opened. You should move it to the Trash."

**Comment by Phillipus** [comment]
This is because of your Mac's security settings. See http://www.statsilk.com/support/faq/resolving-mac-only-error-file-damaged-and-should-be-moved-trash

**Comment by castigf** [comment]
Thanks. However I had to change the settings from the command line, as the GUI did nit allow mw to do so
