### ISSUE TITLE
Defined colors disappear afterr restarting the program

### ISSUE THREAD

**Issue by pujanzi** [archimatetool/archi#169]
Hello!
When I define custom colors in the pallette, they are only available until the program is open. As soon as I close and reopen it again, the whole custom colors (defined colors) are gone. This is annoying since it is timely to get the right code again. Thanks!
Cheers, pj

**Comment by jbsarrodie** [comment]
Hi,

As I also find this annoying, I've just done a new search on this topic. It seems that there is some (new since eclipse 3.8) methods on org.eclipse.swt.widgets.ColorDialog to get/set the custom colors. These are getRGBs() et setRGBs().

Maybe we could now save them in a preference file.

**Comment by pujanzi** [comment]
That is a brilliant idea! :)

**Comment by Phillipus** [comment]
> It seems that there is some (new since eclipse 3.8) methods on org.eclipse.swt.widgets.ColorDialog to get/set the custom colors. These are getRGBs() et setRGBs().

This works on Windows. On Mac and Linux, custom colours are persisted anyway.

However, this will be supported in Archi 4.6 (as per JB's suggestion of saving them in the preference file)

So I'll close this one as "fixed".
