### ISSUE TITLE
Nesting of Realization relations for Motivation elements

### ISSUE THREAD

**Issue by pjjv** [archimatetool/archi#172]
**Motivation elements** when used as target of **Realization** relation do not create relationship by nesting source elements. 
When created **Realization** relationship manually, the validator still complies with _Visual Nesting_ warning.

**Comment by jbsarrodie** [comment]
Hi,

Nesting for realization is defined as **target nested inside source**, so you shoukd nest the motivation ekement (eg. Requirement) inside the Core Concept (eg. Application Component).

It seems your are doing the opposite. Can you confirm ? 

Regards,

JB

**Comment by pjjv** [comment]
Yes, you're right. I swapped the from/to.

So I withdaw this
