### ISSUE TITLE
Nesting Relations in Grouping a/o Plateau Elements

### ISSUE THREAD

**Issue by pjjv** [archimatetool/archi#173]
When adding any relation between nested elements in Plateau/Grouping, no New Relationship is offered (no pop-up window).

If manually adding aggregation/composition relationship, it works fine. Tested on Example 1, p. 21 of the Specification.

I would be usefull if ARM will be enhanced for adding relationships inside Grouping/Plateau Elements.

**Comment by Phillipus** [comment]
Can you give steps to reproduce? I'm seeing the dialog when adding elements.

**Comment by pjjv** [comment]
I use the Example 1 from Specification on p. 21:

1) Grouping created
2) Process 1 created nested -> ARM opens
3) Process 2 created nested -> ARM opens
4) Triggering relation between Process 1 and Process 2 -> NO ARM
...

**Comment by Phillipus** [comment]
OK, I understand. It's the relationship between the relationship and its source/target element's parent. Not so easy to do.

**Comment by pjjv** [comment]
I thought about testing both ends, if they are both nested, then the relation should be nested as well. I know it is har to test relation alone.

Only an idea ...
