### ISSUE TITLE
[Feature] Change Appearance of all selected components

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#174]
When multiple components have been selected, changing the appearance (e.g. font size) should change the formatting for all selected components.

**Comment by Phillipus** [comment]
If you use the menu item Edit->Font... you can do this.

**Comment by smileham** [comment]
Then ignore me! (plus you just saved me a lot of time!)

Cheers

Steve

**Comment by jbsarrodie** [comment]
_If you use the menu item Edit->Font... you can do this._

I didn't know this! I must admit I never use menu, only keybord and toolbar....

Thank you !
