### ISSUE TITLE
Notation cues

### ISSUE THREAD

**Issue by pjjv** [archimatetool/archi#178]
When notation cues (left topcorner letters MSBAIPT) will be available?

**Comment by Phillipus** [comment]
Do people really need these? Personally, I find them to be...unnecessary. ;-)

**Comment by pjjv** [comment]
As I am using most of the time uncolored icons,
I found the 'I' cue helpful to distinguish for example Implementation Event from its BAT variant,
but most of the time it helps me not to distinguish the BAT items, so generally agree.
