### ISSUE TITLE
Model Tab - renaming a view or element move view when jumping to end of line

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#179]
Hi there,

Haven't seen this raised but I might have missed it...

Another time consuming issue is when you are in the Model Tab and you rename a view or element, it does not move the view when jumping to end of line to edit a name or want remove the (copy) text after duplication... you have to use t he scroll bar to move to the  right or resize the Model Tab.

Would be great if it either scrolls to the right automatically or temporarily expands the Model Tab to show the entire name for editing.

Hope it is a small quick change because it will save a lot of time...

**Comment by theunsfvo** [comment]
Can somebody have a look at this? I think it is done somewhere else in the app already, but having to manually scroll on the scroll bar to to view the name is very cumbersome...

**Comment by Phillipus** [comment]
Fixed. Text cell editor uses new API and scrolls text box as text expands.

Will be in next version.

**Comment by theunsfvo** [comment]
Excellent! Thanks Phil.

Thanks,
Theuns

"I love deadlines. I like the whooshing sound they make as they fly by."
Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *

**Comment by Phillipus** [comment]
In 4.1.0
