### ISSUE TITLE
Copy-paste does not tag duplicated objects

### ISSUE THREAD

**Issue by Ridderby** [archimatetool/archi#184]
In Archi 4.0.0 Beta 4:

When I copy and paste objects they do sometimes (as expected) duplicate but in this version the duplicates is not marked with "(copy)" as it used to. One have to be observant to the tree to see if there was a duplication or not.

**Comment by ajosey** [comment]
I thought this was the idea, when you want to use the same object in another view, you would copy and paste from an existing view to another view (and its not marked as a copy). If you copy and paste in the same view then it is indeed a copy and marked as so.

**Comment by Ridderby** [comment]
Sorry, I misread my complex project. It marks the copy with copy alright if it makes a copy.

Ajosey: you are right, this is what I normally want but the  the pate operation does automagic and in some cases it does make a copy and in that case the copy shall be marked with "(copy)". And it is.

I support the possibility to chose if I shall make a copy or a use the same object. There seems to be a request on that somewhere. 


Please close this issue as invalid or so.

**Comment by Phillipus** [comment]
Closing as requested.
