### ISSUE TITLE
[Feature] Allow diagram view to pan outside diagram

### ISSUE THREAD

**Issue by peso** [archimatetool/archi#185]
When a diagram gets too tight, you need to increase the diagram size. That is easiest done by simply adding elements outside the current diagram borders, thereby increasing the diagram. However, this is not allowed in Archi 3.3.2. Instead you have to add the new element inside the current view of the diagram, then grab the element in one side, and drag the other part of the element outside diagram borders.

A simple fix would be to allow the diagram view to pan outside the diagram.

**Comment by Phillipus** [comment]
This is a limitation of the Eclipse graphical framework. A quick way to get more space is to Ctrl and scroll wheel to make zoom 25% or 50%.

**Comment by FlightControl-User** [comment]
> This is a limitation of the Eclipse graphical framework. A quick way to get more space is to Ctrl and scroll wheel to make zoom 25% or 50%.

This suggestion works, but is not effective and user friendly. You lose focus in a working session and it just confuses many people watching your screen in a presentation or workshop.
I'll try to get a fix in place and go for a pull request.
