### ISSUE TITLE
[Feature Request] Gap & Deliverable Figure alternative shape option

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#188]
Please can we have alternative shapes for these two elements? It becomes very difficult to resize with various text lengths, align and position with other elements when the funny bottom shape overlapping with text... give it an alternative shape like with services so others can be nested and resizing can be done easier...

**Comment by Phillipus** [comment]
There are no standard alternatives for these in the spec - http://pubs.opengroup.org/architecture/archimate3-doc/apdxa.html#_Toc451758116
