### ISSUE TITLE
Realisation relationship not allowed between Technology artifact and Application Data Object

### ISSUE THREAD

**Issue by pannema** [archimatetool/archi#190]
I have tried in both Archi 4.0.0 beta3 and 4 to create a realisation relationship between an artifact and data object and it is not allowed... although I believe it should. Could you help me out?

**Comment by Phillipus** [comment]
Is the relationship in the matrix in the ArchiMate 3 spec? Or is it one for the list @jbsarrodie ?

**Comment by pjjv** [comment]
It is already on @jbsarrodie  list.

@pannema - temporarily you can allow it if you edit relationships.xml file inside model plugin and add allowance for this and other missing relationships

**Comment by pannema** [comment]
Thanks both Phillipus and pjjv! The workaround works as a charm :-)
