### ISSUE TITLE
Additional relationships missing from the relationships.xml file

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#191]
From https://www.linkedin.com/groups/50758/50758-6225768676843413505:

Colin Coates: Maybe the following relationships missing from your relationship table? ;-) 

Artifact realizes Data Object [previously reported in https://github.com/archimatetool/archi/issues/190], 
Technology Process realizes Application Process, 
Technology Process realizes Application Function, 
Technology Function realizes Application Process, 
Technology Function realizes Application Function, 
Technology Interaction realizes Application Process, 
Technology Interaction realizes Application Function, 
Technology Interface realizes Application Interface.

Best regards,
Michael Herman (Toronto)

**Comment by Phillipus** [comment]
Thanks, I think we can add these to https://github.com/archimatetool/archi/issues/164

**Comment by mwherman2000** [comment]
NOTE: Jean-Baptiste is in contact with Gerben who has another list that he and I have been working as part of my project to graphitize the ArchiMate relationship matrix. .."kill as many birds as possible" ...doesn't sound right but get the idea.
