### ISSUE TITLE
Error On Importing Exported CSV

### ISSUE THREAD

**Issue by cwknox** [archimatetool/archi#192]
I am using Archi to track an evaluation of a client environment.  Currently the findings are in a spreadsheet.  I created blank findings as Assessments and then exported the model as a CSV.  I then edited the elements.csv to add the Name and Documentation fields.  I wasn't able to do it because the import generated an error:

> Invalid character found in ID: 4.892E+092 

Not **the** most cryptic error message I've seen, but it's in the top ten!

Experimenting further, I found that importing the same elements.csv with no changes generated the same error.  In other words, the error is in my existing model and was part of the successful export.  Same error occurs in both Version 3.3.2 (Build 201603061150) and Version 4.0 (Build 201612151122), and it occurs with different models.  Do I need to tweak the CSV file prior to importing?

**Comment by Phillipus** [comment]
I'd need to see the offending CSV line and ID to see what's going on here.

**Comment by cwknox** [comment]
I exported and tried importing unchanged a model built from the canvas at http://forum.archimatetool.com/index.php?topic=271.0 (OODA Loop Canvas) and Archi4 generated the same error attempting to import elements.csv.  All I did was create the model from the canvas and export it.  No additions.

**Comment by Phillipus** [comment]
It seems that many of the IDs used in the OODA file have been manually created. For example - f7aadddd;b59dcacf;0.1 - thus the CSV import does not support these characters. This is not supported.

**Comment by Phillipus** [comment]
In the case of ID of type "4.892E+092" it may be that you exported it into Excel and it converted the ID to this format

**Comment by cwknox** [comment]
Weird.  I got the same results even when the file never saw Excel.  I tried to import the exported file with no changes.  In the first case I exported and updated only the Name and Documentation fields, hoping to use the same IDs.  I had not done anything with the OODA file except open it.  I'll look for a better example.

**Comment by Phillipus** [comment]
If one exports from Archi and then imports without any editing, all the IDs should be OK.

IDs in Archi 3 are like "016a6685" and in Archi 4 like "a792b916-3a84-436c-a342-89ebac39192d" so these are safe. To get an ID like "4.892E+092" one would have to edit it manually or perhaps Excel converted it. The OODA file seems to have some user-created IDs.

**Comment by cwknox** [comment]
Interesting.  This may be an Excel thing.  I opened the exported CSV and had this:

"48920e88","Assessment"

After editing with Excel (but saving as a CSV) the same line looks like this:

4.89E+92,Assessment

Note the loss of the quotes and recasting the value as Scientific Notation.  Trying it with a Libre Office.

**Comment by Phillipus** [comment]
When opening CSV data with Excel it makes some "clever" guesses at the data in each column. In this case it thinks it's a scientific number. Better to use the menu item "Data -> From Text" menu item where you can specify the correct data format for each column.

**Comment by cwknox** [comment]
Yes, that's what is happening.  And Libre Office is doing the same "clever" thing.  There's a data processing principle that seems to have been lost somewhere:  Leave things like you found them!

**Comment by jbsarrodie** [comment]
Hi,

Have you tried the option "Use Excel leading zeros/spaces workaround" when exporting. It should generate a CSV that can be imported into Excel (and libreoffice). The trick is that it **has** to be imported into excel **and** saved as another CSV to be imported back in Archi.

**Comment by Phillipus** [comment]
Closing. Please re-open if still an issue.
