### ISSUE TITLE
Specialization gets opposite direction when adding an sub type element using ARM

### ISSUE THREAD

**Issue by tespersson** [archimatetool/archi#193]
When adding an element like a Application Component, Data Object or Capabilitiy the **Specialization** relationship gets assigned with the opposite direction (arrow should point to the "base type" from the "sub type")
- first add the element to a "container" element, then move it outside the container element and you see that it got the wrong direction

**Comment by Phillipus** [comment]
Which version of Archi is this?

**Comment by Phillipus** [comment]
ArchiMate spec 3 says:

"Alternatively, a specialization relationship can be expressed by nesting the specialized element inside the generic element."

@jbsarrodie What do you think?

**Comment by tespersson** [comment]
Archi 4.0.0 beta 5 (also beta 4) both on Mac and Windows

best regards Tord

**Comment by jbsarrodie** [comment]
Hi,

I confirm that there's a "bug". Specialization is now allowed as nesting, but the direction is "reverse": in this specific case, the outer concept is the target of the relationship and the inner one is the source (the logic is the opposite for all other relationship that can be nested).

**Comment by Phillipus** [comment]
Thanks J-B. Is this the only case?

**Comment by jbsarrodie** [comment]
Yes, that's the only exception regarding direction of nesting.

**Comment by Phillipus** [comment]
OK, thanks. I'll get it fixed... :-)

**Comment by Phillipus** [comment]
I've committed a fix. Will be in next beta build (later this week).

**Comment by Phillipus** [comment]
Archi 4 beta 6 contains the fix. Closing. Re-open if needed.
