### ISSUE TITLE
Path, Communication Network & Distribution Network alternative shapes

### ISSUE THREAD

**Issue by pjjv** [archimatetool/archi#194]
Is there a plan to integrate the Path, Communication Network & Distribution Network alternative shapes for 1-to-1 connectivity?

**Comment by Phillipus** [comment]
Tricky. These are nodes not edges (elements not relations) so one would need to able to link them to other elements with relationships.

**Comment by pjjv** [comment]
@Phillipus,

I know, but it looks better, especially for:
- the supply chain Distribution Network
- combined Path/Communication Network diagrams

Analysis of trickiness:
1) Graphically, it is relation between 2 nodes on single View
- so allowance of its change should be constrained
- when created, it should check all the associated/aggregated Path&Network nodes before creating new one
2) Internally (model), it is <<relation, node, relation>> linking these 2 nodes
- probably it need to pop-up ARM to select which relation (association, aggregation) is used

**Comment by jbsarrodie** [comment]
Hi,

Small remark: this notation always means association, never aggregation/composition (these are used to link equipments that support the path/communication network).

**Comment by pjjv** [comment]
@jbsarrodie 
Thank you for explanation, this makes it easier:

1) Graphically
- Allow to change visual form only if view contains association-element-association
- when creating, check existence of respective element linked by association and offer it instead of the new one (but heartbeat networks can be duplicit)
2) Internally
- association, element, association and no need of ARM

**Comment by Phillipus** [comment]
Implemented in 4.9
