### ISSUE TITLE
When I drag a Grouping element from the model browser onto a View, its relationships are not being drawn

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#195]
If I treat a Grouping more or less like a full-fledged ArchiMate 3.0 element and for example using Composition Relationships to relate multiple Business Actors to the Grouping element - then create a new View, drag the Business Actors onto the View and then drag the Grouping element onto the same new View, the Composition Relationships are not being drawn when they are expected to be drawn (from a consistent user experience perspective).

Best regards,
Michael Herman (Toronto)

**Comment by Phillipus** [comment]
There must be a case where this is not working for you. I just tried it and it worked for me. Can you get a reproducible series of steps?

**Comment by mwherman2000** [comment]
My apologies ...it appears I had a duplicate element in my model and the element I dragged onto the view did not in fact have any relationships.
