### ISSUE TITLE
When I give a Grouping element a long name, the name doesn't wrap like it does for other elements

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#196]
When I resize a Grouping element to be the same default size as another element (e.g. Business Actor) and I give the Grouping a long name (e.g. Bridgewater Associates [Business Organization]), the text of the name isn't being wrapped when it is drawn on the face of the Grouping element.

**Comment by Phillipus** [comment]
The text control in a Grouping is a single-line one, unlike the others. I'll take another look at this and see if there is a better way to do it.

**Comment by Phillipus** [comment]
Fixed in 4.4
