### ISSUE TITLE
[feature] Preference for default figures text alignment

### ISSUE THREAD

**Issue by smeagol74** [archimatetool/archi#197]
My proposal is to add configurable preference for default figures text alignment horizontal and vertical, so new figure use them instead hardcoded values.

For example, I prefer for most figures vertical align for captions to be middle not top as for now, and just in some rather rare cases (really only when figure contains some others figures in it for grouping, aggregating and so on) to have top aligned captions.

**Comment by hercules808** [comment]
Is that something you would consider adding (albeit a low priority)?

For example I generally select all elements and do: Edit > Text position > Centre

I think it looks cleaner as it moves the text label away from the top-right ArchiMate icon.

It would be great if that was somehow configurable as a default via: Edit > Preferences > Diagram > Appearance

Admittedly doing it manually as I describe above is not overly onerous...

**Comment by Phillipus** [comment]
I'll close this because I just implemented this now in Preferences (Diagram > Appearance). Will be in the next version.
