### ISSUE TITLE
HTML Report: Link to specific view

### ISSUE THREAD

**Issue by stigbd** [archimatetool/archi#199]
Hi,

In the html report I would like to get a link to a specific view in the project's view-folder. This would come in handy when I would like to point the reader to a specific viewpoint in my projects.

When the user click on the link, he is taken to the HTML Report with the given view displayed.

I hesitate to label this issue a 'feature request' as I am not entirely sure it cannot be done in the current version of Archi. (I am using version 4.0.0, build 201701161137)

**Comment by vic51** [comment]
FYI, I implemented this feature by altering model.js. See: https://github.com/archimatetool/archi/issues/365#issuecomment-762456735
