### ISSUE TITLE
Text overlaps alternate figure in application component

### ISSUE THREAD

**Issue by archofit** [archimatetool/archi#200]
It seems like the bounding box is too var left for the text in the alternative figure version of the component element.

Figure 1 - Here's an example where the text is too far left and overlaps the figure. 
Figure 2 - Using the text alignment options (to align right) improves but does not fix the overlap.

![2017-02-14 22_36_46-archi](https://cloud.githubusercontent.com/assets/23109329/22960856/ef5e0962-f306-11e6-86b0-b838a4eaabc7.png)
![2017-02-14 22_42_02-archi](https://cloud.githubusercontent.com/assets/23109329/22960857/ef60cd64-f306-11e6-86ac-831b50736fc6.png)

**Comment by Phillipus** [comment]
That doesn't look nice, does it?

Fixed in next beta version.
