### ISSUE TITLE
Zoom above 100% switches the "Text Position" from target to source in a serving relation

### ISSUE THREAD

**Issue by gbonazzoli** [archimatetool/archi#201]
In both Archi 3.x and Archi 4.0 beta if you zoom above 100% the label in a "serving relation" switches the "Text Position" from target to source and viceversa.

"Text Position" middle is not affected by the bug.

I Attach two screenshots to better illustrate the problem.

Regards.

![archi_zoom_200_percent](https://cloud.githubusercontent.com/assets/17742862/23090597/a7e046c0-f5a1-11e6-9b65-e4a5afe1d85c.png)
![archi_zoom_100_percent](https://cloud.githubusercontent.com/assets/17742862/23090598/a7ebdff8-f5a1-11e6-9026-09c5172b3b6b.png)

**Comment by jbsarrodie** [comment]
Fixed. Will be in Archi 4.2.1
