### ISSUE TITLE
Issue with Search in combination with a huge number of elements & relations

### ISSUE THREAD

**Issue by ghost** [archimatetool/archi#203]
I just loaded >75000 elements/relations from our CMDB into Archi. And Archi perfoms very good with the exception of Search (and the Visualiser when the Depth is larger than 3 but that's logical) 

The problem is that Search start searching directly after I've typed the first letter and that stalls Archi for a moment. So I can't see what I type next and must wait a bit. Solution would be not to start the search on the first few letters that are typed in the Search box or to create an option in the preferences to disable the "auto-"search feature. I prefer the disabling in the preferences solution.

Regards,
Peter

**Comment by Phillipus** [comment]
OK, but >75000 elements/relations is probably pushing the limits of an app that loads the whole model into memory. :-)

**Comment by MapBakery** [comment]
It's not too bad. Opening the model takes 15 minutes but after that I don't notice much problems with the memory usage. Archi uses about 200-300Mb RAM. Only during the import of the .csv data the memory usage went up to about 600 Mb at one point. But that was still no issue on my laptop (with 16GB but Windows 32 so effectively 4GB RAM)

**Comment by MapBakery** [comment]
I'm still curious to know what the "Ok, but..." answer means. Does it mean "Ok it will be implemented someday" ? :-)

Regards,
Peter

**Comment by Phillipus** [comment]
At the moment, a stable version 4 release is the priority. After that, features/issues need to be gathered and prioritised for 4.x version(s).

**Comment by anderstn** [comment]
We don't have 75000 elements yet, but I can already tell that this would be a feature we will need down the road.

**Comment by Phillipus** [comment]
I spent some time on this problem today.

I've introduced a small delay between key presses and some other optimisations and it seems to work well with larger models.

It needs more testing but, if all goes well, should be in the next version.

**Comment by Phillipus** [comment]
In the next version there will be an option in General Preferences to complete the search query when the Return key is pressed. The default will be auto-search as you type (current behaviour) with a small delay between key presses (which, in my tests, works well with many tree nodes).

**Comment by Phillipus** [comment]
Fixed in 4.6
