### ISSUE TITLE
Import Export issue with created IDs

### ISSUE THREAD

**Issue by nfigay** [archimatetool/archi#213]
Version 4.0 Build 201703301449
Starting to work with Archi 4 Beta 8 of the 30th of March 2017, I experimented import/export  Model To Open Exchange File, Exporting a model and re-importing it.
I had the message: Error Importing File: Occurrences multiples de la valeur d'ID xxxx.
Looking at the .ArchiMate file, it occurred that after export and reimport, each model element is duplicated, one with the initial id  and the other with the same id prefixed with"id-" E.g. "2d33f1cb-5337-409a-b69b-d7f7b4a45ea2"  and "id-2d33f1cb-5337-409a-b69b-d7f7b4a45ea2".
As a consequence, supporting chain of changes using different modeler doesn't work properly, as Id's are changed.

**Comment by Phillipus** [comment]
Not sure what you mean by "supporting chain of changes using different modeler". When Archi exports to Open Exchange File it prefixes "id-" to the identifier to ensure that the identifier is of proper ID type (http://www.datypic.com/sc/xsd/t-xsd_ID.html)

**Comment by Phillipus** [comment]
I'm unable to reproduce the error. I created a basic model in Archi, exported it in Open Exchange format, then re-imprted it as a new model. All was OK.

**Comment by nfigay** [comment]
I tried to reproduce the error but can't, don't remember the sequence of actions I made.
I attached the obtained file, test2.archimate.
I will take some time trying to reproduce what I made for obtaining  such a result.
Nicolas
[test2.archimate.zip](https://github.com/archimatetool/archi/files/908044/test2.archimate.zip)
