### ISSUE TITLE
Capability Map and Resource Map viewpoints

### ISSUE THREAD

**Issue by archofit** [archimatetool/archi#215]
A minor nit (which is hopefully all that is left in beta 8 :-) ...

The standard names the two strategy viewpoints dealing with capabilities and resources as,
"Capability Map" viewpoint
"Resource Map" viewpoint
while Archi leaves off the "Map" on the viewpoint names calling them simply "Capability" and "Resource" in the pull down in the Properties window.

**Comment by Phillipus** [comment]
Intended, as the elements allowed belong to those categeories, but the diagram is not really a map.

**Comment by jbsarrodie** [comment]
Hi,

@Phillipus in fact that's a map ;-) A typical Capability Map looks like this:

![Capability Map](http://image.slidesharecdn.com/solutiondesignframeworkandsolutiondesignscorecard-final-150421180425-conversion-gate02/95/business-value-measurements-and-the-solution-design-framework-18-638.jpg)

**Comment by Phillipus** [comment]
Ok, I can easily add "Map" to the text, but I was trying to avoid the situation where someone might say "I tried to draw a Capability Map like the one shown here, but I can only draw boxes and lines....when will you be implementing the map features...." ;-)

**Comment by archofit** [comment]
That's a very good question as I was trying to figure out how I'd use Outcomes and Resources given the many examples of capability maps out there which are really just a hierarchy of capabilities. The only relationships between those capabilities are some form of hierarchy of containment (composition, aggregation or grouping) or layering (again grouping).

Here's another example (from http://blog.bizzdesign.com/archimate-3.0-capability-mapping)
![image](https://cloud.githubusercontent.com/assets/23109329/24625717/7e9a07a0-1875-11e7-948e-7ad4ef7ad97a.png)

I cannot find any example of a capability map that includes not only capabilities, but also resources and/or outcomes.

**Comment by Phillipus** [comment]
Names changed with "Map" in next version.
