### ISSUE TITLE
Focus loss when editing with keyboard in the "Models" panel

### ISSUE THREAD

**Issue by florent-andre** [archimatetool/archi#216]
Version 4 
build : 201702211434

Use case : 
* click on a item in the "Models" panel
* move with arrows to a component name to edit
* hit F2
* type some letters
* Enter 

The focus is lost so you can't continue your keyboard editing. 

Thanks for this great piece of modeling tool !

**Comment by Phillipus** [comment]
Yes, that is annoying.

Fortunately, it's an easy fix so closing this and the fix will be in the next build. :-)
