### ISSUE TITLE
Device figure changed after opening old file in Archi 4

### ISSUE THREAD

**Issue by gatcip** [archimatetool/archi#218]
I have an archi file created by Archi 3 with "Device" figures as 3-D boxes in diagrams.
When I open this file in Archi 4, devices are displayed as old-fashioned.
It seems Archi 4 toggles figures.

**Comment by Phillipus** [comment]
This is because I changed the default figures in Archi 4. After some consideration, I will change the figure defaults for Device, Node, and Application Component to how they are in Archi 3 so that users can continue working as they are used to.

**Comment by jbsarrodie** [comment]
Hi

I m not sure thats the reason... I experienced similar issue when **importing** an archimate 2 model : alternate figures are reset to some default when they are converted instead of keeping choosen value.

**Comment by Phillipus** [comment]
No, it is the swapped defaults. I put them back to how it is is in Archi 3 and it's back to normal.

**Comment by jbsarrodie** [comment]
That s strange and I ll look at it because there's no reasons an element on which I explicitely set the figure would be affected by defaults (which are not ised in this case)...

**Comment by Phillipus** [comment]
Because type="1" loads different figures. I know, ;-)

**Comment by Phillipus** [comment]
To be clear - it's the defaults in the figure drawing code, not user defaults.
