### ISSUE TITLE
Shapes not appearing correctly when placed over other shapes

### ISSUE THREAD

**Issue by andrmul** [archimatetool/archi#221]
Archi 4 beta 8. I have a business object that is associated with multiple capabilities. When I move this business object over the top of two or more of the associated capability shapes, the shape often (but not always) renders incorrectly. Please see screenshots x 2.

![business object associated to multiple capabilities - correct appearance](https://cloud.githubusercontent.com/assets/27257046/24889565/389f61e0-1e9d-11e7-8716-62c593e9d227.PNG)
![business object associated to multiple capabilities - incorrect appearance](https://cloud.githubusercontent.com/assets/27257046/24889564/389d9ab8-1e9d-11e7-8a4c-34a6866f50e9.PNG)

**Comment by Phillipus** [comment]
Hi, this is not a bug. In the second case it is because you have dragged the BO _into_ the Processcing shape, and it has become a child object.
