### ISSUE TITLE
Archi 4 Beta 8

### ISSUE THREAD

**Issue by alonsop2017** [archimatetool/archi#223]
Crashes as soon as it starts.  Log file attached...
[Archi 4 beta 8.txt](https://github.com/archimatetool/archi/files/935143/Archi.4.beta.8.txt)

**Comment by Phillipus** [comment]
I see:

!ENTRY org.eclipse.update.configurator 4 0 2017-04-19 09:02:21.413
!MESSAGE Unable to access file "plugins/org.archicontribs.database_v2.0.0.alpha3.jar!META-INF/MANIFEST.MF".

I don't think this is a bug related to Archi beta 8 out of the box. Please re-test with a clean installation. Ensure you have unzipped correctly.

**Comment by alonsop2017** [comment]
Hi Phil,

I tried opening the .jar file and it says it is corrupted.  I unzipped the
installation twice and received the same error.

 I will download the zip again to see if it was a download issue.

Regards,

*Alonso Pérez*
PA: +507-6-483-5515
CA: +1-437-888-4554
US: +1-305-280-2429
Skype: alnspp

**Comment by Phillipus** [comment]
You shouldn't be opening any jar file. Are you talking about the database plugin? If you are, please report bugs on that GitHub project.

Regarding downloading Archi zips, there is an MD5 checksum file on the website to ensure it is not corrupted.

**Comment by alonsop2017** [comment]
I tried to open the .jar file just to see if there was an issue.  There is
one.  I will delete it to see if this resolves the issue.

*Alonso Pérez*
PA: +507-6-483-5515
CA: +1-437-888-4554
US: +1-305-280-2429
Skype: alnspp

**Comment by jbsarrodie** [comment]
Hi,

I think that what Phil is saying is that this jar **is not part of Archi** (it is part of the database plugin developed by Herve). And as such, this means that you haven't a clean install of Archi 4 beta 8 but a mix of Archi and other plugins.

So first try Archi alone (just unzip the archive provide on Archi website), and it this runs fine (it will) then try adding your other plugins, making sure you use versions that are known to be compatible with Archi 4. If you face any issues at this stage, then contact plugins owner (e.g. me for Grafico, Herve for database).

Regards

**Comment by Phillipus** [comment]
Thanks for the clear explanation, JB!

**Comment by herve91** [comment]
Hi Alonzo,

The error messages are evry weird. I've never seen them. I fully agree with JB and Phil. Please install Archi without my database plugin and have it working without my plugin. Then, copy my jar file into Archi's plugin folder and restart Archi.

If Archi stops working, then remove my jar file. If Archi works again, then it definitely comes from my plugin. In this case, I invite you to open an issue on my project github.

Best regards
Hervé

**Comment by alonsop2017** [comment]
Thank you Hervé,

I will try this by first deleting the folder in which Archi is installed to
make sure there is no debris left from the previous version.

I just downloaded it again and the MD5 matched.  The previous time it did
not match...

Will let you know if I am successful.

Thanks for your help.

*Alonso Pérez*
PA: +507-6-483-5515
CA: +1-437-888-4554
US: +1-305-280-2429
Skype: alnspp

**Comment by alonsop2017** [comment]
I did it (deleted the previous install) and it worked  fine!.  Thanks a lot.

*Alonso Pérez*
PA: +507-6-483-5515
CA: +1-437-888-4554
US: +1-305-280-2429
Skype: alnspp

**Comment by Phillipus** [comment]
OK, let's close this.
