### ISSUE TITLE
Beta 9 released April 24 does not start

### ISSUE THREAD

**Issue by jnerune444** [archimatetool/archi#225]
X64 machine, W10. Java 1.8
See log file
[Arch4 B9 start log.txt](https://github.com/archimatetool/archi/files/955457/Arch4.B9.start.log.txt)

**Comment by Phillipus** [comment]
Any other info? Do you have any other external Archi plugins installed? Have you tried re-downloading and unzipping somewhere else on your machine?

**Comment by jnerune444** [comment]
My JRE was 1.8.131

 

I redownloaded the beta.

I have no plug-in installed

 

I copied the content of the ZIP file to my Archi4 folder, EXCEPT for the JRE folder (which seemed to be 1.8.101)

 

The program started normally. No log file was created.

**Comment by Phillipus** [comment]
You need to use the JRE provided in the zip file because it's 32-bit. Using your own 64-bit JRE won't work.

**Comment by Phillipus** [comment]
Is the issue resolved for you now?

**Comment by jnerune444** [comment]
The issue is resolved for me, but maybe not for you.

 

What made it work was using the 64-bit JRE instead of the 32-bit JRE supplied with the Beta, contrary to what you said in an earlier reply..

 

I also installed the beta on a 32-bit Windows 7 machine, and it works ok.

 

Thanks for your quick reply.

**Comment by Phillipus** [comment]
I've always found that it won't work with 64-bit Java
