### ISSUE TITLE
Feature proposal: Figures at Open Exchange File Import

### ISSUE THREAD

**Issue by gatcip** [archimatetool/archi#226]
It seems that export file does not contain info about the figure in diagram, as it is a tool feature, not an Archimate feature. But colours are tool feature, too and they are contained in the export file. 
Anyway, Open Exchange File Import could set the figure to the default figure assigned in Preferences->Diagram->Default Figures .

**Comment by Phillipus** [comment]
Sorry, I don't understand the issue. What information are you referring to?

**Comment by gatcip** [comment]
Tool 's default figure is used. But I meant to use the default figure set in the Preferences->Diagram->Default Figures.
I have set the second figures for Node and Device. Then I exported my test model with diagram containing node and device - both having the shape set to the second figures. After importing the exported file, both node and device have had the shape as the first (tool default) figures

**Comment by Phillipus** [comment]
Can't be done. That setting is particular to Archi, and would not be understood by other tools.

**Comment by gatcip** [comment]
yes, exactly.

**Comment by Phillipus** [comment]
OK, I was confused by the suggestion of exporting this info. I will fix it in the next version of the exchange format to use defaults as set by the user.

**Comment by Phillipus** [comment]
Fixed. Closing.

**Comment by gatcip** [comment]
Phil, the first two sentences of my proposal are really confusing.
Thanks.

**Comment by Phillipus** [comment]
No problem. Next version of Archi 4 with the new 3.0 exchange version will have the fix.
