### ISSUE TITLE
insert my own imagen

### ISSUE THREAD

**Issue by Irene1153** [archimatetool/archi#228]
Hi,

It's possible insert my own simbology for disign my EA.

Thanks,

**Comment by Phillipus** [comment]
There is not enough information here to know what you are asking. Please Edit the title and provide a detailed description.

**Comment by jbsarrodie** [comment]
My understanding is that the question is : Is-it possible to add new concepts with associated figure and/or icon ?

And the answer is : not for the moment

JB
