### ISSUE TITLE
[Bug] Full screen does not respect the monitor choice

### ISSUE THREAD

**Issue by Grinderofl** [archimatetool/archi#229]
Archi 4: 201705031219

When selecting "View" -> "Full Screen", or by pressing F11, the primary display is used instead of the display Archi is on.

Could we do anything about that please? Don't want to have to change primary display whenever using multiple monitors to get full screen on the right display.

**Comment by Phillipus** [comment]
It's not something I can test myself as I have only one monior. If someone would like to contribute a solution that would be helpful. The relevant class is:

com.archimatetool.editor.diagram.actions.FullScreenAction

It may be on line 179:

fNewShell = new Shell(Display.getCurrent(), style);

**Comment by Phillipus** [comment]
Fixed.
