### ISSUE TITLE
[Bug?] When editing a view, deleting an element from the model should warn if it is used elsewhere

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#234]
When a user delete an element from the model tree, a warning is shown if the element is used elsewhere. The same behavior should exist when a user edits a view and decide to delete an element from the model (using the context menu).

**Comment by Phillipus** [comment]
Not a bug, just not implemented. Yet. ;-)

**Comment by Phillipus** [comment]
Fixed.

When? Next release.
Cost? 1 pint of beer

;-)
