### ISSUE TITLE
This issue is used to store images used in my wiki pages

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#235]
![genericfiguredrawing](https://cloud.githubusercontent.com/assets/5757396/26219982/352a2a90-3c11-11e7-8745-ec937e1b3540.png)

**Comment by jbsarrodie** [comment]
CSS theme
![Archi-Theme](https://user-images.githubusercontent.com/5757396/65417231-df08c580-ddf9-11e9-8779-a9006dd86261.png)

[eos.css.txt](https://github.com/archimatetool/archi/files/3641604/eos.css.txt)

**Comment by Phillipus** [comment]
You can add an image to a comment in an open issue, and copy and paste the link without saving the comment.

**Comment by jbsarrodie** [comment]
.. But it's more difficult to find it again later ;-)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/65491644-c4912380-deaf-11e9-8822-be3174d63931.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/65493045-569a2b80-deb2-11e9-86d7-7e86e4f6c0db.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/65493648-8990ef00-deb3-11e9-935a-cfc8157a22d2.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/65493764-cceb5d80-deb3-11e9-9bae-cd140970da76.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/65527667-51110580-def3-11e9-88bb-bbab1baa3f74.png)

**Comment by jbsarrodie** [comment]
A [JGit](https://www.eclipse.org/jgit/) based command line tool (created with [Launch4J](http://launch4j.sourceforge.net))
[jgit-20200103.zip](https://github.com/archimatetool/archi/files/4019889/jgit-20200103.zip)

**Comment by jbsarrodie** [comment]
[Notepad2](http://www.flos-freeware.ch/notepad2.html) configuration file to use Javascript syntax highlighting with jArchi scripts (`.ajs`).
[Notepad2.ini.zip](https://github.com/archimatetool/archi/files/4019909/Notepad2.ini.zip)

**Comment by jbsarrodie** [comment]
A strip down (and portable) version of [WinFontsForAll](https://apps.walialu.com/winfontsforall/)
[WinFontsForAll-portable.zip](https://github.com/archimatetool/archi/files/4019920/WinFontsForAll-portable.zip)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/85753715-c755c900-b70c-11ea-9579-b0041eeb9e3b.png)
![image](https://user-images.githubusercontent.com/5757396/85753826-e0f71080-b70c-11ea-87f3-40ce2f4cdda5.png)

**Comment by Phillipus** [comment]
Can I put pictures of cats here?

**Comment by jbsarrodie** [comment]
> Can I put pictures of cats here?

Of course, but don't expect me to use them on wiki pages ;-)

**Comment by jbsarrodie** [comment]
Sorry, still no cats...

![image](https://user-images.githubusercontent.com/5757396/85765304-47346100-b716-11ea-8afa-1dda53ac725c.png)
![image](https://user-images.githubusercontent.com/5757396/85765690-a003f980-b716-11ea-9064-0276f6165c17.png)

**Comment by jbsarrodie** [comment]
![Screenshot from 2020-11-03 20-57-38](https://user-images.githubusercontent.com/5757396/98034911-02cd7600-1e18-11eb-815d-1b0586d95b77.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/130416871-692ec206-a625-4ee6-9121-ceb0de981930.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/130464380-b6920af0-07d4-4c14-b030-895ded22c59c.png)

![image](https://user-images.githubusercontent.com/5757396/130464458-49c4d018-320d-4170-9692-7661d4c7fff0.png)

![image](https://user-images.githubusercontent.com/5757396/130464502-5efcc272-555a-48e9-be76-a2626f9c7bc0.png)

![image](https://user-images.githubusercontent.com/5757396/130464574-7d2a3e70-a490-46c2-969e-5fed3cab6ef9.png)

![image](https://user-images.githubusercontent.com/5757396/130464233-45d73ebf-ed62-4aa1-be2f-f01e0172a3b6.png)
