### ISSUE TITLE
Add preferences for UI system fonts and colours

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#239]
Add a preference page for customisation of the UI fonts and colours. This includes things such as Models Tree fonts. Note - there is already a preference for the default font to use for diagram components.

**Comment by rich-biker** [comment]
It would also be nice to be able to select multiple objects (shift-click) and change the Appearance fonts/colours for all. It currently only does it for the first selected object. Of course, the format painter can be used to paste formats.

**Comment by Phillipus** [comment]
You can change multiple objects fonts and colours from the main menu under "Edit".
