### ISSUE TITLE
Quality of images lower when exported on hi-res systems

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#240]
It seems that some images are not of good quality in HTML reports when exported from a machine with a hi-res screen.

**Comment by pds2208** [comment]
Example:

![baa807d9-2172-426c-9d95-3d84089cd65d](https://cloud.githubusercontent.com/assets/22938608/26529502/d543706e-43b8-11e7-9659-2308d9551fb3.png)

**Comment by Phillipus** [comment]
Is it the same for exporting images from diagrams? Or just in the HTML report? I think they all use the same methods to create the image.

**Comment by pds2208** [comment]
The same for exports to all bitmap formats (png, jpg, bmp). Absolutely fine with pdf and svg.

**Comment by pds2208** [comment]
PDF version attached.

[Default View.pdf](https://github.com/archimatetool/archi/files/1034230/Default.View.pdf)

**Comment by jbsarrodie** [comment]
This is clearly not the quality I have on windows (on my laptop images are exactly as seen on screen: perfect), so this is certainly due to hidpi or laptop graphic driver itself. Will be difficult to fix without having access to several hidpi computer...

**Comment by pds2208** [comment]
I’ve seen it on 4 different hi-dpi laptops, all with different graphic cards.

**Comment by Phillipus** [comment]
It may have something to do with the method used to create an image from the GEF/Draw2D canvas.

See com.archimatetool.editor.diagram.util.DiagramUtils

SVG and PDF export uses a different approach, SVG based.

**Comment by Phillipus** [comment]
Basically, the method used in com.archimatetool.editor.diagram.util.DiagramUtils to render the Draw2D figure to a graphics instance is not doing what it should do on a hi-res setup. Needs investigating.

This is, hopefully, one of those cases where the members of the open source community come together to help out and solve the problem. Marking as "help needed".

**Comment by Phillipus** [comment]
It might be worth checking how other Eclipse-based tools fare on hi-res (Obeo tools, XMind)

**Comment by pds2208** [comment]
Xmind is fine.

**Comment by Phillipus** [comment]
I had a quick look at XMind source code. I think they may be using an SVG export in all cases (SVG then PNG), but I may be wrong.

We need to test other Eclipse apps and plugins that export to raster graphics (PNG, BMP, GIF) on hi-res screens. Then see if any of these has solved the problem. As I said, I can't test as I don't have hi-res sreen.

**Comment by pds2208** [comment]
Fixed it:

Changed I’ve changed getImageData() to getImageDataAtCurrentZoom() and all is good. See below:


See: http://www.eclipse.org/eclipse/news/4.6/platform_isv.php 

• “Image#getImageDataAtCurrentZoom(): Returns an ImageData that contains the full-resolution pixel data at the current OS zoom level

Thanks
Paul

**Comment by Phillipus** [comment]
Good news. Would you like to create a Pull Request? If you do, please ensure that it only fixes this one issue. We can do other issues in different PRs ;-)

**Comment by maparicio** [comment]
Wow, that was quick! Thanks @pds2208 ! How long should it take until I can start using the fixed version?

**Comment by Phillipus** [comment]
@maparicio Please note that there is no "fixed version" at the moment. The procedure is to receive a Pull Request (PR), review and test the PR, commit and merge the PR. Then once this is approved we will schedule it into a future Archi version. This version will then need to have new build procedure, documentation, and so on.

**Comment by maparicio** [comment]
Yes, I figured that. That's why I asked. I guess you don't have a nightly build available then? I guess I could build it to get the fix earlier...

**Comment by Phillipus** [comment]
PR has been merged. Many thanks to @pds2208

**Comment by maparicio** [comment]
So... just pulled the latest commit and tests are failing

**Comment by pds2208** [comment]
No issues for me using my fork

HTTPS://github.com/paulsoule/archi.git

**Comment by Phillipus** [comment]
> So... just pulled the latest commit and tests are failing

Tests passed https://travis-ci.org/archimatetool/archi/builds/237173260

You'll need to be more specific about what is failing for you

**Comment by pds2208** [comment]
Just a thought…

If you guys are going to support this don’t you think you should be using kit that users use? Otherwise what’s the point?


On 29 May 2017, at 12:15, Phil Beauvoir <notifications@github.com<mailto:notifications@github.com>> wrote:


Good news. Would you like to create a Pull Request? If you do, please ensure that it only fixes this one issue. We can do other issues in different PRs ;-)

**Comment by Phillipus** [comment]
> If you guys are going to support this don’t you think you should be using kit that users use? Otherwise what’s the point?

I don't even know where to begin to answer this.

**Comment by Phillipus** [comment]
> Otherwise what’s the point?

Yep. What's the point. Closing.

**Comment by pds2208** [comment]
Okay, what can I do to help?

**Comment by jbsarrodie** [comment]
> If you guys are going to support this don’t you think you should be using kit that users use? Otherwise what’s the point?
> Okay, what can I do to help?

Well, when reading such statement I can only anser: just make a 2k donation to fund the right hardware to test and support it. Otherwise just stop writing such bullshit...

**Comment by pds2208** [comment]
Okay I can do that

**Comment by pds2208** [comment]
You have no idea who I am am and what I can offer and yet you dismiss me outright? 2k is nothing to me

**Comment by jbsarrodie** [comment]
> Okay I can do that

If that's the donation great ! Else, well... I think you can imagine that 2 guys working for free on a tool used by thousands of architects around the world can't afford buying the same hardware than every user reporting an issue (opensource and best effort...)

**Comment by pds2208** [comment]
Jesus how do you completely screw up an offer for help. I know, tell a potential donor to fuck off.  You can’t make it up...

**Comment by Phillipus** [comment]
When you email me saying "Stop being an arse" what did you expect?

I've no time for this bullshit power game.

**Comment by pds2208** [comment]
I mean for you to have a sense of humour.

**Comment by maparicio** [comment]
Attempting to build the master branch this fails:

```
testAddImageToZip(com.archimatetool.editor.utils.ZipUtilsTests)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: expected:<77> but was:<95>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.archimatetool.editor.utils.ZipUtilsTests.testAddImageToZip(ZipUtilsTests.java:153)
```
It would seem there's something related to this bug that fails. Could be because I have a hi-res display that's different than that of @pds2208  .

**Comment by Phillipus** [comment]
Don't worry about it. The tests run on a Travis CI server that uses a virtual screen at low res. If it bothers you, delete the line in the tests.

**Comment by maparicio** [comment]
Allright. Thanks @Phillipus !

**Comment by maparicio** [comment]
OK. Managed to build the affected library (com.archimatetool.editor) successfully sow now it's working. Thanks for all the help!

**Comment by Phillipus** [comment]
> The HTML-report still has the same problem, alas...

Please provide more details.

**Comment by maparicio** [comment]
HTML reports still have problems with images.  I.e. the source of this thread.
The fix by @pds2208  only fixed the image export from archi not the images in the HTML-reports.

**Comment by Phillipus** [comment]
The code was changed at line 344 of class com.archimatetool.reports.html.HTMLReportExporter:

loader.data = new ImageData[] { image.getImageDataAtCurrentZoom() };

So it uses the same fix as image export

**Comment by pds2208** [comment]
Not true. I tested all scenarios

**Comment by Phillipus** [comment]
> Not true. I tested all scenarios

I can only see the code that was changed. If it doesn't work I'm afraid I cannot test it.

**Comment by maparicio** [comment]
Hmm. That was pretty strange. I'll try again when I'm with my computer.

Den ons. 31. mai 2017, 17.14 skrev Phil Beauvoir <notifications@github.com>:
