### ISSUE TITLE
Quantity characters limit

### ISSUE THREAD

**Issue by mdvadim** [archimatetool/archi#242]
Hi all,
All long element names in the diagram in the main Arch window are displayed without cropping. However, when exporting from Jasper to * .PDF or * .doc, part of the text is clipped - the entire table looks one-line. All that one line does not fit into the report is not included. To us, the conclusion in the reports is extremely important and the inferiority of the generated report makes further work impossible.
Can we hope that the limit on the number of characters displayed in Jasper's reports at least the Word, even in the PDF will be removed?

![2017-05-30_10-32-31](https://cloud.githubusercontent.com/assets/29094130/26628782/a09189f0-4629-11e7-91e0-59067d3e9a61.png)
![2017-05-30_15-05-55](https://cloud.githubusercontent.com/assets/29094130/26628790/a738110c-4629-11e7-81aa-fd72cebf16dd.png)

**Comment by Phillipus** [comment]
Fixed.

Will be in the next release.

**Comment by mdvadim** [comment]
Hi dear Phil,
I so sorry I was out of my office. 
Problem restored for all type of elements in case Russian add. 
For example:
Native Archi:
![default](https://user-images.githubusercontent.com/29094130/28713065-cf442f80-73b7-11e7-9b7f-048ce01874c0.png)
Modify Archi:

![default](https://user-images.githubusercontent.com/29094130/28713166-383961cc-73b8-11e7-8309-569f23001c16.png)

![default](https://user-images.githubusercontent.com/29094130/28713175-40176876-73b8-11e7-8867-7dadaa0ef7bc.png)


Link to page with Russian craft: https://github.com/smeagol74/archi-ru

**Comment by Phillipus** [comment]
Sorry, I don't understand. Native Archi? Modify Archi? What's the problem?

**Comment by mdvadim** [comment]
I mean native is installed Archi without Russian language files. Modify is installed Archi with added Russian language files. If I create report in Archi without Russian I have a document without quantity character limit (you fix it in June), if in Russian Archi — report has cut rows.
----- Исходное сообщение -----
От: Phil Beauvoir <notifications@github.com>
Кому: archimatetool/archi <archi@noreply.github.com>
Копия: mdvadim <mdvadim@kemcardio.ru>, Author <author@noreply.github.com>
Отправлено: Fri, 28 Jul 2017 17:32:20 +0700 (NOVT)
Тема: Re: [archimatetool/archi] Quantity characters limit (#242)

Sorry, I don't understand. Native Archi? Modify Archi? What's the problem?

**Comment by Phillipus** [comment]
So, if I understand this, you are saying that the Russian version at https://github.com/smeagol74/archi-ru does not have the fix? I don't have any control of that version, so they need to update their version.

**Comment by mdvadim** [comment]
I just inform you, Phil. I wrote about problem to smeagol74.
----- Исходное сообщение -----
От: Phil Beauvoir <notifications@github.com>
Кому: archimatetool/archi <archi@noreply.github.com>
Копия: mdvadim <mdvadim@kemcardio.ru>, Author <author@noreply.github.com>
Отправлено: Fri, 28 Jul 2017 20:27:16 +0700 (NOVT)
Тема: Re: [archimatetool/archi] Quantity characters limit (#242)

So, if I understand this, you are saying that the Russian version at https://github.com/smeagol74/archi-ru does not have the fix? I don't have any control of that version, so they need to update their version.

**Comment by Phillipus** [comment]
OK!

I get it now 👍
