### ISSUE TITLE
ArchiMate 3 relationship rules as implemented in Archi 4

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#243]
There are known discrepancies between the published set of relationship rules in the ArchiMate 3.0 spec and Archi 4. This is because the rules are in the process of being revised and Archi contains the latest revisions. 

Any comments can be added to this issue.

**Comment by Katzele** [comment]
In version 4.0.1, a Trigger relationship cannot be drawn from a Work package to a Implementation event.

Although, this is allowed in the [Archimate 3.0 spec - relationship tables ](http://pubs.opengroup.org/architecture/archimate3-doc/apdxb.html#_Toc451758118) (4<sup>th</sup> table)

The error seems to be in the file com.archimatetool.model_4.0.1.201705261613\model\relationships.xml
`<source concept="WorkPackage">`
  ...
  `<target concept="ImplementationEvent" derived="" relations="o">`
should be
   `<target concept="ImplementationEvent" derived="" relations="fot">`

**Comment by jbsarrodie** [comment]
Relationship Tables published as part of ArchiMate 3.0 specs on the OpenGroup website are known to contain a large number of errors, so these should not be taken for granted. The Open Group ArchiMate forum is currently working on a new, corrected, version of those tables.

Archi 4.0 has been shipped with a better table coming from this current OpenGroup activity. Unfortunately, if this table fixes 99,99% of errors, few others have been introduced, and this includes the missing triggering from WorkPackage to ImplementationEven you've found.

A new version of Archi will fix this **when the Opengroup will officially publish the corrected tables**. In the meantime you can fix this issue by editing relationship.xml file by yourself.

**Comment by Katzele** [comment]
Thanks for the anwser ; it works. 

----- Mail original -----

De: "Jean-Baptiste Sarrodie" <notifications@github.com> 
À: "archimatetool/archi" <archi@noreply.github.com> 
Cc: "Katzele" <neidhardt.moreau@free.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Jeudi 1 Juin 2017 13:57:40 
Objet: Re: [archimatetool/archi] ArchiMate 3 relationship rules as implemented in Archi 4 (#243) 


Relationship Tables published as part of ArchiMate 3.0 specs on the OpenGroup website are known to contain a large number of errors, so these should not be taken for granted. The Open Group ArchiMate forum is currently working on a new, corrected, version of those tables. 
Archi 4.0 has been shipped with a better table coming from this current OpenGroup activity. Unfortunately, if this table fixes 99,99% of errors, few others have been introduced, and this includes the missing triggering from WorkPackage to ImplementationEven you've found. 
A new version of Archi will fix this when the Opengroup will officially publish the corrected tables . In the meantime you can fix this issue by editing relationship.xml file by yourself.

**Comment by Phillipus** [comment]
Closing.
