### ISSUE TITLE
Linux downloads are not in gzip format

### ISSUE THREAD

**Issue by Monezz** [archimatetool/archi#244]
The linux downloads on the website are just tar files and not gzip compressed tar files as the .tar.gz extention suggests.

> tar -xvzf Archi-Linux64-4.0.1.tar.gz 
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

Checking type

> file Archi-Linux64-4.0.1.tar.gz
> Archi-Linux64-4.0.1.tar.gz: POSIX tar archive

tar without gzip decompression

> tar -xvf Archi-Linux64-4.0.1.tar.gz 

works.

I would suggest either removing the .gz extention or gzip the tar file.

**Comment by Phillipus** [comment]
This has come up before.

The file is created with an Ant script. Here's the code that does this:

        <tar destfile="${lnx.gz}" compression="gzip">
            
        </tar>

And here's the Ant documentation for "tar":

https://ant.apache.org/manual/Tasks/tar.html

So, unless I'm missing something, I don't know how to do this differently.

**Comment by Phillipus** [comment]
See this discussion - http://forum.archimatetool.com/index.php?topic=149.msg739#msg739

**Comment by Monezz** [comment]
Perhaps splitting the archiving from the compression?

```
<tar destfile="${dist}/manual.tar" basedir="htdocs/manual"/>
<gzip destfile="${dist}/manual.tar.gz" src="${dist}/manual.tar"/>
```
Another thing I noticed is that the md5sum from the tar.gz file is different from the one in the md5 file.

> md5sum  Archi-Linux64-4.0.1.tar.gz
> 66018df47a3455bb67be9e5288eea175  Archi-Linux64-4.0.1.tar.gz

> cat Archi-Linux64-4.0.1.tar.gz.md5 
> MD5 (Archi-Linux64-4.0.1.tar.gz) = 9382ddb9ad77247d3576259e230a200d

**Comment by Phillipus** [comment]
> Perhaps splitting the archiving from the compression?

Nope, makes no difference.

> Another thing I noticed is that the md5sum from the tar.gz file is different from the one in the md5 file.

Then it might have been mangled by your download. I'm getting 9382ddb9ad77247d3576259e230a200d

**Comment by Phillipus** [comment]
I just downloaded it in Chrome and get the 66018df47a3455bb67be9e5288eea175

See https://superuser.com/questions/940605/chromium-prevent-unpacking-tar-gz

And, no, I have no control over how my hosting provide serves .tar.gz files without the content-encoding: gzip header.

**Comment by jbsarrodie** [comment]
> And, no, I have no control over how my hosting provider serves .tar.gz files without the content-encoding: gzip header.

Yes as discussed before, this clearly seems to be an issue with headers and interpretation by the browser (or a proxy in between). Look [here](https://superuser.com/questions/940605/chromium-prevent-unpacking-tar-gz) for more information.

**Comment by Phillipus** [comment]
Closing, since it's out of my control.

**Comment by Phillipus** [comment]
Quick note - Linux downloads now have the .tgz extension and this solves the problem on Google Chrome. Thanks to @jbsarrodie for the heads up.
