### ISSUE TITLE
[Feature Request] Block in Canvas Modeling Toolkit with no fill (transparent)

### ISSUE THREAD

**Issue by j2sacks** [archimatetool/archi#247]
The drawing tools in the canvas modeling toolkit are very limited. I want to lay down a background image and put transparent blocks over it. Currently, the blocks must have a color, so even white will obscure the image.

**Comment by Phillipus** [comment]
Opacity will be in next version. A value of 0 will solve this.

**Comment by Phillipus** [comment]
We have opacity setting now.
