### ISSUE TITLE
Export to Open Exchange file error.

### ISSUE THREAD

**Issue by marbico** [archimatetool/archi#248]
Hi.
I'm trying to export a model to the Open Exchange file (Archi 4.0.1 +Win10) . Find attached the screen with an error message. Do you have any suggestions what might be the cause? 
Best regards,
Marek
![archi export err](https://user-images.githubusercontent.com/14309143/27196048-4b9f3de8-5209-11e7-88c4-0cf835c75d35.JPG)

**Comment by Phillipus** [comment]
Please provide the error log and the file that causes the problem.

**Comment by marbico** [comment]
Please find enclosed two zipped files.

[ABC_ERR.zip](https://github.com/archimatetool/archi/files/1078954/ABC_ERR.zip)

**Comment by Phillipus** [comment]
Thanks, I can reproduce the error. It happens when calculating positionsfrom connection to connections. I will investigate.

**Comment by Phillipus** [comment]
A null position is returned when calculating bendpoints on a connection when tit connects to another connection. This issue is still pending. In the meantime, I have added a temporary fix to not calculate bendpoints in this case.

**Comment by Phillipus** [comment]
I'll release Archi 4.0.2 soon with this fixed.

**Comment by marbico** [comment]
Thank you very much for your answer. I am waiting patiently for the new version. By the way, thank you for the great job you do for the analyst community (I mean Archi).

**Comment by Phillipus** [comment]
Thanks. Archi 4.0.2 has been released.

**Comment by Phillipus** [comment]
Fixed
