### ISSUE TITLE
[Feature Request] Allow to change ID in UI

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#250]
I am often syncing update information from other sources in to the archimate model.
For the elements which are created in UI I need to change the ID for the proper sync.

Now I have to open archimate xml file and change it manually using text editor. (Basically by search and replace, while checking uniqueness.)

Proposal for the properties tab:
add readonly textbox ID: _____
and button aside [Change ID] 

The button will open the dialog:
Old ID: ____________
New ID: ___________
[Check and change]

Check would check whether the new ID is unique.
If not the error is raised.
If yes the change is applied within the whole model including relations.

**Comment by jbsarrodie** [comment]
Hi,

I don't feel this is the right approach as this doesn't scale if you have to sync with several other sources that have their own ids. In the past I have used some properties instead, for example "cmdb_id" to set the id of equivalent element in my CMDB. This allowed me in some cases to add other "_source_ id" properties.

**Comment by Phillipus** [comment]
Sounds like you have a probem with "syncing update information" but are trying to solve it in the UI.

**Comment by radeksvarz** [comment]
@jbsarrodie I am following the help recommendation for the Importing CSV Data into a Model. Additionaly if you want to import properties you need to use ID (and cannot map via other property).

@Phillipus I do not understand what kind of the problem. 

Here is my case:

1. I imported the bulk set of elements (cca 700) with Asset mng. ID as an ID. So I could also import some related properties.

2. After some weeks I bulk update the properties.

3. From time to time I need to add a new Asset. This I enter directly in UI. 

4. Bulk update of the properties. The new asset's properties are in the csv import file. Therefore I need to change ID.

**Comment by herve91** [comment]
Hi Radek,

Last year, I faced the same kind of issue. I now add or update properties from my cmdb directly to my Archi database, created using the database plugin (https://github.com/archi-contribs/database-plugin/tree/master/v2) using Talend. To acheive that, I also have got a property which contains the cmdb ID. Therefore, there is no dependency between booth IDs.

Nevertheless, I must admin that changing the ID a ways easier and I used to do it. So if your process is not mature enough to use separate IDs, I can suggest to use the form plugin (https://github.com/archi-contribs/form-plugin). Its purpose is to present information about a elements and relationships in a form . As any form, somes fields will be read-only (labels) while some others (will be read-write) (text, combo boxes, tables ...). It is very easy to create a table with all your components (class, name, id). It will also be possible to narrow the components list using a filter.

At the moment, the ID is read only but I can easily provide a version where the ID can be changed.

Please let me know.

Best regards
Hervé

**Comment by Phillipus** [comment]
Let's be clear about this - there are thousands of Archi users. A request for something that 1 or 2 people wants will affect these thousands of users and has a big impact. Please be aware of other users. If this is implemented, it's me that has to deal with emails like "I changed the ID of my model and it's now corrupt, help!". I already have to provide free support for organisations that have messed up their models by messing around with the XML.

So, no, I'm not going to implement this.

**Comment by JamesUsmar** [comment]
Regarding the scale of people who might liked to have had the ID presented in an editable dialogue I can appreciate it might be small... but I would have liked this feature.

As an Architect I would rather that id's with this type of tool were human readable and related to what they were, rather than being a random string. I create elements and relations from existing 'data' (like CMDBs) to act as empirical data sources and then add value making logical relationship deductions and create relations based on some part of the data being a 'truth'. QED information and knowledge gained to allow me to make better decisions and so support the business better, and deliver the business goals.

Regards, James.

**Comment by radeksvarz** [comment]
@JamesUsmar, indeed. E.g. it is common approach to declare the enterprise wide ID to the application asset. Such IDs are typically a few letters wide and used extensively in the documentations etc.

@Phillipus @jbsarrodie  You are right that the better approach is to have the external ID stored in the property. However in such case the standard csv import / export does not reflect this as it operates over internal IDs. If I had the chance to declare the property for ID within import / export dialog, then I could follow the right approach.

Anyway, as I mentioned, I have the workaround for now. To open archimate xml file and change it manually using text editor. (Basically by search and replace, while checking uniqueness.)

**Comment by herve91** [comment]
There is another workaround: use the form plugin (https://github.com/archi-contribs/form-plugin).

This control file allows to change one component's ID:
```
{
   "version": 3,
   "org.archicontribs.form": {
      "spacing": 4,
      "refers": "selected",
      "name": "Change component's ID",
      "width": 600,
      "height": 400,
      "tabs": [
         {
            "name": "ID",
            "controls": [
               {
                  "name": "Name label",
                  "x": 5,
                  "width": 125,
                  "y": 31,
                  "text": "Component's name:",
                  "class": "label"
               },
               {
                  "name": "Name text",
                  "x": 130,
                  "width": 400,
                  "variable": "${name}",
                  "y": 30,
                  "class": "text"
               },
               {
                  "name": "Class label",
                  "x": 5,
                  "width": 125,
                  "y": 61,
                  "text": "Component's class:",
                  "class": "label"
               },
               {
                  "editable": false,
                  "name": "class text",
                  "x": 130,
                  "width": 400,
                  "variable": "${class}",
                  "y": 60,
                  "class": "text"
               },
               {
                  "name": "ID label",
                  "x": 5,
                  "width": 125,
                  "y": 91,
                  "text": "Component's ID:",
                  "class": "label"
               },
               {
                  "tooltip": "Warning, the component's ID should be unique across the whole model",
                  "name": "ID text",
                  "x": 130,
                  "width": 400,
                  "variable": "${id}",
                  "y": 90,
                  "class": "text"
               }
            ],
         }
      ],
   }
}
```

This control file alows to display a table with all elements and relationships and change their ID:
```
{
   "version": 3,
   "org.archicontribs.form": {
      "spacing": 4,
      "refers": "model",
      "name": "Change all elements and relationships IDs",
      "width": 660,
      "height": 400,
      "tabs": [
         {
            "name": "IDs",
            "controls": [
               {
                  "name": "Elements and relationships",
                  "x": 5,
                  "y": 5,
                  "width": 630,
                  "height": 300,
                  "class": "table",
                  "columns": [
                        { "name": "Name",  "class": "text", "width": 180},
                        { "name": "Class", "class": "text", "width": 180,  "editable": false},
                        { "name": "ID",    "class": "text", "width": 240, "tooltip": "Warning, the component's ID should be unique across the whole model"}
                  ],
                  "lines": [
                    {
                        "generate": true,
                        "cells": ["${name}", "${class}", "${id}"]
                    }
                  ],
               }
            ],
         }
      ],
   }
}
```

Best regards
Hervé

**Comment by Phillipus** [comment]
My final say on the matter is that an ID is a unique internal thing. It is referenced elsewhere in the model, and is used to uniquely identify the object internally and in other cases. I will not be adding a public UI to change it, since I do not want to be the person who has to provide free support when users mangle their data (it seems that I already do, anyway.) If you change IDs, then this is unsupported and you're on your own.

**Comment by jbsarrodie** [comment]
@radeksvarz 
>You are right that the better approach is to have the external ID stored in the property. However in such case the standard csv import / export does not reflect this as it operates over internal IDs. If I had the chance to declare the property for ID within import / export dialog, then I could follow the right approach.

I don't really see the issue as using your spreadsheet of choice (say Excel) you can easilly create formulas that will create or look for the information you want (I did it several time to sync with my CMDB). This of course requires some work but you only have to do it onece and it can then be used with several external ids.

**Comment by radeksvarz** [comment]
@Phillipus Your final statement is clear. ID to be unique internal thing.

But, if that is internal, why the documentation of the csv import / export refers to these internal IDs?

**Comment by jbsarrodie** [comment]
>But, if that is internal, why the documentation of the csv import / export refers to these internal IDs?

I wrote CSV export/import specifications... The goal was to support both model creation and updates, so for the last one it was needed to have access to Ids. In fact one of the original use-cases was to sync with a CMDB. But again, for this use case, the "Archi Id" was not used directly (just as a mean to update properties of elements), a specific and dedicated property (CdbId) were added on all elements that were in common.

FWIW, I used to sync between 4 referentials: local CMDB, Group CMDB, local monitoring tool, local Application Catalog (which unfortunately were not merged to the local CMDB). And of course there were no shared uniq Id between those 4 solutions.

**Comment by radeksvarz** [comment]
> And of course there were no shared uniq Id between those 4 solutions.

;)

Now I understand your mapping comment. 

@herve91 Thanks for the suggestion, I will try it. 

I believe the csv import/export deserves the change or further elaboration as the outcome of this topic. 
To better help others with related processes and best practices. (I am willing to help.) 

For the future reference I found the related discussion here http://forum.archimatetool.com/index.php?topic=419.0

**Comment by JamesUsmar** [comment]
The 'Principle' of being able to construct and update an entire Archi Architectural Model from CSV source data (so 'Lists' and 'Matrices'... and CMDBs dropped into a universal CSV common interoperable format) is a *hugely* powerful capability and massive positive feature. 

I use Excel to import the raw data from lots of sources, and then lots of string manipulations and logic to create information (elements and relationships) from that data. And you know what... it works, and rapid, and easy to fix if it goes wrong... at real scale. And there is the one element of 'value'.

Clearly I have touched on something here. Apologies. 

Regards,
James.

**Comment by MilennialZero** [comment]
Colleagues

I'm new here, so apologies in advance if I don't have history with this
topic, but this looks relevant to the work I do.
We capture matrices of instances of customer Archimate entities and
attributes using Excel. Then we import that data into Visio. The data is
populated into Visio 'shape sheets' and a Visio diagram (view) is
generated. Which requires additional manual tailoring. For some
customers, we get A0 size diagrams that are visually dense and complex,
but the customer likes them.
If I could import a matrix of data (.csv) into Archi it would be
quite useful!
Also - having robust and reliable export to .csv from Archi is
equally useful.
Thanks

--
  Jon McLeod
  Director, McLeod Consultancy Pty Ltd
  GPO Box 813 Canberra ACT 2601 Australia
  +61 457 988 821
  jmcleod@thelonius.com.au
  Silver Member The Open Group Architecture Forum

----- Original message -----
