### ISSUE TITLE
[Feature Request] Stamp Properties tool in Palette UI

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#253]
Problem: when you have the larger model (meaning with many elements and several different properties ) it is tiresome to selectively apply property value to several elements in the view.

I would like to use the tool such as known from the photographic management tools like Adobe Lightroom.  (Or format "sprayer" from Office tools).

The usage:
1. select the element with desired property value
2. click on the sprayer tool
3. modal window opens with request which properties you want to spray - select and click [Spray] button
4. cursor is changed to spray cursor
5. navigate across the view and click on elements where you want to update or create the selected properties
6. click on any other tool in the palette to finish the task

**Comment by Phillipus** [comment]
What is the underlying problem? Is it:

"Be able to easily add existing property key/value pairs to selected objects"

If so, a "spray" tool is not really the ideal solution as this kind of thing is more suited to UI elements.

**Comment by radeksvarz** [comment]
@Phillipus You are correct we should distinguish between mass applying the visual representation (ala Office spray) and property setting. 

Those might be 2 cases. I would like to conclude here on the property setting.

I think the desired approach is still valid. Only the naming + icon of the tool should be different.

**Comment by radeksvarz** [comment]
The other approach is: 

 - multi select the elements, where the property is to be updated
 - change the property in the Properties list to apply across selected elements

This would require to rework the Properties listview.

**Comment by jbsarrodie** [comment]
I feel that the seal use case is simply to enable user to create and use [profiles](http://pubs.opengroup.org/architecture/archimate3-doc/chap15.html#_Toc489946140) in Archi.

**Comment by radeksvarz** [comment]
I have read through profiles and I am still suggesting the idea of the tool for stamping the properties onto elements.
"Stamp" is rather the valid tool in our case, apology for the spray (which comes from Adobe Lightroom).
