### ISSUE TITLE
[Bug] Lack of Assigned-To relation from AppComponent to BizProcess

### ISSUE THREAD

**Issue by Klpcjsz** [archimatetool/archi#254]
### Current Version of Archi
com.archimatetool.editor.buildid=201706161020
com.archimatetool.editor.versionid=4.0.2

### Expected Behaviour
It is possible to create Assigned-To relation from AppComponent to BizProcess to show that BizProcess is fully automated.

### Actual Behaviour
It is impossible to create Assigned-To relation between source AppComponent and destination BizProcess 

### Steps to Reproduce the Behaviour
1. Create AppComponent
2. Create BizPRocess
3. Try to create Assigned-to relation from AppComponent to BizProcess - no such possibility.

### Comments
There is no ass(i)gnment relation from AppComponent to BizProcess defined in ArchiMate 3 spec as it was in ArchiMate 2 but I think it is a mistake.

**Comment by Phillipus** [comment]
See Issue #243

**Comment by jbsarrodie** [comment]
This is not a mistake, this has been changed to a Realization from an Application Process to a Business Process.

Closing.
