### ISSUE TITLE
JVM crash

### ISSUE THREAD

**Issue by fsclavo** [archimatetool/archi#255]
### Version of Archi, Operating System

Archi 4.0.2, Ubuntu 16.04LTS
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Expected Behaviour

Doesn't crash.

### Actual Behaviour

JVM crashes (logs attached)
### Steps to Reproduce the Behaviour
1. Not always, but the crash more frequently occurs when pushing model to GIT (plugin archi-contrib version 0.2.3)
2.
3.

[logs.tar.gz](https://github.com/archimatetool/archi/files/1149666/logs.tar.gz)

**Comment by Phillipus** [comment]
Not so easy to diagnose this as it is an internal Java error. It seems to happen on org.archicontribs.modelrepository.actions.PushModelAction#run() when the progress monitor dialog is closed:

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 14700  org.eclipse.swt.internal.gtk.OS._gtk_widget_destroy(J)V (0 bytes) @ 0x00007f2c3b58b081 [0x00007f2c3b58b040+0x41]
J 12885 C1 org.eclipse.swt.widgets.Widget.destroyWidget()V (30 bytes) @ 0x00007f2c39e93244 [0x00007f2c39e92f60+0x2e4]
J 16435 C2 org.eclipse.swt.widgets.Widget.release(Z)V (90 bytes) @ 0x00007f2c39c6f528 [0x00007f2c39c6f400+0x128]
J 13418 C1 org.eclipse.swt.widgets.Control.release(Z)V (115 bytes) @ 0x00007f2c3aab5a8c [0x00007f2c3aab5580+0x50c]
J 13121 C1 org.eclipse.swt.widgets.Widget.dispose()V (27 bytes) @ 0x00007f2c3afdcac4 [0x00007f2c3afdc300+0x7c4]
j  org.eclipse.swt.widgets.Shell.dispose()V+20
j  org.eclipse.jface.window.Window.close()Z+65
j  org.eclipse.jface.dialogs.Dialog.close()Z+26
j  org.eclipse.jface.dialogs.ProgressMonitorDialog.close()Z+12
j  org.eclipse.jface.dialogs.ProgressMonitorDialog.finishedRun()V+5
j  org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ZZLorg/eclipse/jface/operation/IRunnableWithProgress;)V+46

But this kind of error can happen with Ubuntu Themes. Try a normal theme and see if it happens.

**Comment by fsclavo** [comment]
Hi Phil, sorry for the delay.
I'm not using any custom theme, just Ubuntu's default.

2017-07-14 18:56 GMT-03:00 Phil Beauvoir <notifications@github.com>:

**Comment by Phillipus** [comment]
Need to pin this one down to something specific. Can you narrow it down? Try different version of Ubuntu, Java...?

**Comment by fsclavo** [comment]
No problem, I've switched JVM to Openjdk. I'll keep you informed.


2017-07-24 18:06 GMT-03:00 Phil Beauvoir <notifications@github.com>:

**Comment by Phillipus** [comment]
Closing pending further info. Please re-open if still a problem.
