### ISSUE TITLE
Suppress relationship name in a view

### ISSUE THREAD

**Issue by rayl** [archimatetool/archi#256]
Feature request to add a "None" item to the "Text Position" selector on the Appearance tab of a Relationship. The idea is to be able to name a relationship, but not necessarily see the name on any given View.

http://forum.archimatetool.com/index.php?topic=392

**Comment by jbsarrodie** [comment]
Hi,

Personnally I also think it makes sens to have a way to hide relationship name. I'm not sure "Text Position" is the best place to do it though (is "nowhere" a position?)...

**Comment by Phillipus** [comment]
It would be easy enough to have a "visible" checkbox in Properties to show or hide it.

**Comment by Phillipus** [comment]
This is implemented in 4.6
