### ISSUE TITLE
[Feature Request] Support for designing and using ArchiMate based domain specific languages (DSLs)

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#257]
- ability to define new element stereotypes (es's) based on the existing ArchiMate (insert version here) elements
- new es's inherit corresponding ArchiMate relationships and semantics
- new es'es can override base stereotype's name, iconography, style)coloring, symbol shape, ...
- support recursive derivation
- sample use/test case: derive ArchiMate 3.0 elements from ArchiMate 2.1 elements including (in the fullness of time) all of the side issues (new base types, new relationships, depreciation/blocking of existing types, ...)

I'm willing to provide some support for this (small level of support, potentially underwelming). 😉

Best regards,
Michael Herman (Seattle/Toronto)

**Comment by mwherman2000** [comment]
Phil and I have discussed this briefly over email and he pointed me to the Sirius project.

Can DSLs be part of the design of a new Archi modeler based on Sirius?

Is anyone currently working on a Sirius based EA modeler? Please post pointers/links.

Michael (Seattle/Toronto)

**Comment by jbsarrodie** [comment]
I guess there are multiple comments here....

In the mid/long term, Archi should support concept specialization as specified in ArchiMate standard. But this is not DSL as this limits to a top level ArchiMate metamodel. There is a [work in progress contribution](https://github.com/archi-contribs/specialization-plugin) that tries to fill this gap (separated plugin, not maintained by Phil nor me).

If you really need to have a tool for a DSL, then Sirius is the way to go.

>Can DSLs be part of the design of a new Archi modeler based on Sirius?

There's no plan for an Archi modeler based on Sirius (and IMHO will never be)...

>Is anyone currently working on a Sirius based EA modeler? Please post pointers/links.

Yes, The company behind Sirius sells a product named [SmartEA](https://www.obeosmartea.com/en/) that is based on Sirius and profides a fully customizable solution for EA that now even supports ArchiMate... but this is not opensource.

**Comment by mwherman2000** [comment]
JB, yes there are several pieces to the puzzle/architecture (where's the ArchiMate diagram when you need it most ;-))

1. "In the mid/long term, Archi should support concept specialization as specified in ArchiMate standard." This is more or less what I envision for the derived metamodel/DSL designer.  Here's an example which uses Specialization (IsA) ArchiMate 3.0 relations to derive a  new metamodel/DSL (on the left side of the diagram) from ArchiMate 3.0 core elements (on the right side of the diagram):
[https://hyperonomy.com/2017/01/25/modeling-a-company-and-its-locations-employees-investors-roles-proposals-wishes-dreams/](url)

2. Then the tricky step is to enhance Archi to understand "restart/reload thyself using the new metamodel/DSL (defined on the left side of the designer)" ...recursively.

3. "There is a work in progress contribution that tries to fill this gap (separated plugin, not maintained by Phil nor me)."  This plugin is a "customizer" (of the existing metamodel) which is closely related but different from a plugin/redesign that supports (recursive) derivation of new metamodels.  It's a great starting point.

4. Is there anyone from or who works on Obeo/Sirius/SmartEA monitoring this project?  Please email me at mwherman at parallelspace dot net.  

Michael (Seattle/Toronto)

**Comment by mwherman2000** [comment]
There's a new standard called GraphQL ...which includes a data definition language for arbitrary graphs.  I'm logging this here as another technology to support ArchiMate-based DSLs (domain specific languages).  

Here's a web cast: [https://www.youtube.com/watch?v=0EmZjheYv-U](url)

Here's a link to the project: [http://graphql.org/](url)

Here's a link to a specific implementation on top of Neo4j: [https://neo4j.com/developer/graphql/](url)

Best regards,
Michael Herman (Seattle/Toronto)
