### ISSUE TITLE
[Feature request] Read-only views

### ISSUE THREAD

**Issue by mb2o** [archimatetool/archi#258]
I would like to have a way of setting a view as read-only, so it can no longer be edited

**Comment by Phillipus** [comment]
Fair enough, but it would have to change if a concept on that View was changed elsewhere.

**Comment by radeksvarz** [comment]
I think this topic needs to be more elaborated due to the reflection of changes in the elements. I think you are rather talking about editing lock.

What do you want to have read only in the view?

The layout of elements?

**Comment by mb2o** [comment]
You interpreted it correctly. I would very much like to see some kind of editing lock.

**Comment by radeksvarz** [comment]
Can you describe more your use case?

The editing lock on selected views to avoid self made mistakes? Or because you hand over the model to someone else?

**Comment by mb2o** [comment]
Exactly. We work with a team on Archi projects. Some of us however are more adept than others. I don't want them accidentally changing views that are marked as final. Also, we iteratively review those views with other departents so it would be nice to have the lock feature so we do not accidentely change views that have recently been reviewed.
