### ISSUE TITLE
[Feature Request] Jasper Report ordered by the Views Contents Order

### ISSUE THREAD

**Issue by CharlesEdw** [archimatetool/archi#260]
When I print out a current Jasper report, it seems to put everything into Alphabetical order. This is not logical for non-Architects to follow. 

Please could you create a report option that allows for sorting in the order of the Views so that it will form a more logical Architectural report. e.g. if my view looks like this with one or many Models in each then the report should also be generated in this order.
- Business Architecture
-- Business Motivation
-- Business Operational Architecture
---- Process Architecture
---- etc.
- IT Architecture
-- Data Architecture
-- Application Architecture
-- ICT Architecture
-- Physical Archirtecture
- Cross Cutting Concerns
-- Services Architecture
-- Strategy & Motivation
-- Security Architecture
Thanks. C

**Comment by Phillipus** [comment]
This is in new JR API

**Comment by CharlesEdw** [comment]
Great thank you.

kind regards
Charles

Enterprise Architect
AgileEA.com

Mobile: +27 61 849 5792

________________________________
