### ISSUE TITLE
[Feature Request] Bulk Property Assignment

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#261]
I don't believe the following is possible with properties (without editing an exported CSV). Happy to be proved wrong.

1) Bulk Edit: To select multiple elements on a view, then assign a property to them all. Better still, assign a property value too. 
2) Default Property: Assign a property as a default to all elements of a given element type, with a blank value.

**Comment by jbsarrodie** [comment]
I find this and interesting idea. Closing this one has discussion (re)started on issue #339.
