### ISSUE TITLE
When creating new items in folder tree - no icons in menu

### ISSUE THREAD

**Issue by belonesox** [archimatetool/archi#263]
* Error log in empty.

### Version of Archi, Operating System

* 4.0.2.
** [archi-configuration.txt](https://github.com/archimatetool/archi/files/1208974/archi-configuration.txt)
* Linux. ROSA Desktop Fresh R9. 

### Expected Behaviour

When creating new items in folder tree where should be icons in new menu. See 
![default](https://user-images.githubusercontent.com/1609739/29084597-34b5c6a6-7c75-11e7-814a-1c345c6878b4.png)

### Actual Behaviour

When creating new items in folder tree - no icons in menu
![default](https://user-images.githubusercontent.com/1609739/29084621-451fdac2-7c75-11e7-89ad-62fa59b837dc.png)

### Steps to Reproduce the Behaviour
1. Create any blank model
2. Try to create new item in folder tree.

**Comment by Phillipus** [comment]
This is going to be a Linux thing. Is there an OS setting for menu icons?

**Comment by jbsarrodie** [comment]
>This is going to be a Linux thing

I think the same. For information I use elementary OS (based on Ubuntu) and have never seen any icons in applications context menus (not only Archi). I think this is a design choice on the GTK theme.

>Is there an OS setting for menu icons?

In my case I don't know

**Comment by Phillipus** [comment]
I did turn them on in Ubuntu or Mint once, but I can't remember why/when/how...

**Comment by jbsarrodie** [comment]
Hi. Closing this issue as this is OS related (see https://ask.fedoraproject.org/en/question/23116/how-to-fix-missing-icons-in-program-menus-and-context-menus/).
