### ISSUE TITLE
Bug: Last letter of elements cut off

### ISSUE THREAD

**Issue by mistertakai** [archimatetool/archi#264]
### Version of Archi, Operating System
Archi 4.0.2
MacOS

### Actual Behaviour
Archi does not display element names properly, the last letter is cut off, either completely or partly.

This example image displays the behaviour (the last letter is missing):

![image](https://user-images.githubusercontent.com/3066447/29271506-16f6deb2-80fc-11e7-9a47-06af0d4d4c64.png)

### Steps to Reproduce the Behaviour
1. Create a view
2. Add a Resource or a Capability and give it a name
3. Displayed incorrectly

**Comment by Phillipus** [comment]
What font and zoom level are you using? This can happen with certain fonts and zoom levels.

**Comment by mistertakai** [comment]
I'm using a zoom level of 150% or 200%. And you're right, looking at the diagrams at 100% does not show the described behaviour.

**Comment by Phillipus** [comment]
It's an issue in the Eclipse Graphical Editing Framework (GEF) that I can't fix.

**Comment by mistertakai** [comment]
Sorry to hear that! If you have a link to the underlying bug, i'll go vote / comment on it...

**Comment by Phillipus** [comment]
Almost 3 years later and we tracked this one down in #621 

Fixed
