### ISSUE TITLE
"Strength" field of Influences Relationship not Present in CSV Export

### ISSUE THREAD

**Issue by yellek** [archimatetool/archi#268]
### Version of Archi, Operating System
Version 4.02
Windows 10

### Expected Behaviour
When a CSV export is performed for influences relationships, the "Strength" field should be exported

### Actual Behaviour
The information from the "Strength" field for influences relationships is not present in the CSV export

### Steps to Reproduce the Behaviour
1. Create an influences relationship (between 2 motivation elements)
2. Set the "Strength" field on the "Main" tab in the properties window to any value (e.g. '+')
2. Export the model to CSV
3. Look in the xxx-relations.csv or xxx-properties.csv for the information in the "Strength" field

My suggestion would be to include it as a property of the relationship however it just needs to be there.

**Comment by Phillipus** [comment]
Good point. Also for the access type of the Access relationship.

I'll have  a think about the best way to do this.

**Comment by Phillipus** [comment]
> My suggestion would be to include it as a property of the relationship however it just needs to be there.

I'm testing this now. It does create some issues. I'm concerned that some other tools/systems expect this file to only contain key/value properties. My feeling is that the "properties.csv" should only contain these. 

An alternative is to add another column to the "relationships.csv" file:

"ID", "Type", "Name", "Documentation", "Source", "Target", "Attribute"

This could contain strength and access type.

**Comment by Phillipus** [comment]
Tested adding the "Attribute" field. Now I'm not so sure if adding as as property is better.

**Comment by Phillipus** [comment]
After testing both approaches I found that adding the attributes "Influence_Strength" and "Access_Type" as properties had less impact. So that's what I've done.

Will be in next build.

**Comment by yellek** [comment]
That is awesome and a really quick response. I look forward to adding them to my neo4j import scripts.

**Comment by Phillipus** [comment]
It's in beta 5.
