### ISSUE TITLE
BOM missing in exported csv for Excel

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#269]
### Version of Archi, Operating System
Archi 4.0.2 on Windows 10

### Actual Behaviour
Generated CSV files do not have BOM codes ( https://en.wikipedia.org/wiki/Byte_order_mark ) which is expected by Excel when reading UTF8 csv.

### Expected Behaviour
Generated CSV files should have BOM codes included.
Proposal: add checkbox to Export Model to CSV files dialog for adding UTF8 BOM 

### Steps to Reproduce the Behaviour
1. export CSV with some Unicode characters
2. open in Excel
3. the characters are not parsed properly due to missing BOM

### Workaround
Adding BOM bytes manually after the exports to the generated csv files, which is somehow complicated.

**Comment by Phillipus** [comment]
Not sure this would work.

Did you try suggestion here

https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by Phillipus** [comment]
Having said that, the following does help:

https://stackoverflow.com/a/8120786

**Comment by Phillipus** [comment]
I tested an option "UTF-8 BOM" to the encodings combo box in the wizard. This will write a BOM byte. My tests show that this works on export but fails on re-import.

**Comment by jbsarrodie** [comment]
Hi,

FWIW, In my experience BOM on UTF8 makes most things worse and I've never had any issues with loading CSV files generated by Archi into Excel.

Maybe your issue has to be investigated.

**Comment by Phillipus** [comment]
I can write the BOM byte easily enough and it opens in Excel as expected. However re-importing with a BOM byte causes lots of problems. The import routine would have to test for the byte and remove it.

Using Excel's Data import function is the preferred method of importing CSV files as you can specify the data format and encoding.

**Comment by jbsarrodie** [comment]
>The import routine would have to test for the byte and remove it.

This is strange as the BOM thing should be managed at Java level

>Using Excel's Data import function is the preferred method of importing CSV files as you can specify the data format and encoding.

Yes, and again, I never had any issue when opening CSV files in Excel, whatever method I use to load the file.

**Comment by Phillipus** [comment]
> This is strange as the BOM thing should be managed at Java level

No. See https://commons.apache.org/proper/commons-csv/user-guide.html#Handling_Byte_Order_Marks

**Comment by Phillipus** [comment]
The issue here is when the CSV file contains Unicode characters. They can be imported correctly using Excel's Data import function, but they are not preserved when re-importing into Archi. I'll take a look at that.

**Comment by Phillipus** [comment]
Importing as UTF-8 fixes the problem of Unicode chars not displaying when importing CSV as Archi. I'll set this as this is probably more important.

**Comment by radeksvarz** [comment]
As I mentioned I am using workaround. Adding the BOM after the extraction to csv. I am using easy .bat file to add it (where bom.csv includes just 3 BOM UTF8 bytes):

add_bom.bat
`copy /b bom.csv + %1 %~n1_bom%~x1`

Less skilled users require to easily open csv by doubleclicking on it.

**Comment by Phillipus** [comment]
As I've said before, opening a CSV file in Excel does not always work as expected. Excel makes a best guess at the data format.

The correct way to import CSV files into Excel is as described here:

https://www.ablebits.com/office-addins-blog/2014/05/01/convert-csv-excel/#import-csv-wizard

Adding a BOM byte to the CSV file really only is for the Excel use case, and it cannot be re-imported into Archi without problems.

**Comment by radeksvarz** [comment]
Phil, I appreciate the education you are giving, but there will be still confused users without such education directly mentioned in the export dialog.

> From what I've read, UTF-8 should not really have a BOM. It seems that it is MS that is doing it.

This is the reason why I propose to implement it as the checkbox option (deafult unchecked).

**Comment by Phillipus** [comment]
The problem then is how to educate users who email me to say that they cannot import a CSV file because of some error. It will consist of me asking "Did you export with the BOM option?"

**Comment by radeksvarz** [comment]
This import problem happens anyway (if they prepare data in Excel, save as csv - UTF8).
The solution is to detect BOM in import code and ignore / stip it if it is there.

note: this is one of the reasons why I directly modify archimate xml using python script when updating properties.

**Comment by Phillipus** [comment]
OK, I've added the option.

- It appears as an extra encoding "UTF-8 BOM" in the File Encoding combo in the CSV export wizard
- It writes the BOM byte
- Import CSV now uses the Apache Commons BOMInputStream class to filter out any BOM bytes

Will be in next build.

**Comment by radeksvarz** [comment]
You guys rock. Respect.

**Comment by Phillipus** [comment]
I'm curious to know why you need the model in Excel.

And what would be the ideal native Excel data layout if you could bypass the CSV export?

**Comment by radeksvarz** [comment]
> why you need the model in Excel.

For 2 reasons:

1. batch editing
2. as the export, which is further enhanced by added columns with lookups to other sheets and provided to colleagues

**Comment by Phillipus** [comment]
I'm exploring native export to Excel file, so I need consensus on an ideal format - number of sheets, how elements, relations, properties are presented, etc.

**Comment by radeksvarz** [comment]
I also additionally export to csv for each element on which diagram (view) it is present. But this is done by directly analysis archimate xml file.

Serves for croschecking and as the lookup reference for HTML views.

**Comment by radeksvarz** [comment]
>  so I need consensus on an ideal format 

I can provide some long term evolved usage.
Basically I use and spread 3 exports to users:
1. HTML diagrams
2. Excel list of elements with related selected attributes
3. Excel list of dependencies of elements (but limited to certain element types)

ad 2) elements structure
Element ID, Title, Documentation, Selected Propertie(s), Comma merged list of diagrams where the element is present.

After the export I delete some element types which are not relevant.
Unfortunately I need to map extra columns, which I do no want to import into Archi. So I map them ex post export.

ad 3) the dependencies structure:
Source element ID, Source title, Selected Source Propertie(s), Relation type, Target element ID, Selected Target Propertie(s), Relation documentation, Selected Relation Properties

The major point is that I have to also export and merge some (selected) properties. 
If I was capable to implement the export I would put there dialog enabling to select which properties are to be exported and attached to each record in 2) and in 3)

**Comment by radeksvarz** [comment]
I am closing this issue as it is implemented in the 4.0.3 version.

The only remark I have is that I would rather call it "UTF-8 BOM for Windows"

**Comment by Phillipus** [comment]
> The only remark I have is that I would rather call it "UTF-8 BOM for Windows"

Even though I know what you mean, that might confuse some people. It still writes the BOM byte regardless.

**Comment by radeksvarz** [comment]
I am reopening this issue as only elements file gets the BOM. Properties and relations do not even when file encoding is set to UTF-8 BOM.

ad naming - you are right. In fact people working on Windows would just have it pre-selected by default.

**Comment by Phillipus** [comment]
Yep. Fix committed. Will be in next build.

**Comment by Phillipus** [comment]
In 4.1.0
