### ISSUE TITLE
[Feature Request] Fill Colour for relationship text

### ISSUE THREAD

**Issue by alcedocoenen** [archimatetool/archi#271]
Using lots of relationship names, it is disturbing that the arrow is crossing the text (when positioned middle), making the text less readable. The text-box is transparant by default, and this is not changeable.
![image](https://user-images.githubusercontent.com/14913203/30480641-19ebab06-9a1b-11e7-8b73-563b474df913.png) 
![image](https://user-images.githubusercontent.com/14913203/30480796-e6bef17e-9a1b-11e7-8889-7af65632568a.png)

 It would be nice of we also could define the Fill Colour for the relationship text. The colour by default, I would say, should be white:
![image](https://user-images.githubusercontent.com/14913203/30480750-a7a13c54-9a1b-11e7-8670-be73939fdea6.png) 
![image](https://user-images.githubusercontent.com/14913203/30480835-1c41611a-9a1c-11e7-861c-d25812401b52.png)

What do you think?

**Comment by Phillipus** [comment]
Yes, this is possible. Also better would be multi-line text and free positioning of the text label rather than the limited three positions currently implemented. I can implement the first two but not the free positioning - this requires better GEF/Draw2d expertise than I currently have. Perhaps that would be something that someone in the OS community might try.

**Comment by jbsarrodie** [comment]
Hi,

I have a small patch to add this background (in fact I created it more than a year ago). It only miss some options (and obsiously to adapt ecore model to store the color). I can confrm this has been prooven useful.

Multi-line would be useful too.

**Comment by jbsarrodie** [comment]
I'm working on it. My current approach is to not draw the part of the relationship under the label. This would remove the need to set an explicit background.

**Comment by Phillipus** [comment]
Set opacity of label?

**Comment by Phillipus** [comment]
Surely a simple fix is in AbstractDiagramConnectionFigure:

```
    public Label getConnectionLabel() {
        if(fConnectionLabel == null) {
            fConnectionLabel = new Label(""); //$NON-NLS-1$
            fConnectionLabel.setOpaque(true); // <------- ADD THIS LINE!
            add(fConnectionLabel);
        }
        return fConnectionLabel;
    }
```

![image 1](https://user-images.githubusercontent.com/600504/37873608-01996bfe-3018-11e8-95aa-2c205595b326.png)

**Comment by jbsarrodie** [comment]
I have to test. This seems very similar in effect.

**Comment by Phillipus** [comment]
I guess the problem with setting it to opaque is this:

**Comment by Phillipus** [comment]
But then if we add opacity value or fill color the user could adjust as needed

**Comment by jbsarrodie** [comment]
OK, that's why I did it differetly. Look at the branch I pushed yesterday. This is a test that works great. I should be able to optimize it through a better clipping area.

**Comment by Phillipus** [comment]
But maybe if the user has options of (1) Opacity and (2) Fill color it provides them with more choice? Perhaps they would like a white label on a grey background?

**Comment by jbsarrodie** [comment]
In this context I'm all for the KISS principle. IMHO our real issue is that label is not readable when set in the middle, not that someone misses label background.

**Comment by jbsarrodie** [comment]
@Phillipus I've just re-pushed my branch with my "final" fix. You can test it and merge it if ok for you.

**Comment by Phillipus** [comment]
@jbsarrodie Yeah, that seems to do the trick. I guess we should merge it and see what users think. If there are any problems with it we can either tweak it, remove it, add an opacity/fill option....

**Comment by janwilmans** [comment]
I'm curious to test this too, I have this also:
![image](https://user-images.githubusercontent.com/5933444/37989418-ecc26884-31f2-11e8-98fb-6a170b727595.png)

in a grey-folder background making it hard to read. I will try the head version to test

**Comment by jbsarrodie** [comment]
Closing as this has been fixed for some time
