### ISSUE TITLE
Junctions should be drawn on relationship layer and not raise ARM

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#272]
After having worked for some time with Archi 4.x and used junctions, I think the following should be done:
- Adding a junction over an element should not raise ARM.
- Junction should be always visible. Might be good to draw them on the relationship layer.

**Comment by jbsarrodie** [comment]
Up!  ;-)

**Comment by Phillipus** [comment]
> Adding a junction over an element should not raise ARM.

If you mean don't show the dialog each time a Junction is dragged into a parent element I can easily exclude Junctions

> Junction should be always visible. Might be good to draw them on the relationship layer.

I don't think if this is possible. "Bring to Front" can move it to the top.

**Comment by jbsarrodie** [comment]
>If you mean don't show the dialog each time a Junction is dragged into a parent element I can easily exclude Junctions

Yes. This is needed because in fact nesting rules don't apply to junction (reminder: junction is not an element but a relationship connector).

>I don't think this is possible. 

I was afraid of this.

>"Bring to Front" can move it to the top.

But if the junction is no more visible you won't be able to right clic on it ;-)

**Comment by Phillipus** [comment]
> junction is not an element but a relationship connector

In GEF/Draw2D it is a "node" so follows the same graphical rules

> But if the junction is no more visible

When is it not visible?

**Comment by jbsarrodie** [comment]
>But worth remembering that In GEF/Draw2D it is a "node" so follows the same graphical rules as other nodes (not on the connection layer)

Yes I know. Not an issue at all (that was just a remark so that anybody reading this can understand why ARM dialog should not appear.

>When is it not visible?

Simply if you move something else on top of it (not a good practice though)

**Comment by Phillipus** [comment]
I've just committed a change so that Junctions are excluded from the ARM dialog.

**Comment by jbsarrodie** [comment]
Thank you!
