### ISSUE TITLE
[Feature Request] Pass through on Import Error (eg Concept ID not found)

### ISSUE THREAD

**Issue by JamesUsmar** [archimatetool/archi#279]
Hi, 

I have found Archi very useful in finding Solution Architecture gaps in requirements, CMDBs and other models through semi-automated approaches creating CSV import files using Excel. The only trouble is Archi stops the CSV import on every missing "Concept ID" not found the elements.csv file. 

My feature request is simply that there is an 'option' to log and omit the relationship when a missing 'Concept ID' is found on processing the relationships.csv, rather than a hard stop of the import on the first find. At the end of the import the log should be shown in simple text box (allowing copy of the text).

Thoughts? 

Many thanks
James Usmar

PS: Apologies, but this is one of a couple of feature requests around the CSV Import feature.

**Comment by Phillipus** [comment]
Are you seeing the missing concept message because you are importing relationships that reference non-existent elements? Would it not be better to try and address the cause of the problem in the CSV file? There's a reason that the error is thrown and stops the import process, in case the model gets corrupt.

**Comment by JamesUsmar** [comment]
I do agree that as a principle the data model must not become corrupt, and so a relation being imported with a missing corresponding concept id in the elements file must not happen... and yes, the error is because on or the other end of a relationship is missing in the elements file as an object.

Accordingly an option toggle should default to a "stop" rather than "omit, log and continue".

The root of the issue is efficiency, time and "value". If I knew the root cause in the empirical data I would have addressed it. I am finding that actually I need to go back to the source empirical data and understand what went wrong at a fundamental level from the source masses of diverse Architecture data I am looking at.

I have found in modelling an existing Architecture it is a little time consuming, when there are a "good few" errors and you are trying to just capture the extent of the data error to address the root cause through identify the pattern of the error. Hence being able optionally to bypass the errors, omit the relationship and get a log of them, would create the most value from an Architecture perspective and be the most valuable use of my time.

Just a thought, if would be a quick win.   

Many thanks for your consideration.
