### ISSUE TITLE
[Feature Request] From the Visualiser enable right click "Select in Model Tree" and "Add to Current View" options

### ISSUE THREAD

**Issue by JamesUsmar** [archimatetool/archi#282]
This is a feature request to ask if it would be possible to add two (ideally) right click menu options from any objects presented in the Visualiser view tab.

I frequently use Archi to communicate how an Architecture is currently with colleagues, and build my view on the fly to satisfy a stakeholders view point. While having the right click "Generate View For..." option is good, I don't always want to jump through the architecture in that way and just want to pull in existing objects and watch the relationships unfold. The "value" being in the ability to show the detail in a structured and assured way. 

Currently I expose the Visualiser to see what objects are related to what, and then have to search for the objects one-by-one in the model tree and manually pull them into the view - quite a tedious activity and I risk losing people while I operate the tool, rather than getting the message across. Automating this from a right click would be really helpful. 

My feature request is therefore to enable on any objects presented, the two additional right click menu options of "Select in Model Tree" and "Add to Current View" from the Visualiser view pane. In the first case the object is selected and highlighted in the model tree, just is as is done elsewhere, and in the second the object is made to appear in the view hanging on my mouse pointer ready for me to drop (or similar).

Many thanks for your consideration, I hope others would find this useful too - after all a fundamental outcome principle of Architecture is to communicate...

Regards,
James Usmar.

**Comment by jbsarrodie** [comment]
Seem an interresting feature. I don't know if/how this is possible though.

+1  ;-)

**Comment by Phillipus** [comment]
As it was fairly trivial to do I've just added a "Select in Model Tree" context menu item to the Visualiser.

Some caveats:

- I won't be adding an "Add to Current View" menu item. Once the object is selected in the model tree the user can drag it into a View from there. And no, I really won't be adding this option. If someone else wants to do it, they can.
- Once the "Select in Model Tree" option is selected in the Visualiser and the element selected in the tree, this will have the side effect of updating the Visualiser to focus on the selected element. If this is undesired, then the "pin" option can be set in the Visualiser to stop this. And no, I won't be changing this behaviour.

**Comment by jbsarrodie** [comment]
>I won't be adding an "Add to Current View" menu item

I agree, and BTW when working with the visualizer, there is no more "current view" (the visualizer itself being the current view).

>this will have the side effect of updating the Visualiser to focus on the selected element. If this is undesired, then the "pin" option can be set in the Visualiser to stop this.

Mmm, I hadn't thought about this one...

>And no, I won't be changing this behaviour.

Do you mean "you don't want this to change" or "You dont want to do it yourself". If last option I can work on it.... ;-)

**Comment by Phillipus** [comment]
> Do you mean "you don't want this to change" or "You dont want to do it yourself". If last option I can work on it.... ;-)

I mean it should not be changed. The Visualiser should show the currently selected object in tree or view. Pin current view in Visualiser works well.

**Comment by JamesUsmar** [comment]
Many thanks for this ... its going to be vey useful feature.

Regards, James Usmar

**Comment by JamesUsmar** [comment]
Many thanks - been very useful seeing this work very well in the last two recent releases!

I believe #282 can be closed. 

Best wishes, James
