### ISSUE TITLE
[FEature Request] Error message on "save" after CSV Import (or similar) lists Object IDs in View that have been orphaned

### ISSUE THREAD

**Issue by JamesUsmar** [archimatetool/archi#283]
I am increasingly noticing that as I use Archi, importing empirical sources of data, that any views I may have are not updating. This is resulting on "Save" with an error message being generated stating that I have orphaned relations or objects in various Views. The error message is a simple text message box. The save, I think, has not worked either... so I believe I need to fix the integrity issues before I can successfully save.

By deleting the listed views I can then save successfully.

My feature request is to ask if I possible to provide a link to each view on that error message dialogue or even offer a "global fix" by deleting views or broken parts of a view button. The data integrity of the model is vital, but trying to find random ids in a in a list of view that have become orphaned is impossible.     

Many thanks
James Usmar

**Comment by Phillipus** [comment]
> importing empirical sources of data

Are you importing CSV data that does not resolve objects? If so, you asking the app to fix problems that you should be fixing. Let me say that if you are going to inport CSV please ensure that you know what you are doing.
