### ISSUE TITLE
[Feature Request] Current model filename and path in window title 

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#284]
I propose to show currently selected/edited model's filename and trimmed path in the window title.

The motivation is to avoid editing the wrong .archimate file by accident. (Yes it happened to me :)

**Comment by JamesUsmar** [comment]
+1 from me.

_It is annoying to start editing the model only to realise the top model was the last one you worked on that happened to have a similar name to the .archimate file you just double clicked on to open in Explorer. Appreciate that the path and file name of the model are in the Properties dialogue - but that's only visible if you have the model root selected in the Tree View at the time._

Regards, James Usmar

**Comment by Phillipus** [comment]
This has been added now. Will be in the next build.

**Comment by Phillipus** [comment]
Fixed in 4.2
