### ISSUE TITLE
Ghost Views from Dead Models

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#285]
Hi

I've got only one model folder in my .archimate document. But when Archi opens, there are literally scores of view tabs at the top of the page for views from previous models that I created in past. These view tabs say "this view is no longer available". 

But the .archimate file does not have those models in it any more.

How can I get rid of these undead zombie ghost views from past models that are no longer even in the current .archimate file?

Thanks

![ghost views from non existent model](https://user-images.githubusercontent.com/30424386/31314938-420e4c5c-ac58-11e7-8684-223730cae6bc.png)

### Version of Archi, Operating System
com.archimatetool.editor.buildid=201709061211
com.archimatetool.editor.versionid=4.0.3
Windows 10 latest

**Comment by Phillipus** [comment]
This can happen if you have these views open, close Archi, delete the *.archimate file and re-open. It is trying to preserve the state. Simply close the tabs.

**Comment by MilennialZero** [comment]
Hi Phil - I do that - close all the tabs - save only the current model - there are no other models in the *.archimate file, only the one model - but the next time I open the *.archimate file, the views reappear from a prior different model. Am I misunderstanding your instructions? 

I would have thought that closing the ghost views and saving the model would have eliminated them...

**Comment by Phillipus** [comment]
So, you're saying that these ghost views open when you open the *.archimate file? From the "open" menu? Does the file in the message in your screenshot exist? So you have the option set in prefs to open all views in a model?

**Comment by MilennialZero** [comment]
![not ticked auto open views in a model](https://user-images.githubusercontent.com/30424386/31315904-fae0bb88-ac6d-11e7-803e-408351db8b31.png)
Correct. I open by clicking a shortcut to the .archimate file which is on Dropbox. If I "open" the .archimate file from within Archi, the same thing happens. I don't have the box ticked to open all views in a model. Tx for your help.

**Comment by MilennialZero** [comment]
Actually, I lied. If I 'open' the actual *.archimate file from Archi, the old views do not appear. But if I open the same *.archimate file using the shortcut to Dropbox, the ghost views are displayed.

I have no idea why launching via a shortcut would open the file differently?

**Comment by MilennialZero** [comment]
That is, if I click on the source *.archimate file on Dropbox - no empty old views are displayed. But if I open the *.archimate file via a shortcut, they are displayed. ???

**Comment by Phillipus** [comment]
Please, it's hard for me to help here if I don't have clear and exact steps to reproduce the issue. Please tell me how I can reproduce the problem.

**Comment by Phillipus** [comment]
Try this:

1. Open Archi
2. Close all models in the Model tree.
3. From the Help menu choose "Reset to Defaults..."
4. When prompted restart Archi
5. When Archi restarts, close the Welcome screen and re-arrange tabs and windows as you wish

**Comment by MilennialZero** [comment]
Phil - that worked. Eternally grateful for your help. I had attempted to reset defaults from the "Preferences" panels, but missed the "Reset to Defaults" on the Help menu. :-( (Perhaps all "reset to default" kill switches should be in one location?) Thanks again. Jon

**Comment by Phillipus** [comment]
Jon, good to hear! 

Archi (or Eclipse based apps) try to save "state" of open windows, tabs, editors etc in a file:

C:\Users\yourname\AppData\Roaming\Archi4\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi

When launching Archi from scratch it tries to restore this state from this file. So if, in between closing Archi and re-opening it, a file is moved or deleted, the state cannot be restored.

Doing a "Reset to Defaults" deletes that "workbench.xmi" file and the state
