### ISSUE TITLE
[Bug - very minor] “File|Export|Model To Open Exchange File…” defaults to users home directory 

### ISSUE THREAD

**Issue by JamesUsmar** [archimatetool/archi#291]
“File|Export|Model To Open Exchange File…” defaults to users home directory (I presume an environment variable is being used?) – other options default to the models' current directory location which seems more sensible. (Note: On selecting “Choose” it defaults to the current directory that Archi was launched from.)

### Version of Archi, Operating System
4.0.3, Windows 10

### Expected Behaviour
Selecting “File|Export|Model To Open Exchange File…” defaults to current working directory

### Actual Behaviour
“File|Export|Model To Open Exchange File…” defaults to users home directory
... but offer the current working directory on selecting "Choose".

### Steps to Reproduce the Behaviour
1. Select “File|Export|Model To Open Exchange File…”

This is very minor, it just not what I would have expected. 

Thanks
James.

**Comment by Phillipus** [comment]
This default happens only the very first time the Export dialog is opened. Thereafter, it remembers the last directory the user chose after the export is done.

It's a safe default for the very first time, and many other apps do the same. You'll never see it again once you've selected a different folder and clicked OK.

Won't change, so closing.
