### ISSUE TITLE
[Feature Request] Enable the zoom in/out of the Documentation text

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#297]
As identified in #293 the request is to enable zooming in/out Documentation text area.

Usage: CTRL scroll wheel on mouse enlarges / shrinks the text size in Documentation area, when this area gets focus.

This is different to #296 which discusses the whole UI theming using CSS.

**Comment by Phillipus** [comment]
OK, why not.

Also CTRL + 0 key resets to standard height.

Will be in next version.

**Comment by Phillipus** [comment]
In 4.1.0
