### ISSUE TITLE
[qSSSSSQQQQZ]

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#298]
### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Mistake here?

**Comment by MilennialZero** [comment]
True story: spilled just a few drops of English Breakfast on keyboard yesterday. Today, the "a" key decided to pack it in. Keyboard in the bin. 

Sorry. Scratch that post. :-(

Jon McLeod
Director
McLeod Consultancy Pty Ltd
GPO Box 813, Canberra ACT 2601 Australia
Silver Member, The Open Group

**Comment by Phillipus** [comment]
OK, Jon. Closng this...will wait for Jon to get new keyboard...
