### ISSUE TITLE
[Defect by design] Adding existing relationship when more relationships exist

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#299]
Situation: 
 - Having element A and element B
 - Having 2 "used by" relationship between A and B with different documentation 

New View - adding used by connection between A and B shows dialog for referencing already existing relationship. When hitting Yes, it applies only one of them.

I would like to list both relationships in such dialog for the selection which to apply.

**Comment by Phillipus** [comment]
I'll close this one so we can carry on in #581
