### ISSUE TITLE
bigger influences symbols

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#301]
[Feature Request]
Another trivial one. Probably not a lot of people will care about.
When using the "influences" relationship symbols (++, +, 0, -, --), they're a bit hard to see on the line. Even when I'm using a 27 inch HD monitor.
If these could be rendered as big, bold symbols, it would be nice.
![signs hard to see](https://user-images.githubusercontent.com/30424386/31847636-43f32520-b66b-11e7-9bdc-245d961d6bde.png)

**Comment by Phillipus** [comment]
Jon, try setting the font size bigger for the connection in Properties->Appearance.

**Comment by MilennialZero** [comment]
Ah. Of course. Thanks! :-)

**Comment by Phillipus** [comment]
I'll close this, then.
