### ISSUE TITLE
Question: How to add documents to an archi project like non-functional requirements

### ISSUE THREAD

**Issue by alberttwong** [archimatetool/archi#303]
Is there a way to add text documents to a project?  I'd like to add NFR doc or an architectural decisions doc.

**Comment by Phillipus** [comment]
You can't actually embed documents into an Archi model. You can, however, add text to the "Documentation" field for each model, concept or view. If you wish to link to an online resource you can add a URL (like http://www.somewhere/resource.doc) to the Documentation text field or in the value of a property.

**Comment by jbsarrodie** [comment]
Closing this issue as we wont implement embedded document in Archi. But in some aspects this related to issue #322 (hyperlinks to local content?).

The best solution asof today is to host your docs in a web based system (might be as simple as running a lightweight http server that serves your document folder) and use URL in Documentation or Properties.

**Comment by theunsfvo** [comment]
cool

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*
*    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>*

**Comment by mikisvandijk** [comment]
Any chance you will implement a hyperlink / filelink thats's directly clickable from the archimate element (e.g. application, note)?

It would really enhance the functionality of my models that I distribute as a HTML-export in my organisation.

It's true one can use the 'documentation' field for it, but an end-user not aware of the structure of the tooling just would want a button and click on it. 

On a small scale I create a clickable button already by editing the generated HTML after export. 
But I have to do that everytime again, making it an obtacle to publish my work as often as I would like...
