### ISSUE TITLE
Archi crashes on adding a "note" element

### ISSUE THREAD

**Issue by ldasari** [archimatetool/archi#305]
### Version of Archi, Operating System
Which version of Archi are you using? Are you on Windows, Mac, Linux? Version of these? 

- Archi 4.0.2 on Mac OS Sierra v10.12.6

### Expected Behaviour

Note element when dragged and dropped from the Palette should be placed on the view just as any other element from the palette

### Actual Behaviour

- Archi crashes as soon as the note element is dropped onto the view

### Steps to Reproduce the Behaviour
1. Create a new model
2. Drag the note element on to an empty or existing view
2. Archi crashes as soon as the note element is dropped onto the view.

**Comment by Phillipus** [comment]
This is related to a touchbar bug. Do the following to disable the touch bar completely for Archi from the Mac terminal app:

defaults write Archi NSFunctionBarAPIEnabled -bool NO

**Comment by ldasari** [comment]
That worked. Thank you for your quick response!

**Comment by ldasari** [comment]
Resolved by typing "defaults write Archi NSFunctionBarAPIEnabled -bool NO" on the Mac terminal App.

**Comment by Phillipus** [comment]
For reference see https://bugs.eclipse.org/bugs/show_bug.cgi?id=508366

It's an Eclipse/Apple bug and they can't reproduce it.
