### ISSUE TITLE
Sizing Objects

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#306]
# [Feature Request]
It would be good to have a menu option to match object size in BOTH width and height simultaneously.
Also - it would be good to see (right click) the width and height of a selected object in pixels.
Also - the edit preference for default object width and height are numeric - but it is not shown that the measurement is pixels (which I assume it is, but it would be nice to know)
:-) 
![object size match archi](https://user-images.githubusercontent.com/30424386/32132664-99dabca2-bc13-11e7-8002-3fcbaa04d3e5.png)

**Comment by RonaldMeringer** [comment]
Totally agree.   I am copying the BIAN Service Landscape v9.0 and there are about 354 objects that need to be resized. While I could do it column by column, there could be a better way...

**Comment by Phillipus** [comment]
It turns out that adding an additional menu item of "Match Size" to match both width and height is not so hard. Will be in the next version of Archi.

**Comment by Phillipus** [comment]
> It turns out that adding an additional menu item of "Match Size" to match both width and height is not so hard. Will be in the next version of Archi.

So I'll close this.
