### ISSUE TITLE
[Bug] Search Filter missing Strategy, Physical and Junction elements

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#308]
In Archi 4.0.3, the model filter doesn't yet have the ability to filter on the newer elements: Resource, Capability, Course of Action; Equipment, Facility, Distribution Network, Material. (Are there others I'm missing?).

**Comment by Phillipus** [comment]
Good spot. I've added them (and Junction) to the Search Filter and will be in the next version of Archi (coming soon).

**Comment by Phillipus** [comment]
In 4.1.0
