### ISSUE TITLE
Export Loses Hidden Relationships upon Re-Import

### ISSUE THREAD

**Issue by NicholasJLambert** [archimatetool/archi#309]
### Version of Archi, Operating System
Mac OSX 10.10.5 (14F2511)
Archi 4.0.2, Build 201706161020

### Expected Behaviour
When I export a model with a relationships that have been been created via the "nested Elements Relationship" (in this case the assignment between a Business Role and a Business Process), I expect that these relationships are exported in the xml file and will re-appear correctly when the file is reimported.   

### Actual Behaviour
Upon import, relationships (the assignment between a Business Role and a Business Process) that had been created via the "nested Elements Relationship" are present in the relations folder, but are shown in itallics. When queried using the analysis tab in the properties window they are not present in the model (i.e they have become unattached from the objects).
If however the nested object is pulled off the other object that it has been nested onto, and the relationship is shown on the diagram, then this is exported correctly and when imported from the xml file it is shown to be visible in the diagram and in the analysis tab. 
I have not yet checked to see if this is an issue for other nested element relationships.

### Steps to Reproduce the Behaviour
1. drag a Business Process onto a Business role and create the assignment relationship via the "nested Elements Relationship" dialogue box.
2. Create a second example of this, but after creation, drag the Business Process off the Role to make the assignment relationship visible
3. save and export the model
4. import the model
5. check the relations folder and note that one relationship is in italics (i.e un-attached) and the other is not (i.e OK)

Grateful if you could fix this ASAP as otherwise I have a lot of re-modelling to do if I am to share my model with users in other organisations who have to use other Archimate 3 compliant toolsets !

**Comment by Phillipus** [comment]
Hi, thanks for the detailed report.

Yes, I see the problem. Nested connections are not exported explicitly in the Exchange Format (deliberate) but not re-parsed as an explicit connection when importing.

I'll come up with a fix this week.

**Comment by NicholasJLambert** [comment]
Many thanks !

Nick Lambert

**Comment by Phillipus** [comment]
@NicholasJLambert 

Please try the latest beta - https://www.archimatetool.com/dev/beta

**Comment by NicholasJLambert** [comment]
Phil

The export seems to be fixed now. The nested relationships are no longer itallic and appear in the model

Many thanks for the rapid tunaround!!

Nick

**Comment by Phillipus** [comment]
In 4.1.0

**Comment by lavenderb** [comment]
Hi Phillipus,
I was about to report the fact that nested relationships are not exported in the Exchange format as a bug - but noticed your comment that this is deliberate.
Could you share the rationale for this? 
Would you be open to reconsideration, given a good use case?
Rgds
