### ISSUE TITLE
Labels set to 'middle' on relationships end up over the top of the relationship

### ISSUE THREAD

**Issue by mjtapp** [archimatetool/archi#31]
For labels that are in the 'middle' of a relationship, the label ends up over the top of the relationship when the relationship is horizontal in v2.6 which is kind of ugly. It doesn't happen if you choose 'target' or 'source', for these the label ends up underneath which is much nicer. 

It would be good to have a little more flexibility around where exactly the labels are placed in relation to the relationship as a general rule anyway, for example if the relation is horizontal, sometimes you might want the label above the line rather than below.

**Comment by mennolodder** [comment]
Totally agree, this is particularly useful when having long relations. 

Enterprise Architect allows you to grab the label of a connection and move it relative to it's original position.

**Comment by jbsarrodie** [comment]
Moveable connections are a bit to hard, but not showing the part of the relationship under the label is possible. I'm working on it.

**Comment by Phillipus** [comment]
Opacity of label might do it?

**Comment by jbsarrodie** [comment]
As far as I can tell no. My idea is to tune the paint function of relationship to "erase" the area of the label.

**Comment by Phillipus** [comment]
Implemented
