### ISSUE TITLE
Line jump curves not working in some cases

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#311]
Archi 4.0.3, Windows and Mac

See http://forum.archimatetool.com/index.php?topic=451.msg2498

**Comment by Phillipus** [comment]
Example:

![image](https://user-images.githubusercontent.com/600504/32442584-dcc0db28-c2f3-11e7-9300-15e3d9e5c6d8.png)

**Comment by Phillipus** [comment]
test.archimate file:

[test.zip](https://github.com/archimatetool/archi/files/1446292/test.zip)

**Comment by Phillipus** [comment]
Might be an issue to do with connection to connection in com.archimatetool.editor.diagram.figures.connections.RoundedPolylineConnection

@jbsarrodie ?

**Comment by jbsarrodie** [comment]
Hi,

I'll have a look at it. Should be easy to fix.

**Comment by Phillipus** [comment]
> Should be easy to fix.

🤣

**Comment by jbsarrodie** [comment]
Was easy. See new linejump-fix branch :-)

TBH the root cause lies in OrthogonalAnchor that has to be adapted for connection-to-connection (now on my todo), but the point comparison method was too strict anyway.

**Comment by Phillipus** [comment]
> Was easy.

Nooooooo!!!!!

Merged ;-)

**Comment by jbsarrodie** [comment]
>Merged ;-)

Well.... I haven't had time to do in depth tests, so we might have some side effects (who knows....)

**Comment by Phillipus** [comment]
That's why we have betas...

**Comment by Phillipus** [comment]
In 4.1.0
