### ISSUE TITLE
4.1.0 Changing default figure appearance does not apply to existing elements on the views

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#313]
### Version of Archi, Operating System

Archi-Win64-4.1.0-beta20171106
Windows 10 Pro Version 1703 OS Build 15063.413

### Expected Behaviour

Changing default figure appearance.

### Actual Behaviour

Changes does not apply to existing elements on the views.

### Steps to Reproduce the Behaviour
1. Edit - 
2. Preferences - 
3. Diagram - 
4. Default Figures 
5. Click Alternative figure display
6. Click Apply
7. Click Apply & Close

**Comment by Phillipus** [comment]
This is not how it works. The preference sets the type of of figure that will be used when adding a _new_ element to a view. You can change existing figures from the Properties tab.

**Comment by theunsfvo** [comment]
I see, so if I have a hundred components that I want to load in the new version I have to change them all, one by one, in every view?

**Comment by Phillipus** [comment]
Yes. Users may wish to have alternate figures in different views per model. Changing a figure globally would not allow this.

**Comment by theunsfvo** [comment]
Alright.

Should I put in a feature request to globally or per view figure change
option?

Because it means that I can't use the new version until I have finished my
current project and start a new model, because we have over 90 views
already with a specific figure display for components.

Thanks,
Theuns

"I love deadlines. I like the whooshing sound they make as they fly by."
Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by Phillipus** [comment]
You could, but I doubt it would be a priority to implement. Or you could edit the *.archimate file directly and add the attribute type="1" or type="0" to a "archimate:DiagramObject" child tags.

**Comment by theunsfvo** [comment]
Alright, let me try the file edit option rather.

Thanks Phil.

Thanks,
Theuns

"I love deadlines. I like the whooshing sound they make as they fly by."
Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by jbsarrodie** [comment]
Shall we close this Issue ? Was the "file edit" option ok for you?

**Comment by theunsfvo** [comment]
Hi Jean-Babtiste.

Too much work work to find all the elements to change, i just had to change
each view as and when i load it.

Still think it would be a great option to have but if it is not high
priority it can be closed.

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*

**Comment by jbsarrodie** [comment]
Ok, I flag it as feature. I let it open until we agree on the target (implement it, do it through a workaround, don't do anything...).

Thank you

**Comment by theunsfvo** [comment]
Ps. Having a look at the .archimate file and
searched archimate:DiagramObject to add the type attribute but this will
change it for ALL elements and I only need to replace the Component element
default figure and not everything.

It doesn't look like there is a way of of identifying the type of
DiagramObject easily because it only has id and element references, not
element type references...


Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*
*    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>*

**Comment by theunsfvo** [comment]
PPs. the default figures in the preferences are also not grouped logically,
application component, device and node have a different default figure than
the rest, meaning that all the others show the small icon inside the
element but those three are not, they are swapped around...

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*
*    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>*
