### ISSUE TITLE
Dispay User Properties in diagram

### ISSUE THREAD

**Issue by neothoms** [archimatetool/archi#315]
I woud love to use ArchiMateTools but a few things are not like I want them to be.

I want to use properties.
But they are useless if they only show in the report.
I want some of them to be displayed in the diagram in addition of the name.

**Comment by Phillipus** [comment]
Other users have found many uses for Properties, and so not necessarily  "useless". 

We already have a feature request for this, so closing:

https://github.com/archimatetool/archi/issues/171

**Comment by MilennialZero** [comment]
"Displayed in the diagram"?

Or displayed on the entity, in some way?

Such as like what we do in Visio smart shapes, by linking to an
Excel workbook: 
If there was an add-on for this kind of thing, I'd definitely pay for
it.
PS: I hate Excel. I hate Visio Pro.

I wish Archi had three "modes":

1. Plain and simple - like now - for quick modelling.

2. Matrix view - dynamically switch between graphical view and a simple
   row/column matrix list of entities on the diagram that I could select
   and copy and paste directly into an Excel spreadsheet without having
   to export the whole model. No relationships, just entities. If I
   could also have the matrix display a column for a property that I
   want to enter for all entities on the diagram - bonus.
3. A third mode for graphical presentation purposes where I could say
   "Right. I need to tidy up this particular diagram so I can show it to
   a specific audience, and it needs to have a legend on it, and
   borders, and a title, and maybe some text call-outs that point to
   specific elements on the diagram. And I really won't need an
   expensive Visio Pro license anymore."
But I don't want a lot of menus, palettes, dialogue boxes always in my
face making the UI complicated. The UI for IBM Rational System
Architect is so complex it's unworkable. The UI for Sparx is worse for
the same reason. All bloated crapware. Of all the tools I've used,
Archi has the best UI by far. Simple is good. And we don't want to
bollocks that up, do we?
----- Original message -----

**Comment by herve91** [comment]
Points 1 and 2 are covered (at least partially) by Archi's form plugin: [https://github.com/archi-contribs/form-plugin](url)

**Comment by neothoms** [comment]
I completely agry with you MilennialZero

**Comment by jbsarrodie** [comment]
HI,

As pointed out by Herve, point 2 is covered by its "form" plugin.

IMHO part of point 3 is covered by Canvas & Sketch

BTW - This makes me think I really have to find time to describe/share detailed roadmap/idea/wishlist...

**Comment by MilennialZero** [comment]
Didn't know about the forms add-in.

There are probably many add-ins I'd be interested in. But I don't know
about them. Perhaps they should be noted on the Archi home page?
I'm not really confident or knowledgeable about the process for
installing. I know what Eclipse is, but that's about as far as it goes.
The documentation on what the add-ins do could be improved. It's a
bit skimpy.
Hopefully Archi isn't targeted at coders and people who enjoy and know
their way around GitHub.
Archi is a tool for learning (Archimate), it may not always be the case
that business analysts and architects seeking to use Archi for learning
Archimate come to Archi with knowledge of the terms and technologies
mentioned on the add-in GitHub or wikis.
Thanks for the heads up on the forms add-in. I'll give it a go and see
how far I get.
----- Original message -----

**Comment by jbsarrodie** [comment]
>There are probably many add-ins I'd be interested in. But I don't know
about them. Perhaps they should be noted on the Archi home page?
I'm not really confident or knowledgeable about the process for
installing.

Archi's plugin page only list plugins maintained by Phil and me. This restriction is somewhat needed or else people start asking us support for things we don't maintain. But there's a [public page](http://archi-contribs.github.io/) associated with most plugins hosted on github. I must admit that I haven't updated it for a while...

Maybe a community maintained wiki page on the Archi wiki would be best suited. We could then easily put a link on this wiki page on main Archi website.

Last: the process of installing is as simple as copying a .jar file to the plugin sub-folder of Archi. There is even now a menu entry to do it from within Archi (but this requires a different packaging based on a zip file).

**Comment by herve91** [comment]
Hi JB,

Do you mind adding my plugins on your [public page](http://archi-contribs.github.io/) please ?
- [**Form plugin**](https://github.com/archi-contribs/form-plugin): add the ability to show and update elements and relationships properties in a form
- [**Specialization plugin**](https://github.com/archi-contribs/specialization-plugin): allow to change the icon of elements and to replace the label of elements and relationships
- [**Script plugin**](https://github.com/archi-contribs/script-plugin): automates some actions (load model, generate web site, ...)
- [**Database plugin**](https://github.com/archi-contribs/database-plugin): persist Archimate models in a central database (SQL or Neo4J)
- [**Service Now import plugin**](https://github.com/archi-contribs/snow-import-plugin): Download CMDB information from Service Now web services and convert them to Archimate elements and relationships

Thanks
Hervé

**Comment by jbsarrodie** [comment]
@herve91 I'll do it asap

**Comment by jbsarrodie** [comment]
@herve91 Done ;-)

**Comment by herve91** [comment]
Thanks a lot :)
