### ISSUE TITLE
[feature request] Find/replace searching on "documentation" field

### ISSUE THREAD

**Issue by joao-paulo-c** [archimatetool/archi#317]
Hi.

For me it would be useful to find elements by searching at "Documentation" field, which one can find at the "Properties" (Alt+Enter) of an element (at "Main" sheet).

I use this field to document some additional information about some elements, which I don't want to show at the diagrams. Some times I have to skim the elements to find those which I put specific "documentations".

Att.
João Paulo

**Comment by Phillipus** [comment]
You can search on Documentation using the Search Bar in the Model Tree.

**Comment by joao-paulo-c** [comment]
Thanks for your answering. Sorry for opening the feature request. I'll close the issue.
