### ISSUE TITLE
Dragging a View onto a Diagram Creates a Link

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#319]
Just discovered by accident that one can drag a view onto a diagram and it becomes a link to the diagram.

This is useful. Why didn't I know this before?

This is my issue.

**Comment by Phillipus** [comment]
Well, I guess not reading the manual could be a bug... ;-)

**Comment by MilennialZero** [comment]
"Read the manual"?

Requirement: Needs built-in autonomous robotic AI to tell the user what they want to do and how.

Next release?

Jon McLeod
Director
McLeod Consultancy Pty Ltd
GPO Box 813, Canberra ACT 2601 Australia
Silver Member, The Open Group

**Comment by MilennialZero** [comment]
Or: 
![a-billion-is-a-thousand-million-why-wasnt-robert-mankof](https://user-images.githubusercontent.com/30424386/32928038-2475db18-cba4-11e7-92c6-a363d6859142.jpg)
