### ISSUE TITLE
Google Open Doc URLS Don't Display or Work as Hyperlink in Archi

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#320]
http://www.abs.gov.au/ausstats/abs@.nsf/productsbytopic/76CD93AA32E74B29CA25713E0005A2EA?OpenDocument

Type the above into the Documentation panel of an element. Hyperlink formatting doesn't extend beyond the ampersand symbol - and clicking on the link does not navigate to the full URL location.

**Comment by Phillipus** [comment]
Fixed for next version
