### ISSUE TITLE
[Bug] Export To Excel of Forms Plugin of a Table fails

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#321]
### Version of Archi, Operating System
archi 4.0.3
org.archicontribs.form plugin 1.8.1 (or earlier)
Windows and Mac

[FormPlugin.log](https://github.com/archimatetool/archi/files/1488296/FormPlugin.log)

### Expected Behaviour
The table should get exported to excel

### Actual Behaviour
I get an error popup of "Failed To update Excel file." "null". 

### Steps to Reproduce the Behaviour
1. By following the form wiki instructions Create a simple form with a table and some lines. I set   "excelFirstLine": 1
2. Run the form and get some data back.
3. Export to excel 

### Workaround
Add this to the config file as well as the excelFirstLine, but set to 1.
                  "excelLastLine": 1,

So either the wiki needs to say this, or the code needs to default last to first.

**Comment by jbsarrodie** [comment]
Hi,

You on the wrong repository. The form plugin is maintained by @herve91 on its own repository.

Regards

**Comment by Phillipus** [comment]
https://github.com/archi-contribs/form-plugin/issues

**Comment by jbsarrodie** [comment]
FWIW I've created the issue for you ;-)

https://github.com/archi-contribs/form-plugin/issues/7

**Comment by rich-biker** [comment]
Many thanks - sorry for misplacing.

Regards,
Richard.
