### ISSUE TITLE
hyperlinks to local content? 

### ISSUE THREAD

**Issue by MilennialZero** [archimatetool/archi#322]
I don't seem to be able to make this work:

I want to put an Archi repository in a folder. In the same folder, I want to put non-archi content - HTML pages that contain textual narrative, which may contain links to other content (in the same folder or anywhere). I may also put MS Word docs in the same folder, and link to those. 

How do I create a clickable hyperlink in the Documentation section of a view or entity that will link to content in the same folder as the Archi repository?

I've tried file:/// and href and http:/ - but haven't been able to get it to work. I know it's possible. Links to 

As a feature request - it might be useful to have a non-Archimate entity (hyperlink) that I can drag onto a diagram.

**Comment by Phillipus** [comment]
Jon, only external links are supported http, https, ftp at the moment. This was intended to ensure that Archi files could be opened by different users without local files.

**Comment by MilennialZero** [comment]
Phil

Mmm. So I have to host my content on a html server somewhere and link to
that. Okay. I can do that. It's probably a better approach anyway.
I'm only using Archi as a personal repository. Other architects are too
lazy to learn 1. Archimate 2. How to use Archi the tool, 3. How to use
any architecture modelling tool other than Excel, Visio, PowerPoint.
I keep my Archi repository on Dropbox. Archi probably doesn't support
server-based functions: check-in, check-out, integrity checking, roll-
back, etc.?
Given there are so few architects willing to learn Archimate, I prefer
to give them  the HTML content generated by Archi. If they want, I can
give them a copy of the Archi repository file that I maintain. If they
want to change any of the views I've created, they come to me and I'll
keep the master copy up to date. And that gives me a chance to detect
any errors and misunderstanding in what they're trying to model.
I often print Archimate views, and other architects sometimes transcribe
my work into Visio diagrams. Like medieval monks with quill pens.
Archi works best with a data projector, creating smaller, more tightly
focused architecture digrams. I have developed several "techniques" for
structuring models and views I create.
We still print A0 Visio diagrams for people to use in workshops. And
that approach is useful for certain types content.
Often I hear colleagues say "Oh, we don't know how to use an
architecture modelling tool, so we won't be able to access the
information you're capturing, so you shouldn't use a tool". When that
happens, I tell my colleagues "I'm not using an architecture modelling
tool. This is just how I take my personal notes. You use Excel and
OneNote. You take notes using a paper notebook and a pen. I use this. I
don't tell you how to take notes, do I?"

--
  Jon McLeod
  Senior Consultant
  From Here On
  www.fromhereon.com
  +61 457 988 821
  jon.mcleod@fromhereon.com
 
  Jon McLeod
  Director, McLeod Consultancy Pty Ltd
  GPO Box 813 Canberra ACT 2601 Australia
  +61 457 988 821
  jmcleod@thelonius.com.au
  Silver Member The Open Group Architecture Forum

----- Original message -----

**Comment by jbsarrodie** [comment]
Hi Jon,

>I keep my Archi repository on Dropbox

So you can also host other files on Dropbox and use links to them.

>Archi probably doesn't support server-based functions: check-in, check-out, integrity checking, roll- back, etc.?

It does through the [Collaboration plugin](https://archimatetool.com/plugins). Each model should then be stored on a Git repository that will be fully managed through Archi without prior git knowledge. You can use git hosting services like [bitbucket](https://bitbucket.org/). Bitbucket has the great advantage to allow private repository, so your models would be accessible only to you.

At some point we might create some tuned hosting system for that purpose. Maybe with a free (but public) and paid (and private) plans...

**Comment by Phillipus** [comment]
We support `file://` protocol now since Archi 4.6.
