### ISSUE TITLE
Clipboard export shortened links text

### ISSUE THREAD

**Issue by Petrolevb** [archimatetool/archi#324]
### Version of Archi, Operating System
Archi v4.0.3, on Windows 7 x32 & Windows 10 x64

### Expected Behaviour
Copy the view as an image should not depend on the zoom used in the view

### Actual Behaviour
The image exported takes into account the current zoom used in the view, and if the name on links are shortened in the View, they will be shortened in the extract

### Steps to Reproduce the Behaviour
1. Create two objects  
2. Add a link with a long name between them
3. Set the Property "Text Position" in the Appearance of the link to Source or Target
4. Set the zoom to 75% (at this moment, the view should have the name shortened)
5. Export the image to the clipboard (through the menu Edit->Copy Image to Clipboard or via Ctrl+Maj+C)
![image](https://user-images.githubusercontent.com/1260264/33069796-ef2c6fde-ceb5-11e7-8658-87c1b79386a5.png)

**Comment by jbsarrodie** [comment]
Fixed (was a side effect of another bug). Will be in Archi 4.2.1
