### ISSUE TITLE
Archi cuts header string in Jusper reports 

### ISSUE THREAD

**Issue by mdvadim** [archimatetool/archi#325]
### Version of Archi, Operating System
Archi 4.1.0., Win7

### Expected Behaviour
Header string must be full length. 

### Actual Behaviour
Header string was truncated in Jasper report pdf, docx, pptx three.

### Steps to Reproduce the Behaviour
1.This is *.pdf

![2017-11-27_16-00-53](https://user-images.githubusercontent.com/29094130/33258547-890c111a-d38c-11e7-9339-2712c8ecc971.png)

2. This is *.docx
![default](https://user-images.githubusercontent.com/29094130/33258602-bf41d468-d38c-11e7-9d98-483b4132931c.png)

3.This is *.pptx
![default](https://user-images.githubusercontent.com/29094130/33258702-09034b36-d38d-11e7-922f-3f65cf1960ed.png)

Previous jasper report of previous version of Archi for this model from Jul 28 looks same.
![default](https://user-images.githubusercontent.com/29094130/33258992-f96641a0-d38d-11e7-9252-0ae27d959020.png)

**Comment by Phillipus** [comment]
Fixed for 4.1.1 release

**Comment by mdvadim** [comment]
Hi @Phillipus 
Not in version 4.1.1-beta20171127?
![default](https://user-images.githubusercontent.com/29094130/33305326-384f7de8-d440-11e7-8b74-08aaac2e7577.png)

**Comment by Phillipus** [comment]
Is that the name of a View?

**Comment by mdvadim** [comment]
Yes, it is.


![default](https://user-images.githubusercontent.com/29094130/33312093-6c5cad4a-d459-11e7-875c-52cf5d177b00.png)

**Comment by Phillipus** [comment]
Tested here:

![image](https://user-images.githubusercontent.com/600504/33312177-ff29b8f6-d41e-11e7-858c-e6e8a42de9c4.png)

**Comment by mdvadim** [comment]
What is wrong?
![default](https://user-images.githubusercontent.com/29094130/33312821-85277588-d45b-11e7-8077-d23b123c0e25.png)

**Comment by mdvadim** [comment]
apparently, this is a localization error
That is native 4.1.1.beta (without localization) report:

![default](https://user-images.githubusercontent.com/29094130/33313337-f44fdc38-d45c-11e7-9883-2c39e5b3cff8.png)

**Comment by Phillipus** [comment]
OK, so there's nothing I need to do my end.

**Comment by mdvadim** [comment]
For sure, this problem is related to the locale

That Archi 4.1.1.beta report before localization
![default](https://user-images.githubusercontent.com/29094130/33313829-5e2efb74-d45e-11e7-8947-def171ff2269.png)

That Archi 4.1.1.beta report after localization
![default](https://user-images.githubusercontent.com/29094130/33313851-70b1d988-d45e-11e7-9b82-1da6c0c2adb1.png)
