### ISSUE TITLE
Images are pixelated on 4.1.0 when exporting

### ISSUE THREAD

**Issue by yellek** [archimatetool/archi#326]
### Version of Archi, Operating System

4.1.0, Windows 10

### Expected Behaviour

Exported images should be crisp and clear at 100%

### Actual Behaviour

Images are pixelated, Element borders not rendered

### Steps to Reproduce the Behaviour
1. Open a view
2. Export view as image
3. Look at the image in an internal editor

**Comment by Phillipus** [comment]
Can you provide an example please?

**Comment by yellek** [comment]
Here you go...
![archi 4 1 0 export](https://user-images.githubusercontent.com/3826930/33262956-1eb21a00-d3bc-11e7-841e-892071ba3367.png)
![archi previous export](https://user-images.githubusercontent.com/3826930/33262961-220641cc-d3bc-11e7-9599-611a7b3b881a.png)

Both files were exported at 100% to PNG. Archi 4.1.0 is noticably worse.

**Comment by Phillipus** [comment]
Do you have the View at 100% in the zoom control in the app? This should be set to 100%.

**Comment by yellek** [comment]
Yep, both exported at 100%. Scaling up to 400% doesn't restore the box borders. I'm hoping this is user error, I have a 90 page document due tomorrow.

SVG is rendering correctly in Chrome but not in Visio or Gimp.

**Comment by Phillipus** [comment]
What machine are you using? Does it have a hi-res screen? If so, can you compare when using another non-hi-res screen machine? Can you compare with Archi 4.0.3?

I'm trying to see if there is a regression in the image export code. 4.1 uses a different version of Eclipse which has deprecated image methods.

**Comment by yellek** [comment]
I am using a MS Surface with Windows 10 and yes it does have a Hi Res Screen. I will see if I can get Archi installed on another machine at work tomorrow (10pm here). The second image was exported from Archi 4.0.3 with the same settings (100% png). They are different diagrams but the same scale.

**Comment by yellek** [comment]
The size on the second image (and other images from 4.0.3) is about double what I would expect. The boxes are about 288 pixels wide and 144 pixels high whereas I would expect 144 wide and 72 high. The 4.1.0 image has the correct dimensions but the rendering is poor. Given this screen is scaled at 200% the factor of 2 makes sense.

**Comment by Phillipus** [comment]
I've made a new beta build of Archi that rolls back the code for image handling:

https://www.archimatetool.com/dev/beta

Can you test this version?

**Comment by Phillipus** [comment]
Latest beta build should fix this:

https://www.archimatetool.com/dev/beta

**Comment by yellek** [comment]
I will test when I am back in the office in a couple of hours.

**Comment by yellek** [comment]
This version has image export working as expected. Thanks for the fast response!

**Comment by Phillipus** [comment]
Thanks for the feedback. I'll get a maintenance build out soon (I want to look at some image 2x things). In the meantime, you can use the beta version. The only changes are image export fixes and one other Jasper Reports fix.

**Comment by Phillipus** [comment]
Fixed in 4.1.1
