### ISSUE TITLE
[Feature] Give us a way to integrate BPMN

### ISSUE THREAD

**Issue by PinoEire** [archimatetool/archi#327]
Hi,
We all know that Archi quite often needs to be integrated with BPMN diagrams. i appreciate that for Archi this is intrinsecally out of scope being a TOGAF  tool, but why not to look at this with an open mind? Every TOGAF design ends up having a lot of processes described in BPMN, so why can't we be practical and at least implement the ability to create BPMN views? I won't go as far as mixed views because i do see how that could be bad in so many ways, but defining a BPMN View Type to allow a process definition would be of great help! If then we could reference that as a Business Process or an Application Process it wouild be simply perfect 😄 Pretty please?
~Pino

**Comment by Phillipus** [comment]
Well... have you thought about how much work this might entail? There's only me and JB (part-time) who develop Archi (for free). I'm afraid this is not going to happen...unless someone would like to devote the next 2 years of their life to do it...unpaid. ;-)

**Comment by jbsarrodie** [comment]
Hi,

>i appreciate that for Archi this is intrinsecally out of scope being a TOGAF tool, 

Well... in short... no. Archi is not a TOGAF tool. Archi is an ArchiMate modelling tool and the only relation between TOGAF and ArchiMate is that both are standards maintained by The Open Group and both are related to Enterprise Architecture.

>Every TOGAF design ends up having a lot of processes described in BPMN

In your practice maybe, but one can use only ArchiMate (or no metamodel at all through Visio or PowerPoint...).

>but defining a BPMN View Type to allow a process definition would be of great help!

The real question is: what do you think is missing in ArchiMate to do process modelling ? I know there are some differences between both standards, but letting aside BNPM features that target process automation (through workflow tools), there aren't too many and most are not very often used.

For example, this is a BNPM diagram that I once found on internet:
![collaboration_diagram_public_process_for_cab_booking](https://user-images.githubusercontent.com/5757396/33339981-0c6a2c88-d47b-11e7-89fb-4124ced31d9f.png)

And here is a potential way of modelling it in ArchiMate in Archi:
![image](https://user-images.githubusercontent.com/5757396/33340021-2a3c1b0e-d47b-11e7-8a41-6095f87b126d.png)

**Comment by MilennialZero** [comment]
+1

--
  Jon McLeod
  Senior Consultant
  From Here On
  www.fromhereon.com
  +61 457 988 821
  jon.mcleod@fromhereon.com
 
  Jon McLeod
  Director, McLeod Consultancy Pty Ltd
  GPO Box 813 Canberra ACT 2601 Australia
  +61 457 988 821
  jmcleod@thelonius.com.au
  Silver Member The Open Group Architecture Forum



----- Original message -----

**Comment by jbsarrodie** [comment]
Just to make it clear... I don't say that ArchiMate can be used instead of BPMN for all and any cases (and same is true for UML FWIW). Both have pros and cons depending on use case.

I my (of course limited) experience, I mostly see people using only a small part of BPMN, and this small part can be done in ArchiMate as well. Archi targets those people, and those that needs really more will certainly need a true BPMN modelling tool (which as Phil said requires a huge amout of work).

Regards

**Comment by Phillipus** [comment]
Great comments from @jbsarrodie :-) My own personal perspective amounts to what/who would be required to implement this.... ;-)

**Comment by PinoEire** [comment]
Ok, so @jbsarrodie, I'm well aware that Archi can be used to some extent to describe what is normally noted in BPMN, and the "to some extent" part that makes that a very limited thing, and it's expected. 

About the workload, maybe @jbsarrodie and @Phillipus you are thinking to BPML and BPEL when i say **BPMN**? As an enterprise solutions architect I don't really care in my practice about BPML and related BPEL (those would really be a huge amount of work indeed!). What I miss is the **notation**, with some properties and documentation fields to be able to have all my deliverables in one place without bringing Visio in the mix, also becasue visio won't play along and doesn't have documentation and properties for nodes and all.

BPMN, alone, without execution language and engine, is nothing but a small collection of symbols and their connections rules. Sure is not just a one day job, but not years either 😄 If you guys are not opposed to have a BPMN View in Archi I can see at freeing some of my volunteering time starting in January and get down to get it done myself, without adding it to your plate 😉 

Regards,
Pino

**Comment by jbsarrodie** [comment]
Hi @PinoEire,

So what you descibe is in some ways in our head (and described [here](https://github.com/archimatetool/archi/wiki/Ideas-for-a-nice-and-elegant-way-to-implement-profiles-and-concepts-customization)). In short, this is what ArchiMate calls language customization. The idea is to specialize ArchiMate concepts and provide them some custom (visual) notation (shape, icon...).

For the moment, Archi (per se) doesn't allow you to do it (thus our plan to do it at some point, but that still need big amount of work and code refactoring).

Perhaps you might have a look at Herve's [specialization plugin](https://github.com/archi-contribs/specialization-plugin) (which does not really cover what ArchiMate call specialization, but at least allows you to change icons).

Regards,

JB

**Comment by PinoEire** [comment]
Hi @jbsarrodie,

Indeed that is quite close, but obviously it would be based on user costomization, while what I'd like to have in Archi is a BPMN View out of the box part of the tool, so that it's also easy to share without having to share any additional configuration or plugin. This is one of the downsides of the specialization plugin, and anyway that wouldn't really give us anything besides the nodes presentation (icon/image).

The language customization (chapter 15) also doesn't really cover BPMN simply because BPMN nodes cannot be seen as a specialization of any of Archi's nodes. That's why I believe BPMN should stand on its own, part of Archi, living in BPMN views, and maybe referenced in Application Process or Business Process nodes, so that they could be seen as such in Archi views, and (as a stretch feature) double clicking on the process node in the Archi view would even open up the referenced BPMN view. Same referencing in the generated documentation as well would be the coronation of a complete tool (IMHO).

My offer to make it happen stands if you guys like the idea 😉 

Regards,
Pino

**Comment by jbsarrodie** [comment]
>Indeed that is quite close, but obviously it would be based on user costomization, while what I'd like to have in Archi is a BPMN View out of the box part of the tool

In the mecanism described in the wiki (which is the way I see it) definition of viewpoints would:
* be done by user inside its model, meaning that you can decide to save it in a model template to have it on all your models
* drive notation

This would allow someone to just define and then create "BPMN-like" views.

>The language customization (chapter 15) also doesn't really cover BPMN simply because BPMN nodes cannot be seen as a specialization of any of Archi's nodes.

Even if I know BPMN a bit, I don't see what you call "BPMN nodes"

>and (as a stretch feature) double clicking on the process node in the Archi view would even open up the referenced BPMN view. 

FWIW you can already put references to views inside another view (and open it through double-clic). So using an ArchiMate based BPMN-like viewpoint would do it.

>That's why I believe BPMN should stand on its own, part of Archi, living in BPMN views, 

I'm still not convinced. **Could you provide a real life example (diagram) of something that you think can not be expressed using ArchiMate**.

**Comment by PinoEire** [comment]
Hi @jbsarrodie,

Sorry for the delay, December was all holiday focused 😄 Happy 2018 BTW 😸 

I never suggested that one cannot express a BPM diagram in Archi using Archi current nodes and links, but I do believe that the resulting diagram is quite a conceptual stretch and forces to mix up Events and Messages into one single node (Event), taking away BPML meaningfulness completely (see below).

Referencing the [BPMN normative](http://www.omg.org/spec/BPMN/2.0/PS) at section12, you can see what i call "BPMN nodes", an why it's impossible to emulate them using Archi nodes. For instance, if you look just at table 12.9 without getting any deeper, you see that there are 8 nodes (meaningful symbols) just for the tasks and figure 12.22 lists 58 different Events nodes (meaningful symbols). 

We cannot properly do any of that in Archi using Archi nodes, and those are **normative BPMN nodes**, not optionals. Adding to Archi a BPMN view and related normative nodes is not a big deal as it's nothing like BPML and BPEL, but will bringArchi to an unparalleled level of completeness.

**Comment by evlibra** [comment]
I would vote for the ability to export BPMN-compatible parts of Archimate models to BPMN format - the use case is data mining or simulations in tools most of which support *.bpmn

**Comment by Phillipus** [comment]
> I would vote for the ability to export BPMN-compatible parts of Archimate models to BPMN format - the use case is data mining or simulations in tools most of which support *.bpmn. The export can be view-dependent

I would say that this perhaps could be something that someone might implement in a plug-in.
