### ISSUE TITLE
[Bug] Links Area in Hi-res screen generated HTML report are not aligned with pictures

### ISSUE THREAD

**Issue by rvelter** [archimatetool/archi#328]
### Version of Archi, Operating System
Archi 4.1.1/Win64 Pro 1709

### Expected Behaviour
To Click on object for properties in Hi-res HTML report
To Click on View Object to move to another view in Hi-res HTML report

### Actual Behaviour
Links Area within Hi-res HTML report are not aligned with objects (the clikable areas are here but not at the same scale of the picture)

### Steps to Reproduce the Behaviour
1. Insert views object (or just any object) in a view. Save 
2. Export HTML with a Hi-Res screen.
3. Open the report on hi-Res screen and try to click on objects

**Comment by Phillipus** [comment]
Did this work on Archi 4.0.3?

**Comment by rvelter** [comment]
No.

I think the "workaround" for nice pictures on High-Res Report Generation broke the alignment.

**Comment by Phillipus** [comment]
OK. I'll need help to test this as I don't have a hi-res computer.

Apart from the hit areas, do the diagrams look OK?

**Comment by rvelter** [comment]
The diagrams are nice and sharp.

**Comment by rvelter** [comment]
And thank you for Archi. It's a great tool.

**Comment by Phillipus** [comment]
Thanks. I'll take a look at this issues real soon. Stay tuned...

**Comment by rvelter** [comment]
Many thanks

**Comment by Phillipus** [comment]
This feature was contributed by @aschlechter I took a look at the code, but it would be great if @aschlechter might be able to help.

**Comment by Phillipus** [comment]
@rvelter - I spent a few hours looking at this and I think I might have fixed it. Can you test it?

https://www.archimatetool.com/dev/beta

**Comment by rvelter** [comment]
@Phillipus I'll check tomorrow morning at work (i'm in France and do not have hig-res at home). Many thanks for your work. As soon as i check, i'll drop a note here.

**Comment by rvelter** [comment]
Hi, I think it works !! marvelous !

I'll use it several times to verify but it seems to work. Good job !

Many thanks.

**Comment by Phillipus** [comment]
Great. Thanks for testing. I want to tidy up the code so I'll do another test build later.

**Comment by Phillipus** [comment]
@rvelter - I've re-done the code that handles this. Would you mind testing one more time?

https://www.archimatetool.com/dev/beta

**Comment by rvelter** [comment]
Hi @Phillipus, I made a test this morning and it seems to work. :)

Many thanks.

**Comment by Phillipus** [comment]
Thanks. The fix will be in the next build of Archi. Also, there will be 2x icons for hires screens.

**Comment by Phillipus** [comment]
Fixed in 4.2
