### ISSUE TITLE
[Issue] Work Package appearance has gone rectangular

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#329]
### Version of Archi, Operating System
Archi 4.1.1 64bit on Mac (or PC). 

### Expected Behaviour
Work Package element appearance used to have rounded corners.

### Actual Behaviour
The Work Package element appears as a rectangle.

This seems to have appeared at some point since I started using the Collaboration, forms or specialisation plug-ins. I don't really want to strip them out, but downloading a fresh Archi seems to be ok again.

The other round-corner shapes seem find, as far as I can tell.

![wp](https://user-images.githubusercontent.com/18450552/33841937-fe2ad74c-de90-11e7-8a9c-e6dbf879ee9a.png)

**Comment by Phillipus** [comment]
It still has rounded corners. This must be an issue with the form plugin of Herve. Please open the issue there:

https://github.com/archi-contribs/form-plugin/issues

**Comment by Phillipus** [comment]
It still has rounded corners. This must be an issue with the form specialization of Herve. Please open the issue there:

https://github.com/archi-contribs/specialization-plugin/issues

**Comment by Phillipus** [comment]
Actually it looks like intended behaviour, but ask Herve on his project page.

**Comment by rich-biker** [comment]
Will do. However, when I downloaded a separate ‘clean' Archi I got rounded corners back (and no icon); so not sure about the intended behaviour.

Regards,
Richard.

**Comment by Phillipus** [comment]
I mean it might be what Herve intends in his plug-in - if there is an icon then use a rectangle.

**Comment by rich-biker** [comment]
I'll move to Herve's area. Thanks.
