### ISSUE TITLE
Label placement for text position 'target'

### ISSUE THREAD

**Issue by mennolodder** [archimatetool/archi#330]
### Version of Archi, Operating System
V4.1.1 Windows 10, 64 bit

### Expected Behaviour
For a horizontal relation, when selecting 'text position' = 'target' the label should be placed close to the line near the target of the relationship.

### Actual Behaviour
Label is placed quiet a bit below the line, distance from target differs based on label width.

### Steps to Reproduce the Behaviour
1. Add two application nodes. 
2. Make a flow relation between them, making the relation horizontal at the target.
3. Give the realtion a long name
4. Select 'Text Position' Target.

Example: 
![image](https://user-images.githubusercontent.com/7911897/33881363-dd4b56b0-df34-11e7-90bd-5fa3bc4f8929.png)

**Comment by jbsarrodie** [comment]
Hi,

In fact this happens only when zoom is different from 100%.

@Phillipus I guess this is because zoom is badly taken into account for either label position or the whole connexions layer. I can have a look if you want.

**Comment by Phillipus** [comment]
Yes, that would be good. It might be deep down in GEF code, though ;-) Ideally, what we need in the longer term are moveable labels anchored to the connection.

**Comment by Michael4713** [comment]
I think "moveable labels with anchors" would also solve my issue with labels (_Improvement on Label Positioning #334_)

**Comment by Phillipus** [comment]
Merged the branch into master, and deleted the branch.

**Comment by rfamans** [comment]
Making labels moveable with textwrap is more than welcome as there are important architect use cases that can't be fulfilled without controling visual aspects of relation names in views. E.g show interface names properly for a flow relation. Working with source, middle and target often results into text that breaks fluency of flow connector lines. This has major readability drawbacks.

**Comment by jbsarrodie** [comment]
This has been fixed in previous versions
