### ISSUE TITLE
Allow for translation of Jasperreports through resouce bundle properties file

### ISSUE THREAD

**Issue by cirpka** [archimatetool/archi#331]
I am looking into the ability to produce jasperreports in different languages using the same template. Having looked a little into the capabilities I understand that this is done using ResourceBundles and using the REPORT_LOCAL property. Within the archi source base I already do find an attempt to set this property, but it seems to be unfinished work. If I am not mistaken the real challenge is that the locale must be set at compile time to use the R() feature of jasper. So that would be setting the locale based on a new dialog value in the createJasperPrint routine. The other challenge I had sofar is the path of the resource file - I would like to see that file next to the .jrxml files, such that with a customized report I could add my own labels for translation. Using the default locale I have not been able to load such a localization.properties and localization_en_US.properties file in a report for which I have extended the root node using 
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports"   ..... resourceBundle="localization"> (getting the error that the bundle for the local en_US cannot be found).

**Comment by Phillipus** [comment]
The main language localisation in Archi itself is dependant on the locale setting and whether a language pack is present for the externalised strings. Therefore the Jasper report will use these strings and whatever the user provides for element names, views, etc. What strings are you referring to?

**Comment by cirpka** [comment]
Phil,

Thank you for your thoughts this fast. I should have explained myself better. All 😉 I want is to be able to have localized versions of <staticText> in the JasperReport files, for example ‘Purpose’ in main.jrxml.

Jan

**Comment by Phillipus** [comment]
> Within the archi source base I already do find an attempt to set this property, but it seems to be unfinished work. 

Where is this?

**Comment by cirpka** [comment]
https://github.com/archimatetool/archi/blob/master/com.archimatetool.jasperreports/src/com/archimatetool/jasperreports/JasperReportsExporter.java
line 228

But as said, for my scenario I need specify the locale in the dialog such that it can be set here.
Then secondly I wonder what the path for the resource bundle would be … I believe the most usable would be next to the .jrxml files – that would allow people to create their own versions based on a sample, versions that either have new translations or versions with a slightly changed layout.

Speaking of layouts … I have made a version where the background/cover image is local to the .archimate file – that allows me to have archimate files for different projects with different logo’s. I should make them available, will check how to do this one of these days.

Than you

**Comment by Phillipus** [comment]
I've figured out how to do this by specifying in code a resource bundle file that exists in the same folder as the jrxml files. The jrxml files also need to be changed to use text fields but not static texts.

So, it is possible.

**Comment by cirpka** [comment]
Great! Reading ‘specifying in code’ I conclude that this needs an update of Archi. Please advise how I can help to test and validate the solution. That the jrxml file and in particular the <staticText> node needs to change is obvious and should be no problem at all for anyone.

Jan

**Comment by Phillipus** [comment]
It's in today's beta build:

https://www.archimatetool.com/dev/beta

The file "strings.properties" is in the customisable report folder. If you create a new file with the format "strings_en_US.properties" and edit that you could try if that works. I'm not sure if it will register the locale of your setup.

**Comment by Phillipus** [comment]
Yesterday's beta build was not correct. Try today's build:

https://www.archimatetool.com/dev/beta

For this to work you must ensure that the machine's locale is set to the target locale, as the code is getting the default locale from the system.

**Comment by cirpka** [comment]
I tested todays download and it works like you described. Great and very quick service!

Ideally one can specify the locale in one of the wizard pages to support a scenario where I can use my laptop (with a default locale such as en_US) to produce a “Dutch” report (nl_NL) for one scenario and an “English” report for another scenario (stored in a different .archimate file). Toggleing the locale of my system is less elegant.

Jan

**Comment by Phillipus** [comment]
> Ideally one can specify the locale in one of the wizard pages

OK, then look on the second page of the wizard in this latest build:

https://www.archimatetool.com/dev/beta

**Comment by cirpka** [comment]
This is so cool! It works great and is exactly what I envisioned. Thank you so much!

**Comment by Phillipus** [comment]
OK, then I'll add it to the main code base...which means I have to re-do and re-generate the help documentation... ;-)

**Comment by cirpka** [comment]
Phil,

What I also did in my reports to allow for image files local to the .archimate file is the following

             <variable name="MODEL_FILE" class="java.lang.String" calculation="System">
             <initialValueExpression><![CDATA[((com.archimatetool.jasperreports.data.ArchimateModelDataSource)$P{REPORT_DATA_SOURCE}).getModel().getFile().getAbsolutePath()]]></initialValueExpression>
             </variable>
             <variable name="MODEL_DIRECTORY" class="java.lang.String" calculation="System">
             <initialValueExpression><![CDATA[((com.archimatetool.jasperreports.data.ArchimateModelDataSource)$P{REPORT_DATA_SOURCE}).getModel().getFile().getParent()]]></initialValueExpression>
             </variable>

In the main.jrxml file. That is basically as I could not find (in the old version) variables that point to the directory of the .archimate file. In particular the MODEL_DIRECTORY variable is of importance (to me), as this allows for

             <variable name="MODEL_COVER_BACKGROUND_FILE" class="java.lang.String" resetType="Page" calculation="System">
             <variableExpression><![CDATA[$V{MODEL_COVER_BACKGROUND} != "" ? $V{MODEL_DIRECTORY}+"\\"+$V{MODEL_COVER_BACKGROUND} : ($V{MODEL_COVER_IMAGE} != "" ? "" : $P{REPORT_PATH}+"default.png")]]></variableExpression>
             <initialValueExpression><![CDATA[$V{MODEL_COVER_BACKGROUND} != "" ? $V{MODEL_DIRECTORY}+"\\"+$V{MODEL_COVER_BACKGROUND} : ($V{MODEL_COVER_IMAGE} != "" ? "" : $P{REPORT_PATH}+"default.png")]]></initialValueExpression>
             </variable>


As you see, a codebase change is not necessary, but together with the localization, I now can make specific configurations with their own localization and their own backgrounds.

Jan

**Comment by Phillipus** [comment]
Thanks for sharing that. But are you querying the locale in the report? The code loads the resource bundle according to the chosen local but I have not set JRParameter.REPORT_LOCALE to it.

**Comment by cirpka** [comment]
Phil,

No, I do not do anything with the locale in the .jrxml file. The business case is the following scenario’s that I as architect want to handle from one and the same PC.


  1.  Model for a specific project that is targeted at a Dutch speaking department
  2.  Overview model for the programme that is targeted at the CIO level  in English speaking

The models have no overlap, so that the descriptive text (and naming of the nodes) is in model 1 Dutch and in model 2 English

For both models I want to create specific backgrounds and headers, so that they feel ‘specific’ to the audience. That I already could realize with the code snippets I sent, allowing me to store image files next to the .archimate file and reference it by a name. Storing it, like the original code, in the plugin/…/reports/<report layout>/ directory is not very handsome, in particular as this directory, once installed with the regular installer, under the Program Files directory requires administrative privileges for modification (such as adding a file).

The second challenge, the localization reusing the <report layout>, is now also addressed.

My snippet was mainly sent to complete the scenario (as described above). Eventually you want to include paramters like MODEL_DIRECTORY with the invocation of the main.jrxml file, even though my trick having gone through the source, does work. Alternatively you may consider to update the sample main.jrmxl file to show people how they can achieve results like I did.

Once more, thank you very much and my apologies for any misunderstanding!

Jan

**Comment by jbsarrodie** [comment]
>Storing it, like the original code, in the plugin/…/reports/<report layout>/ directory is not very handsome

Don't know if you've noticed: You don't have to: you can use whatever directory you want to store your custom reports (Preferences > Jasper Report).

**Comment by Phillipus** [comment]
> Don't know if you've noticed: You don't have to: you can use whatever directory you want to store your custom reports (Preferences > Jasper Report).

And the "Custom..." option allows you to choose any custom report.

![image](https://user-images.githubusercontent.com/600504/34176373-9a5ef3c0-e4f7-11e7-9798-9aea443eb73d.png)

**Comment by cirpka** [comment]
I did not know this. Thanks for pointing this out. Honestly I still prefer my approach for the images – simply as I think that in my scenario the image belongs more to the project (thus the .archimate file) than to the report layout. But again, I already can achieve this today – the localization was the missing piece now resolved.

Jan

**Comment by cirpka** [comment]
Yes, I know (and use this). I have created my own layouts (with for example the lookup of the image in the same directory as the .archimate file).

**Comment by Phillipus** [comment]
Fixed in 4.2
