### ISSUE TITLE
model graphic does not display

### ISSUE THREAD

**Issue by GPringle** [archimatetool/archi#335]
### Version of Archi, Operating System

4.0.3

### Expected Behaviour

When I open my model the graphical model should display to the right of the tree

### Actual Behaviour

The window where the graphical model should be is blank

I am a very new user.  Can someone tell me what I am doing incorrectly?  Thanks

**Comment by Phillipus** [comment]
Please describe in detail the steps you are taking.

Have you created a new View?
Have you double-clicked on the View?
Have you read the User Manual?

**Comment by GPringle** [comment]
Hello. Thanks for your response. 

I created a new model, saved it, printed the model and then shutdown Archi. 

When I launched Archi again it opened at my model. The Tree window is displayed. I am using the default view.

My problem is that the graphical model does not show in the window to the right of the Tree. Also no Outline is available and no palette is available. 

I did not create a view or double click on it. 

I have been reading the user guide as I went about creating the model. I have not read the guide completely but searching it I have not discovered anything that gets me past the issue?

Any guidance that you can provide will be greatly appreciated!

Cheers 

Gord

from iPhone

**Comment by Phillipus** [comment]
You should see Views in the Tree under the "Views" node. If there is one there double-click it to open it.

**Comment by GPringle** [comment]
Hi Phil. Thank you for this. I must have clicked on that icon a few times but obviously had not double-clicked the View name.  The view is now open and the model is displayed. Not sure how I managed to close it!

Thanks again. 

Best regards and best wishes for a Merry Christmas!

Gord

from iPhone

**Comment by Phillipus** [comment]
No worries. 

Views are created in the model tree and you open them by double-clicking them (you can create more than one). Archi will remember which are open next time.

Merry Christmas to you too.

Closing this one...
