### ISSUE TITLE
[Feature Request] Relation source and target listed in Properties tab

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#336]
I propose to list the source and target elements in the Properties tab of the Relation.
The aim is to make it clear when navigating across the relations and elements.

One option is to list it in the Analysis sub-tab.

However it would be better for the first sight to have it listed in the heading of the Properties tab.

Example: -> (my relations label) (Serving relation) (Source element with long name -> Target element with long name)

**Comment by Phillipus** [comment]
Will be in Archi 4.8 EA2
