### ISSUE TITLE
[feature proposal] Add option to render documentation items as Markdown in JasperReport wizard

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#34]
In order to make reports feature more powerfull, it should be possible to add an option on the report wizard (disabled by default) to render documentation items using a Markdown to HTML preprocessor. This would then enable the report to render the HTML (that's an option in jasperreport) and thus create better looking documents.

Adding markdown support should be easy as several (but not tested) Java libs [exists](http://www.w3.org/community/markdown/wiki/MarkdownImplementations).

Of course, seen from Archi, documentation items would remain text only and users will see the Markdown "source", but this should not be a bit deal as it was created to be human readable.

**Comment by Phillipus** [comment]
Moved to https://github.com/archimatetool/archi/issues/1032
