### ISSUE TITLE
(Feature) One click cleanup of unused objects and connections

### ISSUE THREAD

**Issue by chriskl** [archimatetool/archi#342]
A one click (with confirmation) cleanup function that went through and remove all unused objects and relationships from the model would be great.

**Comment by MilennialZero** [comment]
Or: create a list of unused objects and connections in each open model (the user may have more than one model open), with selection boxes for each object / connection, and a "select all" option to delete. 
This would be useful. +1. 

--
Jon McLeod

----- Original message -----

**Comment by Phillipus** [comment]
The Validator shows a list of unused concepts. One can select them all, choose "Reveal Object" which selects them on the Model Tree, and then press Delete.

![screen shot 2018-01-30 at 08 11 30](https://user-images.githubusercontent.com/600504/35554953-6f08b68e-0595-11e8-8972-d3976e5171f6.png)

**Comment by chriskl** [comment]
That's a great solution.  I'll close the issue.

**Comment by csilk** [comment]
This does't work on MAC. Pressing delete does nothing as the objects are only highlighted in grey rather than selected (they will be blue when selected).

Workaround: when the unused objects are highlighted in grey, click one of the objects while holding CMD, this will turn all of the highlights from grey to blue. The object that you click will be unselected, reselect by keeping the CMD button pressed in and left clicking the object to reselect. The goal is to turn all of the highlighted objects (grey) into selected objects (blue).

**Comment by Phillipus** [comment]
> This does't work on MAC. Pressing delete does nothing as the objects are only highlighted in grey rather than selected (they will be blue when selected).
> 
> Workaround: when the unused objects are highlighted in grey, click one of the objects while holding CMD, this will turn all of the highlights from grey to blue. The object that you click will be unselected, reselect by keeping the CMD button pressed in and left clicking the object to reselect. The goal is to turn all of the highlighted objects (grey) into selected objects (blue).

Same thing on Windows. The Validator retains the focus, which is the intended behaviour as it's only revealing and selecting the objects. Simply click on the Models Tree tab so that it gains the focus.

**Comment by csilk** [comment]
If clicking on the tab moves the focus to the highlighted objects then your workaround removes a step from mine. Thanks.

**Comment by Phillipus** [comment]
Actually, I think someone has created a [jArchi](https://www.archimatetool.com/plugins/#jArchi) script to do what the OP wants. I'm feeling too lazy to find it right now, but it's out there.

**Comment by lapshinkirill** [comment]
> > This does't work on MAC. Pressing delete does nothing as the objects are only highlighted in grey rather than selected (they will be blue when selected).
> > Workaround: when the unused objects are highlighted in grey, click one of the objects while holding CMD, this will turn all of the highlights from grey to blue. The object that you click will be unselected, reselect by keeping the CMD button pressed in and left clicking the object to reselect. The goal is to turn all of the highlighted objects (grey) into selected objects (blue).
> 
> Same thing on Windows. The Validator retains the focus, which is the intended behaviour as it's only revealing and selecting the objects in the Models Tree which doesn't have the focus at this point. Simply click on the Models Tree tab so that it gains the focus.

When you have clicked on "Reveal objects" keep the Ctrl button pressed and right click on any selected object. This will keep the selected object from losing focus on the list of unused objects. Next, click "delete" in the menu that appears
