### ISSUE TITLE
Hyperlinks not rendered properly in HTML preview or Report. 

### ISSUE THREAD

**Issue by GeoffMurray** [archimatetool/archi#343]
Bug, but does not seem to have log messages associated. 

### Version of Archi, Operating System
Archi V4.1.1, Windows 10

### Expected Behaviour
When I insert a Hyperlink in the documentation section, I should be able to click on it, either in Archi, or when I export to an HTML report (or preview).

### Actual Behaviour

A link like the following:

http://migsvmqms01/mc/main/index.cfm?event=showFile&ID=M5LTXYIVN5CEZEORGD

Gets converted in the HTML preview or the HTML report to:

http://migsvmqms01/mc/main/index.cfm?event=showFile&AMP;ID=M5LTXYIVN5CEZEORGD

Which renders the link unusable.

### Steps to Reproduce the Behaviour
1. Insert a hyperlink with an & in it.
2.Try it.

Please let me know if any other details I can provide.

**Comment by Phillipus** [comment]
Thanks for opening an issue. A "&" will render as a hyperlink if the URL is well formed. For example:

https://www.archimatetool.com/plugins?event=showFile&ID=M5LTXYIVN5CEZEORGD

Is your example based on a real URL? there is no ".xxx" part after the "migsvmqms01" part.

**Comment by GeoffMurray** [comment]
Thank you so much for the quick response.

We have a DNS entry that translates that to the full domain name and system name. Once I replaced it with the full DNS name, everything worked. 

Closed with much thanks.

**Comment by GeoffMurray** [comment]
Sorry - I spoke to soon. 

Once I updated the URL server name to provide more accurate DNS name, now what happens is the ctrl-click from the Archi window works, but the HTML export still does the &AMP; replacment, rendering the URL useless.

**Comment by Phillipus** [comment]
The HTML export is probably a separate issue. Will investigate.

**Comment by Phillipus** [comment]
Fixed. Will be in next release
