### ISSUE TITLE
undo in Documentation-field does not work

### ISSUE THREAD

**Issue by pdussart** [archimatetool/archi#345]
### Version of Archi, Operating System
I'm on Archi 4.2 macOS High Sierra 10.13.3

### Expected Behaviour

Type, cut, delete... some text in the Properties -> Main -> Documentation field. 

Press command-Z or click Edit->Undo Change Doc

action should be reversed

### Actual Behaviour

Action is not reversed.

Does work in other fields I've tested like Main -> Name

(nothing added to the error log)

### Steps to Reproduce the Behaviour
1. Type, cut, delete... some text in the Properties -> Main -> Documentation field. 
2. Press command-Z or click Edit->Undo Change Doc
3. action in step 1 is not reversed

**Comment by Phillipus** [comment]
The text in a multi-line text field is not completed until the text field loses the focus. So, if you select another field or part of the app after typing text then the Undo action will register.

**Comment by pdussart** [comment]
Indeed.. Not perfect, but once you know this it's OK. So strange that I haven't noticed this before.

**Comment by Phillipus** [comment]
The reason is to avoid too many Undo actions when typing text.
