### ISSUE TITLE
Feature request: sortable datasources for Jasper Reports

### ISSUE THREAD

**Issue by cirpka** [archimatetool/archi#346]
I would like to be able to sort for example the motivations by type. The idea is that in some scenario's a group by type (e.g. stakeholder, assessment) would make the report more readable. Having taken a look into the source code I believe that this requires to extend the JRRewindableDataSource that is implemented in for example the PropertiesModelDataSource. Assuming that there is a method SortBy("column") the invocation of the elements.jrxml than would be something like

````
<dataSourceExpression>
<![CDATA[((com.archimatetool.jasperreports.data.ArchimateModelDataSource)$P{REPORT_DATA_SOURCE}).getElementsDataSource("motivation").SortBy("type")]</dataSourceExpression>
````

Similar one could think about filtering, but that can already be achieved by using `<printWhenExpression>` within the .jrxml files. 

Note: updated by jbsarrodie to make tags visible ;-)

**Comment by Phillipus** [comment]
We now have sorting in the Jasper API
