### ISSUE TITLE
Model views and the x,y coordinates of items in a view

### ISSUE THREAD

**Issue by GeoffMurray** [archimatetool/archi#347]
I'm trying to use a model stored through the database plugin, and re-create a view with an image, followed by the appropriate hotspots to link down to. Ie, I'm not using the supplied HTML report capability directly.

I found an interesting problem, and described it more thoroughly in this post: https://github.com/archi-contribs/database-plugin/issues/30#issuecomment-365719413

When I export the model using the database plugin, I get the tables of views, and objects in the views, including the location information about objects on the view. 

When I export the model using the Jasper HTML plug in, that information gets converted to HTML, and images get created, as well as the image map locations for the objects on the HTML view. However, the locations in the HTML view are offset from the ones in the database.

The images that get exported also seem to be cropped in some way, so that the view objects don't show up in the same map location as when I look at it through Archi. It's like some image whitespace gets cropped (left and top maybe?) when the image screenshot is created. 

What's interesting is that the HTML Jasper report seems to be able to adjust for that shift, but the database details do not. 

So, after a very long winded explanation, is there some other offset information associated with a view that can be exported to the database information, to allow the object mapping to be created correctly?

It seems like the database plugin exports all the information it can find, so then my question is, what does the Jasper report do differently to allow the image map for the objects to be created correctly.

**Comment by Phillipus** [comment]
When an image is created and exported to a .png file it has a 10 pixel border. Is that what you mean?

**Comment by Phillipus** [comment]
BTW - this type of discussion, being neither a bug or feature request is more suited to the Archi forum - http://forum.archimatetool.com/ - please continue there.

**Comment by GeoffMurray** [comment]
Will do. Apologies for the wrong place.

**Comment by Phillipus** [comment]
No probs.
