### ISSUE TITLE
Import CSV Data into model does not work as expected when using Arabic characters

### ISSUE THREAD

**Issue by MalekG** [archimatetool/archi#348]
Hello,

I was trying to import a model from CSV files and I succeeded into importing the model by creating the files in the supported format.

the import does not generate any errors but the text in Arabic is converted to special character such as "���� ������" it appears that Archi does not recognize the Arabic characters yet :(

### Version of Archi, Operating System
I use Archi Version 4.2.0 Build 201801300957 on Windows 10 Version 1709 X64.

### Expected Behaviour
names of the imported artifices appear as
"نظام محاسبة"

### Actual Behaviour
names of the imported artifices appear as
"���� ������"
### Steps to Reproduce the Behaviour
1.Create the CVS files: elements.csv, properties.csv,relations.csv 
2. elements.csv conteents:

> "ID","Type","Name","Documentation"

"71242B0E-3C21-3C39-5E5E-64937757D085","ApplicationService","نظام محاسبة",""

3.Go to File > Import > CSV Data into model
4. select the elements.csv.
5. click open.

[elements.zip](https://github.com/archimatetool/archi/files/1755343/elements.zip)

**Comment by Phillipus** [comment]
Thanks for the report.

- I created a new model with an Application Service called نظام محاسبة
- I exported to CSV using the UTF-8 encoding
- I created a new empty model
- I imported the CSV file(s) and it was OK

How are you creating the CSV file? Is it created as UTF-8?

**Comment by MalekG** [comment]
Thanks for the hint 👍 
I created the CSV file by exporting it from MS Access 2016.
I opened the CSV with Notepad and saved it using the encoding UTF-8 as you hinted instead of ANSI and it worked.
Thanks :)
