### ISSUE TITLE
[Feature Request] Show the list of all Views containing a given object

### ISSUE THREAD

**Issue by viraghtamasjozsef** [archimatetool/archi#349]
Relationships between objects listed in model tree and views can be really complex because of the large number of views and also large number of objects used in views. So it is not easy to understand that relationships and make modifications as they needed. 
(1) There is a great feature "Select in Model Tree" - this can be used to navigate from a view to the items in the model tree.
(2) This feature request suggest a similar useful service: right-click on an item in the model tree it would be useful to have a new item in the pop-up menu: "Related Views" to see the list of all views containing that special object.
Thanks, Tamas

**Comment by Phillipus** [comment]
This feature already exists in the Properties window, called "Analysis"

**Comment by viraghtamasjozsef** [comment]
Thank you Phillipus!
