### ISSUE TITLE
Icons (Models, Validator, Properties) do not appear on the sidebar.

### ISSUE THREAD

**Issue by mdvadim** [archimatetool/archi#351]
### Version of Archi, Operating System
Archi 4.2, Win7 

### Expected Behaviour
Icons (Models, Validator, Properties) appear on the sidebar. 

### Actual Behaviour
Icons (Models, Validator, Properties) replaced with red square on it's sidebar. Just hide/show by Alt+1, Alt+2, Alt+8 can reload correct image.

### Steps to Reproduce the Behaviour
1. Just start Archi 4.2
2. 
3.
![default](https://user-images.githubusercontent.com/29094130/37074015-048722c6-21fd-11e8-8df7-c36264cf641b.png)
![default](https://user-images.githubusercontent.com/29094130/37074092-7f297132-21fd-11e8-895b-5436c9720578.png)

**Comment by Phillipus** [comment]
No idea why this is happening. Try "Window -> Reset Window Layout", if that doesn't work try "Help -> Reset to Defaults" and restart.

**Comment by Phillipus** [comment]
Can't be bothered to reply? Closed.

**Comment by mdvadim** [comment]
Oh, @Phillipus, I'm so sorry! I did not think you were expecting my answer...
After the complaint Archi began to work without problems, and I could not apply your advice.

**Comment by Phillipus** [comment]
@mdvadim No problem. (My last message didn't sound right so I deleted it ;-))
