### ISSUE TITLE
[Feature Request] Support for multi language models - basic solution

### ISSUE THREAD

**Issue by viraghtamasjozsef** [archimatetool/archi#352]
We have to present Archi models in different human languages. Today that needs lot of manual work.
As a first step now we use 2 custom properties: **English Name** and **Hungarian Name** for each and every ArchiMate **Object**, **View** and **Folder**. We store the name of that component in different languages there. 
It would be great to have a menu item in Archi:
- select one of the custom properties as source
- copy the content of that custom property to the Name attribute for each object, each View and each Folder in the current model. (Only if such property exists and is not empty for a given object/View/Folder.)

Now this can be achieved by CSV export, processing in Excel (Copy names) and then CSV import. But this method is too complex, it would be great to have a menu item for that in Archi.

**Comment by herve91** [comment]
Hi,

There are several ways to achieve your goal, depending on the final result you are expecting.

first of all, you need to create a new "**language**" property at the model level. It will contain "**English**" or "**Hungarian**" depending of the language your wish to show.

First solution, you may use the [form plugin](https://github.com/archi-contribs/form-plugin) to create arrays containing all your objects with a text column with these parameters:
- "variable" : "${name}"
- "default" : "${property:${model:property:language} Name}"
- "forceDefault" : true
Running the form would then replace the name of the objects with the "English Name" or "Hungarian Name" property value.

Second solution, easier to implement, is using the [specialization plugin](https://github.com/archi-contribs/specialization-plugin) :
- create a "**label**" property for all your objects with "${property:${model:property:language} Name}"
This plugin will not replace the objects names, just change the label displayed.
Please note that when you change the value of the "language" property, you may close and re-open the views to see the changes.

Hope this helps.
Hervé

**Comment by viraghtamasjozsef** [comment]
Hi Hervé,

thank you very much your answer. I used specialization plugin and works well! 
You saved me lot of time! Now it is easy to provide views in different languages for different stakeholders.

Just one comment: it would be even better if there will be a similar solution to change in such an easy way not only the labels on objects but also names of Views and names of folders in the model.

Thanks again,
Tamas

**Comment by herve91** [comment]
Hi Tamas,

I will check the feasibility of changing the label for views and folders and add it to my todo list.

Thanks for letting me know my plugin solved your problem. You may close this thread.

Best regards
Hervé

**Comment by Phillipus** [comment]
Closing this as Archi 4.7 supports label expressions that can be used in a similar way to how Herve describes above.
