### ISSUE TITLE
Feature Request - Transparent Fill option for Groups & Visual Groups

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#353]
I'm using Archi to model a scenario where certain elements are subject to multiple policy domains (modelled as Groups).
The ArchiMate 3.0.1 specification (p17) acknowledges that groups may "_may be aggregated by multiple (overlapping) groups_" but visually, because Archi draws renders these elements with an opaque fill, it's not possible to show the intersect.

May I propose an option to set the transparency of group element fill colours to the wish-list for some future version?
Cheers  :)

**Comment by MilennialZero** [comment]
Hi lavenderb

Not sure what you mean - a graphic example of something you can do in
another tool would be helpful.
We often need to show a single concept that that has multiple
attributes, contexts, or associations. This can be challenging from a
graphical perspective. The trick is to not make the resulting graphic so
complicated that it is confusing.
In the absence of that - is the example below what you mean
(graphically)?
Here, the attributes are the small boxes within the capability - showing
the capability maturity of "people", "process", "information", and
"technology" for a given business capability. 
Jon

----- Original message -----

**Comment by lavenderb** [comment]
Thanks Jon,

 

A simple version of my scenario would be Call Record Data that is collected by Telco providers.
It’s subject to 2 Regulations (Data Retention Directive – i.e. retention of call logs for 2 yrs for law enforcement & GDPR (privacy)) + numerous internal policies on classification, back-up & recovery, sanitisation for test purposes etc.

I want to model these policy domains as groups.

I can show that the CDRs are subject to multiple domains by aggregation- so:


 

… but it’s nice to depict domains as nesting the elements in their scope.

Overlapped domains in Archi looks like this:



 

But the opaque fill obscures that I’m trying to show that the CDR is meant to be in both domains.
I’m asking for a capability to show this as transparent fill, like the following (created in Visio):




Rgds

**Comment by jbsarrodie** [comment]
Hi Guys. None of your images are visible. Can you update them on GitHub please?

**Comment by jbsarrodie** [comment]
>The ArchiMate 3.0.1 specification (p17) acknowledges that groups may "may be aggregated by multiple (overlapping) groups" but visually, because Archi draws renders these elements with an opaque fill, it's not possible to show the intersect.

The standard does not suggest that this overlap should be visual. Adding transparency would not help you a lot as both Groupings should contain (aggregate) common elements, making them appear twice.

**Comment by Phillipus** [comment]
BTW - opacity of fill in objects has been requested before (see #247 for example). I've almost implemented this.

**Comment by Phillipus** [comment]
Implementing opacity for figures should allow this, and also work for #247 by setting opacity to 0.

![opacity](https://user-images.githubusercontent.com/600504/37594961-d2ebe6e0-2b6e-11e8-8d3e-4400ab981dd3.png)

**Comment by jbsarrodie** [comment]
@Phillipus very interesting! I have some use cases for that if we make sure that the format painter take care of it...

**Comment by Phillipus** [comment]
@jbsarrodie Of course the format painter takes care of it ;-) See https://github.com/archimatetool/archi/commits/figure_opacity

**Comment by Phillipus** [comment]
Implemented in next version

**Comment by lavenderb** [comment]
Thanks - looks great :-)
