### ISSUE TITLE
[Feature request] Object merge

### ISSUE THREAD

**Issue by stigbd** [archimatetool/archi#354]
Apologies to @chriskl for duplicating part of his feature request (#340), but I think a subset of his request might be a standalone feature:

In order to prevent duplicate objects in a model, I would like to merge two objects of the same type into one.

An object 'merge' function. Select 2 (or more) objects of the same type in the Model browser and merge them into one, all views are updated. The resulting set of relations should be a union of the original ones.

I belive that @chriskl's 3rd proposal ("Find objects with identical names") is already supported in the validator ("Possible duplicate" warning).

**Comment by robkamp** [comment]
I would like to add a warning when entering the same name for the same object type and get a dialog/question if I want to use the already existing object or not. , but maybe that requires a different [feature request].

**Comment by jbsarrodie** [comment]
Hi,

@stigbd : This will be made possible through the new Scripting plugin and we'll probably include an example for this use-case.

@robkamp Yes, this requires a different feature request (don't remember if there's already one for this). This is more intrusive (can't be adressed through a simple script) and in a perfect world we could even imagine using autocompletion to help user see if concepts with similar names exist, and if yes, selecting one of them would trigger a dialog to choose between creating a new concept with same name or referencing existing concept.

**Comment by Phillipus** [comment]
Can do this now in jArchi.
