### ISSUE TITLE
[Bug] Changing Fill color of multiple objects not working as expected

### ISSUE THREAD

**Issue by ElvinD** [archimatetool/archi#355]
### Version of Archi, Operating System
Version 4.2.0, Mac OS High Sierra (10.13.3)

### Expected Behaviour
Changing the Fill color of more than one object at the same time should change the fill color of those objects selected.

### Actual Behaviour
Only the first object has its fill color changed

### Steps to Reproduce the Behaviour
1. Select more than one object
2. Select Appearance in the properties window
3. Change the Fill colour
<img width="1087" alt="schermafbeelding 2018-03-22 om 14 18 42" src="https://user-images.githubusercontent.com/7555096/37772780-fdaa9736-2ddb-11e8-8382-9ec81c66d962.png">

**Comment by Phillipus** [comment]
If you choose the fill colour from the Edit menu you can change multiple instances.

**Comment by ElvinD** [comment]
Which I just did.

**Comment by Phillipus** [comment]
>That indeed works, thanks for the great tip. I guess the Properties tab is always meant for just a single instance, and as such you could close this bug report.

Yep. The Properties window logic could be re-written to handle multiple selections, but it would take a bit of work to do that (hide features not relevant to objects in selection, etc.)

**Comment by Phillipus** [comment]
In fact, I've taken another look at this and, as a result, I'm now re-working the whole Archi Properties Window framework to allow for multiple selections. So re-opening this...so I can close it again when I've implemented it...

**Comment by ElvinD** [comment]
I like your way of working, good luck with the rework and thanks for this amazing product!

**Comment by Phillipus** [comment]
Closing this so I can track it in #358
