### ISSUE TITLE
[feature] dubblecheck a palette item to make it 'sticky'

### ISSUE THREAD

**Issue by janwilmans** [archimatetool/archi#363]
When adding lots of components or relationships it would be helpful if you could make the current palette item 'stick'.  

Currently, to add 3 relationships:
- click magic connector
- click component A, click component B, click relationship type
- click magic connector
- click component A, click component B, click relationship type
- click magic connector
- click component A, click component B, click relationship type

New proposed behaviour:

- dubble-click magic connector
- click component A, click component B, click relationship type
- click component A, click component B, click relationship type
- click component A, click component B, click relationship type
- click select on palette to stop using magic connector

The behavior can be tested or observed in other tools, such as 'staruml', it makes 'sketching' faster/ easier and less straining for the mouse-wrist.

**Comment by Phillipus** [comment]
You can make it stick by holding the Shift key when clicking on the palette.

**Comment by theunsfvo** [comment]
This will be VERY useful!

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*
*    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>*

**Comment by janwilmans** [comment]
Wow!

**Comment by Phillipus** [comment]
From the manual:

![image 1](https://user-images.githubusercontent.com/600504/38022291-030a6af4-3277-11e8-927f-ad6adcf40323.png)

**Comment by Phillipus** [comment]
Closing...

**Comment by theunsfvo** [comment]
I did NOT know that, thanks Phil!

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*
*    My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>*
