### ISSUE TITLE
[Feature Request] Integrate Mylyn to Archi

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#367]
I would like to see Mylyn task management integrated to Archi. http://www.eclipse.org/mylyn/

What is the best approach to achieve such integration?

**Comment by Phillipus** [comment]
It's not possible because Archi is an RCP application that uses some of the features of Eclipse. Mylyn needs total integration of the Eclipse workbench. In other words, even though Archi uses some Eclipse-based frameworks it is not an Eclipse plug-in.
