### ISSUE TITLE
Assign color heat map to element fill or relationship line color using object property value

### ISSUE THREAD

**Issue by peterprib** [archimatetool/archi#369]
Allow automation of colors based on property so diagram can highlight change or impact by color.  For example object property version could be compared to diagram property version and based on <,=,> it has a different intensity of base color.

May apply to say property cost. 

Could add a property to diagram to say which heatmap is being applied so one could toggle thru.  If projected as menu option even better still.   In essence an extension on viewport being tailored viewport

**Comment by herve91** [comment]
Hi Peter,

I'll think about this ... but it won't be for now as I'm preparing quite a big update on my database plugin and it takes me all my time at the moment.

Best regards
Hervé

**Comment by ubibene** [comment]
Hi
You could do it with a jarhi script like this one : https://gist.github.com/ubibene/60629a4df719520a96466887dbf08226

**Comment by Phillipus** [comment]
> Hi
> You could do it with a jarchi script like this one : https://gist.github.com/ubibene/60629a4df719520a96466887dbf08226

Closing
