### ISSUE TITLE
[Enhancement] Allow circular "connection to notes"

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#371]
Hi,

I've just noticed that we can create circular connections anywhere but on connections to notes (and visual groups) in ArchiMate views. If allowed, this would make such things possible:
![image](https://user-images.githubusercontent.com/5757396/39430062-069aa4e2-4c8d-11e8-8b54-47d51f4b85a4.png)

**Comment by Phillipus** [comment]
Will be in 4.3
