### ISSUE TITLE
Java Vulnerabilities

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#375]
The JVM supporting the current Archi download (v4.2 Windows 64bit) is being flagged by our vulnerability scanner. Details as follows:

Java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot (TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
<table>
<tr>
<th> Scan Target </th><th>Vector </th><th>Suspect File </th><th>Version</th><th>Vulnerable?</th>
</tr><tr>
 <td>jre</td><td>Java</td><td>C:\temp\Archi4\jre\bin\java.dll</td><td> 8.0.1440.1</td><td>Yes</td> 
</tr><tr>
 <td>jre</td><td>Java</td><td>C:\temp\Archi4\jre\bin\java.exe</td><td> 8.0.1440.1</td><td>Yes</td>       
</tr><tr>
 <td>jre</td><td>Java</td><td>C:\temp\Archi4\jre\bin\javacpl.exe</td><td> 11.144.2.01</td><td>Yes</td>
</tr><tr>
 <td>jre</td><td>Java</td><td> C:\temp\Archi4\jre\bin\javaw.exe</td><td> 8.0.1440.1</td><td>Yes</td>  
</tr><tr>
 <td>jre</td><td>Java</td><td>C:\temp\Archi4\jre\bin\javaws.exe</td><td> 11.144.2.01</td><td>Yes</td>
</tr>
</table>

### Expected Behaviour
Ideally, a clean report. The Application Security team here will complain until it's fixed.
Does it require a product update or can you recommend some other action </br> - such as upgrading to a later jre?

**Comment by Phillipus** [comment]
What is the problem flagged by the scanner?

**Comment by lavenderb** [comment]
The team that perform the scanning don't have anyspecifics - they are just given a list of approved security patched versions and flag anything that is more than 2 releases behind.
I did a bit of research on the CVE database and wonder whether it is this one that is triggering it (https://www.tenable.com/plugins/nnm/8898). Multiple unspecified vulnerabilities effecting confidentiality, integrity & availability - advised to upgrade to Java 1.8.0_26 or later.

**Comment by Phillipus** [comment]
You can either delete the "jre" folder in Archi's installation and Archi will use the system's Java if one is installed, or replace the "jre" folder with a more recent version.

The next version of Archi will ship with Java version 1.8.0_171

**Comment by lavenderb** [comment]
To keep the packaging process simple, it's better to wait for the next release.
They'll accept that if I can give them a reasonable date.
When is the next version expected?

**Comment by Phillipus** [comment]
I can't say when the next release of Archi is, if at all. All work on Archi is voluntary (and unpaid) and so depends on many factors.

**Comment by lavenderb** [comment]
I understand.
My aim in installing Archi at work is to set up a user community.
Once that's established & proven useful, I'll try and get some sponsorship for you :-)

**Comment by Phillipus** [comment]
Well, I'm always open to sponsorship. :-)

**Comment by Phillipus** [comment]
Next version of Archi will include Java 1.8.0_181. Closing this

**Comment by lavenderb** [comment]
Thanks Phil 👍
