### ISSUE TITLE
[Feature Request] Flow Relation text manipulation

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#380]
Can we change the flow relation text (and any relation text for that matter) like the Note element to form the shape of text?

It will allow for better looking models instead op LONG relation name strings it can be multi-line like Note text...

System Context diagram views would be much easier to do this way as well as any other view that has relation descriptions because at the moment I leave them blank and add notes just so that I can format the text look better, which is duplicated work since the name and description is already captured in the relation properties box.

**Comment by herve91** [comment]
Hi,

You may have a look on the [specialization plugin](https://github.com/archi-contribs/specialization-plugin)

It allows you to un-correlate the text in views from the name.

The labels of your objects and connections can then include newlines ("\n") or properties like ${name}, ${description} or ${property:prop_name} ...

Hope this helps

**Comment by theunsfvo** [comment]
Thanks a million, will have a look to see if it does what I need.

Thanks,
Theuns

**Comment by theunsfvo** [comment]
tried it but Archi says it is not a valid plugin zip when i try to add it
via the menu 'Help/Install Archi Plug-in'

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*

**Comment by herve91** [comment]
You need to copy the jar file directly in the Archi's plugins folder.

**Comment by theunsfvo** [comment]
I did, no luck...

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*

**Comment by herve91** [comment]
Usually, this happens when the jar file has not been downloaded correctly. Please compare the file size on your disk and the one on Github.

Should you require more assistance, could you please open a case on my [plugin's site](https://github.com/archi-contribs/specialization-plugin/issues) as this is not related to Archi but to my plugin.

Best regards
Hervé

**Comment by theunsfvo** [comment]
i'll have a look, tnx Hervè ;)

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*

**Comment by Phillipus** [comment]
Close this since we have label expressions now.
