### ISSUE TITLE
[Feature Request] keyboard shortcuts for all menu options

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#381]
If we can't have custom keyboard shortcuts, can we at least have keyboard shortcuts for all the menu and pop-up commands?

Would save a LOT of time, especially on elemt alignment and layer ordering.

**Comment by isalew** [comment]
A key to activate the magic relationship connector would be fantastic.

**Comment by Phillipus** [comment]
I don't think that keybindings were ever implemented for Eclipse GEF - See the proposal here https://www.eclipse.org/gef/plan/gef_plan_3_2.html - something not implemented.

Having said that, as Archi is open source someone might research a possible implementation or workaround and contribute it.

**Comment by Phillipus** [comment]
Custom key bindings will be in Archi 5. However, key bindings for the palette are not possible.
