### ISSUE TITLE
[Feature Request] Automatic grouping option

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#382]
This would help a lot...

Scenario: created a bunch of elements and later realize some of them have a logical grouping... so instead of creating a group element seperately and selecting the elements manually and then moving them onto the group to create a composition relation, why not allow the elements to be selected (mouse drag or ctrl + click) and right click to 'create group'

Same goes for creating a parent element that you want to assign child elements to after the children were created...

**Comment by K4yl** [comment]
**Push**

Yes, I agree. This would be a very beneficial feature.

**Comment by Phillipus** [comment]
Feel free to submit an implementation. This is an open source project.

**Comment by K4yl** [comment]
@Phillipus Thank you for your offer. I might missing the technical capabilities :)

**Comment by Phillipus** [comment]
> Feel free to submit an implementation. This is an open source project.

This is a general statement not aimed at anyone in particular.

`1 person * 500 feature requests / 1 life  = impossible`
