### ISSUE TITLE
[Bug] Soft-hyphens does not work

### ISSUE THREAD

**Issue by trond-eirik** [archimatetool/archi#387]
### Version of Archi, Operating System
Archi 4.2.0 on Windows 10 Pro

### Expected Behaviour
Soft-hyphens should be honored as in a web-browser.
That means invisible when not needed, visible when needed

### Actual Behaviour
Soft-hyphens are always shown as a hyphen

### Steps to Reproduce the Behaviour
1. Create a archi-model with one application component in and save it
2. Open the .archimate file in notepad and replace the name with:  name="LongName&amp;#0173;Here"
3. Save the file and open the model in Archi.  Note that you will see "LongName-Here" all the  time
4. Create a html file with the content below and open in a browser (tested with chrome). Notice that the soft-hyphen is working and that it only shows when the word need to break
&lt;html&gt;
&lt;body&gt;
ThisIsALognTextLetSeHowItIsBrokenIf&amp;#0173;WeDoNothingSpecialAboutIt
&lt;/body&gt;
&lt;/html&gt;
(If this works then https://github.com/archi-contribs/specialization-plugin could be used to insert the special characters - even the best would of course be if it was possible to type then in directly in the Name field. Normally that should work using Alt + 173 but that just seem to cause the meny to activate)

**Comment by trond-eirik** [comment]
If the text is rendered in the Eclipse Draw2D library I would assume that is where the problem is - and where it should be corrected. Somewhere there are some code that already breaks line, either innmiddle of wordd or on regular hyphens. This is the place where the issue should be fixed. Trying to fix it any other place (as long as the xml is correctly translated to unicode characters feed into the rendering component) is likely to be very, very hard.

**Comment by trond-eirik** [comment]
Hmm, BTW seems like Draw2D need to be switced out at some time - maybe the replacement library will fix this issue?
Ref: https://projects.eclipse.org/projects/tools.gef
«Please note that the legacy components Draw2d 3.x, GEF (MVC) 3.x, and Zest 1.x have been put into 'pure maintenance' mode.»

**Comment by Phillipus** [comment]
As I said, Eclipse Draw2D figures do not support rendering text with a soft-hyphen character. This would require some non-trivial additional code to do this. Thus, this is not a "fix" but an additional functionality.

Also, the XML *.archimate format does not support persisting special characters, as you have found. If it did, this may impact other features, such as the exchange format plugin, search and possibly other things.

**Comment by Phillipus** [comment]
> Hmm, BTW seems like Draw2D need to be switced out at some time - maybe the replacement library will fix this issue?

I'm aware of this. The later GEF libraries use JavaFX. This would require a complete re-write of Archi.
