### ISSUE TITLE
Dragging an application component into a business function on a view does not propose to create a relationship between the two elements

### ISSUE THREAD

**Issue by ubibene** [archimatetool/archi#390]
Archi 4.2 Windows 7 or Ubuntu 18
### Expected and Actual Behaviour
When you drag a "business function" into a "business function" , you're prompted for creating a new Relationship between the two functions. You are not when you drag an application component into a business function. As a result the function/application grouping is purely a visual grouping.

### Steps to Reproduce the Behaviour
1. Create a view
2. Add a business function to the view
3.Drag an application component into the business function

**Comment by Phillipus** [comment]
The allowed relationships between Business Function and Application Component are:

- Serving
- Triggering
- Flow
- Association

By default Archi offers nested relationships for these relationships:

- Composition
- Aggregation
- Assignment
- Specialization
- Realization

You can, if you like change this behaviour in Preferences - > Connections -> ARM

**Comment by jbsarrodie** [comment]
The real point is that there is (per ArchiMate standard) no meaningful nesting of Application Component (AC) inside a Business Function (BF).

Such nesting would mean that it exist either a composition/aggregation/assignment/realization/access/specialization **from** BF **to** AC. But none of these relationships are allowed in ArchiMate.

I guess what you want to model is in fact a serving from AC to BF (derived from a some Application Function and Application Service).

In addition, as suggested by Phil your could setup Archi so that it prompts you to create a serving relationship, but even this doesn't work as the resulting serving would be from the outside element to the inside element, ie. from BF to AC.

**Comment by ubibene** [comment]
Thanks ! I was not aware of this settings in the préférences.

It is a common usage to create maps where on the background you put all the enterprise functions , and on the foreground you put on top of these functions the applications used to fullfill (or serve)  them.  (Whats is called "Plan d'occupation des sols fonctionnels in french).  

It's great to achieve this just by adjusting some préférences in archi

**Comment by jbsarrodie** [comment]
Reopening as this doesn't fix the issue

**Comment by Phillipus** [comment]
> Reopening as this doesn't fix the issue

What is the issue to fix?

**Comment by jbsarrodie** [comment]
Issue is not the right word, feature request would be better...

The key point is that there should be a way in ARM to choose the direction of created relationship. I have some ideas for that that I have to share....

**Comment by jbsarrodie** [comment]
Here are my suggestion for an enhanced ARM:

Preferences could allow user to define if they want to allow ARM also for reversed relationships:
![arm configuration](https://user-images.githubusercontent.com/5757396/44910403-5b2df800-ad23-11e8-9a69-a2a72bbfaba7.png)

This preferences could then be used when prompting the user:
![arm in use](https://user-images.githubusercontent.com/5757396/44910429-6f71f500-ad23-11e8-910c-22921a5dced4.png)

For reference, this is related to #207 and by extension also to #233

**Comment by ubibene** [comment]
Maybe you could make the texts in the window "New relationship" the same as the tip text that shows up on a view when hovering over a relationship, just to disambiguate.

Let's say your're dragging B inside of A : the windows will show : 
(aggregation symbol) Composition relation: A is composed of B
...
(aggregation symbol) Composition relation (reverse) : B is composed of A

**Comment by jbsarrodie** [comment]
>Maybe you could make the texts in the window "New relationship" the same as the tip text that shows up on a view when hovering over a relationship, just to disambiguate.

Would be even better, yes.

**Comment by Phillipus** [comment]
@jbsarrodie I've just implemented this in a branch called "arm-reverse-direction". Can you test it? Note that I had to create a new table in Preferences because that table class doesn't allow more than one column.

**Comment by jbsarrodie** [comment]
@Phillipus I'll test during the weekend ;-)

**Comment by jbsarrodie** [comment]
I've just tested. This works as expected. The wording on top of those tables in Preferences should be reviewed (I think it's not clear enough). I'll think about it and will suggest something.

**Comment by jbsarrodie** [comment]
> I've just tested. This works as expected. The wording on top of those tables in Preferences should be reviewed (I think it's not clear enough). I'll think about it and will suggest something.

After some thoughts, I suggest to replace
 - Relation types offered when creating new reversed relations:

by
 - Reverse relation types offered when creating new relations:

**Comment by Phillipus** [comment]
Implemented in 4.3.2.
