### ISSUE TITLE
Hint panel does not render help text 

### ISSUE THREAD

**Issue by pratimsc** [archimatetool/archi#391]
Error Log ->
[default.log](https://github.com/archimatetool/archi/files/2341606/default.log)

### Version of Archi, Operating System

Version of Archi - `4.2.0`
Build - `201801300957`
Os detail - `Fedora 28, Kernel 4.17.14-202.fc28.x86_64, GNU/Linux`
### Expected Behaviour
When any architectural component is selected in any view, it should provide `hints` associated with the component. This is the behaviour that is available on windows, and was available in `Fedora 26`.

### Actual Behaviour
It displays error - 

```
Cannot create Browser component.

If you are running on Linux, please install libwebkitgtk-1.0.0.

<!--- Tell us what happens instead of the expected behavior -->If this fails try setting:
-Dorg.eclipse.swt.browser.DefaultType=mozilla
 or 
-Dorg.eclipse.swt.browser.DefaultType=webkit
in Archi32.ini or Archi64.ini.
```

### Steps to Reproduce the Behaviour
1. On any VM or physical machine, install Fedora 28
2. Install any JVM or JDK on the system
3. Download and unzip Archi
4. Simply start Archi

The library `libwebkitgtk-1.0.0` is not available on Fedora since its release version 27. Newer version of the libraries are available, and the older version can not used in Fedora 28. The versions available on Fedora 28 are -
```
$ dnf list installed | grep -i webkit
kdelibs-webkit.x86_64                  6:4.14.38-6.fc28                @anaconda
kf5-kdewebkit.x86_64                   5.48.0-1.fc28                   @updates 
kwebkitpart.x86_64                     1.4.0-0.1.20180320.fc28         @anaconda
qt5-qtwebkit.x86_64                    5.212.0-0.20.alpha2.fc28        @anaconda
qtwebkit.x86_64                        2.3.4-20.fc28                   @anaconda
webkit2gtk3.x86_64                     2.20.5-1.fc28                   @updates 
webkit2gtk3-jsc.x86_64                 2.20.5-1.fc28                   @updates 
webkit2gtk3-plugin-process-gtk2.x86_64 2.20.5-1.fc28                   @updates 

```

**Comment by Phillipus** [comment]
Did the Hints work on Fedora 27?

In case you are able to search for more info concerning this, this will be an Eclipse SWT Browser component issue.

**Comment by pratimsc** [comment]
No the hint does not work on Fedora 27, and infact its is bit misleading. However, I tried something and it seems to work. 

The solution is that `Archi.ini` file need to be updated, and the GTK version need to be updated to `3` - 
```
--launcher.GTK_version
3
```

So the linux package needs to be updated to hold the value as `3` instead of default `2`. If its requirement from Ubuntu to use GTK version 2 and the package targets the Ubuntu users primarily, then the note on page https://www.archimatetool.com/download/ could be updated to hold this solution for Fedora and other Linux distributions that use GTK version 3.

**Comment by Phillipus** [comment]
I think there may be side issues as well to be aware of if GTK Version is set to 3. I think that Undo/Redo animations don't work for example.

But yes the README can have this information.

**Comment by pratimsc** [comment]
Let me continue to work on Fedora 28 and GTK version 3, in case of any issue I will highlight. 
If I can help anyway to fix this issue e.g. code help, etc - please let me know.

**Comment by Phillipus** [comment]
Some issues are noted in #393 

Googling the issue of using GTK3 instead of GTK2 - some people report slower UI (http://javaclipse.blogspot.com/2017/02/what-is-new-in-eclipse-4x.html) and some UI elements are not so good depending on the Theme.
