### ISSUE TITLE
MacOS Retina graphics not working

### ISSUE THREAD

**Issue by stephanbuys** [archimatetool/archi#394]
### Version of Archi, Operating System
4.3 beta 1

### Expected Behaviour
Retina Graphics

### Actual Behaviour
Blurred text, fuzzy fonts - was the same in version 4.2

### Steps to Reproduce the Behaviour
Unknown - just running this on MacOS.

**Comment by Phillipus** [comment]
This is the same for version 4.2 you say? I've not had any other reports from Mac users about this.

Can you provide a screenshot?

**Comment by Phillipus** [comment]
Something to try I found from here: 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=382972#c4

1. Right-click the Archi.app
2. "Show Package Contents"
3. Dig into Contents folder
4. Edit "Info.plist" and add this:
```
<key>NSHighResolutionCapable</key>
<true/>
```

May need to log out and back in again.

**Comment by Phillipus** [comment]
Attached is a an Info.plist file that you could try. It's in a zip file.
[Info.zip](https://github.com/archimatetool/archi/files/2346321/Info.zip)

**Comment by stephanbuys** [comment]
Hi yes - I have the same on 4.2.  
<img width="433" alt="screen shot 2018-09-04 at 06 28 19" src="https://user-images.githubusercontent.com/6009682/45010475-11d4f580-b00e-11e8-9713-2175677dce28.png">

I tried the Info.plist fixes, no luck. I also tried: https://apple.stackexchange.com/questions/75891/how-can-i-completely-remove-apples-java-6-and-make-oracles-java-7-default-for
(in my case 1.8)

Somewhere there's a cached setting or something.

**Comment by Phillipus** [comment]
Setting the Java won't help as Archi has its own bundled Java in the App.

When you replace the Info.plist you might try renaming things, or rebooting to clear the cache (ckec the thread at https://bugs.eclipse.org/bugs/show_bug.cgi?id=382972). Right-click on Archi app and "Get Info" should show "Open in Low Resolution" as not checked.

Eclipse itself should be similar. You could download it and see if it works in hi-res mode:

https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.7.3a-201803300640/eclipse-SDK-4.7.3a-macosx-cocoa-x86_64.dmg

**Comment by Phillipus** [comment]
One thing you could also try in Archi is "Help - > Reset To Defaults..." and restart Archi. This will clear Archi layout cache and visual settings.

**Comment by stephanbuys** [comment]
@Phillipus - ah - it is checked (Open in Low Resolutions): but greyed out and I can't untick it even with privileges.

But making a copy of the App (so that MacOS can notice the change) worked! Thanks so much, it looks so much better.

**Comment by Phillipus** [comment]
Ah, that's great news. Thanks for reporting this.

Some observations:

1. I don't have a retina Mac so I rely on users who do to report this type of issue, so strange that no-one else has noticed this. Thanks for reporting this. :-)
2. The updated Info.plist will be included in Archi 4.3 beta 2
3. I'm now wondering how retina Mac users who update to Archi 4.3 can force the change. I found this https://apple.stackexchange.com/questions/162141/how-do-i-properly-force-osx-to-reload-the-info-plist-file-of-an-application - moving the app to a different location seems to do it.

**Comment by Phillipus** [comment]
The updated Info.plist is now present in Archi 4.3 beta 2.

Forcing the cache to update seems to involve moving the Archi.app from one location to another.

**Comment by Phillipus** [comment]
@stephanbuys Are you seeing the issue reported in #396 ?
