### ISSUE TITLE
Ability to increase line width on elements

### ISSUE THREAD

**Issue by mjtapp** [archimatetool/archi#395]
This is a feature request. It would be really useful if the width of the line surrounding ArchiMate elements could be made thicker for a given element in a diagram. 

The reason being that changing the colour of the outline of an element is a heatmapping variant that works well - but it doesn't work so well in Archi because the line isn't thick enough by default to really show up, so being able to increase the thickness on an element by element basis would add another option to the visual layout of elements.

**Comment by Phillipus** [comment]
That's a fair request.

There is an issue that needs to be solved first with drawing with line widths greater than 1 at different zoom levels (in the app and when exporting to image). The lines are not equal on all sides.

**Comment by mjtapp** [comment]
Ah, fair enough, I figured there must have been a reason. I'll let you figure that out then :)

**Comment by jbsarrodie** [comment]
+1

I really would like this to work. This could be packaged with #273.

Maybe I should go back to code ;-)

**Comment by Phillipus** [comment]
I tried different ways to do this in the RectangleFigureDelegate class. I set line width to values of 1, 2, 3, 4. Then zoomed in and out in the view, and also exported to SVG. Some zoom levels just did not work out in different cases. There is no setting where it works at all zoom levels and in SCG export.

**Comment by jbsarrodie** [comment]
Some months (maybe years) ago I tested something that worked or rectangles but never tested it on more complexe shapes.

I can see two possible solutions here:
* either keep the bounding box/clipping area unchanged and drawing borders **inside** it. This requires to override common drawing methods.
* or keep the drawing logic unchanged but extend the bounding box/clipping area. This has impacts on some other things like anchors that would have to be checked.

BTW, overriding some common (draw2d) drawing methods could fix the issue we have on SVG export: draw2d and SVG have different algorithms for rectangle (and some other basic shapes):
* draw2d draws a rectangle from origin to origin **+** width/height, so rectangle (1,1,10,10) results in a rectangle which is 11px wide.
* SVG draws a rectangle from origin, and with size equals to width/heigh, so rectangle(1,1,10,10) results in a rectangle which is 10px wide.

I will investigate, I like this kind of challenges ;-)

**Comment by jbsarrodie** [comment]
@Phillipus look at the new branch "line-width-experiment" ;-)

**Comment by Phillipus** [comment]
@jbsarrodie Well, that does seem promising. :-) I did some testing at various line widths, zoom levels and export to SVG. Seems good.

Any gotchas or side-effects that you noticed? Any caveats?

**Comment by jbsarrodie** [comment]
>Any gotchas or side-effects that you noticed? Any caveats?

Not really:
* If we stick with small linewidth (max 3 or 4px) everything is ok, but if we try thicker linewidth then the border overlap a bit with icons.
* as the border is drawn a bit over the bounds, anchor points car be a bit inside the border for linewidth >2

Other than those tiny things it seems ok... and a surprisingly simple fix. I think we should add it to 4.3 beta3, together with an option to set line-width to Normal (1px), Medium (2px), Heavy (3px). My rational if that EMF model has been change a bit to add transparency, so it's better to group as many of those changes together in a release.

**Comment by Phillipus** [comment]
- The EMF model won't be impacted as ILineObject is already implemented in IDiagramModelObject and will not affect any .archimate files existing
- Setting the line width to 1 is not the same as the existing behaviour where line width is not set (0). With line width at 0 the width does not change when zooming in/out. We should keep 0 as an option. Users have seen it like this for 8 years now. ;-)
- A default line width is needed in prefs, perhaps. Not sure about setting the existing line width as a default to 1 because users may get a surprise in their diagrams!

**Comment by Phillipus** [comment]
IDiagramModelObject.getLineWidth() returns 1 as a default. So, 0 is not an available default value.

**Comment by Phillipus** [comment]
Some objects don't look so good with line width not zero. Canvas Stickies for example.

**Comment by jbsarrodie** [comment]
>The EMF model won't be impacted as ILineObject is already implemented in IDiagramModelObject and will not affect any .archimate files existing

Good

>Setting the line width to 1 is not the same as the existing behaviour where line width is not set (0). With line width at 0 the width does not change when zooming in/out. We should keep 0 as an option. Users have seen it like this for 8 years now. ;-)

I personnaly have always found it ugly to not have width set to 1 but 0. This has blocked me from exportig PNG at something other than 100% several time. I consider setting it to 1 as a fix (but again, personnal opinion).

>A default line width is needed in prefs, perhaps. Not sure about setting the existing line width as a default to 1 because users may get a surprise in their diagrams!

I would set 1 has the default in prefs and (in object properties) add a choice for 0 ("unset") leading to those choices: unset, 1, 2, 3. Old models could use "unset" by default so rendering is not impacted. In my case a simple jArchi script will set it to 1 everywhere ;-)

>IDiagramModelObject.getLineWidth() returns 1 as a default. So, 0 is not an available default value.

Not sure to understand. But if this means that rendering will change by default for old models, maybe we could convert old models when loading them the first time.

>Some objects don't look so good with line width not zero. Canvas Stickies for example.

Rendering should be exactly the same at 100%, but I haven't tested.

**Comment by Phillipus** [comment]
> Not sure to understand. But if this means that rendering will change by default for old models, maybe we could convert old models when loading them the first time.

That's what it means.

I've taken a closer look, and the overall changes and impact are non-trivial. I'm not sure about it being targeted for 4.3.

**Comment by Phillipus** [comment]
Added new branch "linewidth".

- This adds a Line Width setting to the Property Tab.
- Added setLineWidth method to AbstractDiagramModelObjectFigure so this will only render for some figures.

- Set the line width to "Heavy" on a figure.
- Move the object
- Deselect the object
- Undo/Redo

**Comment by jbsarrodie** [comment]
>I've taken a closer look, and the overall changes and impact are non-trivial. I'm not sure about it being targeted for 4.3.

If adding this has no impact on EMF model then this can wait for 4.3.1

>Added new branch "linewidth".
>There are some rendering issues when moving objects and then doing Undo/Redo (ensure the object is not selected to see this).

Ok, Will test later tonight.

**Comment by Phillipus** [comment]
+1 on targeting 4.3.1

**Comment by Phillipus** [comment]
Moved to #953

**Comment by zetic-be** [comment]
Hello,
Setting the Line Width in Properties >Appearance is convenient.
Is there a way to set it by default in preferences for all or specific figure types?
I found how setting colours for objects, Element line colour, but not Line Width.
Could be also defined in Appearance > Defaults for new Archimate figures?
Thank you

**Comment by Phillipus** [comment]
> Hello, Setting the Line Width in Properties >Appearance is convenient. Is there a way to set it by default in preferences for all or specific figure types? I found how setting colours for objects, Element line colour, but not Line Width. Could be also defined in Appearance > Defaults for new Archimate figures? Thank you

I'll add it to the "to do" list.

**Comment by zetic-be** [comment]
Great, thank you @Phillipus  !
