### ISSUE TITLE
Collaboration github certificate

### ISSUE THREAD

**Issue by jvdongen17** [archimatetool/archi#402]
### Version of Archi, Operating System

Archi 4.1.1.
Github SCMManager

### Expected Behaviour

Refresh of model from Github

### Actual Behaviour

Error on certificate by refresh.
![error message](https://user-images.githubusercontent.com/35136585/47773550-bc098a80-dcea-11e8-8492-a625091431a5.png)

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Please can you report this in the Collaboration Plugin Issues https://github.com/archimatetool/archi-modelrepository-plugin/issues

**Comment by jvdongen17** [comment]
Done

Op wo 31 okt. 2018 om 11:04 schreef Phil Beauvoir <notifications@github.com

**Comment by jvdongen17** [comment]
Done
