### ISSUE TITLE
Literals & properties Not NLS exported

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#403]
There are few elements that are still not yet accessible to be translated with the NLS plugin :
- the Outline view : as it seems to be an eclipse basic component, it is translated by "Structure"  with the Babel plugin ... and cannot be modified thus translated
- the toolbar seems to have exactly the same behavior as the Outline view
- the 'Generate View' box (Ctrl+ G) offer a list of Viewpoint. This list seems to be based with an xml file, and is not exported with the nls plugin
<img width="615" alt="tmp" src="https://user-images.githubusercontent.com/43959255/48002104-dd171480-e10a-11e8-8859-fb02c15be894.png">

**Comment by Phillipus** [comment]
For the list of Viewpoints, there is a file "viewpoints.xml" in the `com.archimatetool.model/model` folder that contains these strings. I haven't yet figured out how to externalise this file, or put it in a location that can be NLS'd. I think a workaround would be to replace that file with one where the strings are translated.

**Comment by jbsarrodie** [comment]
@phillipus I've noticed that the viewpoints.xml contains `xml:lang` attributes in name tags. Is it used in the UI or not ?

**Comment by Phillipus** [comment]
@jbsarrodie No. It's a placeholder. This needs revisiting. In the meantime, replacing the xml file with a translated one will work.

**Comment by Phillipus** [comment]
This is fixed now. See https://github.com/archimatetool/archi/issues/683#issuecomment-711149691
