### ISSUE TITLE
CSV cannot distinguish AND vs OR junctions

### ISSUE THREAD

**Issue by mcavaiani** [archimatetool/archi#406]
### Version of Archi, Operating System
Archi4, Windows 10

### Expected Behaviour
The .csv -element file should be able to distinguish AND junctions from OR ones. After creating the required .csv files, the imported junctions should show the proper colour according to the type (Black for AND junctions, white for OR ones) 

### Actual Behaviour
AND and OR junctions share the same type tag in the .csv -elements file. In this way Archi cannot distinguish and from or junctions.

### Steps to Reproduce the Behaviour
1. Create a new model
2. Add one AND junction. Add one OR junction.
3. Export the model to .csv files
4. Open the .csv -elements file: there will be no difference between the two item
5. Close the model
6. Create a new model and import the .csv -elements file
7. Drag and drop the two junctions: both of them will be black and of AND type.

**Comment by Phillipus** [comment]
Thanks for the clear and detailed report.

This should be handled the same way as we do it for types of Access relationship type and Influence relation strength attributes - as a property in the corresponding *.properties CSV file.

I've just committed a fix to use `Junction_Type` as a key and "Or" or "And" as the value.

```
"ID","Key","Value"
"314aa40d-68dc-49f6-a084-55204d3c355b","Junction_Type","Or"
"825543a0-1d67-4c25-a893-88415fd81715","Junction_Type","And"
```

Will be in next version of Archi.

**Comment by Phillipus** [comment]
Please try latest Archi 4.3.1 with a fix https://www.archimatetool.com/download/

**Comment by mcavaiani** [comment]
Thank you very much

Best

MC

________________________________
Da: Phil Beauvoir <notifications@github.com>
Inviato: Friday, November 30, 2018 3:01:50 PM
A: archimatetool/archi
Cc: mcavaiani; Author
Oggetto: Re: [archimatetool/archi] CSV cannot distinguish AND vs OR junctions (#406)


Please try latest Archi 4.3.1 with a fix https://www.archimatetool.com/download/
