### ISSUE TITLE
87 compilation problems with com.archimatetool.zest

### ISSUE THREAD

**Issue by bluecrystalsign** [archimatetool/archi#411]
### Expected Behaviour

Can't compile com.archimatetool.zest
### Steps to Reproduce the Behaviour
1.Just followed the code import tutorial.
2.
3.

**Comment by bluecrystalsign** [comment]
Dear Phil,

Thank you for your quick answer.
Yes, I have set the target and it fixed most errors.
I have followed the procedure described on the wiki, step by step. But just to make sure, I just deleted everyhting, and I'm rdoing it from scratch.



Just to make sure:
* I'm using JDK 8 181
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

* Eclipse
Eclipse for RCP and RAP Developers
Version: Oxygen.3a Release (4.7.3a)

Build id: 20180405-1200
* Windows 10


The error list I havenow is shown below, and they are all relted to com.archimatetool.zest:

Description	Resource	Path	Location	Type
Bundle 'org.eclipse.zest.core' cannot be resolved	MANIFEST.MF	/com.archimatetool.zest/META-INF	line 15	Plug-in Problem
Bundle 'org.eclipse.zest.layouts' cannot be resolved	MANIFEST.MF	/com.archimatetool.zest/META-INF	line 16	Plug-in Problem
GraphConnection cannot be resolved to a type	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 173	Java Problem
GraphNode cannot be resolved to a type	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 270	Java Problem
GraphNode cannot be resolved to a type	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 270	Java Problem
GraphNode cannot be resolved to a type	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 278	Java Problem
GraphNode cannot be resolved to a type	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 278	Java Problem
GraphNode cannot be resolved to a type	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 246	Java Problem
GraphViewer cannot be resolved to a type	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 31	Java Problem
GraphViewer cannot be resolved to a type	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 96	Java Problem
IGraphContentProvider cannot be resolved to a type	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 29	Java Problem
ISelfStyleProvider cannot be resolved to a type	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 56	Java Problem
LayoutStyles cannot be resolved to a variable	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 123	Java Problem
SpringLayoutAlgorithm cannot be resolved to a type	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 123	Java Problem
The constructor PropertiesAction(ZestGraphViewer) is undefined	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 327	Java Problem
The import org.eclipse.zest cannot be resolved	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 21	Java Problem
The import org.eclipse.zest cannot be resolved	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 17	Java Problem
The import org.eclipse.zest cannot be resolved	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 18	Java Problem
The import org.eclipse.zest cannot be resolved	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 46	Java Problem
The import org.eclipse.zest cannot be resolved	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 47	Java Problem
The import org.eclipse.zest cannot be resolved	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 13	Java Problem
The import org.eclipse.zest cannot be resolved	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 18	Java Problem
The import org.eclipse.zest cannot be resolved	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 19	Java Problem
The import org.eclipse.zest cannot be resolved	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 20	Java Problem
The import org.eclipse.zest cannot be resolved	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 21	Java Problem
The method addDoubleClickListener(new IDoubleClickListener(){}) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 140	Java Problem
The method addSelectionChangedListener(DrillDownManager) is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 52	Java Problem
The method addSelectionChangedListener(new ISelectionChangedListener(){}) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 129	Java Problem
The method applyLayout() of type ZestGraphViewer must override or implement a supertype method	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 100	Java Problem
The method dispose() of type ZestViewerContentProvider must override or implement a supertype method	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 84	Java Problem
The method getContentProvider() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 824	Java Problem
The method getControl() is undefined for the type ZestGraphViewer	ExportAsImageAction.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 42	Java Problem
The method getControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 164	Java Problem
The method getControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 295	Java Problem
The method getControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 666	Java Problem
The method getControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 667	Java Problem
The method getDestination(Object) of type ZestViewerContentProvider must override or implement a supertype method	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 165	Java Problem
The method getElements(Object) of type ZestViewerContentProvider must override or implement a supertype method	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 92	Java Problem
The method getGraphControl() is undefined for the type new MouseWheelListener(){}	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 88	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	CopyZestViewAsImageToClipboardAction.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 48	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 269	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 277	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	ExportAsImageAction.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 43	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 63	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 71	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 120	Java Problem
The method getGraphControl() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 189	Java Problem
The method getInput() is undefined for the type new IPropertyChangeListener(){}	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 40	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ExportAsImageAction.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 37	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 238	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 400	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 441	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 531	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 592	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 630	Java Problem
The method getInput() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 851	Java Problem
The method getLabelProvider() is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 74	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 100	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 241	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 234	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 362	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 393	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 442	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 532	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 593	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 624	Java Problem
The method getSelection() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 678	Java Problem
The method getSource(Object) of type ZestViewerContentProvider must override or implement a supertype method	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 157	Java Problem
The method inputChanged(Viewer, Object, Object) of type ZestViewerContentProvider must override or implement a supertype method	ZestViewerContentProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 88	Java Problem
The method refresh() is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 211	Java Problem
The method registerContextMenu(MenuManager, ISelectionProvider) in the type IWorkbenchPartSite is not applicable for the arguments (MenuManager, ZestGraphViewer)	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 669	Java Problem
The method setContentProvider(ZestViewerContentProvider) is undefined for the type ZestGraphViewer	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 51	Java Problem
The method setInput(null) is undefined for the type new IPropertyChangeListener(){}	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 41	Java Problem
The method setInput(Object) is undefined for the type new IPropertyChangeListener(){}	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 43	Java Problem
The method setInput(Object) is undefined for the type ZestGraphViewer	DrillDownManager.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 75	Java Problem
The method setLabelProvider(ZestViewerLabelProvider) is undefined for the type ZestGraphViewer	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 52	Java Problem
The method setLayoutAlgorithm(SpringLayoutAlgorithm, boolean) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 123	Java Problem
The method setSelection(IStructuredSelection) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 401	Java Problem
The method setSelection(IStructuredSelection) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 443	Java Problem
The method setSelection(IStructuredSelection) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 533	Java Problem
The method setSelection(IStructuredSelection) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 594	Java Problem
The method setSelection(IStructuredSelection) is undefined for the type ZestGraphViewer	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 631	Java Problem
The method setSelectionProvider(ISelectionProvider) in the type IWorkbenchSite is not applicable for the arguments (ZestGraphViewer)	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 158	Java Problem
The return type is incompatible with IModelView.getViewer()	ZestView.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 300	Java Problem
ZestStyles cannot be resolved to a variable	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 42	Java Problem
ZestStyles cannot be resolved to a variable	ZestGraphViewer.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 56	Java Problem
ZestStyles cannot be resolved to a variable	ZestViewerLabelProvider.java	/com.archimatetool.zest/src/com/archimatetool/zest	line 157	Java Problem

**Comment by Phillipus** [comment]
Sometimes Eclipse can get "stuck" when compiling all the projects. This has happened to me before. I've managed to coax it into action by closing the project and then re-opening it, or choosing "Project -> Clean..." from Eclipse main menu.

Other times I've tried "Reload Target Platform" from the "archi-target" file. This should look like this:

![screen shot 2018-11-19 at 10 13 43](https://user-images.githubusercontent.com/600504/48700436-eb256480-ebe3-11e8-872b-a15aa750d01f.png)

**Comment by bluecrystalsign** [comment]
Dear Phil.

Thank you for your help.
IT works fine now.

The missing step was:
"In the editor, click "Reload Target Platform" (top right of the editor, might be required to click first "Set as active platform")"

My best regards,
Sergio

**Comment by Phillipus** [comment]
OK, if it's OK I'll close this.
