### ISSUE TITLE
Precise position of elements in view with keyboard

### ISSUE THREAD

**Issue by rchevallier** [archimatetool/archi#412]
The mouse doesn't always allow easily to precisely position pixel wise elements in views or do bulk modification. 

Proposition: 
Use the keyboard direction keys up/down/left/right (with modifier) to move/resize elements. 
* To __move__: use ALT modifier key. 
* To __resize__: use CTRL modifier.
Keep standard selection behaviour (resp. extend) with direct  keys (resp. with SHIFT modifier)

Behaviour may depends on Snap to Grid (to be decided)
if Snap to Grid is off: 
    move/resize selected elements (1 or more) by 1 pixel up/down/left/right 
If Snap to Grid is on:
   move/resize selected elements (1 or more) to the next grid point up/down/left/right

**Comment by jbsarrodie** [comment]
>It's possible to do similar to this already. From the Archi User Guide:

OMG, despite the fact I read this guide several time, I never noticed this feature.... but I was looking for it !

**Comment by Phillipus** [comment]
Because we use the GEF 3 library we have to use whatever is inbuilt for that. ;-)

**Comment by normenmueller** [comment]
@Phillipus Does this also work under macOS Catalina? Currently, if I select an element and then click ".", I cannot move the element with the keyboard. Any ideas?

**Comment by Phillipus** [comment]
> @Phillipus Does this also work under macOS Catalina? Currently, if I select an element and then click ".", I cannot move the element with the keyboard. Any ideas?

Yes, but you have to give permission for Archi to use Accessibility features in Mac's Preferences, Accessibility, Privacy settings.

<img width="667" alt="Screenshot 2020-05-12 at 21 27 42" src="https://user-images.githubusercontent.com/600504/81742190-9a6c9000-9497-11ea-8f05-a8361722e0aa.png">

**Comment by normenmueller** [comment]
@Phillipus Wow! Thx for the fast reply. Unfortunately this does not work. I already granted those accessibility rights, but nothing happens clicking ".".
![image](https://user-images.githubusercontent.com/428576/81745155-96933a80-94a4-11ea-9d7a-0a0a8c331bf2.png)
I running the this version
![image](https://user-images.githubusercontent.com/428576/81745189-a90d7400-94a4-11ea-9c15-33c9af64459b.png)

**Comment by Phillipus** [comment]
I don't know what else to suggest. Selecting a box in a diagram and pressing "." works for me on MacOS 10.15.4. The cursor changes. Pressing "." multiple times also changes the cursor. It might be an internationalisation thing. As this functionality is built into the graphics library (GEF) I can't change anything.

**Comment by normenmueller** [comment]
@Phillipus OK. I understand. What keyboard settings are you using?

**Comment by Phillipus** [comment]
British - PC.

**Comment by normenmueller** [comment]
Still doesn't work. Must be sth. else... :-( Thx anyway for your time!

**Comment by Phillipus** [comment]
Remove Archi from the list of apps in the Privacy preferences (don't untick it, remove it). Then run Archi again, select a box in a diagram and press the "." key. A Mac dialog should appear asking to grant it permission.

**Comment by normenmueller** [comment]
Great idea! I followed your advice and yes a mac dialog appeared. I (re)granted the access rights and swichted back to Archi... no luck... again just nothing happens.

**Comment by normenmueller** [comment]
I guess it interferes with some other app. Will investigate further... and hopefully post a success story here ;-)
