### ISSUE TITLE
Not to automatically draw relations when an element is reused in a view

### ISSUE THREAD

**Issue by jyl13** [archimatetool/archi#414]
This is a feature request, not an issue.

Currently when an element is used several time in a same view, the currently defined relations are automaticaly redraw. It forces to delete all of them before to draw the new ones.
Is it possible not to draw these relations (could be configurable in preferences, or through a question box poping-up on duplication of the element).

**Comment by Phillipus** [comment]
If you mean when you drag and drop an element from the tree to a View then if you hold the CTRL key down at the same time then relationships are not added.

**Comment by jyl13** [comment]
Closed as already covered. Thanks a lot.
