### ISSUE TITLE
To add a "duplicate" option on element contextual menu

### ISSUE THREAD

**Issue by jyl13** [archimatetool/archi#415]
When we need to reuse an element in the same view (to use the same element several time), by default a copy of the element create an new instance of the element. Could it be possible to add a "duplicate" option in right click contextual menu which in this case create a new icon of the same element (not creating a new instance of the element in the tree menu).

**Comment by Phillipus** [comment]
A "duplicate" is different than "new instance". To create a duplicate, you can copy and paste elements in a View. Or you can use "Paste Special" which does create a new instance. Does this cover your use case?

**Comment by jyl13** [comment]
Hello

Thank for your qucik reply.
Not sure it cover the need.
In the same view (diagram) I want to reuse the same component several time (meaning it appear only one time in the tree model, but in the diagram I want to have the same element repeated several time.
Currently if in the view I select an element and do" Ctrl C / Ctrl V" or "right-click + copy + paste" then a new instance of the component is automatically created in the tree model on the left, this is what I would like to avoid through a new option in the right click menu, maybe I misused  "duplicate".

Regards



[Description: Description: Description: Description: Description: Description: Description: logo_big5] [cid:image003.png@01D48742.57332D30]

Jean-Yves LONGUEVILLE | TINA: 043 6129 | Tel: +33 442 686 129 | Mobile: +33 637 178 476
STMicroelectronics | ICT Manufacturing & Quality | Technology Architect

ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world

**Comment by Phillipus** [comment]
This is why I said:

> Or you can use "Paste Special" which does create a new instance.

**Comment by jyl13** [comment]
Whaou !!! … exactly what I need, you can delete the other request also. Is there a keyboard shortcut associated such as Ctrl-C + Ctrl-V ?

[Description: Description: Description: Description: Description: Description: Description: logo_big5] [cid:image004.png@01D48743.19F740E0]

Jean-Yves LONGUEVILLE | TINA: 043 6129 | Tel: +33 442 686 129 | Mobile: +33 637 178 476
STMicroelectronics | ICT Manufacturing & Quality | Technology Architect

ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world

**Comment by Phillipus** [comment]
> Is there a keyboard shortcut associated such as Ctrl-C + Ctrl-V ?

Yes, you can see it in the menu - Ctrl + Shift + V

> you can delete the other request also

Please feel free to close any issues if they are resolved. :-)

**Comment by jyl13** [comment]
Excellent !!! I close....
