### ISSUE TITLE
[Feature Request] Export Notes as text in the reports

### ISSUE THREAD

**Issue by jfdeclercq** [archimatetool/archi#422]
I'd like Archi to export the contents of notes in the report as text. Today they are only visible on the diagrams. If a note contains 'toto" we should be able to search and find the text "toto" in the report.

**Comment by Phillipus** [comment]
In the next version, notes, stickies, etc will be selectable in the report's View image and their text and properties will be exposed too.

**Comment by Phillipus** [comment]
Fixed in Archi 4.4 beta
