### ISSUE TITLE
[Feature Request] Diagram Note

### ISSUE THREAD

**Issue by jfdeclercq** [archimatetool/archi#423]
On each diagram I'd like  add a "diagram note" in a click with : 
- Diagram Name
- Diagram Author Name
- Diagram Creation Date
- Diagram Last modif date

- Optional  : version (can be in the name)

**Comment by jbsarrodie** [comment]
Hi, this should be easy to do using [jArchi](https://github.com/archimatetool/archi-scripting-plugin/wiki).
Here is a starting point in the API: https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Object#createobject

**Comment by jfdeclercq** [comment]
I try but I have an error with this line: 

var note = archimateView.createObject("note", 10, 200, -1, -1);

Script Error at: javax.script.ScriptException, javax.script.ScriptException: ReferenceError: "archimateView" is not defined

How do I get the current archimateview ?

Also, does the scripting language manipulate dates ? What is the scripting engine in fact ?

J-F

**Comment by jfdeclercq** [comment]
Cool, I only add to add "var" here and there and add view.name and it works ! Thanks !

// Get the first view in the current selection
var view = selection.filter("archimate-diagram-model").first();
// Get current date
var currentDate = new Date();
// Create a new note and set its text
var note = view.createObject("note", 10, 200, -1, -1);
note.text = view.name + " - " + currentDate.toDateString();
