### ISSUE TITLE
Model tree not sorting?

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi#425]
### Version of Archi, Operating System
Archi version 4.3.0, build 201809101333, windows 10

### Expected Behaviour
The objects in the model tree should be sorted in alphabetical order according to the User Guide, v 4.3.1, page 10, "Folders and Organisation":  "all elements in a folder are automatically sorted alphabetically".  Am I missing something?

### Actual Behaviour
The object listed in my Application folder and in my Technology/Physical folder are not sorted in one continuous alphabetical list.  There are 2 alphabetical sub-lists, one after the other.  Closing and re-starting Archi does not affect the sort order.  The closest I can come to providing a sort-order theory is it is might represent creating these objects on 2 separate days.
![application folder list](https://user-images.githubusercontent.com/40830379/50177087-bbdb4380-02c6-11e9-9064-623cdf359fcf.PNG)
![tech-physical folder list](https://user-images.githubusercontent.com/40830379/50177091-bf6eca80-02c6-11e9-827a-7d9da4e3b769.PNG)

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
It's sorting in the order of upper case, then special characters, then lower case. This has always been the. er, case. Whether this is the preferred behaviour, I'm not sure. It would be possible to the change the sort order but we'd need to found out what would be best for most users.

**Comment by timhale7** [comment]
ah, so that's it!  I didn't catch that distinction.  I can adjust my naming now that I know how it acts.  thank you.

**Comment by Phillipus** [comment]
I could change the sorting so that it sorts in the order of AAA, aaa, ///

**Comment by timhale7** [comment]
in my opinion, that would make it easier to observe and discern the default behavior.

**Comment by Phillipus** [comment]
@jbsarrodie Do you have an opinion on this?

**Comment by jbsarrodie** [comment]
>Do you have an opinion on this?

Yes, current sorting can (and should) be improved. I would suggest a typical (simplified if needed) ASCII sorting: numbers, upper case, lower case, non numbers/alphabetical.

One could also suggest to mix upper and lower case, maybe as an option (I have some applications that should be written with a staring lower 'e', while all other applications starts with a capital letter...)

**Comment by timhale7** [comment]
mixing upper and lower together gets my vote...

**Comment by Phillipus** [comment]
Version 4.3.2 released today solves this.

**Comment by timhale7** [comment]
Phil,
I downloaded the new version.  this looks great.  thank you!
