### ISSUE TITLE
[enhancement] object icon movement behavior when moving a group

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi#426]
### Expected Behaviour
When I change the size of the group using the top or left handles, I would prefer that the included objects not move at all - I've usually got them already aligned with other objects elsewhere on the page, and I'm needing to increase the group space to add a new one.  

### Actual Behaviour
When I make a group taller using the handles on the top of the group, it moves all of the object icons with it.  When I make a group wider using the handles on the left side of the group, it moves all of the object icons with it.  I would prefer that the included objects not move at all when changing the size of the group.

I like how the included icons do not move when I use the right/bottom handles to change the group size.

I like how the group and icons move together when I click and drag the group elsewhere on the page.

**Comment by Phillipus** [comment]
This is possible, and I've just written the code to do this.

@jbsarrodie Which option do you prefer?

1. Leave diagram parent/child behaviour as it is now  - children "stick" to the top-left when the parent is resized on top/left
2. Change diagram parent/child behaviour - children stay in their existing positions when the parent is resized on top/left
3. Add a User Preference for 1 or 2

**Comment by jbsarrodie** [comment]
@Phillipus would it be possible te keep current behavior (1) by default but switch to the other one (2) when resizing while keeping some key pressed (SHIFT for example) ?

**Comment by Phillipus** [comment]
@jbsarrodie Funny you should say that, as I spent today trying to do just that. For technical reasons to do with how GEF handles Commands and things, not so easy.

**Comment by Phillipus** [comment]
>@jbsarrodie Funny you should say that, as I spent today trying to do just that. For technical reasons to do with how GEF handles Commands and things, not so easy.

GEF already uses various key modifiers (Shift, Ctrl / Command, Alt deepening on OS Platform) to change the resize behaviour - keep aspect ratio, extend in two directions etc. So can't easily add another modifier key.

**Comment by jbsarrodie** [comment]
>not so easy.

In addition, there is not so many remaining modifiers (shift, alt and ctrl are already used).

**Comment by jbsarrodie** [comment]
We're on the same page ;-)

It seems that alt-gr is available (but don't know if it has an equivalent on mac)

**Comment by Phillipus** [comment]
It's technically not a good idea to access the global key listener when in the midst of a GEF Command. I spent several hours trying this today. ;-)

Having a preference for one or the other is better than nothing. Perhaps revisit the modifier key another time,

**Comment by jbsarrodie** [comment]
Thinking a bit more about the use-case: resizing from top and/or left usually (almost always) is done because you want some room on the top and/or left, so I think (2) is the best default behavior.

So I'd suggest to use a preference but to make (2) the new default, and (1) an option.

**Comment by Phillipus** [comment]
> So I'd suggest to use a preference but to make (2) the new default, and (1) an option.

OK. But existing users might find this surprising. Or they may be delighted! :-)

**Comment by jbsarrodie** [comment]
>Or they may be delighted! :-)

+1

**Comment by Phillipus** [comment]
OK, will be in 4.4

**Comment by timhale7** [comment]
thank you, gentlemen.

**Comment by Phillipus** [comment]
This is in 4.4.

**Comment by timhale7** [comment]
I installed 4.4 this morning and tried it out.  Works great!  Thanks!!
