### ISSUE TITLE
Add Images to ArchiMate Views

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#43]
You can already do it in the "Canvas" view. Would users like it for ArchiMate Views as well? Some users were asking for additional illustrations.

So far I kept it restricted to the Canvas View in case it didn't work out. But I could easily open up the functionality to ArchiMate views.

Caveats are the same as including an image in a Canvas view:
- The *.archimate file will be in an archive format (zipped) to contain all the assets together
- ~~Saving and loading is a bit slower~~ Opening a View with images in it is a bit slower
- Use reasonable size images, not your whole Flickr family holiday collection.

**Comment by peterprib** [comment]
Understand why image shouldn't be treated as separate case but note should allow images and more robust store say word docs etc.  Actually it goes to reference material used to construct model.

**Comment by herve91** [comment]
Hi Peter,

You can add images on Archimate views using my [specialization plugin](https://github.com/archi-contribs/specialization-plugin).

Best regards
Hervé

**Comment by MilennialZero** [comment]
I've used Sparx to store rtf docs in the model data base and found it better to add links in the model to content in the corporate Sharepoint. Ie, program and project documentation.

And some of that program and project documentation in Sharepoint contains diagrams and text mastered in an Archimate model. And the content of an Archimate model can be replicated from the tool in HTML, which can be loaded straight into Sharepoint.

Options.

Jon McLeod
Director
McLeod Consultancy Pty Ltd
GPO Box 813, Canberra ACT 2601 Australia
Silver Member, The Open Group

**Comment by peterprib** [comment]
Hi Hervé

Tried it out.  Doesn't work as described.  Changes icon on models but fails to materialize on view and has odd behavior on properties where by it overrides all tabs.

**Comment by herve91** [comment]
Hi Peter,

Could you please open an issue on the [plugin site](https://github.com/archi-contribs/specialization-plugin/issues), detailing what you do and I will help you make the plugin work.

Best regards
Hervé

**Comment by vojtob** [comment]
I would like to add images into archimate views. Enterprise architecture is communicated with business people and it could help. 
To add images to exported diagrams is uncomfortable, every small change in diagram implies manual (=error prone) work. Thanks.

**Comment by gitfirenz** [comment]
90% of my archi schemes are **redrawn** by PMO : they need cool pictures etc. When a manager pay $$$$ to Oracle, he wants at least the logo on the IT view.

I think **comments with pictures** would be a nice first step (not to alter the model).

Or adding a picture on a component, and having a global View setting to show/hide customizations.

**Comment by jbsarrodie** [comment]
Hi,

This is an old feature request... FWIW, I now think that this should be possible and could help in several occasions. I've described my ideas for such feature in [this page](https://github.com/archimatetool/archi/wiki/Ideas-for-a-nice-and-elegant-way-to-implement-profiles-and-concepts-customization).

@gitfirenz : in fact you can already do it through @herve91's [specialization plugin](https://github.com/archi-contribs/specialization-plugin). You will not be able (to my knowledge) to add images to visual notes, but you will be able to override top right icons on elements, meaning that you can easily show a nice oracle icon on services, nodes or artifacts related to such technology.

**Comment by jbsarrodie** [comment]
In addition, I bet that even with such feature in Archi, you'll still see PMO (or others) redrawing things in PowerPoint (or similar). This is very often motivated by the fact that they want to be able to change the layout and visual to better support their message.

On solution that we are exploring is to create a plugin (or a jArchi script) that would export a view to a Visio or PowerPoint document using real shapes and connectors, not as a single image. Of course this would not be 100% similar to the original ArchiMate view in Archi, but would be similar enough to be usable (and later customized by PMO).

**Comment by gitfirenz** [comment]
Thanks for you quick reply !

I'll try specialization plugin very soon. I have to check how it mix with collaboration plugin.
Exporting to PowerPoint would be nice, you're right.

There is a big challenge in sharing, publishing, socializing our beloved schemas in enterprise. I'm expecting a lot from the next versions (according to the roadmap) :)

**Comment by herve91** [comment]
The specialization plugin will not interfere with the collaboration plugin as it does not change the objects seen by the specialization plugin.

It sets properties on elements and relationships and use those properties to determine if icons and labels should be changed.

Hope this helps

**Comment by Phillipus** [comment]
Closing as no longer valid. Re-open new issue if required,
