### ISSUE TITLE
[Feature Request] Element properties as pre-defined set or by element template

### ISSUE THREAD

**Issue by ruben-s** [archimatetool/archi#430]
Possibly related to #339

Hello,

as also remarked in https://forum.archimatetool.com/index.php?topic=187.0 I think it would be usefull if Archi would provide in a way to define a standard set of properties for an element.

I see 2 possible solutions/scenarios:
a ) Define a set of properties that get applied on an element.
In this case one would need to manage multiple sets of properties.

b) "subtype" an element by means of adding a particular set of properties. This element should not conflict with the archimate standard! It should only add a set of properties that is standard for the subtype.

In my opinion b) is the prefered way as it avoids managing sets of properties.
Different subtypes can have different set of properties.
Note element inheritance migth allow for adding properties from multiple parent elements.

Ideally properties would be flagged as mandatory, in which case a "Validate Model" should indicate which mandatory properties do not have a value.

 #339 is different in that it asks to edit multiple elements 1 one go. But possibly this is a different solution to the desire to add a standard set of properties to an element.

best regards,
  Ruben

**Comment by jbsarrodie** [comment]
Hi,

What you describe is [ArchiMate Language Customization Mecanisms](http://pubs.opengroup.org/architecture/archimate3-doc/chap15.html). This is something that we'd like to do but requires some major work.

For the moment, the best solution (even if not perfect) is to use a mix of Hervé's great plugins: [Form](https://github.com/archi-contribs/form-plugin) and [Specialization](https://github.com/archi-contribs/specialization-plugin).

Regards

**Comment by ruben-s** [comment]
Hello Hervé, Jean-Baptiste,

thank you for the feedback.
I will have a look at the plugins.

Best regards,
 Ruben
