### ISSUE TITLE
Relation name display bug in SVG export

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#434]
### Version of Archi, Operating System
Archi 4.3.1, Windows 10 64bit (10.0.16299.847)

### Expected Behaviour
When exporting to SVG, relation text should be always readable.

### Actual Behaviour
Export to SVG is sometimes not readable, because the line is not interrupted below the text and the text is crossing the line.

### Steps to Reproduce the Behaviour
1. Create two elements
2. Create relation between them
3. Add text to the relation
4. Export to SVG

Problem:

![bug](https://user-images.githubusercontent.com/20066733/51907011-ec35f780-23c5-11e9-8086-c05dfbb8691d.png)

Possible solution:

![solution](https://user-images.githubusercontent.com/20066733/51907012-ec35f780-23c5-11e9-91ad-9336e923f2c6.png)

**Comment by Phillipus** [comment]
The SVG renderer class (third-party code) is a limited in that it does not render the clipping region on objects as it is set in the diagram.

Your possible solution would be difficult to implement. However, a contributor could take a look at the code for a patch.

**Comment by Phillipus** [comment]
Ideally, what we need in the longer term are moveable labels anchored to the connection.

**Comment by Phillipus** [comment]
Clipped connection setting has this covered.
