### ISSUE TITLE
"export/view as image" grayed out

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi#437]
I frequently create PDFs of my views in order to distribute via email
As I do this, I encounter times that the view I want to export has just been opened, but clicking on File/Export shows that the "view as image" option will be grayed out.
Sometimes I can remedy the situation by again double-clicking on the (already open) view.  Sometimes this has no effect and "view as image" remained grayed out.  
Closing and re-opening the file is my go-to remedy.

Archi 4.3.2 build 201901281101
Windows 10

**Comment by Phillipus** [comment]
You have to have a View (diagram) focused for the menu item to be enabled. Click somewhere on the View. You can also use the right-click menu.

**Comment by timhale7** [comment]
any idea why sometimes double-clicking on a view is sufficient to give it focus, and sometimes it's not?  

When I do a publication round of the 19 views, I'm rote clicking... double click to view, file, export, view as image... double click to view, file, export, view as image...

and somewhere in the series, sometimes one of the views will not get the focus after just a double-click.  the majority of them always get the focus on a double-click.

thank you
Tim

**Comment by Phillipus** [comment]
No idea. But if you use the right-click menu item you can be sure it has the focus. If you export to HTML report, all images are exported in the target folder.

**Comment by jbsarrodie** [comment]
> > When I do a publication round of the 19 views, I'm rote clicking
> 
> You could automate this easily with a jArchi script.

Or you could simply use the jasper report feature of Archi and do a selective export by tagging your views...

**Comment by timhale7** [comment]
I was looking at the jarchi capabilities.  I didn't see that it could
manipulate the menu functions.  I will look again.

**Comment by Phillipus** [comment]
It doesn't use menus. It can query the model for all Views and export each as an image.

**Comment by jbsarrodie** [comment]
> I didn't see that it could manipulate the menu functions.

It can't, but you can export selected views to PNG, or even in a single HTML page containing those PNG (that you can then print as PDF from Chrome for example)

**Comment by timhale7** [comment]
Thanks!

**Comment by Phillipus** [comment]
Closing as it's not really a bug.
