### ISSUE TITLE
Wrong version number in 4.3.2

### ISSUE THREAD

**Issue by stigbd** [archimatetool/archi#438]
### Version of Archi, Operating System

Supposedly Version 4.3.2, but "About Archi" says 4.3.1. Build 201901281101. Windows 64 bit.

### Expected Behaviour
After downloading version 4.3.2, version in About Archi should show 4.3.2

### Actual Behaviour
Version shows 4.3.1 and when clicking "Check for New Version", system says there is a new version. 

### Steps to Reproduce the Behaviour
1. Download Archi 4.3.2 from https://www.archimatetool.com/download/ and install
2. Open Help. Click "About Archi"
3. Open Help. Click on "Check for New Version

**Comment by jbsarrodie** [comment]
Mmm, I can reproduce this bug :-(

**Comment by Phillipus** [comment]
Well. That's easy. I forgot to update the internal version number. ;-) Will be fixed in version 4.3.3.

@jbsarrodie Why disable it? Just don't use it? All it is a simple mechanism - small file with the version number in at the root of the website address. If another URL is used then that file would need to be updated too.

**Comment by jbsarrodie** [comment]
>Why disable it? Just don't use it?

If only it would be that simple ;-) User usually try to click everywhere, and if they see that a new version is available some of them will download it, install it and then complain that Archi no more work as expected in their organization.

Thinking about it, I suppose I can update a plugin.xml (or similar) to hide the menu entry. I will do some experiments (nothing urgent though).

**Comment by Phillipus** [comment]
@jbsarrodie I now have a solution for your problem.

I've put the URL of the update file in an internal preference string. If you set this to blank then the menu item will be disabled. You can also set it to something else.

The defaults are:

updateURL=https\://www.archimatetool.com/archi-version.txt
downloadURL=https\://www.archimatetool.com/download

So, find the file:

~/path to user storage/Archi4/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.archimatetool.editor.prefs

And set this to blank (or your own URL):

updateURL=

If you set downloadURL to blank it wont ask if you want to download it. Or you can set your own download page URL.

**Comment by jbsarrodie** [comment]
>I now have a solution for your problem.

You're a genious !

**Comment by Phillipus** [comment]
Fixed in Archi 4.3.3.

@jbsarrodie You might want to note the prefs settings above.

**Comment by jbsarrodie** [comment]
>@jbsarrodie You might want to note the prefs settings above.

I've just tested and it works perfectly. I'm adding it to a wiki page...

**Comment by Phillipus** [comment]
https://github.com/archimatetool/archi/wiki/How-to-disable-the-%22Check-for-Updates...%22-menu-item
