### ISSUE TITLE
XML in .archimate file should be sorted

### ISSUE THREAD

**Issue by aranxas** [archimatetool/archi#440]
### XML in .archimate file should be sorted by ids
In order to facilitate comparison of different version of the .archimate file it would be good if the XML was sorted by the ids. I suppose on the folders the order should be as shown in Archi but for any elements in the folders, the id should be used to sort.

### Actual Behaviour
At the moment the order of elements in the XML file seems to be random. This makes it impossible to compare version of the .archimate file with each other.

### Steps to Reproduce the Behaviour
1. Make a copy of an existing .archimate file.
2. Modify a number of things.
3. After a number of changes, elements will appear in the .archimate file in a different order.

**Comment by Phillipus** [comment]
Can you please explain what you mean?

**Comment by aranxas** [comment]
Sorry, I was too fast with the send button :-).

**Comment by Phillipus** [comment]
Sorry, I'm going to close this as it's not possible.

Archi uses the Eclipse Modelling Framework to write to XML and it has its own way to do this. Also, order of objects in the diagrams denotes the Z-Order of objects.
