### ISSUE TITLE
SQL DB embedded in HTML export doesn't work when a documentation field contains newlines

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#441]
Shame on me!

Related to #400

The escape method used to export information from the model to the Embedded SQL DB doesn't escape newlines and, at best, makes the SQL DB unusable, and at worst makes the default model page (not the whole export though) unreadable.

I have to double check escape methods used by StringTemplate...

JB

**Comment by Phillipus** [comment]
Do you mean "Documentation" field?

Escaping can be tricky, we had problems before now with links and other issues.

**Comment by jbsarrodie** [comment]
> Do you mean "Documentation" field?

Yes, title changed

**Comment by Phillipus** [comment]
Is this a problem with the export of the report or the SQL DB code?

**Comment by jbsarrodie** [comment]
The issue lies in `frame.stg` on lines 46 and 53: they use `description:decodeURL("^c.Documentation;format="xml-encode"^")`. `decodeURL` is a javascript function which "url-decodes" a string that has previously been encoded by StringTemplate using the `format="xml-encode"`.

In this case, `format="xml-encode"` doesn't encode newline, this is the problem. I have to read the StringTemplate doc to see how to to this.

**Comment by Phillipus** [comment]
`format="xml-encode"` was added some years ago because of problems (can't remember what). So we have to be careful of regressions.

**Comment by jbsarrodie** [comment]
> `format="xml-encode"` was added some years ago because of problems (can't remember what). So we have to be careful of regressions.

This is not related. In this case this should be `url-encode` instead of `xml-encode`. This was what was used in previous version but this led to a null string (thus the comment on previous issue about documentation being empty). Using `xml-encode` works.. unless there is some newline, and unfortunately my quick tests has been done with a model containing small documentation fields without newlines.

**Comment by jbsarrodie** [comment]
I've found. In fact in previous version the issue was not cause by `url-encode` but by the fact that I used the field `Description` instead of `Documentation`. So If I use `Documentation` together with `url-encode` it seems to work: I can see the whole documentation content, but the newline gets removed. I will now check the javascript decodeURL() function.

**Comment by jbsarrodie** [comment]
Fixed in [this commit](https://github.com/archimatetool/archi/commit/51b1a3bf052c19942adfb93e5a2756c472af8deb)

Sorry for having introduced this silly bug :-(

**Comment by Phillipus** [comment]
> Sorry for having introduced this silly bug :-(

Well, it happens, doesn't it? ;-) What would software be if it didn't have silly bugs? I'm sure we'll find more silliness...

**Comment by gitPrasun** [comment]
is it the same reason alasql does not return any result for a bigger model( possibly with newline characters in description) but works fine for a smaller model with do documentation ? I am using 4.3.3

**Comment by jbsarrodie** [comment]
Yes, as soon as there's at least one documentation field with a new line it screws the DB. You can fix it be manually replacing .st files by the one in the commit linked before.

**Comment by gitPrasun** [comment]
Wonderful . When is it expcted to release ? ( as new version).
I somehow got by with replacing the CRLF characters for the.archimate with blank. :) . It works also.

btw , I think it would be kind of  cool to allow some `HTML` tag documentation ( instead of simple text) - is it posible in any later version ?

**Comment by nunosilva90** [comment]
Hi,

I have a model with multi-line strings in the element's documentation field. When exporting it to an HTML report and opening it in the browser, I am getting the following error on the browser's console:

SyntaxError: "" string literal contains an unescaped line break

I believe this error is responsible for not being able to execute alasql queries on the model.

Could you please confirm that this is the same issue as the one discussed in this thread?
If so, do you have a date in mind for when the update will be released?

Thank you,
Nuno

**Comment by jbsarrodie** [comment]
>Could you please confirm that this is the same issue as the one discussed in this thread?

I can't confirm anything if you don't provide enough details (like the version of Archi you are using).

This issue is solved in latest version of Archi (still in beta at writing time). So check latest 4.4.0 beta and see if you bug is fixed.

**Comment by jbsarrodie** [comment]
Closing as this is solved in Archi 4.4.0
