### ISSUE TITLE
Edit > Find/Replace doesn't search/work with the text contents of Notes

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#444]
Edit > Find/Replace doesn't search/work with the text contents of Notes

TODO: Enable the Edit > Find/Replace pop-up dialog to also search the text contents of Notes (and enable replacements in the text).

**Comment by Phillipus** [comment]
The current implementation of FInd/Replace only works with the names of objects (it's really a "Rename" operation). Replacing text in notes/stickies requires a different implementation. 

(Good candidate for someone who might want to take a look at it sometime)

**Comment by jbsarrodie** [comment]
Maybe a good candidate for a jArchi script ;-)

**Comment by mwherman2000** [comment]
Here's an example/use case where I'm using Notes to reach a richer/better positioned set of relationship labels *and* I need to have 4 identical copies of this view where only (mostly) the "1.1" needs to be changed to 1.2, 1.3, 1.4, etc.

![image](https://user-images.githubusercontent.com/6101736/53032958-2d518280-342d-11e9-9519-7e071c54eb71.png)

**Comment by Phillipus** [comment]
I've now implemented this for the next version of Archi.

The Find/Replace dialog will also search in the Text Content of Notes, Stickies and Canvas Objects.

Note that all instances of the found text in the Note/Sticky's content will be replaced.

**Comment by Phillipus** [comment]
Fixed in Archi 4.4 beta
