### ISSUE TITLE
HTML doesn't work for Block and stiky

### ISSUE THREAD

**Issue by capelm** [archimatetool/archi#446]
### Version of Archi, Operating System
4.3.3 / Windows10

### Expected Behaviour
If I preview HTML I expect to see the documentation on Block and sticky on a HTML preview as well as the possibility to click on the objects. However this only works for a view I dragged and dropped to the canvas. For other objects it won't work....although it shows tab's for documentation and propertie and so on...

### Actual Behaviour
It seems to be not an HTML object at all. It wo'n provide the documentation and other properties on objects.

### Steps to Reproduce the Behaviour
1. Open Canvas
2. Put a block or stikky on the canvas
3. Put some text in it
4. Publish on HTML
5. Notice the objects are shown, but not as objects with text, documentation and properties

**Comment by Phillipus** [comment]
This is something that has yet to be implemented (if it's possible). Perhaps a good candidate for a contributor.

**Comment by Phillipus** [comment]
@jbsarrodie Just a heads up - I've made a first pass at this in branch "html-report-diagram-objects". Other diagram objects (notes, stickies, etc) are now selectable in Views. But there are no properties, documentation or text displayed in the tabs. Not sure at this stage how that part works.

**Comment by Phillipus** [comment]
Actually, I've just implemented this fully now.

- All other graphical objects can be selected in the diagram (Notes, Stickies, Canvas objects, Groups)
- If any object has Properties these are displayed
- If any objects has Documentation this is displayed in the "Documentation" tab
- If any object has Text Content (Note, Stickies, Canvas Objects) this is displayed in the "Content" tab (same as Documentation tab but says "Content")

Will be in next version.

**Comment by jbsarrodie** [comment]
@phillipus so you've played with stringtemplate and html (bootstrap based) skeleton ;-)

Hope you enjoyed (compared to jasperreport)

Btw I have some enhancements to do on embedded SQL DB (add views and usable html links) ...

**Comment by Phillipus** [comment]
@jbsarrodie Yes, But I've hacked at it before for Archi 4 and refactoring the image map link stuff. ;-)

> Btw I have some enhancements to do on embedded SQL DB (add views and usable html links) ...

I've changed things a bit so maybe branch off my branch? Unless the two branches will be easy to merge?

**Comment by Phillipus** [comment]
@jbsarrodie One problem with StringTemplate is determining the class of an object. It would be nice to test an object's class like:

```^if(object.Class.Name == "ArchimateModel")^```

But instead we query whether the object has a method like:

```^if(object.Purpose)^```

Which can be a problem if classes share methods, and also if the method is removed or renamed.

**Comment by Phillipus** [comment]
> I've changed things a bit so maybe branch off my branch? Unless the two branches will be easy to merge?

@jbsarrodie  No longer an issue as I've merged this into the master branch

**Comment by Phillipus** [comment]
Fixed in Archi 4.4 beta
