### ISSUE TITLE
Bundle with OpenJDK

### ISSUE THREAD

**Issue by danielwagn3r** [archimatetool/archi#447]
Due to the changes in Oracle's Java licensing it should be considered to bundle a decent OpenJKD together with Archi in the future.

AdoptOpenJDK https://adoptopenjdk.net/ could be a good choice since it's already beend adopted by many projects and also supported by a remarkable list of sponsors.

**Comment by Phillipus** [comment]
We're currently using Oracle's JDK 8 because it supports 32-bit and is not subject to Oracle's new licensing. When we do move to a newer JDK then it will need to align with other developments and a later version of Eclipse (which also does not support 32-bit).

So, yes, later versions of Archi will bundle a non-Oracle JDK.

**Comment by akuckartz** [comment]
> We're currently using Oracle's JDK 8 because it supports 32-bit and is not subject to Oracle's new licensing.

AdoptOpenJDK provides 32-bit binaries for Windows. The new Oracle JDK 8 license is very problematic in many commercial settings.

**Comment by Phillipus** [comment]
> The new Oracle JDK 8 license is very problematic in many commercial settings.

I thought that the new Oracle license doesn't apply to JDK 8? Or does it apply to later versions of JDK 8?

**Comment by Phillipus** [comment]
https://www.oracle.com/technetwork/java/javase/overview/faqs-jsp-136696.html

" Java SE 8 remains free of charge for general purpose desktop and server use and is available under the Oracle Binary Code License (BCL) at https://www.oracle.com/javadownload."

**Comment by Phillipus** [comment]
I think to avoid any doubt, the next version of Archi will **not** bundle an Oracle JRE. I shall investigate options.

**Comment by akuckartz** [comment]
This article analyses the situation and alternatives:
https://medium.com/@javachampions/java-is-still-free-c02aef8c9e04

**Comment by Phillipus** [comment]
At this point we need to bundle these JREs:

- Mac 64-bit
- Windows 64-bit
- Windows 32-bit

The Mac JRE needs to operate in the same way as the Oracle one in that it executes the lib/jspawnhelper file.

**Comment by danielwagn3r** [comment]
The problem wird Java SE 8 is that the public support will end soon and further updates will only we available for premier support customers, see https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by Phillipus** [comment]
This can be overcome by deleting the "jre" folder in the Archi installation and either replacing that with your own, or if the "jre" folder is absent then Archi will use the system installed Java.

**Comment by danielwagn3r** [comment]
@Phillipus I know it can be replaced manually, however for users it could be more convenient to have a Java Runtime with proper licensing bundled right from the start. That's all I wanted to point to.

**Comment by Phillipus** [comment]
> Other projects provide a package with and without bundles Java Runtime but this pushes responsibility and complexity to the user.

Sometimes in free and open source projects there has to be some give and take with users.

As I said above:

> I think to avoid any doubt, the next version of Archi will **not** bundle an Oracle JRE. I shall investigate options.

**Comment by Phillipus** [comment]
@jbsarrodie Do you foresee any issues around this?

**Comment by Phillipus** [comment]
- We will, later this year, no longer ship 32-bit versions of Archi as later versions of Eclipse are 64-bit bit only and we need to start using a later version of Eclipse for various reasons. Therefore shipping a 32-bit JRE will no longer be an issue.

- Therefore we should probably bundle JRE 11 with Archi (Linux Archi users will probably be using this anyway as we do not bundle JRE in Linux version)

Given that we will use 64-bit versions is there any advantage to using the AdoptOpenJDK version rather than the OpenJDK version?

**Comment by Phillipus** [comment]
I notice that the OpenJDK 11 does not include nashorn.jar which we need for jArchi. Is it available for OpenJDK?

**Comment by akuckartz** [comment]
nashorn.jar is deprecated in 11 - but that does not imply that it is not included: https://openjdk.java.net/jeps/335

**Comment by jbsarrodie** [comment]
> @jbsarrodie Do you foresee any issues around this?

Well, I find it useful to include a JVM because this makes Archi usable right after installation. I've seem so many software relying on Java that get broken because of people using a JVM which is not the right one.

If there are some good alternative, then I think we should either ship it with Archi, or at least provide direct download links from Archi's download page.

**Comment by Phillipus** [comment]
Here's the issues:

- Java 10 is supported by Eclipse 4.8 (used by current Archi)
- Java 11 is not supported by Eclipse 4.8 (used by current Archi)
- If we ship Java 11 we have to use Eclipse 4.10 or later
- If we use Eclipse 4.10 or later then the installation of Archi plug-ins breaks and we have to use the new Eclipse P2 system

So, we could bundle OpenJDK Java 10 now or wait until all dependencies are resolved and bundle Java 11.

What I'm not clear on is are we affected by Oracle's new licensing if we continue to ship any version of  their Java 8?

**Comment by danielwagn3r** [comment]
Java SE 8 is only affected if using a Oracle JDK 8 build and continued updates are needed. Switching to an OpenJDK 8 build resolves the problem. Hence there is no need to mix this with an upgrade to JDK 11.

The already linked article https://link.medium.com/ymN7mc1kJT describes this pretty clearly.

**Comment by Phillipus** [comment]
OK, it seems that AdoptOpenJDK is the best solution so far. They have bundles for all platforms and versions. Thanks for the heads up on that, :-)

Still being tested...

**Comment by Phillipus** [comment]
I've tested AdoptOpenJDK version 8 on Windows 32-bit, Windows 64-bit, and Mac. It all seems good.

Clearly we have to stop bundling Oracle's JRE with Archi so, unless I find any last minute problems. the next version of Archi will be bundled with AdoptOpenJDK version 8.

This gives us breathing space while we solve the issues of Java 11 and Eclipse.

Thanks for the heads up and advice, everyone. :-)

**Comment by peterprib** [comment]
May be you should be considering https://www.eclipse.org/openj9/  heritage being IBM suggests it is probably best option for eclipse based development along with it now being in the eclipse projects.

**Comment by Phillipus** [comment]
@peterprib Thanks for the suggestion. Following the link, it's actually the AdoptOpenJDK version with a different JVM than "HotSpot". I'll investigate.

**Comment by Phillipus** [comment]
> Other projects provide a package with and without bundles Java Runtime but this pushes responsibility and complexity to the user.

The best I can do is that installing the JRE sub-folder will be an optional part of the installation process when using the Windows Installer versions from the next version. The Mac and portable Windows Zip bundles will still contain the JRE sub-folder, but I have put a note on the download page to say that it can be deleted if required (some compromise is needed here.)

**Comment by Phillipus** [comment]
Fixed in Archi 4.4 beta
