### ISSUE TITLE
Archi plugin localization support

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#448]
Hello gentlemen, i'd like to ask if there are any plans on implementing some universal way to localize archi and plugins?

Smth like shared resource with messages/help/hints and so on, or maybe plugin to be installed as localization thing, or even a kind of "marketplace" to find and manage localizations globaly.

**Comment by Phillipus** [comment]
Hi, some people have already done this for some languages - Russian and French for example.

See https://github.com/smeagol74/archi-ru/releases for example

There are instructions here - https://github.com/archimatetool/archi/wiki/Translating-Archi

**Comment by WatchTh1** [comment]
I'm currently supporting russian langpack) And so is the question about a localization way without recompiling archi plugins itself)

**Comment by Phillipus** [comment]
OK, but then I don't understand your question. What are you asking for? Sorry if I don't understand.

> PS: And in addition editing java/messages.properties is way too complex to follow up frequent releases)

I don't know of any other way to do it.

**Comment by jbsarrodie** [comment]
> PS: And in addition editing java/messages.properties is way too complex to follow up frequent releases)

With @VinceAxe we've thought about a way to "easily" follow up frequent releases: The idea is to:
1. create a git repo to store your work
1. generate the language plugins from Archi and store them in a the "master" branch (this should be your first commit)
1. create a branch off this commit, name it "baseline"
1. do the translation work and store it in "master"
1. publish your work in a release that matches the Archi version
1. when a new version of Archi is published, generate the language plugin agains and commit this on the "baseline"
1. merge "baseline" on "master": this should basically update version number and add new strings to localize, but should not impact existing translation.
1. commit your work, publish, etc.

You can find an attempt [here](https://github.com/VinceAxe/archi-language).

**Comment by WatchTh1** [comment]
> With @VinceAxe we've thought about a way to "easily" follow up frequent releases: The idea is to:
> 
> 1. create a git repo to store your work
> 2. generate the language plugins from Archi and store them in a the "master" branch (this should be your first commit)
> 3. create a branch off this commit, name it "baseline"
> 4. do the translation work and store it in "master"
> 5. publish your work in a release that matches the Archi version
> 6. when a new version of Archi is published, generate the language plugin agains and commit this on the "baseline"
> 7. merge "baseline" on "master": this should basically update version number and add new strings to localize, but should not impact existing translation.
> 8. commit your work, publish, etc.
> 
> You can find an attempt [here](https://github.com/VinceAxe/archi-language).

This is the way I do it currently. I was thinking about some kind of solution to allow lessen technical complexity of localization process to allow:
1. Community members localize Archi plugins if they need to without exp in development
2. Lessen complexity of archi localization maintenance

> I don't know of any other way to do it.
If the only way of localization of Eclipse EPF app is to rebuild plugins and resources - then so be it till time comes)

**Comment by WatchTh1** [comment]
Updated russian language pack up to 4.3.3 (open beta) for commuinity testing. 

I think current issue may be closed.

Link to langpack release:

https://github.com/WatchTh1/Archi-rus-pack/releases/tag/4.3.3
