### ISSUE TITLE
(Feature) Easy cleanup of unused objects and connections

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#449]
Hi,
I'd like to reopen the idea described in issue #342.

For huge models proposed solution is not efficient. The option for batch cleaning of unused objects and relations would be nice and useful feature.

**Comment by jbsarrodie** [comment]
Hi,

This can be done with a jArchi script. @Phillipus even shared one for that some time ago: you can find it [here](https://gist.github.com/Phillipus/64139333f7599c6d499317051e32f60c).

Regards

**Comment by davidsara** [comment]
Thanks for the hint, I will check!
