### ISSUE TITLE
[improvement ]Add HTML report default export path for model.

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#451]
Could it be considered to add report export path into model properties or add smth like "Project settings" to support per model export path setting ? 

It's annoying to select a folder everytime I create an html report on windows system from My computer to C:\data\Projects\...\...\.. and so on)

**Comment by Phillipus** [comment]
All save/open dialogs are system dialogs and should therefore use the last location when opening a new dialaog. Is it not remembering the last location?

**Comment by WatchTh1** [comment]
Nope. Every time it starts from "my computer".

**Comment by Phillipus** [comment]
OK, on Mac it remembers the last location, nit on Windows.

I've changed it so that Directory Dialogs remember the last folder location.

**Comment by WatchTh1** [comment]
Mhm, would you please test it on linux as well (have no such a thing right
at hand)?
Also there is a case with windows/linux network share (attached/unattached)
will it try to open location prior trying to open it (might be usefull to
make OS request authentication credentials)?

вт, 12 мар. 2019 г. в 15:15, Phil Beauvoir <notifications@github.com>:

**Comment by Phillipus** [comment]
>Mhm, would you please test it on linux as well 

Tested for that too. I think it's only Mac that remembers the last folder.

> Also there is a case with windows/linux network share (attached/unattached) will it try to open location prior trying to open it

It checks to see if the folder exists. If not, check if parent folder exists until an existing folder is found. If not, then default. Same for shared folder.

> might be usefull to make OS request authentication credentials

Not possible. It's just a standard Directory dialog.

**Comment by Phillipus** [comment]
I've changed it so that Directory Dialogs remember the last folder location in 4.4
