### ISSUE TITLE
[feature] Concept label per view

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#452]
### Request
Concept label changeability on per view basis.

### Kind of solution but...
There is a plugin:
https://github.com/archi-contribs/specialization-plugin
that provides a "label" propertie to model elements and some behaviour to operate.

### Case that is the reason 
While doing configuration management across projects, there should be model element naming agreement applied to every model element. It supports reporting ability doc autogeneration.

Views are mostly used to negotiate amongst many stakeholders for the 3 main purposes such as: Informing, Deciding and Designing.

Tool such as archimate, especialy with model collaboration plugin, is very useful for all of purposes mentioned but:
 Views using concepts named accordingly to the naming agreement (often with special prefixes/suffixes or kind of functionName_of-Element.smth::Else stuff defined for some kinds of concepts) are inappropriate to be used discussing with non technical stakeholders and this is the reason views has to be aligned accordingly.

**Comment by Phillipus** [comment]
Transferred to Archi issues.

**Comment by WatchTh1** [comment]
> This is not an issue for the model repository plug-in. Did you mean to put this in the main Archi issues?

Yeah, sorry, missed, thanks for your care)
