### ISSUE TITLE
[Feature Request] in search bar show properties in alphabetically order

### ISSUE THREAD

**Issue by larspijnappel** [archimatetool/archi#453]
When using the search bar, would it be possible to show the list of properties in alphabetical order? 
Currently, it is listed in the order as it is stored in the `.archimate` file.

![image](https://user-images.githubusercontent.com/12656725/54278838-d6564d80-4593-11e9-858d-9165d5519eba.png)

BTW, I really appreciate the feature of when selecting the property key(s), the Model Tree is showing the relevant elements on the fly. This is very powerful!

**Comment by Phillipus** [comment]
Seems a good idea. Will be in the next version.

**Comment by Phillipus** [comment]
Fixed in 4.4 beta
