### ISSUE TITLE
[Group Elements in Reports] When an Group element is clicked, the associated Description text is not being displayed

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#454]
### Version of Archi, Operating System

Archi 4.3.0 on Windows 10 Pro

![image](https://user-images.githubusercontent.com/6101736/54559659-26fbeb00-4986-11e9-93c7-fc69af5df703.png)

### Expected Behaviour
When an Group element is clicked in a Report, the associated Description text should be displayed in the lower-left Documentation tab in in the web report.

### Actual Behaviour
When an Group element is clicked in a Report, the associated Description text is not being displayed in the lower-left Documentation tab in in the web report.

### Steps to Reproduce the Behaviour
1. Open the report from here: https://mwherman2000.github.io/indy-arm/
2. Click any view in the left panel
3. Select any Group element in the image of the view
4. Look under the Description tab in the lower-right corner of the web app
5. Nothing shows up (assuming the Description property was given a non-zero length string)

**Comment by Phillipus** [comment]
This is issue #446 

Will be implemented in next version

**Comment by Phillipus** [comment]
Fixed in 4.4 beta
