### ISSUE TITLE
[Feature Request] Add an option to use less formal symbols for the ArchiMate elements...

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#455]
Add an option to use less formal symbols for the ArchiMate elements.  ...for example, ...

![image](https://user-images.githubusercontent.com/6101736/54610545-d4b8d980-4a1a-11e9-886c-fead710273d2.png)

**Comment by mwherman2000** [comment]
Bizzdesign Studio has a similar Display Level capability available for their BPMN diagrams...

![image](https://user-images.githubusercontent.com/6101736/54612503-b0f79280-4a1e-11e9-8159-8f4d0e8fd9b7.png)

**Comment by Phillipus** [comment]
Alternate figures and icons have been requested in other issues here. This requires a lot of development work to support this. Perhaps this is something  could be looked at further down the line.

**Comment by herve91** [comment]
It won't look like Bizzdesign but you may try the [specialization plugin](https://github.com/archi-contribs/specialization-plugin).
