### ISSUE TITLE
[Feature Request] When I paste a copy of an element, I want to be warned if the copied element has metadata

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#456]
## Context 

I have a Business Role element in my model called Thing that has a Description string value (plus potentially other metadata). When I rapidly copy&pasted this element in a view, of course, Archi copied not only the base element but the value of the Description property as well.  Technically, this is correct behavior but it leads to erroneous documentation/metadata being propagated throughout the model ...not good.

## Requested Change

If an element has (non-default) property values "I can't see", I'd like an option (a pop-up dialog box) to warn me when this is the case during a paste operation.  The pop-up can have a check-box to uncheck if you don't want to see these confirmations.  The check-boxes would be scoped to an individual model ...not global across models,

**Comment by Phillipus** [comment]
Not a good idea to have this kind of thing on Copy/Paste workflow, and not something that I would implement.
