### ISSUE TITLE
[Bug][Linux] SWTError: No more handles on Ubuntu 18

### ISSUE THREAD

**Issue by joelvim** [archimatetool/archi#462]
### Version of Archi, Operating System
4.4.0-beta3 but also observed on 4.3.1 and 4.3.3
Only observed on linux (Ubuntu 18.10 and Ubuntu 18.04, seems to be working on older Ubuntu)

### Expected Behaviour
View tabs are displayed normally.

### Actual Behaviour
View tab are always empty, only the close button is displayed. I used Archi on Windows without problem, I only have this problem on Linux, seems to be related to SWT.

### Steps to Reproduce the Behaviour
1. Open Archi
2. Open or create a view

### Attached files
* configuration [configuration.txt](https://github.com/archimatetool/archi/files/3034200/configuration.txt)
* Error log [log.txt](https://github.com/archimatetool/archi/files/3034197/log.txt)
* screenshot ![archi](https://user-images.githubusercontent.com/1035781/55408022-784bd300-555f-11e9-9db5-ea207357f06d.png)

**Comment by jbsarrodie** [comment]
Hi,

I've never had this issue on Linux but I'm using an older version of elementary OS (based on previous Ubuntu LTS).

Can you provide exact version of your JVM and GTK ?

**Comment by joelvim** [comment]
Indeed my colleagues using older versions of ubuntu don't seem to face this issue.

My jdk : 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.10.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

GTK : 3.24.4-0ubuntu1

**Comment by Phillipus** [comment]
Looking at the error log we see this:

```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:180)
	at org.eclipse.draw2d.Cursors.<clinit>(Cursors.java:195)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite$ButtonCanvas.init(FlyoutPaletteComposite.java:1214)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite$ButtonCanvas.<init>(FlyoutPaletteComposite.java:1180)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite.createFlyoutControlButton(FlyoutPaletteComposite.java:265)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite.access$4(FlyoutPaletteComposite.java:264)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite$Sash.<init>(FlyoutPaletteComposite.java:745)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite.createSash(FlyoutPaletteComposite.java:291)
	at org.eclipse.gef.ui.palette.FlyoutPaletteComposite.<init>(FlyoutPaletteComposite.java:197)
	at org.eclipse.gef.ui.parts.GraphicalEditorWithFlyoutPalette.createPaletteComposite(GraphicalEditorWithFlyoutPalette.java:94)
	at org.eclipse.gef.ui.parts.GraphicalEditorWithFlyoutPalette.createPartControl(GraphicalEditorWithFlyoutPalette.java:73)
	at com.archimatetool.editor.diagram.AbstractDiagramEditor.createPartControl(AbstractDiagramEditor.java:259)
```

This will certainly mean that the editor (View) can not be created.

`org.eclipse.swt.SWTError: No more handles` can be a problem with some GTK versions. Time to Google this one...

**Comment by Phillipus** [comment]
Any clues here? https://bugs.eclipse.org/bugs/show_bug.cgi?id=542675

**Comment by joelvim** [comment]
Note that I don't have this problem with eclipse oxygen. I tried starting with GTK_IM_MODULE=ibus but it didn't solve my problem.

**Comment by joelvim** [comment]
SWT_GTK3=0 fixed the problem \o/

**Comment by joelvim** [comment]
Thank you very much for your support!

**Comment by Phillipus** [comment]
> SWT_GTK3=0 fixed the problem

I was going to suggest that. But...you may encounter other graphical issues with this. GTK 2 is deprecated. You might see missing menu items for example. Suggest Googling this a bit more to see if it can be approached in a different way. Not sure if different version of GTK is the answer

**Comment by joelvim** [comment]
What's strange is that I don't have this problem with Eclipse Oxygen and Eclipse 2019-03.

**Comment by Phillipus** [comment]
Eclipse 2019-03 will have later version SWT. But yes, strange about Oxygen because that's what Archi is built on. Does eclipse.ini have any GTK setting in it?

See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=526357

**Comment by joelvim** [comment]
No sign of gtk version in eclipse.ini, only a `launcher.library` that I tried to set on Arch.ini with the corresponding value without success.

**Comment by Phillipus** [comment]
No, the launcher shouldn't be changed. The issue is Eclipse SWT + GTK 3 versions. Hard to find out what works and doesn't work. I use Linux Mint 19.1 (based on Ubuntu 18.04) and that works OK.

**Comment by joelvim** [comment]
Maybe my Ubuntu installation has some libs that don't play well with Archi but doesn't mess with eclipse.

**Comment by Phillipus** [comment]
Do the other parts of Archi work OK? Trees, tables, widgets, browser. It may be that the GEF Palette is causing it via Draw2d allocating a cursor.

**Comment by joelvim** [comment]
The other views of the perspective seemed ok: the model tree, the properties table view, the welcome view and the help.

**Comment by Phillipus** [comment]
I installed a fresh copy of Ubuntu 18.10 and all updates. And Archi was working OK for me.

Do you use Unity or MATE desktop? Could it be something like this causing it?

At this point, I can't help with any more testing on this. This has to be something that Linux users try to solve. Perhaps it's GTK version, a theme, or desktop version. Perhaps a conflict with SWT.

Linux users - heal thyself! ;-)

**Comment by Phillipus** [comment]
My GTK: libgtk-3-0:amd 3.24.4-0ubun

**Comment by joelvim** [comment]
My install is quite old, and has come through many updates. I suspect an old library remaining from the old ages causing trouble with SWT.

**Comment by joelvim** [comment]
Whatever, with the env var trick explained upper, it works, so it's ok for me.

**Comment by WatchTh1** [comment]
Running 18.04 + Plasma + Oracle JDK (latest). 

Works just fine.

**Comment by cbredesen** [comment]
> `export SWT_GTK3=0` in Archi-Ubuntu.sh fixed the problem \o/

This fixed me on Fedora 29 as well. I actually made an Archi-Fedora.sh that omits the Ubuntu menu script and adds the GTK3 variable. FINALLY! \o/

**Comment by alecarlosjesus** [comment]
SWT_GTK3=0 fixed my problem to!
Thx!!!
