### ISSUE TITLE
Check for new version - No proxy definition

### ISSUE THREAD

**Issue by jyl13** [archimatetool/archi#463]
Hello 
There is no way to configure proxy as it is possible in Eclipse, so check for new version does ot work.
Could it possible include it ?

Regards

Jean-Yves Longueville

**Comment by Phillipus** [comment]
I believe @jbsarrodie has seen this problem too. We have Proxy support in the Collaboration plug-in, perhaps we could push this up to the main Archi code as general proxy settings at some point.

**Comment by herve91** [comment]
Hi,

You may add the following lines to the **archi.ini** file

> -Dhttp.proxyHost=_\<proxy name or IP address\>_
-Dhttp.proxyPort=_\<proxy port\>_
-Dhttp.proxyUser=_\<username if credentials are required\>_
-Dhttp.proxyPassword=_\<password if credentials are required\>_
-Dhttps.proxyHost=_\<proxy name or IP address\>_
-Dhttps.proxyPort=_\<proxy port\>_
-Dhttps.proxyUser=_\<username if credentials are required\>_
-Dhttps.proxyPassword=_\<password if credentials are required\>_
-Djdk.http.auth.tunneling.disabledSchemes=
-Djdk.http.auth.proxying.disabledSchemes=

Best regards
Hervé

**Comment by Phillipus** [comment]
Thanks Hervé.

Does it actually work with checking for new version from Archi, though?

Does it conflict with Model Collaboration Proxy settings?

**Comment by herve91** [comment]
In fact, the INI lines just activate the proxy mechanism if the Eclipse framework.

As I did not install your Collaboration plugin, I can only suppose. Per my understanding, you bypass the standard proxy mechanism by providing the proxy configuration your get from the plugin parameters. So it shouldn't interfere. But it should be tested.

**Comment by herve91** [comment]
And, yes, it works for checking new versions of Archi :-)

**Comment by Phillipus** [comment]
Thanks! :-)

Added to wiki - https://github.com/archimatetool/archi/wiki/Proxy-Settings

**Comment by jyl13** [comment]
Hello
Still some problem
[cid:image001.png@01D4EBCF.82A16580]
For info I  am using Archi 4.3.1.

Regards

[Description: Description: Description: Description: Description: Description: Description: logo_big5] [cid:image005.png@01D4EBCF.82A8B880]

Jean-Yves LONGUEVILLE | TINA: 043 6129 | Tel: +33 442 686 129 | Mobile: +33 637 178 476
STMicroelectronics | DIT Manufacturing & Quality | Technology Architect

ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world

**Comment by Phillipus** [comment]
@jyl13 Your message has not shown the error.

I would add that these proxy settings are "unsupported" so please don't be offended if I can't spend time on this issue.

@herve91 Hervé, could you assist if possible.

BTW Archi 4.4 is available,

**Comment by jyl13** [comment]
No problem. The error message was "Error connecting to srever".
What is the version on which it is working and tested? 4.4?
Is it supported with the last collaborator plugin? If yes I will upgrade to 4.4 …

[Description: Description: Description: Description: Description: Description: Description: logo_big5] [cid:image002.png@01D4EBD1.13DCD9C0]

Jean-Yves LONGUEVILLE | TINA: 043 6129 | Tel: +33 442 686 129 | Mobile: +33 637 178 476
STMicroelectronics | DIT Manufacturing & Quality | Technology Architect

ST online: www.st.com<http://www.st.com/> | Follow us on twitter: @st_world

**Comment by Phillipus** [comment]
> What is the version on which it is working and tested? 4.4?

As I said, those archi.ini proxy settings are not supported, and seem to work for @herve91 

The proxy settings for the Collaboration plug-in are only for connecting to gut repositories, not the "Check for update" feature.

**Comment by Phillipus** [comment]
I've removed the wiki page with those Proxy settings as my tests indicate that it is not working in all cases. It also depends on if the Collaboration plug-in uses a Proxy and if it has been initialised or not.

Needs more research.

**Comment by Phillipus** [comment]
A workaround may be to set the Proxy settings in the Collaboration plugin, perform an action the requires a connection and then do a "Check for New Version" as I think this will set the proxy for the Archi session.

However, proxy settings and testing is one of those features where we could use some help in coding. I only can test with a local proxy server (CCProxy) and it doesn't really cover all cases.

**Comment by herve91** [comment]
The "Error connecting to server" error message indicates that Archi cannot check if there is a new version available, thus that Archi cannot go through your proxy. It happens to me when my configuration is wrong (ie every month when my proxy credentials expire)

Unfortunately, I cannot say if this is related to the Collaboration plugin as I do not use it, but here is few things that might be checked:
- check for any syntax error in your configuration
- check you updated the right archi.ini file (it happened once I updated the ini file in one folder, and my shortcut launched Archi from another folder)
- check there is no space around the equal signs
- check your password do not contain special chars (space, quote, backslash, ...) 
- remove the proxyUser and proxyPassword lines if your firewall does not require credentials

Also, I haven't upgraded my plateform to Archi 4.4 yet and therefore haven't try if the OpenJDK bundles impact the proxy parameters.

**Comment by Phillipus** [comment]
Proxy settings will be supported in Archi 5.
