### ISSUE TITLE
[Feature Request] (optional) warning when renaming a concept or changing source/target of a relationship

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#464]
Asof today, deleting a concept raises a warning if the concept is used in a(nother) view. This is helpful to avoid unwanted impact on views.

It would be useful to have a similar (but optional) warning raised when a concept is renamed or when source or target of a relationship are changed. In the later case, it often leads to relationships removed from views without notice.

**Comment by jbsarrodie** [comment]
@Phillipus Do you think we could solve this for 4.7 ?

**Comment by Phillipus** [comment]
Relationship ends was already fixed in #558 - unless this one is different?

**Comment by jbsarrodie** [comment]
> Relationship ends was already fixed in #558 - unless this one is different?

Good. I was almost sure it was solved (and I don't have access to Archi 4.7 to test it) but I was not able to find the issue, only this one.

Thank you!
