### ISSUE TITLE
[Feature Request] Enhanced Code : Event Based System

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#465]
It might be helpful and interesting to consider all changes inside the model as Event.

Related Issue : 
- #464 
- Feature mentioned inside the #464 about the alert when an object is deleted 
- Help with the Model Repository plugin 
-- https://github.com/archimatetool/archi-modelrepository-plugin/issues/98
-- https://github.com/archimatetool/archi-modelrepository-plugin/issues/99
Probably many other things

It has a lot of impact

**Comment by Phillipus** [comment]
The code already is event based and each change to the model is a model event. But the code can't decide what has impact or not. Impact depends on circumstances. Changes can only be surfaced to the user by UI code and code that analyses the model. 

Example #464 - when there is a reconnection, then the code iterates through every diagram to look for instances of the source and target objects and tries to reconnect them. If one or other is missing then the connection is removed from the diagram so it is not orphaned. This will in fact lead to several events that all go on the undo stack. Whether event driven or not, that code had to be manually constructed to handle that.

So, in those issues, event driven or not makes no difference.

**Comment by jbsarrodie** [comment]
@VinceAxe Might be good for you to become familiar with the codebase and especially EMF. This should help you understand how all this works and why such suggestion by itself doesn't solve anything.
