### ISSUE TITLE
[Feature Request] Dark theme

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi#467]
Hello, is it possible to somehow get dark theme? Controls and tabs may stay like they are, but I really appreciate to change the workbench white to dark for the night shifts :)

I've already discovered e4_basestyle.css, but not sure, which class should be changed.

Thanks!
David

**Comment by Phillipus** [comment]
Yes, you can create your own themes with CSS by editing those files.

See https://www.vogella.com/tutorials/Eclipse4CSS/article.html

**Comment by davidsara** [comment]
Thanks I will check.

**Comment by Phillipus** [comment]
The dark theme will be in the next version of Archi (4.6).

**Comment by davidsara** [comment]
Cool! Looking forward.
