### ISSUE TITLE
Error message on startup

### ISSUE THREAD

**Issue by vv3** [archimatetool/archi#468]
Upon startup I get a dialog box saying:

"An error has occured. See the log file ..../.archi4/.metadata/.log" 

I have attached the log file. 

### Version of Archi, Operating System
I am running Ubuntu 18.04.2. The error message appears both on Archi 4.3 and Archi 4.4.0

### Expected Behaviour
The application should start

### Actual Behaviour
An error dialog appears, and then the application stops

[log.LOG](https://github.com/archimatetool/archi/files/3106460/log.LOG)

**Comment by Phillipus** [comment]
Archi 4.4 doesn't support Java 11. If you can install Java 8 that would do it.

From the download page:

"Requires Java 8 or 10 (64-bit) installed."

(We will support later versions of Java at some point, but this requires building Archi on later versions of Eclipse which bring in a new set of problems)

**Comment by vv3** [comment]
Ah, that explains it. Java 8 is already installed in my system, so it was only a matter of preferring this version:
`sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`

**Comment by bosskopp** [comment]
You can edit Archi-Ubuntu.sh to change Java version to 8 before starting Archi and set it back to 11 afterwards:
```
#!/bin/bash
echo "Setting Java Version to 8"
sudo update-java-alternatives -s java-8-oracle
echo "Starting Archi"
export UBUNTU_MENUPROXY=0
dir=$(dirname $(readlink -m $0))
$dir/Archi
echo "Setting Java Version to 11"
sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
```

To get Java-names, use `sudo update-java-alternatives -l`

**Comment by Phillipus** [comment]
Next build of Archi 64-bit will include a bundled Java 8.
