### ISSUE TITLE
Colours in palette and tree are no longer correct in 4.4

### ISSUE THREAD

**Issue by PinoEire** [archimatetool/archi#469]
### Version of Archi, Operating System
Windows 10

### Expected Behaviour
Loaded the colours preferences as usual. The palette and tree should show the **new** colour scheme.

### Actual Behaviour
Loaded the colours preferences as usual. The palette and tree should show the **default** colour scheme.

### Steps to Reproduce the Behaviour
1. Open Archi
2. Import the preference file (Mastering Archimate prefs from the website)
3. See the above behaviour.

**Comment by Phillipus** [comment]
Setting the colours in the icons of the tree and palette was removed in version 4.3.1. This is because the icons for higher resolution monitors contain shaded colours and changing pixel colours doesn't work properly.
