### ISSUE TITLE
HTML report doesn't export elements consistently

### ISSUE THREAD

**Issue by steve-vincent** [archimatetool/archi#470]
### Version of Archi, Operating System
Archi 4.3

### Expected Behaviour

HTML files in elements folder would be named by element IDs

### Actual Behaviour

Some html files begin with "id-" prefix, and some strip the "id-" prefix. I can't link to these documentation files, without being able to rely on naming convention, and I can't figure out logic why naming isn't consistent.

### Steps to Reproduce the Behaviour
1. Generate HTML report
2. Look in elements folder
3. See how some files start with "id-" and some don't

**Comment by jbsarrodie** [comment]
Hi,

This is not related to HTML export. I assume you imported a model previously exported to the exchange file format (which contains 'id' prefix) and added new concepts in it.

Regards, 

JB

**Comment by Phillipus** [comment]
As IDs are internal (non API) the format of them could vary. Importing via CSV could also use different format IDs.

**Comment by steve-vincent** [comment]
Yes thanks Phillipus, that clarifies. I see that exporting to XML changes the IDs (prefixes with "id-" for numeric). I can instead use CSV to reliably get names of HTML files. 

However, I need to process views/diagram data... which is only in XML.

I think the only way to do that will be to use CSV, append "id-" for anything numeric.... and use some kind of lookup table.

**Comment by jbsarrodie** [comment]
>However, I need to process views/diagram data... which is only in XML.

Maybe you could use [jArchi](https://github.com/archimatetool/archi-scripting-plugin/) and create some scripts ?

**Comment by steve-vincent** [comment]
Yes - i think I'll figure something out.

Thanks for the help!
