### ISSUE TITLE
Archimatetool.com Website Unreachable

### ISSUE THREAD

**Issue by PaulComis** [archimatetool/archi#472]
http://www.archimatetool.com is re-directing to 127.0.0.1, giving an "unreachable" error:

"Hmmm... cannot reach this page
Try this
Make sure that you’ve got the right web address: http://127.0.0.1"

Replicated on multiple internet connections and locations.

**Comment by Phillipus** [comment]
Hi, thanks for report. I'm in contact with the ISP about it...

**Comment by Phillipus** [comment]
Seems to be OK now. Thanks for reporting it.

**Comment by PaulComis** [comment]
You're welcome...glad its back! About to induct a few newbies to EA Modelling!
