### ISSUE TITLE
[Feature Request] copy/paste the list of selected elements from models tree to external tool

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#473]
Use case:
I mark some services with " !label " label in the element title (or in a property). The amount of such elements is small comparing even within the large model. 

I want to list all such services from the model into the sheet. 

Current workarounds:
If there are only a few of the filtered elements -> retype into the sheet.
If that is not convenient -> export model to csv and filter out within the sheet.

Desired approach:

Steps:
Filter and select 1 or more elements. CTRL-C. Switch to Excel (or any other sheet or text based tool). CTRL-V would paste the list each on a new line. 

### Version of Archi, Operating System
4.4 WIN 10

**Comment by Phillipus** [comment]
Sorry, this is too specialist.
