### ISSUE TITLE
[Bug] Links Area in Hi-res screen generated HTML report are not aligned with pictures

### ISSUE THREAD

**Issue by rvelter** [archimatetool/archi#475]
### Version of Archi, Operating System

Archi 4.4.0
Windows 10 64bit 1903

### Expected Behaviour

To Click on object for properties in Hi-res HTML report
To Click on View Object to move to another view in Hi-res HTML report
 
### Actual Behaviour

Links Area within Hi-res HTML report are not aligned with objects (the clikable areas are here but not at the same scale of the picture)
With the 2x size Report option Checked or unchecked.

### Steps to Reproduce the Behaviour
1. Insert views object (or just any object) in a view. Save
2. Export HTML with a Hi-Res screen.
3. Open the report on hi-Res screen and try to click on objects

**Comment by Phillipus** [comment]
I tested this and it's working for me. Assuming you mean a View link box on a diagram?

**Comment by rvelter** [comment]
Yes. A View link box on a diagram.
After investigation, it seems that all links area are "offset" (like the old bug for 4K screens with links HTML report)

**Comment by rvelter** [comment]
Old bug  #328

**Comment by Phillipus** [comment]
Could you amend this bug's title and description? Or close this one and open a new bug report?

**Comment by Phillipus** [comment]
There is also a new Preference, can you see how this is set:

![Image 1](https://user-images.githubusercontent.com/600504/58195072-05d5b480-7cbf-11e9-952e-0db6549868e6.png)

**Comment by rvelter** [comment]
> 
> 
> Could you amend this bug's title and description? Or close this one and open a new bug report?

Of course, i'll edit

**Comment by rvelter** [comment]
> 
> 
> There is also a new Preference, can you see how this is set:
> 
> ![Image 1](https://user-images.githubusercontent.com/600504/58195072-05d5b480-7cbf-11e9-952e-0db6549868e6.png)

It was unchecked.
If i check it, the offset is higher on my 4K screen.

**Comment by Phillipus** [comment]
Did this used to work for you? Was it on a different machine and screen?

This is not easy for me to debug because I don't have 4k screen so I'm having to guess. It would certainly help if someone with such a setup could help on this with the code.

**Comment by rvelter** [comment]
Phil, 
I’m living in France and the 4K screen is at work.
Tomorrow i’ll test 6 more scenarios.
Generation on 1K with checkbox unchecked and consulting of report on 1K
Generation on 1K with checkbox checked and consulting of report on 1K
Generation on 1K with checkbox unchecked and consulting of report on 4K
Generation on 1K with checkbox checked and consulting of report on 4K
Generation on 4K with checkbox unchecked and consulting of report on 1K
Generation on 4K with checkbox checked and consulting of report on 1K
Generation on 4K with checkbox unchecked and consulting of report on 4K (bug)
Generation on 4K with checkbox checked and consulting of report on 4K (bug)

With the same machine.

**Comment by rvelter** [comment]
> Did this used to work for you? Was it on a different machine and screen?
> 
> This is not easy for me to debug because I don't have 4k screen so I'm having to guess. It would certainly help if someone with such a setup could help on this with the code.

Never used with 4.4.0

**Comment by Phillipus** [comment]
Is the scaling in Windows showing as 200% or 400% or...?

**Comment by rvelter** [comment]
> Is the scaling in Windows showing as 200% or 400% or...?

150% but i cannot verify and test at this time

**Comment by Phillipus** [comment]
If it is 150% that might account for it.

**Comment by Phillipus** [comment]
When you are ready, could you try this build and ensure that the preference option is ticked:

https://www.archimatetool.com/downloads/beta/Archi-Win64-4.4.1.zip

My suspicion is that in the older version the image size and hitbox calculation used the device scaling factor but the new code uses 200%. The beta build uses the old method.

**Comment by rvelter** [comment]
> When you are ready, could you try this build and ensure that the preference option is ticked:
> 
> https://www.archimatetool.com/downloads/beta/Archi-Win64-4.4.1.zip
> 
> My suspicion is that in the older version the image size and hitbox calculation used the device scaling factor but the new code uses 200%. The beta build uses the old method.

I will try tomorrow morning here.  Thx.

**Comment by Phillipus** [comment]
I'm not sure 150% scaling will affect things. From what I can make out, scaling in Eclipse and Archi is either 100% or 200%.

**Comment by Phillipus** [comment]
Can you remember a version of Archi where this worked with the 4k screen?

**Comment by rvelter** [comment]
Hi, sorry for silence.
No. But if you have old exe somewhere i can test to know when it works and when it doesn't

**Comment by Phillipus** [comment]
You could try the beta:

https://www.archimatetool.com/beta/
