### ISSUE TITLE
org.eclipse.swt.SWTError: No more handles #27

### ISSUE THREAD

**Issue by bourboule** [archimatetool/archi#476]
### Version of Archi, Operating System

Archi 4.4.0
Build 201904031131
Plugin org.archicontribs.form_v1.9.1.jar [https://github.com/archi-contribs/form-plugin/blob/master/org.archicontribs.form_v1.9.1.jar](url)

### Expected Behaviour

When using Form plugin, the form windows should be setup with element properties and usable through mouse and keyboard.

### Actual Behaviour

This issue is already explained in form plugin issues. Herve ask me to open an Archi issue too: [https://github.com/archi-contribs/form-plugin/issues/27](url)

[handle.archimate.txt](https://github.com/archimatetool/archi/files/3223788/handle.archimate.txt)
[handle.conf.txt](https://github.com/archimatetool/archi/files/3223789/handle.conf.txt)

After few seconds of form building process, I can't no more use Archi.
The form windows still displayed and can't be closed. Icon "Please wait, we are creating the form..." still displayed inside the window.
I have to kill the process Archi.exe.

Here is the error log:

`!ENTRY org.eclipse.ui 4 0 2019-05-23 14:02:16.006 !MESSAGE Unhandled event loop exception !STACK 0 org.eclipse.swt.SWTError: No more handles at org.eclipse.swt.SWT.error(SWT.java:4559) at org.eclipse.swt.SWT.error(SWT.java:4448) at org.eclipse.swt.SWT.error(SWT.java:4419) at org.eclipse.swt.widgets.Widget.error(Widget.java:482) at org.eclipse.swt.widgets.Control.createHandle(Control.java:718) at org.eclipse.swt.widgets.Control.createWidget(Control.java:758) at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:151) at org.eclipse.swt.widgets.Control.<init>(Control.java:112) at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:82) at org.eclipse.swt.widgets.List.<init>(List.java:83) at org.eclipse.swt.custom.CCombo.createPopup(CCombo.java:478) at org.eclipse.swt.custom.CCombo.<init>(CCombo.java:158) at org.archicontribs.form.FormJsonParser.getCells(FormJsonParser.java:1443) at org.archicontribs.form.FormJsonParser.createLine(FormJsonParser.java:1047) at org.archicontribs.form.FormJsonParser.createLine(FormJsonParser.java:1064) at org.archicontribs.form.FormJsonParser.createLine(FormJsonParser.java:1064) at org.archicontribs.form.FormJsonParser.createLine(FormJsonParser.java:1064) at org.archicontribs.form.FormDialog.createControl(FormDialog.java:1044) at org.archicontribs.form.FormDialog.<init>(FormDialog.java:306) at org.archicontribs.form.menu.FormEditorHandler.execute(FormEditorHandler.java:60) at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291) at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55) at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305) at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239) at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132) at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494) at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487) at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210) at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:390) at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:820) at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:797) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079) at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039) at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153) at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336) at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594) at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148) at com.archimatetool.editor.Application.start(Application.java:82) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590) at org.eclipse.equinox.launcher.Main.run(Main.java:1499)`

Here is the end of plugin log file:

`2019-05-23 14:11:10 TRACE 67:FormVariable - getting refered EObject from variable "${property:Comment}" (source object = DiagramModelArchimateObject:"Indus PER BSC FE TBD"(fd0dc4de-1f3e-46c9-a8a2-4402f97d00ee)) 2019-05-23 14:11:10 TRACE 108:FormVariable - --> itself 2019-05-23 14:11:10 DEBUG 1062:FormJsonParser - Indus PER BSC FE TBD is a DiagramModelContainer : getting children 2019-05-23 14:11:21 DEBUG 1642:FormDialog - Cancel button selected by user.`

I think I reached some limits (org.eclipse.swt.SWTError: No more handles).

I have a work around: split this view in many views with less elements inside, but if I could avoid, it'll be great. This view has a special name which is used by a script to extract properties and node from XML files.

I have tested without solving the issue:
 - to increase max memorysize in archi.ini to 2GB, 4GB
 - use 32 or 64 bit version
 - remove specialization and modelrepository plugins

### Steps to Reproduce the Behaviour
1. Install form plugin: org.archicontribs.form_v1.9.1.jar
2. Configure form with parameter file handle.conf (in attachment)
3. Open model file handle.archimate (in attachment)
4. Click on contextual menu Test Handle

**Comment by Phillipus** [comment]
Actually, Herve said this:

You may as well open a case in Archi forum to get help from the whole Archi comunity:(https://forum.archimatetool.com/index.php)

So I'm going to close this issue here

**Comment by bourboule** [comment]
Ok. Sorry for this misunderstanding.

**Comment by Phillipus** [comment]
No problem!  :-)
