### ISSUE TITLE
[BUG] Clicking on Properties panel "forgets" selected element (Visualiser?)

### ISSUE THREAD

**Issue by GuyWicks** [archimatetool/archi#483]
### Version of Archi, Operating System
Reproducable in 4.3.0, 4.3.3 and 4.4.0 - Windows 

### Expected Behaviour
When you click (selected) a concept/element and then click on the properties windows properties sub-tab (or other sub-tab), you should see the selected elements properties.

### Actual Behaviour
**If you have the properties and visualipanel in a separate (detached) window**, you can click on the element, click on the property sub-tab and the properties window will change to show properties of the VIEW, not the element. You have to click on the element again and the intended property tab. 

### Steps to Reproduce the Behaviour
From start up:
1. open a model
2. open the "visualiser" window and drag it into a new separate window 
3. open the "properties" window and drag it into the same window as the visualiser

![image](https://user-images.githubusercontent.com/12052236/58950741-5fda7d80-8787-11e9-9881-e2662a31cb4b.png)

4. Click on the visualiser (anywhere)
5. Click on the element you want to view properties for: (The property window DOES change)

![image](https://user-images.githubusercontent.com/12052236/58951168-5867a400-8788-11e9-86e8-43269faf85a2.png)

![image](https://user-images.githubusercontent.com/12052236/58951111-3cfc9900-8788-11e9-9978-d131e848a607.png)

6. Click on a sub tab (any). The "focus" of the properties window changes to the VIEW

![image](https://user-images.githubusercontent.com/12052236/58951041-10488180-8788-11e9-9537-dacd80cc215d.png)

**I would expect the focus to remain on the "[Label] Service Criticality: Degrated" element.**

**Comment by GuyWicks** [comment]
@Phillipus 

I will admit, sometimes it can be hard to reproduce...  Spent over an hour trying to create a fully 100% reproducible sequence - and didn't fully achieve it.  But - it does happen and it's bleeding annoying when it does it! 

It seems particularly sensitive to the way you have the window layout.  I have two large screens and drag the "auxiliary" windows to the right with the model window on the left. YMMV

**Comment by Phillipus** [comment]
It may be:

- An edge case relating to focus of windows
- Related to having two screens
- An Eclipse bug

I followed your steps and coudn't reproduce the issue. I use only one screen. If we could get 100% reprodicible sequence I'll be able to take a look at it.

**Comment by Phillipus** [comment]
I notice you are using Herve's Specialisation plug-in - please try without that installed, it might be doing something with the Properties tab.

**Comment by GuyWicks** [comment]
re: specialisation plug-in - I've tried this in several configurations and versions - my newest Archi 4.4.0 does not have this enabled :)

I'll try to improve on the reproduction steps.

**Comment by Phillipus** [comment]
OK.

At stage 6, "Click on a sub tab (any). The "focus" of the properties window changes to the VIEW", what's selected on the diagram view? Is the object deselected?

**Comment by Phillipus** [comment]
Also, what is the selection in the Models Tree? Is it the View in question?

Something is putting the focus on the View, which may the diagram tab or the View node in the tree.

**Comment by GuyWicks** [comment]
The element is still (looks) selected in the view.
The selection in the model tree goes BACK to the view.
Video - https://youtu.be/5TPgz367_RA

**Comment by Phillipus** [comment]
The video helps.

One piece of important information - "Link to View" is enabled in the toolbar of the Models Tree. If this is off the problem does not occur. Why this happens needs to be investigated. It may be a side-effect of "Link to View".

**Comment by GuyWicks** [comment]
Excellent.   Not going mad!
It also happens with the scripts page too.

**Comment by Phillipus** [comment]
It seems to only do this when the Properties and Visualiser tabs in a detached window. At this point I'd put it down as an Eclipse quirk. Needs further investigation.

**Comment by Phillipus** [comment]
Sorry I closed this issue by mistake (the "Close and comment" button is too big!)

**Comment by Phillipus** [comment]
So, yes, I figured out what was going on - the editor part was being selected which then selected it in the tree which then selected that in the properties tab. Complicated. Anyway, I've patched it so as to not select the same editor. Tests seem to indicate that this will fix the issue.

Will be in the next release of Archi (not sure when that is, but not too long). So we'll keep this issue open until it's confirmed to be fixed.

**Comment by Phillipus** [comment]
The workaround in the meantime is to **not** do this sequence of events if the Properties Tab and Visualiser Tab are detached in the same window:

1. Put focus on Visualiser
2. Put focus on an object in a diagram View
3. Put focus on Properties tab

Switching between (2) and (3) or (1) and (3) is OK.

**Comment by Phillipus** [comment]
Fixed in 4.5
