### ISSUE TITLE
[Feature Request] Allow RTF or HTML of elemet Main Documentation, Notes and even all all text

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#485]
Feature Request: Allow RTF or HTML of elemet Main Documentation, Notes and even all all text

**Comment by odungern** [comment]
If we are talking about formatted text, XHTML is the natural choice. Or a popular markup language.

**Comment by theunsfvo** [comment]
What would be easier? RTF or XHTML?

I'm familiar with XHTML but I assume it is like HTML.

Thanks,
Theuns

*IQ Business <http://www.iqbusiness.net/>: Solution Architect | TOGAF 9
Certified Enterprise Architect  *
*"I love deadlines. I like the whooshing sound they make as they fly by." *
*  - Douglas Adams*

**Comment by odungern** [comment]
.. I do not belong to the Archi-Team, I am a user just like you und wanted to add my view.

In any web-environment RTF is not a very good choice. Archi is not the web, but the results are likely to be published in the web. So, formatted text should use a markup-language of the web, so XHTML or a markup language used by popular WIKIs. As a user, that's what I would appreciate most.

**Comment by odungern** [comment]
SpecIF ([https://specif.de](https://specif.de) and [https://github.com/GfSE/SpecIF](https://github.com/GfSE/SpecIF)) is an initiative to integrate models of different notations (BPMN, ArchiMate, ReqIF and others) and tools. Try [https://specif.de/apps/edit.html](https://specif.de/apps/edit.html).

We are supporting markdown and XHTML. Most tools including Archi export descriptions using markdown in the OpenExchange format. Upon publication, markdown is transformed to XHTML (browser, ePub) or WORDML. Works nicely.
