### ISSUE TITLE
[Feature Request] auto numbering of elements and/or relationships in a view

### ISSUE THREAD

**Issue by theunsfvo** [archimatetool/archi#487]
When describing views to audiences, numbering of certain elements in view or relationships to descrive the sequence or related parts is crucial and I usually have to do this manually with notes, which takes a lot of time.

A tobble in the properties or even on the elements and relations in the view to flag for numbering displays would really help a lot!

For example:

![image](https://user-images.githubusercontent.com/5095077/59343339-f10f9e00-8d0b-11e9-9493-e44a2f0f276c.png)

**Comment by Phillipus** [comment]
I won't be implementing this.

**Comment by jbsarrodie** [comment]
FWIW, I'm working on a script to do it (thanks to the upcoming new "label" feature)
