### ISSUE TITLE
Archi not/partly running under Ubuntu with Wayland 

### ISSUE THREAD

**Issue by armorica** [archimatetool/archi#488]
### Version of Archi, Operating System
4.4.0 build 201904031131

### Expected Behaviour
I expect Archi to open on start and open dialogs when clicking menu items.

### Actual Behaviour
After install, Archi opens but, for instance the Help the plugin load dialogue doesn't open. Also the canvas may get closed will no longer open.

Most of the times Archi doesn't start at all, throwing an error.

### Steps to Reproduce the Behaviour
1. Install Archi on Ubuntu (19.04) (I'm using the 'pure' Gnome environment)
2. Open Archi
3. If Archi opens, try to install a plugin

I presume this is an Eclipse - XWayland issue, out of scope for Archi, but it may be good to mention the issue as part of the Linux install. Also, the plugins are easily installed under Linux by unpacking the zip file, copying them to the plugins directory and restarting Archi, so no show stoppers here.

[archi.log](https://github.com/archimatetool/archi/files/3284593/archi.log)

**Comment by Phillipus** [comment]
Not sure what's happening here. Does Eclipse 4.8 work on Ubuntu 19.04? Some of the messages in the log suggest some kind of Display issue.

**Comment by Phillipus** [comment]
Does this help?

export GDK_BACKEND=x11

**Comment by armorica** [comment]
It does! I'll add it to my Archi-Ubuntu.sh script. Thanks for you quick response.

**Comment by Phillipus** [comment]
I'd like to keep the issue open until I can investigate further.

**Comment by armorica** [comment]
Fine with me. If you want me to test/check things, let me know.

**Comment by Phillipus** [comment]
@armorica  Thanks.

It would be good to know:

- if Wayland is on by default in 19.04
- are there issues using Eclipse 4.8 on 19.04?
- As Archi is built on Eclipse 4.8, is this still an issue with Eclipse 4.11 or 4.12? (i.e if we built Archi on on a later version of Eclipse is this still a problem?)

**Comment by armorica** [comment]
> @armorica Thanks.
> 
> It would be good to know:
> 
> * if Wayland is on by default in 19.04
I will have to double check, but I don't believe so; 19.04 not being an LTS release is a bit more aggressive with respect to new technologies, but I believe X has not been replaced as the default. As I do have multiple other minor issues with Wayland (which I'm testing every new release), I may, by accident, kept it as my default. I'll try a clean install, also leaving out the gnome-session-manager, for a out of the box Ubuntu experience.

> * are there issues using Eclipse 4.8 on 19.04?
I will have to test. Via the Software App in Ubuntu I get Eclipse 2019-03 (4.11.0) as a snap. I don't use an IDE, so will test this on the clean install as well. I also 'messed' around with java versions on my machine while installing Archi (Oracle version 11 and OpenJDK8 installed now (8 as default).

> * As Archi is built on Eclipse 4.8, is this still an issue with Eclipse 4.11 or 4.12? (i.e if we built Archi on on a later version of Eclipse is this still a problem?)
Can't say. If you provide me such a version, I can test. I'm willing to try a build, but I'm not really experienced with that.

**Comment by Phillipus** [comment]
I mean Eclipse 4.7, not 4.8.

(Edited all comments to refer to Eclipse 4.7, not 4.8)

**Comment by Phillipus** [comment]
> I'll try a clean install, also leaving out the gnome-session-manager, for a out of the box Ubuntu experience.

That would be useful.

>  I also 'messed' around with java versions on my machine while installing Archi

The 64-bit Linux Archi 4.4 version has been retro-fitted with a bundled AdoptOpenJDK Java 8 runtime. I did this yesterday. If the Archi installation has a "jre" folder when unarchived then you know you have the latest version. I did this because many users were reporting that Archi on Linux won't start with the default Java 11.

> As Archi is built on Eclipse 4.7, is this still an issue with Eclipse 4.11?

For testing it's just a case of seeing if Eclipse launches, runs or if there are any weird messages.

Eclipse 4.7 - https://archive.eclipse.org/eclipse/downloads/drops4/R-4.7.3a-201803300640/download.php?dropFile=eclipse-SDK-4.7.3a-linux-gtk-x86_64.tar.gz

Eclipse 4.11 - https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.11-201903070500/eclipse-SDK-4.11-linux-gtk-x86_64.tar.gz

Thanks for your help.

**Comment by Phillipus** [comment]
How does one enable/disable Wayland?

**Comment by armorica** [comment]
At login. Clicking your user, there is "settings wheel" next to the password field, where you can choose Ubuntu, or X.org Ubuntu, or ...

As I type this out of my head, the optionsmay be slightly different, but I think you get the idea.

Paul

**Comment by Phillipus** [comment]
@armorica I've released a beta version of Archi 4.5:

https://www.archimatetool.com/beta/

It's built on Eclipse 4.11, the latest version. If the Wayland issues are still there, then it's out of my hands as this is down to Eclipse.

**Comment by Phillipus** [comment]
I tried Archi 4.5 beta 1 on Ubuntu 19.04 with Wayland in a VM. The experience was horrible, and I mean the whole 19.04 + Wayland experience. Would suggest we close this issues until 19.10.

**Comment by armorica** [comment]
@Phillipus I'll have look too; I got occupied with other stuff last week. I'm fine running under X.org; as stated, I was surprised myself to run a Wayland session (unintentional). I'm curious how horrible your experience was; probably because I'm using gnome-sessions I don't experience it that much with Ubuntu (I don't like their look and feel, independant from Wayland or X.org).

Anyway thanks for the quick response and tests. Don't expect too much from 19.10 though as that won't be a LTS neither. 20.04 would be a better moment to revisit things I presume.

**Comment by Phillipus** [comment]
Archi ran under Wayland, but slower. Dialog boxes were fixed in size and attached to the main app window.
