### ISSUE TITLE
[Feature Request] Model validation from command line

### ISSUE THREAD

**Issue by qbarlas** [archimatetool/archi#489]
I use Archi command line in my CI / CD pipelines to build and publish the HTML Report.

It would be nice to be able to trigger the model validation in the pipeline to stop the process when someone has pushed bad things.

**Comment by Phillipus** [comment]
Which model validation do you mean?

**Comment by qbarlas** [comment]
I mean the validation you can do in the menu : Tools > Validate Model

**Comment by Phillipus** [comment]
The Validator is mostly a UI plug-in. To have similar functionality as a CLI would require quite a bit of a re-write of the plug-in. It could be done, but quite a bit of work.

**Comment by jbsarrodie** [comment]
In fact, I think it would be easier to create a jArchi script that would do the same checks. You could run them through CLI, check the result, and if invalid stop the pipeline.

**Comment by Phillipus** [comment]
Good idea.

This jArchi is some magic stuff!

**Comment by Phillipus** [comment]
In fact, this is exactly the kind of use case that jArchi was designed for, and I keep forgetting that! jArchi exposes the model concepts so any kind of semantic or structural interrogation is possible using jArchi. And once it is implemented in jArchi, the script can be shared.

@qbarlas See if this is possible for you. If it is, we can close this issue. In fact we should close the issue anyway as it's unlikely to be implemented in the Validator code.

**Comment by Phillipus** [comment]
I'll close this as this can achieved with jArchi.
