### ISSUE TITLE
[Feature request] Allow opening link in a browser from an URL inside a property

### ISSUE THREAD

**Issue by bourboule** [archimatetool/archi#490]
For documentation field, user guide describe the feature below:
"In the "Documentation" text control, URLs that start with "http://" "https://" or "ftp://" will show as a hyperlink. Pressing the Ctrl / Command key will change the cursor to a "hand" cursor and you can open the link in a Browser."

Feature request is to provide the same behavior for a property value field.

**Comment by Phillipus** [comment]
You can do this already.

Double-click the left part of the table row.

![Image 1](https://user-images.githubusercontent.com/600504/59532498-dc383380-8ee0-11e9-832c-eccc6411ad3c.png)

**Comment by bourboule** [comment]
Perfect. Sorry I was not aware of it.

**Comment by jbsarrodie** [comment]
FWIW, this is explained in the [user guide](https://www.archimatetool.com/downloads/Archi%20User%20Guide.pdf) on page 65:

>To Add a Hyperlink Property Entry:
>1. Select the Property entry in the Properties table you wish to use as a hyperlink
>2. Edit the value so that it contains a URL that starts with "http://", "https://" or "ftp://"
>3. Double-click the the left part of the Property row to open the link in a Browser

An btw, even I was not aware of it until Phil explained it to me 2 years ago ;-)

A good enhancement could be to display a small icon inside this first column when an URL is detected (but I don't know if this is possible)

**Comment by Phillipus** [comment]
> A good enhancement could be to display a small icon inside this first column when an URL is detected (but I don't know if this is possible)

Yes,  it is. ;-)

![Image 1](https://user-images.githubusercontent.com/600504/59632487-3c79e000-9142-11e9-8d63-93bdef5f0d4f.png)
