### ISSUE TITLE
Archi 4.4.0-Alert "Java was started but returned exit code=13"

### ISSUE THREAD

**Issue by ERo29** [archimatetool/archi#491]
### Version of Archi, Operating System

Archi 4.4.0
Mac OS X El Capitan 10.11.6

### Expected Behaviour

Archi should start normally.
### Actual Behaviour

Archi can't be launched => Alert "Java was started but returned exit code=13".
![20190616-Archi 4 4 0-Alert Java was started but returned exit code=13](https://user-images.githubusercontent.com/51884740/59566467-f731b180-9060-11e9-9802-1d229e141395.png)
### Steps to Reproduce the Behaviour
1. Java jdk version installed
java -version
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
2. Click on Archi icon in Dock
3. Alert (see joined png)

**Comment by Phillipus** [comment]
This can happen with Eclipse-based apps where there is a special character in the path. In your case it is "#" in "#Apps". Move it to a folder without this character.

**Comment by ERo29** [comment]
It was indeed the issue. Many thanks.
