### ISSUE TITLE
A dot in the view name messes up the export view file name

### ISSUE THREAD

**Issue by Ridderby** [archimatetool/archi#492]
### Version of Archi, Operating System

Archi 4.3.3 on Gentoo Linux using
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Gentoo icedtea-3.12.0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

### Expected Behaviour

To organize my views I name them using a numbering scheme like "1.2.3 Details of service". Dots are the natural separators used in technical documentation. 
When I chose to export a view as file in any format the file name is dependent on the dots in the view name and the default name in this case will be "1.2.png" (or svg, format does not matter). 

### Actual Behaviour

The file name for the view export shall be the same as the view name with .<format> added. 
E.g: "1.2.3 Details of service.png" or "1.2.3 Details of service.svg"

If there is a need to remove unsafe characters which a dot might be on some ancient OSes I suggest this chars (and space) are replaced in a deterministic manner, like replace all of them with '_'. 

I recall this is the same problem on Windows but I have no means to verify that statement right now. 

### Steps to Reproduce the Behaviour
1. Create a view with dots in the file name
2. Chose to export the view as image
3. The suggested filename is cropped

**Comment by Ridderby** [comment]
Forgot the fix;
Adding an additional dot at the end of the View Name makes Archi happy and the propose a file name as expected but without the additional dot.

**Comment by Phillipus** [comment]
Some very "helpful" code is adding a default file extension by looking for the last "." in the file name and removing the rest.

Will be fixed for the next version.

Until then, the file name is just a suggestion so you can manually change it in the text box to the correct name.

**Comment by Phillipus** [comment]
Fixed in 4.5
