### ISSUE TITLE
[Feature request] Let set a link into an element (as a properties) to an existing view to allow navigation to generated view

### ISSUE THREAD

**Issue by micwic** [archimatetool/archi#495]
It would be nice to let set a dedicated link properties to an existing view into the properties in an element from a view or much better also in the element itself everywhere it is instantiated.

I used this in Signavio to have abstract view and detailed view link together and allow users to navigate easily in the portal. Maybe something similar may be possible with the generated HTML documentation without a big effort.

**Comment by paugras1969** [comment]
Yes i agree, the default view of an element should be easily referenced via a  link or properties value, 
i'm tired to drop views icon on the top of each instance of a concept when i reference it a view.

**Comment by Phillipus** [comment]
> i'm tired to drop views icon on the top of each instance of a concept when i reference it a view.

Then I suggest you find a different (paid) software and use that instead.

**Comment by jbsarrodie** [comment]
>the default view of an element should be easily referenced via a link or properties value

There is no "default view of an element". Maybe in your usage there is, but this is a minority from my experience: when some kind of drill down is needed, this has to be contextual and thus has to be defined on a per view basis. So there is no gain between adding a reference to a view manually and adding a property somewhere else.

**Comment by jbsarrodie** [comment]
BTW, you can also try Herve's [specialisation plugin](https://github.com/archi-contribs/specialization-plugin) which provide this kind of feature.
