### ISSUE TITLE
Error : org.archicontribs.specialization_2.0.0.alpha1

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#496]
### Version of Archi, Operating System
VERSION 4.4, last download and install on the 2d of july

### Expected Behaviour

I have installed the SPECIALIZATION plugin. I get an error message in ARCHI when I click on it : 
An error has occurred. See error log for more details.
java.lang.NullPointerException

### Actual Behaviour

I get an error message in ARCHI when I click on it : 
An error has occurred. See error log for more details.

### Steps to Reproduce the Behaviour
1. open ARCHI
2. Select a view
3. Select an object on the view, In the properperties, you can see Specialization and Drill down
4) Click on DRILL DOWN : it works perfectly
5) Click on SPECIALIZATION, you get the error message "An error has occurred. See error log for more details.  java.lang.NullPointerException"

Regards
Christine.

**Comment by jbsarrodie** [comment]
Hi Christine, this is an issue with Hervé 's plugin and thus you should open an issue in its github repository, not Archi' s one.

**Comment by chdessus** [comment]
Done :-)

Christine Dessus
T : +33 6 31 09 73 54
www.competensis.com

**Comment by herve91** [comment]
Hi, this bug is indeed linked to my plugin. The issue has already been identified and will be solved in the next release.

Best regards
Hervé

**Comment by chdessus** [comment]
Merci.

Christine Dessus. Message envoyé  avec mon téléphone

Le mer. 3 juil. 2019 à 10:56, Hervé Jouin <notifications@github.com> a
écrit :
