### ISSUE TITLE
AMFF import failed: "Cannot find declaration of element 'model'"

### ISSUE THREAD

**Issue by robinwo** [archimatetool/archi#497]
### Version of Archi, Operating System
Archi 4.4, Windows 10

### Expected Behaviour
Import AMFF file (BlueDolphin export, verified that it contains model and element attributes), then continue working on that model in Archi.

### Actual Behaviour
Import AMFF file throws "Cannot find the declaration of element 'model' (line 2)". Import failed.

### Steps to Reproduce the Behaviour
1. Export model from BlueDolphin
2. Import AMFF file in Archi
3. Get error.

See first few lines of XML file below, incl. line 2 which has model attribute:
`<?xml version="1.0"?>
  <model xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" identifier="id-5c8fa727145c103fdfff998ad" xmlns="http://www.opengroup.org/xsd/archimate">
   <name xml:lang="EN">companyname</name>
   <elements>
    <element xsi:type="Goal" identifier="id-5c9ddf5bbbfdfdf1fb032269a">
     <label xml:lang="EN">Offering PaaS to customer</label>
    </element>`

**Comment by Phillipus** [comment]
Judging by the namespace `"http://www.opengroup.org/xsd/archimate"` this looks to be an older ArchiMate 2.0 exchange file.s Archi only supports ArchiMate 3.0 exchange file. (Also there is no XSD schema location so it's not possible to validate it.)

I don't know what BlueDolphin is, perhaps you could raise the issue with them?

**Comment by Phillipus** [comment]
I'll close this as it's not an Archi issue.

**Comment by robinwo** [comment]
Hmmm, makes sense. Any ideas for converting this 2.0 export to 3.0?

**Comment by Phillipus** [comment]
> Hmmm, makes sense. Any ideas for converting this 2.0 export to 3.0?

I believe a colleague of yours has contacted me about this.
