### ISSUE TITLE
Visual Studio Code plug-in available?

### ISSUE THREAD

**Issue by cveld** [archimatetool/archi#500]
Are you planning a markdown extension for Visual Studio Code in order to utilize the Archi rendering engine to render ArchiMate diagrams?

For an example refer to the PlantUML extension: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

Although PlantUML supports rendering of ArchiMate diagrams, it is not the same level of quality compared to Archi.

The PlantUML documentation with regards to its support for ArchiMate can be found here:
http://plantuml.com/archimate-diagram

**Comment by Phillipus** [comment]
No plans to do this.

> in order to utilize the Archi rendering engine to render ArchiMate diagrams?

Technically that's not practical. Diagram rendering relies on the Graphical Eclipse Framework (GEF) and Draw2D which renders in its own native canvas.

**Comment by cveld** [comment]
So this would require a huge refactor on the Archi side? Ideally Archi just plugs a generic drawing contract which has at least support for the GEF implementation and vscode drawing context (html5 canvas?).

**Comment by Phillipus** [comment]
Not possible. The whole GEF framework handles drawing, policies, layouts, command undo/redo, and so on.

**Comment by Phillipus** [comment]
I'll close this as it's not possible to do.
