### ISSUE TITLE
[Feature request] Auto layout in Archimate View editor (as in vizualiser pane)

### ISSUE THREAD

**Issue by rchevallier** [archimatetool/archi#501]
The vizualizer pane propose a auto layout tool. 
To assist the manual display of items on a view, make the same tool available on the View editor
Option: if no element selected: works on all elements on the view (warning box?), if elements selected, works only only on these elements. (for 1 element: do nothing and warn)

**Comment by Phillipus** [comment]
A layout algorithm could be applied to elements in a View....if someone can do this (not me, this is not my expertise ;-) ). This is something that could be implemented in a jArchi script, for example.

**Comment by rchevallier** [comment]
Not possible (simpler?) to reuse the already existing algorithm/button from the "visualizer pane"?

**Comment by Phillipus** [comment]
> Not possible (simpler?) to reuse the already existing algorithm/button from the "visualizer pane"?

No. That's a completely different component and framework.

**Comment by rchevallier** [comment]
One day when I'll find time, I'll try to do the jArchi script....
