### ISSUE TITLE
[Feature-request] Archi plugin marketplace

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#502]
Would be great to make people publish and share plugins on a platform basis, alongside with collaboration server seems to be great. Like for examle Atlassian products. Is it in the roadmap ?

**Comment by Phillipus** [comment]
I won't be hosting this

**Comment by WatchTh1** [comment]
I have an option to host, if we conclude on API would be nice.

**Comment by jbsarrodie** [comment]
Hi,

In fact we already have http://archi-contribs.github.io/ which is updated each time someone makes us aware of some new plugin. I don't think we need much more than that (there is only one other plugin contributor: Herve with its specialization, servicenow and database plugin).

**Comment by WatchTh1** [comment]
Oh! What a nice thing! Will you put an Archi integration feature for this repo onto roadmap?
