### ISSUE TITLE
[Bug] Import CSV Data Into Model works on file with 30 rows but not with 95.000 rows

### ISSUE THREAD

**Issue by whoisraibolt** [archimatetool/archi#503]
### Version of Archi, Operating System

Archi v4.4.0, on Windows 10 x64.

### Expected Behaviour

Import CSV Data Into Model working on a .csv file with 95.000 rows or more.

### Actual Behaviour

I'm trying to import into Archi an elements.csv file with approximately 95.000 rows.

However, I received the following error message importing: 

> Could not find concept: (Some ID that in this elements.csv file does not exist).

I already ran a test and reduced the same elements.csv file to only 30 rows and in this way Archi imported elements.csv file correctly.

That is, with this test I was able to verify if there was any error with respect to the data, and it was identified that there is no inconsistency in the data.

I took a quick look at the `CSVImporter.java` file and in the `ArchimateModelUtils.getObjectByID()` function, maybe left something pass, and as I mentioned earlier, the ID returned along with the CSVImporter_10 message does not exist in elements.csv file.

I could not recognize exactly why the code returned this error, but again, I took a quick look.

### Steps to Reproduce the Behaviour
1. Create the elements file in MS Excel (with approximately 95,000 rows) containing an ArchimateModel type and the rest of the objects as Artifacts type.
2. Save the elements file in .csv format using the UTF-8 encoding.
3. In Archi, create a new Empty Model.
4. Without renaming the Empty Model or any other modification, import the elements.csv file through the CSV Data Into Model.

PS: By doing the same process, however, reducing the 95,000 rows to 30 rows, this same process works as expected.

I'm new using Archi, I'm not sure if this can be considered a bug.

But anyway, I would like to know if it is in fact a bug or something else.

Anyway, I apologize if I have opened this issue in the wrong way.

Best Regards.

**Comment by Phillipus** [comment]
This can happen if there is a wrong object id in the relations.csv file. The source and target IDs should match entries in the elements.csv file. Did you check this?

**Comment by whoisraibolt** [comment]
Using the CSV Data Into Model option I can not import the three files (elements.csv, properties.csv and relations.csv) together.

I need to import them one at a time. In this case, I do not know if there is a correct import order, but at this first moment I'm trying to import the elements.csv file first.

So I could not check what you commented because the reported problem occurs when I try to import only the elements.csv file, (and I can not import all three files at once).

**Comment by Phillipus** [comment]
As long as the three file names match ("elements.csv", "relations.csv", "properties.cvs") you only need to select one file for import. So if you import "elements.csv" file the others will be imported also.

Search for the incorrect ID in the "relations.csv" file, and you will find it in the Source or Target column.

**Comment by whoisraibolt** [comment]
Sorry for the delay in answering it.

I have not realized that if I import elements.csv file the others will be imported also.

So I was looking for an error in the elements.csv file instead of looking for something in the relations.csv file.

This worked for me. Thank you!

Just one more thing, I fixed the problem reported above, but now when importing I'm getting the CSVImporter_2 error:

`Incorrect record size.`

What exactly does that mean? I understand that there is a condition to check if the size of the elements record is correct.

But I can not understand why I'm getting this error.

**Comment by Phillipus** [comment]
Incorrect record size means that there are not enough, or too many, entries in a row. You have to check there are the exact right amount in each row.

**Comment by whoisraibolt** [comment]
OK. Thank you!

Once the main problem has been clarified and solved, I will be closing this issue.

Any other problems, I'll get in touch.

Best Regards.
