### ISSUE TITLE
[Feature Request] Ability to lock editing at views and folder level through right click context menu

### ISSUE THREAD

**Issue by Manj75** [archimatetool/archi#505]
Selecting a folder or viewpoint and being able to set it to be non-editable such that if set then Archi would not allow elements from the palette to be added to the view or recursively to all sub-folders and views if set at folder level.

This request is not about limiting the editing of the model, i.e. design elements of lock views/folders, but more about locking the layout of the views and folder structures in the Views folder.  This would be really beneficial in an organisation using Archi with Collaboration plugin where a team is editing and want to prevent accidental changes to views and folder structures for items that are baselined.

Please see forum discussion: https://forum.archimatetool.com/index.php?topic=683.0

**Comment by Phillipus** [comment]
Actually, this has already been opened with #493 

So, I'll close this one.
