### ISSUE TITLE
[Bug] Use of angle brackets in model folder/view name results in erroneous HTML report

### ISSUE THREAD

**Issue by Manj75** [archimatetool/archi#506]
If in the model there is an angle bracket used that resembles an HTML tag format it will cause incorrect generation of the HTML report.

For example a folder named `Project<ID>Title<TEMPLATE>` will not display folders before this folder due to `<TEMPLATE>` being interpreted as an HTML tag.  In other cases of HTML tag like use in folder/view names, such as<ID>, will not be display in the HTML report as it appears to be stripped off.

I've not had a chance to carry out a detailed inspection but I feel this is to do with these being interpreted as HTML tags.  I've resolved the issue by substituting out the use of angle brackets, but is still a low priority bug.

**Comment by Phillipus** [comment]
Thanks for reporting. I can reproduce this.

This will be fixed in Archi 4.5/

**Comment by Phillipus** [comment]
Fixed in 4.5
