### ISSUE TITLE
No UI feedback on menu button when a window is active 

### ISSUE THREAD

**Issue by sudr** [archimatetool/archi#508]
When I click on a menu button to enable (ie. display) any of the windows (properties, validator, etc.),  the menu button does not provide any feedback that it is enabled (for example "depressed").

**Comment by Phillipus** [comment]
The toggled state of a button in the toolbar can get out of sync if the corresponding window is closed by using the "X" to close it, or from the main menu. This would mean retrofitting a workbench window close and open listener to every toolbar button action handler in Archi and in all plug-ins, which is probably more trouble than it's worth, to be honest.

The fact that the window is open or not open is really the visual feedback here.

**Comment by sudr** [comment]
Thanks for reviewing it. Maybe this can feed into design guidelines for a future UI refresh of Archi.
