### ISSUE TITLE
Use accented characters in HTTP link as a documentation or property

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#509]
### Version of Archi, Operating System
 VERSION 4.5 (the latest issued on the 5th of August)

### Expected Behaviour

I try to include a HTTP link to a Sharepoint or shared directory. The link is large and the directories contains space and some letters have French accents (é ê è à...) 

### Actual Behaviour

The link is visually truncated. 

### Steps to Reproduce the Behaviour
1.  We could solve the difficulty by suppressing spaces and accents. Unfortunately, this is not possible at a company level. 
Could you fix it ? 

Thanks
Christine
+33 (0)6 31 09 73 54

**Comment by Phillipus** [comment]
Could you provide an example URL?

**Comment by Phillipus** [comment]
This is the regex expression used to parse for URLs:

`(http|https|ftp)://([\w-]+\.)+[\w-]+([\w-./?%~#!+@:&=\(\)]*)?`

If anyone can provide a regex expression that supports accented characters, please do so.

**Comment by chdessus** [comment]
Yes. I'm doing that....

Christine Dessus. Message envoyé  avec mon téléphone

Le mar. 6 août 2019 à 11:35, Phil Beauvoir <notifications@github.com> a
écrit :

**Comment by chdessus** [comment]
Here is the example :

The first link works well, not the the second one :

*https://acp.andritz.com/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25_Modele_conceptuel.graphml
<https://acp.andritz.com/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25_Modele_conceptuel.graphml>*

 *https://acp.andritz.com/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25%20Modèle%20conceptuel.graphml
<https://acp.andritz.com/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25%20Mod%C3%A8le%20conceptuel.graphml>*


We could have the same issue with the Novegian or German (Nordic) letters :)



[image: image001.png]


Many thanks !


Christine Dessus
T : +33 6 31 09 73 54
www.competensis.com

**Comment by Phillipus** [comment]
This is the proposed regex expression:

`(http|https|ftp)://([\w-]+\.)+[\w-]+([\w-./?%~#!+@:&=\(\)[À-ÿ]]*)?`

It seems to work in tests, but needs more testing.

**Comment by Phillipus** [comment]
The regex expression doesn't work because of UTF-8 encoding issues in the source code. This one seems to work:

(http|https|ftp)://([\w-]+\.)+[\w-]+([\w-./?%~#!+@:&=\(\)[\u00C0-\u017f]]*)?

See https://stackoverflow.com/questions/20690499/concrete-javascript-regex-for-accented-characters-diacritics

**Comment by chdessus** [comment]
Thanks. Didn't have a chance to test. In vacation in the  centre of France.
Cut off almost every IT stuff.
Regards.

Christine Dessus. Message envoyé  avec mon téléphone

Le mer. 14 août 2019 à 19:42, Phil Beauvoir <notifications@github.com> a
écrit :

**Comment by Phillipus** [comment]
Hi Christine, no need to test this. These comments are just notes to myself, and a record of progress,

**Comment by indeyets** [comment]
Another option is to use external library which handles difficult cases https://github.com/robinst/autolink-java

**Comment by Phillipus** [comment]
@indeyets Thanks for the link!

**Comment by Phillipus** [comment]
Should be fixed in 4.6
