### ISSUE TITLE
[Jasper Reports] Print relations for each view in model

### ISSUE THREAD

**Issue by NickTononi** [archimatetool/archi#510]
Hello,
I edited the archi code and model to add this feature.

This feature allows to see the relations associated with a view.

I'm attaching a generated report after the changes I made.
[report-with-relations-per-view.pdf](https://github.com/archimatetool/archi/files/3472432/report-with-relations-per-view.pdf)

Is this a feature that might come handy?

**Comment by Phillipus** [comment]
Hi Nick, thanks for the submssion.

This could be an optional feature of the Japer Reports.

Some of the proposed changes to the code are a bit more problematic:

- We can't modify the `Property` class as this is generated by core EMF. One should use the factory method to return a `IProperty` class instead.
- `ElementsDataSource` - setting the concepts shouldn't really be done, as this class's function is to return concepts for a context (model or folder)
- I need to look closer at the proposed changes to the other java classes as these seem to have a lot of impact and would require unit tests as well

I'll look a bit deeper, but I'm sure this could be done in a simpler way.

That's not to disparage your changes. :-) It's just I that I need to see if the DataSource API could be modified in a better way to return relationships.

**Comment by NickTononi** [comment]
Hi Phillipus,
thanks for the feedback!
I just needed that feature so I made the most simple changes just to achieve the result without thinking to the whole project.

Wanted to share with you guys to see if this could be done in a more clean and efficient way than I did.

**Comment by Phillipus** [comment]
Hi Nick, yes I thought that. :-)

My comments are not criticisms, just code comments. So thanks for sharing. :-)

I'll take a look at it soon.

**Comment by Phillipus** [comment]
We probably need a new class like `ViewChildrenDataSource` but for relations.

**Comment by Phillipus** [comment]
Once we've had more testing of the new method `ViewModelDataSource#getChildRelationsDataSource()` we can add it to the master branch and *.jrxml files can call it.

**Comment by Phillipus** [comment]
The changes to the `ViewRelationsDataSource` have now been merged the master branch.

@NickTononi If you want to use this API in your *.jrxml file feel free to try it.

**Comment by NickTononi** [comment]
Works like a charm, thanks for merging into master branch. 

Does this mean that the next Archi release will support this feature?

**Comment by Phillipus** [comment]
> Does this mean that the next Archi release will support this feature?

Yes.

**Comment by Phillipus** [comment]
But the jrxml file is unchanged. That is a separate issue.

**Comment by NickTononi** [comment]
I made a mistake while testing before, I added a simple subreport inside the jrxml and now I get the following error:
![jasperError](https://user-images.githubusercontent.com/48349671/63675827-f5673580-c7e9-11e9-9baa-548dd81069fb.png)

Just added the following to view.jrxml:
`<subreport>
				<reportElement positionType="Float" isPrintRepeatedValues="false" x="0" y="120" width="515" height="50" isRemoveLineWhenBlank="true"/>
				<subreportParameter name="VIEW_DETAILED">
					<subreportParameterExpression><![CDATA[$V{VIEW_DETAILED}]]></subreportParameterExpression>
				</subreportParameter>
				<subreportParameter name="REPORT_PATH">
					<subreportParameterExpression><![CDATA[$P{REPORT_PATH}]]></subreportParameterExpression>
				</subreportParameter>
                <subreportParameter name="REPORT_RESOURCE_BUNDLE">
                    <subreportParameterExpression><![CDATA[$P{REPORT_RESOURCE_BUNDLE}]]></subreportParameterExpression>
                </subreportParameter>
				<subreportParameter name="TITLE">
					<subreportParameterExpression><![CDATA["View Relations"]]></subreportParameterExpression>
				</subreportParameter>
				<dataSourceExpression><![CDATA[((com.archimatetool.jasperreports.data.ViewModelDataSource)$P{REPORT_DATA_SOURCE}).getChildRelationsDataSource()]]></dataSourceExpression>
				<subreportExpression><![CDATA[$P{elements_report}]]></subreportExpression>
			</subreport>`

I'm attaching the jrxml file. 

[view.jrxml.txt](https://github.com/archimatetool/archi/files/3540109/view.jrxml.txt)

I don't get the error here, do you think this is somehow related to the new added method?

**Comment by Phillipus** [comment]
getChildRelationsDataSource() follows exactly the same structure and pattern as getChildElementsDataSource() so I can't see how it would cause an error if used in the same way.

Suggest setting a debug breakpoint and seeing what's wrong.

**Comment by Phillipus** [comment]
The error in Eclipse is:

Caused by: java.lang.ClassCastException: class com.archimatetool.jasperreports.data.ViewRelationsDataSource cannot be cast to class com.archimatetool.jasperreports.data.ElementsDataSource 

So looks like your jrxml file needs changing?

**Comment by Phillipus** [comment]
Probably because it is using the elements.jrxml sub-report. You might need to modify that one to handle relations and a ViewRelationsDataSource?

**Comment by NickTononi** [comment]
I now edited the jrxml file in order to use the feature.
I [forked](https://github.com/NickTononi/archi) the repo adding the custom template.

And here is the resulting report:
[report-relations-view.pdf](https://github.com/archimatetool/archi/files/3541078/report-relations-view.pdf)

Thanks for your hints and suggestions on this one.

**Comment by Phillipus** [comment]
@NickTononi There may be a change to this. See #518
