### ISSUE TITLE
NPE when changing Palette settings

### ISSUE THREAD

**Issue by sudr** [archimatetool/archi#512]
[archi-error-log.txt](https://github.com/archimatetool/archi/files/3487710/archi-error-log.txt)

### Version of Archi, Operating System
Mac OSX
com.archimatetool.editor.buildid=201904031131
com.archimatetool.editor.versionid=4.4.0

### Expected Behaviour
Should be able to change the settings for the Palette view.

### Actual Behaviour
Changing any of the settings in the Palette Settings window throws a NPE and is show in the error dialog.

### Steps to Reproduce the Behaviour
1. Right click inside the Palette view
2. Select "Settings..."
3. Click on any setting

**Comment by Phillipus** [comment]
Are you using the Palette View (opened from the toolbar) or the palette that is attached to the diagram editor?

**Comment by Phillipus** [comment]
I can't reproduce this. Does this happen every time or is there some factor involved that causes this?

Also, can you try with Archi 4.5.1.

**Comment by Phillipus** [comment]
Do you have any Archi plug-ins installed?

**Comment by sudr** [comment]
Didn't have any plug-ins installed. I just upgraded to 4.5.1 and the issue doesn't occur on this version. Thanks for the quick response.
