### ISSUE TITLE
Custom Plugin does not get loaded in 4.5.1

### ISSUE THREAD

**Issue by TiPunch69** [archimatetool/archi#514]
I switched from Archi 4.4.0 to 4.5.1.

I have a custom plugin, that works fine under 4.4.0 and below, but does not load from the "plugins" folder in 4.5.1. Do I have to perform additional steps to get it loaded?

The plugin works fine when launching Archi via Eclipse RCP (both in normal and debug mode).

**Comment by Phillipus** [comment]
Hi, have you tried putting it in the "dropins" folder?

Archi now uses this mechanism to discover new plugins, See the last page of the user guide, or discussion here https://www.archimatetool.com/blog/2019/08/05/archi-4-5/

**Comment by TiPunch69** [comment]
Thanks for the quick response.

Putting the plugin into the dropins folder did the trick. I would suggest updating the development documentation, since there the old mechanism with the "plugins" folder is described.

If I change the dropins folder location (I have a portable installation) it does not work anymore. I guess the only way around is to package it as a feature and install it via the new plugin manager.

**Comment by Phillipus** [comment]
> I would suggest updating the development documentation, since there the old mechanism with the "plugins" folder is described.

Done.

> If I change the dropins folder location (I have a portable installation) it does not work anymore.

For a portable version you can (optionally) remove this line in the Archi.ini file

`-Dorg.eclipse.equinox.p2.reconciler.dropins.directory=%user.home%/AppData/Roaming/Archi4/dropins`

and create a "dropins" folder alongside the "plugins" folder. See https://github.com/archimatetool/archi/wiki/How-to-create-a-fully-portable-(Windows)-version-of-Archi-(including-plugins)

> I guess the only way around is to package it as a feature and install it via the new plugin manager.

No. It is not an Eclipse "feature". It is simply a zip file containing the plug-in jars and a marker file (empty) named "archi-plugin". The plugin manager simply opens the zip file, looks for the marker file to ensure it is an Archi plugin and unzips the jar files or folders to the "dropins" folder.

**Comment by Phillipus** [comment]
For the background on this new mechanism see https://github.com/archimatetool/archi/issues/429

**Comment by Phillipus** [comment]
Actually, if a plug-in is copied into the "plugins" folder it will work. It just won't show up in Archi's Plug-in Manager, since that is only looking for plug-ins in the "dropins" folder(s).

**Comment by TiPunch69** [comment]
Thanks, worked like charm. Although I had to re-download the fresh 4.5 version and dump all settings, because they messed up with new package mechanism.

**Comment by TiPunch69** [comment]
I think this one could be closed.
