### ISSUE TITLE
Generated view for Plateau does not include aggregated relations.

### ISSUE THREAD

**Issue by GisbeyD** [archimatetool/archi#516]
### Version of Archi, Operating System
V4.5.1 , Windows 10

### Expected Behaviour

Generating a view for a selected Plateau should include everything aggregated to that Plateau, including connections which are themselves connected to the Plateau.
### Actual Behaviour

The generated view does not include connections that are connected (by aggregation) to the Plateau, unless Add All Available connections is checked, but then the view contains connections which are not part of that Plateau. As a result it is not possible to generate a view of the architecture state represented by a Plateau, 
### Steps to Reproduce the Behaviour
1. Create a model with a current and future state represented by two plateaus, and elements including connections aggregated into each plateau.
2.Right click a plateau and choose Generate View for Elements
3.Select viewpoint:None and leave Add All Available connections unchecked.

[test1.zip](https://github.com/archimatetool/archi/files/3534317/test1.zip)

**Comment by Phillipus** [comment]
> ...unless Add All Available connections is checked, but then the view contains connections which are not part of that Plateau. 

If there are connections to connections then some other elements have to be included in order that there are source and target elements for all connections.

There may be a deficiency in the parsing of the "Generate View For..." command when connection to connections are involved. I haven't looked at this code for some time, and it's not on my immediate radar, so if anyone would like to improve this code (not suggesting it is you @GisbeyD ) then these are the classes:

https://github.com/archimatetool/archi/tree/master/com.archimatetool.editor/src/com/archimatetool/editor/tools

**Comment by GisbeyD** [comment]
I can see this could get a little complex when the appropriate behaviour for a range of different scenarios is considered. For example, if a plateau aggregates everything present at a point in time, then clearly it lacks integrity if a connector is present at that point in time, but the source or target element isn't, so it might be helpful to include these elements but also highlight the apparent model integrity issue.
