### ISSUE TITLE
Access relationship from Material to Equipment object

### ISSUE THREAD

**Issue by gbvbg** [archimatetool/archi#521]
### Version of Archi, Operating System
 Version 4.5.1, Windows 10.

### Expected Behaviour

I am trying to model "Example 32: Physical Elements" from Chapter 11 of "ArchiMate® 3.0.1 Specification" in particular relationship between Material and Facility or Equipment. Example Link from Plastic case" and "Assembly Line". This relationship looks to be "Access" type.
![image](https://user-images.githubusercontent.com/35333850/63936533-b0046b80-ca68-11e9-9c07-0aa67fd55b57.png)

### Actual Behaviour

It is not possible create Access relation from a Material object to a Facility or Equipment using Archi. And in the same time "ArchiMate® 3.0.1 Specification" says that "The access relationship models the ability of behavior and active structure elements to observe or act upon passive structure elements." Thus inability model Access from Passive Structure Element (ex. Material) to Active Structure Element should be correct?

### Steps to Reproduce the Behaviour
1. Create Meterial and Equipment objects
2. Try create Access relationship from Material to Equipment object

**Comment by jbsarrodie** [comment]
Hi, this is because access relationship is the way around (from equipment to material) but defined as 'read' instead of 'write'.

Note: access always ends at a passive structure element.

**Comment by gbvbg** [comment]
Thanks a lot.
