### ISSUE TITLE
provide a way to hide the toolbar

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#523]
Please provide a way to hide the toolbar.

While trying to find a way to do it myself I discovered that toolbar elements can be dragged to the status bar and when all have been moved the toolbar automatically closes. For a few moments I was happy, but then I discovered two issues:

1. the alignment and zoom toolbar won't stay there and will jump back to the top after Archi is restarted
2. when toolbars are dragged to the status bar the status bar it won't disappear when "preferences-general-show status bar" is unchecked and screen space is still wasted

**Comment by Phillipus** [comment]
There is a "Hide Toolbar / Show Toolbar" menu item already.
