### ISSUE TITLE
[Feature Request] Please add a setting for disabling derived relationships.

### ISSUE THREAD

**Issue by rojoweko** [archimatetool/archi#524]
Please consider adding a setting to Archi that allows the user to disable the usability of derived relationships between elements. I think an option for limiting relationships to the ones explicitly defined in the standard could be a great feature for users, who want to improve their understanding of the basic concepts of Archimate modelling.

Thanks in advance!

**Comment by Phillipus** [comment]
We actually have considered this, but never really finalised how it would look in the UI. Whether to show derived and core relationships differently. This needs to be fleshed out properly,

**Comment by rojoweko** [comment]
Thanks for the reply!
I took a look at the relationships.xml. It appears to distinguish between core and derived relationships. On what data is it based? There is a relationship matrix in the appendix of the Archimate standard. Could this be used for this? If not, would it be reasonable to consider implementing an option to simply disable every relationship listed in the derived-properties in the given relationships.xml in the magic connector menu and disallow it when trying to establish a new non-core relationship?

**Comment by Phillipus** [comment]
The distinguishing between core and derived in that file is not 100% accurate and will be removed for the next version. I'll see what can be done about getting a more accurate list.

Implementing this would also affect the Model Validator.

**Comment by jbsarrodie** [comment]
Hi, The real question is "Is-it useful to have only direct relationships?"

Almost none of the model I see would be possible without derived relationship. For example, a simple flow between two application components is derived, but is one of the most frequently use relationships.

I'd say the real issue or risk is with relationships derived across layers, or in a more general term, relationships derived through more than 2 or 3 relationships.

@rojoweko: Could you elaborate a bit more on why you think this should be done?

**Comment by Phillipus** [comment]
I just looked at the current "relationships.xml" file. Here's an example:

```
<target concept="TechnologyService" relations="fotv" derived="ftv" />
```

In many cases the only core relationship would be Association. Not sure how useful that would be.

One option would simply be to distinguish between core and derived in the UI by some means so the user knows. Again, practically not sure how useful this would be.

**Comment by rojoweko** [comment]
My intention behind this request is, that I think that an optional limitation of the allowed relationships would help people to train their understanding of the basic concepts of Archimate, since they can force themselves to use those without having the chance to "cheat". Especially beginners probably already know about the basic meaning of certain elements or relationships, but might "abuse" the Archimate notation by establishing derived relationships between elements without understanding, which elements, that led to this derivation, they actually missed out in a diagram. I can imagine that users who are familiar with other modelling languages also could mix up concepts and thus use Archimate not in the way it was intended (at least this is my personal impression). The fact that in many cases only association relationships are allowed, would help in this context, because then the user has to implement a "path" of intermediate elements and relationships in order to "connect" the elements in question using Archimate core concepts.

Please understand that I am not asking for a general restriction of allowed relationships in Archi, but a user-switchable OPTION which turns this restriction on or off (for instance for practicing purposes) would be pretty nice, I think. ;-)

**Comment by Phillipus** [comment]
> Please understand that I am not asking for a general restriction of allowed relationships in Archi, but a user-switchable OPTION which turns this restriction on or off (for instance for practicing purposes) would be pretty nice, I think. ;-)

I understand that.

Perhaps then the issue is one of making clear what is derived, what is core and, possibly, how it is derived?

**Comment by rojoweko** [comment]
As far as I understand the Archimate standard every relationship (other than association, which appears to be always usable) allowed in chapters 6-13 is "explicitly" allowed (so-called "core"). All other allowed relationships are "implicit" and are "derived" according to the derivation rules given in chapter 5.6 of the specification. All relationship types are ranked from "strong" to "weak". To my understanding the derivation rules basically state that you can shorten a "path" of intermediate elements and relationships with the same direction between two "terminating" elements by leaving the intermediate elements/relationships out and use only the weakest relationship in the path to connect these two elements (there are some exceptions though). This relationship would be a derived one. There is probably a way of computing derived relationships, but I cannot tell yet. As mentioned details are stated in the standard (https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc489946006).

**Comment by jbsarrodie** [comment]
>As far as I understand the Archimate standard every relationship (other than association, which appears to be always usable) allowed in chapters 6-13 is "explicitly" allowed (so-called "core").

Yes

>All other allowed relationships are "implicit" and are "derived" according to the derivation rules given in chapter 5.6 of the specification.

Yes but the in depth description of rules in on [Appendix B](https://pubs.opengroup.org/architecture/archimate3-doc/apdxb.html#_Toc489946155)

>All relationship types are ranked from "strong" to "weak"

False. Only structural and dependency relationships have a _weight_.

>To my understanding the derivation rules basically state that you can shorten a "path" of intermediate elements and relationships with the same direction between two "terminating" elements by leaving the intermediate elements/relationships out and use only the weakest relationship in the path to connect these two elements (there are some exceptions though)

This is true only for structural and dependancy. Dynamic relationship follow other rules.

>There is probably a way of computing derived relationships, but I cannot tell yet.

Of course there is, this is how we (Open Group ArchiMate Forum members) generate the table ;-) But this is all but simple to implement because of edge cases and recursion involved. FYI, there are 3 different implementation maintained using different language. When they all provide the same output set, then the table is known to be valid.

**Comment by rojoweko** [comment]
OK, thanks for the clarification. So do you need some further information from me regarding this issue?

**Comment by Phillipus** [comment]
The real issue here is whether this is a useful feature for Archi users and, if so, how would it appear. I'm against disabling derived relationships even as an option. Indicating them as such is preferable.

**Comment by rojoweko** [comment]
OK, maybe that will work. I appreciate this! Thanks!

**Comment by Phillipus** [comment]
But this is still up for discussion - is this something other users want? How useful is it? How/where does it manifest?

**Comment by jbsarrodie** [comment]
> But this is still up for discussion - is this something other users want? How useful is it? How/where does it manifest?

I'm not convinced this is useful for users. This is more related to training (and as such could be interresting for training centers which use Archi... but they hardly support Archi anyway).

I have the feeling that it might be interresting to have some kind of feedback in Archi when some strange derived relationships are used, but this would require to define (and agree on) such set of "strange derived relationships".

IMHO, the best way for someone new to ArchiMate to learn it is to never use the magic connector and simply use relationships that he know.

**Comment by rojoweko** [comment]
OK, I solved this myself. It probably won't comply with your quality standards and I defined myself which relationships are core or derived, but I did it to my best knowledge and it serves my needs for the moment. ;-) So I will close this issue now.
