### ISSUE TITLE
NOT dark theme-firendly

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#526]
### Version of Archi, Operating System
Archi 4.5.1, linux (ubuntu 18.04), KDE 5 with standard breeze dark theme

### Expected Behaviour
All colours in a diagram, including view background and element name, should be defined in Archi and should be platform-independent.

### Actual Behaviour
I started working on a diagram on windows and although I was getting more and more annoyed by the eye-destroying white background, I couldn't at least complain about the contrast. Now I tried to open the same diagram on linux, and just look at it:
![Screenshot_20190913_083032](https://user-images.githubusercontent.com/11752339/64840434-13af9c80-d604-11e9-8276-140a487d273c.png)
View background and element name colours changed to theme-derived values while other diagram colours remained the same, as a result, it is quite unusable.

**Comment by jbsarrodie** [comment]
Jumping in....

There seems to be a regression. Look at this:
![image](https://user-images.githubusercontent.com/5757396/64842900-d9de9600-d603-11e9-80f3-412944715629.png)

This is a screen shot of my desktop using dark theme (note: I don't use ubuntu but elementary os which is based on ubuntu). On the top left you have Archi 4.5.1 which exibits the same issue, on bottom left you have Archi 4.2 which doesn't.

@Phillipus This might be related to the new version of eclipse framework. Have the CSS themes files been updated?

@lvmm If you didn't already, I'd like you to read [this post](https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/) by one of the Gnome maintainers. He explains that in fact there is no theme at all in Gnome, and that any attempt to create such theme have a high probability to impacts some applications. This is one good example of such impact.

**Comment by jbsarrodie** [comment]
BTW: https://askubuntu.com/questions/1149986/eclipse-looks-terrible-with-linux-dark-theme

**Comment by jbsarrodie** [comment]
Here is a workaround: start Archi from the command line and force the theme `GTK_THEME=Adwaita ./Archi`

**Comment by lvmm** [comment]
> Here is a workaround: start Archi from the command line and force the theme `GTK_THEME=Adwaita ./Archi`

Ah, just came to tell that I found a similar workaround - in KDE GTK and Qt themes can be controlled independently via system settings. This is even better, only it should be 'export GTK_THEME=...'

**Comment by Phillipus** [comment]
> This might be related to the new version of eclipse framework. Have the CSS themes files been updated?

The CSS theme files are as those used in Eclipse 4.11, with the exception of a `TabbedProperty*` CSS items (their colour choice is not good). I suspect that internally Eclipse's theme handling code has changed between Eclipse 4.7 and Eclipse 4.11.

One  can create one's own theme in Archi by editing the CSS files in the `com.archimatetool.editor.themes\themes\eclipse` directory. I tried this once using Eclipse's dark theme as a starting point and it looked messy. Some UI elements were not dark, and I could see that it would require some work to edit the CSS files to get it to work.

Side note - the Eclipse Foundation developers have a tendency these days to forget that there are RCP applications built upon Eclipse. More and more it seems their mantra is "If it works on my copy of Eclipse, it works everywhere".

**Comment by Phillipus** [comment]
https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse&list_id=18943739&product=Platform&query_format=advanced&short_desc=theme%20dark&short_desc_type=allwordssubstr
