### ISSUE TITLE
Multiple filters for the Visualizer

### ISSUE THREAD

**Issue by KingBain** [archimatetool/archi#528]
I was working on some modeling and noticed when I use the visualizer that you can only filter based on one type of element . Is it possible to filter based off two or more elements ?

I checked the archi userguide and didnt see any mention of selecting multiple filters in the visualizer section. 

I thought maybe it could work like ,hold shift and multi-select from the drop box.

photoshoped the idea
![image](https://user-images.githubusercontent.com/367922/64974386-b7a27d80-d87a-11e9-8e71-f00d18146682.png)

Is there any other way to filter on multiple elements ?

**Comment by Phillipus** [comment]
It only works for one type.

Perhaps the next time the visualiser gets some attention we could add that as a feature.

**Comment by ZanteBFF** [comment]
Hello,

any update on this topic?

**Comment by lavenderb** [comment]
I'd like to second this proposal.
  and modify is slightly such that it would be possible to 'Select all' and then filter out specific elements or relationships that are cluttering the desired visualisation.

**Comment by Phillipus** [comment]
I took a look at this today and I've made changes so that more than one Element or Relationship can be selected in the filter lists. So this will be in the next version of Archi.

So I'll close this one as completed.
