### ISSUE TITLE
AbstractDiagramConnectionFigure#clipTextLabel not working on Mac

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#529]
I've just noticed that the label clipping patch for connections doesn't working on Mac. Tested on Archi 4.3, 4.4 and 4.5.

If we only set the clip rectangle to the label it does clip to that region but adding the other rectangle "g" doesn't create the effect.

```java
Path path = new Path(null);
// path.addRectangle(g.x, g.y, g.width, g.height);
path.addRectangle(l.x, l.y, l.width, l.height);
graphics.setClip(path);
```

@jbsarrodie I know you don't have a Mac but do you have any hint what might be the problem? Or is there another way to set the clip area?

**Comment by jbsarrodie** [comment]
>If we only set the clip rectangle to the label it does clip to that region but adding the other rectangle "g" doesn't create the effect.

Do you mean that it works if we simply set the clip area to the label ? (it shouldn't and instead draw the connection only inside the label bounding box).

I don't know why it doesn't work on Mac, but there is an alternate way to set the clipping area without using two rectangle:
- Let's call `L` the label's bounding box.
- First, we have to get the intersection of `L` and `g`, let's call it `R`. We have `R = L.getIntersection(g)`
- Then we have to define the Path as a polygone that goes through:
   - (g.x, g.y)
   - (R.x, R.y)
   - (R.x+R.width, R.y)
   - (R.x+R.width, R.y+R.height)
   - (R.x, R.y+R.height)
   - (R.x, R.y)
   - (g.x, g.y)
   - (g.x, g.y+g.height)
   - (g.x+g.width, g.y+g.height)
   - (g.x+g.width, g.y)
   - (g.x, g.y)

**Comment by Phillipus** [comment]
> Do you mean that it works if we simply set the clip area to the label ?

The opposite. I mean the drawing area. I'll try a path like you suggest, thanks.
