### ISSUE TITLE
[Feature request] See/switch between "Most recent" diagrams

### ISSUE THREAD

**Issue by bhsolberg** [archimatetool/archi#532]
When working with many diagrams open, it would be useful to be able to switch between the most recent open/active diagrams as this would save time from having to navigate the Models window or scan through the open diagrams to find the previous one(s) I was working on. E.g.Ctrl-Tab and Shift-Ctrl-Tab to navigate backward / forward in a Most Recently Used list of diagrams.

Thanks,

Bjorn

**Comment by smileham** [comment]
Have you tried "Ctrl-F6"

**Comment by Phillipus** [comment]
> Have you tried "Ctrl-F6"

I have now, thanks!

**Comment by bhsolberg** [comment]
Ctrl-F6 Doesn't do anything in Archi on a MacBook Pro. It has a "touch bar" instead of real keys for F1-F12, and I first had to activate the F1-F12 keys for the touch bar for Archi (it was empty by default). F1 for help works, but F6 does nothing with any of the modifier keys (Ctrl, Option, Command, Shift, ...). I can't see a way to adjust/configure the hot keys for Archi either in the "Preferences" menu or otherwise?

**Comment by smileham** [comment]
According to this post "Ctrl-Page Up"/"Ctrl-Page Down" could work too https://stackoverflow.com/questions/4150072/what-are-the-shortcut-keys-to-change-to-the-next-and-previous-tab-in-eclipse-on?rq=1

Seems to work on Windows, might be Command PgUp/PgDown on Mac?

**Comment by bhsolberg** [comment]
Ctrl-PgUp/Down takes you to the next and previous tab across the set of open tabs. What I find more useful when working with many tabs open and on 2-3-4 tabs at a time is to be able to move back and forth between the most recently used / visited tabs so I can quickly switch between the 2-3 diagrams I'm currently working on. The set of open tabs is simply in the order they were first opened... Cmd-[/] or Cmd-{/} doesn't do anything either (except splits the canvas). Hmm....

**Comment by Phillipus** [comment]
Ctrl-E will bring up a list of recents in a popup.

**Comment by bhsolberg** [comment]
I can confirm that this works in the latest version, rather with Command-E on OSX. Thank you! What would be even better is to also provide a quick visual of the diagram, and using a hotkey (a la Ctrl-Tab and Shift-Ctrl-Tab) to navigate back and forth in the history with the visual outline of the diagram. It's easier to find the right diagram through the visual (and name) rather than just the name, and quicker to navigate through a hotkey rather than one for bringing up a list and another for navigating the list - requires more finger movement.

**Comment by Phillipus** [comment]
> What would be even better is to also provide a quick visual of the diagram, and using a hotkey (a la Ctrl-Tab and Shift-Ctrl-Tab) to navigate back and forth in the history with the visual outline of the diagram. It's easier to find the right diagram through the visual (and name) rather than just the name, and quicker to navigate through a hotkey rather than one for bringing up a list and another for navigating the list - requires more finger movement.

It's unlikely that I'll implement that anytime soon. But if anyone else wants to have a go at implementing it please do.
