### ISSUE TITLE
Scroll bar appears in Element name box

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#533]
### Version of Archi, Operating System
4.6 beta, Windows 7

### Expected Behaviour
Renaming element box shows full size when naming component

### Actual Behaviour
Small scroll bar appears on right hand side of field.

### Steps to Reproduce the Behaviour
1. Open model
2. Open View
3. Add Element
4. Scroll bar appears in element name field in view.

**Comment by Phillipus** [comment]
This is intended. This is to distinguish single-line text controls from multi-line text (Notes, Stickies, etc). If the edit control showed full size like the multi-line text controls users might press return to create a new line. It's intended as a hint that a name is single line.

**Comment by smileham** [comment]
That's interesting, I would assume the opposite, if there is a scroll bar present, then I would expect the box to support multiple lines, but if there is no scroll bar present, then it is just a "single line" field.

**Comment by Phillipus** [comment]
The idea is to not have one long single line edit control that grows infinitely to the right (not good with long names). The only way to do that is to use a multi-line edit control which has a scroll bar. Otherwise we're back to square one.
