### ISSUE TITLE
Maven 3.6.2 build fails

### ISSUE THREAD

**Issue by indeyets** [archimatetool/archi#534]
It looks like Maven 3.6.2 is not compatible with polyglot-maven. see: https://github.com/takari/polyglot-maven/issues/200

I get almost immediate failure with any `mvn` command with lots of errors similar to:

> [FATAL] Non-readable POM (…)/archi/com.archimatetool.canvas/.polyglot.build.properties: input contained no data @

I doubt there's anything to be done on Archi side. Creating issue so other people could find it

**Comment by Phillipus** [comment]
OK, thanks for the heads up. We're using Travis CI for unit tests so let's hope that they don't update to 3.6.2. Do you know if Apache are aware of this?

**Comment by indeyets** [comment]
They are: https://issues.apache.org/jira/projects/MNG/issues/MNG-6765

**Comment by Phillipus** [comment]
Thanks. So I wonder who need to fix it? Maven or polyglot?

**Comment by indeyets** [comment]
It's on polyglot's table until they can prove it's maven's issue :)

**Comment by Phillipus** [comment]
Looks like Apache is fixing this in Maven 3.6.3.

https://github.com/takari/polyglot-maven/issues/200#issuecomment-547086494

**Comment by Phillipus** [comment]
I've tested with Maven 3.6.3 and it all seems to work now:

https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/

3.6.1 has a bug that leads to the "Missing requirement" error
3.6.2 fixed the bug in 3.6.1 but broke polyglot support

So, use either 3.6.0 or 3.6.3.

Unfortunately both Travis CI and GitHub CI Actions are using Maven 3.6.2. With Travis CI I am able to download and use 3.6.0 but I can't see how to do this with GitHub CI Actions.
