### ISSUE TITLE
No editor when renaming in model tree

### ISSUE THREAD

**Issue by Ridderby** [archimatetool/archi#537]
### Version of Archi, Operating System

64 bit Gentoo Linux
Archi 4.6.0 Beta 1. 

### Expected Behaviour

When changing an elements name in the model tree it shall be interactive via an one line text editor. 

### Actual Behaviour

No editor shows. User can edit but nothing is visible until enter is pressed and changes are applied. 

### Steps to Reproduce the Behaviour
1. Mark an element in the model tree. 
2. Press F2 to edit the element name

**Comment by Phillipus** [comment]
Is this specific to Gentoo? Can you test with another Linux? Or perhaps a different theme.

There are some issues with GTK 3 and Eclipse SWT on some Linux versions. If this is one of them it will have to narrowed down to either GTK, a certain theme or Eclipse SWT. These are not Archi specific issues.

**Comment by Phillipus** [comment]
Also, does it occur in Archi 4.5.1?

Are there other Eclipse-based apps that have an inline editor to compare?

**Comment by Ridderby** [comment]
This also applies when a new element is created, editor is not visible but changes still apply.

**Comment by Ridderby** [comment]
IT does not apply to Archi 4.5.1, i crosschecked this morning. 
I run KDE and there is some theme issues here and there. Mostly related to the KDE scroll bar popping up in the last space down and right in the model covering the last piece making it difficult to resize an item. 

I might be able to try it on Artix linux (arch-based) but that is still under KDE. I don't use eclipse for anything else but perhaps I can download and try eclipse out of the box later. 

Perhaps someone else with a different linux and perhaps Gnome can complement me and try out the beta.

**Comment by Ridderby** [comment]
I toggled between two themes in KDE, then changed GTK2-theme from Adwaita to Breeze (the KDE theme) and restarted Archi 4.6.0 Beta 1 and it just works like a charm. 

Actually, putting the settings back won't let me reproduce the problem so it seems like a problem on my side. Sorry for troubling you with this.

**Comment by Phillipus** [comment]
Goof to hear. But there are some issues involving  Eclipse SWT widgets, Linux, GTK and some themes. For example, on Linux Mint Cinnamon I can't edit the first row in a table in Archi 4.5.1, but I can in Archi 4.6. What changed? The Eclipse SWT behaviour, I guess.

If Linux widget issues are found the general advice is to try different themes and narrow the issue down. It may be a theme issue, a GTK issue or an Eclipse SWT issue. Usually, there's nothing I can do about it in Archi's code as Archi uses the standard SWT widgets.

**Comment by Phillipus** [comment]
Anyway, thanks for testing 4.6 beta.

**Comment by Ridderby** [comment]
No, thank YOU for developing it.

**Comment by Ridderby** [comment]
Tee most annoying thing with Archi in KDE is that the last row in the Model tree is heart near impossible to click on. The model is perfectly sized but when I move into it it adds scroll bars in the inside, covering the last entry in the tree. I blame it on KDE and the direction of KDE-ifying GTK. Similar problems is in LibreOffice as well. I don't expect you to solve that but perhaps I should post a ticket on KDE ;)

**Comment by Phillipus** [comment]
There is an issue with those auto/hide/show scroll bars in GTK. I can't remember it but if you Google it you can sometimes mitigate the problem by turning this setting off.

**Comment by Phillipus** [comment]
Whilst checking the tree edit control on Linux Mint Cinnamon I noticed that the edit text control's height was too small, so I've increased this for the next 4.6 beta.

**Comment by Phillipus** [comment]
I think we should close this issue now, as this is more of a general thing.

**Comment by Ridderby** [comment]
I agree.
