### ISSUE TITLE
[Feature Request] to be able to run Archi under Linux running on ARM processors such as Raspberry Pi 4 or Linux on Dex

### ISSUE THREAD

**Issue by AwsTaha** [archimatetool/archi#539]
### **[Feature Request] to be able to run Archi under Linux running on ARM processors such as Raspberry Pi 4 or Linux on Dex (Samsung Tab S4 or Samsung Note 9 running Dex)**

**I have downloaded the latest Archi from [https://www.archimatetool.com/download/](https://www.archimatetool.com/download/ )
under linux that is running on a device with ARM processor such as Raspberry Pi 4 or Tinker Board S or Linux on Dex (Samsung Tab S4 or Samsung Note 9 running Dex) 
then tried to run Archi program file, it did not work, (I am anticipating that the Archi is compiled for Intel processor so it did not work )
Yet, you know that java can run in ARM Linux so Archi should be able to do so
I think it is just needed to do a build for Archi from source code inside Linux running on ARM System.**

**Comment by Phillipus** [comment]
Sorry, that platform is not supported by the Eclipse SWT libraries.
