### ISSUE TITLE
[Tutorial or guidance needed] How to add a new element's property section and use Features?

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#540]
Hi @Phillipus ,

Now that we have the new [Features](#530) API and that [property section has been reworked](#358), I'd like to use both to add new features to Archi. But I have one issue, I need some guidance (and I think I'm not the only one).

So I'm opening this issue to keep track of your advices (and my progress if any). At the end, my goal is to write a new wiki page directed toward potential contributors.

As we need something to work on, here is the use-case I want to implement: object's label customization, similar to what @herve91 is doing in his first [specialization plugin](https://github.com/archi-contribs/specialization-plugin/wiki/Replacing-Labels). I even plan to use compatible macro format (why reinvent the wheel).

So what I'd like to achieve is:
- When a visual object (element, relationship, note, grouping...) is selected, a new property section "Label" is visible. BTW, what a "property section" is, is not clear to me. Is it a new tab (like "Main, Properties, Analysis, Appearance) or a new section in an already existing tab)
- This section would contain a "Use custom label" checkbox and (if checked) an editable text field (which will contain the label text of formula)
- The (bolean) value of "Use custom label" and the (string) value of the text field would be stored in features
- The figure drawing classes would be updated to use the custom label when needed.

So, where do I start? ;-)

**Comment by Phillipus** [comment]
It's not as simple as providing a general magic bullet tutorial as each change to the UI affects different parts of the code

When I implemented "Features" I made one deliberate commit that demonstrates the changes needed to implement hiding a relationship name:

https://github.com/archimatetool/archi/commit/059531c91fe3617a4397ee4d193cca92dc6d180a

This affects the connection Figure and the property section. The important thing is to ensure that the Feature change is put on the Undo/redo stack using a `FeatureCommand` as can be seen in `DiagramConnectionSection`

For the use case above, I checked what would need to change. At first glance it would affect the following areas:

- Property Sections would need to be refactored and/or added (AbstractNameDocumentationSection) with relevant FeatureCommands and Undo/redo support
- AbstractDiagramConnectionFigure would need to query the Features to show the relevant text
- AbstractTextControlContainerFigure would need to query the Features to show the relevant text
- MultiLineTextDirectEditManager would need to be refactored to query the Features to edit the relevant text
- Unit tests for feature changes
- Checks in other parts of the UI would need to be made to see how this affects reports, csv, exchange format, jArchi, coArchi, etc...

Perhaps other things but I would need to check.

**Comment by jbsarrodie** [comment]
Thank you. That's a good starting point for me. I should be able to manage now :-)

**Comment by Phillipus** [comment]
> Thank you. That's a good starting point for me. I should be able to manage now :-)

But...the next theme for Archi is "UI x2" and I can implement this use case in that stretch, amongst other things (font awesome, bend points, etc) ;-)

**Comment by jbsarrodie** [comment]
Of course you could, but the value (for me) is in learning ;-)

**Comment by Phillipus** [comment]
> I even plan to use compatible macro format 

What does that mean? ;-)

**Comment by jbsarrodie** [comment]
If you look at the like pointing to Herve's plugin wiki, you'll see that we can use macro like ${name}, ${documentation} and other (some still not documented outside of the code). This is really powerful and solves several common use cases.

**Comment by Phillipus** [comment]
> If you look at the like pointing to Herve's plugin wiki, you'll see that we can use macro like ${name}, ${documentation} and other (some still not documented outside of the code). This is really powerful and solves several common use cases.

OK, you can do that part. ;-)
