### ISSUE TITLE
Is there the ability to delete node but retain content in diagram

### ISSUE THREAD

**Issue by peterprib** [archimatetool/archi#542]
This may be a new feature requirement.  I duplicate diagram drawing for new alternative variate or simplified diagram and find I want to retain node content for nested nodes but delete containing node from view.  This could be extended to moving the containing node without moving content on diagram or even just doing move so can be moved out the way then deleted.

**Comment by peterprib** [comment]
I have used this solution but is problematic if many nodes involved along with connections.  One has to get the nodes back in exact same place.  Thought it would be very simple to improve as node to delete is highlighted without containing nodes so just a matter of adding new option and changing point in code where it processes dependents..

**Comment by Phillipus** [comment]
There are many selection options such as "Select Contained Nodes" in the selection tool from the palette,

**Comment by peterprib** [comment]
Aware of those options. Proffering this as a quick win in ease of use.  Easier to move/delete one node than move many twice
