### ISSUE TITLE
Arguments are not passed along to Archi if started using Archi-Ubuntu.sh

### ISSUE THREAD

**Issue by Ridderby** [archimatetool/archi#544]
### Version of Archi, Operating System

4.6.0 Beta 2 (valid also for Beta 1)

### Expected Behaviour

Arguments shall be passed along to archi, also via the ubuntu starter Archi-Ubuntu.sh.

### Actual Behaviour

Arguments are ignored. 

### Steps to Reproduce the Behaviour
1. Start Archi-Ubuntu.sh using a relevant argument

Code snippet, last line in Archi-Ubuntu.sh from archi 4.3: 
`$dir/Archi $*`

Same from 4.6.0, both betas:
`$dir/Archi `
(arguments are not passed). 

I figure you will change this easier than receiving a pull request, though I will make one if it will help.

**Comment by Phillipus** [comment]
The current Archi-Ubuntu.sh is:

```
#!/bin/bash
export UBUNTU_MENUPROXY=0
dir=$(dirname $(readlink -m $0))
$dir/Archi
```

I'm not even sure if  `export UBUNTU_MENUPROXY=0` is relevant any more.

What do you suggest for arguments? (PR not possible as this file is not in GH)

**Comment by Ridderby** [comment]
I have no clue what the proxy-stuff does and but while I am running kubuntu I might try out starting it as on other linuxes and see if I discover anything. 

I suggest to add 
$*
(space dollar star)
to the $dir/Archi line. $* will expand to the argument list of the script and pass all arguments on to Archi. 

My modified script:
`#!/bin/bash
export UBUNTU_MENUPROXY=0
dir=$(dirname $(readlink -m $0))
$dir/Archi
root@nuffsan:/usr/local/archi# vim archi-4.6.0-beta2/Archi-Ubuntu.sh 
root@nuffsan:/usr/local/archi# more archi-4.6.0-beta2/Archi-Ubuntu.sh
#!/bin/bash
export UBUNTU_MENUPROXY=0
dir=$(dirname $(readlink -m $0))
$dir/Archi $*
`

**Comment by Phillipus** [comment]
I'm not sure we even need `Archi-Ubuntu.sh` any more. It was originally supplied because there was an issue with menus not displaying in older versions of Eclipse. Hence the `export UBUNTU_MENUPROXY=0` line. Normally you can start Archi from the executable `Archi` file and use any arguments with that.

**Comment by Ridderby** [comment]
I have traced this from eclipse to launchpad and [bug 618587](https://bugs.launchpad.net/ubuntu/+source/libdbusmenu/+bug/618587). Itis actually unclear if there is a real fix or the solution is the UBUNTU_MENUPROXY. The problem seems to apply to Unify. 

Ubuntu have abandoned unify since 18.04 but there might still be LTS versions out there. 
I suggest the following:

Name the script to Archu-unify.sh 
With the following content:

```
#!/bin/bash
# This script solves a bug in dbus for Ubuntu/Unify where menus fails for eclipse based application. 
# Ref: https://bugs.launchpad.net/ubuntu/+source/libdbusmenu/+bug/618587
# and https://bugs.launchpad.net/ubuntu/+source/unity-gtk-module/+bug/1208019
# Use this script if this problem is experienced. 
# The script it not known to make any difference for other desktops than Unify

export UBUNTU_MENUPROXY=0
dir=$(dirname $(readlink -m $0))
$dir/Archi $*
```

**Comment by Ridderby** [comment]
BTW
It is possible that this applies to all Unify users and even though Unify is not default in Ubuntu any more it is fully possible to install it from Ubuntu or any other distro.

**Comment by Phillipus** [comment]
Added this to latest beta version. Kept the original file name but added the comments.

**Comment by WatchTh1** [comment]
For linux desktop distros i'd suggest to make a .desktop file, and make an installer *.sh-script to make it be. This one I use in my current environment.
/usr/local/sbin/archi  - simlink to archi binary. The desktop file itself could be placed either at /usr/share/applications/ if someone needs a systemwide entry, or at $HOME/.local/share/applications if there's a need to make it user personal applink.

Entry code I'm currently using:
`[Desktop Entry]
Name=Archi Archimate modeler
Name[ru]=Archimate моделер 
GenericName=Archi modeler
Comment=Create and edit your archimate models
Comment[ru]=Средство создания моделей Archimate
Keywords=Archimate;model;
Keywords[ru]=Моделирование;
Exec=/usr/local/sbin/archi %U
Icon=archi
Terminal=false
Type=Application
Categories=Development
X-MultipleArgs=false
StartupNotify=true
`

**Comment by Phillipus** [comment]
Close this one now that 4.6 is released.
