### ISSUE TITLE
HTTP Link doesnt support intranet style URL (without dot) : regex still too restrictive

### ISSUE THREAD

**Issue by Plepoutre2019** [archimatetool/archi#546]
When you type a link in a description with have this form, regex doesnt detect it as an URL
Examples :
http://server/folder/doc.htm
https://docproject/folder/file.html

This fail because our current regex needs a dot as mandatory (domaine style url).
I think it only have drawbacks. Lots of corporate intranet server use an alias and some dont provide access to an domain style url like http://server.domain.ext/xxx/yyy

In august we had an issue (#509) with accents and special characters, so this should be the current version of regex :
(http|https|ftp)://([\w-]+\.)+[\w-]+([\w-./?%~#!+@:&=\(\)[\u00C0-\u017f]]*)?

Solution : 
We should just add ? right afer the first dot :
(http|https|ftp)://([\w-]+\.?)+[\w-]+([\w-./?%~#!+@:&=\(\)[\u00C0-\u017f]]*)?

Test data :
https://acp.andritz.com/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25%20Modèle%20conceptuel.graphml
https://intranet/sba/0664/IT/APG/ASAP/Shared%20Documents/1%20-%20Enterprise%20Architecture/Modeles_Archi/Shipping/2019_02_25%20Modèle%20conceptuel.graphml

**Comment by Phillipus** [comment]
Fair enough. But this one doesn't work:

http://s/folder/doc.htm

**Comment by Phillipus** [comment]
TBH after all of the many iterations of the regex, I think it might be easier to simply use this:

`"(http|https|ftp)://\\S*"`

That is, it starts with either http, https, ftp and includes any non-space characters after that.

**Comment by Phillipus** [comment]
The simpler regex is in Archi 4.6 beta 3.

**Comment by Plepoutre2019** [comment]
Thank you for the quick response and that great project

**Comment by Phillipus** [comment]
Also added `file://` to the regex. This will be in next release. (An interesting side effect is having a URL like `file://mymodel.archimate` which, on Windows at least, opens that model in Archi.

**Comment by Phillipus** [comment]
Close this one now that 4.6 is released.
