### ISSUE TITLE
[Enhancement] Archimate 3.1 support

### ISSUE THREAD

**Issue by rojoweko** [archimatetool/archi#547]
Are there any plans to support Archimate 3.1? The new specification seems to be about to be released.

**Comment by Phillipus** [comment]
When The Open Group announce a new version, we'll be sure to take a look at what's new. I'll close this until then. ;-)

**Comment by Phillipus** [comment]
Archi 4.6 beta 4 has now been released with ArchiMate 3.1 support. Sorry I couldn't say before, as I was waiting for The Open Group to make the official announcement first.

**Comment by rojoweko** [comment]
Awesome! Thanks a lot! ;-)
