### ISSUE TITLE
Canvas Views not Exported / Imported

### ISSUE THREAD

**Issue by Glomal** [archimatetool/archi#549]
'Ordinary' Archi Views are exported into the Open Model Exchange XML file and imported.
That is fine and good - and I can use that mechanism to move views between model files as part of some model versioning system.

However, Canvases do not seem to be exported - and so cannot be imported. Since I use Canvas views to assist in read-only navigation of the model for non-Archi users this makes and since Archi insists on creating a new model on an XML import rather than importing into current models this makes upversioning a model navigation infrastructure across files difficult.

I would suggest two missing features in Archi: 1) import XML data into an existing model rather than creating a new model and 2) export and import of canvases in the Open Model Exchange XML.

**Comment by Phillipus** [comment]
> 1) import XML data into an existing model rather than creating a new model

This is not the intention of the ArchiMate Exchange Format so this won't be implemented (however, should someone wish to write an implementation that does this, they can). 

> 2) export and import of canvases in the Open Mode

The ArchiMate Exchange Format does not support these kind of Views and canvas objects so this is not possible.
