### ISSUE TITLE
Display the Strength of an Influence in the Visualiser

### ISSUE THREAD

**Issue by mtilley-qq** [archimatetool/archi#551]
Would it be possible to display the strength of an influence relationship in the Visualiser, in the same way as it does in Views?

**Comment by Phillipus** [comment]
Yes, that's easy enough to implement.

I wonder if this needs to be optional?

**Comment by mtilley-qq** [comment]
That's fantastic.  I think having it as an option would be a good idea, if that would be possible in the future

**Comment by Phillipus** [comment]
Close this one now that 4.6 is released.
