### ISSUE TITLE
Dialog font is always used for SVG export

### ISSUE THREAD

**Issue by Ridderby** [archimatetool/archi#552]
### Version of Archi, Operating System

Gentoo Linux 64 bit, KDE, Archi 4.6.0 beta 3
This has been a problem for several versions, I just found out why now. 
### Expected Behaviour

Default font settings are 9pt Serif. 
This is the font used in diagrams in Archi, in PNG-exports and is alos expected to be used in SVG exports. 

### Actual Behaviour

The font Dialog and size 9.75 with the result that text won't fit into it's frame and that the last character is cliped. 

### Steps to Reproduce the Behaviour
1. Create diagram
2. Export to SVG
3. Open in Inkscape and font settings are Dialog 9,75pt

**Comment by Phillipus** [comment]
Is it the same problem with other fonts?

**Comment by Ridderby** [comment]
The SVG-atribute font-family seems to be omitted when the default font is used but set when another font is used. I think this is the font core problem.

**Comment by Ridderby** [comment]
When I am using 9pt font size in the Archi settings the SVG-atribute font-size is set to 13px which seems to render a slightly larger font at the end. I manually changed this to 9pt (instead of px) and it renders perfectly in inkscpae. 9pt also is accepted as a value on https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Values but I cannot find a specification that clearly states that pt is a valid unit for font size in SVG. I am an beginner in both SVG and CCS so someone else might probably know better. Pt seems to work though. 

If I set the font size in Archi to 10pt it will show up as 14px in the svg. Perhaps there is some formula for pt to px conversion that need trimming.

**Comment by Ridderby** [comment]
I realize that this is actually two tickets; one for the font and one for the font-size. Shall I create a second one?

**Comment by Ridderby** [comment]
According to this site: https://websemantics.uk/articles/font-size-conversion/
9pt shall be converted into 12px which converts back to a perfect 9pt size in Inkscape.

**Comment by Phillipus** [comment]
Please check if this still happens with Archi 4.7.
