### ISSUE TITLE
Add github sponsor button, and link with patreon

### ISSUE THREAD

**Issue by dkdndes** [archimatetool/archi#554]
Displaying a sponsor button in your repository

You can add a sponsor button in your repository to increase the visibility of funding options for your open source project.

Patreon | patreon: USERNAME
-- | --

See: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

**Comment by Phillipus** [comment]
Thanks for the heads up, I've been meaning to do this.

Done!

**Comment by AleksandarDamnjanovic** [comment]
Thank you so much :+1:
