### ISSUE TITLE
Installing through homebrew fails

### ISSUE THREAD

**Issue by kevin-smets** [archimatetool/archi#561]
### Version of Archi, Operating System
None, Mac OS Mojave

### Expected Behaviour
Homebrew should install when running `brew cask install archi`

### Actual Behaviour
The install fails with a 404 error:

```
==> Downloading https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip

curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'archi' with message: Download failed: https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
```

Download link should be `https://www.archimatetool.com/downloads/20191111/Archi-Mac-4.6.0.zip`

### Steps to Reproduce the Behaviour
1. `brew cask install archi`

I've checked the documentation over at the homebrew repo: https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/curl_error.md and thus ended up here :).

**Comment by Phillipus** [comment]
Not an Archi issue. Please take this up with them.
