### ISSUE TITLE
[Bug] On MacOS a detached window does not display on secondary monitor

### ISSUE THREAD

**Issue by stephanbuys** [archimatetool/archi#565]
### Version of Archi, Operating System
Archi 4.6, MacOS Catalina 10.15.1

### Expected Behaviour
When detaching a Window (through drag and drop) from a docked state, this new window should be able to be dragged to a secondary monitor (to enable seeing more).

### Actual Behaviour

When detaching a Window (through dragging) from a docked state, when that window is dragged to a second monitor it does not display.

### Steps to Reproduce the Behaviour
1. Pick a docked tool window 
2. Click and drag the toolbar of the window until the window is detached
3. Drag that new window to a different display
4. The new detached window stays only on the same display as Archi

**Comment by Phillipus** [comment]
I won't be able to take a look at this since I don't have dual monitors with Mac.

It might be either a Catalina issue or an Eclipse issue. One way to narrow it down would be try this on Mojave. Also test to see if the Eclipse 4.13 IDE itself does this - https://www.eclipse.org/downloads/

**Comment by Phillipus** [comment]
I get a feeling this may be down to Eclipse - https://wiki.eclipse.org/Improve_multi-monitor_support

@stephanbuys If you could test with Eclipse IDE itself then we can decide whether to pursue this or not.

**Comment by stephanbuys** [comment]
@Phillipus I think you are correct, I tried with the latest Eclipse and also no luck - it's a shame, but luckily I can manage with the current limitations.

**Comment by Phillipus** [comment]
OK, thanks for testing. Let's close this one since we can't do anything about it.
