### ISSUE TITLE
[Feature Request] Command line support without graphics requirements

### ISSUE THREAD

**Issue by nicorikken** [archimatetool/archi#567]
I'm setting up a build pipeline, to automatically generate the HTML diagrams from my model in a Git model repository. If I use the commandline in a self-built Docker file, I get a link error on GTK.
The https://github.com/qbarlas/archimatetool Docker image solves this by bringing a graphics stack.

If possible with Eclipse, it would be nice to be able to generate reports from the commandline without needing a graphics stack, to reduce complexity and size of the Docker image.

**Comment by jbsarrodie** [comment]
Hi, This has been answered several time and answer is, unfortunately, no, that's not possible.

**Comment by Phillipus** [comment]
Indeed that is correct. In order to generate images we use the Eclipes GEF/Draw2D framework which requires a Display device, even if its a virtual one. The same is true for running headless unit tests.
