### ISSUE TITLE
Stable download URL for Archi

### ISSUE THREAD

**Issue by ludovicc** [archimatetool/archi#569]
Hello,

I am writing an installation script for Archi with Nix package manager (https://nixos.org/nixpkgs/).

I'm reopening #410 as the URL pattern for downloads has changed recently 

From @Phillipus :

> Having explained the reasons why the URLs change I have now however changed the URLs to use this prefix:
> 
> https://www.archimatetool.com/downloads/4.3.0/
> 
> This won't change now. I'll do the same for future releases:
> 
> https://www.archimatetool.com/downloads/4.3.1/
> 
> https://www.archimatetool.com/downloads/4.4.0/
> 

Archi 4.6.0 does not follow this pattern, the URL is now https://www.archimatetool.com/downloads/75a43a6b4f295fe0f/Archi-Linux64-4.6.0.tgz

I'm trying to make installation of Archi simpler on Linux machines (and probably MacOs), and if this works I will add support for Archi plugins. Eclipse and its plugins are easily installable using Nix.

To keep track of downloads, consider using a CDN, and to motivate first-time users to engage with Archi community and donate, add a welcome screen to Archi.  

Thanks,
Ludovic

**Comment by Phillipus** [comment]
I'll take a look at it.

> add a welcome screen to Archi.

It has one.

**Comment by ludovicc** [comment]
You can use BinTray to host your binaries. It's free for opensource, and statistics are provided.

https://bintray.com/
