### ISSUE TITLE
Cannot create a relation of an element to itself with the magic connector

### ISSUE THREAD

**Issue by timolaine** [archimatetool/archi#570]
### Version of Archi, Operating System

I am using Archi 4.6.0 on Windows.

### Expected Behaviour

The magic connector will not create a relation of an element to itself. This is needed for example for looping processes that trigger themselves. It is possible to create the relation by choosing manually the Triggering relation from the palette, but I do not see why the magic connector should not work as well.

![image](https://user-images.githubusercontent.com/2081960/72242378-fad6e800-35f1-11ea-8d16-be3887cfbd90.png)

### Actual Behaviour

When you try to create a relation from an element to itself with the magic connector, nothing happens.

### Steps to Reproduce the Behaviour
1. Create an element, e.g. Business Process.
2. Pick the magic connector from the palette.
3. Try to make a relation from the element you created to itself.

**Comment by Phillipus** [comment]
This is the expected behaviour for the Magic Connector. Clicking back on the same element cancels the operation.

Selecting a standard connector tool from the palette allows you to create a circular connection.

**Comment by timolaine** [comment]
Thank you for the explanation. Still, I wonder why the cancel behavior is different for the magic connector than the other connectors.

**Comment by Phillipus** [comment]
> Still, I wonder why the cancel behavior is different for the magic connector than the other connectors.

Historical reasons. In earlier versions creating circular connections was a preference and `off` by default. So, when using the MC or the normal connector tool, clicking on the same element cancelled the operation. Then we got rid of the circular connection preference so, now, clicking on the same element with the connector tool creates a circular connection.

I suppose we should have also added this behaviour to the MC to be consistent.

You could re-open this and let it remain as a feature request, but it's low priority for me as I'm working on other things for Archi.

**Comment by Phillipus** [comment]
Actually, I took a look at the code for the MC and it's trivial to implement so if users want this I can implement it for the next version. cc @jbsarrodie

**Comment by timolaine** [comment]
If it's trivial, I think it should be done. It would make the behavior more consistent.

**Comment by Phillipus** [comment]
OK, I'll test it some more and commit it.

**Comment by Phillipus** [comment]
Closing this as it is implemented for the next version. Please re-open if any issues are found when released,
