### ISSUE TITLE
[feature] Simplify installation and launching at freedesktop compatible linux environment.

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#572]
Modern linux distros have nice thing such as *.desktop files describing application to launch. Such files could be placed in a user local home directory to provide nice system integration.

For such integration to be made following conditions should be met:
 1. A .desktop file should be created.
 2. A link to executable should be put into $HOME/.local/bin
 3. $HOME/.local/bin should be ensured to be in $PATH variable
 4. Nice icon should be put into $HOME/.local/share/icons/hicolor

To do such a thing it would be nice to have a distro (*rmp, *deb, etc...) and installation scripts.

.desktop file example (derived from org.kde.application.dolphin.desktop) attached.

[Archi.zip](https://github.com/archimatetool/archi-modelrepository-plugin/files/4097101/Archi.zip)
Pass:1234

**Comment by Phillipus** [comment]
I'll close this because I'm not going to create another download option.
