### ISSUE TITLE
[ACLI] Additional program arguments in Archi.ini cause the command line to fail

### ISSUE THREAD

**Issue by projetnumero9** [archimatetool/archi#573]
I use a packaged and portable version of Archi, for various client-related reasons. 
To automate reports generation, I wrote a Powershell script, which takes as parameters
- the folder in which it will find the `Archi.exe`
- the folder containing the .archimate files from which reports should be generated
- the desired reports format (.HTML, .PDF)

Whole thing works smoothly, thanks to: [Archi Command Line Interface · archimatetool/archi Wiki](https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface) 

Whole thing worked till recently, when we upgraded to Archi version 4.6.0.
Doing some digging around, and thanks to the .LOG generated (stack below), I found that, in `Archi.ini`, the packager added a switch, to enforce the *skin*, if I can express it that way: `-cssTheme org.eclipse.e4.ui.css.theme.e4_classic`
   
First workaround was to remove the incriminated switch from `Archi.ini`.
The second workaround (and which works, I tested it), which was suggested to me by the packager (thanks again by the way!), was 
- to duplicate `Archi.exe` and `Archi.ini` in the same subtree, with a new name (`Archi_duplicate.exe` and `Archi_duplicate.ini`)
- to remove the incriminated switch from the `Archi_duplicate.ini`.

By the way, same error happens when launching: ` 'C:\foo\Archi4.6.0 - packaged\Archi.exe' -console -application com.archimatetool.commandline.app -consoleLog -nosplash --help`

If I understood correctly, this error is more Eclipse-related than Archi-related.
So, just to share the experience,

### Version of Archi, Operating System
Archi 4.6.0, but packaged 😄, Win10

### Expected Behaviour
Reports generated using [Archi Command Line Interface · archimatetool/archi Wiki](https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface).

### Actual Behaviour
Ends in failure.

### Steps to Reproduce the Behaviour
1. add `-cssTheme org.eclipse.e4.ui.css.theme.e4_classic` to `Archi.ini`
2. launch ` 'C:\foo\Archi4.6.0 - packaged\Archi.exe' -console -application com.archimatetool.commandline.app -consoleLog -nosplash --help`

### Error stack

```
!SESSION 2020-01-24 17:32:11.902 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=11.0.5+10
JRE 11 Windows 8 amd64-64-Bit Compressed References 20191031_360 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 775c5eb03a based on jdk-11.0.5+10
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR

!ENTRY org.eclipse.osgi 4 0 2020-01-24 17:32:12.985
!MESSAGE The -clean (osgi.clean) option was not successful. Unable to clean the storage area: C:\foo\Archi4.6.0 - packaged\configuration\org.eclipse.osgi

!ENTRY org.eclipse.osgi 4 0 2020-01-24 17:32:24.475
!MESSAGE Application error
!STACK 1
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -cssTheme
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleConcatenatedOptions(DefaultParser.java:702)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:533)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:81)
	at com.archimatetool.commandline.CentralScrutinizer.processOptions(CentralScrutinizer.java:130)
	at com.archimatetool.commandline.CentralScrutinizer.start(CentralScrutinizer.java:68)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
```

**Comment by Phillipus** [comment]
Can you confirm that adding `-cssTheme org.eclipse.e4.ui.css.theme.e4_classic` to `Archi.ini` was not causing this problem in Archi 4.5.1 or 4.4?

**Comment by Phillipus** [comment]
I've just tested with Archi 4.4 and 4.5.1 and this error occurs in those versions and this is to be expected. The ACLI processes all application arguments including those in `Archi,ini`. So, if you are using the ACLI you should not add extra arguments.

**Comment by Phillipus** [comment]
I'm experimenting with removing any arguments that don't match the ACLI arguments. If this works it will be in Archi 4.7. This will ensure that adding non-ACLI arguments to Archi.ini won't throw an error.

**Comment by jbsarrodie** [comment]
@Phillipus I'm the "packager" ;-)

No need to rush to fix this. We noticed this with my new "packaged" version of Archi and other plugins. I've added `-cssTheme` options for the first time with 4.6 package, but this is not an issue which is 4.6 specific (as you've seen).

The main goal of this issue is to keep track of this very specific configuration so that people who customize their `Archi.ini` file can find the workaround.

**Comment by Phillipus** [comment]
@jbsarrodie Aha!

The issue here is that we don't want the ACLI to fail if there are other program options like `-cssTheme`. The fix I have is now committed to a branch and seems to work; it iterates through all arguments and removes any that don't match any of the ACLI ones.

**Comment by jbsarrodie** [comment]
> @jbsarrodie Aha!

![bitmoji](https://render.bitstrips.com/v2/cpanel/63f35423-4041-47c4-8842-7b202bfcfcd3-c97261fe-73f7-460c-956e-ad0fc53ac950-v1.png?transparent=1&palette=1&width=246)

> The issue here is that we don't want the ACLI to fail if there are other program options like `-cssTheme`. The fix I have is now committed to a branch and seems to work; it iterates through all arguments and removes any that don't match any of the ACLI ones.

I had the same idea, that's also the reason why I wanted us to open an issue.

**Comment by Phillipus** [comment]
This is fixed now and pushed to `master`.

**Comment by Phillipus** [comment]
Closing this as it is fixed for the next version. Please re-open if any issues are found when released,
