### ISSUE TITLE
[Resquest Feature] / [Issue] Properties Addition

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#574]
On the last version of Archi

When I add a new Properties
And I start to add something

Then I click on a new field

The consequence is that the field still in edition is set blank and I lose all the work

But if I click somewhere else, the behavior isn't the same, the field is not reset
<img width="476" alt="note" src="https://user-images.githubusercontent.com/43959255/73193975-b6883380-412b-11ea-9584-1820176dbb97.png">

**Comment by jbsarrodie** [comment]
Is it specific to 4.6 or was it already the same with previous versions ?

**Comment by Phillipus** [comment]
You have to press return or tab to complete the edit in the text field before adding a new property.

**Comment by Phillipus** [comment]
Having said that, it's an easy fix to complete the current edit before adding a new property so it will be fixed in the next version.

**Comment by Phillipus** [comment]
Closing this as it is fixed for the next version. Please re-open if any issues are found when released,
