### ISSUE TITLE
[Enhancement] Warn if user changes a relationship's end while this relationship is used in other views

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#579]
In Archi it is possible to change the relationship's ends (this is done in a view by selection the relationship, then draging the anchor at one end and droping it on another element).

But when doing so, any other view containing the relationship will be impacted (the relationship will be udpated if the new end is also present in the view, or will be removed if the new end is not present) without any prior warning.

It would be good in such cases to warn the user, the exact same way we warn it when deleting an element from the model while it is used in another view.

**Comment by Phillipus** [comment]
Is this a duplicate of #558?

**Comment by jbsarrodie** [comment]
> Is this a duplicate of #558?

Yes, it seems I've just had the same idea as this guy (jbsarrodie) ;-)
