### ISSUE TITLE
Splitting core and archimate

### ISSUE THREAD

**Issue by magwas** [archimatetool/archi#58]
I am preparing a feature branch which is the beginning of the split of the current codebase of Archi to two parts: general metamodel-independent modeling code, and archimate metamodel support. Before even thinking of submitting this, I would like to make sure that I am going in a direction which is okay for you.

Here are the goals and constraints. Please reply which is acceptable and which is not, and add your own constraints.

Goals:
1. Split the general part (core) and the archimate support in a way which supports creating a product (in another repo) which depends on the core, and have different metamodel than archimate.
2. Archi builds correctly
3. All of the current unit tests of archi run successfully
4. Core and archimate support have their own unit tests such that when building Zenta, core unit tests can be used and archimate unit tests are not in the way.
5. In the core there should be no reference to the archimate metodology beyond the fact that the base package name is com.archimatetool.
6. The core will incorporate all of the minimally needed frameworks which support any functionality of Zenta. That is when such a framework is proposed by Zenta developer, the discussion will be about how to support the feature with minimal modification in the core and not about whether the feature should be supported.
6. No intention to do all of the split in one step. This feature branch is about setting up the infrastructure to do so. Goals 2. and 3. should always be satisfied nevertheless.

Constraints:
1. The core and the archimate parts will be in their own directory, both of them have their own tests directory.
2. The core will incorporate frameworks which support functionality needed in Zenta but not needed in Archi, and the other way around. That is the functionality will be implemented in the respective product, but the minimally needed modifications to support that functionality are implemented in the core.
3. The core will not incorporate any functionality which is conflicting with the functionality of either Archi or Zenta. The implementation of functionality which differ with the two products will be factored out into product-specific plugins. This includes metamodel-dependent things like metamodel-specific viewpoint logic, but also those core functionalities where we cannot agree, like the movearound one. The patch to factor out those functionalities in a way which does not break any of the products should be made by the one who do not want to see the functionality in the core.
4. The core can incorporate any functionality which is useful for both of the products. The patch to factor in these functionalities in a way which does not break any of the products should be made by the one who wants to see the functionality in the core.
2. The ecore model will be split into two bundles, somewhere around the current "ArchimateElement" element.
3. ArchimateElement will be renamed to "ModelElement".

**Comment by mwherman2000** [comment]
See my new Feature Request related to this (#110 I think).

**Comment by mwherman2000** [comment]
#257

**Comment by mwherman2000** [comment]
Magwas, did you make any headway on your above proposal?

**Comment by magwas** [comment]
No, unfortunately I have forked the project due to communication problems. My fork is called Zenta.

**Comment by Phillipus** [comment]
"communication problems" - please elaborate.

**Comment by magwas** [comment]
We (Phil and me) were unable to reach a common understanding. I do not blame anyone, I have just tried to state facts in an unbiased way.

**Comment by Phillipus** [comment]
Want to build a gerneral purpose tool with extensible and customisable metamodels in Eclipse?

The Sirius project is thataway ------------------>

Good luck!

Want an ArchiMate tool?

Archi is here.
