### ISSUE TITLE
HTML Report - Create links in property table value fields

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#582]
### Version of Archi, Operating System

I'm using the 4.6 version

### Expected Behaviour

Open a HTTP link from the HTML report.

### Actual Behaviour

The link is accessible from the Main/Documentation field
The link is not accessible from the Property field.
This problem occurs only in the HTML report. This problem doesn't occur in the ARCHI application.

### Steps to Reproduce the Behaviour
1. Create a mode and a new Archimate view
2. Add a HTML link in the Main/Dovumentation field
3. Add a HTML link via the Properties field
4. Check that both links are working in Archi
5. Create a HTML report : File/Report/HTML
6. Open the HTML report, click on the HTTP links to open it

<img width="839" alt="2" src="https://user-images.githubusercontent.com/47627451/74738654-af020900-5257-11ea-9f8e-e791e2c44e85.PNG">
<img width="864" alt="1" src="https://user-images.githubusercontent.com/47627451/74738657-af9a9f80-5257-11ea-90ed-8d74d89ea944.PNG">

.

**Comment by Phillipus** [comment]
I had a quick look at this but couldn't come up with a solution.

@jbsarrodie I think the `<td>` in the table needs to do something similar to the magic in the documentation field with JS, but not really sure?

**Comment by Phillipus** [comment]
I figured out a way to do this now. Will be in the next release.

**Comment by Phillipus** [comment]
Closing this as it is implemented for the next version. Please re-open if any issues are found when released,
