### ISSUE TITLE
[Feature Request] Ability to configure fonts in user interface

### ISSUE THREAD

**Issue by davevint** [archimatetool/archi#583]
I'm using a JArchi script to export the models to markdown format. Amongst other things, this allows tables to be embedded inside documentation using ASCII text. This works easiest if the font displayed when entering the table is fixed-width. Currently the ''Properties->Main->Documentation' text control is locked to the system font. It would useful to have some way to configure that so it can use a fixed-width font such as Courier.

**Comment by Phillipus** [comment]
This is probably a more generalised feature - configure fonts for single and multi text controls (and maybe the tree but perhaps not if it will mess up the icon height).

**Comment by Phillipus** [comment]
But before this we might want to think about if we were to use Markdown for the Documentation field then the font wouldn't matter.  Like this text box that I'm typing in now ("Write") has a system font and the "Preview" tab shows the markdown output.

**Comment by davevint** [comment]
Yes, but I'm using the 'grid_tables' extension in pandoc which looks like this in a non-fixed width font and is therefore difficult to line up the column separators:

+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+

I can't use the 'pipe_tables' since the documentation will go over multiple lines. I guess it depends upon the markdown converter as to what's useful?

**Comment by davevint** [comment]
See https://pandoc.org/MANUAL.html - search for 'grid_tables' extension

**Comment by Phillipus** [comment]
OK, I'll add this to the "To Do" list.

**Comment by davevint** [comment]
Thanks! I have a workaround at the moment which is setting the table up in another text editor and then pasting into Archi.

**Comment by Phillipus** [comment]
I guess something like this might do it:

![fonts](https://user-images.githubusercontent.com/600504/74863723-45acf380-5346-11ea-9eb5-23a9a9a054bf.png)

**Comment by Phillipus** [comment]
Of course this won't affect the fonts used in the HTML report or Jasper reports as these are set differently (CSS for HTML and whatever Jasper Reports uses). This is purely an application UI setting (although I'm sure we'll get many "The font in the HTML report is different than the one in Archi" bug reports...)

**Comment by davevint** [comment]
That's looks perfect!

**Comment by Phillipus** [comment]
Closing this as it is implemented for the next version. Please re-open if any issues are found when released,
