### ISSUE TITLE
[BUG][ALASQL, HTMLReport] ViewsContent.contentid field doesn't contain valid model elements id

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#584]
### Version of Archi, Operating System
Archi version: 4.6
Linux

### Usecase
Extract data from HTML report using AlaSQL query.

### Expected Behaviour
AlaSQL query:
`SELECT * FROM ViewsContent INNER JOIN Views ON ViewsContent.viewid = Views.id WHERE Views.name LIKE '%ViewName%' AND ViewsContent.contenttype LIKE 'DiagramModelArchimateObject'`

Returns table containing elements id as contentid.

### Actual Behaviour
Value contained in ViewsContent.contentid field could not be found amongst model elements.

### Archi forum discussion
https://forum.archimatetool.com/index.php?topic=796.0

**Comment by jbsarrodie** [comment]
This is because ViewsContent contains id of visual objects instead of model elements. This is indeed a bug and I'll fix it for next version.

**Comment by WatchTh1** [comment]
Could you please tell when are you planning to release 4.7 ?

**Comment by gitNelsoncruz** [comment]
Hi 
This si my temporal fix solution.

open file frame.stg in:
..\Archi-Win64-4.5.1\Archi\plugins\com.archimatetool.reports_4.5.1.201908071603\templates\st\frame.stg

line 83:

dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.Id^", contenttype:"^c.Class.SimpleName^"\});

remplace with:
dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.ArchimateElement.Id^", contenttype:"^c.Class.SimpleName^"\});

and line 85:

dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.ReferencedModel.Id^", contenttype:"^c.Class.SimpleName^"\});

remplace with:
dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.ReferencedModel.Id^", contenttype:"^c.Class.SimpleName^"\});

when restart you archimate instance.

¿Please can you validate my solution? .. whis work for my test.

thanks.

**Comment by jbsarrodie** [comment]
> This si my temporal fix solution.
> [...]
>
> ¿Please can you validate my solution? .. whis work for my test.

Hi,

This is almost good, but :

1/ You have to use `.ArchimateElement` and `.ReferencedModel` also for contenttype:

Line 83 becomes:
````
dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.ArchimateElement.Id^", contenttype:"^c.ArchimateElement.Class.SimpleName^"});
````

Line 85 becomes:
````
dataViewsContent.push({viewid:"^view.Id^", contentid:"^c.ReferencedModel.Id^", contenttype:"^c.ReferencedModel.Class.SimpleName^"});
````

**Note:** I haven't tested it, but that's the way it should be.

@Phillipus : I'll test later today and will commit a fix.

**Comment by Phillipus** [comment]
@jbsarrodie Thanks, I'll put out 4.7 EA3 later today. :-)

**Comment by jbsarrodie** [comment]
>Thanks, I'll put out 4.7 EA3 later today. :-)

If you plan this today, I have to publish my other changes quickly...

**Comment by Phillipus** [comment]
> If you plan this today, I have to publish my other changes quickly...

Not really, because there will be EA4 and EA5... EA3 is focussed on bug fixes.

**Comment by jbsarrodie** [comment]
>Not really, because there will be EA4 and EA5... EA3 is focussed on bug fixes.

But I have some client who want to test it because of some features :-)

**Comment by jbsarrodie** [comment]
I've just commited a fix. Will be in EA3

**Comment by WatchTh1** [comment]
> I've just commited a fix. Will be in EA3

Nice! Paciently awaiting for release.

**Comment by Phillipus** [comment]
In the meantime you could manually replace this file:

https://github.com/archimatetool/archi/blob/master/com.archimatetool.reports/templates/st/frame.stg

**Comment by Phillipus** [comment]
Archi 4.7 EA3 released with the fix. Let's close this.

**Comment by WatchTh1** [comment]
Bugfix confirmed. Tested. Thanks!

**Comment by WatchTh1** [comment]
Seems like bug is fixed for concepts but bot for relationships.
SELECT * FROM Views AS v INNER JOIN ViewsContent AS vs ON vs.viewid = v.id WHERE v.name LIKE 'ViewName'
Gives a table like:

13 | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | ArchimateDiagramModel | ViewName |   | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | 3981d96c-e4a9-4b6c-b69a-f4fa10e1d1f5 | BusinessRole
-- | -- | -- | -- | -- | -- | -- | --
14 | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | ArchimateDiagramModel | ViewName |   | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | e5d05b59-4803-40a3-926e-07b00f35ef5d | DiagramModelArchimateConnection
15 | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | ArchimateDiagramModel | ViewName |   | e28a7ef9-38a1-4068-9ad8-ed4cde0f59ad | 77ff2817-a708-4d26-9568-332c9ec7bac6 | DiagramModelArchimateConnection

**Comment by jbsarrodie** [comment]
FIxed. Will be in 4.7. You can test by manually replace this file:

https://github.com/archimatetool/archi/blob/master/com.archimatetool.reports/templates/st/frame.stg

**Comment by WatchTh1** [comment]
Thanks, i'll try to fix it on my instance. Just got a time to check, sry for long silence.
