### ISSUE TITLE
Generate View For Elements - "Add all available connections" mystery option

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#585]
When using the "Generate View For..." feature selecting "Add all available connections" doesn't seem to do anything.

These are the line in the code (`GenerateViewCommand.java`):

```
// Don't add connections that are not connected to the main elements if option is set
if(!fAddAllConnections && !(fSelectedElements.contains(elementSource)) && !(fSelectedElements.contains(elementTarget))) {
   continue;
}
```

There might be a mistake in that one line so it should be:

```
if(!fAddAllConnections && !(fSelectedElements.contains(elementSource) && fSelectedElements.contains(elementTarget)))
```

But, to be honest, I can't remember why we would want such an option. Maybe it could be removed.

See https://forum.archimatetool.com/index.php?topic=799

**Comment by Phillipus** [comment]
It _does_ do something if you select different elements for the "Generate View" command.

For example, given this:

![1](https://user-images.githubusercontent.com/600504/75371734-30444600-58bf-11ea-8edc-d47d4ae5232e.png)

If you select elements A and D and do a "Generate View" with the option deselected you get:

![2](https://user-images.githubusercontent.com/600504/75371811-5964d680-58bf-11ea-9237-b07e8070fc03.png)

If you select elements A and D with the option selected you get:

![1](https://user-images.githubusercontent.com/600504/75371734-30444600-58bf-11ea-8edc-d47d4ae5232e.png)

**Comment by jbsarrodie** [comment]
I don't understand because:
1. I sometime use this option
2. As far as I can tell, it works

**Comment by Phillipus** [comment]
@jbsarrodie Yes, it does. I just couldn't remember...

**Comment by jbsarrodie** [comment]
When in doubt, ask an Archi user you know ;-)

**Comment by Phillipus** [comment]
![alt text](https://static.skaip.org/img/emoticons/180x180/f6fcff/headbang.gif "Ah!")
