### ISSUE TITLE
Palette Icons not presented 

### ISSUE THREAD

**Issue by SW7-Tech** [archimatetool/archi#586]
### Version of Archi, Operating SystemArchi 4.7 EA Beta 
Window 7
### Expected Behaviour
Icons to be presented in the Palette Window

### Actual Behaviour
No Icons presented 

![PaletteIcons](https://user-images.githubusercontent.com/55116027/75722675-c5679480-5d2e-11ea-82f8-bec06d52b1f5.JPG)

**Comment by Phillipus** [comment]
1. There should be no difference between Archi 4.7 EA 1 and Archi 4.6 as they are built upon the same frameworks - are you seeing this with Archi 4.6?

1. Did you try with Windows 10?

1. Did you try a new installation and/or clearing the user data area (Help -> Reset Workbench to defaults)?

**Comment by Phillipus** [comment]
Other things to test:

1. If you right-click on a blank area of the palette and choose "Settings" and then "Icons Only" for layout do you then see the icons?

1. Are you using the zip Archi bundle or the installer version?

1. Are the icons missing elsewhere? In the models tree? Other parts of the UI.

**Comment by Phillipus** [comment]
I'll close this as I don't think this anything to do with Archi itself but rather an installation issue. If the icons are missing this suggests that some icon files are missing from the installation. I suggest to re-download the portable zip version and run that.
