### ISSUE TITLE
FEATURE REQUEST: Ability to make a single relationship type selection for a collection of elements dragged into an other element for nesting

### ISSUE THREAD

**Issue by krismeukens** [archimatetool/archi#587]
### Expected Behaviour
When dragging a larger collection of elements onto an other element for nesting, one has the option to make a single relationship type selection for the whole collection.

### Actual Behaviour
When dragging a larger collection of elements onto an other element for nesting, one has to make a relationship type selection for each and every element that is nested which can be quite cumbersome.

### Suggested Behaviour
1. Select the collection and drag it onto an other element
2. Tick the check box for a single relationship type selection for the whole collection
3. Choose one out of the available relationship types that work for the whole collection
4. Press ok.

**Comment by Phillipus** [comment]
If you hold the Ctrl key down when making a selection from the combo box and click on an empty area the selection applies to all (if it is a valid relation).

I'm not going to change the current behaviour as it can be quite flexible.

**Comment by jbsarrodie** [comment]
> If you hold the Ctrl key down when making a selection from the combo box and click on an empty area the selection applies to all (if it is a valid relation).
> 
> I'm not going to change the current behaviour as it can be quite flexible.

? I didn't know this trick. That's really cool (and useful). Thank you!

**Comment by Phillipus** [comment]
Page 40 ;-)

**Comment by jbsarrodie** [comment]
> Page 40 ;-)

The point is that I must be one of the few who really did read the manual (and at least twice), but this is the kind of things I did not noticed of maybe even understood at that time.

Now, the next time someone told me this is too long to change all values I will say: "Hey, this is a simple trick, did you ever read the Fu?#!&& manual?" ;-)
