### ISSUE TITLE
Problem with -Xmx max memory usage in 4.7 beta

### ISSUE THREAD

**Issue by michalradacz** [archimatetool/archi#588]
### Version of Archi, Operating System

4.7 on Windows 10 

### Actual Behaviour

After start of app dialog warning from database plugin appears with warning of maximum 259MB memory usage. Recomended changing "-Xmx" parameter in archi.ini does not work, Archi not use this parameter in 4.7 version.

### Steps to Reproduce the Behaviour
1. Install database plugin
2. Install beta 4.7 EA version of Archi
3. Run Archi...

**Comment by Phillipus** [comment]
If this is related to Herve's DB plugin then I'll close this.

Can you please open the issue here fro Herve to look at:

https://github.com/archi-contribs/database-plugin/issues

**Comment by michalradacz** [comment]
Okay, but when I run Archi, this message appears:

Database import/export plugin v2.2.4  dialog:  Archi is configured with 259 MB max memory. If you plan to use the database plugin with huge models, we recommand to configure Archi with 1 GB of memory (you may add or update the "-Xmx" parameter in the Archi.ini file). You may deactivate the memory check in the database plugin preference page.

May I ignore this, or I may post is as an issue to this plugin. I dont know when its problém of plugin or Archi app itself.

Odesláno z aplikace Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> pro Windows 10

Od: Phil Beauvoir<mailto:notifications@github.com>
Odesláno:středa 4. března 2020 19:09
Komu: archimatetool/archi<mailto:archi@noreply.github.com>
Kopie: Michal Rada<mailto:michal@kancelarmr.cz>; Author<mailto:author@noreply.github.com>
Předmět: Re: [archimatetool/archi] Problem with -Xmx max memory usage in 4.7 beta (#588)


Just a general comment, though, regarding memory usage and Archi.ini.

There is no -Xmx setting in Archi.ini. By default Archi (actually Java) will usually use about 25% of available memory for the maxiumum. So, if your machine has 8GB of RAM then it will allocate 2GB.

If you need more memory allocated then you can add the following to Archi.ini after the -vmargs line and with the value in Mb:

-Xmx2048m

So the -Xmx setting in Archi.ini does work, you have to make sure it comes after -vmargs.

**Comment by herve91** [comment]
Hi Michal,

As Philippus stated, this message is not shown by Archi but by my database plugin. The plugin needs memory to run (especially if you're using big models) so it checks the memory allocated to the JVM and prints a warning message if it is less than 1 GB.

As the message states, the recommended action is to add an "-Xmx" setting in Archi's ini file to increase the JVM memory to 1 GB. Alternatively, you may deactivate this memory check on the plugin's preference page.

As this message is not related to Archi itself, but to the database plugin, I suggest we continue this thread on my plugin's Github page ([https://github.com/archi-contribs/database-plugin/tree/master/v2](https://github.com/archi-contribs/database-plugin/tree/master/v2).

Best regards
Hervé

**Comment by michalradacz** [comment]
Yes, but I have 32GB of RAM, if Archi uses quarter there is 8GB memory allocation, but plugin dialog says that maximum memory is 259MB. Thats my reason to open issue on main Archi repo. If this isnt problém oof Archi memory allocation, I create similar issue on plugin= s repo.


Odesláno z aplikace Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> pro Windows 10

Od: Hervé Jouin<mailto:notifications@github.com>
Odesláno:čtvrtek 5. března 2020 9:01
Komu: archimatetool/archi<mailto:archi@noreply.github.com>
Kopie: Michal Rada<mailto:michal@kancelarmr.cz>; Author<mailto:author@noreply.github.com>
Předmět: Re: [archimatetool/archi] Problem with -Xmx max memory usage in 4.7 beta (#588)


Hi Michal,

As Philippus stated, this message is not shown by Archi but by my database plugin. The plugin needs memory to run (especially if you're using big models) so it checks the memory allocated to the JVM and prints a warning message if it is less than 1 GB.

As the message states, the recommended action is to add an "-Xmx" setting in Archi's ini file to increase the JVM memory to 1 GB. Alternatively, you may deactivate this memory check on the plugin's preference page.

As this message is not related to Archi itself, but to the database plugin, I suggest we continue this thread on my plugin's Github page (https://github.com/archi-contribs/database-plugin/tree/master/v2.

Best regards
Hervé

**Comment by Phillipus** [comment]
Why don't you just add `-Xmx4096m` after `-vmargs` in Archi.ini and try it. And, as Herve, says disable the message in the DB plugin preferences.

This isn't an Archi issue as we just use Java and whatever memory there is.

Herve's code calculates memory as follows:

```
int maxMemory = (int) (Runtime.getRuntime().maxMemory() / 1000000);
```

**Comment by Phillipus** [comment]
BTW - this is neither related to Archi 4.7 Early Access. Did you try with Archi 4.6?
