### ISSUE TITLE
Request: Show relationships in HTML report

### ISSUE THREAD

**Issue by michalradacz** [archimatetool/archi#589]
Request for improvement #improvement 

In HTML report it can be usefull to show new tab in element details Relations with showing all relations of this element. It works fine in Archi itself on Analysis tab in element properties, but not shown in HTML model.

**Comment by jbsarrodie** [comment]
This is considered for the new version of HTML export. More info here: https://github.com/archimatetool/archi/wiki/HTML-export-v3

**Comment by michalradacz** [comment]
Many thanks Jean, I am blind and I am using model for knowledge base too, that can help me. Thanks


S pozdravem

Michal Rada
________________________________
Od: Jean-Baptiste Sarrodie <notifications@github.com>
Odesláno: Wednesday, March 4, 2020 8:04:35 PM
Komu: archimatetool/archi <archi@noreply.github.com>
Kopie: Michal Rada <michal@kancelarmr.cz>; Author <author@noreply.github.com>
Předmět: Re: [archimatetool/archi] Request: Show relationships in HTML report (#589)


Closed #589<https://github.com/archimatetool/archi/issues/589>.
