### ISSUE TITLE
Ci build

### ISSUE THREAD

**Issue by magwas** [archimatetool/archi#59]
This is my proposal, please reply what is acceptable and what is not, and your additional constraints.

Goals:
1. Continous integration using free cloud service, which is drone.io now.
2. CI includes automatic publication of installers to a configureable scp destination. For me it is the "archici" sourceforge project.
3. Stable and unstable releases are clearly separated on the destination, stable meaning builds of the master branch.
4. It is possible to use eclipse as a development environment, and this includes running unit tests and using "Launch an Eclipse Application" from archimate.product
5. It is possible to create and check installers "at home", without submitting to git or cloud, and without network connection
6. One thing is implemented exactly once
7. Build should be possible on supported platforms

Constraints:
1. The CI build uses maven.
2. Maven conventions are adhered.
3. The build uses files only in places where a unprivileged user have write rights.
4. The non-eclipse dependencies of the build (jre installs and Inno Setup) are placed in one artifact in a place which unambigously exists in all supported platform. That is there is one tar.gz or zip, containing all of the three things, and it is within the home directory. Currently it is ~/Downloads/archi-extra.tar.gz
5. Installers are created using maven even "at home".
6. Working (creating installer) without net is possible if both
a) a build have already ran with network which have cached in all the dependencies (e.g. a succesful mvn install)
b) no new dependency have been introduced

**Comment by Phillipus** [comment]
I've implemented a maven build process now. It's not public, though.

**Comment by magwas** [comment]
It does not exists then. You are free to borrow the poms from the Zenta project though.

**Comment by Phillipus** [comment]
Archi is not a "free for all" project. The source code is public, the "Archi" product and build process is not.

Zenta poms are not appropriate.

**Comment by magwas** [comment]
Can I quote you on this? 3:)

**Comment by Phillipus** [comment]
Do what the hell you like. Archi code is open source. "Archi" is a registered trade mark. My build process is appropriate for my branding.

**Comment by jbsarrodie** [comment]
Hi,

My 2 cts on this...

As a user and contributor I don't mind a CI build process. I can work on code locally and export a product easily.

As an Archi team member, I don't find it a necessity to provide all those products/build resources neither. And that's even more logical because at least the Archi logo and Archi brand are copyrighted. We have to be careful about those aspects because if one day Archi becomes a certified tool, this certification would only be meaningful for Archi, not for any derivative work based on Archi.

BTW - Have you seen that now ArchiMate 3.0 is [really open](http://www.opengroup.org/archimate/as30/license_comm) (one can provide consultancy services without having to pay TOG).

**Comment by Phillipus** [comment]
And even if it was that kind of a project it would require proper governance in order to stop every Tom, Dick, and Harry throwing all kinds of shit at it, and trying to turn it into their own pet project, and use it for their own agenda.

**Comment by theunsfvo** [comment]
Hi,

I read the link in the BTW and it seems you still have to get a commercial
license, Jean-Baptiste. Why do you say you don't need to pay TOG for
consultancy services?



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=theunsfvo@gmail.com&idSignature=22>

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by jbsarrodie** [comment]
@theunsfvo : I'm quoting _"For the avoidance of doubt, the use of the Documentation for writing books or the provision of consultancy services does not require a commercial license."_

Don't get me wrong, I don't say ArchiMate standard is _fully_ open, but it is now enough so that a company can use it and rely on some consultants with no need for a commercial license. TBH, the fact that The Open Group is asking  money to have a training or a tool certified is not that bad as the goal is to make sure that nobody claim to support or train ArchiMate where in fact it is not the case. I've seen so many tools claiming to support BPMN where in fact they don't...

**Comment by theunsfvo** [comment]
I agree with the licensing necessity, just a bit confused with the
application of it. For instance, I'm doing consulting for clients and use
ArchiMate to illustrate designs and although the tool is free, you still
need a commercial license to use the standard in the tool, according to the
TOG guys. Unless the 3.0 license works differently than the 2.1 license.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=theunsfvo@gmail.com&idSignature=22>

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by magwas** [comment]
I think that CI is a necessity for:
- reproduceable build process (so you have lower probability to fsck up a release, and you can have good enough release cadence (which in turn correlates with development velocity))
- if you are willing to accept contributions, it is a very good first item on the checklist whether the contribution would be acceptable. I have a feeling that this part is not important to Archi. As you have rightly pointed out, accepting contributions would need some kind of governance, and that seems to be too resource- and communications intensive for you from where I see the project.

Sorry for the bitterness, but I cannot help thinking about that if we could work together, both your goals with Archi, and mines (with Zenta now) would have been better served.

**Comment by Phillipus** [comment]
Setting up a full public CI requires something like Gerrit, and perhaps IP check process, peer review and more - this is the sort of thing that we see at the level of the Eclipse Foundation or the Apache Foundation. For the Archi product that I personally make available I do what I am able to do given the constraints of time and resources. If anyone wants to create an alternative product and process, then they can.

As for working together, I don't think our outlooks are aligned.

**Comment by jbsarrodie** [comment]
@theunsfvo : _"Unless the 3.0 license works differently than the 2.1 license."_ Yes, things have changed with ArchiMate 3.0. A commercial license used to be needed but this is no more the case with version 3.0. This is a huge step forward.

@magwas : I think CI is good (and needed) in big project, but Archi is supported by Phil, and only him. When I look at the number of pull request (that is: almost none), I really don't think an open CI would help. A simplier way to setup a dev environment (like what is now described on Archi website) is much more important asof now.

**Comment by Phillipus** [comment]
To be clear the model for Archi is like Xmind - http://www.xmind.net/ They have free and paid-for products. Source code is available but no public CI process.

**Comment by magwas** [comment]
@jbsarrodie : I think the number of pull requests show that you have a nice healthy project here.
I believe an open CI is more important than you would think at first. It lowers the entry barrier as it shows without any doubt how to build and test the product, and gives you a way to check whether what you did the code actually works.

**Comment by Phillipus** [comment]
https://travis-ci.org/archimatetool/archi

**Comment by magwas** [comment]
Well done, congrats.

**Comment by Phillipus** [comment]
> Well done, congrats.

Thanks for your support. :-)
