### ISSUE TITLE
The Replace Label feature of the specialization plugin stopped working for nodes after Archi 4.5.1

### ISSUE THREAD

**Issue by erikhag1** [archimatetool/archi#593]
Summary:
The Replace Label feature of the specialization plugin stopped working for nodes after Archi 4.5.1. It still works for connections though. Note that the displayed value previously set by the specialization plugin is still displayed, also for "soft" labels like e.g. "${name} [ns:${property:difi:namespace}]".

Additional info: We have relied extensively  on the replace label feature of the specialization plugin  to replace (partly by scipting) the element name with indication of namespace, language and linebreaks.  How to workaround? E.g is there a system property that I can set instead of the label property? (Or work a new feature for this into the to Archi itself?) 

### Version of Archi, Operating System
Windows 10; Archi 4.6 or Archi 4.7 EA2
org.archicontribs.specialization_v1.0.11.jar

### Expected Behaviour
Using org.archicontribs.specialization_v1.0.11.jar, the value of the label property should be reflected in the displayed text of the element in question.

### Actual Behaviour
The diplayed text is no longer affected for nodes/elements when setting the label property (however it still works for connections/relationships).

### Steps to Reproduce the Behaviour
1.  Install org.archicontribs.specialization_v1.0.11.jar (copy to the plugin folder and restart)
2.  Modify the label property of a node/element and observe...
3.  If you like, modify the label property of a relation and observe how it should work.
4. If you like, install Archi 4.5.1 or earlier and see how it used to work.

**Comment by Phillipus** [comment]
This is something for @herve91's plug-in so I'll close this here.

@erikhag1 Could you please report this here:

https://github.com/archi-contribs/specialization-plugin/issues

**Comment by herve91** [comment]
Hi Erik,

I'm using my specialization plugin 1.0.11 at work with Archi 4.6 and it works fine with elements as with relationships. Let's continue this thread on my plugin's GitHub.

**Comment by Phillipus** [comment]
Just to say, I tested it too with Archi 4.6 and 4.7 EA2 and also working for me.

**Comment by herve91** [comment]
Thanks Phil. I asked him to switch the plugin's log to trace and I'll investigate from that.
