### ISSUE TITLE
[Enhancement] Add direct access to "Properties Manager" dialog

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#594]
There seems to be a hidden gem in Archi: the "Properties Manager". Most people don't know it or are not able to find it when needed.

Of course when you Read The Fantastic Manual, you know how to find this "Properties Manager", but I think it would be great to have a more direct access, for example through the "Edit" or "Tools" menu, and/or through the model contextual menu.

**Comment by Phillipus** [comment]
Notes for me:

1. Move `com.archimatetool.editor.propertysections.UserPropertiesManagerDialog` to another package.
1. Seems to be globally accessible via constructor `public UserPropertiesManagerDialog(Shell parentShell, IArchimateModel model)` I can't see it tied to the User Properties Section.

**Comment by Phillipus** [comment]
Done. Added to "Tools" menu.
