### ISSUE TITLE
Why regenerate new IDs when creating a new model from template ?

### ISSUE THREAD

**Issue by Plepoutre2019** [archimatetool/archi#598]
**Hello to all the gods of Archimatetool !**

**Summup**: When using a template, the IDs are regenerated so we can not re-import CSV data to update a model.

**1) First,** We did export from another tool a good part of our CMDB to CSV files.
In those files, we use the internal ID of the CMDB.
For example, application "GAMMA PLUS" has the ID "A0001".
I can see Archimatetool handles this very well.

That's quite handy as if there are changes in the CMDB, we can import again those files to an archi model and this is going to update nicely all the app ! Great !

**2) Next**, we built a nice template that contains all those applications, etc.
However, when we create a new model from this template, all the IDs are re-generated.
For example, application "GAMMA PLUS" has now the ID "436b71ed-6797-4a54-9641-e230743b1589".
So I can no more import CSV updates from the CMDB, has they would be treated as totally different and new objects.

**3) Digging in**
I could see in the ".architemplate" file that the original IDs are preserved, so the problem is at the new model creation time.

**4) Proposal**
Could you add a tickbox to allow keeping the original IDs from the template rather than regenerating new IDs ?

Thank you !

**Comment by Phillipus** [comment]
> Hello to all the gods of Archimatetool !

Greetings, earthling.

Yes, new IDs are generated when a new instance is created from a template, it's been like this since forever. The idea was to create uniqueness of models, especially the model ID. I can understand the advantage of not doing that for your use case, but before changing this we should have a think about what disadvantages there may be. /cc @jbsarrodie

**Comment by Plepoutre2019** [comment]
Wow, so quick response ! I love it !

I think you did regenerate IDs from template to handle "generic object" that could be in a template.
In that case, you don't want that 2 "descendants" of this same generic object could conflict later.

Example : 
Template contains a "Generic web application" ID=1234 in a nice model with "generic database" etc.
New archi model 1  : "Generic web application" is renamed to "Supplier web app" 
New archi model 2 : "Generic web application" is renamed to "Client web app"
if you want to merge (how ? csv ?) those 2 descendants, you need ID to be different to keep both app.

My proposal is just to add the option to keep the IDs. 
Default behavior could stay as today.

Is there anyone thinking of other caveats ?

**Comment by jbsarrodie** [comment]
Hi,

This is by design to make sure that there is no two elements with the same id.

In fact, the key issue is that you should never have used your internal Ids. This feature of CSV import is meant for roundtrips (ie. exporting part of the model from Archi, editing it in another tool like Excel and then merge it back in Archi).

I your case, I can see two options:
- Short term option: no more use templates but use the upcoming "model import" feature. This will keep ids and allow later updates.
- Long term option: no more use CSV but a jArchi script to make sure you use properties as foreign keys and not internal ids. And you're lucky as I have such script which is going to be opensourced by one of my clients.

**Comment by Plepoutre2019** [comment]
Hello Jean-Baptiste,

- I'm looking forward to see the model import !
- I understand that archi integrity relies on its own IDs, however, in our organisation, the CMDB is strong and I dont know if a jArchi script would be that easy (for us) to build and maintain. I mean managing updates/new/deletes can be tough.

However, as I needed a solution right now, I did "search/replace" the IDs in the .archimate with a python script (as there were more than 3000 different IDs to replace), and it worked ! so I could import again the CSV from our CMDB to upgrade my archi model with fresher objects.

The remaining problem I had, is when I import new relations (from CSV files), it seems that importing existing relations creates duplicates... I think there is no solution unless to change the CSV relation file format : 
currently, it doesnt include the IDs of the relation, only the source and destination ID, so it can not determinate if the relation is existing or new.

You are doing such a great job there ! thank you for this great product and support.

Patrick

**Comment by Phillipus** [comment]
> currently, it doesnt include the IDs of the relation,

IDs of relationships are exported.

**Comment by jbsarrodie** [comment]
>The remaining problem I had, is when I import new relations (from CSV files), it seems that importing existing relations creates duplicates... I think there is no solution unless to change the CSV relation file format :
currently, it doesnt include the IDs of the relation, only the source and destination ID, so it can not determinate if the relation is existing or new.

That's the reason why a script is better (my script manages this).

>However, as I needed a solution right now

You can manually install the modelimporter plugin (unzip and then use menu "Help > Manage Plug-ins..." to install the .archiplugin file)
[com.archimatetool.modelimporter_1.0.0.202001101050.zip](https://github.com/archimatetool/archi/files/4386461/com.archimatetool.modelimporter_1.0.0.202001101050.zip)

>I dont know if a jArchi script would be that easy (for us) to build and maintain. I mean managing updates/new/deletes can be tough.

My script manages most of this and simply rely on a configuration (no real code) for most cases. I'm planning to share this file next week (I have to remove some proprietary content and provide some guidance documentation)

**Comment by Phillipus** [comment]
You could try Archi 4.7 Early access version that has the model importer inbuilt.

**Comment by Plepoutre2019** [comment]
> > currently, it doesnt include the IDs of the relation,
> 
> IDs of relationships are exported but if missing new IDs are generated. So, unless IDs are present, there is no way to tell if they exist already other than to check if an existing relationship of that type already exists.

I'm sorry, I didnt double-check : you are right, the IDs of relation are indeed in CSV. So my "duplicate relation problem" comes from the fact I didnt replace/normalize those IDs...  I'll do it now.

**Comment by Plepoutre2019** [comment]
> You could try Archi 4.7 Early access version that has the model importer inbuilt.

Great suggestion, I'll give it a go

**Comment by Plepoutre2019** [comment]
Finally the Model importer plug-in did the job beautifully in my 4.6 version :)

thank you for the great support !

**Comment by Phillipus** [comment]
> You could try Archi 4.7 Early access version that has the model importer inbuilt.

The version in 4.7 EA is more recent and fixes some bugs.

**Comment by Phillipus** [comment]
Shall we close this issue?

**Comment by Plepoutre2019** [comment]
sure ! Thank you !

**Comment by Plepoutre2019** [comment]
great support.
