### ISSUE TITLE
Mac Archi 4.6.0 sometimes crashes on an [CMD-Z] undo operation thereby losing all editing.

### ISSUE THREAD

**Issue by hestratmann** [archimatetool/archi#600]
### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Could you say what exactly you mean by "crash" and what you were doing. Also please take a look at the error log.

**Comment by Phillipus** [comment]
@hestratmann Do you have any update on this issue? Are you still experiencing it? If so can you provide more details?

**Comment by Phillipus** [comment]
Closing due to no useful information. Please re-open if you have further information that would help.

**Comment by Phillipus** [comment]
See https://github.com/archimatetool/archi/issues/1018
