### ISSUE TITLE
[Bug][Windows][Upgrade 4.3 -> 4.6] Failed to create the Java Virtual machine

### ISSUE THREAD

**Issue by Welsh44** [archimatetool/archi#601]
### Version of Archi, Operating System
Windows 10, Archi 4.6.0, ZIP Installation

Under Windows 10
I used Archi 4.3.0 installed from a Zip.
I downloaded Archi 4.6.0 as a Zip file.
I extract everything over the existing installation.

Executing archi.exe tells me : "Failed to create the Java Virtual Machine" in a dialog box with "Archi" as title.

Java is installed, version 1.8.0_171

Thanks in advance

**Comment by Phillipus** [comment]
> I extract everything over the existing installation.

Please don't do that. Install separately.

**Comment by Phillipus** [comment]
I'm going to close this as unzipping a new version over an old version will break things.
