### ISSUE TITLE
[Feature Request] Relationship Selector Pop-up

### ISSUE THREAD

**Issue by reed155** [archimatetool/archi#602]
Feature Request:

We use the data flow relationship extensively and when we draw the relationship on a diagram we typically want to reuse an existing relationship. The problem, however, is that we have multiple of the same relationship types and it always defaults to the “first” one of the type.  We would like to be able to choose which relationship by name. The only workaround is to use the object analysis and scroll through all the relationships to locate in the object tree, then drag onto the diagram.

One possibility - 

If you could turn (Archi Current.PNG)

![Archi Current](https://user-images.githubusercontent.com/55559666/78025096-6b56f080-7327-11ea-8710-ee3f47fc7966.png)

Into (Archi Relationship Selector.PNG)

![Archi Relationship Selector](https://user-images.githubusercontent.com/55559666/78025127-790c7600-7327-11ea-9627-256ef8cb75d3.png)

**Comment by Phillipus** [comment]
This will be implemented in Archi 4.7. See https://github.com/archimatetool/archi/issues/581

I'll close this one.
