### ISSUE TITLE
[featureRequest] Rational field as default fielt for model element.

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#603]
**Rational**
One of common usecases is to get an answer on the question "Why did we do that?", meanwhile architecture description element documentation could be a heavy large text, while rational itself could be as a link to meeting agenda, analysis document, or just a few words.

Currently it's hard to distinguish between model element description and model element rational by query, it requres additional code to be supplied and hardens document generation.

As well architecture rational is a common part of ISO 42010 Architecture description metamodel, separated from model element.

Do you think it is reasonable to add a separate field to contain "Rational" for model element such as a:

- Relationship
- View
- Concept
- Grouping

**Comment by jbsarrodie** [comment]
What you describe is simply one of the use-cases of [ArchiMate Language Customization](https://pubs.opengroup.org/architecture/archimate3-doc/chap15.html).

We do plan at some point to support a such customization mecanism inline with ArchiMate specifications in Archi, but this if not for the near future. For the moment, I suggest you to look at [Herve's specialization plugin](https://github.com/archi-contribs/specialization-plugin) which implement something very similar.

As we're not going to implement such "Rational" field outside of this more generic contexte. I'm closing this issue.
