### ISSUE TITLE
Improve SVG Rendering

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#605]
Discussion for improving SVG rendering.

Copy and paste from Comments on commit 5f9acb85:

> this makes SVG really better (outline and fill are now of the exact same size, and bendpoints and line jumps are good looking)

> I can see big improvements on bendpoints and line jumps both in diagrams and SVG. And I can see the outline and fill match up now in SVG (before this you could see a little slice of fill). Great work!

> There are other things I'd like to fix but the root cause is elsewhere (like arrow heads been drawn over the line, but with the end of the line visible if linewidth is medium or heavy, or using real rounded path for polylines and not some approximation based on segments

> With SVG being on par with diagrams in Archi (except maybe fonts in some cases), it might become possible to use SVG instead of PNG in HTML exports which opens new horizons (like no more rely on an image map, add hovering effects and make relationshisp clickable ! )

> Some things don't render - gradients, for example. This is because GraphicsToGraphics2DAdaptor does not implement them. I suggest to keep PNG as a fallback in case GraphicsToGraphics2DAdaptor breaks in the future.

> GraphicsToGraphics2DAdaptor is code taken from GMF and tweaked and extended in ExtendedGraphicsToGraphics2DAdaptor which over-rides some methods. setBackgroundPattern() is one of them. It acts a bridge between Java AWT and Draw2D Graphics classes. Batik and FOP libs then do the SVG work.

**Comment by Phillipus** [comment]
It might be better to modify `ExtendedGraphicsToGraphics2DAdaptor` rather than `GraphicsToGraphics2DAdaptor ` by over-riding methods there.

**Comment by jbsarrodie** [comment]
I didn't see that we are already extending it. So it might be best to move my changes in this class.

**Comment by jbsarrodie** [comment]
Some remarks for future use:
- Now that I played a bit with Path2D, I think this should be a better options for rounded bendpoints and line jumps (both in diagrams and SVG). Here is an [interesting page](https://www.oracle.com/technical-resources/articles/javase/java2dpart1.html)
- I can embbed fonts in SVG but this doesn't work (ie. this always lead to bad or truncated glyphs)

**Comment by Phillipus** [comment]
> I didn't see that we are already extending it. So it might be best to move my changes in this class.

I'll refactor and move your changes up.

**Comment by jbsarrodie** [comment]
>I'll refactor and move your changes up.

Thank you !

**Comment by Phillipus** [comment]
@jbsarrodie I've moved your changes so they are now over-ridden methods in `ExtendedGraphicsToGraphics2DAdaptor`.

I've also made some fields in `GraphicsToGraphics2DAdaptor` protected rather than private so they can be accessed. This way we can more freely work in `ExtendedGraphicsToGraphics2DAdaptor` and add comments for the changes.
