### ISSUE TITLE
[feature request] Select visual object label from alasql database

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#606]
With 4.7 beta 3 introduced per view label a need pops up to select per view label with alasql query. Is it possible atm ?

if not is there a possibility to implement such a feature?

**Comment by jbsarrodie** [comment]
>Is it possible atm ?

No

>if not is there a possibility to implement such a feature?

Maybe. At some point we'll add a way to access the function which takes care of converting the label expression to a simple text from jArchi. We might also expose a `label` attribute on visual objects. So when we'll work on this, I'll try to "backport" this into the HTML export as this is a quite similar need.

**Comment by WatchTh1** [comment]
Will be waiting. And hope to see HTMLv3 export soon to test.

**Comment by WatchTh1** [comment]
Issue could be fixed using object namings from properties as ${property:key} macro.
So seems like not needed.
