### ISSUE TITLE
[Exchange Format] Language Import Selection

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#607]
When I import a model exchange file 
And this file contains translations 
For instance : 
```
<element identifier="id-56020" xsi:type="Equipment">
			<name xml:lang="de">Hausalarmanlage</name>
			<name xml:lang="en">Home Alarm System</name>
			<name xml:lang="fr">Système d'alarme domestique</name>
			<name xml:lang="es">Sistema de alarma de casa</name>
			<name xml:lang="nl">Thuisalarmsysteem</name>
</element>
```

I would like to be able to select the language I am willing to import

Even cooler (and desirable) : I can change the language whenever I want 

The file I import is the ArchiSurance OpenGroup

**Comment by jbsarrodie** [comment]
>Even cooler (and desirable) : I can change the language whenever I want

Archi doesn't support several languages at the same time for a model (in fact there is no notion of lang in Archi). So this can't be done.

>I would like to be able to select the language I am willing to import

It seems we both know someone who faces this issue. I was not even aware this could happen andam also interrested by such additional feature.

**Comment by jbsarrodie** [comment]
>The file I import is the ArchiSurance OpenGroup

Could you provide exact link to download it as the one I downloaded doesn't contains several languages.

**Comment by Phillipus** [comment]
It might be possible but it would have to be an option, and the import dialog would have to be a wizard with that option, the importer would have to look for strings that match the chosen language code, and if found, use that.

Re-exporting the lang would not be possible in Archi because:

> Archi doesn't support several languages at the same time for a model (in fact there is no notion of lang in Archi).

**Comment by Phillipus** [comment]
Actually...this is already implemented when importing. The importer uses the Locale language code of the host machine and chooses the matching string if there is one. I just tested it by setting my Archi to "fr" and it used the French string.

```
String getChildElementText(Element parentElement, String childElementName, boolean normalise) {
    //Check for localised element according to the system's locale
    String code = Locale.getDefault().getLanguage();
    if(code == null) {
        code = "en"; //$NON-NLS-1$
    }

    for(Element childElement : parentElement.getChildren(childElementName, ARCHIMATE3_NAMESPACE)) {
        String lang = childElement.getAttributeValue(ATTRIBUTE_LANG, Namespace.XML_NAMESPACE);
        if(code.equals(lang)) {
            return normalise ? childElement.getTextNormalize() : childElement.getText();
        }
    }

    // Default to first element found
    Element element = parentElement.getChild(childElementName, ARCHIMATE3_NAMESPACE);
    return element == null ? null : normalise ? element.getTextNormalize() : element.getText();
}
```

**Comment by VinceAxe** [comment]
> > The file I import is the ArchiSurance OpenGroup
> 
> Could you provide exact link to download it as the one I downloaded doesn't contains several languages.

This is the file:
[ArchiSurance 3.1.txt](https://github.com/archimatetool/archi/files/4438974/ArchiSurance.3.1.txt)

**Comment by VinceAxe** [comment]
> Actually...this is already implemented when importing. The importer uses the Locale language code of the host machine and chooses the matching string if there is one. I just tested it by setting my Archi to "fr" and it used the French string.
> 
> ```
> String getChildElementText(Element parentElement, String childElementName, boolean normalise) {
>     //Check for localised element according to the system's locale
>     String code = Locale.getDefault().getLanguage();
>     if(code == null) {
>         code = "en"; //$NON-NLS-1$
>     }
> 
>     for(Element childElement : parentElement.getChildren(childElementName, ARCHIMATE3_NAMESPACE)) {
>         String lang = childElement.getAttributeValue(ATTRIBUTE_LANG, Namespace.XML_NAMESPACE);
>         if(code.equals(lang)) {
>             return normalise ? childElement.getTextNormalize() : childElement.getText();
>         }
>     }
> 
>     // Default to first element found
>     Element element = parentElement.getChild(childElementName, ARCHIMATE3_NAMESPACE);
>     return element == null ? null : normalise ? element.getTextNormalize() : element.getText();
> }
> ```

That is also what I thought ... but it seems that the collegue who tested it has its computer in US local ... well I think there is some ``--language fr``  argument somewhere then

**Comment by Phillipus** [comment]
Add this to the Archi.ini file (after the `-vmargs` line):

`-Duser.language=fr`

**Comment by Phillipus** [comment]
Shall we close this one?
