### ISSUE TITLE
[Label Expression problem] Nested expressions not working

### ISSUE THREAD

**Issue by viraghtamasjozsef** [archimatetool/archi#610]
[log.txt](https://github.com/archimatetool/archi/files/4481630/log.txt)
[Example.archimate.zip](https://github.com/archimatetool/archi/files/4481631/Example.archimate.zip)

### Version of Archi

Version 4.7.0 Build 202004150922
### Archi Plug-ins

Collaboration Plugin
### Operating System

macOS Catalina v10.15.4
### Expected Behaviour

Label on a Business Actor: ${property:$model{property:Language} Name}
 should give the result "Customer" because the Language property of the model has the value: English and the "English Name" property of the given Business Actor has the value "Customer".
### Actual Behaviour

The ${property:$model{property:Language} Name} label provides the "Name}" string as the result. 
### Steps to Reproduce the Behaviour
1. Create a Property for the model: Property name=Language, Property value=English
2. Create the following two properties for a Business Actor item in one of a views: Property name=English, Property value=Customer and Property name=Hungarian, Property value=Ügyfél
3. Type in the following label to the above mentioned Business Actor element: ${property:$model{property:Language} Name} 
Additional comment: It works fine if I use the label: ${property:English Name} the result is Customer. If I use the label: $model{property:Language} then the result is English as it is correct. But the combined nested expression does not work correctly.

**Comment by Phillipus** [comment]
Thanks for your report but I'll close this one because nested expressions have not been implemented yet. We are still working on this.

I'll close this issue. :-)

**Comment by Phillipus** [comment]
For reference, we'll be discussing nested expressions here https://github.com/archimatetool/archi/issues/576
