### ISSUE TITLE
Export / import to JSon request

### ISSUE THREAD

**Issue by michalradacz** [archimatetool/archi#612]
Hi there, I have idea, because I am now often working with JSon on my iPad. Is there any chance to create internal func or external plugin to export and import model elements to standard JSon? It may helps I believe not only for me.

**Comment by Phillipus** [comment]
We have no plans to implement export/import JSON. However, if someone else wishes to do so they could develop their own plug-in. See https://github.com/archimatetool/archi/wiki/Developing-Import-and-Export-Plug-ins

I'll close this issues, because of reasons above.

**Comment by jbsarrodie** [comment]
Export can be easily done with jArchi and ` JSON.stringify`.
Import should be doable too, but that's a bit more work.
