### ISSUE TITLE
Allow to export elements with attributes to CSV

### ISSUE THREAD

**Issue by michalradacz** [archimatetool/archi#613]
Hi there, I have idea to export ALL model elements (not only in selected view as it works on special export script) to CSV with all their elements. For example, I am working on Archi patterns with stereotypes, Stereotype is attribute of element and now I am not able easylly export and import these stereotypes. Related discussion to new 4.7 function for adding attributes to element’s label.

**Comment by Phillipus** [comment]
I'm not clear what attributes you mean? Do you mean features? Do you mean to add this to the existing CSV export.

**Comment by jbsarrodie** [comment]
CSV export already includes everything in the model (ie. all elements, relationships and their properties)

>not only in selected view as it works on special export script)

Which script are you talking about (their is no script in Archi, unless you speak about jArchi and on of the example scripts, but in this case this issue relates to jArchi, not Archi)

**Comment by michalradacz** [comment]
Hi. I requested it as internal export improvement.

Attributes is equivalent for properties. Sorry for using attributes word instead. :-)

Odesláno z iPhonu

26. 4. 2020 v 12:35, Jean-Baptiste Sarrodie <notifications@github.com>:

﻿

CSV export already includes everything in the model (ie. all elements, relationships and their properties)

not only in selected view as it works on special export script)

Which script are you talking about (their is no script in Archi, unless you speak about jArchi and on of the example scripts, but in this case this issue relates to jArchi, not Archi)

**Comment by Phillipus** [comment]
> Attributes is equivalent for properties. 

These are already exported in the export to CSV action. Can you explain what isn't being exported?

**Comment by michalradacz** [comment]
Properties are exported only to xml. When export to csv in file menu, export contains only type, name, documentation. Not properties and property values.

Odesláno z iPhonu

26. 4. 2020 v 16:15, Phil Beauvoir <notifications@github.com>:

﻿

Attributes is equivalent for properties.

These are already exported in the export to CSV action. Can you explain what isn't being exported?

**Comment by Phillipus** [comment]
> Properties are exported only to xml. When export to csv in file menu, export contains only type, name, documentation. Not properties and property values.

When export to CSV is performed 3 files are created - "elements.csv", "relations.csv" and "properties.csv". The properties are stored in this last file. More information in the Archi User Guide, page 81.

**Comment by Phillipus** [comment]
I think we answered the question, so I'll close this.

If we misunderstood something, please let us know. :-)
