### ISSUE TITLE
Ask for confirmation when deleting a view used in another view

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#614]
I've just noticed that deleting (from the model tree) a view which is used in another view does not raise a confirmation dialog has we have for concepts. I think we should implement a similar behavior to avoid user mistakes.

**Comment by Phillipus** [comment]
> which is used in another view 

I guess you mean a View reference?

**Comment by jbsarrodie** [comment]
> I guess you mean a View reference?

Yes

**Comment by Phillipus** [comment]
Implemented now.
