### ISSUE TITLE
Add an option to always ask for confirmation before deleting something from the model tree

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#615]
For the moment, Archi only ask for confirmation when trying to delete a concept used in some views (but not views, which is addressed in #614). I think this can be misleading and in some occasion I have seen people deleting elements without really wanted it.

I think it would make sens to always ask for confirmation. Maybe this could be set as an option in Preferences.

**Comment by Phillipus** [comment]
OK if it is a preference, but I would have thought Undo would be sufficient in this case?

**Comment by jbsarrodie** [comment]
> OK if it is a preference, but I would have thought Undo would be sufficient in this case?

Undo works only if you noticed you deleted something.

The typical issue is the following:

- Someone is designing a view.
- At some point he decides to delete an object in his view:
  - the object is selected,
  - he hits delete but nothing happens, except the object gets deselected.
- He select it again, hit delete and this time the object is deleted from the view.
- Everything is fine now.

Everything is fine, except that in fact, before hiting delete the first time, the user selected some concept in the model tree. This didn't unselect the object on the view but the focus was then on the model tree and of course these concepts were deleted instead of the object in the view... But the user didn't notice.

**Comment by Phillipus** [comment]
OK, fair points.

**Comment by Phillipus** [comment]
Closing this because...it's done. ;-)
