### ISSUE TITLE
[Feature request] More control over the layout of the text that goes on relation. 

### ISSUE THREAD

**Issue by sudr** [archimatetool/archi#618]
When having text on a relation the text does not wrap to fit in-between the elements. This requires us to instead move the elements far enough apart to ensure the relation text doesn't overlap over the elements.

It would nice to have some word-wrap capability to control this behavior or make it so that it wraps automatically like it should.

**Comment by Phillipus** [comment]
This will be partly solved with #576

**Comment by sudr** [comment]
Thanks for pointing me to #576. I'll watch for it and will be sure to provide any usability feedback if that helps.

**Comment by Phillipus** [comment]
I'll close this one because the new label rendering will allow you to add line breaks to the text. Automatic wrapping is not going to be implemented because that assumes a fixed size text control, which in this case is not used.

**Comment by jbsarrodie** [comment]
> Automatic wrapping is not going to be implemented because that assumes a fixed size text control, which in this case is not used.

Well, this will be more or less implemented as that's the goal of my current work on `${wordwrap:size:text}` label expression. Should be available in 4.7.

**Comment by Phillipus** [comment]
> Well, this will be more or less implemented as that's the goal of my current work on ${wordwrap:size:text} label expression. Should be available in 4.7.

Yes, that's right. I mean for the present implementation with just the name.
