### ISSUE TITLE
[Linux] validity check failed Archi-Linux64-4.6.0.tgz

### ISSUE THREAD

**Issue by tobinstultiens** [archimatetool/archi#619]
### Version of Archi
4.6.0 aur

### Archi Plug-ins
no

### Operating System
Linux Manjaro 20.0

### Expected Behaviour
Installs the package from the aur

### Actual Behaviour
![image](https://user-images.githubusercontent.com/22025068/81546274-6b143100-937a-11ea-83b9-10f939f87419.png)

### Steps to Reproduce the Behaviour
1.Pull from the aur
2.Run makepkg -si

**Comment by Phillipus** [comment]
This is not an Archi issue.
