### ISSUE TITLE
[OSX 4.7 Beta] Unable to launch

### ISSUE THREAD

**Issue by XaeroZero** [archimatetool/archi#620]
### Version of Archi
4.7 beta 1 OSX
### Operating System
OSX Catalina 10.15.4 

Unable to launch Archi beta 4.7b1,
after adding app to quarantine, following dialog shows up
![Screen Shot 2020-05-11 at 5 44 37 PM](https://user-images.githubusercontent.com/9266238/81576529-07f1c100-93b1-11ea-97be-31581a54ad37.png)

Tried different unarchivers, same behavior.
4.6 stable version runs well.

Any help on advice will be helpful

**Comment by Phillipus** [comment]
Fix incoming...

**Comment by Phillipus** [comment]
@XaeroZero  Sorry about that, I forgot to update a file reference. Please download it again.

**Comment by XaeroZero** [comment]
Thank you very much, working now
