### ISSUE TITLE
[FeatureRequest] Advanced search and replacement

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#623]
Search dialog is supporting only search object by name. But there are a lot of other search conditions such as properties, descrtiption text, visual labels, object color and etc.
Would be nice to add following features:
 1.  Search and replace object used in view name/propertie/label by regular expression.
 2. Search objects in view by color picked.
 3. Search object in view by relation type/direction.

**Comment by jbsarrodie** [comment]
Such feature can't be implemented because of the diversity of use-cases that people can invent.

Creating a jArchi script is the way to go for this kind of needs.
