### ISSUE TITLE
Outline thumbnail not drawing on Linux with hi-res display

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#624]
On Archi 4.5.1, 4.6, 4.7
Linux Mint running in VMWare Fusion with display set to hi-res.

With this configuration, the Outline Thumbnail throws an "Graphic Disposed" exception.

This is because when an Image is drawn at hi-res the `Image#destroy()` method is called which causes its owning `org.eclipse.swt.graphics.GC` to be disposed.

So the `org.eclipse.draw2d.archi.part.Thumbnail` can no longer draw on that `GC`

This is from the Linux version of `org.eclipse.swt.graphics.Image`:

```java
void destroy() {
	if (memGC != null) memGC.dispose();
	...
	memGC = null;
}
```

`memGC` is our `GC` instance! Thanks a lot.

**Comment by Phillipus** [comment]
I've spent some time investigating this and I can't fix it.

Note - the same thing happens with Modelio's tool as they also use the Draw2d thumbnail component (in their case the outcome is worse because an infinite series of error dialogs appear...)

For Archi, I'll add a check to catch the exception so it does not write to the error log.

Unfortunately, it means that the Outline thumbnail does not work for the Linux version of Archi with a hi-res display.

This is why I am opening this issue in case someone wonders why, which I will also close as "won't fix".

If any Eclipse SWT gurus would like to help, please do!

**Comment by Phillipus** [comment]
TBH, the Draw2D `Thumbnail` class has cost me many days of frustration...

**Comment by Phillipus** [comment]
Closing this as #CANTFIX #WONTFIX #FUCKIT

**Comment by Phillipus** [comment]
Opening this up again, because....

**Comment by jbsarrodie** [comment]
> Opening this up again, because....

OCD...

![image](https://user-images.githubusercontent.com/5757396/82124956-ef175000-97a2-11ea-82d6-ac09f60ef054.png)

**Comment by Phillipus** [comment]
...maybe. ;-)

**Comment by Phillipus** [comment]
...because I hate to be beaten by something like this.

I have a workaround for it now. But it's not satisfying because of the underlying cause which only happen on Linux where the device scaling is > 100.

Under those conditions, the Image's `destroy` method is called which disposes of its `GC` which happens to belong to the Thumbnail. So if that happens we create a new `GC` and also create other instances as per the Mac fix.

I don't know why this should be and it might be an Eclipse Linux SWT bug. Or it might not.

**Comment by Phillipus** [comment]
I'll close this now. Beer is the reward.

**Comment by Phillipus** [comment]
This is caused by an underlying issue on Linux SWT:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=563253

**Comment by Phillipus** [comment]
At least this had a good outcome. The underlying issue on GTK has now been fixed:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=563253
