### ISSUE TITLE
Use prefix for IDs

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#625]
In reference to https://forum.archimatetool.com/index.php?topic=859.0

I can easily add a prefix to generated IDs. The question is what prefix?

- The "_" character?
- "id-"?
- ???

The use case is that exporting to XML exchange format will always use the same IDs as that used internally in Archi. Of course, this will only affect new models as models that already been imported with IDs that have the "id-" prefix will be preserved.

~However this will not help with round-tripping. Let's say we use a "_" prefix.~

~1. User imports an exchange file (perhaps from another tool)~
~2. All the IDs in the XML file are valid (they have to be otherwise the XML file would be invalid) and so are used internally in the Archi model~
~3. Let's say, for example, an ID from the imported file is "mygeneratedID1234"~
~4. User re-exports the model to another exchange file~

~What to do about "mygeneratedID1234"? The exporter will now add on the prefix "_" because it doesn't have one (same as the existing behaviour now but adding "id-")~

Solved.

**Comment by Phillipus** [comment]
Rules for XML IDs (NCNames) are https://stackoverflow.com/questions/1631396/what-is-an-xsncname-type-and-when-should-it-be-used

**Comment by Phillipus** [comment]
A simple rule for exporting could be:

- If not it's not a valid XML ID, add the prefix

If all new IDs have a prefix that rule will only apply to legacy IDs that start with a number, or IDs that have been imported from another tool.

**Comment by Phillipus** [comment]
Yes, that plan works.

- All new IDs from here on have the prefix so there's not a problem when exporting
- Valid legacy IDs are preserved when exporting/importing
- Invalid legacy IDs have the prefix added when exporting and these are then preserved when re-importing

**Comment by Phillipus** [comment]
New branch created, `id-prefix` with changes.

**Comment by Phillipus** [comment]
In fact, last year, I did change it to add "id-" as a prefix but changed my mind:

https://github.com/archimatetool/archi/blob/ddf291801b2ef0349de1a7f648da626550ee439f/com.archimatetool.model/src/com/archimatetool/model/util/UUIDFactory.java

**Comment by jbsarrodie** [comment]
> The question is what prefix?

My first idea was to use one single char because that's enough for the purpose, and I'd have suggested to use underscore.

Using ` id-` seems interesting but we in fact we gain nothing IMHO: if we import a model from exchange format we won't change its ids so round trip is still possible. We'll only change the format of XML ids generated for new models, which should have no impact.

So I would go for underscore unless we find a valide reason not to do so.

**Comment by Phillipus** [comment]
Using "id-" will only maintain consistency with what we have now when exporting a model to the exchange format. Other than that it's not important.

We could even use `EcoreUtil#generateUUID()` which is this:

```
  /**
   * Generates a universally unique identifier, 
   * i.e., a <a href="http://www.ietf.org/rfc/rfc4122.txt">UUID</a>.
   * It encodes the 128 bit UUID in <a href="http://www.ietf.org/rfc/rfc2045.txt">base 64</a>,
   * but rather than padding the encoding with two "=" characters, 
   * it prefixes the encoding with a single "_" character,
   * to ensure that the result is a valid <a href="http://www.w3.org/TR/xmlschema-2/#ID">ID</a>,
   * i.e., an <a href="http://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName">NCName</a>
   * @return a universally unique identifier.
   */
```

ECore IDs look like this:

`_p-gB8Jg1Eeq-g-BWxJa22A`
`_zJZEMZg1Eeq-g-BWxJa22A`

**Comment by Phillipus** [comment]
Having an ID generated by `EcoreUtil` makes it much shorter in length

`_zJZEMJg1Eeq-g-BWxJa22A`

vs

`_32fc4eea-d850-4cdd-b127-3a4e30c3ceff`

**Comment by Phillipus** [comment]
At this point my vote is for `EcoreUtil`

- it prefixes a "_" always and is a valid XML NCNAME
- it is shorter than the existing method
- it is used by other EMF base tools

**Comment by jbsarrodie** [comment]
We can't use `EcoreUtil` because it is case sensitive, while some OS like Windows aren't, and this is a requirement for coArchi as we create files containings the Id and these files must be unique.

So I'd vote for a UUID prefixed by an underscore.

**Comment by Phillipus** [comment]
> We can't use EcoreUtil because it is case sensitive

Interesting.

**Comment by Phillipus** [comment]
> So I'd vote for a UUID prefixed by an underscore.

Well it's either that or we create an online UUID server. Each time an Archi client creates a new object a request for a UUID is sent to the server. This then sends an email to you to manually generate a UUID by throwing a coin 26 times. Then you check it's not the database and, if OK, you then add it to the database which then sends it to the client. OK with that idea?

**Comment by Phillipus** [comment]
This is now in Archi 4.7 beta 3 https://www.archimatetool.com/beta/

**Comment by tschijv** [comment]
I have some doubts about the use of underscore as a prefix. Previously we had 'id-' as a prefix and there was no issue at all. So why change that with a prefix which may cause issues in for examples URI's. We use Mediawiki as our publication platform for ArchiMate models, with the id in the name of the webpage. Mediawiki interprets an underscore as a space character, and we have to take that in to account in our publication process. This one situation if of course no reason for changing this new approach, but I can imagine similar issues in uses of the id in URI's or other web publication environments.

**Comment by Phillipus** [comment]
Hmmm...fair point. IDs are meant to be internal things but I can see how they would be used externally.

@jbsarrodie What do you think?

**Comment by jbsarrodie** [comment]
I think that ids are internal and using them for other things is bad practice. There's no other non letter character accepted as first char in an id and underscore being valid in a url, we can't adapt to any other tool around. Unless there's a better single char proposal, I'd keep it as is.

**Comment by Phillipus** [comment]
The aim of this change is to be consistent when initially creating IDs, to ensure they are NCNAME friendly, and to maintain existing IDs when importing from the exchange file.

So, even if Archi uses some other prefix than "_" that won't stop other tools from using it and Archi importing it, or even someone manually creating/editing the ID.

Having said that, I notice that ModelioSoft use "m-" as a prefix when exporting:

`m-d7c04010-8031-428b-9092-9a94b49c6b00`

**Comment by tschijv** [comment]
In addition, even if an id is for internal use only, an export of this data in the AMEF format is for public use, so it would be nice if the exchange format has requirements for an identifier (e.g. a guid with a general prefix, to be used by every tool).

**Comment by Phillipus** [comment]
The big mistake when using the ArchiMate Exchange Format is to regard an internal XML ID as a canonical UUID.

These IDs are used for _internal_ XML identifier references _and have no scope outside of the XML file_.

They may in fact be modified by any tool or processing agent.

_There are no guarantees_.

If a UUID is required then this should be made a separate entity (as in RDF) and then it can be stated somewhere that this should not be changed. _However_, that still doesn't guarantee that any tool should store the UUID and re-export it.

Which brings me onto the second biggest mistake that some people try to impose on the ArchiMate Exchange Format:

_Thou shalt not dictate what a tool can and cannot do._ (a.k.a the tail wagging the dog syndrome.)

The ArchiMate Exchange Format must _never_ dictate things like "you have to support persistent IDs, bendpoints, gradients, dancing neon bears, and...persistent IDs"

_If it's not part of the ArchiMate spec it is optional._

Also, and this is the big one, _an exchange format file is not a persistent artefact,_

I think the misunderstanding comes from thinking that a tool is directly reading and writing to an exchange format file.

Wrong.

A tool **imports** _whatever data it supports_  from the exchange file into its internal data model _and then throws the file away._ It no longer exists. It is an ex ~parrot~ file.

And that is why IDs can change.

`</rant>`

**Comment by tschijv** [comment]
Yes, I know your position in this discussion. I have read it before ;-). I just wanted to state our perspective in this discussion, which is a very different use case. Also, we can handle the situation, that's not the issue here. In the essence is a fundamental different way for what purpose you want to have an exchange standard. On that we disagree. But, we are still extremely happy with ArchiMate, the exchange format and the Archi tooling.

**Comment by Phillipus** [comment]
> Yes, I know your position in this discussion.

It's not just my position. These are facts. The AEF is not a UML file. It does what it can and no more.

> I just wanted to state our perspective in this discussion, which is a very different use case.

Which can never be fulfilled given that the exchange format file is precisely that - a mechanism for exchanging (some) information from one tool to another.

Let me say this - there will _never_ be a file format (XML, RDF, OWL, UML, MOF, whatever) that can capture 100% an ArchiMate model and all of its graphical information. Why? Because graphical features are not part of the ArchiMate spec. Any tool can import an AEF file, change all the IDs, disregard all incoming graphical information (colors, fonts. bendpoints, line thicknesses, etc) and re-export it.

**Comment by jbsarrodie** [comment]
FWIW, while working on the Single Page HTML export project, I decided that it might be worth using another id instead of the internal Archi id because in my context ids are dumped a lot of time in the export file, which leads to a big html file.

So potentially any use-case might have it's own set of requirements (XML -> doesn't start with a number, generating files -> case insensitive, generating URL -> being URL firendly, etc...).

It is impossible to take every possible requirement into account, so people have to adapt. I saw several people developping processing based on Archi's own persistence file, and that's a very bad idea because we can change the internal format at any time (and FWIW we've starting doing it with 4.6). I think that generic software development best practices should apply: Archi is a bounded context in itself and any other custom development has to add it's own anti corruption layer to adapt data when needed.

>In addition, even if an id is for internal use only, an export of this data in the AMEF format is for public use, so it would be nice if the exchange format has requirements for an identifier (e.g. a guid with a general prefix, to be used by every tool).

There is a requirement for the identifier: it must be unique in the scope of the AMEF file and must conform to XML ids rule. There's no need to add other requirements.



> Having said that, I notice that ModelioSoft use "m-" as a prefix when exporting:
> `m-d7c04010-8031-428b-9092-9a94b49c6b00`

I once though about using `a-` (`a` for Archi) but I don't like this "biased" convention. TBH I would even prefer using (in all cases, not just when the UUDI starts with a number) `id-` (which at least has a real semantic) followed by a UUID in which `-` have been removed (to make it as short as possible), leading to  `id-d7c040108031428b90929a94b49c6b00`.

**Comment by jbsarrodie** [comment]
> There is a requirement for the identifier: it must be unique in the scope of the AMEF file and must conform to XML ids rule. There's no need to add other requirements.

(a bit of track) For the moment, The Open Group itself offers no guarantee that a new version of a public model (e.g. Archisurance or BIAN Reference Model) will have coherent ids (ie. a concept 'X' in the second version of a reference model might have a different id than the concept 'X' in the first version). _that's something I'm working on atm inside The Open Group_

**Comment by Phillipus** [comment]
>  TBH I would even prefer using (in all cases, not just when the UUDI starts with a number) id- (which at least has a real semantic) followed by a UUID in which - have been removed (to make it as short as possible), leading to id-d7c040108031428b90929a94b49c6b00.

That would be easy enough to implement.

**Comment by Phillipus** [comment]
I wonder whether people have heated discussions about the format of internal IDs as used in databases? No, because, as with XML files, these are internal identifiers not URLs. They should not be exposed - unless you're prepared to take a risk.

**Comment by jbsarrodie** [comment]
> I wonder whether people have heated discussions about the format of internal IDs as used in databases?

I had !

In one of my projects, Product owners argued that business people were used to keeping track of their case (imagine an after-sales complain) by their Id, so database Ids should be "human-friendly", which (which between other things means starts with a two digit code of the case type and should not be too long and...). I tried to say FU** but we had to find a compromise so we now have "business" ids and "technical" ids...

**Comment by Phillipus** [comment]
That would be a "Customer ID" or a "Case ID". Databases generate their own internal IDs for tables - and these should be in a black box,

**Comment by Phillipus** [comment]
> 
> 
> > TBH I would even prefer using (in all cases, not just when the UUDI starts with a number) id- (which at least has a real semantic) followed by a UUID in which - have been removed (to make it as short as possible), leading to id-d7c040108031428b90929a94b49c6b00.
> 
> That would be easy enough to implement (`id-` might please [Freud](https://www.verywellmind.com/what-is-the-id-2795275))

@jbsarrodie This is a trivial change and would make more people happy than "_" and also aligns with what is happening when exporting already. Perhaps we should go for it?

**Comment by Phillipus** [comment]
@jbsarrodie OK, I see a thumbs up. :-)

**Comment by jbsarrodie** [comment]
> @jbsarrodie OK, I see a thumbs up. :-)

That's my way of saying:
![image](https://user-images.githubusercontent.com/5757396/83296295-d8381b00-a1f0-11ea-8513-fa425131661d.png)

**Comment by Phillipus** [comment]
OK, I've committed the changes. The new ID format is as follows:

`GoForIt-d7c040108031428b90929a94b49c6b00`

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/83297965-e3d91100-a1f3-11ea-8877-4f629dd26d54.png)

**Comment by tschijv** [comment]
Thanks for the commit!

**Comment by tschijv** [comment]
Hi,

Congrats with the new version of Archi! But we still see one issue with the use and export of Id's. The release notes say:
_Add an “id-” prefix to all newly generated internal IDs and to legacy IDs that begin with a digit when exporting to exchange format_

In previous versions the "id-" prefix was added to all internal ID's and now in only the cases above. Why not as you did in previous versions and always add "id-"? The export of previously made models in 4.7 now differs a lot of the same models exported by previous Archi-versions. We use these exports for processing the models into other environments and we get quite a number of differences between models we have to solve. So please is it possible to add "id-" to ALL elements in the export?

Kind regards,

Toine

**Comment by Phillipus** [comment]
@tschijv Here's how it works now in Archi 4.7:

- Any new object created in Archi has the "id-" prefix added to its identifier (example - `id-c5bfbdc80fdb4fa9b334eff8e545d49b`)
- All existing identifiers in an `*.archimate` file remain the same and will not be changed.

When exporting to the exchange format:

- If an identifier starts with a digit, then "id-" is prefixed
- If an identifier does not start with a digit (also with the `id-` prefix) then the identifier is used

This is to ensure that legacy identifiers are valid in the exported XML file. Ideally, we are aiming for preserving the original identifiers for the reasons discussed here - https://forum.archimatetool.com/index.php?topic=859.0

**Comment by tschijv** [comment]
Thanks for your response! I completely agree on your strategy, with one exception. Previously you always added `id-` in _all_ cases. So, in that way we could preserve identifiers elsewhere. For the new export in 4.7, you now introduce a different strategy in such a way that we cannot not preserve the identifiers. For example 
- in 4.6 and before, you exported the Id `c5bfbdc80fdb4fa9b334eff8e545d49b` as `id-c5bfbdc80fdb4fa9b334eff8e545d49b`  and `25bfbdc80f4b4fa9b334eff80545d49b` as `id-25bfbdc80f4b4fa9b334eff80545d49b`
- and in 4.7 you export the first identifier as `c5bfbdc80fdb4fa9b334eff8e545d49b` and the second as `id-25bfbdc80f4b4fa9b334eff80545d49b`.

So your goal to ensure that legacy identifiers are valid in the exported XML file is not correct compared to previous versions of the Archi-export functionality. It is only working for the internal use of identifiers (upon which I completely agree) not for the external use of identifiers (no preservation and not backwards compatible).

**Comment by Phillipus** [comment]
`c5bfbdc80fdb4fa9b334eff8e545d49b` is a valid identifier for XML so there's no need to change it. `25bfbdc80f4b4fa9b334eff80545d49b` starts with a digit so we have to prefix it with a non-digit. So we use `id-`.

The aim is to:

- Preserve all identifiers internally and when exporting
- Where this is not possible add an additional "id-" prefix when an identifier is non-valid XML (starts with a digit) when exporting

**Comment by tschijv** [comment]
Correct, if you would start today, it is a fine solution. But as I stated previously, it's about the previous versions of the Archi-export. Now, we have a discontinuity in the system of identifiers. So, it's not backwards compatible for identifiers which a created previously. For new identifiers, there is no problem.

**Comment by jbsarrodie** [comment]
> Now, we have a discontinuity in the system of identifiers. So, it's not backwards compatible for identifiers which a created previously.

As already explained, there is no such requirement for any tool exporting to the Open Exchange File Format, and previous approach was forcing XML id where this were not needed. New behavior is better because it make sure internal ID in Archi is preserved when possible, and only changed when strictly needed, which makes roundtrip possible in Archi.

Sorry if you've developed some workflows relying on these ids to be stable, but that's the risk when dealing with things like ids on which you have no control and should not make any assumption about.

**Comment by Phillipus** [comment]
I think JB's explanation summarises it perfectly. The situation we have now is what should have been in place before.

So we can close this as "fixed".
