### ISSUE TITLE
Archi UI Theme Issues

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#629]
There are some reported issues around the Archi UI themes (Light, Dark, Classic) on different operating systems and whether the OS is set to dark theme or not.

Archi themes are CSS based and based on the themes that Eclipse itself uses.

Archi installed theme files are located at `/plugins/⁨com.archimatetool.editor.themes_4.X.X.xxxxxxx/themes⁩/eclipse⁩` (xxx is the version number)

Source code is here -https://github.com/archimatetool/archi/tree/master/com.archimatetool.editor.themes/themes/eclipse

Now, here's the thing - we cannot cater to every OS and OS theme permutation (especially Linux) so I'm opening this issue so that the community can help themselves. _Yes, believe it or not, Archi is open source!_

So, if you find an issue with a theme, the CSS files (linked to above) can be edited. And now is your chance to contribute fixes!

**Comment by Phillipus** [comment]
Top tip - if you find that the native OS dark theme on Ubuntu 20.04 causes Archi's View window to be dark, select the dark theme in Archi itself. (The palette will still be dark, though.)

(It took me most of Saturday to get, install, and configure Ubuntu 20.04 on a VM to discover this...you're welcome.)

**Comment by Phillipus** [comment]
For reference - https://github.com/archimatetool/archi/wiki/How-to-create-a-theme-for-Archi

**Comment by haba713** [comment]
> (The palette will still be black, though.)

How can I change the palette color to white? I use [Xfce](https://www.xfce.org) with [Adwaita dark](https://www.gnome-look.org/p/1293054/) theme.

**Comment by Phillipus** [comment]
> How can I change the palette color to white?

This is probably something in the CSS files of the Eclipse theme, I don't know what part of it would need to be changed.

**Comment by haba713** [comment]
> This is probably something in the CSS files of the Eclipse theme, I don't know what part of it would need to be changed.

Ok. I asked for help also [in Archi forum](https://forum.archimatetool.com/index.php?topic=499.msg5008#msg5008).

**Comment by haba713** [comment]
> How can I change the palette color to white? I use [Xfce](https://www.xfce.org) with [Adwaita dark](https://www.gnome-look.org/p/1293054/) theme.

I've found a workaround. You can set the GTK theme (in this case one with a light background) for a single application like this:
```
GTK_THEME=Adwaita:light /opt/Archi-Linux64-4.7.1/Archi
```

**Comment by cristianvasquez** [comment]
I have problems when opening old diagrams with Archi-Linux64-4.8.0 . Something happens with the encoding.  
![image](https://user-images.githubusercontent.com/361916/103249295-cb3dfe80-496e-11eb-9e77-ebbd1afc879c.png)

**Comment by Phillipus** [comment]
@cristianvasquez You've provided no information about your setup, so we really can't help.

Linux version? Using X11 or Wayland? Did you try on another version of Linux? GTK version? Does it work on Archi 4.7.1? Is it all models, or just some models? Hi DPI? Are there fonts missing? Did you try a different Linux theme?

Basically, what have you tried to narrow the problem down?

**Comment by cristianvasquez** [comment]
Thanks for your quick response @Phillipus ,

info: 
I'm using X11 in Ubuntu, and I haven't tried it with another Linux. Openjdk 11.0.9.1. Happens with all models all Linux themes I have installed. This happens to me with other Archi versions in the past. 

I'm using 2880 x1620 as resolution, 96x96 dots per inch.

Perhaps there is a parameter to scale up the icons?

Regarding the font, I tried changing the font to another one and it worked.

**Comment by Phillipus** [comment]
> I'm using X11 in Ubuntu

Which version of Ubuntu?

> Openjdk 11.0.9.1

Why not use the JRE that ships with Archi (in the "jre" folder)

> Perhaps there is a parameter to scale up the icons?

If you are using x2 hiDPI then Archi's x2 icons should be used. Have you set display scaling to 200% in Ubuntu?

You could compare with how Eclipse behaves (https://download.eclipse.org/eclipse/downloads/drops4/R-4.18-202012021800/download.php?dropFile=eclipse-SDK-4.18-linux-gtk-x86_64.tar.gz) to see if it's an Eclipse issue.

Beyond that, there's nothing more I can suggest.

**Comment by cristianvasquez** [comment]
Hello,

I can confirm that Eclipse behaves in the same way. 
I'm using display scaling to 100% in ubuntu. 

I think that for the moment I won't investigate further.

Any plans to make an ArchiMate tool that works, for example, in VSCode?

**Comment by Phillipus** [comment]
> Any plans to make an ArchiMate tool that works, for example, in VSCode?

No. But it's all open source so free for someone else to implement.

**Comment by cristianvasquez** [comment]
Thanks @Phillipus

**Comment by Phillipus** [comment]
I'll close this generalised issue so folks can open any new issue if required.
