### ISSUE TITLE
[Feature request] HTML export v3

### ISSUE THREAD

**Issue by miss-architect** [archimatetool/archi#631]
Hello,

I have been using Archi for my System Architects team documentation as a pilot project in order to improve our Architecture Documentation. It is a great tool with lots of potential. I would like to know when are you planning to release the new version of the HTML export? I'm using it to generate and publish our documentation so it can be accessible to all our stakeholders, but I would like to link to different diagrams from different places like our Enterprise Wiki. For that I would need to be able to get deep links, and I saw that mentioned for the new version. I would also like to change the initial page so I can show the entry point diagram.

When could we expect this new version? Would you have a kind of "demo version" of it? If I can try it out and proof that it could be beneficial for our documentation, maybe I could get some founding from my company to get it done.

Thank you!

**Comment by jbsarrodie** [comment]
Hi,

I'm the only person working on it and that's mainly a side project with no defined release date ("It's done when it's done" philosophy). That's still mainly an experimental work in progress really hard to share (I have 3 different version of the HTML/CSS/JS code with no automatic way to generate it).

That being said, here are some (hopefuly) useful informations for you:
- You can easily create deeplinks with the current version of the report. In fact it uses framesets, so you can open a view in another browser tab and share its link. Links use views' internal id and thus won't change until you delete the views. If you can also get the URL of a diagram image by inspecting the properties of the image. Again, this image URL uses internal ID and won't change.
- From a UX and internal point of view, the [jArchi powered Single Page report](https://github.com/archi-contribs/jarchi-single-page-html-export) is really close. So you can use it for some demo (but it still doesn't include deeplinks)

**Comment by miss-architect** [comment]
Hello,
Thanks for you quick reply. I would definitely like to have the new version of the HTML export, but of course I understand that "it's done when it's done". I will keep checking in the future for any tentative release date of this feature :)
Meanwhile I will take a look on your proposed alternative, it looks interesting.
Thank you!

**Comment by pihomeserver** [comment]
Hi. Any news for a potential release date for the v3 export ?
Thanks
