### ISSUE TITLE
Horizontal mouse wheel should scroll views

### ISSUE THREAD

**Issue by ramiromagalhaes** [archimatetool/archi#632]
### Version of Archi
4.6.0

### Archi Plug-ins
Git Collaboration Plugin

### Operating System
Windows 10

### Expected Behaviour
Scrolling with my horizontal mouse wheel should scroll horizontally the Views.

### Actual Behaviour
When scrolling your horizontal mouse wheel, nothing happens.

### Steps to Reproduce the Behaviour
1. Open/create any view on Archi.
2. Add enough elements on the view for it to have a horizontal scroll bar.
3. Make sure your Archi view is focused. Move your horizontal mouse wheel and notice that nothing happens.

**Comment by Phillipus** [comment]
Horizontal mouse wheel scrolling can be achieved by holding the Shift key and using the vertical scroll wheel.

I don't have a mouse with a horizontal scroll wheel so there's no way for me to test if there is native support for this and how to implement it.

**Comment by jbsarrodie** [comment]
In don't have a mouse with horizontal scroll wheel either, but I tested with my trackpad and two fingers gestures. Horizontal scrolling works on Linux but not on Windows (at least in my case).

So maybe there are so OS dependant things happening...

**Comment by Phillipus** [comment]
> but I tested with my trackpad and two fingers gestures. 

I tested with my MacBook and horizontal scrolling is supported out of the box on MacOS.

And I can run Windows as a VM on the MacBook so I can use the trackpad in Windows:

- horizontal scrolling does not work for diagrams in Archi
- horizontal scrolling _does_ work for the Models tree in Archi
- horizontal scrolling does not work for editors or trees in Eclipse
- horizontal scrolling does not work for diagrams in Modelio
- horizontal scrolling _does_ work for the right-hand properties palette in Modelio

I dug deep into GEF and SWT and there are no tricks or hacks I can do to make this work. No mouse events are being sent when horizontal scrolling.

But read this - https://bugs.eclipse.org/bugs/show_bug.cgi?id=205137

**Comment by Phillipus** [comment]
Interesting comment on that Eclipse bug:

> As a result, only widgets that support native scrolling support scrolling by horizontal mouse wheel. For instance, a tree (without columns See Bug 562499) does support scrolling by horizontal mouse wheel.

Don't know why it works on Mac, though. Unless the SWT widgets are coded so that they work with the trackpad.

**Comment by projetnumero9** [comment]
FWIW, I use a Logitech MX Master 2S on Win10 with 
- com.archimatetool.editor.buildid=201911111111
- com.archimatetool.editor.versionid=4.6.0
 and I have the same "bug". 
  
To be thorough, I tested the following:
- the horizontal scroll button, in a view,  does nothing
- the horizontal scroll button, in the model tree, scrolls

- using the SHIFT button with the vertical scroll, in the model tree, does nothing
- using the SHIFT button with the vertical scroll, in a view, scrolls

- using the trackpad with two fingers, in a view, the horizontal scroll button does nothing
- using the trackpad with two fingers, in the model tree, the horizontal scroll button scrolls

**Comment by Phillipus** [comment]
@projetnumero9 Thanks for that.

The Shift key only works in a View because I coded it to do so (for mice that only have a vertical scroll wheel).

**Comment by Phillipus** [comment]
First comment in https://bugs.eclipse.org/bugs/show_bug.cgi?id=444851

"Canvas (and hence also StyledText) does not support the horizontal scroll wheel on Windows."

Archi Views have at their UI root a `org.eclipse.draw2d.FigureCanvas` which is a subclass of `Canvas`.

**Comment by Phillipus** [comment]
BTW - holding the space bar down while using the mouse in a View acts like a pan tool.

**Comment by Phillipus** [comment]
This Eclipse bug pretty much explains it: https://github.com/archimatetool/archi/issues/632

"On SWT win32, scrolling by horizontal mouse wheel is not supported for non-native widgets"

So, we're sore out of luck on this one, folks.

**Comment by Phillipus** [comment]
Sorry, @ramiromagalhaes, for all the reasons above we can't do anything about this. So I'll close this one.

**Comment by ramiromagalhaes** [comment]
Thank you guys for your thorough and quick review on this.
