### ISSUE TITLE
Fix for Association on relationships which doesn't appear in Navigator/ Analysis tab

### ISSUE THREAD

**Issue by pschoepf** [archimatetool/archi#633]
This has already been addressed in other (closed, not fixed) issues but I would like to provide a fix at least for the Navigator view and analysis tab. 
#562 

### Version of Archi
4.6

### Archi Plug-ins
None

### Operating System
Any

### Expected Behaviour
- When selecting a relation (e.g. flow relation) which has a connected association towards an e.g. Data Object this association should be visible in the analysis property tab and in the navigator view
- Navigator view should also show this association relationship within the tree if a related concept is selected in the model

### Actual Behaviour
Neither the navigator view nor the analysis tab show associations connected to relations. This makes it difficult to find concepts (e.g. data objects) associated to relations (e.g. flows) without additional scripting.

### Steps to Reproduce the Behaviour
1.Create AC1 and AC2, two applications components
2.Create a Flow relationship between AP1---FlowR-->AP2
3.Create a dataobjet DO1
4.Create an Association relation from DO1 to FlowR
5.Select the FlowR and observe Navigator or Analysis Tab : no way to find connected DO1

### Proposed fix
I have implemented a (forked) fix which works at least for navigator and analysis tab. The output for a more complex example looks as follows.
Example:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/2749027/83170481-e153ba00-a114-11ea-8d87-69d3312ad0d1.png">

Navigator when selecting the App1:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/2749027/83170542-fc262e80-a114-11ea-9317-f654c9d05025.png">

Analysis tab when selecting the Flow:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/2749027/83170591-13651c00-a115-11ea-94e8-cc072442ac60.png">

If accepted I'd like to submit the fix via pull request.

**Comment by Phillipus** [comment]
Thanks for following protocol and opening an issue before throwing code into a PR. I think this is worth looking at. Can you submit a _**draft**_ PR?

**Comment by jbsarrodie** [comment]
It seems that guys called "Philipp" do things the right way ;-)

**Comment by Phillipus** [comment]
Currently, the Analysis tab is only displayed when an ArchiMate element is selected. It shows the element's incoming and outgoing relationships.

Your proposal shows the Analysis tab for a relationship which has incoming/outgoing relationships, so it's similar to the current functionality. But how do you propose to manage the current situation when a relationship is selected that has elements at each end?

**Comment by pschoepf** [comment]
Thanks for being open for the discussion. Regarding the question "But how do you propose to manage the current situation when a relationship is selected that doesn't have any incoming/outgoing relationships?". 
If I understand you currently you mean what should happen if I select a relation e.g. the flow from App3 to App1 ? My current solution would display an empty list as there are no relations in the model referencing to the selected relation:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/2749027/83173941-ebc48280-a119-11ea-9928-8608450c0f24.png">

**Comment by Phillipus** [comment]
> My current solution would display an empty list as there are no relations in the model referencing to the selected relation. But happy to discuss if you would expect something different.

I agree.

`com.archimatetool.editor.propertysections.UsedInRelationshipsSection` has a filter to only display the table when the selection is an `IArchimateElement`. This needs changing to `IArchimateConcept` to display also for a `IArchimateRelationship`. This could also apply other logic - "IF object is `IArchimateRelationship` AND has incoming/outgoing relationships" which would mean that the table would not be visible in this case. But I think if it was there in all cases, the user would understand that it is relevant for all concepts even if not in all cases.

**Comment by Phillipus** [comment]
I tried this:

```
    public static class Filter extends ObjectFilter {
        @Override
        public boolean isRequiredType(Object object) {
            if(object instanceof IArchimateElement) {
                return true;
            }
            return object instanceof IArchimateRelationship
                    && !ArchimateModelUtils.getAllRelationshipsForConcept((IArchimateRelationship)object).isEmpty();
        }

        @Override
        public Class<?> getAdaptableType() {
            return IArchimateConcept.class;
        }
    }
```

And the I realised that this is actually the fix for it!

**Comment by pschoepf** [comment]
Exactly, I modified the mentioned filter and added some code to not run into class cast exceptions and to find the related associations and . I will submit the PR until tomorrow so you can have a look.

**Comment by Phillipus** [comment]
> added some code...to find the related associations

As far as I can tell this works already:

```java
public Object[] getElements(Object inputElement) {
    return ArchimateModelUtils.getAllRelationshipsForConcept((IArchimateConcept)inputElement).toArray();
}
```

**Comment by Phillipus** [comment]
As the changes I made in `com.archimatetool.editor.propertysections.UsedInRelationshipsSection` were quite simple and solves the issue there and the help files need updating with new text and a screenshot, I decided to create a new branch with these changes - the branch is called `issue633`.

@pschoepf I don't want to "steal your thunder" but you could now work off of the branch `issue633` for the Navigator part.

**Comment by pschoepf** [comment]
Thanks :-) Yes it was only those few lines of code. 
I can provide the navigator view via PR, that was also not too much change. If its ok for you we can also skip the effort of a PR and you directly try out the following code snipped in `com.archimatetool.editor.views.navigator.NavigatorViewer`

`@Override
        public Object[] getChildren(Object parent) {
        	// the parent element is a relationship
            if(parent instanceof IArchimateRelationship) {
            	IArchimateRelationship relation = (IArchimateRelationship)parent;
                List<Object> results = new ArrayList<>();
            	// get all association relationships targeting or sourcing the parent
            	results.addAll(ArchimateModelUtils.getAllRelationshipsForConcept((IArchimateRelationship) parent));
            	boolean addTarget = fShowTargetElements;
            	boolean addSource = !fShowTargetElements;
            	if (parent instanceof IAssociationRelationship) {
            		// if we traverse an undirected association always add target and source
            		if (!((IAssociationRelationship) parent).isDirected()) {
            			addTarget = true;
            			addSource = true;
            		}
            	}
            	// get the source or target element of the relation
            	if(addTarget) {
                    results.add(relation.getTarget());
                }
                if (addSource) {
                	results.add(relation.getSource());
                }
                return results.toArray();
            }
            else if(parent instanceof IArchimateElement) {
                IArchimateElement element = (IArchimateElement)parent;
                if(fShowTargetElements) {
                    return element.getSourceRelationships().toArray();
                }
                else {
                    return element.getTargetRelationships().toArray();
                }
            }    
            return new Object[0];
        }`

**Comment by Phillipus** [comment]
@pschoepf I edited the code for formatting.

I can do that but I thought you might like to get your name on the PR commit?

**Comment by pschoepf** [comment]
well that's a valid argument ;-) lets do it as you proposed. happy to contribute something to this great tool.

**Comment by Phillipus** [comment]
OK. The problem with PRs is that the submitted code usually needs some "tidying up" by me (and some help files updated), But this then creates a problem if I commit it - the original contributor does not get the commit authorship. So we need to find a solution so that we work together and you do the final PR so I can merge it and you get your name in the git history.

**Comment by Phillipus** [comment]
PR has been merged.

@pschoepf Thanks for opening the issue and the fix! Credit to you also for the `UsedInRelationshipsSection` fix - I just happened to follow your lead on that one. ;-)

**Comment by Phillipus** [comment]
I'll close this.
