### ISSUE TITLE
[UIX] Autoselect model element in model tree

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#638]
After upgrading to 4.7 beta 3 I have and issue with following scenario:
1.Select an element in view
2. Select it in model tree
3. Go to other view
4. Other view is selected in model tree.

It is nice in some way but I can not drag-n-drop elements from model tree selecting them in a view to other view =)
Is there an option to disable autoselecting mode elements in model tree by clicking them in a views ?

**Comment by Phillipus** [comment]
This has always been like this with the "Link to View" button on. Turn that off.

**Comment by WatchTh1** [comment]
Ow, found that. Many thanks and best regards)
