### ISSUE TITLE
[feature] XLXS Export with alasql

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi#639]
This might be good enough to include some additional alasql features to HTML report.
 Smth like
https://github.com/agershun/alasql/wiki/XLSX

Can it be done without recompling archi itself?

**Comment by jbsarrodie** [comment]
You can easily change the template used to create the HTML report by editing it in your local Archi installation: 

Simply add:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/X.Y.Z/xlsx.core.min.js"></script>`

before this line:
https://github.com/archimatetool/archi/blob/master/com.archimatetool.reports/templates/st/frame.stg#L278

**Comment by WatchTh1** [comment]
Thanks a lot! As offtop to an issue, but relative HTML export. How's it going with HTMLv3 export ? https://github.com/archimatetool/archi/wiki/HTML-export-v3
Here https://www.archimatetool.com/roadmap/ there is no info about current state.
