### ISSUE TITLE
Error when trying to open a link to a shared directory on a property (file://)

### ISSUE THREAD

**Issue by yetesse** [archimatetool/archi#641]
### Version of Archi
4.7 Beta

### Archi Plug-ins
Archi model repository

### Operating System
Windows 10 64 bits

### Expected Behaviour
I'd like to add properties containing links to documents stored in a shared network directory. I expect Architool to open the link.

### Actual Behaviour
It works well for http links as well as file:// to local directory. However I run into a warning message whenever I try to access a shared network directory with file:// (see screenshot attached)

### Steps to Reproduce the Behaviour
1. create a property with value file://dirxyz (where dirxyz is the path to your shared network directory)
2. double click on the icon to open the link in a browser
3. warning message about the link being incorrect (note the message is a warning so there is no error in the log)

Am I getting it wrong with the regex or is there a problem with shared network folder links?

Thanks in advance for your help and keep up the good work,
Yann
![Archi_4_7_Beta_file_shared_directory_error](https://user-images.githubusercontent.com/67420218/85725037-0a0ba700-b6f5-11ea-89a0-a5f276948936.jpg)

**Comment by jbsarrodie** [comment]
> or is there a problem with shared network folder links

This is most certainly the case. Try looking for file:// url and network drive on any search engine. FWIW, I found [this entry](https://stackoverflow.com/questions/5796215/an-url-to-a-windows-shared-folder) providing some interresting ideas on how to solve it.

But this is not related to Archi (Archi simply makes the link clickable), so closing this issue.
