### ISSUE TITLE
Specialization Alpha1 plugin doens't work in 4.7

### ISSUE THREAD

**Issue by micwic** [archimatetool/archi#642]
### Version of Archi
com.archimatetool.editor.buildid=202006221030
com.archimatetool.editor.versionid=4.7.0

### Archi Plug-ins
	Herve Jouin	Form plugin for Archimate Tool	1.9.1	org.archicontribs.form
	HervÃ© Jouin	Icon plugin for Archimate tool	2.0.0.alpha1	org.archicontribs.specialization

### Operating System
W10 Pro 1903

### Expected Behaviour
Installation et utilisation plugins Spezialization 

### Actual Behaviour
Le plugin s'installe mais l'écran de configuration n'apparait pas dans les Préférences
De même, l'onglet Figure sur un élément créé une exception (nullpointer)

### Steps to Reproduce the Behaviour
1.Installer le plugin
2.Essayer de le configurer et de l'utiliser
3.

**Comment by Phillipus** [comment]
Hi, this is not an Archi issue. Could you please open an issue for Herve here - https://github.com/archi-contribs/specialization-plugin/issues - or add to this one - https://github.com/archi-contribs/specialization-plugin/issues/40
