### ISSUE TITLE
[Archi 4.7 Beta7] Importing a model should raise a warning when an object/folder exists but won't be updated

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#643]
The new model importer feature comes with an _"Update existing objects and folder"_ option which enable or disable updating existing objects or folder if the model being imported already contains an object or folder with the same internal Id.

Take the two models contained in this 
[ZIP archive](https://github.com/archimatetool/archi/files/4851181/Issue_643.zip)

If you open _"M1"_ and import _"M2"_ with this option enable, then you'll get this log:
<pre>
<b>[Info] Element synchronized: 'HAS BEEN CHANGED'</b>
[Info] Element added: 'New Application'
[Info] Relationship added: 'Flow relation'
<b>[Info] View synchronized: 'View 1'</b>
[Info] View added: 'Project'
</pre>

So you can easily see what has been updated.

But if you disable this option, you'll get this:
````
[Info] Element added: 'New Application'
[Info] Relationship added: 'Flow relation'
[Info] View added: 'Project'
````

And you'll get no warning nor information about those two elements which existed but were not updated.

I suggest we add more logging for this case, such as:
<pre>
<b>[Info] Element not updated: 'SHOULD NOT CHANGE'</b>
[Info] Element added: 'New Application'
[Info] Relationship added: 'Flow relation'
<b>[Info] View not updated: 'View 1'</b>
[Info] View added: 'Project'
</pre>

**Comment by Phillipus** [comment]
@jbsarrodie I have committed a change in branch `model-importer`.

How do we want to handle this? Release Archi 4.7 beta 8 or some other way to test this?

**Comment by jbsarrodie** [comment]
> How do we want to handle this? Release Archi 4.7 beta 8 or some other way to test this?

Being a small change, I propose to test myself today and don't release another beta (let's jump straight to final release!)

**Comment by jbsarrodie** [comment]
I've just tested and everyting seems fine !

**Comment by jbsarrodie** [comment]
(FWIW, I still have to test other part of beta 7 with my models. Doing it now)
