### ISSUE TITLE
[Feature Request]  Properties -> Properties tab, add keyboard shortcut to update name/value  [Pending evaluation, bump]

### ISSUE THREAD

**Issue by justsomerandombloke** [archimatetool/archi#645]
Use-case;  
(a) User opens the "Properties" box, navigates to Properties tab using keys and selects earlier added Name/Value line [existing functionality]
(b) User then press designated key shortcut, e.g. F2 or CTRL+Enter enabling the Name/Value fields for editing [new functionality]

Saving; 
User will not need to move mouse pointer to box and click every-time fields needs to be updated. 

(Thank you so much for a great software guys! Hope the above isn't all to weird. Maybe I should fork and code it? )

**Comment by justsomerandombloke** [comment]
Bump on this one. This is a small change but with Great value .. would make life so much easier!

**Comment by Phillipus** [comment]
It turns out pressing the enter key to initiate an edit in the table is better. (In Eclipse there is a properties table for editing an eCore model that does exactly this.)

Archi 4.7.1 beta 2.

https://www.archimatetool.com/beta/

**Comment by Phillipus** [comment]
This is in Archi 4.7.1

https://www.archimatetool.com/download/

**Comment by justsomerandombloke** [comment]
Absolutely superb. You're stars! 
    On Monday, 13 July 2020, 10:25:05 BST, Phil Beauvoir <notifications@github.com> wrote:  
 
 


It turns out pressing the enter key to initiate an edit in the table is better. (In Eclipse there is a properties table for editing an eCore model that does exactly this.)

Archi 4.7.1 beta 2.

https://www.archimatetool.com/beta/
