### ISSUE TITLE
[Feature Request] Multiple connection mode + Quick connection [Pending evaluation]

### ISSUE THREAD

**Issue by justsomerandombloke** [archimatetool/archi#647]
2 Use cases relating to connections; 

**[new functionality 1 - multiple connection mode]**  
(a) User double clicks on connector icon in the "Palette".  Connector icon is coloured to indicate 'Multiple connection mode' on.  
(b) User can then make several connections in the "View" (using existing connection functionality). 
(c) 'Multiple connection mode' is turned off e.g. by (i) user pressing Escape or (ii) user clicking the connector icon or (iii) user clicks the 'multiple connection mode OFF' icon placed next to the Format Painter icon in the "Palette". 

**[new functionality 2 - quick connection]**  
(a) User right-clicks on element 1 in "View".  Pop up menu provides new option: "Create connection"
(b) User choose the option and existing connection functionality commence with Element 1 selected. Connection type can be chosen by additional pop up or simply by user changing connection type later.

**Comment by Phillipus** [comment]
> [new functionality 1 - multiple connection mode]

This can be achieved by holding the Shift key down when single-clicking on a Palette icon. Single-clicking again without the Shift key down will toggle back again. (It's a tip in the User Guide - page 25).

Note - I did originally try to use a double-click for this, but it conflicts with something internally so it doesn't work.


> [new functionality 2 - quick connection]

Did you try the "Magic Connector"?

**Comment by justsomerandombloke** [comment]
_[new functionality 1 - multiple connection mode]
This can be achieved by holding the Shift key down when single-clicking on a Palette icon. Single-clicking again without the Shift key down will toggle back again. (It's a tip in the User Guide - page 25).
Note - I did originally try to use a double-click for this, but it conflicts with something internally so it doesn't work._

Sorry. Should RTFM more carefully. My bad and this ticket is closed for sure. You're a star mate !
