### ISSUE TITLE
[Feature Request] Zoom onto selected element [Help wanted]

### ISSUE THREAD

**Issue by ghost** [archimatetool/archi#648]
**Use case** 
(a) User has marked element X in the "View".
(b) User press CTRL and moves mouse-wheel to zoom in.  Archi then zoom onto the selected element and not 'straight onto the current view'. 

**Savings**
User will no longer have to repeatedly press SPACE and 'move the screen' to selected element. 

**Existing issues?**
Issue list searched and no similar request found.

Sincere Regards :)

**Comment by Phillipus** [comment]
Perhaps the same as #103 ?

For this one and #103, it requires someone to investigate the Eclipse GEF (Graphical Eclipse Framework) and devise a way to do this. So I'll make this with "help wanted"

**Comment by justsomerandombloke** [comment]
Spot on.  Can't say I'm an expert on EGEF but let's see if someone engage, otherwise ... maybe... there's a hobby project coming up here :)

**Comment by guypayeur** [comment]
I would have appreciated to be able to zoom to a selection using CTRL&SCROLL WHEEL. I found this code here: https://github.com/ApexSoft/modellipse/blob/master/org.eclipse.papyrus.uml.diagram.menu/src/org/eclipse/papyrus/uml/diagram/menu/toolbar/ZoomToolbar.java
Can it may help to implement this feature?

**Comment by Phillipus** [comment]
> Can it help to implement this feature?

Sorry, no. There's nothing there to actually zoom into selected elements
