### ISSUE TITLE
Line width of 1 causes a thicker line at 100% due to anti-aliasing

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#650]
(Note - this won't be apparent on hi-res screens)

Now that we set a line width of one pixel for figures we have this method:

```java
protected void setLineWidth(Graphics graphics, float lineWidth, Rectangle bounds) {
    bounds.width -= lineWidth;
    bounds.height -= lineWidth;
    graphics.setLineWidthFloat(lineWidth);
    graphics.translate(lineWidth / 2, lineWidth / 2);
}
```

The call to `graphics.translate()` allows us to move the x and y drawing area by `lineWidth / 2` to compensate for clipping when drawing the line. However, when `lineWidth` is 1 the translate factor is 0.5. Because this is not a whole number anti-aliasing is introduced and the outline appears thicker (and greyer if it is black).

So with a translate factor of 0.5 pixel we get this:

![1](https://user-images.githubusercontent.com/600504/86817270-b138f880-c07c-11ea-95ea-cbb778cce690.png)

But if we use a translate factor of 1 pixel we see this (which is how it should be):

![2](https://user-images.githubusercontent.com/600504/86817361-d7f72f00-c07c-11ea-85e2-8c6416103d9c.png)

However, using a translate factor of 1 pixel is much the same as calling `bounds.shrink(1, 1);` and the problem with that was the gap it causes around the figure.

**Comment by Phillipus** [comment]
We can see the effects of the anti-aliasing if we zoom into the figure:

![2](https://user-images.githubusercontent.com/600504/86822725-e6951480-c083-11ea-86aa-41b21e266311.PNG)

However, if we don't use `graphics.translate(0.5, 0.5);` we have a nice clean outline (again, this is zoomed in):

![1](https://user-images.githubusercontent.com/600504/86822865-0fb5a500-c084-11ea-9705-a264b709cd11.PNG)

**Comment by Phillipus** [comment]
@jbsarrodie I think we might have to use `bounds.shrink(1, 1)`. The only downside is the 1 pixel gap:

![gap](https://user-images.githubusercontent.com/600504/86823319-9d919000-c084-11ea-85db-4264d0206560.png)

**Comment by pschoepf** [comment]
Cool that fixes the issue on my 1080p resolution but as you said it creates a small gap between connector lines and the figure shape. This topic seems to be full of side effects... 
Using `graphics.translate(1,1);` doesn't seem to have this 1px gap (at least not on my screen), what would be the downside of using that ?

**Comment by Phillipus** [comment]
> Using `graphics.translate(1,1)` doesn't seem to have this 1px gap (at least not on my screen), what would be the downside of using that ?

That is exactly the same as:

```
bounds.x++;
bounds.y++;
```

And you will see the 1px gap on the left and the top:

![Image 1](https://user-images.githubusercontent.com/600504/86903490-500a3700-c107-11ea-9985-5f429e7b94d7.png)

The only reason I used `graphics.translate(x, y)` was because it can move the bounds by floating point numbers (0.5). But I hadn't thought about the problem of anti-aliasing (I did a lot of testing on a retina Mac where this is not a problem)

**Comment by pschoepf** [comment]
Ah right, I see. What about setting `graphics.setAntialias(SWT.OFF);` and leaving `graphics.translate(lineWidth / 2, lineWidth / 2);` ? At least on my device that looks promising.

**Comment by Phillipus** [comment]
> What about setting graphics.setAntialias(SWT.OFF);

I tried that, It leads to poor quality and jagged lines of curves in some figures.

**Comment by Phillipus** [comment]
I'm experimenting with a mixed approach:

```java
if(ImageFactory.getDeviceZoom() > 100 || FigureUtils.getFigureScale(this) > 1.0) {
    graphics.translate(lineWidth / 2, lineWidth / 2);
}
else {
    graphics.translate(1, 1);
}

```

Pseudo-code:

```
if device is hires OR diagram scale > 100% {
   move x, y by lineWidth / 2; // Will be 0.5
}
else if diagram scale is 100% {
   move x, y by 1;
}
```

For hires devices this is not a problem, 0.5 pixels is OK, no anti-aliasing is done. For non-hires devices we move by 1 pixel.

As you zoom in 200, 300, 400, 600, 800 there is no anti-aliasing so `lineWidth / 2;` is OK, For odd zoom factors (75%, 150%) there is anti-aliasing on non-hires devices anyway.

**Comment by pschoepf** [comment]
great, that looks good my both, my retina and the 1080p

**Comment by Phillipus** [comment]
This is what I ended up with:

```java
protected void setLineWidth(Graphics graphics, float lineWidth, Rectangle bounds) {
    graphics.setLineWidthFloat(lineWidth);

    // Width and height reduced by line width
    bounds.width -= lineWidth;
    bounds.height -= lineWidth;
    
    // x,y offset is half of line width
    float offset = lineWidth / 2;
    
    // If non hi-res device and scale = 100% round up to integer to stop anti-aliasing
    if(ImageFactory.getDeviceZoom() == 100 && FigureUtils.getFigureScale(this) == 1.0) {
        offset = (float)Math.ceil(offset);
    }
    
    graphics.translate(offset, offset);
}
```

@pschoepf This is in branch `linewidth-fix` can you test it?

The only compromise is a gap of 1px on the left and top at 100% on non-retina devices. This is my best shot, I can't think of anything else.

**Comment by Phillipus** [comment]
It turns out that if line width is 1 and scale is 100% we don't need to do anything.

So this is what we have now:

```java
protected void setLineWidth(Graphics graphics, float lineWidth, Rectangle bounds) {
    graphics.setLineWidthFloat(lineWidth);
    
    final double figureScale = FigureUtils.getFigureScale(this);
    
    // If line width is 1 and figure is 100% scale then do nothing
    if(lineWidth == 1 && figureScale == 1.0) {
        return;
    }

    // Width and height reduced by line width
    bounds.width -= lineWidth;
    bounds.height -= lineWidth;
    
    // x,y offset is half of line width
    float offset = lineWidth / 2;
    
    // If this is a non hi-res device and scale == 100% round up to integer to stop anti-aliasing
    if(ImageFactory.getDeviceZoom() == 100 && figureScale == 1.0) {
        offset = (float)Math.ceil(offset);
    }
    
    graphics.translate(offset, offset);
}
```

And I've added a hack method in `com.archimatetool.editor.diagram.figures.FigureUtils#setFigureScale()` so that we know what scale is being used when creating an Image (otherwise there is no way of querying the current scale from `SWTGraphics`)

This is not easy stuff. 😉

**Comment by Phillipus** [comment]
I've refined things even further now so that the scale is set on a Figure's ancestor pane when exporting to image. This way `com.archimatetool.editor.diagram.figures.FigureUtils#getFigureScale()` doesn't need to be hacked.

New commit in `linewidth-fix` branch.

I want to get get Archi 4.7.1 beta 1 out ASAP. This fix is quite important,

**Comment by Phillipus** [comment]
Archi 4.7.1 beta 1 contains the fix for this - https://www.archimatetool.com/beta/

@pschoepf Would you like to test this?

**Comment by pschoepf** [comment]
happy to do with my team, but I got a "page not found"

**Comment by Phillipus** [comment]
> happy to do with my team, but I got a "page not found"

Fixed it!

**Comment by Phillipus** [comment]
This turned out to be a bit more complex...

> I've refined things even further now so that the scale is set on a Figure's ancestor pane when exporting to image. 

That was a potentially dangerous idea. You might get unexpected results in the future. So I've created a class `ExtendedSWTGraphics` which extends `SWTGraphics` and this stores the current scale. This can be accessed in our new method (which has grown somewhat):

```java
protected void setLineWidth(Graphics graphics, int lineWidth, Rectangle bounds) {
    graphics.setLineWidth(lineWidth);
    
    // If we are exporting to image or printing this will be ExtendedSWTGraphics
    // Otherwise it will be SWTGraphics
    final double scale = graphics instanceof ExtendedSWTGraphics ? ((ExtendedSWTGraphics)graphics).getScale() : FigureUtils.getFigureScale(this);
    
    // If line width is 1 and scale is 100% then do nothing
    if(lineWidth == 1 && scale == 1.0) {
        return;
    }

    // Width and height reduced by line width to compensate for x,y offset
    bounds.width -= lineWidth;
    bounds.height -= lineWidth;
    
    // x,y offset is half of line width
    float offset = (float)lineWidth / 2;
    
    // If this is a non hi-res device and scale == 100% round up to integer to stop anti-aliasing
    if(ImageFactory.getDeviceZoom() == 100 && scale == 1.0) {
        offset = (float)Math.ceil(offset);
    }
    
    graphics.translate(offset, offset);
}
```

And then I discovered more problems - the "Print" action (do people still print on paper?) uses `Draw2d` classes that use...yes, you guessed it, `ScaledGraphics`! So I had to copy and hack these classes to not use `ScaledGraphics` and to use our `ExtendedSWTGraphics` so now at least it looks half decent when printing (I only tested by printing to PDF file).

All of this is in a new branch `graphics-fix`. And we'll need a new 4.7.1 beta.

**Comment by pschoepf** [comment]
interesting. hadn't discovered any problems so far in the beta but I have to admit I never printed directly from Archi :-)

Once the new beta is out I will test again.

**Comment by Phillipus** [comment]
Archi 4.7.1 beta 2 for a final check. I'm aiming to get 4.7.1 out this week.

https://www.archimatetool.com/beta/

**Comment by Phillipus** [comment]
This is in Archi 4.7.1

https://www.archimatetool.com/download/
