### ISSUE TITLE
[Feature Request] Remove all line's bend points option

### ISSUE THREAD

**Issue by kvaleev** [archimatetool/archi#653]
**Use case**
1. There is a view opened with elements and connections arranged, connections have bend points.
2. I want to rearrange elements on the view.
3. Connections bend points stay in the same places as they were before. Currently, I need either to straighten lines point by point or completely remove lines and draw new ones. **It will be great to have an option to remove all bend points on the line with one click.** 

**Savings**
Users will no longer have to repeatedly straighten bend points on a line before creating new ones.

**Existing issues?**
The issue list searched and no similar request found.

**Comment by jbsarrodie** [comment]
You can do it with [jArchi](https://www.archimatetool.com/plugins/#jArchi):

Simply create a file named `Delete bendpoints.ajs` with following content:
````javascript
selection.filter("relationship").each(function(o) {
  o.deleteAllBendpoints()
})
````

And run it from contextual menu through the Script entry after having selected the relationship(s).

**Comment by kvaleev** [comment]
Thanks, I tried to run this script in Archi 4.7 and got an error:

```
Script Error at: javax.script.ScriptException, javax.script.ScriptException: TypeError: 
o.deleteAllBendpoints is not a function 
in /Users/user/Library/Application Support/Archi4/scripts/Delete Bendpoints.ajs 
at line number 2
```

**Comment by Phillipus** [comment]
You have to select connection(s) in a View not in the Models Tree.

**Comment by kvaleev** [comment]
Yes, I get the error, when I try to start the script on the view

**Comment by kvaleev** [comment]
But this script eventually works: https://gist.github.com/jbsarrodie/3cfe6ae90b29696c55550ce3d4b3a577
