### ISSUE TITLE
[Feature Request] Support localization for elements and relations types

### ISSUE THREAD

**Issue by kvaleev** [archimatetool/archi#654]
I'm aware that there are some localization packs for Archi, but they are intended to translate the whole Archi user interface. But more often it's necessary to have only elements and relations types localized, as they appear on exported artifacts: diagram views (via labels) and reports.

So it will be great to have a way to easily add translation (preferably configurable) for these type names.

**Comment by Phillipus** [comment]
The HTML report can be translated in the `com.archimatetool.reports/templates/html/css` folder using a css file. Jasper Reports uses externalised fields (See https://github.com/archimatetool/archi/issues/331). All other strings have to be translated viz a language pack.
