### ISSUE TITLE
[feature request] Keeping traces of copies

### ISSUE THREAD

**Issue by Plepoutre2019** [archimatetool/archi#658]
Sometime we need to evaluate 2 scenarios so we have
a) the "now view" : One view with 5 applications / processes / actors as of "today"
b) the "scenario 1 view" : Same 5 applications / processes / actors but with some changes, new dataflows, maybe another 6th app
c) the "scenario 2 view" : Same 5 app minus one / some processes have been splitted / actors / ...

To achieve that, we need to make standalone copies of the objects. 
Bad things is that we loose track thoses copies, so if we need to rename or add some properties to the objects, we need to do it 3 times.

Solution : 
- when copying an object "Application X", the copy named "Application X #2" would keep a 'hidden link to' father application "Application X'. When right-clicking on the 'father app' we could see it has 2 variants : Application X #2 and Application X #3 for examples. We could have 'easy renaming' capabilities or even data inheritances between fathers toward its copies.
- when an object is created from the palette, no 'father' object. Maybe we should add something to secure this behaviour as some people may have made some kind of custom template-like objects they use to copy/paste.

**Comment by Phillipus** [comment]
The feature request description is incomplete.

**Comment by jbsarrodie** [comment]
> To achieve that, we need to make standalone copies of the objects.

Why? There is no need to duplicate elements for several scenarios. Simply reuse the elements which are in common.
