### ISSUE TITLE
[Unexpected Behavior] No Association proposition with Nested Relations

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi#660]
### Version of Archi
Archi 4.7.0 (and 4.7.1)

### Expected Behaviour
When I drag and drop a Device inside a Communication Network, I would like to use an Association Relationship between them

### Actual Behaviour
The association isn't a choice 

Side note : this behavior is the same whatever the node type with whatever path type, so same for Facility and Distribution Network

![image](https://user-images.githubusercontent.com/43959255/89275397-85d90780-d642-11ea-9652-0ee73309e5cb.png)

**Comment by VinceAxe** [comment]
Checked also with 4.7.1, same behavior

**Comment by Phillipus** [comment]
You need to enable it in Preferences:

<img width="731" alt="Screenshot 2020-08-04 at 11 07 20" src="https://user-images.githubusercontent.com/600504/89281961-bb7df080-d642-11ea-80b3-b4d6be3cddeb.png">
