### ISSUE TITLE
Is it meant to be possible to use the same key multiple times in the property tab?

### ISSUE THREAD

**Issue by Ballzer0** [archimatetool/archi#661]
### Version of Archi
Archi4

I am trying to import our architecture to a database when i realised that you can use the same key multiple times in the property tab. Each property does not have a unique identifier. so I am left wondering if this is by design or if its meant to be limited to 1 row for each defined property.
![image](https://user-images.githubusercontent.com/28560729/89303221-2ee82800-d66c-11ea-9f4c-b32cb92feb60.png)

**Comment by Phillipus** [comment]
Yes, that is intentional.

**Comment by Ballzer0** [comment]
alright just had to be sure. ill just close this then
