### ISSUE TITLE
[Feature request] Export Label data in the Exchange Format

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#662]
The new Label feature in 4.7 is **really** useful in the creation of QNAMEs (Qualified names - guaranteed to be unique across namespaces) but there doesn't appear to be a way to export label information in Exchange format.

I'd like to propose a Preferences setting whereby the exported element name would be generated from a concatenation of the Label data and the local name (copy by value obviously - not the formula!).

For example, if the Label expression is '`myNamespace:${name}`' and the element name is 'myElement', the Exchange file would declare
`<element identifier='id-xyz' ..........>
      <name xml:lang='en'>myNamespace:myElement</name>
</documentation>`

**Comment by Phillipus** [comment]
That won't work because the label expression is applied to each graphical instance in a View not the concept itself.

As for exporting the label expression in the exchange format, remember that the idea is to exchange the model with other tools and services which will probably not use the label expression.

**Comment by lavenderb** [comment]
Ths Phil, I see.
I can work around it then by defining the namespace as an Element property and then reference it using the label, like so
`${property:namespace}:${name}`
That way the namespace information survives export and only the label script is lost. :-)

Shame though that I'll have to add the label script into every graphical instance manually.
Would it break any design principle to have a Prefs option to select label consistency across all instances?

**Comment by Phillipus** [comment]
> Shame though that I'll have to add the label script into every graphical instance manually.
Would it break any design principle to have a Prefs option to select label consistency across all instances?

@lavenderb Steven, per concept is discussed in #640
