### ISSUE TITLE
[Feature Request] UI for changing relation type

### ISSUE THREAD

**Issue by radeksvarz** [archimatetool/archi#663]
### Version of Archi
4.4 32b and 4.7.1 64b

### Archi Plug-ins
none

### Operating System
WIN 10

### Actual Behaviour
There are cases when after some investigation user wants to change the relationship type.

E.g. changing "Associated to" into "Serves" relation.

Current way is to draw the new relation and remove the old one. This leads to mistakes, when the original relation is present in more views.

Workaround is to edit the .archimate file and change xsi:type="archimate:AssociationRelationship" into the desired one.

### Expected Behaviour
a) add change action into the contextual menu of the existing relation in the view
![image](https://user-images.githubusercontent.com/6020891/90246626-4e820c00-de35-11ea-99eb-e4af6fa6cd95.png)

`"Change relation type to..."` would list allowed relation types

b) add change action into the contextual menu of the existing relation in the model

![image](https://user-images.githubusercontent.com/6020891/90246764-95700180-de35-11ea-9da1-78ed4b238d30.png)

`"Change relation type to..."` would list allowed relation types

**Comment by Phillipus** [comment]
This request has been proposed several times. It can be achieved with a jArchi script - https://gist.github.com/smileham/a989e42e8db2d811f5f1427147b39e2e

**Comment by radeksvarz** [comment]
@Phillipus Apologies. I tried to find relevant issues, but without success.

**Comment by Phillipus** [comment]
> @Phillipus Apologies. I tried to find relevant issues, but without success.

No problem.

**Comment by Phillipus** [comment]
This is in Archi 5.1 beta.
