### ISSUE TITLE
[Improvements] Add an “id-” prefix to html report tree structure to link with id in xml report

### ISSUE THREAD

**Issue by egar4mimil** [archimatetool/archi#664]
In 4.7 version, "id-" prefix was added to all newly generated internal IDs and to legacy IDs that begin with a digit when exporting to exchange format.
In html report export, there isn't this prefix in tree structure (directory and file name), so we can't use xml export to retrieve html link.

**Comment by Phillipus** [comment]
I don't understand this:

> In html report export, there isn't this prefix in tree structure (directory and file name), so we can't use xml export to retrieve html link.

**Comment by egar4mimil** [comment]
In XML report, now we have something like this :
`<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.opengroup.org/xsd/archimate/3.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengroup.org/xsd/archimate/3.0/ http://www.opengroup.org/xsd/archimate/3.1/archimate3_Diagram.xsd" identifier="id-7c520b91-6710-4eec-a4fb-1b76638cafca">
  <name xml:lang="fr">Test</name>`

But in html report we have a directory like this :
`\7c520b91-6710-4eec-a4fb-1b76638cafca\views\...`

We don't have the same id in xml and in html report.

**Comment by Phillipus** [comment]
As I explained here:

https://github.com/archimatetool/archi/issues/625

We are trying to preserved the original ID where possible and only add the "id-" prefix to a legacy ID when exporting to the XML format because we have to (IDs can't start with a number). 

IDs are internal. Do not depend on them.

**Comment by Phillipus** [comment]
I'll close this because this won't change.

**Comment by egar4mimil** [comment]
I developped a little app which read the XML export, expose graph, node and generate link to HTML report and ids are different.

But i understand

**Comment by Phillipus** [comment]
In fact this has not been affected by the changes in 4.7. Even in Archi 4.6, with a number like "7c520b91" that would be exported as "id-7c520b91" in the xml export and "7c520b91" in the html report.

**Comment by egar4mimil** [comment]
Before I use only CSV export.

I think, it would be better to use same id in all cases.
