### ISSUE TITLE
[Feature Request] Auto Save

### ISSUE THREAD

**Issue by achampion** [archimatetool/archi#667]
Would be really useful to have an auto save configuration option (frequency).
Or just very good undo and models perma-saved, which seems to be an increasingly common approach.

**Comment by Phillipus** [comment]
Sorry, but for various reasons this isn't going to be implemented. Better to be realistic and close this one.

**Comment by Droppers** [comment]
@Phillipus with "for various reasons", do you mean from a technical or functional point-of-view? Because I take auto-saving for granted (majority of the IDEs and Office products have auto-saving) and have several times made the mistake of forgetting to save before shutting down / restarting 😄.

**Comment by Phillipus** [comment]
> @Phillipus with "for various reasons", do you mean from a technical or functional point-of-view?

Technical.

> Because I take auto-saving for granted (majority of the IDEs and Office products have auto-saving) and have several times made the mistake of forgetting to save before shutting down / restarting 😄.

Fortunately, Archi is open source so you or someone else can contribute the code to implement it. 😄

**Comment by Droppers** [comment]
I would love to, but I'm sure it is a bit more work than just creating a background job that calls save for each model periodically 😄, but if I ever have some spare time I could try 👍
