### ISSUE TITLE
Model Treeview fails to update

### ISSUE THREAD

**Issue by kdrangej** [archimatetool/archi#668]
### Version of Archi

4.7.1 202007151058

### Archi Plug-ins
Archi Excel 0.1.0
Archi Model Repository 0.6.2
Archi Model Repository Command Line 0.6.2
Archi Scripting 0.7.2
Archi Scripting Command Line 0.7.2
Archi Scripting Example 0.7.2
Lightbox for Archi

### Operating System
Window 10 Pro 

### Expected Behaviour
Elements in the models/treeview should never disappear when you are working with the window, or when you select or work with the elements in the treeview. 

### Actual Behaviour
Occasionally on refresh the entire models treeview nodetree disappear and nodes individually reappear when you hover over them. When the control refreshes on (invalid) the tree is fully functional until it glitches again.

### Steps to Reproduce the Behaviour
The behavior occurs at random

**Comment by Phillipus** [comment]
I've not encountered this problem before.

Is this only one one machine? Is it a graphics card or driver issue? Do you have a large amount of child nodes open?

The tree can be slow refreshing if you have many models and tree nodes open.

**Comment by kdrangej** [comment]
This happens on both my home computer and office computer. I will attempt to take a screenshot next time it occurs.

**Comment by Phillipus** [comment]
Any issue related to the tree depends on how many tree nodes are open and what you are doing at the time. For example, is it drag and drop? Running a jArchi script? Renaming? Adding new objects?

Try closing some tree nodes to reduce the load on the tree.

**Comment by kdrangej** [comment]
Thanks for the tip. It seems completely random. I had quite a few occurrences of the bug today when working in different models (which lead me to file the bug report) but it has been absolutely fine for the rest of today.

**Comment by kdrangej** [comment]
I have been unable to reproduce. I am leaning towards maybe it is a graphics card issue. I will reopen the case if I can get a screenshot of the error when it happens.
