### ISSUE TITLE
Label expression $source{type} of a relation is not resolved, while $source{name} works fine

### ISSUE THREAD

**Issue by olwol** [archimatetool/archi#673]
### Version of Archi

com.archimatetool.editor.buildid=202007151058
com.archimatetool.editor.versionid=4.7.1

### Archi Plug-ins

![grafik](https://user-images.githubusercontent.com/71402184/93383692-4bc76c00-f864-11ea-8941-4241a70699b8.png)

### Operating System

os.arch=amd64
os.name=Windows 10
os.version=10.0

### Expected Behaviour

With the label expression of the aggregation relation shown in the picture
$source{type} "$source{name}"
${name}
$target{type} "$target{name}"
[${type}]

I would expect what is shown in the picture while I see the actual behaviour shown in the picture as well:

![grafik](https://user-images.githubusercontent.com/71402184/93389775-efb51580-f86c-11ea-9977-448c43147b66.png)

### Actual Behaviour

So 
*$source{type}*
*$target{type}*
is not resolved, while *$source{name}* and *$target{name}* works fine.

### Steps to Reproduce the Behaviour
Set the label expression of the aggregation relation to:
$source{type} "$source{name}"
${name}
$target{type} "$target{name}"
[${type}]

Is my expectation wrong?

**Comment by Phillipus** [comment]
I think your expectation is correct, however the current implementation of `${type}` does not support reference prefixes.

However, I've just pushed a speculative fix for this, and with some more testing should be part of the next version of Archi.

**Comment by Phillipus** [comment]
Testing your example case with the speculative fix results in this:

![Image 1](https://user-images.githubusercontent.com/600504/93391550-428bce80-f867-11ea-9dc9-f67d43e270c0.png)

**Comment by olwol** [comment]
Thanks a lot for your quick response. Looking forward for the next version of Archi.
With kind regards, Olav
