### ISSUE TITLE
[Feature Request] Add Multiple [element/relationship]

### ISSUE THREAD

**Issue by pgartlan-kd** [archimatetool/archi#680]
Hi, when creating lots of things, it would be good if you could double-click something on the palette and stay in that mode until you press "esc".
For example:
1) double click application component
2) add lots of application components to a view
3) press esc
4) double click aggregation relationship
5) link lots of application components as aggregrates.
6) press esc

Merci

**Comment by jbsarrodie** [comment]
Hi,

Read the Archi User Manual and you'll find the answer ;-)

**Comment by pgartlan-kd** [comment]
oops I had read it but missed that - thanks for the heads up
