### ISSUE TITLE
[Feature Request] Add to current diagram from visualiser

### ISSUE THREAD

**Issue by pgartlan-kd** [archimatetool/archi#682]
The visualiser is an awesome way to explore the model from within a current diagram. It would be great to be able to right click on an element in the visualiser and add it to the current diagram. Would save much back-n-forth via navigator etc

Merci

**Comment by lavenderb** [comment]
I'm very much in agreement with this request.
I'm finding that the Visualiser is a very powerful utility for managing large models and the ability to **drag an element** across to the current diagram would be much more efficient than the current sequence: 
 - Right click element in Visualiser
 - click 'Select in Model Tree'
 - Drag & drop from Model Navigator
 - Close Model Tree Folders (expanded in earlier step)
 - Restore Visualiser context to original element & repeat

**Comment by Phillipus** [comment]
Drag and drop outside of the Visualiser isn't possible, I'm afraid.

**Comment by isalew** [comment]
200% agreed with the value here. It's very tedious to see an item in the visualizer, but have to search for it in the "Models" pane, resetting any filters you have set there.

**Comment by Phillipus** [comment]
As drag & drop from the Model Navigator outside of the Visualiser isn't possible (see https://github.com/archimatetool/archi/issues/682#issuecomment-1192384738) and as Archi doesn't have psychic powers to know where exactly to add the element in the current View I suggest the following:

1. Select as required in the Visualizer
2. Click the pin button in the Visualizer toolbar ("Pins the current view")
3. Right click element in Visualiser
4. Click 'Select in Model Tree'
5. Drag & drop from Model Navigator to the current View
