### ISSUE TITLE
java.lang.IllegalAccessError in AbstractDiagramEditor

### ISSUE THREAD

**Issue by sudr** [archimatetool/archi#685]
The below line in 4.7.1 is throwing the following error when editing text in a Note element:
 
https://github.com/archimatetool/archi/blob/81563015fb7fbd9978c4a38d055deeb42f485633/com.archimatetool.editor/src/com/archimatetool/editor/diagram/AbstractDiagramEditor.java#L641

!ENTRY org.eclipse.jface 4 2 2020-10-26 10:52:11.162
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.IllegalAccessError
        at java.base/jdk.internal.misc.Unsafe.throwIllegalAccessError(Unknown Source)
        at com.archimatetool.editor.diagram.AbstractDiagramEditor.refreshFiguresWithLabelFeature(AbstractDiagramEditor.java:641)
        at com.archimatetool.editor.diagram.AbstractDiagramEditor.commandStackChanged(AbstractDiagramEditor.java:609)
        at org.eclipse.gef.commands.CommandStack.notifyListeners(CommandStack.java:345)
        at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:240)

My JVM is on Mac OS version 10.15.7: 
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.3+7
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.vendor=AdoptOpenJDK
java.vendor.url=https://adoptopenjdk.net/
java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-build/issues
java.vendor.version=AdoptOpenJDK
java.version=11.0.3
java.version.date=2019-04-16
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=AdoptOpenJDK
java.vm.version=11.0.3+7

I have the following plugins installed:
Archi Model Repository                            - 0.6.2.202004031233
Archi Model Repository Command Line - 0.6.2.202004031233
Archi Scripting                                          - 0.8.0.2020206231201
Archi Scripting Command Line               - 0.8.0.2020206231201
Database export/import plugin               - 2.2.12

**Comment by Phillipus** [comment]
Under what circumstances? Any way to reproduce this?

**Comment by sudr** [comment]
I've added additional information to the issue description above.

**Comment by Phillipus** [comment]
Could be the Database plugin conflicting. Try removing that plug-in.

**Comment by sudr** [comment]
Uninstalled the database plugin and restarted and the issue persists.

**Comment by Phillipus** [comment]
Please try with no plugins and then add them back one at a time to narrow it down.

**Comment by Phillipus** [comment]
Also, please provide steps to reproduce. 

What version of MacOS?

I'm trying to help but you're not providing enough info!

**Comment by sudr** [comment]
Added the Mac OS version to the issue description.

Once I uninstalled the script plugin the issue went away. But I've not re-installed the script plugin and cannot reproduce the issue.

**Comment by Phillipus** [comment]
OK.

The `java.lang.IllegalAccessError` can occur if an older Java class is accessed. We had to update some Java classes in Archi 4.7.1 to implement Label expressions.

This error can happen if you use Herve's Specialization plug-in as well as using Archi's Label expressions. This is because this plug-in is accessing an older version of the Java classes.

I don't think the Script plug-in should affect it.

**Comment by sudr** [comment]
That sounds right. I installed the specialization plugin and am seeing exceptions.

Do you have any insight as to when the specialization plugin might be updated to the newer Java classes?

**Comment by Phillipus** [comment]
> Do you have any insight as to when the specialization plugin might be updated to the newer Java classes?

It's Herve's plug-in, so you'd need to ask him - https://github.com/archi-contribs/specialization-plugin

**Comment by herve91** [comment]
Hi @sudr 

I'll give a priority to this and will provide you with a new version of the plugin ASAP.

Best regards
Hervé
