### ISSUE TITLE
ARM defaults should not include any reverse relationship

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#687]
I've just discovered that by default ARM setup includes creating reverse relationships (I didn't noticed before as I usually test new version with an existing configuration). This should not be the case as this is not explicitly allowed in ArchiMate (and I think we should stick to "compliant" defaults), and this offers too many choices to users when nesting elements.

Could we change this in 4.8?

**Comment by Phillipus** [comment]
Done.
