### ISSUE TITLE
Group and Grouping tab size does not fit Text

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#688]
### Version of Archi
4.7.1

### Archi Plug-ins
N/A

### Operating System
Windows

### Expected Behaviour
"Group" and "Grouping" label fits within the tab box regardless of text length and font size

### Actual Behaviour
![Grouping Title](https://user-images.githubusercontent.com/2892935/98841758-7981f900-2440-11eb-95b0-c72111f472c9.png)

### Steps to Reproduce the Behaviour
1. Drag on Group/Grouping component
2. Enter Text in Tab name
3. Set font to size 18

**Comment by Phillipus** [comment]
That's just the way it is if you use a bigger font. The figure is drawn with a fixed tab size.

**Comment by Phillipus** [comment]
However, should anyone want to have a go at a patch, you'd need to do at least the following:

- When drawing a Group or Grouping Figure get the local font height
- Convert the font height to pixels for each platform
- Check whether hi DPI is being used to calculate the font height
- Check whether the figure's text is positioned at the top of the figure
- Redraw the whole figure depending on the calculated height
- Refactor the connection anchor to take account the new height
- Ensure there are no regressions with the newly drawn figure
- Test on all platforms and three different versions of macOS, three test versions of Linux at different DPI scaling

I might have missed something.

**Comment by jbsarrodie** [comment]
> However, should anyone want to have a go at a patch, you'd need to do at least the following:
> 
> * When drawing a Group or Grouping Figure get the local font height
> * Check which figure is being drawn (tabbed or plain)
> * Check whether there is text visible in the figure
> * Convert the font height to pixels for each platform
> * Check whether hi DPI is being used to calculate the font height
> * Check whether the figure's text is positioned at the top of the figure
> * Redraw the whole figure depending on the calculated height
> * Refactor the connection anchor to take account of the new height
> * Ensure there are no regressions with the newly drawn figure
> * Test on all platforms including two versions of Windows, three different versions of macOS, three test versions of Linux at different DPI scaling
> * Perhaps a unit test as well
> 
> I might have missed something.

Actually, there might be another way to solve this: When using the tabbed mode, we could force text position to top left and the font size to a size known to work in (almost) all cases. Slightly better: we could define the real text box so that it fits the tab header, this would also forces ellipsis when text is too long.

**Comment by Phillipus** [comment]
Actually, it was a little easier to implement than I thought. So we can test it in the next beta.

**Comment by Phillipus** [comment]
Close this, as it will be in Archi 4.8 EA2.

**Comment by Phillipus** [comment]
Discussion is continuing in #689
