### ISSUE TITLE
[XMLExchange] folder id's are ignored on export and import

### ISSUE THREAD

**Issue by markbacker** [archimatetool/archi#690]
### Version of Archi
Archi 4.7.1

### Archi Plug-ins
jArchi and coArchi

### Operating System
Windows 10 64

### Expected Behaviour
When exporting a model to a XMLExchange file, all the objects, including folders, have an attribute id. 
When importing a XMLExchange file with folders with id's, a new model is created with folders with de same id's. 

### Actual Behaviour

When exporting a model as an XMLExchange file, the id attribute of folders is not exported.
When importing a XMLExchange file with folder id's, the id's are ignored. The imported model has folders with new generated id's

We need these folder id's to be able to merge architecture models coming from different tools. Now if we merge the two models, in the result all the subfolders are duplicated

Is it possible to also export and import folder id's?

**Comment by Phillipus** [comment]
These are not really "folders".

In the exchange format, there is the notion of an "organization" containing items. This represents an abstract organization of items that refer to other objects in the model. It might be a table of contents, or some arbitrary collection of grouped objects. It might be a set of folders, or it might not.

As Archi uses the "organization" structure for folders we can easily export the IDs of these, but we cannot guarantee what will happen when importing from another tool. If the other tool creates an "item" with an ID and it is deemed to be a folder we can set the folder ID to that but I'm not sure what side-effects there may be.

But we can try it in an Archi beta and test it.

**Comment by markbacker** [comment]
Yes, please. If there is a beta I can test it.

**Comment by Phillipus** [comment]
> Yes, please. If there is a beta I can test it.

I'll add this in the next Archi 4.8 Early Access build.

**Comment by Phillipus** [comment]
Hi Mark,

I took another look at the XML Exchange code and think that setting IDs on folders when importing the XML file might lead to problems with the existing import code.

The code to import the organizations/items is quite complex because another tools' folder structure will be different from Archi's structure and so we make a best attempt to try to map each item onto Archi's folder structure. It doesn't always lead to perfect results.

I wrote this code some time ago and it took a long time to do it and it's not foolproof. In order to add incoming IDs on folders all of that chunk of code would need to be re-examined and probably re-written. That will take several days of my life. If anyone wants to take a look at it's here:

https://github.com/archimatetool/archi/blob/master/org.opengroup.archimate.xmlexchange/src/org/opengroup/archimate/xmlexchange/XMLModelImporter.java

**Comment by markbacker** [comment]
Hi Phil,

That's a bummer. Thanks for looking into it. I also had a look at the code, and indeed, it is a long and complex. 

We will have to find another sollution. I'm thinking now of a jArchi script to be run after a import. The script should move all synchronized objects back to their original folder and then delete the duplicate folder. 

Thanks,

Mark

**Comment by Phillipus** [comment]
Hi Mark,

it can be done in theory...if a better algorithm can be devised to parse the imported organization/item structure given that:

- There might zero or more organization/item entries
- An item might or might not have an identifier
- An item might have the same name as another one
- More than one item might reference the same object
- The structure of the imported organization bears no relation to Archi's folder structure

The current code is a best attempt at this but does not handle some edge cases. It's based on this issue #288

It's just one of those things that has taken a lot of time, and requires more than one person to perfect it,.

**Comment by Phillipus** [comment]
A quick example of one case where this can't work.

A tool exports a folder structure as in this pseudo-XML:

```
<item Folder1 identifier="1">
   <item Folder2 identifier="2">
      <item BusinessActor>
      <item ApplicationComponent>
   </item>
</item>
```

Archi re-creates it as:

```
Business
    |----Folder1
             |---- Folder2
                       |---- BusinessActor
Application
    |----Folder1
             |---- Folder2
                       |---- ApplicationComponent
```

Because of the split we can't re-use the imported identifiers of Folder1 or Folder2 as we have created two more sub-folders.

**Comment by Phillipus** [comment]
Mark, I'll close this one for now.

**Comment by markbacker** [comment]
Yes, I understand. 
I see the problem with de folder structure you show. I guess the only way to really solve this, is to specify the folder structure as part of the ArchiMate standard.
