### ISSUE TITLE
Default figures

### ISSUE THREAD

**Issue by szuniga** [archimatetool/archi#691]
### Version of Archi

4.8 EA1
### Archi Plug-ins

Yes
### Operating System

Windows 10
### Expected Behaviour

All default figures can be selected to change their appearance.
### Actual Behaviour

Just some of the default figures can be selected.
### Steps to Reproduce the Behaviour
1. Edit
2. Preferences
3. Diagram
4. Default Figures
5. Try to select, e.g., Goal

**Comment by Phillipus** [comment]
Goal does not have an alternative figure. In fact we have not implemented several alternative figures. Perhaps we will in an update.

**Comment by Phillipus** [comment]
Actually if anyone wants to contribute alternative figures we're open to contributions. My estimate is 3-4 weeks work.

**Comment by Phillipus** [comment]
I'll close this. Adding alternate shapes might happen in a future update.
