### ISSUE TITLE
NF: UML Elements

### ISSUE THREAD

**Issue by tkazimie** [archimatetool/archi#692]
Achimate as a notation does not provide sequence diagrams nor state machine diagrams. 
I am aware that it is possible to emulate them using some elements from Archimete but this is ugly and not really compliant not with Archimate nor with UML.

How about allowing drawing some of UML diagrams as Skatch diagram is allowed. This would help a lot when we want to have all types of diagrams in the single repository. I am concerned especially on sequences (this would be highest priority) and next state machine diagrams (as nice to have). All the rest UML is easy to mimic in Archimate.

**Comment by Phillipus** [comment]
I don't think this is likely in the immediate future. Unless we completely refactor the whole of Archi's Figure framework to allow different types of shapes (and more shapes).
