### ISSUE TITLE
Tabbed Group and Grouping show label expression completely in the tab

### ISSUE THREAD

**Issue by larspijnappel** [archimatetool/archi#693]
### Version of Archi
Archi 4.8 Early Access 2 (Windows 64-bit Portable Zip)
### Archi Plug-ins
No
### Operating System
Windows 10 Pro
### Expected Behaviour
Both Group and Grouping with Tabbed Border show any newline part of the expression _below the tab_
![image](https://user-images.githubusercontent.com/12656725/99833754-cfeae800-2b62-11eb-9b31-e3c5a4d745c8.png)

### Actual Behaviour
Both Group and Grouping with Tabbed Border show the complete label expression _in the tab_
![image](https://user-images.githubusercontent.com/12656725/99833584-839fa800-2b62-11eb-92d1-a79c08af9d34.png)

### Steps to Reproduce the Behaviour
1. Add label expression `${name}\n${name}` to see this behavior.

**Comment by Phillipus** [comment]
That's because of #689

**Comment by Phillipus** [comment]
@larspijnappel I'll close this issue, just so the discussion can continue in one place - #689
