### ISSUE TITLE
Value 'archimate:ValueStream' is not allowed for attribute 'xsi:type'.

### ISSUE THREAD

**Issue by philover** [archimatetool/archi#697]
### Version of Archi

4.7.1
### Archi Plug-ins

No
### Operating System

Windows
### Expected Behaviour

I change an element from any other type (let's say Business Process) to a ValueStream. Then I want to move this element to the Strategy folder (where it belongs). 
### Actual Behaviour

Model seems to work fine, I am not able to drag ValueStream element to Strategy folder. When I edit the .archimate file in a XML-editor and I move the ValueStream element to the Strategy folder, the model still works fine.
But when I open the model in an XML-Editor that validates the model to the defined namespace xsi, I get a warning. My hunch is the defined namespace is unaware of the xsi:type "ValueStream".

Resolution(s) could be:
1. update the namespace definition or,
2. define a new namespace for spec 3.1.

### Steps to Reproduce the Behaviour
1. Create new model
2. Add ValueStream element
3. Drag element to default view
4. Safe model
5. Open model in Alltova XML-Spy
6. Validate XML there

Validation Messages:
Warnings
	File C:\Users\Phil\Documents\philtest.archimate has warnings.
		Value 'archimate:ValueStream' is not allowed for attribute 'xsi:type'.
			Warning location: archimate:model / folder / element / @xsi:type
			Details
				cvc-attribute.5: Value 'archimate:ValueStream' of attribute 'xsi:type' must resolve to a type definition.
				cvc-assess-elt.2: Assessment of attribute 'xsi:type' failed.
				cvc-assess-elt: Lax assessment of element <element id="id-5a97ccc4809649d0881d5ead5e3d0cb0"> failed.

Archimate file
`<?xml version="1.0" encoding="UTF-8"?>
<archimate:model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:archimate="http://www.archimatetool.com/archimate" name="philtest" id="id-3ea61e2f9b67476684ead27f32fe0220" version="4.6.0">
  <folder name="Strategy" id="id-88c3cfabff2b40a59d89f56273d7b0d4" type="strategy">
    <element xsi:type="archimate:ValueStream" name="vstest" id="id-5a97ccc4809649d0881d5ead5e3d0cb0"/>
  </folder>
  <folder name="Business" id="id-36fba76f46424dd58a2c822a8b2e47d9" type="business"/>
  <folder name="Application" id="id-a5a4eb4c7d624095bc860181701e87c0" type="application"/>
  <folder name="Technology &amp; Physical" id="id-7e11b5db1b6f46c8a81f818a9e4c062d" type="technology"/>
  <folder name="Motivation" id="id-841fd5fe3105458fbdf8ef37e6b4a73a" type="motivation"/>
  <folder name="Implementation &amp; Migration" id="id-2aad51e51c214d938be85af1274a4a97" type="implementation_migration"/>
  <folder name="Other" id="id-6e410e032dd5423582bff7f10dbe80e9" type="other"/>
  <folder name="Relations" id="id-911a26399dd74ee7a7ec16ad0ab1937c" type="relations"/>
  <folder name="Views" id="id-14da1f9877a746e4bc7af97b121dc980" type="diagrams">
    <element xsi:type="archimate:ArchimateDiagramModel" name="Default View" id="id-f3c633ad61b24d4c87c0139bb6c29bc0">
      <child xsi:type="archimate:DiagramObject" id="id-59d9dcdae26540aa9af06041cddb33f8" archimateElement="id-5a97ccc4809649d0881d5ead5e3d0cb0">
        <bounds x="120" y="113" width="120" height="55"/>
      </child>
    </element>
  </folder>
</archimate:model>
`

**Comment by jbsarrodie** [comment]
>I change an element from any other type (let's say Business Process) to a ValueStream. Then I want to move this element to the Strategy folder (where it belongs).

Changing the type of an element is only possible through jArchi and of course moves it to the right folder.

> When I edit the .archimate file in a XML-editor and I move the ValueStream element to the Strategy folder, the model still works fine.

This should never be done (the XML file should never be updated outside Archi for obvious integrity reasons)

So my question is: how did you change the type of the element?

**Comment by Phillipus** [comment]
I don't understand the problem here. Why are you trying to validate the XML? If you do that you need the XSD Schema.

**Comment by Phillipus** [comment]
1. If you change the internal contents of an .archimate file it's at your own risk. It might or might not work.
2. If you are going to validate the xml in an  .archimate file then you need all the XSD Schema files for the *.archimate format and eCore model format for validation.

So I'll close this.

**Comment by philover** [comment]
Hi Phil,

The issue is not that I cannot validate the model actually. The issue is that I cannot move a ValueStream element to the Strategy folder. To me it seems that there is a validation rule in Archimate that prevents me to move the element according to the definition of the namespace.

Met vriendelijke groet,​
​
Phil Overbeeke
 |
Informatie Analist / Solution Architect
[X]<https://www.transfer-solutions.com/>
Transfer Solutions
Dokter Reilinghplein 2
4141 DB Leerdam
T
M
E
+31 345 616888 <tel:+31345616888>
+31 6 12672197<tel:+31%206%2012672197>
phil.overbeeke@transfer-solutions.com<mailto:phil.overbeeke@transfer-solutions.com>
[X]<https://dutchitawards.nl/3295/stemmen.html>

**Comment by Phillipus** [comment]
>  The issue is that I cannot move a ValueStream element to the Strategy folder. T

You mean you cannot move a ValueStream element to the Strategy folder **after you changed it manually in the XML from another type.** 

This is a UI constraint in Archi to disallow moving elements in different folders. The simple solution is don't mess with the internal stuff!

**Comment by jbsarrodie** [comment]
@philover 

> The issue is not that I cannot validate the model actually. The issue is that I cannot move a ValueStream element to the Strategy folder. To me it seems that there is a validation rule in Archimate that prevents me to move the element according to the definition of the namespace.

There is no way in Archi to change the type of an element, thus no way to have a Value Stream element outside the Strategy folder. You said you have no plugin, thus you can't have changed the type of a process.

Again, the only way to do this is through jArchi. So please clarify what you are doing or else there's nothing we can do.

**Comment by philover** [comment]
Sorry, but I was flabbergasted by your prompt reaction. I had the impression the archimate file format is open as the archimate modelling itself. I just ran into this warning and had the intention to assist you. Mainly because the warning also occurs on a model created from scratch with the archimatetool. I will look into the capabilities of jArchi. That's all for now. Thanks for your swift response.

**Comment by Phillipus** [comment]
The `*.archimate` file format is for Archi only and so should be considered proprietary. You're thinking of The Open Group's Exchange format (https://www.opengroup.org/open-group-archimate-model-exchange-file-format).

If you are going to validate any XML you have to validate against its XSD schema otherwise you will only see validation warnings and errors. The Open Group's file format has a published schema, whilst Archi's schema is internal as it is generated from the Eclipse modelling framework.
