### ISSUE TITLE
Feature Request: merging models respecting the identity of Archi objects

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi#698]
Occasionally I cut a fragment `F` from a model (e.g. a view) and paste it into a different model `T`. The current semantics of this is a "disjoint union". That is: all elements from `F` and `T` are present in the combined model. It is now possible that there are multiple elements with the same type and name sitting in the combined model.

For example: Suppose `F` contains an Archi object (with internal identifier 96a0c822-d611-420c-9b57-dc2f15da36f0) of type "ApplicationComponent" and name "File Upload Server". At the same time, `T` contains an Archi object (with internal identifier c28e684f-600b-4aeb-a247-92040e595168) of type "ApplicationComponent" and name "File Upload Server". In this case, I get two Archi objects with the same type and name in the combined model. If both Archi objects have a number of relations attached, I have to do tedious "plumbing" to turn them into one object.

The problem is that I want objects with the same type and name to be identical because there are relations attached to them that need to be combined in the new model. Doing that by hand is utterly impractical. I need the semantics of "union" rather than "disjoint union".

So, I would like to have a way of merging that respects the identity of Archi objects and merges these two objects into one. This can be done by substituting one of the internal identifiers systematically with the other internal identifier, throughout the entire combined model.

The architectural principle here is that objects with the same type and name are identical and are therefore represented in a model only once. I am asking to promote this principle to be a feature of Archi and apply it consistently throughout the software.

**Comment by Phillipus** [comment]
The Import/Merge feature works on the basis of objects' internal identifiers to determine uniqueness. This is by design and so it's not something that will change in this feature.

Of course someone could write a plug-in or a jArchi script that could import/merge objects based on other criteria.

**Comment by stefjoosten** [comment]
The implementation of this feature request is slightly different with properties, because properties don't have an internal identifier in Archi. A property is basically a key/value pair. So, for example, if I have Archi object `o` in model `F` with properties "(repr, Philip)", "(repr, John)", and "(source,240)", and I have Archi object `o'` in model `T` with properties "(repr, Sarah)", "(repr, Jane)", "(repr, John)", and "(idiom,cluster)", then there should be one combined object `o''` in the combined model with properties "(repr, Philip)", "(repr, John)", "(source,240)", "(repr, Sarah)", "(repr, Jane)", and "(idiom,cluster)". This too is not the disjoint union of properties, but the union (where a property is seen as a set of key/value pairs).

**Comment by stefjoosten** [comment]
Do you know of any such plug-in? Is there a list of known plug-ins somewhere?

**Comment by stefjoosten** [comment]
> The Import/Merge feature works on the basis of objects' internal identifiers to determine uniqueness. This is by design and so it's not something that will change in this feature.
> 
> Of course someone could write a plug-in or a jArchi script that could import/merge objects based on other criteria.

Do you know of any such plug-in? Is there a list of known plug-ins somewhere?

**Comment by jbsarrodie** [comment]
> The architectural principle here is that objects with the same type and name are identical and are therefore represented in a model only once.

In the ArchiMate standard, it is possible to have multiple objects of the same type and name. Thus I don't think it would be good to enforce this when merging two models.

It is not too complicated in jArchi to merge concepts based on whatever rule you defined (one colleague created such script), so I'll share such script in the future as soon as I'll have cleaned it a bit.

**Comment by stefjoosten** [comment]
@jbsarrodie, thanks for sharing that. I will look out for it.

Just now I have made a jArchi-script called "[Show duplication.ajs](https://gist.github.com/stefjoosten/cd14441f09e5f625d7320f76def3bf55)" to signal this situation.

**Comment by stefjoosten** [comment]
> > The architectural principle here is that objects with the same type and name are identical and are therefore represented in a model only once.
>
> @jbsarrodie said:
> In the ArchiMate standard, it is possible to have multiple objects of the same type and name. Thus I don't think it would be good to enforce this when merging two models.
> 
Hm, the [ArchiMate standard](https://pubs.opengroup.org/architecture/archimate3-doc/) does not define equality on elements. So it leaves it up to the tool implementor to decide whether or not it is possible to have multiple objects of the same type and name. Archi's answer is "yes", but that cannot be traced to the ArchiMate standard. (@jbsarrodie please point out where I missed the definition of equality between elements in the ArchiMate standard. I don't mind being wrong about this...)

If the ArchiMate standard leaves the equality of elements up to the tool builders, the issue boils down to whether there is a good reason from a user perspective to define that equality.

My plea in the opening comment boils down to a plea to have equality of elements based on name and type within a single model. As a modeler, I want sharing of relations across views to be predictable. Whichever instance of an element I click on, regardless of the view I'm in, I want to see the same analysis and the same list of properties. All of this will still be within the ArchiMate Standard since it does not define equality of elements.

If Archi were to adopt this equality, it would interestingly enough NOT affect the visual representation of any view. It would however ensure that an element with the same name and type is shown with the same analysis and properties throughout the model. It would have to be implemented as a system invariant.

**Comment by jbsarrodie** [comment]
> Hm, the [ArchiMate standard](https://pubs.opengroup.org/architecture/archimate3-doc/) does not define equality on elements. So it leaves it up to the tool implementor to decide whether or not it is possible to have multiple objects of the same type and name.

That's not how it works with the standard: if it is not explicitly forbidden then it is allowed, so it **is** possible to have multiple concepts of the same type and name in ArchiMate (as in most modelling language and/or notation). This is reflected in the [ArchiMate Model Exchange File Format](https://www.opengroup.org/open-group-archimate-model-exchange-file-format) which defines a separate id. The fact that some tools impose to have different names has even been an issue for interoperability testing when developing the exchange format. These tools were considered non compliant.

>My plea in the opening comment boils down to a plea to have equality of elements based on name and type within a single model. As a modeler, I want sharing of relations across views to be predictable. Whichever instance of an element I click on, regardless of the view I'm in, I want to see the same analysis and the same list of properties.

I do think that most of the time we (as practitioners) should try to avoid "name duplicates" (let's call them this way). That's why it's useful to have such rule implemented in Archi's Validator. But I know lot's of cases which forces people to have "name duplicate". One of the best example is data modelling: As soon as a model encompass multiple business domains (that's my case), then it becomes impossible to avoid "name duplicates" because it is perfectly right for different business to use the same word (thus Business Object) while attaching a different meaning. The real issue behind is not the name itself but the need for a kind of namespace.

**Comment by Phillipus** [comment]
> If Archi were to adopt this equality

That ship sailed long ago.

All of Archi's code is based on the equality of objects' identifiers. That's not going to change so, for me, this discussion is purely academic.

**Comment by stefjoosten** [comment]
Well, let's leave the discussion to the academics then.

In the meantime, I have published a second [jArchi code snippet](https://gist.github.com/stefjoosten/0f274aaf84d7ac0cd3ebe6992b084aee) to ensure that all elements that share type and name are one and the same element. Executing it does not affect any views and is idempotent.
