### ISSUE TITLE
Can not start application installed via snap on Ubuntu

### ISSUE THREAD

**Issue by Mariyo** [archimatetool/archi#708]
Hi,

I try to install Archimate 4.7.1 using snap on Ubuntu 20 via command `snap install archimate`, but when I want to start application via command `archimate` it fails.

First I found that there was issue with permissions: `The configuration area at '/home/mariyo/.archi4/.config' could not be created.  Please choose a writable location using the '-configuration' command line option.` This i fixed with new directory.

Now, there is this error with which I stuck: `!MESSAGE Error reading configuration: Unable to create lock manager.`

![image](https://user-images.githubusercontent.com/1678254/107856371-02397800-6e28-11eb-8817-b91dd33ff554.png)

Could you please help me?

Thank you

**Comment by Phillipus** [comment]
That Snap distribution is unauthorised, completely unsupported and nothing to do with me. I have asked them to remove it and it is still there.

Closing this.
