### ISSUE TITLE
Error Message of Running Archi in ChromeOS

### ISSUE THREAD

**Issue by yasenstar** [archimatetool/archi#709]
Cannot start Archi.

### Version of Archi
4.8.1

### Archi Plug-ins
none

### Operating System
ChromeOS, version 90.0.4411.0

### Expected Behaviour
Open Archi

### Actual Behaviour
when running using my normal user, I got below error:

~/Archi$ ./Archi
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

Then using sudo, can see the full error:

Archi:
JVM terminated. Exit code=13
/home/[usernmae]/Archi/jre/bin/java
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area=@user.home/.archi4
-Dosgi.configuration.area=@user.home/.archi4/.config
-Dorg.eclipse.equinox.p2.reconciler.dropins.directory=%user.home%/.archi4/dropins
-Declipse.p2.data.area=@config.dir/.p2
-jar /home/[usernmae]/Archi/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /home/[usernmae]/Archi/Archi
-name Archi
--launcher.library /home/[usernmae]/Archi/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.0.v20200915-1442/eclipse_11201.so
-startup /home/[usernmae]/Archi/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
--launcher.overrideVmargs
-exitdata 1801b
-cleanConfig
-vm /home/[usernmae]/Archi/jre/bin/java
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area=@user.home/.archi4
-Dosgi.configuration.area=@user.home/.archi4/.config
-Dorg.eclipse.equinox.p2.reconciler.dropins.directory=%user.home%/.archi4/dropins
-Declipse.p2.data.area=@config.dir/.p2
-jar /home/[usernmae]/Archi/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar

### Steps to Reproduce the Behaviour
refer to above description, thanks

**Comment by Phillipus** [comment]
The reason you are seeing an error message is because Archi is not supported on ChromeOS.

Closing this,

**Comment by yasenstar** [comment]
Thanks Phil, that's my expectation and hope can make that running as I'm using ChromeBook a lot.

**Comment by Phillipus** [comment]
> Thanks Phil, that's my expectation and hope can make that running as I'm using ChromeBook a lot.

There won't be a ChromeOS version of Archi. We only support Windows, Mac and Linux.

**Comment by yasenstar** [comment]
Maybe I need to be clarify here, I don't seek for native ChromeOS version runtime, actually I've activated the Linux within ChromeOS, so from at least the command terminal perspective, it's actually the Debian based Linux. That's why I'd like to see and test our Linux package, and believe it should be able to configured running.
No problem that we don't commit to running on ChromeOS device, I will do some little further research and see.
Thanks again.
