### ISSUE TITLE
Windows 10: When I re-export a view to overwrite an existing version of the image file, the date of the newly updated file is not being updated to the current TOD

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#710]
Windows 10: When I re-export a view to overwrite an existing version of the image file, the date of the newly updated file is not being updated to the current time-of-day.

!SESSION 2019-09-25 05:00:37.825 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_202
java.vendor=AdoptOpenJdk
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA

!ENTRY org.eclipse.osgi 4 0 2019-09-25 05:00:38.715
!MESSAGE The -clean (osgi.clean) option was not successful. Unable to clean the storage area: C:\Users\mwher\AppData\Roaming\Archi4\.config\org.eclipse.osgi

### Version of Archi

![image](https://user-images.githubusercontent.com/6101736/109230133-99d08c00-7781-11eb-8101-651c5400588c.png)

### Archi Plug-ins

None

### Operating System

![image](https://user-images.githubusercontent.com/6101736/109230174-a7861180-7781-11eb-925e-3f8c66b98b3e.png)

### Expected Behaviour

Windows 10: When I re-export a view to overwrite an existing version of the image file, I expect the date of the newly updated file to be the current time-of-day.

### Actual Behaviour

Windows 10: When I re-export a view to overwrite an existing version of the image file, the date of the newly updated file is not being updated to the current time-of-day.

### Steps to Reproduce the Behaviour
1. See above
2. Exported image file type is: PNG
3. The contents of the file are updated ....just the date for the file is not updated.

**Comment by Phillipus** [comment]
The modified date attribute will be updated, not the date created. This is standard OS behaviour. The same for any file that is saved with the same name.

**Comment by mwherman2000** [comment]
You're right Phil.

This is totally weird: some folders on my Windows 10 laptop use/display a Date column while others use/display a Date Modified column ...apparently somewhat at random. #gofigure

**Comment by mwherman2000** [comment]
I don't think Archi is off the hook Phil.

Repro:
1. Create a new empty subfolder from File Manager/File Explorer called FooBar.
2. Note that it will have a column displayed called Date Modified
3. Now export a view into a new image file inside folder FooBar
4. Archi's export function results in the the Date Modified column being hidden and the Date column being display.

**Comment by mwherman2000** [comment]
Microsoft Paint does the same thing (with a new empty folder).
Microsoft Notepad does not.
