### ISSUE TITLE
Labels are cut off in exported images

### ISSUE THREAD

**Issue by mikisvandijk** [archimatetool/archi#714]
### Version of Archi
Archi 4.8.0

### Archi Plug-ins
Specialization and jArchi installed, probably not relevant

### Operating System
Win 10

### Expected Behaviour
Labels shown in Archi app are fully visible when exported to HTML or PDF
Used font is Segoe 11

### Actual Behaviour
Labels are cut off, last character is not or only partly visible

### Steps to Reproduce the Behaviour
Export any view to PDF or HTML

See attachted screenprint and export
<img width="764" alt="Screenprint Archi" src="https://user-images.githubusercontent.com/75125418/112127654-f169e800-8bc5-11eb-9554-4e939d72594a.png">
[Radiotherapie.pdf](https://github.com/archimatetool/archi/files/6188454/Radiotherapie.pdf)

**Comment by jbsarrodie** [comment]
>Specialization and jArchi installed, probably not relevant

Quite the opposite. Please retry without the Specialization plugin (it hooks in the graphic engine and can introduce issues)

**Comment by Phillipus** [comment]
It's not clear to me from the screenshot which labels are cut off.

Please try Archi 4.8.1 without the Specialization plug-in. If the issue persists, please attach an example `*.archimate` file that demonstrates the problem.

**Comment by mikisvandijk** [comment]
Thanks fo your reactions. I've done some more elaborate testing:

- The issue pertains to SVG and PDF export. 
   Not to BMP and PNG
   Although I remember previous issues with HTML export as well, I couldn't repoduce them now.

- (De)installing the specialization didn't have any impact

- Upgrading from 4.8.0 to 4.8.1 greately reduces the issue (to an acceptible level) but doesn't solve it entirely

- I couldn't reproduce the issue with Arial and Calabri, but I could with Arial Semi-narrow...

Additional info: I do use simple label expressions, but elements without any label-expression attached are also implicated.
I use a 4K monitor; at the moment I have no opportunity to test on a different system.

Attachted screenprint demonstrates the difference before (right) and after (left) the upgrade to 4.8.1

If you still would like a .archimate example I can send my complete model (confidentially) by e-mail or I have to construct something. Let me know.

<img width="1920" alt="Archi pdf export comparison" src="https://user-images.githubusercontent.com/75125418/112145766-0f8e1300-8bdb-11eb-9726-cf3fa6265f74.png">

**Comment by Phillipus** [comment]
Thanks for the extra info.

1. If you could you try the same on a different monitor (not hires 4k) that would help narrow it down, or perhaps another machine.
1. There is a Preference in `General -> Export images at double scale` - is this off or on? Please try with this on and off
1. Could you try with Archi 4.6 (https://www.archimatetool.com/archive/) and compare?

> If you still would like a .archimate example I can send my complete model (confidentially) by e-mail or I have to construct something.

A simple model with one View where you can reproduce the problem would suffice.

**Comment by Phillipus** [comment]
Actually, it's interesting that you see such a difference between 4.8.0 and 4.8.1 as there were no changes made that might affect PDF export.

**Comment by mikisvandijk** [comment]
I'll be back, but probably not today...

**Comment by Phillipus** [comment]
I can get a slightly clipped text label on Windows 10 if I set my display to 200% scaling (not an ideal scenario as all windows are double size) and using Arial Narrow 11 font and a text string of "RT Pre-processing". It seems to happen more on words ending in "g". Also the same on Archi 4.6.0.

I think this won't be something that I can fix. The PDF/SVG export code is borrowed from some old Eclipse code from many years ago (`com.archimatetool.export.svg.graphiti.GraphicsToGraphics2DAdaptor`) and combined with the `Draw2D` library we are seeing miscalculations of string widths when some fonts are used on hi-res devices. The same font and text might render OK on Mac, so it's also an OS thing.

**Comment by Phillipus** [comment]
I found something interesting in the original `GraphicsToGraphics2DAdaptor.java` code:

https://github.com/eclipse/gmf-runtime/commit/2d71b27e2d536c459ae115f92f2b9a5790454078#diff-6472b34090ce6cb354ce805448d72e932824883ce9dcecf658bc2515d4a2cae4

They had a bug related to calculating font height. As an experiment I applied this line:

`height = (int) fsize;`

and my test case rendered OK on Windows at 200% scaling.

**Comment by Phillipus** [comment]
@mikisvandijk Could you test a special build of Archi?

I've uploaded it here - https;//www.archimatetool.com/downloads/beta/Archi-Win64-4.8.1-test.zip

It's the portable zip version of Archi for Windows and won't conflict with your current version of Archi. Just unzip it and run `Archi.exe`

If you could try creating a PDF with this version and report back that would be helpful.

**Comment by mikisvandijk** [comment]
Thanks! I will try it tomorrow...

Op di 23 mrt. 2021 19:16 schreef Phil Beauvoir ***@***.***>:

**Comment by mikisvandijk** [comment]
I've tried and I get interesting results that might help to narrow down the cause:

- First I created a pdf with my scaling (unchanged, as usual) at 150%: no difference, clipping as before
- Then a pdf with scaling at 200%: perfect
- And with scaling at 100%: perfect as well

I hope it is fixable. If not, then at least we've found a work-around: change scaling factor before exporting.

**Comment by Phillipus** [comment]
@mikisvandijk Where are you setting the scaling of 100%, 150% and 200%? In Windows?

> I hope it is fixable. If not, then at least we've found a work-around: change scaling factor before exporting.

The cause is a combination of device scaling, legacy Eclipse code and other factors. There is no real fix, unfortunately. The best we can do is to slightly reduce the size of the font by rounding down the float font size rather than rounding it up to the nearest integer.

The SVG and PDF image export is never going to be perfect. See here - https://bugs.eclipse.org/bugs/show_bug.cgi?id=312723

**Comment by mikisvandijk** [comment]
Yes, I set the scaling In Windows.

BTW I have a two-monitor setup.

My primary screen is the 4K monitor that I use at 150%, the secondary a Full-HD I use at 100%.
I usually run my Archi on the 4K.
