### ISSUE TITLE
Changing appearance (color) of element crashes when trying to add color to color picker

### ISSUE THREAD

**Issue by marceldohmen** [archimatetool/archi#715]
### Version of Archi
4.8.1

### Archi Plug-ins
EIRA plugin

### Operating System
MacOs 11.2.2 (Big Sur)

### Expected Behaviour
when picking a color from color picker and dragging into available slot for preferred colours it should add the color to the available placeholder in the picker and select the color to be used in the appearance of the selected Archimate element

### Actual Behaviour
when picking a color from color picker and dragging into available slot for preferred colours the app crashes, loosing all unsaved changed prior to crash

### Steps to Reproduce the Behaviour
1. Select element (f.i. application component)
2. Select appearance in properties window
3. Click fill color (color picker opens)
4. Select a color from the picker
5. drag the color from the preview box (down left corner) in the picker to an available slot (bottom right part of the picker)

**Comment by Phillipus** [comment]
This isn't specific to Archi. In fact it can happen with other Mac apps on Big Sur. I've reported the issue at Eclipse's bug tracker[1] but the fix is up to Apple.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=568920

**Comment by Phillipus** [comment]
It seems that the crash in the color picker will only occur if all the slots are empty. See the comment here[1].

A workaround is to drag a color into a slot using another app where the crash doesn't happen, for example the TextEdit app, and then try again in Archi.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=568920#c18

**Comment by marceldohmen** [comment]
Indeed, adding a color to color picker slot in another app (notes f.i.) the problem cannot be reproduced any more. So this is a perfect workaround for now. Just remember to save the Archi file before messing with the color picker

**Comment by Phillipus** [comment]
I'll close this as this is a macOS issue (which is still present in 11.4).
