### ISSUE TITLE
Archi Log Error Notification

### ISSUE THREAD

**Issue by kaitlynhall99** [archimatetool/archi#716]
Here is the error that comes up when I try and open Archi on my mac:
<img width="424" alt="Screen Shot 2021-03-30 at 2 41 35 PM" src="https://user-images.githubusercontent.com/81647490/113040787-344c3280-9167-11eb-904d-5e076bb26e44.png">

It then quits after I press Ok. Does anyone know how to resolve this issue? It was working fine a couple weeks ago.

### Version of Archi

The Latest Version

### Archi Plug-ins

No

### Operating System

Mac

### Expected Behaviour

The App Should open

### Actual Behaviour

the app force quits when I try to open it and i cannot access it

**Comment by Phillipus** [comment]
What does it say in the that error log file?
What version of macOS?

**Comment by kaitlynhall99** [comment]
> What does it say in the that error log file?
I'm not sure where to find the error log file, I tried looking in the console and couldn't find it - All I know is the info in the picture.

> What version of macOS?
I'm using Version 10.14.6 - macOS Mojave

**Comment by Phillipus** [comment]
The location of the error log file is in your screenshot.

**Comment by Phillipus** [comment]
I really can't say what's wrong as I've not come across this problem before.

Things to try:

1. Restart your machine
2. Delete the `.config` folder
3. Re-install Archi

Other than that, I can't think of what else to try,

**Comment by kaitlynhall99** [comment]
Ok thanks for the help anyways! I'll try those out.

**Comment by Phillipus** [comment]
Closing this as this can be fixed by deleting the `.config` folder.
