### ISSUE TITLE
SQL error when trying to import database

### ISSUE THREAD

**Issue by stevek421** [archimatetool/archi#718]
**Version of Archi**
v4.8.1

**Archi Plug-ins**
Database plug-in v2.2.16

**Operating System**
Windows 10

We have an Archi repository created under Archimate v4.6 that was last used several months ago and not updated since. As new member of the team, I installed Archimate v4.8.1 and v2.2.16 of the database plugin on my laptop. The MS JDBC driver is also the latest version. When I go to connect to the repository so I can update the model, I get the following error when trying to initiate the import:
 
_Failed to check the database.
SQLServerException: Could not find stored procedure 'sp_RENAME'._
 
I'm able to connect to the SQL database. Tried reinstalling with a slightly older version of Archimate and the plugin, but see the same error. A couple of colleagues who had previously been able to connect under original version and have since upgraded to Archi v4.8.1 and the latest plug-in are also experiencing connection issues. Only person still able to connect is running Archi v4.6 and older plug-in. 

Has anyone experienced anything similar or have suggestion as to what could be causing this? Thx.

**Comment by Phillipus** [comment]
Please can you report this on the tracker for this plug-in:

https://github.com/archi-contribs/database-plugin/issues
