### ISSUE TITLE
[Feature request] Logical operator OR and set separators for label expressions

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#724]
Label expressions would hugely benefit from expansion to logical operators and sets. I'd rather display something than nothing if information in the label expression value is not available. My aim is to seamlessly to switch between languages.

For example, the object expression '${property:fi}' does not currently display anything if the property does not exist for that object. It would be better to be able to express options '${property:fi}<logical OR>$name'.

The logical AND is already present by default. Adding set separators ("parenthesis") would further increase the expressibility of label expressions.

**Comment by Phillipus** [comment]
Archi 4.9 has `if` and `nvl` - https://github.com/archimatetool/archi/wiki/Label-Expressions
