### ISSUE TITLE
[Question] macOS 11.2.3: move/ resize objects with keyboard

### ISSUE THREAD

**Issue by normenmueller** [archimatetool/archi#725]
### Version of Archi
4.8.1

### Archi Plug-ins
n/a

### Operating System
mac OS 11.2.3

### Expected Behaviour
As described in Archi User Guide.pdf: 

> It is possible to move and resize selected objects in a View by using the computer keyboard instead of a mouse. To move an object, press the period key (".") once to reveal the MOVE cursor. Then use the Arrow keys, followed by the ENTER key to commit the move. To resize the object, press the period key (".") until the RESIZE cursor appears at the desired resize handle. Press the ENTER key to commit the resize.

### Actual Behaviour
Pressing the first time "." pops up a notification to grant access to "Accessibility" within the mac OS private security settings. Granting the access, however, does not change the behaviour of Archi. Even after a restart, now nothing at all happens after clicking ".".

### Steps to Reproduce the Behaviour
1. Create an empty model
2. Just drag some object to the empty diagram
3. Click "."
4. Open System Preferences | Security & Privacy | Accessibility and grand 'Archi' access
5. Go back to Archi and click "." or restart Archi and then click "."
6. Nothing happens.

Any hints?

**Comment by Phillipus** [comment]
I just tried this on macOS Catalina. 

System Preferences had already been granted Accessibility access to Archi, however pressing the "." did nothing. So I deleted the "Archi" entry in Accessibility Preferences re-started Archi. Pressed the "." again and re-granted access and now it works again.

**Comment by normenmueller** [comment]
@Phillipus Lucky you. I followed your advice, removed Archi, restarted Archi, pressed ".", re-granted access, back to Archi... nothing.... re-started Archi... still :-(

I have a fresh installation of mac OS Big Sure 11.2.3. 

Glad it's working for you...

**Comment by Phillipus** [comment]
I assume the "Archi" entry in System Preferences is ticked? If it is and it still doesn't work then I don't know what else to suggest.

**Comment by normenmueller** [comment]
Unfortunately for me it is ticked. 

I tested  on two Macs. Both have Big Sure 11.2.3 installed. It does not work on either. The behavior on the first "."-click is also the same on both. Too bad.

**Comment by Phillipus** [comment]
Sorry I don't know what to suggest. I tried it on Catalina, Big Sur and also Sierra and it works on these. Perhaps a difference in macOS configuration? Perhaps something to do with locale or language keyboard settings (mine set to UK GB).

**Comment by normenmueller** [comment]
What a bummer though. I have set keyboard to german, english us, english uk and, in all cases, extended... no success. No idea what the problem is. I'm sure it's some setting, but I currently have a completely "fresh" Mac, where I haven't made any specific settings yet. Well, should I come to a conclusion, I will post it here. Thanks for your help.

**Comment by Phillipus** [comment]
I'll close this as it's out of my control.
