### ISSUE TITLE
Ability to use archimate view properties when referenced in other views

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#727]
It is a good feature to have ability to reference views in each other.
But somtimes there are cases, when, for example, there bp a need to use a full or detailed view description for a view element on a diagram (instead of using a view name from a model tree, which can be shortened and etc.).

All views are provided with properties, which can be edited from the model tree, or when editing a view itself:
![image](https://user-images.githubusercontent.com/14212283/116465217-5def9b00-a886-11eb-97d0-9d410437c52b.png)

But they are not accessible from the view element, when it is placed on the other view diagram:
![image](https://user-images.githubusercontent.com/14212283/116465309-7cee2d00-a886-11eb-95de-43e0ce0ad4cf.png)

**Comment by Phillipus** [comment]
Please note that a View Reference node is a _visual shortcut_ to the View itself. Therefore it is a visual node for which you can edit the visual aspects relating to the node - Appearance and Label (editing the name was a simple easy thing to do). The Documentation, Viewpoint, and Properties relate to the View itself and can be edited there.

**Comment by Claus72** [comment]
That's exactly the point: is a visual shortcut from which you cannot access the properties of the view itself.
The initial poster and myself believe that it would be an useful feature being able to do so. In my specific case: I'm an old dog and IDEF0 practitioner and supporter of its presentation standard, and wish to simplify the deliverables preparation process having all the diagrams and cross references right from Archi and export them just for formatting purposes, this slight limitation adds an additional step

**Comment by startsevsa** [comment]
>  The Name, Documentation, Viewpoint, Connection Router type, **and Properties relate to the View itself and can be edited there**.

But the properties doesn't work (and in addition properties tab doesn't appear in Properties window when you select a visual shortcut on a view.

Proof is here:

![image](https://user-images.githubusercontent.com/14212283/184189939-f4c2e83d-90fa-42ea-93d0-70bfc191f136.png)

![image](https://user-images.githubusercontent.com/14212283/184190135-aa6f31d0-db5c-453c-941f-5229fbe68a3f.png)

**Comment by Phillipus** [comment]
This will be implemented in the next version of Archi.

**Comment by Phillipus** [comment]
This is in Archi 4.10

**Comment by Claus72** [comment]
Wonderful!!
