### ISSUE TITLE
Conditional formulas in label expressions

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#728]
This will be a got addition to label expression language to have an ability for using IF and CASE analogs (like in Excel & etc).

Example of using:
you have a property, which can bet set or not (is optional)
And when using an element with this option in a view, you want to show in in brackets, but when the value of property is empty, you want to hide the empty value itself and the brackets too.
![image](https://user-images.githubusercontent.com/14212283/116467139-cb9cc680-a888-11eb-85ab-eed1e91c7218.png)

With conditional formula this can be done, for example smth. like this:
`${if(${property:optional property}='';'';'('+${property:optional property}+')')}`

**Comment by Phillipus** [comment]
We want to avoid over-complicating label expressions as they can slow things down when rendering. I think this is out of scope.

**Comment by Phillipus** [comment]
I'm going to close this one because it just ain't gonna happen.
