### ISSUE TITLE
theming on linux

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#730]
### Version of Archi
4.8.1

### Archi Plug-ins
no

### Operating System
Linux 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux, X11, KDE, standard Breeze Dark UI theme in ubuntu.

### Expected Behaviour
Theming should change interface colours and in general they should be readable. 

### Actual Behaviour
Regardless of the theme selected colours don't change much and are pretty unreadable e.g. all lines and connectors in Palette window. Weirdly dark theme changes main window background to light. It is almost the same on windows 10, only in reverse: even though the dark system UI is selected in windows, in Archi 's system theme everything is blinding white. Not cool, but at least readable.
![Screenshot_20210506_101100](https://user-images.githubusercontent.com/11752339/117259416-adb9fd80-ae56-11eb-8c1f-ec3c6b70d3aa.png)
![Screenshot_20210506_101118](https://user-images.githubusercontent.com/11752339/117259423-ae529400-ae56-11eb-93ed-93664ff747ee.png)
![Screenshot_20210506_101134](https://user-images.githubusercontent.com/11752339/117259424-aeeb2a80-ae56-11eb-954b-55a2d4a7583b.png)
![Screenshot_20210506_101202](https://user-images.githubusercontent.com/11752339/117259427-aeeb2a80-ae56-11eb-90ae-b3ac1a49e7c2.png)
![Screenshot_20210506_101212](https://user-images.githubusercontent.com/11752339/117259428-af83c100-ae56-11eb-9c26-89de00229c74.png)

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Themes are controlled by the Eclipse Theming Engine. The themes that ship with Archi are slightly modified Eclipse themes (these can actually be edited as CSS files, if required).

> Regardless of the theme selected colours don't change much and are pretty unreadable e.g. all lines and connectors in Palette window.

I have no control over how a system theme affects the Palette. I've spent several days trying to hack this to control theming in the Palette, but it's not possible.

> Weirdly dark theme changes main window background to light.

By design. If the background was black you would not see any connections.

> It is almost the same on windows 10, only in reverse: even though the dark system UI is selected in windows, in Archi 's system theme everything is blinding white. Not cool, but at least readable.

If you want dark theme on Windows, then select the dark theme in Archi.

As I said, this is all handled by the Eclipse Theme Engine. Compare Archi with the Eclipse IDE if you like.

**Comment by Phillipus** [comment]
I've looked at this issue some more:

- I can fix the background changing to a dark color when in full screen mode. See #729 
- I can fix the background changing to a dark color when the OS theme is dark (should be a white background in all cases)

But there are some issues I can't solve:

- I have no control over the Palette's background color
- I can't change the color of the connections icons in the Palette depending on the Archi or OS theme

If the OS theme is set to dark, then set Archi's theme to dark as well. This is not perfect but better in some cases.

**Comment by Phillipus** [comment]
> I have no control over the Palette's background color

Now that we have forked our own versions of Eclipse GEF/Draw2d I have hooked into where the palette background is set and exposed it in the Theme files. It will be white regardless of the OS theme (slightly less white in Archi's Dark theme).
