### ISSUE TITLE
Transparent background when copy as image a view

### ISSUE THREAD

**Issue by rvelter** [archimatetool/archi#731]
Hi,

Is it possible to have a transparent background when we copy as image a view ?
(shift+ctrl+c).

Many thanks and hava a nice day :)

**Comment by Phillipus** [comment]
Looking at how the Eclipse Graphical framework handles layers I don't think this is possible, or if it is, not easy to solve.

**Comment by Phillipus** [comment]
I'll close this one. I'll re-open it if we find a way to do this.

**Comment by Phillipus** [comment]
Just a quick note for reference on this one.

I nearly got it working on Windows, but not when copying image to clipboard and Mac had some issues. Close but no cigar. See https://github.com/eclipse-platform/eclipse.platform.swt/issues/561 for why.
