### ISSUE TITLE
Cannot open Archi due to log error

### ISSUE THREAD

**Issue by yanntse** [archimatetool/archi#733]
I opened Archi and have been using it for the past week, however, I quit the app completely yesterday and today I cannot open it anymore as it says: log error <user>/Library/Application Support/Archi4/.metadata/.log

I read the "READ me" file but don't understand it... Does anyone know how to proceed?

Thanks in advance!

**Comment by Phillipus** [comment]
I assume your using Archi 4.8.1 on Mac.

You should try deleting the `Library/Application Support/Archi4/.config` folder and re-starting Archi.

See here - https://forum.archimatetool.com/index.php?topic=1018.0

**Comment by yanntse** [comment]
This is what is suggested: An error message concerning a missing class is written to the .log file at startup. This file is located at "<user>/Library/Application Support/Archi4/.metadata/.log".
  To stop this message being written to the log, select "Help -> Reset Archi to Defaults...", then "Reset User Interface".

However, I don't find the help button anywhere

**Comment by Phillipus** [comment]
> This is what is suggested: An error message concerning a missing class is written to the .log file at startup. This file is located at "/Library/Application Support/Archi4/.metadata/.log".
> To stop this message being written to the log, select "Help -> Reset Archi to Defaults...", then "Reset User Interface".
> 
> However, I don't find the help button anywhere

No, that is not suggested for the issue you are seeing. Nor is there a "help button".

Read what I said here:

I assume your using Archi 4.8.1 on Mac. You didn't prove any useful information as requested in the issue template regarding OS, Archi version, plug-ins installed, etc.

You should try deleting the Library/Application Support/Archi4/.config folder and re-starting Archi.

See here - https://forum.archimatetool.com/index.php?topic=1018.0

**Comment by yanntse** [comment]
<img width="477" alt="Screenshot 2021-05-20 at 22 54 58" src="https://user-images.githubusercontent.com/84543487/119047685-8880cf80-b9be-11eb-9e42-c42c745fa327.png">

Yes, I am indeed using version 4.8.1. However, I cannot find the file as you can see on the pic

**Comment by yanntse** [comment]
All good now. You can't imagine how much I appreciate your help! Thanks so much!!

**Comment by Phillipus** [comment]
> All good now. You can't imagine how much I appreciate your help! Thanks so much!!

Good. I'll close this now...
