### ISSUE TITLE
Undoing connection deletion messes its routing

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#734]
### Version of Archi
4.8.1

### Archi Plug-ins
no

### Operating System
windows 10

### Steps to Reproduce the Behaviour
prerequisites: manual connection router

1.    Create two application components.
2.    Create two flow connections between them: one A to B, another one B to A. Archi automatically angles the second connection for better visibility - so far so good.
![archi-undo-bug-1](https://user-images.githubusercontent.com/11752339/119866758-d436fa00-bf25-11eb-9772-ec66772440a8.png)
3.    Delete straight connection, angled connection remains angled.
![archi-undo-bug-2](https://user-images.githubusercontent.com/11752339/119866760-d4cf9080-bf25-11eb-88f7-7dba9ad7c6a6.png)
4.    Undo connection deletion.

### Actual Behaviour
Deleted connection is restored as angled and merges with the second connection.
![archi-undo-bug-3](https://user-images.githubusercontent.com/11752339/119866762-d5682700-bf25-11eb-99db-66000d1cd150.png)

### Expected Behaviour
 Two issues here: first, undo should restore things exactly as they were and definitely shouldn't make diagram unreadable. Second, it may be a good idea to straighten the angled connection after step 3 because it was automatically angled so it won't merge with the connection we just deleted.

**Comment by Phillipus** [comment]
This is a glitch in the Eclipse GEF/Draw2d frameworks and has always been like this. Unfortunately, this is not something I can fix.

A workaround is to move one of the objects and move it back again, or move the connections so they are like this:

![image](https://user-images.githubusercontent.com/600504/119867664-0b9daa80-bf16-11eb-9472-e9fac617d517.png)

**Comment by Phillipus** [comment]
I'll close this as it's not something I can fix. If anyone cares to look deep into the Eclipse/GEF code to try to fix, please do.
