### ISSUE TITLE
[feature request] Add a "Delete All" function for unused elements and relations

### ISSUE THREAD

**Issue by vbo75** [archimatetool/archi#735]
Hi, 
Modeling generates many unused elements and relations.
Deleting one by one is a waste of time.
Is it possible to add a "Delete All" function for unused elements and relations of a model ?
Thanks a lot.

**Comment by sonear** [comment]
I use the following process

1. Validate model
2. Select the first item to be deleted in the validate results
3. Scroll to Bottom of list of elements or relations you want deleted the hold down shift and click on the item... Or control click a set of more than one items
4. Right click on your highlighted set and select 'reveal'. This highlights all of the elements/relations in the model tree. If you have a large model you won't see them all highlighted... Know that they are
5. Over in the model tree, right click on one of the highlighted items
6. Choose delete
7. Now validate model again... The previously selected items should now be gone.

Note... This was all written from memory. Also note I use Mac version of archi. Instructions should be directionally correct.

Hope this is what you are looking for.

Scott Griffith

**Comment by Phillipus** [comment]
As this is answered, I'll close it.
