### ISSUE TITLE
Corrupt Model

### ISSUE THREAD

**Issue by RamsayCE** [archimatetool/archi#738]
### Version of Archi
4.7, but the problem persists to 4.8

### Archi Plug-ins
No

### Operating System
Mac OSX 11.2.3

### Expected Behaviour
The model should open

### Actual Behaviour
The error below is shown:

cannot open **_pathname_** this model is incompatible
content is not allowed in the prolog

### Steps to Reproduce the Behaviour
1. Double click on the .archimate file OR
2. Try to open from inside Archi
3.

**Comment by Phillipus** [comment]
The error message suggests that the contents of the file are not in the correct format. Has this file been opened in Archi successfully before now?

(This is impossible to diagnose without access to the problematic model.)

**Comment by RamsayCE** [comment]
Hi Phil,

Yes, I was working on the model yesterday afternoon.
The backup seems to open fine…
Do you want me to send over the model

Thanks in advance

Ramsay

From: Phil Beauvoir ***@***.***>
Reply to: archimatetool/archi ***@***.***>
Date: Friday, 11 June 2021 at 13:43
To: archimatetool/archi ***@***.***>
Cc: Ramsay Brand ***@***.***>, Author ***@***.***>
Subject: Re: [archimatetool/archi] Corrupt Model (#738)


The error message suggests that the contents of the file are not in the correct format. Has this file been opened in Archi successfully before now?

(This is impossible to diagnose without access to the problematic model.)

**Comment by Phillipus** [comment]
Hi Ramsay, yes please send to info (at) archimatetool.com

**Comment by Phillipus** [comment]
I'll close this as we continued this off-line.
