### ISSUE TITLE
Folder label change objects's name

### ISSUE THREAD

**Issue by kolpitor** [archimatetool/archi#739]
### Version of Archi

4.8.1

### Archi Plug-ins

Jarchi and coArchi

### Operating System

Windows 10 enterprise version 1909

### Expected Behaviour

Change the folder's label should change the displayed name of the folder and shouldn't modifie the objects on it.

### Actual Behaviour

Change the folder's label don't change the displayed name of the folder but modifie the displayed name of the objects on it.

### Steps to Reproduce the Behaviour
1. Select a folder
2. Change the label expression

**Comment by Phillipus** [comment]
Please see https://github.com/archimatetool/archi/issues/723

**Comment by kolpitor** [comment]
Oh sorry for the inconvenience, i didn't saw the issue ^^'

Thank for your answer.

Have a good day.

**Comment by Phillipus** [comment]
No problem. I'll close this one.
