### ISSUE TITLE
Developping a Data Dictionary Plugin

### ISSUE THREAD

**Issue by micwic** [archimatetool/archi#743]
Hello, I would like to inform you we are starting the development a new Data Dictionary Plugin.
You will find design and features in the attached document.
Any comments is welcomed.
Depending on result after the first release we will offer the plugin to the community.
[Plugin development for archimatetool.com.docx](https://github.com/archimatetool/archi/files/6731546/Plugin.development.for.archimatetool.com.docx)
Best regards, Michel

**Comment by Phillipus** [comment]
Hi Michel, thanks for the information, that looks very interesting. Will you be hosting it on GitHub?

It would be better, though, to continue this discussion either on the Archi forum, or your own discussion space, as this is really for Archi issue/bug tracking.

So I'll close this issue and continue elsewhere...

Cheers, Phil

**Comment by micwic** [comment]
Hello Phil, We will host the source in GitHub and let you know the project as soon it is created.
Regards, Michel

***@***.***D76CD0.535696E0]
Michel Wicky
Administrateur
Senior Consultant

Mobile: +41 79 414 94 44
Email: ***@***.***

Ruelle de Chaucey 2
CH-1807 Blonay


[Titre : LinkedIn - Description : image of LinkedIn icon]<http://www.linkedin.com/in/michelwicky>



De : Phil Beauvoir ***@***.***>
Envoyé : mardi, 29 juin 2021 10:01
À : archimatetool/archi ***@***.***>
Cc : Michel Wicky ***@***.***>; Author ***@***.***>
Objet : Re: [archimatetool/archi] Developping a Data Dictionary Plugin (#743)


Hi Michel, thanks for the information, that looks very interesting. Will you be hosting it on GitHub?

It would be better, though, to continue this discussion either on the Archi forum, or your own discussion space, as this is really for Archi issue/bug tracking.

So I'll close this issue and continue elsewhere...

Cheers, Phil

**Comment by jbsarrodie** [comment]
@micwic As said by Phil you should post this to the forum so that more people can react. In the meantime I have some remarks:
- Code can be hosted under archi-contribs GitHub Organization for more visibility if you want.
- Reading your doc, I'm not sure to understand what you call a data dictionnary as you don't seem to target documentation field of Business/Data Object while this is certainly the most straightforward approach.

**Comment by micwic** [comment]
@jbsarrodie seem to me that archi-contribs is managed by @Phillipus  and @jbsarrodie. Can you create a repository so we can start working into.

**Comment by Phillipus** [comment]
> @jbsarrodie seem to me that archi-contribs is managed by @Phillipus and @jbsarrodie. Can you create a repository so we can start working into.

Yes, what name  for the repo would you like?

**Comment by micwic** [comment]
@jbsarrodie Reading your doc, I'm not sure to understand what you call a data dictionnary as you don't seem to target documentation field of Business/Data Object while this is certainly the most straightforward approach.

I disagree with this statement. The structure of the data dictionary will not be managed easily in Business/Data Object documentation because the definitions will be scattered. The data definitions are not limited to Business/Data Object but also Data Flow or even Trigger (even Business/Data Object may be associated with). This the reason we implement an embedded graph database. That said, the relevant parts for the element will be also translated in a textual way in the properties of the element.

**Comment by micwic** [comment]
@jbsarrodie data-dictionary-plugin seem good to me.

**Comment by Phillipus** [comment]
> @jbsarrodie data-dictionary-plugin seem good to me.

It's created. You need to respond to the invite that was sent by GH by email.

**Comment by micwic** [comment]
@jbsarrodie can you also invite matrix.nad@gmail.com that is the developer. Thks.

**Comment by Phillipus** [comment]
> @jbsarrodie can you also invite [matrix.nad@gmail.com](mailto:matrix.nad@gmail.com) that is the developer. Thks.

(I'm not @jbsarrodie )  as you have admin rights you can do this from Settings -> Manage Access.

**Comment by micwic** [comment]
@Phillipus Thks Phil. Everything is ok.
