### ISSUE TITLE
No nesting relationship is created when pasting

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#745]
### Version of Archi
4.8.1

### Archi Plug-ins
none

### Operating System
windows 10-64

### Expected Behaviour
when an element is pasted inside another element a nesting relationship should be created and Archi should prompt for relationship type - like when it is dragged and dropped

### Actual Behaviour
when an element is pasted into another element a nesting relationship is not created and there is no prompt

### Steps to Reproduce the Behaviour
1. create two independent application components
2. select one and cut it to clipboard (^x)
3. right-click inside another application component and select paste from the context menu

**Comment by Phillipus** [comment]
This would become extremely complicated if several elements were copied and pasted. Doubtful this will be implemented, unless the Copy/Paste code has a big overhaul.

**Comment by lvmm** [comment]
Actually it is already complicated when multiple elements are being dragged and dropped: if they are dropped in such a way that only one is nested Archi will create nesting relationship for the whole bunch anyway and make those elements that didn't fit invisible. Personally I find it very confusing.

**Comment by Phillipus** [comment]
> Actually it is already complicated when multiple elements are being dragged and dropped: if they are dropped in such a way that only one is nested Archi will create nesting relationship for the whole bunch anyway and make those elements that didn't fit invisible. Personally I find it very confusing.

That's how it works with DnD. The target element is where the mouse is at the drop point. Whatever elements are being dragged is what is assumed to be candidates for nesting. But feel free to contribute a patch if you can find a better way to do it.

**Comment by Phillipus** [comment]
I'll close this for now because elements are not pasted inside of other elements and so nesting is not an option. If we change how copy/paste works then we'll take a look at it.
