### ISSUE TITLE
Error when running mvn clean package -P product

### ISSUE THREAD

**Issue by LucasMic1** [archimatetool/archi#749]
### Version of Archi
<4.8.0>

### Operating System
<Windows 10>

### Actual Behaviour
<Hello, I am currently trying to build the Binaries with the github tutorial but I have an error that I can't solve when I run the command mvn clean package -P product.

Here is the error:

[ERROR] Cannot resolve project dependencies:

[ERROR]   Software being installed: com.archimatetool.canvas 4.8.0.qualifier

[ERROR]   Missing requirement: com.archimatetool.canvas 4.8.0.qualifier requires 'osgi.bundle; org.eclipse.core.runtime 0.0.0' but it could not be found

[ERROR]

[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.

[ERROR] Cannot resolve dependencies of MavenProject: com.archimatetool:com.archimatetool.canvas:4.8.0-SNAPSHOT @ C:\Users\E023914\Documents\archi-release_4.8.0\com.archimatetool.canvas\.polyglot..META-INF_MANIFEST.MF: See log for details -> [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException`

### Steps to Reproduce the Behaviour
[https://github.com/archimatetool/archi/wiki/Building-the-Binaries](url)

**Comment by Phillipus** [comment]
Do you have the latest `master` branch checked out of GitHub. Seems that you don't.
