### ISSUE TITLE
incomplete alternative shape support

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#751]
Archimate specification usually provides two alternative element shapes. Archi supports some, but not all of them e.g. for Technology elements one can use both shapes for Node or Device (accessible on the Figure tab) but for System Software or Communication Network there is no Figure tab and only one shape is available although two are specified in https://pubs.opengroup.org/architecture/archimate3-doc/chap10.html#_Toc10045428

### Version of Archi
4.8.1

### Archi Plug-ins
none

### Operating System
windows 10

**Comment by Phillipus** [comment]
There will be more in Archi 4.9.

**Comment by Phillipus** [comment]
Close this as they will be in Archi 4.9.
