### ISSUE TITLE
Profile reference corruption in 4.9.0

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#753]
### Version of Archi
4.9.0

### Archi Plug-ins
Yes - jArchi, Lightbox, Excel, 
installed but not used - coArchi

### Operating System
Windows

### Expected Behaviour
Attempt to save a model after normal editing 

### Actual Behaviour

Twice now, the model has become corrupted and won't save.
```
Profile reference is orphaned: id-xxxxxxxx ....
Profile has wrong concept type: id-xxxxxxxx ....
```
 ..... repeats several times for different id refs. (see image)

### Steps to Reproduce the Behaviour
Has happened twice now but not clear what's causing it.
I am though creating a model by copy-pasting from previous models and using the new stereotype feature to denote the source.
![Archi Bug](https://user-images.githubusercontent.com/33519378/126904177-3f512918-b70b-410d-8fd5-4277caaeff97.PNG)

Cannot investigate the source file further because of the binary format :-(
Any chance it can it be salvaged?

**Comment by jbsarrodie** [comment]
Hi Steven,

>Cannot investigate the source file further because of the binary format :-(

As soon as the model contains some images, the `.archimate` file becomes a zip, so simply rename it to `something.zip`, unzip it and you'll then be able to tweak the model.xml file (that's a file using the native Archi file format), then zip all again to open it in Archi.

But do you see any objection in sharing the file with me (I guess you have my email from a meeting we both joined recently) so that I have a chance to understand what happened ?

**Comment by Phillipus** [comment]
This problem can  occur if you imported another model containing Profile/Specialization information into another model. Model Import for Profile/Specialization is not working in this alpha version.

> Any chance it can it be salvaged?

As I tried to make clear on the download page:

_"Please ensure you back up your data first before testing this version, and please use test data only."_

**Comment by lavenderb** [comment]
Thanks for the tip - I'll try it.
I'll send you the model by DM.

**Comment by lavenderb** [comment]
Though Phil's feedback is most likely what happened.

**Comment by Phillipus** [comment]
> Though Phil's feedback is most likely what happened.

But thanks for testing and feeding back to us! Appreciated.

**Comment by jbsarrodie** [comment]
>Model Import for Profile/Specialization is not working in this alpha version.

I forgot that I use a more recent version. You're right, the published alpha doesn't support model import.

**Comment by lavenderb** [comment]
The difficulty of making something idiot proof - they say - is that idiots are so very ingenious ;-)

**Comment by Phillipus** [comment]
Let's close this issue, assuming that the problem was importing from another model. I'm working on a new beta build which will have an initial version of model import that supports this. If it's a different bug, we can re-open this.
