### ISSUE TITLE
Request. Disable Internet activity from application

### ISSUE THREAD

**Issue by ilyacoos** [archimatetool/archi#754]
Hi!  Thanks for your amazing app.  Unfortunately, we cannot use it within our organisation, because Information Security office found a suspicious activity.  Could it be disabled somehow?

1. Internet requests from the application. Such domains as: www.google-analytics.com (64.233.165.102) , www.archimatetool.com (217.160.0.203), login.live.com (40.126.31.140). And so on - over 40 domains
2. Gets the list of the installed software on the machine
3. Writes to Windows registry: HKEY_CURRENT_USER\Software\Microsoft\RestartManager\Session0000\RegFiles0000
4. Restores suspended threads in the third-party processes
5. Identifies virtualization engine

It will be great to disable the first and get the explanation for others. Thanks in advance

**Comment by Phillipus** [comment]
1. That's probably the internal Help Browser where there's a link to https://www.archimatetool.com and 
2. No it doesn't
3. The installer basically does this:

```
set APP_PATH=%~dp0Archi.exe

reg add "HKCR\.archimate" /t REG_SZ /d "Archi.file" /f
reg add "HKCR\Archi.file" /t REG_SZ /d "Archi Model" /f
reg add "HKCR\Archi.file\DefaultIcon" /t REG_SZ /d "%APP_PATH%,0" /f
reg add "HKCR\Archi.file\shell" /t REG_SZ /d "open" /f
reg add "HKCR\Archi.file\shell\open\command" /t REG_SZ /d "\"%APP_PATH%\" \"%%1\"" /f
```

So you can choose to use the Zip package that doesn't write these keys.

4. No it doesn't
5. Don't know what that means

**Comment by Phillipus** [comment]
I'll close this as there's nothing I can change. BTW - you should try installing Eclipse itself - I'm sure you'll see the same things.
