### ISSUE TITLE
Does the "Drill Down" function supposed to work in the HTML Report?

### ISSUE THREAD

**Issue by greg-hisc** [archimatetool/archi#755]
### Version of Archi
4.8.1

### Archi Plug-ins

Yes

### Operating System

Windows

### Question

Does the "Drill Down" function supposed to work in the HTML Report?

Thanks.

**Comment by Phillipus** [comment]
This is an application-only feature. HTML report has separate functionality to the main app UI.

**Comment by greg-hisc** [comment]
This would be very helpful for internal navigation within the HRML Report. Similarly to using URL links in properties to navigate to outside resources. Can we add this to enhancements list?

**Comment by Phillipus** [comment]
> 
> 
> This would be very helpful for internal navigation within the HRML Report. Similarly to using URL links in properties to navigate to outside resources. Can we add this to enhancements list?

Sure, as long as there's a "we" who will implement it. 😉

**Comment by Phillipus** [comment]
Close this one. If anyone wishes to implement it, please do so.
