### ISSUE TITLE
Command line SVG view export

### ISSUE THREAD

**Issue by mkriachko** [archimatetool/archi#756]
Is it possible to export views from model to vector (SVG) form using com.archimatetool.commandline.app?
The possble ways I see:
- Add an option with view id param to export one view to SVG.
- Add an option to export all model views to folder (like the HTML report) (prefered).

If there is another way to get SVG view representation in the Archi headless mode please let me know.

**Comment by Phillipus** [comment]
No, this has not been implemented. There is also a request for this as part of jArchi. See https://github.com/archimatetool/archi-scripting-plugin/issues/77

**Comment by Phillipus** [comment]
I'm closing this issue for these reasons:

- Exporting a View to SVG will be part of a future version of jArchi after Archi 4.9 is released
- Then it will be possible to call a jArchi script that exports to SVG from the command line
- If we do implement export to image file from the command line it will be a generic command line provider for all image formats

See https://github.com/archimatetool/archi-scripting-plugin/issues/77
