### ISSUE TITLE
[Feature] Option to Import CSVs with ANSI encoding

### ISSUE THREAD

**Issue by LucasSalmen** [archimatetool/archi#758]
### Version of Archi

4.7.1
### Archi Plug-ins

Yes
### Operating System

Windows 10
### Expected Behaviour

It should prompt a box with an option to select the desirable encoding to import a CSV file to Archi (like "ANSI").
### Actual Behaviour

Archi always uses encoding UTF-8 when importing CSVs.
### Why this is important
When working with special characters like "á" or "ã", archi can't recognize due to UTF-8 encoding. This could be an important feature for usage with alphabets like portuguese.

**Comment by Phillipus** [comment]
The whole point of using UTF-8 is to support special characters. If the CSV file is UTF-8 encoded and contains special characters they are imported correctly.

**Comment by LucasSalmen** [comment]
I'm now converting my CSV files to UTF-8 and now it's working. Thank you.
