### ISSUE TITLE
"Extending the Model with a new Relationship" tutorial needs update to include how to set up labels for new relationships

### ISSUE THREAD

**Issue by jmariani** [archimatetool/archi#76]
add:

Update messages.properties @ com.archimatetool.editor.ui with new labels for your relationship
Update Messages.java @ com.archimatetool.editor.ui with new static strings to hold the labels
Update ArchimateLabelProvider.java @ com.archimatetool.editor.ui to add the new labels
You will need to update getRelationshipSentence and getRelationshipPhrase methods

**Comment by Phillipus** [comment]
Closing this as that tutorial is out of date now.
