### ISSUE TITLE
Incorrect work with nested group element if I choice specialization relationship. 

### ISSUE THREAD

**Issue by margolyesh** [archimatetool/archi#762]
### Version of Archi

4.8.1, 4.9 ea5

### Archi Plug-ins

All

### Operating System

Win 10

### Expected Behaviour

After linking a group element to another element with a specialization relation (I tried node, device, application component) if I move the element inside the group again, the dialog box for linking the element and the group appears, as if there is no link. With other relationship types it works correctly.

### Actual Behaviour

I expect that working with the specialization relation will be the same as, for example, with composition or aggregation relationship.

### Steps to Reproduce the Behaviour
a) Add a group element to the view.
b) Add a node element to the view.
c) Move the node element to the group element.
d) Select a specialization relation in the dialog box that appears.
e) Move the node element out of the group.
f) Make sure that there is a specialization relation between the group and the node.
g) Repeat steps c, d, e.
h) Verify that the specialization relationship has increased by one.
f) Repeat steps c, d, e, g, h.

**Comment by Phillipus** [comment]
Thanks for reporting this. Specialization is a special case, so this needs looking at.

**Comment by Phillipus** [comment]
Fixed in next beta version, thanks for the clear report.
