### ISSUE TITLE
Specializations: Custom figure

### ISSUE THREAD

**Issue by ArchiRepo** [archimatetool/archi#765]
When creating a specialisation it would be useful to be able to render a custom figure when it is used on a diagram.
This would help the viewer recognise that this is a specialisation of the base Archimate concept that is being used.
The icon is good but if we could also substitute the figure itself that would be better.
Here is an example where I coded a custom distro with this feature (It was a lot of fuss and not a long term solution)
![image](https://user-images.githubusercontent.com/30729678/135314850-faf743ad-a6d4-4f7f-bece-bdcec9953f2b.png)

**Comment by Phillipus** [comment]
In a future version of Archi we plan to have more figure shapes to choose from. As these have to be implemented as `Draw2d` figures they have to be in-built shapes, not user designed.

**Comment by jbsarrodie** [comment]
> This would help the viewer recognise that this is a specialisation of the base Archimate concept that is being used.

Not sure to understand how a custom figure would help someone better than using the exact same base figure but with a custom icon.

> The icon is good but if we could also substitute the figure itself that would be better.

Depends on what "better" means ;-) For me, using custom figures means that users have to learn a whole new visual language so we loose the main value of ArchiMate and there must be a really strong value somewhere else to compensate (and I've hardly seen such value).

BTW, the custom image/icon can be of any size, so it is possible to use big icons and set the background and border of a figure to transparent. That's already covering lots of use-cases.

**Comment by Phillipus** [comment]
I'll close this one for the reasons above,

**Comment by jbsarrodie** [comment]
A last comment on this.

>In a future version of Archi we plan to have more figure shapes to choose from. 

Of course yes. For those interested, this is partly explained in [this old wiki page](https://github.com/archimatetool/archi/wiki/Ideas-for-a-nice-and-elegant-way-to-implement-profiles-and-concepts-customization#figure-customization)
