### ISSUE TITLE
When moving mouse from last right document tab to the nearest at the left - the last doc tab dissapears

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#767]
### Version of Archi
4.9. Beta 2

### Archi Plug-ins
coArchi, jArchi, 

### Operating System
Windows 10

### Expected Behaviour
Highlighting and showing tool-tips when moving mouse over the documents tabs.

### Actual Behaviour
When moving mouse from last right document tab to the nearest at the left - the last doc tab dissapears:

### Steps to Reproduce the Behaviour
1. Move mouse to the last doc tab at the right
![image](https://user-images.githubusercontent.com/14212283/135333840-5d435d94-4f9c-4b94-a3c4-fb32c34d6155.png)

2. Move mouse to the nearest tab at the left of the last right tab
![image](https://user-images.githubusercontent.com/14212283/135333874-09ee9895-b789-424b-aec8-c1ed0f96b086.png)

**Comment by Phillipus** [comment]
Yes, this is an Eclipse bug that only affects the "Classic" and "Basic" themes:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=575873

We have to wait for Eclipse 4.22 to be released for the fix.

Workaround is to move the move around until it appears. Or use a different theme.
