### ISSUE TITLE
Allow multi-line names for objects

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#77]
At the moment, all name attributes for an object are single-line. The name attribute is saved as a single line in the model, and the text editing components are single line. 

Allow multi-line names, like the "Documentation" field.

**Comment by tuxwielder** [comment]
Wouldn't it make more sense to allow users to choose which properties to display within elements?

For example you could define a property "Pattern type" and display it's contents by setting a template:

[{Archi_name}]
<<{Pattern type}>>
({Archi_Element_type})

The first and last line would be using "built in" types. The default template would then just be:

{Archi_name}

This would not overload the name for something it isn't and still have the benefits that we seek...

**Comment by misterbotha** [comment]
Disappointing to see this issue open for so long - surely this cannot be a difficult thing to do?

We are trying to adopt Archimate as a modelling language in our organisation, but our business stakeholders aren't impressed by some of the silly constraints in the models.

How do we expedite this improvement?

**Comment by Phillipus** [comment]
> Disappointing to see this issue open for so long - surely this cannot be a difficult thing to do?

How do you know it's not difficult? Sometimes a feature has deep dependencies.

> We are trying to adopt Archimate as a modelling language in our organisation, but our business stakeholders aren't impressed by some of the silly constraints in the models.

Then perhaps this is not the right tool for you. Suggest you look at alternatives.

> How do we expedite this improvement?

As this is open source, you can contribute the code, or perhaps consider contributing financially toward the execution of this feature.

**Comment by misterbotha** [comment]
Thanks.. I'll take a look.  We are already compiling the business case for other alternatives.

**Comment by herve91** [comment]
Hi,

I just updated my [specialization plugin](https://github.com/archi-contribs/specialization-plugin) to do it (the plugin allows to separate the concept labels from their names).

I added this morning the 2 following updates:
* Replace the "\n" string by a new line
* Expand variables ${name}, ${id}, ${property:xxxxx}, ... the same way my [form plugin](https://github.com/archi-contribs/form-plugin) does

![replacing labels](https://user-images.githubusercontent.com/9281982/34665993-8e5fe87a-f462-11e7-91bb-a48f15472843.png)

Hope this helps
Best regards
Hervé

**Comment by atownley** [comment]
That's awesome, Hevé!  I'm trying to prototype/explore some things, and this functionality was preventing me showing stereotypes the way I wanted.  The fact that it works based on variables is super slick.  You saved my day!  THANKS!

**Comment by herve91** [comment]
you're welcome :)
