### ISSUE TITLE
Impossible to Open a view

### ISSUE THREAD

**Issue by jmonsel** [archimatetool/archi#770]
### Version of Archi

4.9 Beta 3
Build 202110041231

### Archi Plug-ins

CoArchi 0.7.1
JArchi 1.1.1
Icon Plugin 2.0.0 alpha2
Lightbox 1.1.1

### Operating System

Windows 10 entreprise
Version 10.0.19043

### Expected Behaviour

I try to open Archi and open a view. I shoudl have, at least, a perspective with the panel view displaying the view I selected 

### Actual Behaviour

Opening Archi, GUI is weird, especially the panel opening view is empty. Even if I click to open a view nothing happen except a new tab appears but without any content.
After some other attempt I finally code a wonderful message : "An error has occurred. See error log for more details.
java.lang.NullPointerException"

### Steps to Reproduce the Behaviour
1. Open Archi
2. Select and double clic a view to Open it
3.
<img width="923" alt="Capture" src="https://user-images.githubusercontent.com/14196829/136536136-dba35ade-de85-4989-8175-b37b5c3b5767.PNG">

**Comment by jbsarrodie** [comment]
Hi, what is the "icon plugin" you mentioned? Please check with no plugins at all and then with ony official plugins provided by Phil and I (coArchi, jArchi, Excel and Lightbox).

**Comment by Phillipus** [comment]
This will be because you have Herve's Specialization plug-in installed. This is not compatible with Archi 4.9.0

See https://github.com/archi-contribs/specialization-plugin/issues/54

**Comment by Phillipus** [comment]
I'll close this one.
