### ISSUE TITLE
[ISSUE] Default-Size button not working as expected ?

### ISSUE THREAD

**Issue by ProximaBay** [archimatetool/archi#771]
### Version of Archi

4.9.0

### Archi Plug-ins

Not Relevant for this issue (IMHO :-)

### Operating System

Windows 10

### Expected Behaviour

When changing the default size of an element on a view (changing its default width and/or its default height), the [Default Size] button in the toolbar (which is greyed-out by default) should become active/available to the user, to "reset" element's dimensions to default.

### Actual Behaviour

Actually, the [Default Size] button in the toolbar only become active when you change the element's default height. If you manage to change only its default width, the button keeps grayed-out and is not made active/available to the user.

### Steps to Reproduce the Behaviour
1. Place an element on a view
2. Change the element's default width
3. Try to restore the element's default dimensions (height and width) by clicking the [Default Size] button
4. That's all :-)

**Comment by Phillipus** [comment]
Hi, I can't reproduce this. 

What element are you using? 

> Change the element's default width

Do you mean by resizing it?
