### ISSUE TITLE
Archi 4.9 and DataBase export plugin

### ISSUE THREAD

**Issue by sportingdurutti** [archimatetool/archi#775]
### Version of Archi
4.9

### Archi Plug-ins
org.archicontribs.database_2.2.19
org.archicontribs.modelrepository_0.7.1.202102021056

### Operating System
Windows 11

### Expected Behaviour
Test connection ok. Save and start exporting

### Actual Behaviour
Database export plugging giver error while initializing. Test Connection is ok when closing windows give null reference

### Steps to Reproduce the Behaviour
1. Choose an existing connection (eg: neo4j)
2. Save 
3. Select connection and stat exporting

**Comment by jbsarrodie** [comment]
The database plugin is not maintained by us (Phil and me) but by Herve. To my knowledge, Herve's plugins are still not updated to work with Archi 4.9, but you can open an issue on its plugin page: https://github.com/archi-contribs/database-plugin/issues
