### ISSUE TITLE
Cursor size on multi-monitor setup when creating relationships

### ISSUE THREAD

**Issue by steverumsby** [archimatetool/archi#779]
### Version of Archi

4.9.1

### Operating System

Windows 10

### Actual Behaviour

I have an MS Surface with two external 1080p monitors (22", so much lower dpi than the Surface monitor). On the Surface display everything appears to be fine.

When the archi window is on one of the external monitors, and I try to create a relation between two elements, while dragging the mouse the cursor is way too big.  

This is the appearance on the Surface monitor:
![IMG_20211026_114332150](https://user-images.githubusercontent.com/15650733/138863524-ad47638d-19e9-4091-a906-ecffd127e4fc.jpg)

This is the appearance on the external 1080p monitor (apologies for the dodgy colour balance!):
![IMG_20211026_114354842](https://user-images.githubusercontent.com/15650733/138863637-e54f69e5-0c52-45c4-a65f-4500e2961eb1.jpg)

I haven't noticed this behaviour in any other context. As far as I have noticed, everything else looks correct on the external monitors.

This did not happen with 4.8.1. The cursors were still different on the two screens, but not oversized on the external monitor.

**Comment by Phillipus** [comment]
Let's close this one as there are some options to manage this.
