### ISSUE TITLE
Drill Down feature

### ISSUE THREAD

**Issue by osanimmnt** [archimatetool/archi#782]
The deprecated specialization plug-in had a very helpful DrillDown feature that allow navigate to a view from an object. can this version has that very helpful, nice, valuable feature?

### Version of Archi

4.9.1

### Archi Plug-ins

no

### Operating System

Windows 

### Expected Behaviour

there where a drill down feature where after double click open a view (specialization plug-in)

### Actual Behaviour

nothing.

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
The behaviour of double-clicking an object is to open the Properties window, and that's not going to change. There are View reference objects that you can add to an object.

See https://forum.archimatetool.com/index.php?topic=786.msg4458#msg4458

**Comment by osanimmnt** [comment]
Tthat is nice trick, thanks. 
Just one question, is there any way to configure that just one time and get view-object relationship in all views?
