### ISSUE TITLE
[Feature Request] fixed release location for Arch PKGBUILD

### ISSUE THREAD

**Issue by Thorgrimson** [archimatetool/archi#798]
I would like to maintain archi in the AUR but there is warning about changing release locations. I would be easier to provide the package for Arch users if there is a fixed release location.

**Comment by Phillipus** [comment]
Please download from the downloads page.

**Comment by Thorgrimson** [comment]
Then every user has to do it on its own. I need a link for a script that pulls the release.

**Comment by Phillipus** [comment]
Zero effort leeching is not supported.
