### ISSUE TITLE
Exporting .archimate to .xml (OpenExchange) -> missing properties and documentation for Notes + Groups (view only elements)

### ISSUE THREAD

**Issue by grmatthews** [archimatetool/archi#799]
### Version of Archi

v4.8

### Archi Plug-ins

No

### Operating System

Windows

### Expected Behaviour

Exporting a .archimate file to OpenExchange, where there are Group and Note elements in a view, each of which have properties and documentation defined.
Expecting those properties and documentation items to be in the output .xml file

### Actual Behaviour

properties and documentation elements not present in exported .xml (OpenExchange) file

### Steps to Reproduce the Behaviour
1. Create a view in ArchiMate with a Group + Note, and add a property + documentation for each
2. Export to .xml / OpenExchange
3. Inspect .xml file, and notice that the properties and documentation is missing

**Comment by Phillipus** [comment]
There's nothing we can fix here because of the following:

- A Note doesn't have a Documentation field so that can't be exported
- Documentation for a Group is actually exported
- The Exchange Format currently doesn't support Properties on the visual nodes like Groups and Notes

**Comment by Phillipus** [comment]
I'll close this one.
