### ISSUE TITLE
View IDs in XML export does not match HTML export

### ISSUE THREAD

**Issue by decentropy** [archimatetool/archi#801]
### Version of Archi
4.8.1

### Archi Plug-ins
No

### Operating System
Windows

### Expected Behaviour
HTML report view IDs should match view IDs in Open Exchange export

### Actual Behaviour
The html files generated by Archi do not always match what is exported to XML.
Sometimes, the view html file is prefixed "id-" and sometimes it's not... even though in XML the viewRef always starts with "id-"
This makes it impossible to use the XML for reliably extending or processing views (e.g. search, index, or other useful features I am attempting to do).

### Steps to Reproduce the Behaviour
1. Export to Open Exchange File
2. Generate HTML report
3. Compare the view HTML file names against viewRef IDs, and see that some file names cut off the "id-"

**Comment by Phillipus** [comment]
I'm not exactly clear about this, because you mention viewRef IDs. Can you provide a simple example model?

**Comment by Phillipus** [comment]
OK, I think I see what you mean. You might be using an older model where objects didn't have the "id-" prefix.

For the Open Exchange File export legacy IDs cannot start with a number so if it does it is prefixed with "id-"

**Comment by decentropy** [comment]
Yep Phil, that must be it (i.e. - my issue is with old views from prior version).
I can resolve this by scrubbing the .archimate file and prefixing all DiagramObject with "id-", so the HTML matches the XML moving forward

Thanks - closing issue
