### ISSUE TITLE
[feature request] projects

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#802]
Sometimes I work on multiple projects; each project requires its own open files and views. Keeping them all open at the same time clutters the desktop, opening and closing when needed is time-consuming, and it is not possible to open multiple instances of Archi at all. The only workaround I know is to stop Archi, replace workbench.xmi file with a saved copy for another project and start again - not very convenient. Can we have project support? - the ability to save the desktop state such as open files, views, panels and their layouts, etc, and switch between these saved states with minimal effort.

**Comment by Phillipus** [comment]
This is not something that is likely to be implemented.

You could edit the `Archi.ini` file to change the workspace location `osgi.instance.area` and config area `osgi.configuration.area`. You can then have multiple instances open.

See https://github.com/archimatetool/archi/wiki/The-Archi.ini-file
