### ISSUE TITLE
Find function on "Find/Replace" form don't use "Case Sensitive" option with cirillic.

### ISSUE THREAD

**Issue by margolyesh** [archimatetool/archi#804]
### Version of Archi

4.9.2

### Archi Plug-ins

Archi Colloboration 0.8.0.2021110121448
Archi Scripting 1.2.0.2021110121451
Lightbox for Archi 1.1.1.20210807

### Operating System

Win 10

### Expected Behaviour

Find function on "Find/Replace" form don't use "Case Sensitive" option with cirillic.

### Actual Behaviour

Positive scen.
I have two Bussiness Actor elements: "Customer" and "customer".
If "Case Sensitive" options hasn't activate on "Find/Replace" form and I searching "customer" or "Customer" then both element will be find. 
If "Case Sensitive" options has activate on "Find/Replace" form and I searching "customer" or "Customer"  then one element element will be find.

Negative scen.
I have two Bussiness Actor elements: "Клиент" and "клиент".
If "Case Sensitive" options hasn't activate on "Find/Replace" form and I searching "клиент" or "Клиент" then one element element will be find.
If "Case Sensitive" options has activate on "Find/Replace" form and I searching "клиент" or "Клиент"  then one element element will be find.

**Comment by Phillipus** [comment]
Notes for investigation:

[com.archimatetool.editor.ui.findreplace.AbstractFindReplaceProvider](https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor/src/com/archimatetool/editor/ui/findreplace/AbstractFindReplaceProvider.java)

Possible change to regex pattern in method `getSearchStringPattern`:

```
if(!isCaseSensitive()) {
    searchString = "(?i:" + searchString + ")"; 
}
```

**Comment by Phillipus** [comment]
Will be fixed for next version.

**Comment by Phillipus** [comment]
Fixed in next version
