### ISSUE TITLE
Model tree panel goes blank when toolbar is hidden

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#811]
### Version of Archi
4.9.2

### Archi Plug-ins
no

### Operating System
Windows 10

### Expected Behaviour
Model tree panel should always display the tree

### Actual Behaviour
If toolbar is hidden and one clicks on a view name in the Models tree panel, then on its documentation (or any other field in its properties) and then again on the same view name in Models, Models tree disappears.

### Steps to Reproduce the Behaviour
1. hide toolbar if not hidden (window-show tollbar)
2. press ^N to create a new empty model
3. click on 'Default view' in model tree
4. click on Documentation in properties pane
5. click on 'Default view' in model tree again - with the exception of the view name tree pane goes blank (screenshot)

Tested with clean profile. Nothing in error log. This issue occurs only when toolbar is hidden.
![archi-disappearing-pane](https://user-images.githubusercontent.com/11752339/152793368-2bea9758-5a82-4bc5-a5a5-6dfeac0b22f1.png)

**Comment by Phillipus** [comment]
This is a strange bug somewhere in Eclipse.

It happens under these conditions:

1. Windows only
2. Toolbar is hidden
3. A Tree that has drag support
4. With certain themes ("Light" and "Dark")

It can be triggered by putting the focus on a Tree and then putting focus on another part (say, a diagram View) and focussing back and forth.

- If I change the theme to "Basic", "Classic", or "System" it doesn't happen
- If I comment out `registerDragSupport();` in `TreeModelViewerDragDropHandler` it doesn't happen in the Models Tree.

So there's something weird happening here which, unless someone can create a simple stand-alone test case and report it to Eclipse, is unlikely to be fixed.

**Comment by Phillipus** [comment]
I've made a simple test project and reported it to Eclipse:
