### ISSUE TITLE
Feature request: Ability to order relations

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#814]
When graphs get busy, I'd like to place objects next to each other.  Often the lines from the relations get on the way and obscure the names of the objects that usually the most important aspect of the graph.

However, I can not select the lines representing the relationships and order them to go behind the objects (Send to Back). Could this be enabled?

I suppose this might  have been discussed at some point, but in that case I’d be interested in hearing the  justification of leaving this feature out.

**Comment by Phillipus** [comment]
If you're asking for connections to be drawn behind objects, that's not possible due to the way the Eclipse Graphical Eclipse Framework orders objects and connections in different layers. The connection layer is behind the node layer.

See https://github.com/archimatetool/archi/issues/590

**Comment by heikkil** [comment]
That's what I am asking. I see now that it has been discussed and rejected. I disagree since it is always possible draw confusing graphs. The user should have the choice it is deemed necessary.

But fair enough if that is the final word. This ticket can be closed from my part.

**Comment by jbsarrodie** [comment]
> That's what I am asking. I see now that it has been discussed and rejected. I disagree since it is always possible draw confusing graphs. The user should have the choice if that is deemed to be necessary.

Some comment: the graphical framework (eclipse) draws elements and relationships on two different layers, so the only choice we have is either **all** relationships are in front or below **all** elements. Because most of the users want them to be in front of elements, this is how Archi is configured.

**Comment by Phillipus** [comment]
See also: https://forum.archimatetool.com/index.php?topic=37.0

**Comment by Phillipus** [comment]
As a follow up to make this clear: 

Connection layer on top:

![coonections-ontop](https://user-images.githubusercontent.com/600504/221578293-1cd5b740-2f2c-43f5-a298-a663f76d9374.png)

Connection layer below:

![connections_under](https://user-images.githubusercontent.com/600504/221578328-7e4ab768-d40c-4dd1-b66d-0796f8e993b8.png)
