### ISSUE TITLE
Feature request: Numeric sorting of views

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#815]
My main way of keeping track of views of a model is the Models pane where they are located in the Views folder. It is possible to create further subfolder to organise the views, but within a folder they are automatically ordered alphabetically. I influence the order by using numbers in the view names, e.g. 1, 2, 2.1, 2.2, 3,... .  This ordering breaks down when number 10 is added. 

Would it be possible to have an option of having numeric sorting of views?

Of course, I could use numbers with zeros in from, but that looks weird.

**Comment by Phillipus** [comment]
I looked at some Java alphanumeric comparator algorithms and they all seemed overly-complicated.
