### ISSUE TITLE
Feature request: Automatic saving

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#816]
I can not see a use case where I do not want to save what I have drawn. Sometimes I forgot to save, and even worse the application crashes. More often this happens when I work with multiple related by separate models.

I'd like to see an option in the preferences that would automatically start saving models that already have a file associated with them. Saving should happen in some sensible interval without affecting the use of the application.

**Comment by Phillipus** [comment]
I'm not going to implement auto-save, since I can't guarantee safety of models as it could lead to unknown problems (especially jArchi and coArchi are used).

See https://forum.archimatetool.com/index.php?topic=1079.msg5766#msg5766

I'll close this one.
