### ISSUE TITLE
[feature proposal] A PlantUML type DSL for Archi

### ISSUE THREAD

**Issue by timoc** [archimatetool/archi#82]
I use PlantUML (http://plantuml.sourceforge.net/), and i find its DSL a great way to design, update, version and render/share UML with others. It also works well embedded as part of the documentation and as part of the design and build process.

I would like to be able to run a command line plantuml tool that can use an archimate DSL like approach. Archimate should import/export these also.

**Comment by jamespjh** [comment]
+1 for this feature.

**Comment by tooh** [comment]
+1

**Comment by MapBakery** [comment]
+1 although I'm looking for a DSL that just works with the ArchiMate 3.0 Strategy viewpoint elements Resource and Course of Action in combination with the triggering relationship. Or perhaps for me it's even better to build something that transforms PlantUML sequence diagram code into an ArchiMate Model Exchange File (and vice versa).

**Comment by theunsfvo** [comment]
PlantUML plugin would be a great idea to link UML directly in Archmate!

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by jbsarrodie** [comment]
Hi,

FYI, there's already an attempt to extend PlantUML to support ArchiMate: http://plantuml.com/archimate
But this needs more traction to evolve in something really usable.

**Comment by MapBakery** [comment]
Thanks, I heard something about that. But that's too complicated for me and not quite what I'm looking for. After a good night sleep I think that I can make my solution for "a DSL that just works with the ArchiMate 3.0 Strategy viewpoint elements Resource and Course of Action in combination with the triggering relationship" by making a script separate from Archi, That script should take PlantUML sequence diagram code and put that in an Archi .archimate XML or in a an ArchiMate Model Exchange File. An export from an Archi .archimate XML or a an ArchiMate Model Exchange File to PlantUML will be more difficult but not impossible with scripts.

**Comment by theunsfvo** [comment]
And it doesn't have to be full integration with Archimate elements, if you
could just write, generate and save UML diagrams in Archi and maybe allow
the diagrams as viewpoints in other Archi diagrams for reference, that
would already go a LONG way to show more traditional technical lower level
views...

Regards,
Theuns  - "I love deadlines. I like the whooshing sound they make as they
fly by." Douglas Adams
  IQ Business <http://www.iqbusiness.net>: *Solution Architect *| *TOGAF 9
Certified Enterprise Architect *
   My 3D Images <http://bluestarcreations.wordpress.com/> || Some of my
writings <http://www.writingroom.com/writingresults.aspx?m=Zandria> || My
Awesome Stuff Blog <http://awesomestufftheunslikes.wordpress.com/about/>

**Comment by mwherman2000** [comment]
+1

**Comment by timoc** [comment]
There is an XML markup for Archimate - possibly this would be a good starting point?
