### ISSUE TITLE
[feature request] more compact palette

### ISSUE THREAD

**Issue by lvmm** [archimatetool/archi#822]
Space usage in Icons Only layout of Palette can be optimised: horizontal spacing is too wide and there are sizeable unallocated gaps between icons. I sometimes click these gaps by mistake and get annoyed when nothing is selected. Also, when vertical scrollbar is not needed the space for it is still reserved on the right. Is it possible to remove these gaps and make Palette more compact?

**Comment by Phillipus** [comment]
No.
