### ISSUE TITLE
Exception at startup after upgrading to 4.9.2

### ISSUE THREAD

**Issue by micwic** [archimatetool/archi#823]
[archi.error.log](https://github.com/archimatetool/archi/files/8159727/archi.error.log)

### Version of Archi

4.9.2
### Archi Plug-ins

CoArchi

### Operating System

W11
### Expected Behaviour

Error detected at startup, very big latency at usage

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Ensure old version is uninstalled first and try a fresh clean install and delete the `<user>/AppData/Roaming/Archi4/.config` folder. You could also delete the `dropins` folder and re-install plug-ins.

**Comment by micwic** [comment]
Thanks Phil, seem ok after reinstalling the CoArchi plugin. Will close the issue after working a little bit more to check the latency problem is solve also. Regards.

**Comment by Phillipus** [comment]
Please provide steps to reproduce and where the latency is occurring. And what do you mean by "latency"?

**Comment by Phillipus** [comment]
As this has not been reported by anyone else you're going to have to narrow this down even further. Try a clean install with no plug-ins. What version of coArchi is/was working OK?

**Comment by micwic** [comment]
This is confirmed on two completely different installed Archi from the same project git source.
At my side, I reinstalled Archi 4.9.2 after deinstalling it (but I didn't deinstalled the plugins and their configurations).
My colleague didn't have the latency until it updated the CoArchi plugin.
I freshly installed Archi in a new computer (same hardware and W11 OS, no Archi previously installed into) from the same project git source without the latency problem (good news).
I will deinstall everything and reinstall completely from scratch in my computer.

**Comment by Phillipus** [comment]
I'll close this now.
