### ISSUE TITLE
I am not able to open previous version(s) of Archi in the 4.9.2 version

### ISSUE THREAD

**Issue by yravikrishna** [archimatetool/archi#824]
### Version of Archi
4.9.2

### Operating System
Windows 10

### Expected Behaviour
I expect the previous version of *.archimate files to get opened in 4.9.2 without any issues

### Actual Behaviour
It is not opening the previous version files. It doesn't throw any error and does not open the file. 

### Steps to Reproduce the Behaviour
1.  Take any previous version of a file. 
2. Open in 4.9.2
3.

**Comment by Phillipus** [comment]
Please provide _exact_ steps to reproduce and error log. Please attach a file that doesn't open.
