### ISSUE TITLE
Conditional text in label

### ISSUE THREAD

**Issue by mikisvandijk** [archimatetool/archi#827]
Is there any syntax to include a conditional text in a label, depening on a property but not the property itself?

I want to add 'footnote-like" symbols to te label of a relation depending on specific conditions.

I've tried expressions like 

${if:(${property:m_standard}===("HL7"):⑦  }
or
${if:(${property:m_standard}.equals("HL7"):⑦  }

But these won't work. Is there any way to have the desired effect?

Thanks!

**Comment by Phillipus** [comment]
Not on the property value, but whether the property exists:

`${if:${property:m_standard}:⑦}`

**Comment by mikisvandijk** [comment]
Thank you. That's clear.

I'll consider using my properties another way.
Another option could be creating a separate "label_text" property using a jarchi script and using that in thet label expression.
