### ISSUE TITLE
How to put the component title in Bold or Italic ?

### ISSUE THREAD

**Issue by xyz-mtl** [archimatetool/archi#828]

**Comment by Phillipus** [comment]
Fonts for digram objects can be set from the "Appearance" tab in the Properties windows. The font dialog allows setting bold and italic. See the Archi User Guide for more information.

**Comment by xyz-mtl** [comment]
@Phillipus How to put the title in Bold and the description in italic ?

**Comment by jbsarrodie** [comment]
You can't. There's only one single label on each elements and the appearance apply to the whole of it.

**Comment by xyz-mtl** [comment]
Can we consider this suggestion to an enhancement ?

**Comment by Phillipus** [comment]
> Can we consider this suggestion to an enhancement ?

You can, but it won't be implemented. The (single) text box in a figure can only use one font and style. To have multiple fonts would require multiple text boxes.

**Comment by jbsarrodie** [comment]
FWIW, there's a workaround that I use quite often: you add a (transparent) note inside an element and set its label to `$parent{description}'. You can then set the font attributes independently for the element (showing the name) and the note (showing the description).

**Comment by Phillipus** [comment]
> FWIW, there's a workaround that I use quite often: you add a (transparent) note inside an element and set its label to `$parent{description}'. You can then set the font attributes independently for the element (showing the name) and the note (showing the description).

Literally "thinking outside the box". 😉 

I think you meant `$parent{documentation}'`

**Comment by jbsarrodie** [comment]
> I think you meant `$parent{documentation}`

yes (now edited)
