### ISSUE TITLE
[Feature Request] - XML Export - Include "specialization" value as a fixed user defined property when exporting

### ISSUE THREAD

**Issue by gernotfriedrich** [archimatetool/archi#830]
I like the new "Specialization Manager" in Archi 4.9 as it makes life so much easier. So far our team has used a user-defined property "stereotype" to implement the specialization concept of the ArchiMate language but this was error prone as people had to type the correct value, whereas selecting from a predefine list is much better.

However, when exporting the model in XML the values of the new "specialization" attribute in Archi is not exported (same as label expression). Whilst I understand that these values are specific to the Archi tool they would still be very useful for exchanging files in the Open Exchange Format. 

To distinguish these "Archi properties" from other user defined properties I could imagine a special identifier which could be based on the tag URI scheme as defined by RFC 4151. So this would enable the exchange of these useful data elements using the open exchange specification until a future ArchiMate version includes those properties as part of the standard..

----------------------------------
`
 <element identifier="id-f11f19a0bb14481bbb603a83d0df4aab" xsi:type="Capability">
      <name xml:lang="en">My Capability</name>
      <documentation xml:lang="en">lore ipsum</documentation>
      <properties>
        <property propertyDefinitionRef="tag:archimatetool.com,2021-10-12:specialization">
          <value xml:lang="en">CapabilityConfiguration</value>
        </property>
        <property propertyDefinitionRef="tag:archimatetool.com,2020-07-01:labelexpression">
          <value xml:lang="en">«${specialization}»
${name}</value>
        </property>
      </properties>
    </element>
...
<propertyDefinitions>
    <propertyDefinition identifier="tag:archimatetool.com,2021-10-12:specialization" type="string">
      <name>Specialization</name>
    <propertyDefinition identifier="tag:archimatetool.com,2020-07-01:labelexpression" type="string">
      <name>Label Expression</name>
      ...
`

**Comment by Phillipus** [comment]
We will, at some point, be implementing support for ArchiMate Profiles and Stereotypes for the exchange format when that has been published by TOG, so until then we won't be adding any other ways to do it.

**Comment by Phillipus** [comment]
Setting a property for the label expression won't work because label expressions are applied to diagram nodes, not concepts. And the exchange format only allows properties on concepts, not nodes.

**Comment by gernotfriedrich** [comment]
This is fair enough. Is TOG going to update the ArchiMate Model Exchange File Format 3.1 together with the next minor release for the ArchiMate language that is planned for mid-2022?

**Comment by Phillipus** [comment]
I'll close this one and we'll wait for feedback from TOG about changed to the AMEFF.
