### ISSUE TITLE
[Feature request] Brew formula

### ISSUE THREAD

**Issue by gokaygurcan** [archimatetool/archi#831]
Hi,

It'd be nice to have a brew formula/cask, so that we can easily install and update Archi through terminal on macOS (and to some extend on Linux). 

More information can be found here: https://docs.brew.sh/Cask-Cookbook

If I can allocate time, I'd like to help with this. But in any case, I believe this is a valuable addition to the existing tool to distribute it easier.

I hope this makes sense.

Best,
G.

**Comment by Phillipus** [comment]
I'll close this as is not something to change in Archi code.
