### ISSUE TITLE
Ctrl+TAB for walk through view tabs

### ISSUE THREAD

**Issue by smirnoww** [archimatetool/archi#834]
It would be convenient for me to walk through tabs using ctrl+tab and ctrl+shift+tab hotkeys.
Not only for me, I hope.
![image](https://user-images.githubusercontent.com/6284636/163733794-3054b8e3-a6d8-410a-87b9-1913763794fe.png)

Thanks any way for your work

**Comment by Phillipus** [comment]
I'll close this as you already raised this before in #686
