### ISSUE TITLE
Add "Analysis" tab for the elements information panel (along with Properties ans Description tabs) in HTML report  

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#835]
### Version of Archi
4.9.3

### Expected Behaviour
Show tab "Analysis" is HTML report for the selected element.
![image](https://user-images.githubusercontent.com/14212283/165026124-47aba65e-443e-4c7c-b4da-91bce39b6d2b.png)
It will be very helpful for navigating through the model views.
At first a "Used in views" part is mostly needed (each view name must be a link), and, a "Model relations" info would be pleased to be realised too (but no links, cause the is no navigation to a model elements in HTML report).

![image](https://user-images.githubusercontent.com/14212283/165026407-dad38c16-7197-4ea6-a477-c03b017e13ca.png)

**Comment by Phillipus** [comment]
Implemented in #984
