### ISSUE TITLE
Color selector crashes Archi

### ISSUE THREAD

**Issue by hornkim** [archimatetool/archi#836]
### Version of Archi
4.9.3

### Archi Plug-ins
jArchi 1.2
DB Plugin

### Operating System
MAC Big Sur 
V 11.6.4

### Expected Behaviour
Drag a color into palette, the program does not crash

### Actual Behaviour
Drag a color into palette, Archi crashes

### Steps to Reproduce the Behaviour
1. Select object on View
2.Properties Appearance
3. choose fill color
4. choose the round circle color chooser
5. drag the color (bottom left ) to small palette boxes
6. CRASH !!!!!!

**Comment by Phillipus** [comment]
Duplicate of #715. It's a macOS bug.
