### ISSUE TITLE
Add underscores on `_hide_from_export_` in help documentation

### ISSUE THREAD

**Issue by isalew** [archimatetool/archi#838]
In the section on reporting tool documentation, the [Archi User Guide](https://www.archimatetool.com/downloads/Archi%20User%20Guide.pdf) says `hide_from_export`, but should say `_hide_from_export_` with underscores, as documented in the [release version history](https://www.archimatetool.com/version-history/).

The following line of code should be updated:
https://github.com/archimatetool/archi/blob/1f90a1d484392b846c2f0e21dae4bf79971740f4/com.archimatetool.help/help/Text/reporting-html.html#L36

**Comment by Phillipus** [comment]
Thanks for raising this. I've corrected the error now so will close this one.

https://github.com/archimatetool/archi/blob/master/com.archimatetool.help/help/Text/reporting-html.html
