### ISSUE TITLE
Derived relation depend on direction? of association

### ISSUE THREAD

**Issue by rudibelt** [archimatetool/archi#84]
Take the following diagram:
![image](https://cloud.githubusercontent.com/assets/8036286/3442103/ca6d6d42-010e-11e4-80ea-c9910885a694.png)

When association relation is from Application Component to Data Object its not possible to create a derived relation from Application Component to Artifact. If the association is from Data Object to Application Component it is possible to create the derived association relation. If I am correct the association relation has no direction.

**Comment by Phillipus** [comment]
As Derived Relations is not currently implemented I'll close this.
