### ISSUE TITLE
Using the Archimatetool components in Java web applications

### ISSUE THREAD

**Issue by kinjelom** [archimatetool/archi#844]
I want to develop my own Java application that describes my infrastructure using many Archimate projects.
I need some libraries to parse Archimate files and render requested views as SVG.

Are there any ready-to-use pure java libraries, not depended on Eclipse ( https://mvnrepository.com/search?q=archimate )?
Is there any chance of extracting the mentioned functionality from your codebase?

**Comment by Phillipus** [comment]
This was raised before:

https://forum.archimatetool.com/index.php?topic=1054.msg5658#msg5658

So, no, there are no plans to do this as the conversion depends on Eclipse based libraries. It may be possible by developing a plug-in or some other means (directly from the *.archimate file) but not something we will do.
