### ISSUE TITLE
After update to 4.9.3 -> failed to create the part's control

### ISSUE THREAD

**Issue by jeroeneikmans** [archimatetool/archi#845]
### Version of Archi
4.9.3

### Archi Plug-ins
icon plugin

### Operating System
windows

### Expected Behaviour
archimate file should normally open the view

### Actual Behaviour
After updating to 4.9.3., open the view now generates 'Failed to create the part's controls'. 

### Steps to Reproduce the Behaviour
1. Open archimate, open archimate file
2. Open view
3.
[log.txt](https://github.com/archimatetool/archi/files/8754100/log.txt)

**Comment by Phillipus** [comment]
You have Herve's Specialization plug-in installed. This is no longer supported. See the text here https://github.com/archi-contribs/specialization-plugin

>The specialization plugin is designed to specialize concepts (figures, icons, etc.) inside Archi up to version 4.8.
> As Archi 4.9 natively includes specialization, this plugin won't be maintained anymore. it can be considered as deprecated.

**Comment by jeroeneikmans** [comment]
Thanks for the quick response and the solution to my problem. Simply uninstall specialization plugin.

**Comment by Phillipus** [comment]
I'll close this then.
