### ISSUE TITLE
[Feature Request] Distributing Linux releases through Flatpak?

### ISSUE THREAD

**Issue by weavermarquez** [archimatetool/archi#847]
Hi all, I'm wondering if there are any plans to distribute a Flatpak version of Archi. 

Correct me if I'm wrong, but I had a cursory glance through the Forum and Github Issues ~and didn't find any discussion on any alternative packaging/distributions, even of AppImages, Snaps, or repository packaging (rpm, deb).~
_(edit: I'm silly - here's recent stuff from [Nov 2021](https://forum.archimatetool.com/index.php?topic=1132.msg6059#msg6059), with [Github guide](https://github.com/archimatetool/archi/wiki/How-to-create-a-packaged-version-of-Archi-(including-configuration-and-plugins) on this repo )_

If you are not familiar with Flatpak: [Flatpak is a framework](https://docs.flatpak.org/en/latest/introduction.html) for distributing desktop applications across various Linux distributions. 

If the maintainers find the notion unnecessary because of Java, that's okay. However, it should not suck up your time, as it is primarily a packaging feature request - one that I am willing to work on.

Some points to consider:

- An outside maintainer willing to work on this (me) - I've been meaning to learn this for a while.
- Existing prior work to draw from, e.g. [Flatpaks using OpenJDK11](https://github.com/search?q=org%3Aflathub+org.freedesktop.Sdk.Extension.openjdk11&type=Code)
- Flatpak provides convenient user-space sandboxing, further reducing potential vectors of attack through Archi or any of its components.
- Many developers in the GNOME ecosystem have used Flatpaks as a very effective CI/CD tool, as Flathub provides a buildserver.
- A Flatpak creates public exposure in multiple channels across the Linux ecosystem. Several major Linux GUI software managers showcase Flathub apps with their native repository apps.
- Potential for a 1-click install for Archi Plugin inside the Archi Flathub page

The first link above goes into the various issues that Flatpak solves

**Comment by Phillipus** [comment]
I am absolutely adverse to App stores, Snaps, Flatpaks or any other form of distribution that will lead to support issues due to permissions, sandboxing.

Sorry, but I'm only going to distribute and support the current distributions.

**Comment by weavermarquez** [comment]
Ah, that makes sense. No need to be sorry - maintainers have to set their boundaries. Have a lovely day! :)
