### ISSUE TITLE
[Feature Request] AutoSave Please

### ISSUE THREAD

**Issue by shinkinson** [archimatetool/archi#850]
Just looking to add an autosave function please to Archi. Corporate PCs require frequent restarts for patching etc., and if you forget to save all your lovely work is gone. Caught me out a few times :)

Doesn't need to be an MS Paperclip, just a simple (1) "save every X mins" option and potently (2) "re-start from last place you were editing" as secondary feature.

**Comment by Phillipus** [comment]
Hi, as mentioned in the Archi Forum, the side-effects of this are unknown if it is running as a background task.

https://forum.archimatetool.com/index.php?topic=1213.0

https://forum.archimatetool.com/index.php?topic=1079.msg5766
