### ISSUE TITLE
property hide_from_export = true - doesn't hide the element, folder or view from the export 

### ISSUE THREAD

**Issue by InceptusSolutions** [archimatetool/archi#855]
All my models show this behaviour (I have only just found out you are supposed to be able to hide elements)

### Version of Archi 

4.10 (Also 4.9.3)

### Archi Plug-ins

jArchi
CoArchi
Lightbox
Excel

### Operating System

Windows 11

### Expected Behaviour

property hide_from_export set to "true" is supposed to hide the view or element or folder from the HTML report but it doesn't

### Actual Behaviour

The view, element or folder shows up in the model explorer in the HTML

### Steps to Reproduce the Behaviour
1. add property "hide_from_export" to a view, folder or model element
2. set value of the property to true
3. run the report HTML (file > report > HTML) (or run the HTML preview)
4. the view, folder or model element still appear in the generated HTML report
![Screenshot 2022-06-30 164735](https://user-images.githubusercontent.com/98902566/176720823-de11bb5b-b05a-47bc-b643-a6d63241f205.png)
![Screenshot 2022-06-30 164546](https://user-images.githubusercontent.com/98902566/176720857-ee1b87d0-bbcf-432d-ac39-1101026ac318.png)

**Comment by jbsarrodie** [comment]
> Hi, the property (and others) applies to Jasper reports, not HTML reports.

No, this one in particular does target the HTML report, but it should start and end by underscore (`_hide_from_export_`)

**Comment by InceptusSolutions** [comment]
Thanks.
Just as a note the documentation (Archi User Guide) page 99 is missing the leading and trailing underscores for the property.

Regards
Paul Perry
Inceptus Solutions

***@***.***
***@***.******@***.***>
07595 401 208

**Comment by Phillipus** [comment]
> Just as a note the documentation (Archi User Guide) page 99 is missing the leading and trailing underscores for the property.

That's fixed in Archi 4.10 user guide.

**Comment by Phillipus** [comment]
> No, this one in particular does target the HTML report, but it should start and end by underscore (`_hide_from_export_`)

Yep, I keep getting these mixed up.

**Comment by Phillipus** [comment]
Assuming that `_hide_from_export_` works, close this.
