### ISSUE TITLE
How to make achi support UPDM

### ISSUE THREAD

**Issue by Iyetux** [archimatetool/archi#858]
Reference documents
I can achieve basic extensions (GEF, RPC, etc.)
But I have no clue about UPDM.

**Comment by Phillipus** [comment]
What does this mean? What is UPDM? Do you mean to import something?

Please elaborate.

**Comment by jbsarrodie** [comment]
I guess you're refering to UML Profile for DODAF/MODAF. Archi being an ArchiMate modeling tool and not a UML one, this is not supported (nor even possible).

**Comment by Iyetux** [comment]
@Phillipus Thank you for your reminder. I may not be clear about the concept.

@jbsarrodie Your guess is right.Because I saw that achi was very similar to modelio, but achi was updated, so I had a bold idea.
