### ISSUE TITLE
HTML Report does not honor "hide_from_export" property

### ISSUE THREAD

**Issue by MarcF88** [archimatetool/archi#861]
### Version of Archi
4.9.3

### Archi Plug-ins

Collaboration
Archi command line
Archi Excel plugin
Archi scripting
Lightbox

### Operating System
Windows 11

### Expected Behaviour
When generating an html report, views with property "hide_from_export" set to value "true" should not be exported, nor should folders with the same (as per user manual)

### Actual Behaviour
Property "hide_from_export" is blissfully ignored and so-equipped views and folders are included in the report.

### Steps to Reproduce the Behaviour
1. Add property "hide_from_export" to view or folder, set its value to "true"
2. Save the model
3. Select "File .. HTML Report"

**Comment by Phillipus** [comment]
There was a typo in the help file. You need to use `_hide_from_export_`

See https://github.com/archimatetool/archi/issues/855

**Comment by MarcF88** [comment]
That was *fast*. And three cheers for the property manager, that has a rename function for exactly this purpose. I can confirm that this works, thank you!

**Comment by Phillipus** [comment]
OK, I'll close this one.
