### ISSUE TITLE
Install failed partially (jArchi not enabled)

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi#869]
### Version of Archi
I am using Archi 4.10

### Archi Plug-ins
I have jArchi installed.

### Operating System
I am on MacOS 12.6 on Apple silicon.

### Expected Behaviour
I expected the new Archi to start up flawlessly.

### Actual Behaviour
At startup, I got this screen (partial screen shown)
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/275768/190574602-5c5dccff-ad90-4ad3-8cbc-154a1f370a14.png">

### Steps to Reproduce the Behaviour
1. I deleted my old Archi by taking the application to the trash bin.
2. I installed the new Archi according to the instructions.
3. I started Archi.

**Comment by Phillipus** [comment]
As noted you need to use jArchi 1.2.1 with Archi 4.10:

https://forum.archimatetool.com/index.php?topic=1249.0

https://forum.archimatetool.com/index.php?topic=1234.0

**Comment by Phillipus** [comment]
I'll close this one as the fix is to use jArchi 1.2.1 with Archi 4.10.

**Comment by stefjoosten** [comment]
It works! Thx!
