### ISSUE TITLE
Improve accessibility for people having eyesight disabilities

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#870]
### Version of Archi
 4.93

### Archi Plug-ins
 YES

### Operating System
 WINDOWS10

Hello,
I'm frequently working with people having vision disabilities. I would like to improve the use of ARCHI for these persons. Here attached a document to explain the requirements. 

Regards
Merci beaucoup.
Christine
[Improve accessibility for people having eyesight disabilities.pdf](https://github.com/archimatetool/archi/files/9584354/Improve.accessibility.for.people.having.eyesight.disabilities.pdf)

**Comment by Phillipus** [comment]
Hi Christine,

thanks for the report.

> A solution could be to add a (small) letter close to the object pictogram

The ArchiMate 3.1 specification does say that the letters B, A and T can be displayed on an element. This solution can be achieved through using a Label Expression in Archi. For example - `${name} (B)`

> Having a way to enlarge the size of menu items

This depends on the display settings in the operating system (by increasing text size, perhaps)

> Having a way to enlarge the buttons size

From your screen shot I think you are referring to the toolbar buttons. Unfortunately, the relative size of the toolbar and its buttons is fixed by the Eclipse framework.

**Comment by jbsarrodie** [comment]
Hi Christine,

As Phil said, there are several constraints related to the eclipse framework.

Some short term hints:
- Color is not normative in ArchiMate, thus you are free to use whatever color make sense, and choose them to avoid such issue as much as possible. Some [online resources](https://davidmathlogic.com/colorblind/#%23000000-%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7) can help check in advance if chosen color are "safe" or not.
- Setting a label as `${name}\n(${type})` can make the element type explicit. Such label can be set quickly with a simple script. There's also a (slightly more complex) way to only add a single letter based on the layer through label expressions (it involves creating model properties whose name are the ArchiMate element types, and value are the associated letters. Then `${name}\n$model{property:${type}}` does the trick).
- In Windows, it is possible to change DPI settings on an app basis. I've never tried to use these settings to lower DPI, but you might try to see if it helps to have bigger icons. This has been discussed [here](https://github.com/archimatetool/archi/issues/832#issuecomment-1082211193).

**Comment by chdessus** [comment]
Thank you so much. Add a label with ${name}\n(${type})  is a good solution solution for the time being.
I really appreciate your answer. 
Christine

**Comment by chdessus** [comment]
Hello,

Hope you will get this message. The solution proposed by both of you is
convenient.
I just add the ${name}\n(${type}) label and it works fine.
many thanks.
Regards.

Christine Dessus
T : +33 6 31 09 73 54
www.competensis.com
