### ISSUE TITLE
[Archi 5] Support ArchiMate 3.2

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#875]
This is an umbrella issue for implementing the changes in Archi for ArchiMate 3.2.

Changes between 3.1 and 3.2 - https://pubs.opengroup.org/architecture/archimate32-doc/#_Toc112155137

- Improved the definitions of several concepts, most notably outcome, constraint, business function, and product
- Made the Physical elements part of the Technology Layer chapter instead of a separate chapter
 - Changed the Technology Layer metamodel, making device, system software, facility, and equipment no longer subtypes of node but of technology internal active structure element, and adding composition and aggregation relationships with node.
- Added composition and aggregation relationships from plateau to outcome
- Added realization from material to equipment
- Improved the restrictions on derivation rules described in Section [B.3.5](https://pubs.opengroup.org/architecture/archimate32-doc/#_Ref93150978)
- Added a derivation rule for grouping
- Changed the icon notation of the meaning and communication network elements, added an icon notation for work package, and added new box notations for meaning, value, business object, contract, representation, work package, and deliverable
- Changed the default color of the plateau and gap elements to the same pink as the other Implementation and Migration elements

**Comment by Phillipus** [comment]
New branch `archimate32` created.

Things to do:

- [x] Change default colours of Location, Gap and Plateau
- [ ] Add alternate figures for Business Object, Contract, Representation, Product, Grouping, Data Object, Meaning, Value, Work Package, Deliverable
- [x] Change some first type figures to rectangles
- [x] Swap some default figure types from first position to second position (e.g. Application Component)
- [x] Add Model Compatibility Handler to handle swapped default figure types
- [ ] Update Relationships table
- [ ] Update Hints texts

**Comment by jbsarrodie** [comment]
I'll take care of the relationship table and suggest to replace hints content by only the definition coming from the glossary. This should make it easier for people to translate Archi because they'll be able to reuse the official glossary's translation (and if none exist, they could create one and I'll manage to get it through the internal review process of the Open Group).

We should also anticipate a bit the fact that the ArchiMate Model Exchange File Format will change in the (hopefully) near future and make sure we can importe a file which claims to be from the new version (without changing the import code). This will make sure that people can at least import a model created with another tool that create "3.2" AMEFF files.

**Comment by Phillipus** [comment]
@jbsarrodie I've had a go at the new small icons and the new alternate figures (Work Package, Communication Network).

I failed at creating thought bubbles for the Meaning figure, so left it as it is.

My maths is terrible!

**Comment by Phillipus** [comment]
> replace hints content by only the definition coming from the glossary. 

I can't find the 3.2 glossary. Is it published?

**Comment by jbsarrodie** [comment]
> I failed at creating thought bubbles for the Meaning figure, so left it as it is.
> My maths is terrible!

😂

I'll manage it. It might be better to either keep the current figure as the icon version or used a slight different one to maximize the avalable space for the text inside the bubble (e.g. having only one small bubble in the lower left corner).

>I can't find the 3.2 glossary. Is it published?

No, but I can share it with you in private.

**Comment by Phillipus** [comment]
For the hints, the text is rather short. Should we keep the Category ad Examples parts?

For example:

A **Business Actor** represents a business entity that is capable of performing behavior.

**Category:**
Business. Active Structure.

**Examples:**
A Customer, Marketing & Communications department, Director of Finance, Secretary, Admissions Department, Product Development.

**Comment by jbsarrodie** [comment]
>Should we also keep the Category and Examples parts?

Yes, that make sense and there's no changes on these parts

**Comment by ModelDeveloper** [comment]
> @jbsarrodie I've had a go at the new small icons and the new alternate figures (Work Package, Communication Network).
> 
> I failed at creating thought bubbles for the Meaning figure, so left it as it is.
> 
> My maths is terrible!

Hello @Phillipus 

I'm not sure if this is still an outstanding issue, but in case you are interested, I have created a 16x16 'Meaning' transparent PNG (the GitHub Issue editor does not allow me to include the .ICO file) that approximates the new ArchiMate 3.2 version (attached).
![archi_moti_meaning32](https://user-images.githubusercontent.com/88500285/201552615-f03c3c01-41f7-47a4-8c01-3c724dd2f25b.png)

Regards,
Andrew Greff

**Comment by Phillipus** [comment]
HI Andrew, thanks for that. The palette requires a 16x16 and a 32x32 version. The actual figures are created in Draw2d code (example [here](https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor/src/com/archimatetool/editor/diagram/figures/elements/MeaningFigure.java))

**Comment by Phillipus** [comment]
> Here is the new relationship.xml file (created from the official Excel version of the table, thus the order of concepts and characters is a bit different):

Thanks for that! In order to get a readable diff between versions I need to put it all in alphabetical order. Can you think a way to do this? Maybe a jArchi script? ;-)

**Comment by jbsarrodie** [comment]
> Thanks for that! In order to get a readable diff between versions I need to put it all in alphabetical order. Can you think a way to do this? Maybe a jArchi script? ;-)

I can easily do it for concepts' names (I just have to reorder some columns and rows), but that's another story for letter combinations depincting allowed relationships :-(

**Comment by Phillipus** [comment]
I'm working on a Java routine to do it...

**Comment by Phillipus** [comment]
This one is missing:

`<target concept="Junction" relations="afnortv" />`

**Comment by jbsarrodie** [comment]
> This one is missing:
> 
> `<target concept="Junction" relations="afnortv" />`

Yes, that's because things changes a bit:
- All relationships can be used with Junction
- From [ArchiMate 3.2 - 5.5.1 Junction](https://pubs.opengroup.org/architecture/archimate32-doc/#_Toc112154932): a junction (which connects some relationships), may also be aggregated or composed in a plateau, grouping, or location element. If that junction connects other aggregation or composition relationships, it should be interpreted without the aggregation or composition to this containing element. The composition or aggregation merely states that the junction is part of a plateau, grouping, or location. Without that relationship, the junction must fulfill the same conditions as above: it connects relationships of the same type, with at least one incoming and one outgoing relationship.

But for us, maybe it still makes sense to add it to the xml file.

**Comment by Phillipus** [comment]
We have to add it to the xml file because of the way the code works. So should it be this?

`<target concept="Junction" relations="acfginorstv" />`

And this:

```
    <source concept="Junction">
        <target concept="ApplicationCollaboration" relations="acfginorstv" />
        ...more...
```

**Comment by Phillipus** [comment]
@ModelDeveloper Thanks for that. The icons in the tree and palette are indeed pngs. See [here](https://github.com/archimatetool/archi/tree/master/com.archimatetool.editor/img/archimate).  I tried your Meaning icons and I think it might work better with only one small bubble and more rounded main bubble.

For reference - https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor/img/archimate/meaning%402x.png

**Comment by jbsarrodie** [comment]
>So should it be this?

Yes, I'll re-generate the XML tomorrow.

**Comment by jbsarrodie** [comment]
>It's easier for me to manually edit it...

That's quite easy for me and I can re-order concepts at the same time ;-)

**Comment by Phillipus** [comment]
> That's quite easy for me and I can re-order concepts at the same time ;-)

Noooooooooooooooooooooooooooo!

https://github.com/archimatetool/archi/commit/79b2e0903824ce0b358637390606b679b33c8d32

**Comment by Phillipus** [comment]
Archi 5 is out!

**Comment by Phillipus** [comment]
@fdh54 The was changed because new figures were introduced in Archi 5.2 for each concept and the figure types had to be standardised. The Archi file format is internal and subject to change.
