### ISSUE TITLE
Problems Opening Link: unable to open web browser {0]

### ISSUE THREAD

**Issue by pi4630** [archimatetool/archi#879]
Error does not appear in archi error.log.

### Version of Archi
4.10.0

### Operating System
Linux, Ubuntu 20.04 LTS. Using google-chrome-stable as web browser.

### Expected Behaviour
When I click on URLs from within archi, I'd like archi to open my system web browser with that URL. (I use URLs in value fields in properties).

### Actual Behaviour
When I double click on the world icon, I get an error message: Title "Problems Opening Lik" and detail "Unable to open web browser on {0}

### Steps to Reproduce the Behaviour
1. Draw any object from palette into a view
2. Under "Properties" of that object, enter any name in Name and an URL in the Value field
3. Try to click on the world icon that appears
![Auswahl_981](https://user-images.githubusercontent.com/8255446/200278505-86226861-4ec0-4c37-8019-4e19ad27fb30.png)

**Comment by Phillipus** [comment]
This will be something to do with the Linux configuration of webkit as that's the underlying browser used by Eclipse. Nothing I can change on our side. Please investigate your Linux setup.

**Comment by Phillipus** [comment]
What is the URL that you are trying to open?

**Comment by Phillipus** [comment]
See:

https://www.eclipse.org/forums/index.php/t/154955/
https://github.com/archimatetool/archi/issues/866#issuecomment-1235715505
https://bugs.eclipse.org/bugs/show_bug.cgi?id=534113

**Comment by pi4630** [comment]
Thank you for your efforts. I'll look into it and get back to you when I've found a solution. Yes, I don't have this problem on macOS.

**Comment by pi4630** [comment]
I tried my eclipse 2022-06 IDE instance. The webbrowser is recognized fine, and whenever I create a HTML page and choose to open it with "Open With Webbrowser", Chrome pops up and shows the page.
Some screenshot:

Can it be that some underlying eclipse library/config is missing from within the archi tool? The archi Edit->Preferences->General don't show webbrowser recognition, like in the eclipse case.
![Auswahl_984](https://user-images.githubusercontent.com/8255446/200318246-2d24a35f-9fd7-4e9f-aadd-6c85f1b83f95.png)
![Auswahl_982](https://user-images.githubusercontent.com/8255446/200318276-b4dbe576-7ad9-41e1-970e-b7d406c7e76e.png)

**Comment by Phillipus** [comment]
Archi doesn't do anything special, it calls the system browser:

https://github.com/archimatetool/archi/blob/40996e3af5f55235718514d5464bca9aa0bd49e5/com.archimatetool.editor/src/com/archimatetool/editor/utils/HTMLUtils.java#L65-L70

**Comment by pi4630** [comment]
Okay, I will check with the eclipse rcp forum and report back. Current version in 4.10.0 is Eclipse RCP	4.25.0.v20220831-1800	org.eclipse.rcp.

**Comment by Phillipus** [comment]
I think the reason is as described here:

https://www.eclipse.org/forums/index.php?t=msg&th=154955&goto=489201&#msg_489201

**Comment by Phillipus** [comment]
Eclipse has a preference page to set the external browser. Archi doesn't include the plug-in that contains this preference page (`org.eclipse.ui.browser`). It is possible that we could do this. I'll investigate if there are any overheads or unwanted dependencies.

**Comment by pi4630** [comment]
Thank you . yes, that would be a feature request :) I hope there is no regression.

**Comment by Phillipus** [comment]
The Web preference will be in Archi 5

**Comment by pi4630** [comment]
Thanks a lot, will look into it!

**Comment by damobrisbane** [comment]
On linux I fixed issue by adding link to my browser, ie:

sudo ln -s /usr/bin/google-chrome /usr/bin/mozilla

ref: https://stackoverflow.com/questions/6269748/using-firefox-in-eclipse-instead-of-ie
