### ISSUE TITLE
[Archi 5] Secure credentials and proxy settings

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#881]
At the moment we have custom secure credentials storage and proxy settings in coArchi. We need to implement secure credentials and proxy in Archi itself so that other plug-ins can use them.

Proposal is:

- Use Eclipse's secure storage for passwords
- Use our proxy code moved to Archi from coArchi

I've implemented this in the `security-proxy` branch.

Eclipse's secure storage has a lot of advantages:

- it's possible to store the primary password encrypted by the system so user doesn't have to input a primary password each time
- or you can set it so the user _does_ have to input a primary password each time.
- which encryption algorithm to use can be set by the user

For reference - https://help.eclipse.org/latest/index.jsp?topic=/org.eclipse.platform.doc.user/reference/ref-securestorage-options.htm

**Comment by Phillipus** [comment]
> Use Eclipse's secure storage for passwords

The other alternative is to use our own encrypted property storage secured by a password. This would have to be manually unlocked on first use as we do in coArchi, and would need a bit of re-inventing of the wheel regarding setting/changing the primary password and so on. We get all of that for free with the Eclipse implementation.

@jbsarrodie WDYT?

**Comment by jbsarrodie** [comment]
>@jbsarrodie WDYT?

I'm never in favor of re-inventing the wheel, so I would go for Eclipse's secure storage. My only remark is: would it be possible to force a secure storage provider (and some of its attributes) through `Archi.ini` file, for the case where a "big company" wants to enforce some provider (e.g. primary password based) and options (e.g. minimum password lenght...) ?

**Comment by Phillipus** [comment]
> minimum password lenght

That isn't possible without writing your own provider which I think would be quite hard.

**Comment by jbsarrodie** [comment]
> You can select which one to use in prefs. This is written to a file in `.config/.settings/org.eclipse.equinox.security.prefs`:

Ok, so like with any preference, it should be possible to [set the default value](https://github.com/archimatetool/archi/wiki/How-to-create-a-packaged-version-of-Archi-(including-configuration-and-plugins)#change-default-configuration)

>Actually it is possible to write your own Password provider. It would have to be a manually entered password type dialog but you could then check it for length etc

Perfect ! Of course not needed at the moment, but good to know it is possible if really needed.

**Comment by Phillipus** [comment]
One more thing. Because the path to the Eclipse secure storage file (key ring) is set in `Archi.ini`, you will need to launch Archi from Eclipse by clicking on the Launch link in the `archi.product` file. This will effectively add the following to the Program Args:

```
-eclipse.keyring
@user.home/AppData/Roaming/Archi4/secure_storage
```
