### ISSUE TITLE
Input of CSV reports " Invalid character" in ID field 

### ISSUE THREAD

**Issue by Neil-Kemp** [archimatetool/archi#883]
### Version of Archi
 4.10.0

### Archi Plug-ins
 Yes

### Operating System
 windows 11

### Expected Behaviour
[exportelements.csv](https://github.com/archimatetool/archi/files/9998372/exportelements.csv)

 Round trip export/input should work

### Actual Behaviour
 I exported a file as CSV. Ran spell checking *only* on the "Name" column and attempted to reimport only "exportelements.csv
[exportelements.csv](https://github.com/archimatetool/archi/files/9998389/exportelements.csv)
"

### Steps to Reproduce the Behaviour
1. Export and input with no change
2.
3.

**Comment by Phillipus** [comment]
Hi, I can import the attached CSV file without any errors. I did notice, though, that the fields are not surrounded with quote marks. Perhaps your external editor corrupted a field?

**Comment by Neil-Kemp** [comment]
Interesting.  when I did the export the files did did not contain the quotes before I did any editing

**Comment by Phillipus** [comment]
> Interesting.  when I did the export the files did did not contain the quotes before I did any editing

Archi's CSV exporter adds quotes to each field. Perhaps your editor removed them?

**Comment by Neil-Kemp** [comment]
I redid every just now. The problem is the way I am using Excel for the import

 

I am sure I can take it from here

 

Thx
