### ISSUE TITLE
Shift-Del to remove item from model

### ISSUE THREAD

**Issue by triplebeta** [archimatetool/archi#884]
In the popup menu there are 2 options to delete an item but when working with Archi I often use the keyboard for simple actions.

The Del key works to remove an item from the diagram but keeps it in the model.
I'd like to see a keyboard shortcut like Shift-Del for removeing an item from the model.

Furthermore, both of these shortcuts might be shown in the popup menu next to the option, just like the popup shows that "Copy As Image to Clipboard" can be done with Ctrl+Shift+C.

**Comment by Phillipus** [comment]
Sure, why not. Will be in Archi 5.
