### ISSUE TITLE
Label expression for access-relationship does not show Access Type

### ISSUE THREAD

**Issue by olwol** [archimatetool/archi#885]
### Version of Archi
4.10.0

### Archi Plug-ins
Collaboration
Excel
Scripting
Lightbox

### Operating System
Windows 10

### Expected Behaviour
I have an access relation created and I want to show the access type (Read, Write, ...) using the label expression.

In a view I have:

- Source concept name = A
- Target concept name = B
- Relation concept name in model tree = C
- Relation concept name in view = D
C = D
- Relation concept in model tree has Access Type Read selected and it is visible with the view concept in the Main tab.

We have the following prefixes for label expressions for connections:
- source
- target
- parent

The following works as expected.
- `$source{name}` shows A
- `$target{name}` shows B

But
- `$parent{name}` shows A
I am expecting
- `$parent{name}` to show D

I am expecting to get the name of the relation concept in model tree as it is the visual relation concepts parent, isn't it?
And I expect either `$parent{accessType}` or `${accessType}` to work and show "Read".

When I use scripting and the access-relation is the selection, the following

- `selection.concept.getAccessType();`

shows "Read". But it does not work without the "`.concept.`". So, it is not available with the visual element. Due to this, I am wondering, whether it would be intended to be available with `$parent{accessType}` but is missing for some reason.

Is this a bug?

**Comment by Phillipus** [comment]
Hi, Access type is not implemented in Label expressions, and we should consider it for the next time we work on expressions. The only expressions that are supported to date are those in the [wiki](https://github.com/archimatetool/archi/wiki/Label-Expressions).

**Comment by olwol** [comment]
Hello, I'd appreciate it if you put it on your to-do list to work on it next time you work on expressions.
Thanks for the quick response.

**Comment by Phillipus** [comment]
OK, but let's keep the issue open so I remember. :-)

**Comment by Phillipus** [comment]
Will be in Archi 5
