### ISSUE TITLE
Export SVG View as a Service

### ISSUE THREAD

**Issue by kinjelom** [archimatetool/archi#890]
Is there any way to use the Archi (command line?) or its components to export a view as SVG?

**Comment by Phillipus** [comment]
jArchi supports exporting to SVG, so you could create a script and run that script from the ACLI.

**Comment by kinjelom** [comment]
[ACLI](https://devlog.archimatetool.com/2017/07/28/archi-command-line-interface-acli/) + jArchi... thanks, I will try it :)
