### ISSUE TITLE
Associations does not snap to the boundary of the new figures

### ISSUE THREAD

**Issue by q-rt** [archimatetool/archi#891]
### Version of Archi
5.0.0 beta 1
Build: 202212041528

### Archi Plug-ins
Archi Excel Plugin 0.2.202108071821
coArchi 0.8.7.202212021111
jArchi 1.3.1.202211041747
Lightbox for Archi 1.2.0.202212041725

### Operating System
Windows 11 Enterprise 22H2

### Expected Behaviour
Association should snap to the boundary of the active/selected figure 

### Actual Behaviour
Association snaps to the boundary of a default figure

### Steps to Reproduce the Behaviour
1. Create new empty model
2. Create two new value items, oversize these
3. Create association between elements 
4. Drag association to the edges of the elements

![image](https://user-images.githubusercontent.com/20205517/209787605-d1db060c-d65a-4bc7-a55a-e2ae892366f2.png)

**Comment by Phillipus** [comment]
Good catch! Thanks for the report. This will be fixed in Archi 5 beta 2.

**Comment by Phillipus** [comment]
Fixed in Archi 5 beta 2.
