### ISSUE TITLE
WorkPackage Icon

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#893]
I'm tuning the workpackage small icon (the one used in the box notation) and came up with two variants:

1) Based on the [very first proposal](https://media.licdn.com/dms/image/C4D2CAQFn1iqHgfhaIA/comment-image-shrink_8192_1280/0/1643634696862?e=1673956800&v=beta&t=3O3g4FHfpITfz848D1hW7U3vMil34reNYYHOYID9u4U) I made [on LinkedIn](https://www.linkedin.com/feed/update/urn:li:groupPost:50758-6892858604165181440?commentUrn=urn%3Ali%3Acomment%3A%28groupPost%3A50758-6892858604165181440%2C6893903585911140352%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%286893903585911140352%2Curn%3Ali%3AgroupPost%3A50758-6892858604165181440%29):
![image](https://user-images.githubusercontent.com/5757396/211570402-80813678-06d1-464f-a6cf-a70212b39944.png)

2) Based on the [version which ended up in the spec](https://pubs.opengroup.org/architecture/archimate32-doc/#_Toc112155048) (which is slighly different):
![image](https://user-images.githubusercontent.com/5757396/211571830-d40c4aec-3f93-4469-84a4-0c0f8924b4c6.png)

@Phillipus Which one do you prefer ?

**Comment by Phillipus** [comment]
In the spec the arc joins the arrow line so it is almost a circle, which is what I tried to do in my attempt:

![image](https://user-images.githubusercontent.com/600504/211573715-b91bc259-034c-4e9d-b469-10e2b7be3097.png)

**Comment by jbsarrodie** [comment]
>In the spec the arc joins the arrow line so it is almost a circle

That's a "flaw" in the spec ;-) It shouldn't appear as a full circle (inspired from the agile sprint icon).

I choose version (2) and added a bit more of the arc. This seems (to me) the best compromise:
![image](https://user-images.githubusercontent.com/5757396/211753940-3c66c60b-3e8a-4fdb-975d-e57ffdcb2074.png)

Next: tuning the full icon

**Comment by Phillipus** [comment]
I prefer this one:

![image](https://user-images.githubusercontent.com/600504/211785976-79a81e34-832d-48ee-a484-669d5bf5e943.png)

;-)

**Comment by hammerled** [comment]
I prefer the first one as it looks a bit more balanced.

Regard,

Andrew Greff

**Comment by jbsarrodie** [comment]
@Phillipus Just noticed (but too late) that I pushed to `master` instead of a feature branch :-(

**Comment by Phillipus** [comment]
That just shows how confident you are in your change. :-) 

I pushed a branch `wp-figure` and put `master` back to how it was with a force push. You'll need to pull and reset.

I got a mix of tabs and spaces in `AbstractTextControlContainerFigure.java` so hard to see what changed there. Maybe your Eclipse is set to use tabs instead of spaces.

**Comment by jbsarrodie** [comment]
>I got a mix of tabs and spaces in AbstractTextControlContainerFigure.java so hard to see what changed there. Maybe your Eclipse is set to use tabs instead of spaces.

Maybe, I'll have a look (trying to get everything working again now that target has changed...)

**Comment by Phillipus** [comment]
I can reformat and force push the branch if you'd prefer.

**Comment by Phillipus** [comment]
Don't worry about the spaces thing, it had tabs in anywyay. I force pushed `wp-figure` again anyway.

**Comment by Phillipus** [comment]
I tested this and the change in #895 and it's all good by me. Let's commit this and get Archi 5 out!

**Comment by jbsarrodie** [comment]
>Let's commit this and get Archi 5 out!

waiiiiiiittttttt, I still have to fix the meaning figure

**Comment by Phillipus** [comment]
> I still have to fix the meaning figure

What do you, er, _mean_? Oh yeah I forgot about that one, needs an extra bubble...
