### ISSUE TITLE
Add menu option to straighten connectors (which are manually bended?)

### ISSUE THREAD

**Issue by FlightControl-User** [archimatetool/archi#896]
### Version of Archi

4.9;2

### Archi Plug-ins

Yes, coarchi and jscript

### Operating System

Windows 11

### Feature Request

Please consider adding an option to make a manual connector between different archimate shapes "straight".
I don't recall there is a feature for this. So when i need to straighten a connector, I need to do this "manually" trying to make the bended points straight again.

![image](https://user-images.githubusercontent.com/13690775/215020540-e6903d5e-b3b7-4c74-8093-24804f510e84.png)

and make it straight like:

![image](https://user-images.githubusercontent.com/13690775/215020598-991e3cdc-24a9-406c-aaa3-e5b7646b9d80.png)

This is the menu currently:

![image](https://user-images.githubusercontent.com/13690775/215020653-e806ba4c-866c-481d-b8c1-3f10f1935a69.png)

Please advise ...

Sven

**Comment by Phillipus** [comment]
I think someone wrote a jArchi script to do this.

**Comment by Phillipus** [comment]
Save this as a jArchi script:

`selection.first().deleteAllBendpoints()`

In Archi 5 and jArchi 1.4 you can assign a key shortcut to the script.

Job done.

**Comment by FlightControl-User** [comment]
Thank you for the workaround. I'll try it. 
But can this little feat be added as part of the standard functionality of Archi?
I mean, this might help many.
