### ISSUE TITLE
Scroll canvas beyond last shape on the right, bottom, left, top ???

### ISSUE THREAD

**Issue by FlightControl-User** [archimatetool/archi#897]
### Version of Archi

4.9.2

### Archi Plug-ins

coArchi and jscript

### Operating System

Windows

### Feature request

Can please the scrolling area of an Archimate drawing be extended BEYOND the drawing borders of an active canvas?
Right now, the scrolling area stops at the last shape on the canvas, both horizontally and vertically.
Can the scrolling area be modified or with an option set so that at least you can scroll beyond the last shape on the drawing?

![image](https://user-images.githubusercontent.com/13690775/215021152-75977d8c-d7d5-40a1-b65e-9dd9f6718df5.png)

note the scroll bar and where it stops.

![image](https://user-images.githubusercontent.com/13690775/215021266-7a648bd1-5020-41e1-8b01-e43557163f47.png)

This hinders the user when i wants to extend a drawing, adding new shapes on an already existing drawing.
And yes, you can zoom in or out, but when you have a LARGE drawing, then it becomes really unhandy having to this, especially
if you have a large audience of people in front of you in workshops.

Please consider the following solution: can we add a setting that scrolling goes beyond the last shape with let's say x pixels, so that the architect can scroll to a white area and then add shapes there?

Sven

**Comment by Phillipus** [comment]
See https://github.com/archimatetool/archi/issues/185

Given that it's related to the Eclipse GEF perhaps someone might care to submit a PR for this one?

**Comment by FlightControl-User** [comment]
Where do i need to look to make a fix for this? Can you help me to indicate the area?

**Comment by Phillipus** [comment]
> Where do i need to look to make a fix for this? Can you help me to indicate the area?

If I knew that I would have implemented it by now,

There are many classes in the `org.eclipse.draw2d` package including `FreeformHelper`, `FreeformLayer`, `FreeformLayeredPane`, `Viewport` and others. These all work together to determine the overall figure canvas area and scrollbars depending on child figures and zoom level. Hacking into any of these to extend the figure canvas area can be done but is not a workable solution. As I said, before this requires a deeper dive into the Eclipse GEF and Draw2d code.
