### ISSUE TITLE
Keyboard shortcut for the Magic Connector

### ISSUE THREAD

**Issue by pvginkel** [archimatetool/archi#898]
I understand that Archi5 will have a keyboard shortcut configuration function, but I also saw that it doesn't support the palet. That's fine and I'm not requesting that support for this is added.

However, I would like to get a shortcut specifically for the Magic Connector. I think that if I'd have a shortcut for it, I wouldn't have a need for the other connectors on the palet anyway. I found out today that you can even add new elements through the Magic Connector. It's a very nice tool.

**Comment by Phillipus** [comment]
If you double-click or Shift-click the Magic Connector in the Palette it stays selected.

**Comment by Phillipus** [comment]
I'll close this one for the reasons stated.
