### ISSUE TITLE
Accent not correctly taken into account in alphabetical sort

### ISSUE THREAD

**Issue by Alice-Paillard** [archimatetool/archi#899]
### Version of Archi
4.10.0
Build 202209150946

### Operating System
Windows 10 Professionnel
French language

### Actual Behaviour
I have two elements in my model, "Gestion" and "Gérer" which don't appear properly sorted in the model tree: "Gestion" is 1st and "Gérer" is 2nd. 

### Expected Behaviour
In the model tree "Gestion" should appear 2nd and "Gérer" 1st. 

### Steps to Reproduce the Behaviour
1. Create an element "Gestion"
2. Create an element "Gérer"
3. view these 2 items in the model tree

**Comment by Phillipus** [comment]
Hi, this is already fixed for the next version Archi 5.

**Comment by Phillipus** [comment]
I'll close this one as it's already fixed.
