### ISSUE TITLE
Label Expressions does not display user defined property value

### ISSUE THREAD

**Issue by rdinnik** [archimatetool/archi#902]
### Version of Archi
4.10.0

### Operating System
Windows

### Expected Behaviour
If I have user defined property **"myprop"** with value equal to **"some text"**, label expression **${myprop}** should display **"some text"** on the symbol.

### Actual Behaviour
Text **"${myprop}"** is displayed on the symbol

**Comment by Phillipus** [comment]
Hi, that's not how to use a property in an expression label. use:

`${property:myprop}`

See https://github.com/archimatetool/archi/wiki/Label-Expressions

**Comment by rdinnik** [comment]
laybel expression should be ${property:myprop}
