### ISSUE TITLE
UX of element appearance settings in Properties window

### ISSUE THREAD

**Issue by Yame12** [archimatetool/archi#904]
Hi, I use this tool almost for 2 years now. It's a great help for my daily work. But I find the order of the controls in the Properties/Appearance window still confusing/unnatural.

![image](https://user-images.githubusercontent.com/124377468/216641263-5bfd79ad-0f84-420e-b106-1aa0e139eb4f.png)

The fill settings are distributed on multiple places - Fill Colour on top, Gradient in the middle, Fill Opacity at bottom. Same goes for Line settings - Colour in line 2 and the related Opacity setting at the bottom right. Out would be a more natural workflow to have it grouped together, eg.

- Fill Colour + Gradient + Fill Opacity  
- Line Colour + Line Opacity
- Icon Colour
- Text settings ...

Second suggestion: While a "correct" order of the settings might be subjective, the fixed 2-column layout is somewhat impractical - especially on smaller screens where space is limited. 

If the Properties Window is docked to the side with limited width - I need to scroll horizontally to get to the settings on the right:
![image](https://user-images.githubusercontent.com/124377468/216642276-a0b81700-187c-4b8f-ae66-ad8cbc4941ce.png)

If properties are docked to the bottom, I need to scroll vertically. Although in this case at least you can use the mouse wheel, but there is also big empty space which is practically unused.
![image](https://user-images.githubusercontent.com/124377468/216643217-c5f7109f-791d-41d4-a767-e9e229c33374.png)

Would it be possible to have the number of columns used responsive to the window size, similar to the Palette?  

Best regards,
Enrico

**Comment by Phillipus** [comment]
> If the Properties Window is docked to the side with limited width - I need to scroll horizontally to get to the settings on the right:

There is a setting in the local menu "Single Column Layout" (User Guide page 51) that might help.

> Would it be possible to have the column layout responsive to the window size, similar to the Palette?

For technical reasons, no.

**Comment by Yame12** [comment]
Hi Philipus, thanks for the quick hint - I never noticed this setting. It solves at least the horizontal scrolling issue ;-)
