### ISSUE TITLE
How is the ArchiMate metamodel encoded into the Archi modeler?

### ISSUE THREAD

**Issue by mwherman2000** [archimatetool/archi#905]
How is the ArchiMate metamodel encoded into the Archi modeler? How easy/difficult would be to encode the metamodel for a different visual language for designing software systems?

For example...
![20230204_141002](https://user-images.githubusercontent.com/6101736/216787846-48b85b9c-6d1d-4b0e-8ada-941600d7c1dd.jpg)

![20230204_140947](https://user-images.githubusercontent.com/6101736/216787861-e3434a05-ceb3-4312-a307-a07ab83b57c3.jpg)

Michael

**Comment by Phillipus** [comment]
> How easy/difficult would be to encode the metamodel for a different visual language for designing software systems?

Hi. It would be impossible.

Archi is specifically an ArchiMate modelling tool. For creating a tool based on a different metamodel, you need to look at a generic framework like Eclipse Sirius,
