### ISSUE TITLE
[Feature Request] Add letters to distinguish between layers for color blind people

### ISSUE THREAD

**Issue by pvginkel** [archimatetool/archi#907]
Would it be possible to (optionally) add letters to be able to distinguish between layers for color blind people? The lead EA in our team is completely color blind, so is not able at all to distinguish between the different colors of the different layers of the elements. If it were possible to add letters to the elements, like Example 34 in the spec show, that would allow us to adopt this tool within our organization.

Version 3.1:

https://pubs.opengroup.org/architecture/archimate3-doc/chap12.html#_Toc437870133

![image](https://user-images.githubusercontent.com/828966/217367512-06c90183-c8e5-493b-a99e-47cc8e4fb8fd.png)

Version 3.2:

https://pubs.opengroup.org/architecture/archimate32-doc/#_Toc437870133

![image](https://user-images.githubusercontent.com/828966/217367313-b94de285-2a47-45a9-84d8-47afa7de0f3c.png)

**Comment by Phillipus** [comment]
If you use [Label Expressions](https://github.com/archimatetool/archi/wiki/Label-Expressions) you can add anything you like.

**Comment by pvginkel** [comment]
I'm not sure if I follow. If I were able to set default label expressions per element type, this would implement my request. However, it seems that I can only set this per element. I'd have to do this for every element individually. Is this correct or is there an option to configure label expressions model-wide?

**Comment by Phillipus** [comment]
> I'm not sure if I follow. If I were able to set default label expressions per element type, this would implement my request. However, it seems that I can only set this per element. I'd have to do this for every element individually. Is this correct or is there an option to configure label expressions model-wide?

That's correct. You don't have to user letters. You could use a different signifier.

**Comment by jbsarrodie** [comment]
Hi,

My 2 cents on this (also apply to PR #908)...
1. A good architecture diagram should not need such thing to distinguish between layers as there should be no ambiguity in 90% of the cases (the viewpoint used, the view title and the legend should be enough). I would even argue that if there is ambiguity, then this is an issue with the view itself, not the person who tries to understand it.
2. In 90% of the remaining 10%, you can most of the time magically solve the issue by nesting the behavior inside its active structure, which is unambiguous.
3. For views that mix elements from multiple layers and for which such hint is needed (thus the remaining 1% from previous points), then a label expression should do the trick (see issue #870 for some examples). Setting a label expression on all elements from a view is as simple as: select all elements, then edit the label once and for all. Should you know people who can't remember the label to put, then a simple script can also do it.

So as you might have already understood, I don't see such change as a priority in Archi.

**Comment by wiebow** [comment]
You could also use a simple grouping mechanism to add the viewed elements in the group of its layer.

**Comment by Phillipus** [comment]
I'll close this one given above feedback.
