### ISSUE TITLE
I would like a visual improvement ! 

### ISSUE THREAD

**Issue by chdessus** [archimatetool/archi#913]
### Version of Archi
 4.9.3

### Archi Plug-ins

coArchi - EXCEL - Lightbox - jScript

### Operating System
 WINDOWS 10

### Steps to Reproduce the Behaviour

I'm now working on the model coherence. I select several Application Components in the directory, push it in a new view and I get a mess of relationships. The objective is to check these relationships and purge the double relations, no-more-necessary ones, group some relationships and transform 2 or more into a single one...
The difficulty is to grab the relation between 2 application components. 
Does it exist a trick to help ? I do have some difficulty to grab each relation and separate it from the others.

Here are 2 examples of my "relationships mess". 
Many thanks for your help.

Regards.
Christine.

[visual improvement.pdf](https://github.com/archimatetool/archi/files/10806803/visual.improvement.pdf)
<img width="608" alt="Visual impovement 2" src="https://user-images.githubusercontent.com/47627451/220712035-fed8b50d-2256-4fc4-8501-b0bebac09c2f.PNG">

**Comment by Phillipus** [comment]
Hi Christine,

As there are nine connections each with a text label connected to the same elements  it will be difficult to select individual connections as you have found. There's nothing we can do about how that is displayed as they default to the same position.

You could select each relationship in the models tree and delete it or rename it from there.

Or try this:

1. When you drag the Application Components onto the View, hold the `Ctrl` key at the same time. This will place the components in the view without any connections.
2. Then select a component in the view and, in the Properties window in the "Analysis" tab, you will see all of the components model relations in a table.
3. You can then drag one connection from that table onto the view and position the connection.
4. Repeat for the other connections.

Regards,
Phil

**Comment by jbsarrodie** [comment]
A script has been shared some time ago to help manage relationships in this case. You can find it here: https://forum.archimatetool.com/index.php?topic=1174.msg6254#msg6254

**Comment by Phillipus** [comment]
I'll close this one. :-)

**Comment by chdessus** [comment]
Hello.
Thank you.
It solves the issue.

Merci beaucoup.
