### ISSUE TITLE
Palette Switches to one with "Sticky" and Arrow Icons Only--Can't Switch

### ISSUE THREAD

**Issue by kirkpabk** [archimatetool/archi#915]
Hello, so when I used "split-screen" (Great Feature!!!) and pulled off a tab to a different window (another Great Feature!) the default archimate palette changes to one which has 11 different colored square "sticky" options, arrows, block and image icon.

![image](https://user-images.githubusercontent.com/6099696/221177092-f1d5c3b3-eaf5-4b61-9234-f382816ecd8c.png)

This is GREAT for collaboration and discussion... but the screens only have one or the other and can't swtich palettes. I can even make different tabs have one or the other by pulling the tabs on an off once the states have changed to the other palette--just can't change them once there, to get the normal pallete back, I needed to close the view and reload it.  

BK

**Comment by Phillipus** [comment]
Can you provide steps to reproduce, I don't follow what you mean?

**Comment by kirkpabk** [comment]
Good morning @Phillipus, so, in 4.10, if I have multiple views open. Switch between tabs, I get the standard palette.  If I drag a tab to split windows (vertical or horizontal), I sometimes get the pictured alternate palette.  

It's actually quite useful in collaboration and discussions, it really is!  But it's not easy to switch back.   It also appears to save okay.  So, I take it that this was not intended behavior?

**Comment by Phillipus** [comment]
That palette is for a Canvas View. If you select the Canvas View. that will be the palette you get.

**Comment by kirkpabk** [comment]
Yep--was about to post that.   Thanks--yeah, I had both types open with an original image of an architecture in the canvas view.  Great stuff!!
