### ISSUE TITLE
Updated "ArchiMate 3.2 Notation Overview"

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi#916]
Here's [an updated version of our "ArchiMate 3.2 Notation Overview"](https://github.com/archimatetool/archi/files/10842187/ArchiMate.3.2.Notation.Overview.zip) containing the following color schemes:
- ArchiMate Standard
- Mastering ArchiMate
- Low Saturation
- Saturated

It also contains the model with all elements (using both box and icon notation).

![ArchiMate 3 2 Notation Overview (Standard color scheme)](https://user-images.githubusercontent.com/5757396/221631821-a686aef2-bd6b-443e-a92d-ee5c7d4d5c62.png)

@Phillipus can you update them on Archi's website when you'll publish Archi 5.0 ?

~@Phillipus Wait, I've just seen a small glitch. Fixing it...~ Fixed

**Comment by Phillipus** [comment]
> can you update them on Archi's website when you'll publish Archi 5.0 ?

Sure can. When would you like to see Archi 5.0 go live?

**Comment by jbsarrodie** [comment]
> @jbsarrodie Are we good to go for Archi 5.0 this week?

Yes, it's up to you. For me everything looks ok (except some old minor bugs that I'll work on for 5.0.1 or 5.1)

**Comment by Phillipus** [comment]
Done!
