### ISSUE TITLE
Unable to view / edit Remote Repository Details and Credentials

### ISSUE THREAD

**Issue by whemix** [archimatetool/archi#918]
### Version of Archi
Archi v5.0

### Archi Plug-ins
Co-Archi 0.8.7.2
jArchi 1.3.1
Lightbox 1.2

### Operating System
MacOS Ventura 13.2

### Expected Behaviour
![image](https://user-images.githubusercontent.com/35859671/223357249-e8c7ab79-1ac9-40ae-8e00-d7e2a7ad4902.png)

### Actual Behaviour
Right click, Properties does not open the menu with information, User Details,  Credentials.

Only shows Main and Properties

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/35859671/223358742-d88fa074-9951-4d13-8de2-77c22a7044c4.png">

### Steps to Reproduce the Behaviour
With CoArchi and Remote Repository imported: 
1. Click 'Collaboration" Tab
2. Select the Repository nae
3. Right click -> Properties
4. Option to view / edit / update User Details and Credentials not present.

**Comment by Phillipus** [comment]
Hi, I can't reproduce this problem.

I notice that your screenshots show two different layouts. The first one has the Collaboration Workspace tab in a different area to the Properties tab. The second screenshot has the tabs all in the same grouping - this configuration will not update the Properties tab.

Can you provide a screenshot of the window layout where this is not working?

**Comment by whemix** [comment]
Hi, understand now that it has to be in a particular layout to view the properties.  I reset the window layout and can now see the Information, User Details, Authentication fields under Properties when right-clicking.  Thank you and consider this closed.
