### ISSUE TITLE
File locations in Linux

### ISSUE THREAD

**Issue by bratgers** [archimatetool/archi#92]
At this momen the default configuration location is 
-Dosgi.configuration.area=@user.home/Archi/configuration

But following the FreeDesktop specification (http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) it is better to  $HOME/.config
See: $XDG_CONFIG_HOME

I'm not sure if the -Dosgi.instance.area=@user.home/Archi contains interesting data or files for a regular user. Otherwise can also these directories hide from user perspective by dropping theme in $XDG_DATA_HOME -->  $HOME/.local/share

For example:
-Dosgi.instance.area=@user.home/.local/share/Archi
-Dosgi.configuration.area=@user.home/.config/Archi

**Comment by emidevops** [comment]
Current Archi version (5.0.2) use $HOME/.archi instead of $HOME/.config/.archi :-(
