### ISSUE TITLE
csv import on models with specializations (archimate zip files)

### ISSUE THREAD

**Issue by aborgmann-zech** [archimatetool/archi#921]
### Version of Archi
5.0.0 build 202303061333

### Archi Plug-ins
Archi Collaboration (CoArchi) 0.8.4
Archi Collaboration (CoArchi) CL 0.8.4
Database export/import plugin 4.9.6
Excel for Archi 1.0.0
jArchi 1.3.1
jArchi CL 1.3.1
jArchi Examples 1.3.1
Lightbox for Archi 1.2.0

### Operating System
Windows 10 Enterprise 22H2

### Expected Behaviour
Import of elements, properties and relations should add/update these objects to the model.

### Actual Behaviour
Nothing happens. No adding, no updating, no error messages
I can narrow down the error to archimate models with specializations (archimate zip files with model and images).
Same procedure with same import files work on "plain" models.

### Steps to Reproduce the Behaviour
1. Take an existing model without specializations
2. Add a specialisation with(!) image
3. Import csv file - nothing happens

4. Remove specialization with image
5. Save model (model file will be extracted from archive and saved as a plain .archimate file)
6. Import same csv file - objects will be imported correctly

[log.txt](https://github.com/archimatetool/archi/files/10940083/log.txt)

**Comment by Phillipus** [comment]
Thanks for the report. I can reproduce this bug. I'm working on a fix now.

**Comment by Phillipus** [comment]
This is because I re-wrote the CSV import code to re-use the model importer code. The model importer code expects to see an `ArchiveManager` in the imported model if there are images. Unfortunately, I forget to set one.

This will be fixed in Archi 5.0.1 next week. Sorry, there is no workaround other than to not use CSV import if the target model has images in it.

**Comment by aborgmann-zech** [comment]
Great. Thank you for the quick reply.

**Comment by aborgmann-zech** [comment]
CSV import works again like a charm. Great work! Thank you.
