### ISSUE TITLE
Archi crashes when updating a view

### ISSUE THREAD

**Issue by jsimoncello** [archimatetool/archi#922]
### Version of Archi

5.0.1
### Archi Plug-ins

coArchi 0.8.7
jArchi 1.3.1
### Operating System

Fedora 37
### Actual Behaviour

Archi crashes as soon as I try to modify something on a view, log starts with 
 # A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f94788ea4c4, pid=3589, tid=3591Archi 
(see attached error logs)

Problem occurred after I successfully use Archi for a few hours, and after I have published a model on gitlab. But since, It crashes every time I try to update a view, which ever model I am working on. ( I still can run script and  move concepts in the browser pane)
I have deleted config directory and restarted my computer, problem stil exists.

### Steps to Reproduce the Behaviour
1.Launch archi
2.create a new one
3.add concept to default view
4. save model
5. reopen it
6. move concept on the default view
7. > crash
[hs_err_pid3589.log](https://github.com/archimatetool/archi/files/11026132/hs_err_pid3589.log)
[crash model.zip](https://github.com/archimatetool/archi/files/11026171/crash.model.zip)

**Comment by Phillipus** [comment]
Ensure you use X11 not Wayland.

**Comment by Phillipus** [comment]
> Thanks for the hint, running with X11 seems to solve this issue.
