### ISSUE TITLE
[Feature Request] Search model tree to keep italics on items not on a view

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi#928]
When you do a model search, the items it finds are shown in bold. In fact they are all in bold (so is probably unnecessary anyway). The problem I have is that this overrides the normal/italic fonts that are used to show if they are used on a view or not. 

Can we either forget the bold, or have **_bold-italics_** if the found item is not on a view.

Hope that makes sense.

Richard.

**Comment by Phillipus** [comment]
Yes, that would take 2 seconds to implement. I just need to remember _why_ I decided to make search results bold.

**Comment by Phillipus** [comment]
...I remembered. When showing a parent folder that needs to be shown but is not part of the search result, this is non-bold.

> Can we either forget the bold, or have bold-italics if the found item is not on a view.

Not sure what's best.

**Comment by Phillipus** [comment]
I think bold-italics is best. When the tree is showing bold font it's an indicator that we are in Search mode, and it's been like this for a long time.

**Comment by Phillipus** [comment]
In Archi 5.1 beta
