### ISSUE TITLE
Hide relationship connectors in model tree window

### ISSUE THREAD

**Issue by nicobo** [archimatetool/archi#929]
This is somehow the same request as #646 but only to hide relations in the model window, not in the views.

As stated in #646, relations account for most of the size/height of this window and make it uncomfortable each time you want to search concepts using this tree view because you have to scroll A LOT...

It might be enough to let the "Relations" node closed by default (which is currently open by default) ?

**Comment by Phillipus** [comment]
You can hide any of the folder types in the Models Tree since Archi 4.10. See pages 16-17 of the User Guide.

**Comment by nicobo** [comment]
All right ; I'm still on 4.9 that's why, will wait for the admin to install the latest version. Thanks !
