### ISSUE TITLE
ACLI exits after start of HTML report command 

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi#931]
ACLI command for HTML export (from https://devlog.archimatetool.com/2017/07/28/archi-command-line-interface-acli/) is not working (exits at start of the process)

### Version of Archi
5.0.2

### Archi Plug-ins
![image](https://user-images.githubusercontent.com/14212283/235870184-cc4fd852-9e89-4225-9acd-eaad88ad1345.png)

### Operating System
Windows 10

### Expected Behaviour
HTML report generated

### Actual Behaviour
exits at start of the process
no logs available... :(

### Steps to Reproduce the Behaviour
1. run the command Archi -consoleLog -console -nosplash -application com.archimatetool.commandline.app -HTMLReport_InputFile "..." -HTMLReport_OutputFolder "..."
2. console appears... and finaly it puts out the string "g!" and exits...
![image](https://user-images.githubusercontent.com/14212283/235869109-b63a095a-f2cb-45e0-b954-2a7ca84831fb.png)

**Comment by Phillipus** [comment]
The ACLI has changed since that blog post. Please refer to https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface
