### ISSUE TITLE
Unable to resize objects on the edge of the viewport

### ISSUE THREAD

**Issue by nivanson** [archimatetool/archi#932]
### Version of Archi
5.0.2

### Archi Plug-ins
coArchi 0.8.7.202212021111
coArchi Command Line 0.8.7.202212021111

### Operating System
Linux. Debian 12 Bookworm with GNOME 43 on Wayland.

### Expected Behaviour
It should be possible to resize all objects in a view

### Actual Behaviour
Objects on the edge of a viewport are somtimes unable to be resized due to scrollbars overlapping the resize handles.

### Steps to Reproduce the Behaviour
1. Create a new view
2. Put one object on the bottom so that the viewport is expanded
3. Put another object on the right so that the viewport is expanded
4. a) Attempt to resize the bottom object with one of the handles on the bottom of that object or b) Attempt to resize the rightmost object with one of the handles on the right of that object
5. Watch the scrollbars overlap the handles and that you are unable to resize the object

### Workaround
1. Move the object around so that it is no longer near the edge
2. Resize it
3. Move it back

Or use MacOS where this works as expected.

### Example video
See attached video ```Screencast from 2023-05-03 13-50-05.webm```

[Screencast from 2023-05-03 13-50-05.webm](https://user-images.githubusercontent.com/64952/235909783-33bcf9f3-134c-4c4f-a014-bfdc6a7f683a.webm)

**Comment by nivanson** [comment]
Hi @Phillipus. Thanks for the reply.

I have now tried to run it with the GDK_BACKEND=x11 using the Archi.sh script and the issue is still there even when running with X11.

It seems to me as if the issue is not possible to work around by switching to X11.

**Comment by nivanson** [comment]
I found a workaround now in GNOME. Will open a PR to suggest including this in Archi.sh.

```export GTK_OVERLAY_SCROLLING=0```

[Screencast from 2023-05-03 14-20-07.webm](https://user-images.githubusercontent.com/64952/235914121-1c88e693-0911-44f8-ba2b-76b77ea0dfcd.webm)

**Comment by Phillipus** [comment]
> I have searched through the source code but I am unable to find the Archi.sh or any of the contents of that file in the source code of this repository. I don't know how to proceed to open a pull request.

I can add that, no need for a PR.

**Comment by Phillipus** [comment]
Each diagram view has a margin border of 5 pixels on each side. I experimented with changing it to 20 and that allows space for the scrollbar. I might add this as a user preference to set the border.

**Comment by Phillipus** [comment]
This is in Archi 5.1 beta.
