### ISSUE TITLE
Archi crashes when trying to move an object in the default view

### ISSUE THREAD

**Issue by gremodin** [archimatetool/archi#934]
### Version of Archi
Version 5.0.2
Build 202304051112

### Archi Plug-ins
Only the plug-ins provided with the default package

### Operating System
Linux Debian 12 "Bookworm" (x86-64)

### Expected Behaviour
When moving an object in the default view, the application should not crash 

### Actual Behaviour
When moving an object in the default view, the application crashes

Short log when running in command line : 
[Archi_crash.log](https://github.com/archimatetool/archi/files/11525045/Archi_crash.log)

Full log : 
[hs_err_pid171413.log](https://github.com/archimatetool/archi/files/11525038/hs_err_pid171413.log)

There is no error log in the "About Archi" section.

### Steps to Reproduce the Behaviour
1. Open "Archi"
2. Create a new model
3. Create any object, for instance in Technology (the same behavior is observed for all objects, whatever the type and stage)
4. Add it to the default view
5. Try to move it around
6. Archi crashes brutally

###
Hello Everyone,

I wanted to try out Archi, so I installed it, and stumbled almost immediately on this issue.

From what I understand, it would seem like an issue between the JVM and GTK, but I don't understand more than that at this point ;-)

Is it specific to my setup (which is a pretty standard Debian 12 running gnome) or is there something more ?

Any help would be appreciated !

Thanks in advance.

Kind regards.

**Comment by Phillipus** [comment]
Are you using Linux Wayland? If so, please use X11. You can either set it in the system itself or run Archi with the `Archi.sh` script. The key thing here is `export GDK_BACKEND=x11`

**Comment by Phillipus** [comment]
The underlying problems stem from Wayland and SWT (Eclipse Standard Widget Toolkit). Take a look here:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/158

There is a recommendation to use `WEBKIT_DISABLE_COMPOSITING_MODE=1` that might work.

**Comment by gremodin** [comment]
Hello,

Oh... My mistake, then, I thought (wrongly) that running "Archi" called "Archi.sh" in the background... I guess I didn't read all the documentation ;-)

So, not a bug, I checked and it worked !

Thanks a lot for the fast and spot-on help !

**Comment by Phillipus** [comment]
> So, not a bug

Well, not in Archi, at least.

Eclipse SWT needs more fixes to support Wayland, but that's out of my hands.

**Comment by gremodin** [comment]
> > So, not a bug
> 
> Well, not in Archi, at least.
> 
> Eclipse SWT needs more fixes to support Wayland, but that's out of my hands.

That's what I meant. For the time being, you were able to make Archi work nonetheless, so it's kind of a victory, isn't it ?
