### ISSUE TITLE
Model is incompatible cannot open archimate file DOCTYPE html is disallowed

### ISSUE THREAD

**Issue by asgreenb** [archimatetool/archi#937]
### Version of Archi
5.0.0

### Archi Plug-ins
not that I know of beyond the standard installation

### Operating System
Win 10 x64

### Expected Behaviour
Reference architecture file should load once it is opened using file > open > find file > open

### Actual Behaviour
I get the following error popup:
Cannot open 'C:\Users\357300.NVH\Documents\IT4IT_Reference_Architecture-V0.4.archimate'. This model is incompatible.
org.xml.sax.SAXParseExceptionpublicld:
file:/C:/Users/357300.NVH/Documents/IT4IT_Reference_Architecture-V0.4.archimate; systemId: file:/C:/Users/357300.NVH/Documents/IT4IT_Reference_Architecture-V0.4.archimate;
lineNumber: 8; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
(file:/C:/Users/357300.NVH/Documents/IT4IT_Reference_Architecture-V0.4.archimate, 8, 10)

line 8 contains: <!DOCTYPE html>

### Steps to Reproduce the Behaviour
1. Save file "IT4IT_Reference_Architecture-V0.4.archimate" to hard drive from this git: https://github.com/amgadabdelhafez/IT4IT-RA-in-Archi
2. Open Archi
3. File > Open > select file > Open
4. 

The archimate file is attached. I have no error log to download.

thank you
[IT4IT_Reference_Architecture-V0.4.zip](https://github.com/archimatetool/archi/files/11579859/IT4IT_Reference_Architecture-V0.4.zip)

**Comment by Phillipus** [comment]
The attached file is not an Archi model file. It seems to be a HTML file with an *.archimate extension. You probably want this one - https://github.com/amgadabdelhafez/IT4IT-RA-in-Archi/blob/master/IT4IT_Reference_Architecture-V0.4.archimate

**Comment by asgreenb** [comment]
That was it. GitHub error. I right clicked on the file name from the file list (main) page and chose "save link as" instead of saving the raw version of the xml on the file details page.  Thank you
