### ISSUE TITLE
[Feature request] Restrict relationships usage in viewpoints

### ISSUE THREAD

**Issue by fredlegrain** [archimatetool/archi#941]
Nice feature to have better support of viewpoints : allow to restrict relathionships allowed per viewpoints

**Comment by Phillipus** [comment]
Does restricting relationships in a viewpoint make any sense if they are already constrained by the ArchiMate metamodel?

Not showing some relationships in the palette would also mean re-writing the magic connector so it doesn't suggest certain relationships.

**Comment by jbsarrodie** [comment]
Hi,

> Does restricting relationships in a viewpoint make any sense if they are already constrained by the ArchiMate metamodel?

Yes it does in some non trivial cases. For example, if you define a Process viewpoint, you most certainly want to use trigger but not flow.

> Not showing some relationships in the palette would also mean re-writing the magic connector so it doesn't suggest certain relationships.

Yes, makes sense. We might also want to filter suggested relationships when nesting an element.

But IMHO, just hiding relationships from the palette would already be a good step forward with enough added value (could be a MVP)

**Comment by Phillipus** [comment]
> But IMHO, just hiding relationships from the palette would already be a good step forward with enough added value (could be a MVP)

I made a quick check in the code of what needs changing for this and there is some impact. I think I would rather wait until we do a complete make-over of viewpoints.

**Comment by Phillipus** [comment]
I implemented it in `viewpoints-relations` branch supporting palette, magic connector and suggested relationships when nesting an element.

This implementation means you can limit relationships to those declared in the Viewpoint:

```
<concept>AssociationRelationship</concept>
<concept>FlowRelationship</concept>
```

And this to include all relationships:

```
<concept>$AllRelationships$</concept>
```

If neither of those declarations are present, no relationships will show. This will be a problem for people who have created their own viewpoints.

**Comment by Phillipus** [comment]
Actually I think a better way to do this that maintains backward compatibility and fits in with the current implementation, is that if no relationships are declared in the viewpoint then assume all are present. This is how it is currently in the layered viewpoint for elements:

```
<viewpoint id="layered">
    <name xml:lang="en">Layered</name>
    <!-- No concepts means that all concepts are allowed -->
</viewpoint>
```

**Comment by jbsarrodie** [comment]
> Actually I think a better way to do this that maintains backward compatibility and fits in with the current implementation for elements, is that if no relationships are declared in the viewpoint then assume all are present (and no need for `$AllRelationships$`).

Yes, seems the best option.

Would it be possible to add the following options ?
- `$StructuralRelationships$`
- `$DependencyRelationships$`
- `$DynamicRelationships$`
- `$OtherRelationships$`

**Comment by Phillipus** [comment]
> Would it be possible to add the following options ?

Yes. :-)

**Comment by fredlegrain** [comment]
Would it be possible to specify allowed relationships apply per elements?

**Comment by Phillipus** [comment]
> Would it be possible to specify allowed relationships apply per elements?

Not sure what you mean? Please explain.

**Comment by fredlegrain** [comment]
I mean, not define the allowed relationships in general for the viewpoint,
but define down to the relationships allowed betweens specified elements.
Like an actual subset of the the whole elements/relashionships table.

More complex, but matches the actual principle of viewpoints, right?

**Comment by Phillipus** [comment]
No, that's not planned for viewpoints and if you could do this could break the ArchiMate relations rules.
