### ISSUE TITLE
[Feature request] User defined viewpoints, in Archi user files

### ISSUE THREAD

**Issue by fredlegrain** [archimatetool/archi#942]
Some companies don't allow modifying the program files, of which the viewpoints.xml.

Might be interesting to allow user defined viewpoints, defined in a viewpoints.xml stored in user files.

**Comment by Phillipus** [comment]
We discussed this elsewhere (can't remember if it was here or on the forum) but if user defined viewpoints are stored in an external file, the model file is no longer portable. So they would have to be defined in the `*.archimate` file to be truly portable, and then that would mean they would have to be re-defined for each model.

**Comment by fredlegrain** [comment]
Why not make it 2 files, one in the program files, one in the user files.
I see no specific need to have that "portable" or embedded in the model.
Script, for instance, are not portable, but really useful though.

**Comment by Phillipus** [comment]
> I see no specific need to have that "portable" or embedded in the model.

Except when someone else opens a model with a reference to a viewpoint "my-viewpoint" and it can't be found. A proper implementation of a viewpoint would also define more than just concept constraints, for example the intent of the viewpoint, the target audience, guidelines, etc

See also https://github.com/archimatetool/archi/issues/833
