### ISSUE TITLE
Specializations Manager issue with sorting new specializations

### ISSUE THREAD

**Issue by CzechM8** [archimatetool/archi#945]
### Version of Archi

5.1.0 (but bug has been experienced since version 4.x)

### Archi Plug-ins

CoArchi
jArchi
Lightbox
Excel

### Operating System

Mac OS 13.4.1

### Expected Behaviour

When creating new specializations, after typing in the name of the specialization, the user can hit the tab key to go to the next entry field - the "restricted to element" entry, and then select the appropriate element from the dropdown. Then hit enter to save the new specialization.

### Actual Behaviour

When the specializations manager is opened and the new button is clicked, the user can type in the name of the new specialization. Then the user hits the tab key to enter the appropriate element. Here the dropdown is visible on an existing specialization - not the in-progress one. This is because the specialization has already been alphabetically sorted, but the dropdown list is still at the bottom of the window. If the sorting would be delayed until after the new specialization has been saved, this would likely be fixed.

### Steps to Reproduce the Behaviour
1. Start with a fairly long list of existing specializations
2. Open Specializations Manager
3. Click 'New'
4. Give the new specialization a name
5. Hit TAB key or click to go to select the next column.
6.  Notice the new specialization has already move and the dropdown is on the wrong line.

**Comment by Phillipus** [comment]
I think this is happening because when you rename the Specialization, the sort order is refreshed as it's sorted again. I'll see if I can improve that.

**Comment by CzechM8** [comment]
Cool. Yes, it does this for a new specialization or during renaming one.
Also, going straight to the save button causes the "restricted to" element
to *not* be updated (it saves with the default Business Actor element). You
have to first click away from the "restricted to" element after you've
selected the one you want, and then click save.  It works great if you hit
enter twice - once to select from the dropdown and then the second enter
key saves the specialization. It's actually a different bug/issue.

Thanks, Phil.

**Comment by Phillipus** [comment]
> You have to first click away from the "restricted to" element after you've
selected the one you want, and then click save.

This is a known problem with these combo boxes to make the entry "stick", or pressing enter can make it stick.

**Comment by CzechM8** [comment]
Gotcha! Thanks, Phil.

**Comment by CzechM8** [comment]
That would be great, as I am a big user of this feature.

Thanks, Phil!

Les

**Comment by Phillipus** [comment]
Fixed in Archi 5.1 beta 2.

**Comment by CzechM8** [comment]
Thanks, Phil!
