### ISSUE TITLE
[FEATURE REQUEST] Enterprise Risk and Security Management Elements

### ISSUE THREAD

**Issue by elislusarczyk** [archimatetool/archi#949]
This is a request to add risk and security architecture elements to the Archi tool. Archimate doesn't support any security architecture and I saw that chaps from Bizzdesign created their own version of ERSM shown in the below link.

https://support.bizzdesign.com/display/knowledge/Elements+for+ERSM+modeling

This feature request is to ask to add those elements (perhaps as a plugin as the Bizzdesign elements are not in the standard) to Archi Tool.

Please let me know your thoughts on this request.

**Comment by Phillipus** [comment]
These elements are specializations of existing ArchiMate elements. You can create specializations in Archi.
