### ISSUE TITLE
Problem with CLI to persist data after CSV Import

### ISSUE THREAD

**Issue by francfa** [archimatetool/archi#950]
### Version of Archi
5.01

### Archi Plug-ins
None

### Operating System
Windows

### Expected Behaviour
I submit the following CLI commands
Archi.exe -application com.archimatetool.commandline.app -consoleLog -nosplash --loadModel file.archimate --pause  --csv.import folder_import --saveModel file.archimate

### Actual Behaviour
The console provide successful operations
[Core] Loaded model: 'xxx'
[CSV] Importing csv from folder_import to 'xxx'
[CSV] CSV Imported!
[Core] Saved model to 'file.archimate'

But when I open Archimate via GUI I don't fine the imported objects.

If I do the same manually via GUI Import CSV functionality the items are imported correctly.

### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
I tested this and it's working for me.

Here's my command:

```Archi.exe -application com.archimatetool.commandline.app -consoleLog -nosplash --loadModel Users/phillipus/Desktop/file.archimate --csv.import /Users/phillipus/Desktop/elements.csv --saveModel /Users/phillipus/Desktop/file.archimate```

Ensure that the path to the .archimate file is a full path and also that the `--csv.import` argument references an `elements.csv` file.

**Comment by francfa** [comment]
Thanks! I understood in parallel tat I was missing the element.csv in the path. It is essential but counter-intuitive, because in the symmetics export functionality you just need to provide the folder and not the file.

Now have been fixed. 

Tks a lot Philipus

**Comment by Phillipus** [comment]
> It is essential but counter-intuitive, because in the symmetics export functionality you just need to provide the folder and not the file.

No, because when importing you can specify `elements.csv`, "relations.csv` or `properties.csv` as input files.
