### ISSUE TITLE
The Hints pane does not follow the MacOS dark theme

### ISSUE THREAD

**Issue by heikkil** [archimatetool/archi#951]
### Version of Archi

5.1.0, also present at least in the version 5.0.2

### Operating System

MacOS Ventura 13.4
 
### Expected Behaviour

All panes follow the system theme in their colour. 

### Actual Behaviour

The Hints pane has the default light theme even when all the other Archi window panes follow the system dark theme.

### Steps to Reproduce the Behaviour
1. Switch the MacOS appearance to dark from the Control Panel. 
2. Launch Archi
3. Make  the Hints pane visible

<img width="521" alt="Screenshot 2023-08-09 at 20 51 03" src="https://github.com/archimatetool/archi/assets/75674/f3f2bc0f-0e48-41c4-bcde-04e6fc74decb">

**Comment by Phillipus** [comment]
The Hints pane is actually an embedded browser component and so is not theme aware, as it is displaying HTML content. So won't be able to change this.

**Comment by Phillipus** [comment]
> So won't be able to change this.

Having said that, I have made some experiments of injecting some additional CSS values into the HTML via JavaScript when loading the hint HTML text to give a dark background and light text. So it may be possible with the caveat that the Archi Preference "Enable JavaScript in Hints" has to be enabled and there is a slight flicker when rendering the HTML (white background changing to dark).

**Comment by Phillipus** [comment]
I've implemented this now. As I said aove, the Archi Preference "Enable JavaScript in Hints" has to be enabled and there is a slight flicker when rendering the HTML (white background changing to dark).
