### ISSUE TITLE
As a User I want to be able to use "Save as" on startup

### ISSUE THREAD

**Issue by relascope** [archimatetool/archi#954]
[minor issue]

Start Archi 
Create or load a model
Close Archi

Start Archi
Archi automatically loads the last model
"Save as" is deactivated (observed behaviour)

Expected behaviour
"Save as" is enabled

**Comment by Phillipus** [comment]
"Save As..." is enabled when a model has the focus in the Models Tree or in one of its Views.

**Comment by relascope** [comment]
Shouldn't then be the model preselected?

**Comment by Phillipus** [comment]
> Shouldn't then be the model preselected?

No, there might be no models open, or more than one.
