### ISSUE TITLE
[Feature Request] Technology Evolution Tracker

### ISSUE THREAD

**Issue by krisrr3** [archimatetool/archi#957]
Technology enterprises are constantly evolving, and it is hard to keep track of all past, current and future modernization initiatives in a relatively automated manner. Leaders who need to understand historical decisions need the information pretty quickly and it can be a humongous task due to the information being scattered and attrition. 

The reasons that make it important to keep track of the technology evolution of an enterprise in one tool

1. understand history of an enterprise
2. understand the outcome of previous investments and better predict future outcomes
3. reduce the risk of reducing momentum due to unclear prior decisions during leadership change
4. engage engineering and management community on the evolution journey

I am proposing to develop a plugin (with community support) to aggregate data from various sources and create views in Archimate that will be relevant to various stakeholder levels.

![image](https://github.com/archimatetool/archi/assets/1826315/ff26e39e-5b89-4cd4-8fda-5cf7c2cb819c)

Keen to get initial feedback and understand if this is worthwhile implementing.

**Comment by Phillipus** [comment]
> Keen to get initial feedback and understand if this is worthwhile implementing.

Hi, thanks for your summary of your aim.

If you want feedback on this idea you probably should set up your own space for the project (perhaps a GH repo) and then point folks to it so they can feed back on your ideas/sketches/etc. You could also ask for user feedback on the [Archi Forum](https://forum.archimatetool.com/index.php?board=7.0).

> I am proposing to develop a plugin...to aggregate data from various sources and create views in Archimate that will be relevant to various stakeholder levels.

You might be able to do that with [jArchi](https://github.com/archimatetool/archi-scripting-plugin), or at least prototype it in jArchi.

**Comment by krisrr3** [comment]
Thanks for the reply Phil.

I will do some research on JArchi. But would you be able to point me to a documentation on getting started with Plugin Architecture and Development 101.

Also will post it on the forum.

**Comment by Phillipus** [comment]
> But would you be able to point me to a documentation on getting started with Plugin Architecture and Development 101.

https://github.com/archimatetool/archi/wiki/Developer-Documentation

**Comment by krisrr3** [comment]
thanks ....I read it before, was hoping there was an archetype (Maven Archetype) :-)...let me follow it in the next few weeks.

fyi...posted it here - https://forum.archimatetool.com/index.php?topic=1412.0

**Comment by Phillipus** [comment]
I'll close the issue here because it's neither a bug report or a feature request that I will implement. Hope you get some feedback on the forum and elsewhere.
