### ISSUE TITLE
macOS Sonoma issues

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#962]
A heads up about issues in macOS Sonoma due to be released September 26 2023:

- Splash screen is inverted (actually all background images in Eclipse SWT) - see https://github.com/eclipse-platform/eclipse.platform.swt/issues/772

- Application name is "NewApplication" - see https://github.com/eclipse-platform/eclipse.platform.swt/issues/779

- Cursor doesn't change to default cursor when displaying a context menu - see https://github.com/eclipse-platform/eclipse.platform.swt/issues/773

- Probably other issues not found yet

As the cause of each of these issues is in either macOS and/or Eclipse SWT I can't do anything about this.

**Comment by Phillipus** [comment]
The "NewApplication" is fixed in Sonoma 14.1 (and a workaround is in Eclipse 4.30)

I have a workaround for the inverted splash screen for Archi 5.2.

**Comment by poppason** [comment]
Hi! Phillipus,

Sorry for the delay and not being familiar with the "Archi" jargon.  I'm just a user of the OpenCore Legacy patcher that is experiencing the "MacBook Pro 11,5 will not boot up following the Sonoma 14.1 installation.  The boot progress bar hangs at 25%.  Please advise.

**Comment by Phillipus** [comment]
> Sorry for the delay and not being familiar with the "Archi" jargon. I'm just a user of the OpenCore Legacy patcher that is experiencing the "MacBook Pro 11,5 will not boot up following the Sonoma 14.1 installation. The boot progress bar hangs at 25%. Please advise.

This has got nothing to do with the Archi software.

**Comment by Phillipus** [comment]
This is in Archi 5.2.
