### ISSUE TITLE
the ability to transfer text to the next line in the name of elements and arrows

### ISSUE THREAD

**Issue by nikolay-kochubashev** [archimatetool/archi#963]
Thank you for developing such a thoughtful, functional tool!
Can you implement the ability to transfer text to the next line in the name of elements and arrows?

**Comment by Phillipus** [comment]
Not sure what you mean exactly. But you can use [Label Expressions](https://github.com/archimatetool/archi/wiki/Label-Expressions) to fine tune the names.

**Comment by nikolay-kochubashev** [comment]
Thank you for your suggestion.
I mean a line break in text (carriage-return).

For example I want to type text like this:
```
O’er all the hilltops
Is quiet now,
In all the treetops
Hearest thou
Hardly a breath;
```

But I can it just so:
`O’er all the hilltops Is quiet now, In all the treetops Hearest thou Hardly a breath;`

**Comment by Phillipus** [comment]
Paste that text into the label expression and it will render like that.

**Comment by nikolay-kochubashev** [comment]
It was not obvious that Label Expression supports formatting, and input directly into the name does not support.

It will be good if you can immediately enter text with line separation in the title, for example, using the Alt + Enter or Shift + Enter key combination

Anyway thank you a lot for help!
