### ISSUE TITLE
Node can't Realize another node (Technology metamodel)

### ISSUE THREAD

**Issue by skjmodelfirst** [archimatetool/archi#964]
In the Archimate technologi metamodel a Node can realize another Node.
See https://pubs.opengroup.org/architecture/archimate31-doc/chap10.html

In Archi's Archimate Relationships table the "r" is missing in the Node /Node cell  

### Version of Archi
5.1.0

### Operating System
Windows 

### Expected Behaviour
It should be possible to create a Realization connection between to Nodes in the technology layer

### Actual Behaviour
It's not possible to create a Realization connection between to Nodes in the technology layer

### Steps to Reproduce the Behaviour
1. Create two Node
2. try to connect the two nodes with a Realization connection
3.

**Comment by Phillipus** [comment]
Hi, the document you reference is for ArchiMate 3.1. Archi implements ArchiMate 3.2:

https://pubs.opengroup.org/architecture/archimate32-doc/ch-Technology-Layer.html

**Comment by Phillipus** [comment]
I'll close this one.
