### ISSUE TITLE
[improvement] position of the pasted element in view

### ISSUE THREAD

**Issue by fredlegrain** [archimatetool/archi#965]
When copy-pasting an element within a view, the pasted element appears at a kind-of random position in the view, often far away from the original element, or from the display frame.

Would be greate to ensure that the pasted element appears at a predictable position, like near the selected element, or within the display frame (when no element is selectd).

**Comment by Phillipus** [comment]
The pasted position will be based on the last mouse clicked position. Before pasting, click on the View where you'd like it pasted.
