### ISSUE TITLE
[Feature Request] Order commands in toolbar

### ISSUE THREAD

**Issue by Yame12** [archimatetool/archi#966]
Hi, 

I am missing the order commands (bring forward/front, send backward/back) in the toolbar. This would be more efficient if elements need to forward/backward multiple times in a row, instead of right click > order > ... This doesn't happen often, but then it's annoying ;-)

![image](https://github.com/archimatetool/archi/assets/124377468/c1aeb2f8-1c36-421c-b5e7-15798a9c2801)

Is it possible to add these commands?

Cheers,
Enrico

**Comment by Phillipus** [comment]
Hi, no plans to put these on the toolbar, as these are less common commands.

**Comment by Yame12** [comment]
I agree, it's probably less used - on the other side there is enough space and it would add some consistency. Alternatively, is it possible to bind to keys?

**Comment by Phillipus** [comment]
Key bindings are now supported in Archi 5.4
