### ISSUE TITLE
Feature request: ASPX for HTML Reports

### ISSUE THREAD

**Issue by AlbertoDMendoza** [archimatetool/archi#969]
Following up on [topic 1429](https://forum.archimatetool.com/index.php?topic=1429), it would be great to export the HTML report but with ASPX extension instead.   

This is a workaround due to limitations imposed by SharePoint Online on JavaScript to 1) not allow custom scripts  2) if enabled, only allow custom scripts to certain file extensions.  This workaround is to address point 2. 

Background:
SharePoint makes a differentiation between site scripts ([json based actions](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview?source=recommendations#anatomy-of-a-site-script)) and custom scripts. JavaScript falls under custom scripts, and custom scripts can only be executed by custom pages.  Per Microsoft's security recommendation, the default is to not allow custom scripting in SharePoint sites as (rightfully so) a rogue script have security implications, so there's a level of risk and security a site admin must be willing to accept by enabling this. For more background read [this](https://learn.microsoft.com/en-us/sharepoint/security-considerations-of-allowing-custom-script) and [this](https://blog.mastykarz.nl/inconvenient-no-script-sites-sharepoint-framework/), and [this](https://chuvash.eu/2019/11/06/is-custom-script-dangerous/).  

For those willing to accept the risks: 
1) Enable custom scripts by enabling custom pages, follow this: https://learn.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script#to-allow-custom-script-on-other-sharepoint-sites

2) Once custom scripts are enabled, only certain file extensions are allowed to execute them, ASPX being one of them. See:  
[this](https://support.office.microsoft.com/en-us/article/types-of-files-that-cannot-be-added-to-a-list-or-library-30be234d-e551-4c2a-8de8-f8546ffbf5b3)

This request is to have an option on Archi to use .ASPX instead of .HTML within files and references in the HTML Report for it to work with Sharepoint.

**Comment by AlbertoDMendoza** [comment]
I was afraid something like this would get in the way. Honestly the [single page jArchi script](https://github.com/archi-contribs/jarchi-single-page-html-export) is a better solution, but it's missing features like deeplinks and alasql, I though this would be an easier workaround to implement natively than to add extra features to the script. Thanks for the quick reply.

**Comment by DavidLowBHA** [comment]
Just adding a vote for this functionality as it would assist in sharing this information internally with our Organisation.

I have got it to run in a SharePoint embed webpart using an extension rename and then doing an internal file rename of html to aspx and does work ok. Main issue is I lose the zoom controls that can come in handy when looking at larger views.

**Comment by Phillipus** [comment]
> Just adding a vote for this functionality as it would assist in sharing this information internally with our Organisation.
> 
> I have got it to run in a SharePoint embed webpart using an extension rename and then doing an internal file rename of html to aspx and does work ok. Main issue is I lose the zoom controls that can come in handy when looking at larger views.

We've already said in the comment above that you can post-process the report by renaming the files and links to `.aspx`. If parts of the report are not working after that the reason is clear - the usage is not supported.
