### ISSUE TITLE
Label Expressions: <relationship>: expression only seems to work with relationships in View

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi#970]
I'm not sure whether this is a bug or a conscious design restriction but 

### Version of Archi
5.0.2

### Archi Plug-ins
Yes - all but not relevant

### Operating System
Windows

### Expected Behaviour
I would like (had expected) that the following label expression would work in all circumstances where the relationship exists:
${name}
($assignment:target{name})

### Actual Behaviour
Instead it only works when the relationship is present in the View (in which case, it isn't needed!)
### Steps to Reproduce the Behaviour
Just create the following model fragment - toggle the SystemSoftware in & out of the view.
![Label Bug](https://github.com/archimatetool/archi/assets/33519378/65f1a9b1-ac3b-4276-89d2-28a038f5f7cf)

**Comment by Phillipus** [comment]
Hi, yes that's the expected behaviour.

**Comment by lavenderb** [comment]
Thanks for your quick reply PhilI guess there must be a good reason why it is this way? If you can also see why model scope would be useful, pls add it to the wish list 🙂Sent from my iPhoneOn 7 Oct 2023, at 12:05, Phil Beauvoir ***@***.***> wrote:﻿
Hi, yes that's the expected behaviour.

**Comment by Phillipus** [comment]
Hi, the label expressions have always worked on a per view basis, so that you can have different label expressions for each context.

**Comment by lavenderb** [comment]
All clear, thanks Phil
I’d understood that the label could be used to show different text in different views, but it is obviously goes deeper than that
I’ll use scripting instead 😊

**Comment by Phillipus** [comment]
I opened https://github.com/archimatetool/archi/issues/972 so I'll close this one.
