### ISSUE TITLE
Label Expressions - add msource and mtarget expressions

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi#972]
There seems to be a need from some users to access source and target of relations at the model level rather than the visual connection level. See

https://forum.archimatetool.com/index.php?topic=1432.0
https://github.com/archimatetool/archi/issues/970
https://github.com/archimatetool/archi/issues/713

Perhaps we could add `msource` and `mtarget` expressions to get the model objects? I have actually written the code to do this sometime ago.

@jbsarrodie WDYT?

**Comment by jbsarrodie** [comment]
I've had a need for this some time ago, so it's worth having a look at it.

> Perhaps we could add `msource` and `mtarget` expressions to get the model objects?

I wonder if we actually need dedicated expressions for that or if the existing `source` and `target` could be extended: when getting the list of relationships matching the criteria, we could make sure we have those shown on the view first, and those coming from the model after. As we pick the first one to render expression, this doesn't change anything for currently supported use-case.

BTW, I have a small list of enhancements to label expressions, maybe I could do it for the upcoming version of Archi.

**Comment by Phillipus** [comment]
> I wonder if we actually need dedicated expressions for that or if the existing source and target could be extended: when getting the list of relationships matching the criteria, we could make sure we have those shown on the view first, and those coming from the model after. As we pick the first one to render expression, this doesn't change anything for currently supported use-case.

Good idea.

But why check for view connections first, why not just check model relationship in all cases? If the view connection exists then it will be the same as the model relationship. If not, it will also be the model relationship.

**Comment by Phillipus** [comment]
> But why check for view connections first, why not just use model relationship in all cases? If the view connection exists then it will be the same as the model relationship. If not, it will also be the model relationship.

Ignore that. We need to check for plain "connection" type before archimate types anyway.

**Comment by Phillipus** [comment]
I've implemented this in branch `label-expressions` now. Will use the model relationship if there are no diagram connections.

**Comment by Phillipus** [comment]
This is in Archi 5.2.

**Comment by romualdrichard** [comment]
Hi,

Sorry about that, I tried this and I certainly messed somewhere.
With $association:source{name} I have "Feuille de temps" on the flow relation even if the Data Object is not in the view
With $serving:source{name} I have nothing
![Capture d’écran 2024-01-04 160752](https://github.com/archimatetool/archi/assets/48156053/b6e8b07e-a33f-41b4-b858-3eb3b42de032)
