### ISSUE TITLE
Possible Junction Bug

### ISSUE THREAD

**Issue by ewalters99** [archimatetool/archi#976]
### Version of Archi

5.1.0

### Archi Plug-ins

Collaboration
 
### Operating System

windows 10

### Expected Behaviour

Trying to use a Junction to indicate a Product aggregates either Artefact OR Material. Product to Junction the connection is fine, but it appears that Archi wont allow an aggregation connection from the Junction to Artefact or Material
### Actual Behaviour

Aggregation connection from Junction to Artefact or Material is prohibited. 

### Steps to Reproduce the Behaviour
1. Place a Product, an Artefact and a Material on the canvas. Place a Junction. Draw an aggregation relationship from the Product to the Junction.
2. Try to create an aggregation relationship from the Junction to either the Artefact or the Material. You will see it is prohibited.
3.

**Comment by Phillipus** [comment]
Hi, you can however create an Aggregation from the Artefact or Material to the Junction.

**Comment by ewalters99** [comment]
Yes, but that doesn’t have the same meaning – the diamond end is the ‘whole’ the other end is the ‘part’

 

Regards

 

Ed Walters

Consultant, Business Systems Development

 ***@***.***> ***@***.***

+ 44 (0) 7786 444 372

 

Please note: I am in the process of switching my main personal email address to  ***@***.***> ***@***.***

However I will still be processing emails received at  ***@***.***> ***@***.*** for some time yet.

**Comment by ewalters99** [comment]
The ‘direction’ of aggregation is from the whole to the part.

 

Regards

 

Ed Walters

Consultant, Business Systems Development

 ***@***.***> ***@***.***

+ 44 (0) 7786 444 372

 

Please note: I am in the process of switching my main personal email address to  ***@***.***> ***@***.***

However I will still be processing emails received at  ***@***.***> ***@***.*** for some time yet.

**Comment by Phillipus** [comment]
@jbsarrodie HI JB, can you confirm? Thanks, Phil

**Comment by ewalters99** [comment]
The same rule will apply to Composition of course. I haven’t tried this out though.

 

Regards

 

Ed Walters

Consultant, Business Systems Development

 ***@***.***> ***@***.***

+ 44 (0) 7786 444 372

 

Please note: I am in the process of switching my main personal email address to  ***@***.***> ***@***.***

However I will still be processing emails received at  ***@***.***> ***@***.*** for some time yet.

**Comment by Phillipus** [comment]
The relationship rules that Archi uses are declared in an XML file [here](https://github.com/archimatetool/archi/blob/master/com.archimatetool.model/model/relationships.xml). It declares the relationships allowed between source and target concepts.

(a = Access, c = Composition, f = Flow, g = Aggregation, i = Assignment, n = Influence, o = Association, r = Realization , s = Specialization t = Triggering, v = Serving)

If we look at the rules from Junction to Artefact and Material we see:

```xml
<source concept="Junction">
    <target concept="Artifact" relations="aior" />
    <target concept="Material" relations="aior" />
</source>
```

From Artefact to Junction:

```xml
<source concept="Artifact">
    <target concept="Junction" relations="acfginorstv" />
</source>
```

From Material to Junction:

```xml
<source concept="Material">
    <target concept="Junction" relations="acfginorstv" />
</source>

So, according to those rules provided by The Open Group, the relationships you are trying to create are not allowed.

**Comment by ewalters99** [comment]
Hi Phil,

 

I see, thank you for the info. 

 

Obviously Archi has to implement the rules, so it’s the rules that might need changing. I cc JB and Marc to see if they agree.

 

@JB and Marc: any reason why aggregation and composition were not included here?

 

<source concept="Junction">
    <target concept="Artifact" relations="aior" />
    <target concept="Material" relations="aior" />
</source>

 

Regards

 

Ed Walters

Consultant, Business Systems Development

 ***@***.***> ***@***.***

+ 44 (0) 7786 444 372

 

Please note: I am in the process of switching my main personal email address to  ***@***.***> ***@***.***

However I will still be processing emails received at  ***@***.***> ***@***.*** for some time yet.

**Comment by ewalters99** [comment]
That is because junctions themselves can be aggregated in composite elements like Grouping. Allowing junctions on compositions or aggregations would become ambiguous if the other end of the composition is such a composite element.

Marc
________________________________
Van: ***@***.*** ***@***.***>
Verzonden: Saturday, October 14, 2023 1:55:31 PM
Aan: 'archimatetool/archi' ***@***.***>
CC: ***@***.*** ***@***.***>; Marc Lankhorst ***@***.***>
Onderwerp: RE: [archimatetool/archi] Possible Junction Bug (Issue #976)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Phil,



I see, thank you for the info.



Obviously Archi has to implement the rules, so it’s the rules that might need changing. I cc JB and Marc to see if they agree.



@JB and Marc: any reason why aggregation and composition were not included here?



<source concept="Junction">

    <target concept="Artifact" relations="aior" />

    <target concept="Material" relations="aior" />

</source>



Regards



Ed Walters

Consultant, Business Systems Development

***@***.******@***.***>

+ 44 (0) 7786 444 372



Please note: I am in the process of switching my main personal email address to ***@***.******@***.***>

However I will still be processing emails received at ***@***.******@***.***> for some time yet.

**Comment by Phillipus** [comment]
> That is because junctions themselves can be aggregated in composite elements like Grouping. Allowing junctions on compositions or aggregations would become ambiguous if the other end of the composition is such a composite element.
>
> Marc

OK, I'll close this.
