### ISSUE TITLE
Creating HTML report with CLI

### ISSUE THREAD

**Issue by oozpostaci** [archimatetool/archi#980]
Hello , 
I am using the following code to produce html report :
Archi -application com.archimatetool.commandline.app -consoleLog -nosplash  --modelrepository.cloneModel https://xxxx/kurumsal_mimari_modeli.git --modelrepository.loadModel /model/  --modelrepository.userName  xxxx --modelrepository.passFile c:\dosya\dosya.txt --html.createReport c:\archi4\ -p

if elements have property then command gives an error :

context [/modelreport /expandFolder /_sub1 /expandFolder /_sub1 /expandFolder /_sub2 /classesFromProperties /_sub3] 1:25 no such template: /IGNORE_ERROR_
[HTMLReport] Report generated!

After this error index.html file size is 0 so I cant see report. 

can you help me ? 
Thanks

**Comment by Phillipus** [comment]
This can happen if there is a blank property (no value) in the model. The report should still work, though.

**Comment by oozpostaci** [comment]
thank you very much for fast reply.
