### ISSUE TITLE
[Feature Request] Infinite Canvas

### ISSUE THREAD

**Issue by bkyle** [archimatetool/archi#986]
It would be nice to be able to scroll the canvas for all diagram types beyond the bounds of the elements in a diagram so that I can place elements in far-off positions without having to adjust the zoom level.

**Comment by Phillipus** [comment]
It's a limitation of the Eclipse GEF/Draw2d framework. Sorry!

**Comment by lvmm** [comment]
Is it possible to extend the diagram while dragging so that the element being dragged stays visible and the diagram can be extended infinitely, not in small blind steps? It can be done, Capella works this way.

**Comment by Phillipus** [comment]
You can click on an element and hover the mouse near the edge of the viewport and it will scroll into view. It's built into GEF [here](https://github.com/archimatetool/archi/blob/master/org.eclipse.gef/src/org/eclipse/gef/editparts/ViewportAutoexposeHelper.java)

**Comment by lvmm** [comment]
Doesn't work for me on 5.3.0. When I move mouse pointer over the edge of the viewport while dragging, the dragging of (now invisible) element continues - I can see the scrollbars moving, but only until I hit the edge of the screen, and there isn't much space at all, especially in the fullscreen mode.

**Comment by lvmm** [comment]
Oh, NEAR the edge - yes, there is indeed a zone where it starts expanding. But it is so narrow - just one grid step, 5 pixels... hard to hit and even harder to stay there especially when using a touchpad. I was thinking about 'keep on expanding as long as the pointer is outside' behaviour.
