### ISSUE TITLE
MacBook Pro 11,5 won't boot up following 14.01 upgrade; progress bar stuck at 25 %

### ISSUE THREAD

**Issue by poppason** [archimatetool/archi#989]
### Steps to Reproduce the Behaviour
1.
2.
3.

**Comment by Phillipus** [comment]
Hi, please provide the details requested in the issues template.

You can also try re-downloading Archi and re-installing.

**Comment by Phillipus** [comment]
As Archi doesn't have a progress bar and as you say "MacBook Pro 11,5 won't boot up" I'll close this as a non Archi issue. If you do have a problem starting Archi please provide the exact details to reproduce the problem.
