### ISSUE TITLE
PDF export loses gradient

### ISSUE THREAD

**Issue by nickbrownapollo** [archimatetool/archi#992]
Not sure if this an actual bug or a "feature". When I export a view to PDF, any gradient that I have applied to the appearance of elements is lost.

**Comment by Phillipus** [comment]
Sorry, this is a limitation of the SVG and PDF export code. We use some [third-party code](https://github.com/archimatetool/archi/blob/master/com.archimatetool.export.svg/src/com/archimatetool/export/svg/graphiti/GraphicsToGraphics2DAdaptor.java) for this and it has some limitations.

We mention this in several places in the User Guide:

> Note - gradients will not show when a diagram is exported in SVG image format.
