### ISSUE TITLE
[Feature Request] Auto Save function

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi#999]
As Archi is a "traditional" desktop application, I find myself every once in a while losing changes I have made upon a system crash.  Is there a possibility of looking at some kind of "autosave" function, option to save every X minutes (if a change has been made)?

**Comment by Phillipus** [comment]
Hi, this has come up before:

https://github.com/archimatetool/archi/issues/816
https://github.com/archimatetool/archi/issues/667

In my tests, auto-save is technically possible but there is a possibility of a collision and a model might get corrupted, I don't want to risk it. So, I'll close this one, sorry.
